### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by malicious50** [AHAAAAAAA/PokemonGo-Map#10]
Getting this error:
![cattura](https://cloud.githubusercontent.com/assets/11940908/16901104/bb09eb3c-4c39-11e6-8a3a-3c48848c65da.PNG)

**Comment by dosenhosenjoe** [comment]
thats because pokemon club is down

**Comment by BrodrickChilds** [comment]
Ah I was wondering if they'd updated the API to not include heartbeat to discourage projects like this one... Good to know that's not the case :P

**Comment by mattmmeloan** [comment]
Yeah I think that's the case too. Just needs better exception handling.

**Comment by marauder37** [comment]
Code was just merged to fix this

**Comment by malicious50** [comment]
Works. Closing this.

**Comment by malicious50** [comment]
That problem seems fixed, even if getting a lot of
[-] retrying_api_req: request error (('Connection aborted.', BadStatusLine("''",
))), retrying
[-] retrying_api_req: request error (('Connection aborted.', BadStatusLine("''",
))), retrying
[-] retrying_api_req: request error (('Connection aborted.', BadStatusLine("''",
))), retrying
[-] retrying_api_req: request error (('Connection aborted.', BadStatusLine("''",
))), retrying
[-] retrying_api_req: request error (('Connection aborted.', BadStatusLine("''",
))), retrying
[-] retrying_api_req: request error (('Connection aborted.', BadStatusLine("''",
))), retrying
[-] retrying_api_req: request error (('Connection aborted.', BadStatusLine("''",
))), retrying

now, but I guess because of servers overload. Thanks!
