### ISSUE TITLE
Output to X instead of memory

### ISSUE THREAD

**Issue by Trozz** [AHAAAAAAA/PokemonGo-Map#100]
Currently PokemonGo-Map stores all data within memory, having the ability to save to some form of Database could help low memory systems or systems running multiple 'walkers'

**Comment by favll** [comment]
The high memory usage is due to a bug. This issue is related to #51 and #87. I'm currently running a fix that uses 38.4 MB RAM for 10^2=100 steps. After the bug is fixed, there should be no problem running multiple instances of this project on a low memory system.

**Comment by JZ6** [comment]
fixed
