### ISSUE TITLE
Using geolocation on mobile

### ISSUE THREAD

**Issue by alxsah** [AHAAAAAAA/PokemonGo-Map#1002]
I'm wondering if it would be possible to implement geolocation to track the user's location. I'm not currently concerned with making the scan radius follow the user, but for now simply updating the location of the marker and centering the map around the user.

Any thoughts / advice on how to go about this?

**Comment by DanielSiepmann** [comment]
Had same idea and implemented in #1020 with a toggle option to center map or not.

Must have feature for a bike ride ;)

**Comment by megahambone** [comment]
I implemented this in #725 yesterday, but sure.

**Comment by alxsah** [comment]
Didn't notice the above - thanks, I'll close this.
