### ISSUE TITLE
Map stops refreshing after awhile(all Pokemon disappear and doesn't find any new ones)

### ISSUE THREAD

**Issue by emilylcook** [AHAAAAAAA/PokemonGo-Map#1003]
The application seems to run as expected for awhile, pokemon appear and I can see their time remaining and stale pokemon remove on refresh and new ones appear.  But after awhile new pokemon stop appearing and the existing ones all die out and my map is left blank

## Expected Behavior
Pokemon keep appearing and refreshing

## Current Behavior
Pokemon stop appearing and map is blank

## Possible Solution
?

## Steps to Reproduce (for bugs)
1) run application
example.py -a ptc -u ########### -p #### -l "lat lon" -st 10 -ar 5 
2) wait 10-15 minutes and pokemon stop showing up

## Context
Trying to catch pokemon, can't find them

## Your Environment
Windows 10.1
Python 2.7.12
Accessing from desktop or mobile

**Comment by neuroaktivo** [comment]
+1 on windows 8 same python i believe, it may be more than that time the thing is it stops working. maybe it is after the first loop iteration.

**Comment by Galtwise** [comment]
Master is no longer supported. Move to develop branch
