### ISSUE TITLE
Scan Inaccurate

### ISSUE THREAD

**Issue by macgngsta** [AHAAAAAAA/PokemonGo-Map#1004]
## Expected Behavior
Expect scan to be completed in a square like bounds around the current point

## Current Behavior
Scan seems to favor top right 
- errors did seem to occur on the scan as well `[  ERROR] Scan step failed. Response dictionary key error.`

## Possible Solution
I will give the hexagon spiral a try #776 

## Steps to Reproduce (for bugs)
1. scan for `-l "37.781679,-122.408866" -st 3`
2. see map

## Context
Noticed that while scanning my area that some pokestops were missing. So I tried the same scan on a denser area with more pokestops

## Your Environment
* Version used: dev d0a46b4
* Environment name and version (e.g. Python 2.7): Python 2.7.12
* Operating System and version (desktop or mobile): Mac OS X 10.10.5

![sf_scan](https://cloud.githubusercontent.com/assets/1333829/17035425/0994c4c0-4f3c-11e6-8ff1-8d797bc0a6b9.jpg)

[scanLog.txt](https://github.com/AHAAAAAAA/PokemonGo-Map/files/376771/scanLog.txt)

**Comment by Maxincredible52** [comment]
i also get pokestops all over the place ... pokemon are scanned in a rectangle

**Comment by medghaim** [comment]
Closing this issue as it is outdated. If this issue still persists on the `develop` branch, please reopen a new issue and update the information therein to reflect the new changes.

Also, please be aware of the incredibly helpful and supportive community at: 
https://discordapp.com/invite/Kzp4yky
