### ISSUE TITLE
Time until expires wrong

### ISSUE THREAD

**Issue by haqthat** [AHAAAAAAA/PokemonGo-Map#1005]
Title Says it all.
Just recloned the project, and restarted browser.
All pokemon say that.

![2016-07-21 15_15_11-pokemap](https://cloud.githubusercontent.com/assets/1305090/17035605/42250006-4f56-11e6-909a-98a51ca1fa56.png)

**Comment by Tigershark2005** [comment]
All say 19:00 or expired? I had an issue when my system time was off. It was giving very odd expired countdowns. Check your time zone, date, and exact time.

**Comment by haqthat** [comment]
Every single one says "Disappears at 19:00:00 (expired)"
Even after time has passed, restarting the app, or reloading the browser.

Windows 10 date and time are definitely correct. EST

**Comment by Tigershark2005** [comment]
Interesting, are you on the most recent master branch distribution? The develop branch has some settings that may be preventing that from working in all cases.

**Comment by haqthat** [comment]
I cloned the develop branch, thought master was old

**Comment by DerScreever** [comment]
im on latest develop and it work: http://85.214.145.87:5000/

**Comment by haqthat** [comment]
![image](https://cloud.githubusercontent.com/assets/1305090/17036615/0c210310-4f5b-11e6-9fb8-5d937cb2ccf7.png)

**Comment by haqthat** [comment]
Update: Seems to work in Firefox, but not in chrome.

Chrome Version 51.0.2704.103 m

**Comment by TheRealGitCub** [comment]
It's working for me on latest develop and the same version of Chrome.

**Comment by sykhro** [comment]
Fixed in recent commits
