### ISSUE TITLE
Question- How can I change coordinates in the map?

### ISSUE THREAD

**Issue by briesanji** [AHAAAAAAA/PokemonGo-Map#1008]
Is there a way to change coordinates in the Windows application.. 

Unfortunatly the map shows a location different from the real one.. So I would like to change the coordinates in order to see the pokemons around me.. I tried with Sensors (using Dev Console) but when I refresh nothing happens.

Any solution?

**Comment by macgngsta** [comment]
Originally they had put a current location button in the build, but it seems to have disappeared. You can use my fork for now,  if you want to insert location for now in the gui. #660

**Comment by briesanji** [comment]
Oh I m taking a look right now

**Comment by briesanji** [comment]
Unfortunatly I m a noob.. I can I use your tool

**Comment by macgngsta** [comment]
https://github.com/macgngsta/PokemonGo-Map/tree/map_enhance, click the green button `download as zip`

**Comment by briesanji** [comment]
I tried to run the easy setup .bat file but It returns me an error.. Probably I m not installing it in the right way.. With POGOMAP I have the Exe file and I just run it.. But probably now I have to build it (Sorry again for the stupid question)

**Comment by medghaim** [comment]
Closing this issue as it is outdated. If this issue still persists on the `develop` branch, please reopen a new issue and update the information therein to reflect the new changes.

Also, please be aware of the incredibly helpful and supportive community at: 
https://discordapp.com/invite/Kzp4yky
