### ISSUE TITLE
No Module Named Flask (OSX Mavericks)

### ISSUE THREAD

**Issue by Mr10001** [AHAAAAAAA/PokemonGo-Map#1011]
I ran the "sudo pip install -r requirements.txt" and then ran:
"sudo python example.py -a ptc -u XXXXXXXX -p XXXXXX -l ##.########,-##.####### -st 1000"

I've tried uninstalling and re-installing.

I'm running python 2.7 on OSX Mavericks and I've tried updating my PYTHONPATH to where flask is stored:

PYTHONPATH="/usr/local/lib/python2.7/site-packages:$PYTHONPATH"

Yet, I'm still running into the No Module Named... error.

Any idea what the issue may be?

Thanks for any help with this.

**Comment by macgngsta** [comment]
can you post your console log?

**Comment by Mr10001** [comment]
I'd love to, what should I run?

**Comment by macgngsta** [comment]
also if you can switch to the develop branch

`$ cd <insert path to the map project>`
`$ git checkout develop`
`$ python runserver.py -a ptc -u XXXXXXXX -p XXXXXX -l ##.########,-##.####### -st 3`

btw - 1000 is kinda high for your steps

**Comment by Mr10001** [comment]
I CD'd to the map project folder and then ran "git checkout develop" and received this error: "fatal: Not a git repository (or any of the parent directories): .git"

**Comment by KeenIIDX** [comment]
What is the output of 'pip list'?

**Comment by Mr10001** [comment]
#pip list
click (6.6)
coverage (4.1)
coveralls (1.1)
docopt (0.6.2)
Flask (0.11.1)
Flask-GoogleMaps (0.2.0)
future (0.15.2)
geopy (1.11.0)
gpsoauth (0.3.0)
itsdangerous (0.24)
Jinja2 (2.8)
MarkupSafe (0.23)
peewee (2.8.1)
pip (8.1.2)
protobuf (2.6.1)
protobuf-to-dict (0.1.0)
pycryptodomex (3.4.2)
requests (2.10.0)
s2sphere (0.2.4)
setuptools (24.1.0)
Werkzeug (0.11.10)

**Comment by djackyn** [comment]
Try to use python 2.7 directly:
`python2.7  runserver.py -a ptc -u XXXXXXXX -p XXXXXX -l ##.########,-##.####### -st 3

`

**Comment by Mr10001** [comment]
Same ish issue:

$ sudo python2.7 runserver.py -a ptc -u XXXXXXXX -p XXXXXX -l XX.XXXXXX,-XX.XXXXXX -st 100
Traceback (most recent call last):
  File "runserver.py", line 10, in <module>
    from pogom.app import Pogom
  File "/Users/USERNAME/Downloads/PokemonGo-Map/pogom/app.py", line 5, in <module>
    from flask import Flask, jsonify, render_template
ImportError: No module named flask

**Comment by sethherr** [comment]
Setting up a virtualenv resolved this for me (all steps required for installation once in the project dir):

```
brew install python
pip install virtualenv
virtualenv venv
source venv/bin/activate
pip install -r requirements.txt
```

**Comment by abusalman** [comment]
I got the same issue..

**Comment by backmeupplz** [comment]
Ok guys, had the same issue, solved it:
1.  sudo pip install virtualenv
2. virtualenv flask
3. cd flask
4. git clone *repo*
5. sudo pip install -r requirements.txt
run your python scrypt ;)

**Comment by sethherr** [comment]
Don't use sudo, use homebrew

**Comment by Gr05** [comment]
I got the same issue, and when i try to install the requirements i got these exceptions so maybe it's the root of the issue :  

Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1235, in prepare_files
    req_to_install.assert_source_matches_version()
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 465, in assert_source_matches_version
    % (display_path(self.source_dir), version, self))
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 70, in display_path
    if path.startswith(os.getcwd() + os.path.sep):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 13: ordinal not in range(128)

I never used Python before so i really don't know if that will help something to help me but i tried my best for all the solutions you finds and nothings worked for me :(

**Comment by Mr10001** [comment]
The virtual environment did the trick, thank you!
