### ISSUE TITLE
While Scanning error

### ISSUE THREAD

**Issue by kickasssid** [AHAAAAAAA/PokemonGo-Map#1014]
While scanning in search i get two errors Scan step failed response dictionary key error

**Comment by kickasssid** [comment]
and also why does these pokemon doesn't show in my area and they are showing up in the 5 km radius circle?

**Comment by medghaim** [comment]
Closing this issue as it is outdated. If this issue still persists on the `develop` branch, please reopen a new issue and update the information therein to reflect the new changes.

Also, please be aware of the incredibly helpful and supportive community at: 
https://discordapp.com/invite/Kzp4yky
