### ISSUE TITLE
PokeMap-Live @ http://pokemap-goe.de:5000

### ISSUE THREAD

**Issue by Quebroph** [AHAAAAAAA/PokemonGo-Map#1018]
See my live pokemap. the algorithm takes long for high step counts - so that all pokemon in the inner circle has gone while the complete radius isn´t analysed yet.

How can we fix this?

See http://pokemap-goe.de for my pokemap example for the city of Göttingen, Germany.

**Comment by fettlaus** [comment]
Lower your step count? Niantic servers can only respond so fast

**Comment by Sejadis** [comment]
yeah lower the step count and run multiple instances at different locations instead

**Comment by rezz3x** [comment]
#776 Could help you, try it out.

**Comment by Quebroph** [comment]
ok i try - what does master branch mean? 
how can i run more instances @ same time?

**Comment by rezz3x** [comment]
Use another Port with -P

**Comment by Quebroph** [comment]
I want to collect the pokemon on 1 map. Is this possible when i run multiple instances?

**Comment by docrockulus** [comment]
On dev branch, all data is placed in the .db file and is shared between all maps

**Comment by Quebroph** [comment]
Thanks for the feedback! i´ll try to get the branch with mysql running.

**Comment by docrockulus** [comment]
Nonono, you do not need to set up your own sql. There is an included db handler which will take care of it. Just clone the dev branch, add your gmaps api key, and run.

**Comment by machadox** [comment]
if i run 3 instances in a vps (with port 5000. 5010 5030), 1 ill eventualy spot working, and then all crash :x

**Comment by PrabhanshuAttri** [comment]
@machadox  I had the same issue with 2 instances on heroku.

**Comment by tripout** [comment]
I have 5 instances running on my VPS to do the whole town I am in and so far no crashes.

**Comment by machadox** [comment]
ok, i found now my "map" problem with multiple instances is only on chrome... mozila run it fine...

**Comment by Quebroph** [comment]
Do you start the instances with the same login data?

1. python runserver.py -a ptc -u USER -p PASSWORT -l "LOCATION1" -st 10 -ar -P 5000
2. python runserver.py -a ptc -u USER -p PASSWORT -l "LOCATION2" -st 10 -ar -P 5010
3. python runserver.py -a ptc -u USER -p PASSWORT -l "LOCATION3" -st 10 -ar -P 5020

Is this right?

**Comment by tripout** [comment]
That is what I've done.  My first instance is bound to my public IP and the rest are just bound to localhost with different ports.  I have 5 instances running and it works good.

**Comment by PCVXD** [comment]
You can also run the extra instances with the -ns flag which will disable the webserver for those instances. I don't know if it works better with different login data though.

**Comment by Quebroph** [comment]
I tryed the -ns flag with wont be executed.

**Comment by tripout** [comment]
All 5 of my instances are running with the same user/pass for the PTC login.  I have disabled the webserver (-ns) on 4 of them just leaving the 1 running.  So far works good.  I may write up some scripts to force stop/start the instances every 30 minutes or so

**Comment by almasmaris** [comment]
@Quebroph hey can you tell me how to make the app can be access with http? I'm upload it to my digital ocean server. But, i can't access it with the ip address ([ipadress:5000)

**Comment by Quebroph** [comment]
Yes :-) Cool that you try it, too. Just add `-H IP.IP.IP.IP` to the start command.

Use your server IP instead of `-H IP.IP.IP.IP`

**Comment by medghaim** [comment]
Closing this issue as it is outdated. If this issue still persists on the `develop` branch, please reopen a new issue and update the information therein to reflect the new changes.

Also, please be aware of the incredibly helpful and supportive community at: 
https://discordapp.com/invite/Kzp4yky

**Comment by Shugabuga** [comment]
Unrelated issue, but how did you get the server status in the header?

**Comment by Quebroph** [comment]
Thanks for the question - its set manually hard coded to calm down the users 😂 If there are technical issues i´ll set it orange or red. If the server is not running, there will be no HTML output ;)

**Comment by Shugabuga** [comment]
Ah, I assumed that it was hooked up to some kind of API. Thanks for the response!

**Comment by Quebroph** [comment]
No probs - in Germany we say "Trick17" for a fake output like this ;)

**Comment by ikymwb** [comment]
hi please toturials install on vps digital ocean  ubuntu

**Comment by Shugabuga** [comment]
I'm not familiar with Digital Ocean, but you can do a free (and dead simple) install of this using Heroku or Jelastic using the buttons below:

[![Deploy to Jelastic](https://raw.githubusercontent.com/sych74/PokemonGo-Map-in-Cloud/master/images/deploy-to-jelastic.png)](https://jelastic.com/install-application/?manifest=https://raw.githubusercontent.com/sych74/PokemonGo-Map-in-Cloud/master/manifest.jps) [![Deploy to Heroku](https://www.herokucdn.com/deploy/button.png)](https://dashboard.heroku.com/new?button-url=https://github.com/AHAAAAAAA/PokemonGo-Map/tree/develop&template=https://github.com/AHAAAAAAA/PokemonGo-Map/tree/develop)

Next time, I'd make your own issue, as this is not related to this one.

**Comment by almasmaris** [comment]
@ikymwb Just create new droplet (ubuntu). Upload file to server and run the script with supervisor.

**Comment by hulkrules** [comment]
@ docrockulus

Your map is amazing and makes the game worth plying
Would it be much to ask to expand the map just to  lasalle there is a lot to be found out this way
Much appreciated

**Comment by Shugabuga** [comment]
@hulkrules, you can easily host your own map by using Jelastic or Heroku by clicking one of the deploy buttons below. I'm pretty sure both are free!

[![Deploy to Jelastic](https://raw.githubusercontent.com/sych74/PokemonGo-Map-in-Cloud/master/images/deploy-to-jelastic.png)](https://jelastic.com/install-application/?manifest=https://raw.githubusercontent.com/sych74/PokemonGo-Map-in-Cloud/master/manifest.jps) [![Deploy to Heroku](https://www.herokucdn.com/deploy/button.png)](https://dashboard.heroku.com/new?button-url=https://github.com/AHAAAAAAA/PokemonGo-Map/tree/develop&template=https://github.com/AHAAAAAAA/PokemonGo-Map/tree/develop)

After that, you can input coordinates, fiddle with it, and have it working how you want it.

**Comment by hulkrules** [comment]
wow thanks for the help, now i got it to work for lasalle, its very slow and seems to be scanning areas, do i just let it run continuously and it will work like the rest of the maps

**Comment by Shugabuga** [comment]
@hulkrules, if it is working too slow, lower the radius that it scans. 8-10 is a good number.

If you can't do this (and even if you can), the map will do its thing automatically, so just use it like any other map.
