### ISSUE TITLE
Bug?  Trying to install requirements.txt and this pops up.

### ISSUE THREAD

**Issue by theblackmarmoset** [AHAAAAAAA/PokemonGo-Map#1019]
http://prntscr.com/bvu49q  Whenever I try installing requirements.txt this pops up.  What do I do to fix it?

**Comment by neobithia** [comment]
What's inside your requirements.txt?

**Comment by theblackmarmoset** [comment]
This exactly "Flask==0.11.1
Jinja2==2.8
MarkupSafe==0.23
Werkzeug==0.11.10
argparse==1.2.1
click==6.6
itsdangerous==0.24
peewee==2.8.1
wsgiref==0.1.2
geopy==1.11.0
protobuf==2.6.1
requests==2.10.0
s2sphere==0.2.4
gpsoauth==0.3.0
protobuf-to-dict==0.1.0"

**Comment by Sejadis** [comment]
you forgot the -r

**Comment by theblackmarmoset** [comment]
Ohhhh thanks man!  That fixed it <3
