### ISSUE TITLE
FAKE

### ISSUE THREAD

**Issue by kickasssid** [AHAAAAAAA/PokemonGo-Map#1021]
it's fake, i went there it was not there... my sister told me it's there and it will expire in 5 mins but it not there not even in pokemon nearby

**Comment by neobithia** [comment]
Ban this troll.

**Comment by asam1989** [comment]
It works like a charm - Dont believe this guy!

**Comment by RavensFlight92** [comment]
works perfectly fine

**Comment by kickasssid** [comment]
It's night how would i go out?! i wanted to check that if it it was worth trying or not... if you are saying yes then my time building it was worth it! thanks for reply guys

**Comment by nithou** [comment]
Works perfectly fine, installed on a raspberry, got a Machoke & Porygon right were they were supposed to be :)
