### ISSUE TITLE
ImportError: No module named flask

### ISSUE THREAD

**Issue by kamiathewolf** [AHAAAAAAA/PokemonGo-Map#1023]
Hello everyone,

I am trying to install and run the dev branch of the Pokemon Go Map but I keep getting an error. 

When I type in the following: 
python runserver.py -a ptc -u myusername -p mypassword -l "My Location, USA" -st 10

I get an error that states "File 'filelocation\pogom\app.py', line 5, in <module> from flask import Flask, jsonify, render_template, request
ImportError: No module named flask"

Any help would be greatly appreciated. Sorry if I didn't format this question properly - this is my first time on GitHub forums. Thanks!

**Comment by Galtwise** [comment]
pip uninstall flask
pip install flask


uninstall and reinstall should do it

**Comment by kamiathewolf** [comment]
Thanks for your help, but now I'm getting a new error. I followed your commands and got this output:
![pokemongo_error](https://cloud.githubusercontent.com/assets/20585702/17037990/64863cf4-4f48-11e6-9d8a-b4dfeeba9a6e.png)
