### ISSUE TITLE
Can't Find Auto Refresh Option

### ISSUE THREAD

**Issue by commit-sudoku** [AHAAAAAAA/PokemonGo-Map#1026]
## Expected Behavior

I saw someone post that auto refresh is in the UI now but in the menu I only see filtering options
## Current Behavior

After initial scan I get this in the console and the map stops updating
http://i.imgur.com/PCGmwZs.png
## Steps to Reproduce (for bugs)

I'm running on Heroku with this in my Procfile

web: python runserver.py -u "$USERNAME" -p "$PASSWORD" -l "$LOCATION" -st $STEP_COUNT $EXTRA_ARGS -H 0.0.0.0 -P $PORT -k "$GMAPS_KEY"

with extra_args blank since I read that -ar is no longer supported

## Your Environment

* Version used: Latest Dev
* Environment name and version (e.g. Python 2.7): Python2.7
* Operating System and version (desktop or mobile): Desktop

**Comment by prajwalkman** [comment]
It's enabled by default now.

**Comment by MonkeyLeeT** [comment]
As suggested.

Also just curious, is there some features you could suggest for Japan players, like gps shift for China players?

**Comment by prajwalkman** [comment]
Autorefresh is enabled by default now. Your map is not updating because the search thread crashed - something related to authentication to pokemon servers. Maybe we need a monitor to restart the search thread if it crashes?

**Comment by commit-sudoku** [comment]
@prajwalkman ah I see, thanks!
@MonkeyLeeT I'm a dirty weeb, not a japanese player :P

**Comment by MonkeyLeeT** [comment]
@commit-sudoku you dirty weeb! Closed.
