### ISSUE TITLE
Docker-Howto into Wiki

### ISSUE THREAD

**Issue by pikespeak** [AHAAAAAAA/PokemonGo-Map#1029]
Ive Added Docker to The manual

[_Sidebar.md.txt](https://github.com/AHAAAAAAA/PokemonGo-Map/files/376936/_Sidebar.md.txt)
[Docker-Deployment.md.txt](https://github.com/AHAAAAAAA/PokemonGo-Map/files/376937/Docker-Deployment.md.txt)

**Comment by jnovack** [comment]
#599 is for docker support.

This has typos, non-standard formatting, etc.

**Comment by sykhro** [comment]
Please open a pull request and we'll consider it. Attaching in an issue is not acceptable.

**Comment by pikespeak** [comment]
Sorry, I don't know to open a pull request for the Wiki.
How to do it?

**Comment by sykhro** [comment]
Let's do it like this: create a directory inside the .github folder called docs, and open a pull request with the docs in there. they will be added to the wiki manually by contributors
