### ISSUE TITLE
Only Showing Common/Bad Pokemon

### ISSUE THREAD

**Issue by jfarese23** [AHAAAAAAA/PokemonGo-Map#1030]
I'm updated to the latest development version and it's only showing common/bad pokemon (i.e. pidgey, spearow, rattata, weedle). When I pull up an older master version, I can see all the pokemon on the screen. Is this a problem for anyone else?

**Comment by TheRealGitCub** [comment]
I think this is more an issue of the amount of Pokémon showing in general. Comparing my instances of the master and develop channels, the master has a lot more for me.

**Comment by jfarese23** [comment]
@TheRealGitCub Maybe. In comparing the two maps, literally every common pokemon is on the map and none of the others are showing up
