### ISSUE TITLE
[Dev] [Bug] Scan Step failed

### ISSUE THREAD

**Issue by IQNeoXen** [AHAAAAAAA/PokemonGo-Map#1031]
## Expected Behavior
Showing Pokemon, Stops etc... 

## Current Behavior
Only shows marker on the map and nothing else.
Purging pogom.db didn't help...

## Context
I'm running the server on a vserver, you can check it out at http://pokemon-chip.tk/

## Your Environment
Debian 8, Python 2.7
![bildschirmfoto vom 2016-07-21 22-43-52](https://cloud.githubusercontent.com/assets/20561093/17038237/0f462a68-4f95-11e6-9afc-6da07e5eff2e.png)

**Comment by TheRealGitCub** [comment]
Run a `git pull` in your repo to make sure you're up-to-date. I had this issue and an update fixed it for me.

**Comment by sykhro** [comment]
Pull latest, this bug was fixed

**Comment by IQNeoXen** [comment]
Thanks!

**Comment by IQNeoXen** [comment]
Ok now the scanner doesn't find anything - no pokemon, no pokestops etc... Is this a bug or a feature? ;D

**Comment by DerScreever** [comment]
@IQNeoXen for me all work

**Comment by IQNeoXen** [comment]
Restarted the whole server, purged pogom.db -> Still no result.
Scan steps failing all the time (see console log)

![bildschirmfoto vom 2016-07-21 23-05-36](https://cloud.githubusercontent.com/assets/20561093/17038786/a85a943a-4f97-11e6-96e6-898b68e6874d.png)

**Comment by IQNeoXen** [comment]
`2016-07-21 17:07:51,402 [     search] [  ERROR] Scan step failed. Response dictionary key error.`

What exactly is the dictionary key?

**Comment by IQNeoXen** [comment]
Someone deleted the "locales" folder in the latest dev... why??

**Comment by TheRealGitCub** [comment]
It's [here](https://github.com/AHAAAAAAA/PokemonGo-Map/tree/develop/static/locales) now
