### ISSUE TITLE
Fake gps or THIS! 

### ISSUE THREAD

**Issue by kickasssid** [AHAAAAAAA/PokemonGo-Map#1032]
Hi guys.. so  I'm looking where all pokemons are and i choose doduo 
i'm using fake gps on android to go there, i went to that location
and wow no pokemon..

So guys tell me if this is fake or the fake gps.. explanations needded

**Comment by TheRealGitCub** [comment]
Dude it's not fake. Quit opening new issues.

**Comment by kickasssid** [comment]
I want explanation regarding both either one of them is don't you think too? @TheRealGitCub

**Comment by TheRealGitCub** [comment]
I don't know how to help you man. The shown Pokémon is accurate for me and everyone I've seen use this.
