### ISSUE TITLE
Scan steps failed. Response dictionary key error

### ISSUE THREAD

**Issue by lnmtriet93** [AHAAAAAAA/PokemonGo-Map#1033]
As title, I have an error when running runserver.py

**Comment by macgngsta** [comment]
try deleting pogom.db and running it again

**Comment by lnmtriet93** [comment]
Did it with no succes

**Comment by npeep** [comment]
My copy of the latest commit has started this as well.. :|

**Comment by ximex** [comment]
checkout at c05e07e535ee58d9fbe2cc14928da2a7f7ffc546 fix it

**Comment by lrobson555** [comment]
I'm also having getting this error.
Running runserver.py on a newly checked out develop branch.

Tried deleting pogom.db, doesn't work.

**Comment by Captainohair** [comment]
I just grabbed the most recent and can confirm it is still doing this. I cleared my directory and downloaded it all fresh.

**Comment by DerScreever** [comment]
work for me

**Comment by invisiblek** [comment]
niantic server problems

**Comment by Captainohair** [comment]
And yet, my phone gets in.

**Comment by npeep** [comment]
@invisiblek I don't think so - I am also running https://github.com/megahambone/PokemonGo-Map/tree/develop and his is working perfect - its something in like the last 3 commits maybe?

**Comment by brumie** [comment]
same error just after pull
search] [  ERROR] Scan step failed. Response dictionary key error.

**Comment by seraphbreak** [comment]
I'm having the same issue with scan step failed, response dictionary key error on newest develop commit. login works and servers are up

**Comment by backmeupplz** [comment]
@invisiblek I don't think so, master branch works well

**Comment by beranPro** [comment]
Same error here. Deleting pogom.db doesn't work... Oh pokemon trainer club is down

**Comment by prajwalkman** [comment]
This bug was "reintroduced" in this commit:

https://github.com/AHAAAAAAA/PokemonGo-Map/commit/8b4f78b2b0c8723928b6d8fd946892c28b6f02f8#diff-a350469a6764edb653c7280bd0cf5adbL122

**Comment by lnmtriet93** [comment]
I checked in go.jooas.com and both niantics and ptc work normally

**Comment by backmeupplz** [comment]
@prajwalkman I checked reverting line 149 of `map.js`, didn't help

**Comment by npeep** [comment]
I'd bet it was related to @sykhro 's massive update adding the ignore frontend stuff - which is a bummer, I am very very excited to test that!

**Comment by invisiblek** [comment]
working for me now on latest

**Comment by janitory** [comment]
Nope, just updated and still the same error. Also tried deleting pogom.db.

**Comment by brumie** [comment]
just Updating 1b4e62a..aa8dbdd but still error

**Comment by c133** [comment]
just pulled latest develop, still getting dictionary error. How stable is master? Do all pokemon on master still eventually disappear?

**Comment by backmeupplz** [comment]
Reverted to c05e07e per @ximex suggestion, everything works

**Comment by seraphbreak** [comment]
newest pull works.

**Comment by brumie** [comment]
0afae80 works, thanks

**Comment by InfinityBMX** [comment]
Working now here too.

**Comment by sykhro** [comment]
Yeah, my bad. Forgot to remove experimental code.

**Comment by backmeupplz** [comment]
0afae80 works, thank you!
