### ISSUE TITLE
Lures don't time out and no new Pokemon are shown

### ISSUE THREAD

**Issue by DeastinY** [AHAAAAAAA/PokemonGo-Map#1034]
After some time this happens. The browser-console does not show any errors,  the server is scanning happily. After either restarting the script or forcefully reloading the website it works again for some time.

**Comment by invisiblek** [comment]
this should fix half your issue: https://github.com/AHAAAAAAA/PokemonGo-Map/pull/1006

**Comment by sykhro** [comment]
As of now, Niantic servers are having an outage, and no pokemons are being shown

**Comment by DeastinY** [comment]
@invisiblek your commit looks great :smile:, but I'm afraid there's more here
@sykhro same to you, this happened already 6+ hours ago and is still happening

**Comment by sykhro** [comment]
Most recent commit could have fixed the issue for you. However:

- be sure you are not banned/softbanned (e.g. try another account, whatever google acc is fine, even if it has never entered the game)
- clear you cache and delete pogom.db

**Comment by DeastinY** [comment]
@sykhro will try this later with current develop branch. Will provide feedback then.

**Comment by medghaim** [comment]
Closing this issue as it is outdated. If this issue still persists on the `develop` branch, please reopen a new issue and update the information therein to reflect the new changes.

Also, please be aware of the incredibly helpful and supportive community at: 
https://discordapp.com/invite/Kzp4yky
