### ISSUE TITLE
Gym that doesn't exist showing on map

### ISSUE THREAD

**Issue by KensonN** [AHAAAAAAA/PokemonGo-Map#1037]
The map is showing an uncontested gym near my location, but the Pokemon Go app shows nothing there.

**Comment by invisiblek** [comment]
can you post your pogom.db somewhere? i have a hunch what this is, and can fix it easily if that's the case, but i want to make sure

**Comment by invisiblek** [comment]
there should be a pogom.db in the directory where you run this from. upload it somewhere (dropbox or google drive) and give me a link

**Comment by KensonN** [comment]
Here you go: https://drive.google.com/file/d/0B8Hcaa0yeE6jaTh1SnU2d0JmQkk/view?usp=sharing

**Comment by invisiblek** [comment]
weird, it wasn't what i thought it was...this pogom.db should have held the gym in question right?

**Comment by KensonN** [comment]
Again, I have no programming experience, so I do not know the answer to that. I'm also noticing some pokestops that show up on the map that don't exist.

**Comment by invisiblek** [comment]
that's really strange, i dont have a good answer for you

**Comment by sykhro** [comment]
Try deleting the pogom.db

**Comment by KensonN** [comment]
Deleting it seems to have fixed it. Thanks!

**Comment by medghaim** [comment]
Closing this issue as it is outdated. If this issue still persists on the `develop` branch, please reopen a new issue and update the information therein to reflect the new changes.

Also, please be aware of the incredibly helpful and supportive community at: 
https://discordapp.com/invite/Kzp4yky
