### ISSUE TITLE
JUST GO TO POKEVISION.COM

### ISSUE THREAD

**Issue by fankaisong** [AHAAAAAAA/PokemonGo-Map#1038]
Just go to PokeVision.com  No download needed. Nerds!

**Comment by DanielSiepmann** [comment]
And no modifications are possible, you need to click and wait 30 seconds, eg.

Don't troll.

**Comment by TheRealGitCub** [comment]
Those tags <3

**Comment by fankaisong** [comment]
dam...  at least you don't have to install bunch of stuffs, and after you done installing, pokemons not showing up

**Comment by TheRealGitCub** [comment]
The servers are having issues right now, that's why they're not showing up. 😛

**Comment by fankaisong** [comment]
@TheRealGitCub  If the account that I use i is not currently logged into Pokemon Go App, will I have trouble with logging in on my pc?

**Comment by janitory** [comment]
You seriously think anyone will help you after spouting that nonsense?

**Comment by fankaisong** [comment]
@janitory  I was just saying there is another option to do this.
