### ISSUE TITLE
Provide GUI option to scan and jump to a specific area

### ISSUE THREAD

**Issue by DanielSiepmann** [AHAAAAAAA/PokemonGo-Map#1039]
## Expected Behavior
Provide a search box to enter an address like a street. Map to coordinates and send next_loc request via post. Also update marker location and center map to this location.

## Possible Solution
Integrate an input into the menu. Didn't think much further yet.

## Context
Will allow you to pre scan an target area, like the way to work.

**Comment by medghaim** [comment]
Closing this issue as it is outdated. If this issue still persists on the `develop` branch, please reopen a new issue and update the information therein to reflect the new changes.

Also, please be aware of the incredibly helpful and supportive community at: 
https://discordapp.com/invite/Kzp4yky
