### ISSUE TITLE
Everything Worked Prefectly, but how to Stop?

### ISSUE THREAD

**Issue by teaminstinct** [AHAAAAAAA/PokemonGo-Map#1040]
I accidently set the -st value at 100000000 and was wondering if there was a way to stop this from going all the way through with the search so that i may restart it.

**Comment by TheRealGitCub** [comment]
hit `Ctrl-C` in your console.

**Comment by Bitti09** [comment]
Ctrl + C in the Terminal/Shell wher e you've started the script

**Comment by teaminstinct** [comment]
Thanks!
