### ISSUE TITLE
Making it Portable

### ISSUE THREAD

**Issue by kickasssid** [AHAAAAAAA/PokemonGo-Map#1042]
Hi!  i have concern that a laptop is not that portable to take around to find pokemon, so how can we take this map with us on the run to catch pokemon?

**Comment by fankaisong** [comment]
exactly, You can try pokevison.com but its kind limited for searching pokemons

**Comment by IQNeoXen** [comment]
1. Set up a server
2. Port forward
3. Get dyndns
4. Profit

**Comment by fankaisong** [comment]
I am just telling the pros and cons

**Comment by TheRealGitCub** [comment]
There is also an [Android App](https://github.com/omkarmoghe/Pokemap) in the works.

**Comment by kickasssid** [comment]
how are we gonna make android app?

**Comment by TheRealGitCub** [comment]
By coding Java?????

**Comment by kickasssid** [comment]
Oh really, you're gonna teach me java.?

**Comment by sykhro** [comment]
@fankaisong Comment removed: don't spam
