### ISSUE TITLE
Pokemons not showing

### ISSUE THREAD

**Issue by fankaisong** [AHAAAAAAA/PokemonGo-Map#1043]
I have install everything and the map worked fine just like regular maps. However, I was not getting pokemons on my map at all. I have tried master and develop versions. Both did not work for me. Any ideas?

**Comment by flexusjan** [comment]
same here

**Comment by Foxy1990** [comment]
same here since last update

**Comment by dev-masta** [comment]
Browser console throws "Uncaught TypeError: Cannot read property 'addEventListener' of null" in svg-overlay.js:41

yes, since last update

**Comment by vanrzuf** [comment]
Scan step failed. Response dictionary key error. I get this error after lastest update

**Comment by backmeupplz** [comment]
Relates to #1033

**Comment by sykhro** [comment]
Latest commit should be working now

**Comment by dev-masta** [comment]
Latest commit works here.
Nice work everyone!
