### ISSUE TITLE
Hide common Pokémon

### ISSUE THREAD

**Issue by Foxy1990** [AHAAAAAAA/PokemonGo-Map#1047]
Hide common Pokémon doesnt work with localization

**Comment by npeep** [comment]
Not working at all for me - can't type into it, and its not dropping down.

![image](https://cloud.githubusercontent.com/assets/6043230/17039569/c577f9b8-4f60-11e6-93f8-915bbac75f5b.png)

**Comment by Foxy1990** [comment]
i can only type in english pokemon names but im using german locales and the german names dont work

**Comment by sykhro** [comment]
A switch for that will come soon

**Comment by sykhro** [comment]
@npeep are you using latest commit? It's not supposed to have that colors

**Comment by Bitti09** [comment]
@Foxy1990  Possible Reason:
Filter works on raw Data
Shown names are generated by the ui

**Comment by richipargo** [comment]
@sykhro ran into same issue when i was adding it to #770, the `z-index` are too high on `#nav` element for select 2 dropdown

**Comment by IQNeoXen** [comment]
@sykhro I'm using the latest commit and colors are the same as in @npeep 's screen

**Comment by DanielVolz** [comment]
With the latest commit I got the new menu:
<img width="287" alt="screenshot 2016-07-21 23 39 10" src="https://cloud.githubusercontent.com/assets/3275994/17039813/745a46bc-4f9c-11e6-8dd2-3e78f71a48c4.png">

**Comment by sykhro** [comment]
@richipargo thanks for that! I was trying to figure it out, but I'm kinda brain-dead at the moment. Will  look at your PR

**Comment by sykhro** [comment]
mind linking? can't seem to find them

**Comment by npeep** [comment]
@sykhro Ah, thanks for the tip on the color.  I should have learned by now to sync twice, close and re-open chrome once before even checking :)  That fixed it for me.

**Comment by richipargo** [comment]
@sykhro 

on `static\sass\libs\_vars.scss`
z-index base before sass compilation
```css
// Misc.
	$misc: (
		z-index-base:		500
	);
```

on `static/js/app.js`
for pokemon icon render, probably needs some tuning to newer locale settings
```js
templateResult: function(element){
        if (!element.id) { return element.text; }
        return $('<span><img src="static/icons/'+ element.id + '.png">'+ element.text +'</span>');
      },
      templateSelection: function(result, container){
        return $('<img src="static/icons/' + result.id + '.png">');
      }
```

**Comment by sykhro** [comment]
oh, sorry, I thought you opened a PR. Will merge those shortly

**Comment by richipargo** [comment]
@sykhro i did but its so behind and i don't have the time right know

**Comment by sykhro** [comment]
oh, I see, no worries
