### ISSUE TITLE
Comment magic numbers

### ISSUE THREAD

**Issue by favll** [AHAAAAAAA/PokemonGo-Map#105]
There are a bunch of magic numbers and constants that are hard to understand without having intimate knowledge of the api.

For example:

https://github.com/AHAAAAAAA/PokemonGo-Map/blob/41392476124588aa7bc7243a2ffd6bc71f2f9a80/example.py#L166

https://github.com/AHAAAAAAA/PokemonGo-Map/blob/41392476124588aa7bc7243a2ffd6bc71f2f9a80/example.py#L172

and many more...

**Comment by vedmaque** [comment]
I think magic numbers comes from reverse engineering, so they will be magic numbers forever
