### ISSUE TITLE
Credentials.json

### ISSUE THREAD

**Issue by Waffletaco** [AHAAAAAAA/PokemonGo-Map#1051]
Sorry if this is like a repeating record.  But I can not seem to get Credentials.json working.  I have unzipped the map folder into the Python folder.  C:\python27\Pokemongo*.  I first tried it with the credentials file that was already provided.  That didn't work so I got my own API.  As of now the credentials file has a ptc_client_secret, android _id, client_sig, gmaps_key, and one other.  I got my own Gmaps key and created a new credentials.json and put only {"gmaps_key" : ******}.  Still getting the error 

c:\Python27>python pokemongo-map-master\example.py -a ptc -u [****] -p [******] -l "******" -st 10
"Traceback (most recent call last):
  File "pokemongo-map-master\example.py", line 41, in <module>
    with open('credentials.json') as file:
IOError: [Errno 2] No such file or directory: 'credentials.json'"

I am on a Windows 7 machine.  Please let me know what im doing wrong.

**Comment by fankaisong** [comment]
in your folder, I think you have credentials.example.json. Just change the name to 'credentials.json'"

**Comment by Waffletaco** [comment]
![image](https://cloud.githubusercontent.com/assets/10137569/17040027/7af1d5c0-4f6b-11e6-9f8c-f8f213375502.png)

The Credentials2s.json is the one that came with the file.  I just added a 2 there so I can make a new one.

The Credentials.json is mine that only has the gmaps_key.

**Comment by fankaisong** [comment]
Also, you don't have Google Map API keys in that file

**Comment by Su1ph3r** [comment]
You need to add your API key to the original credentials.json file instead of creating a new file with only the gmaps_key.

**Comment by Waffletaco** [comment]
Already tried that.  This is the original file that came with the zip.  I of course ********* my API key:
![image](https://cloud.githubusercontent.com/assets/10137569/17040107/e711d660-4f6b-11e6-80b9-f70ef293ccef.png)

**Comment by TheRealGitCub** [comment]
Try the `develop

**Comment by Waffletaco** [comment]
TY that worked....!!!!!!!
