### ISSUE TITLE
Server running and "searching for pokemon", but clears map after a bit of time

### ISSUE THREAD

**Issue by Schwaitz** [AHAAAAAAA/PokemonGo-Map#1053]
Hey,

So when I run my program with the command, "**python example.py -u ***** -p ***** -l "latitude, longitude"-st 10 -P 5001 -H 0.0.0.0 -dp -dg**", it works for one (I assume, it could be a couple) loop through, but on the next loop(s), it clears the map completly. As in, when it searches for pokemon in that area on the start of the loop, it clears them from the map, but the others remain until it get's to their step clears them too.

[Here](http://i.imgur.com/DWyOsEN.gif) is a GIF of the server running, and not recieving any errors (while still "searching for pokemon"), but when I go to the map, [this](http://i.imgur.com/8C24IJX.png) is what it shows me.

Any ideas?

Is there a limit to API requests, and I am exceeding it by running 3 servers at once for 3 different locations?

**Comment by Sejadis** [comment]
the master branch isnt officially supported anymore you should switch to dev branch
but to solve that problem remove line 505 in example.py

**Comment by Schwaitz** [comment]
@Sejadis Will switching to the Dev branch also fix it?

**Comment by Sejadis** [comment]
yes it will
