### ISSUE TITLE
 error: argument -p/--password: expected one argument

### ISSUE THREAD

**Issue by alloin** [AHAAAAAAA/PokemonGo-Map#1054]
## Current Behavior
getting  error: argument -p/--password: expected one argument

## Steps to Reproduce (for bugs)
runserver.py -a ptc -u loginname -password 12341234! -l "56.980802, 4.530046" -st 10 -H 192.168.0.163 -P 50003 -dp -dg -ar 60

getting this error, is this because my password has a ! in it?
i tried --password="12341234!" and stuff like that, none seemed to work

**Comment by docrockulus** [comment]
Just -p

**Comment by TheRealGitCub** [comment]
The command you have listed has an error. Try this instead with just `-p` also, `-ar` is no longer needed: 

`runserver.py -a ptc -u loginname -p 12341234! -l "56.980802, 4.530046" -st 10 -H 192.168.0.163 -P 50003 -dp -dg`

**Comment by alloin** [comment]
oh thanks guys, removing -dp -dg -ar 60 fixed this, didnt notice this isnt supported anymore and it made it bug
runserver.py -a ptc -u loginname -password 12341234! -l "56.980802, 4.530046" -st 10 -H 192.168.0.163 -P 50003
works perfect
