### ISSUE TITLE
Blank map has returned

### ISSUE THREAD

**Issue by lnmtriet93** [AHAAAAAAA/PokemonGo-Map#1059]
I just tested the latest pull and it was a blank map at localhost:5000

**Comment by xijbx** [comment]
Yeah I'm getting this issue too - API key tried in both credentials.json and on command line.

**Comment by DerScreever** [comment]
for me work. im on latest commit
http://85.214.145.87:5000/

**Comment by sykhro** [comment]
We are aware of the issue, it's related to local storage. Should be fixed soon.

**Comment by sykhro** [comment]
Please purge your cache, cookies and local storage. It should solve the problem

**Comment by xijbx** [comment]
Can confirm purging cache and local storage fixes this - to anyone unsure you can do it all within Chrome dev tools panel. Hold on the refresh button and you'll have options to hard refresh & empty cache. And you can delete local storage from the resource tab of dev tools.

**Comment by lnmtriet93** [comment]
It worked! I confirm that purging cache and local storage helps fix this bug
