### ISSUE TITLE
Possible to Mark Captured Pokemons

### ISSUE THREAD

**Issue by SkyBadPT** [AHAAAAAAA/PokemonGo-Map#1060]
It would be great, and the new feature is when the user capture the pokemon have the option when click on it to mark as captured and the pokemon appear with one red X on it so the user will know that pokemon as been captured, and when the time expires it disappear, something like that would be cool

**Comment by DerScreever** [comment]
really nice idea!

**Comment by medghaim** [comment]
Duplicate of #1057. Closing.

SkyBadPT - Please don't open 2 issues for the same thing.
