### ISSUE TITLE
Not getting any new pokemons after awhile.

### ISSUE THREAD

**Issue by thomja** [AHAAAAAAA/PokemonGo-Map#1061]
Hello

So after a while, pokemons just stops adding into my maps and eventually. I have to restart the script. No warnings or anything. Old issue that still exists.

**Comment by backmeupplz** [comment]
+1 happened to me a couple of times

**Comment by Sejadis** [comment]
i guess still on master branch?

**Comment by thomja** [comment]
Somewhat old revision taken this morning. Just downloaded the latest version on the master branch and will see what happens.

**Comment by Bitti09** [comment]
@thomja  master branch is deprecated currently

**Comment by DerScreever** [comment]
use develop branch. this error is fixed.

**Comment by ykz89** [comment]
I have this same error on the develop branch

**Comment by medghaim** [comment]
Closing this issue as it is outdated. If this issue still persists on the `develop` branch, please reopen a new issue and update the information therein to reflect the new changes.

Please direct support questions to: https://discordapp.com/invite/Kzp4yky
