### ISSUE TITLE
Heroku deploy not working

### ISSUE THREAD

**Issue by famendola1** [AHAAAAAAA/PokemonGo-Map#1063]
I keep getting this error:
runserver.py: error: argument -p/--password: expected one argument

It say I am using it like this:
usage: runserver.py [-h] [-a AUTH_SERVICE] -u USERNAME [-p PASSWORD] -l  [-c] [-d] [-m] [-k GMAPS_KEY]

I am guessing that the -l flag is missing something

**Comment by xijbx** [comment]
What command are you running?

**Comment by sykhro** [comment]
Are you passing -c?

**Comment by famendola1** [comment]
This is the command:
python runserver.py -u <username> -p <password> -l <location> -st 10 -dp -ol -a
r 30 -H 0.0.0.0 -P 5250

**Comment by HinoReo** [comment]
You should actually do
python runserver.py -a ptc -u USERNAME -p PASSWORD -l "LOCATION, LOCATION" -st NUMBER -P PORT -H HOST
And it seems to me that you just haven't specified any of it

**Comment by famendola1** [comment]
I added the -a ptc part but I get the same error. Also, the username, password, and location are specified when I run it

**Comment by chaze117** [comment]
Remove the -dp param and should it start

**Comment by famendola1** [comment]
Removing the extra args worked but now I get this:
IOError: [Errno 2] No such file or directory: '/app/credentials.json'

I didn't make one because in the updated instructions it removed this part

**Comment by chaze117** [comment]
You have a credentials.example.json rename it to credentials.json and put youg Google map API key in the file.
You gan get the key here https://developers.google.com/maps/documentation/javascript/get-api-key

**Comment by famendola1** [comment]
That worked thanks
