### ISSUE TITLE
[Question] How to change the locale in the "Hide common Pokemon" list ?

### ISSUE THREAD

**Issue by Plop** [AHAAAAAAA/PokemonGo-Map#1064]
Hi,
Trying the latest develop commit, set the -L fr argument, Pokemon are in fr on the map, but the Hide common Pokemon is still in English. How can I change this ?

Thanks.

**Comment by sykhro** [comment]
Manually. That or wait for it to be implemented in the frontend

**Comment by Plop** [comment]
I can't find the file to change this. Where is it ?
Thanks

**Comment by Plop** [comment]
Bump. I would really like to translate it to french. But I can't find where to do the changes. :/

**Comment by medghaim** [comment]
Please direct support questions to: https://discordapp.com/invite/Kzp4yky
