### ISSUE TITLE
UI on iPad (iOS)

### ISSUE THREAD

**Issue by kingeddard** [AHAAAAAAA/PokemonGo-Map#1067]
## Expected Behavior

On safari (OS X El Capitan), "Hide Common Pokémon" lets you type in the desired Pokemon you wish to hide
## Current Behavior

On iOS (currently iPad), pressing on it will say "No options". I think it wants to use a scrolling list to check mark. 
![img_0162](https://cloud.githubusercontent.com/assets/15844285/17041293/0b9797e8-4f5a-11e6-8245-92fd83d7cc35.jpg)

## Possible Solution

I don't know of possible solution but if you add the page to your home screen you get a slightly different UI where the filter list will actually work. But this might help in finding a way for it to actually work ![img_0163](https://cloud.githubusercontent.com/assets/15844285/17041306/24938608-4f5a-11e6-8261-5356b7dd992e.jpg)
## Steps to Reproduce (for bugs)

1. Opening up on iOS, on local network (and also happens when opening it up through IPv6 port forward)
2.
3.
4.

## Context

Not much functionality is lost except being able to hide  Pokemon
## Your Environment

* Version used: Latest commit (91496fa53f5a1bf70c3a389c1fa339214fd44571)
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): run code on OS X El Capitan
Problem arises on iPad (iOS 9, Safari)

**Comment by TheRealGitCub** [comment]
Nice issue bro

**Comment by kingeddard** [comment]
Sorry guys, accidentally submitted it before writing. Please wait

**Comment by TheRealGitCub** [comment]
Lol k

**Comment by kingeddard** [comment]
@TheRealGitCub sorry, its updated now

**Comment by kingeddard** [comment]
Same issue occurs on iOS 9 (iPhone)
![img_2561](https://cloud.githubusercontent.com/assets/15844285/17041426/cb439b82-4f5a-11e6-8a24-d0cee3668c65.jpg)

**Comment by TheRealGitCub** [comment]
It looks like those colors aren't from the latest commit, try to pull the latest version real quick to make sure you're up to date.

**Comment by kingeddard** [comment]
the colors of the the maps or the UI bar? anyways, ran on the latest commit, the issue persists

**Comment by TheRealGitCub** [comment]
The colors of the text and whatnot in the UI. Basically it looks like the first one looks like it's missing the proper CSS that the second one has. That's the only fix I can think of

**Comment by BillyWM** [comment]
This looks like the same caching issue as discovered in https://github.com/AHAAAAAAA/PokemonGo-Map/issues/1086

You are getting a "slightly different UI" due to caching. Try clearing your cache and see if the issue persists (and if it does, please post another screenshot)

**Comment by kingeddard** [comment]
okay will do, will update soon

**Comment by kingeddard** [comment]
Cleared cache, and now works perfectly, thank you so much

**Comment by BillyWM** [comment]
No problem.

(Can a collaborator close? Thanks)

**Comment by Aaronucci** [comment]
Same happens regarding location as well.  Wants the scrolling list like the desktop however... no list to check.

**Comment by kingeddard** [comment]
@Aaronucci try opening it up in "private" and report back what you find and are you using the latest commit?

**Comment by Aaronucci** [comment]
@kingeddars in private it does the same thing.  Second to that there is nothing on the map at all, no stops, gyms, or pokes.






[http://i59.tinypic.com/oazofq.png]<http://tinypic.com?ref=oazofq>


Aaron Bianucci
aaron@bianucci.us<mailto:aaron@bianucci.us>
@AaronBianucci<http://www.twitter.com/AaronBianucci>
http://www.aaronbianucci.com


On Sat, Jul 23, 2016 at 12:55 AM -0500, "kingeddard" <notifications@github.com<mailto:notifications@github.com>> wrote:


@Aaronucci<https://github.com/Aaronucci> try opening it up in "private" and report back what you find and are you using the latest commit?

-

**Comment by kingeddard** [comment]
hmm, not the best person to help you, but i would suggest downloading the latest master, install the requirements and run once again in private mode, if that doesn't work, open up your own issue. 

Hope it works out!

**Comment by Aaronucci** [comment]
Thanks and I did.  I just added the info initially in case it was related and pointed then towards a fix.






[http://i59.tinypic.com/oazofq.png]<http://tinypic.com?ref=oazofq>


Aaron Bianucci
aaron@bianucci.us<mailto:aaron@bianucci.us>
@AaronBianucci<http://www.twitter.com/AaronBianucci>
http://www.aaronbianucci.com


On Sat, Jul 23, 2016 at 2:40 AM -0500, "kingeddard" <notifications@github.com<mailto:notifications@github.com>> wrote:


hmm, not the best person to help you, but i would suggest downloading the latest master, install the requirements and run once again in private mode, if that doesn't work, open up your own issue.

Hope it works out!

-
