### ISSUE TITLE
Don't use ES6 template strings (backticks)

### ISSUE THREAD

**Issue by BillyWM** [AHAAAAAAA/PokemonGo-Map#1069]
These aren't compatible with IE11, or the Android stock browser/webview

You'll have to use .replace() on these strings instead

Alternatively Babel can transpile things like this, but taking a quick look at your gruntfile, you don't seem to be using Babel.

For more ES6 compat information:
https://kangax.github.io/compat-table/es6/
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

**Comment by Maxincredible52** [comment]
the question is why would a sane person use either ie11 or a browser that can't even handle es6? ^^

**Comment by BillyWM** [comment]
Consult the chart I linked: only Safari on Mac is 100% yet. ES6 isn't "here" yet.

And yes, we all know IE sucks, but compat with IE11 is still a reasonable expectation for now.

**Comment by BillyWM** [comment]
On further review, there's a PR for this and more commentary here: https://github.com/AHAAAAAAA/PokemonGo-Map/commit/39d3acffb129d142cdb61dc89b159aac044aff1c
