### ISSUE TITLE
new step value does not show

### ISSUE THREAD

**Issue by daproject85** [AHAAAAAAA/PokemonGo-Map#1070]
I set step to 10, ran then stopped, then changed to 1, however all elements in the 10 radius showed up

**Comment by hgentry** [comment]
They're still there from last time. The results are stored in a database file, not program memory

**Comment by chaze117** [comment]
Try delete pogom.db

**Comment by daproject85** [comment]
@chaze117 @hgentry thank you both of you guys for clarifying it for me. On an unrelated note. I am a total google map NEWB. I have a 25000 limit. What defines a request? While the server is running and refreshing? or when ever I hit the url? does it include moving around the map? does it including zooming out and in?

**Comment by daproject85** [comment]
@chaze117 @hgentry does it also mean all the pokemon values are also there ? or do those get updated and thats only for pokestops and gyms

**Comment by peda** [comment]
@daproject85 as long as you are using the map alone or with a hand full of friends you will most likely never hit the 25000 limit

**Comment by daproject85** [comment]
@peda thanks man for making it simple. QQ about the DB, since the pokestop and gyms seem to presist unless i delete it before i restart server. Do the pokemon info persist too? so a pokemon will never vanish?

**Comment by chaze117** [comment]
I think it is a full data wipe so everything will be gone, if you want just remove pokemons wait until they experies and will disappear in 2-3 secs after if you using the lastest dev build.

**Comment by daproject85** [comment]
would it be a valid ER to deleted it every time the server runs?

**Comment by chaze117** [comment]
It's totally unecessary. For example you shut down a server for like 25 mins. All the pokemon will disappear and when you start the server again new ones will be on the map.

**Comment by daproject85** [comment]
@hgentry @chaze117 @DerScreever can anyof you guys explain something? I am a newb. So if everyone is checking code in ... who moderates it? if i lets say check something in and I add a class to a file and you feel like that class should be there... who has a say
