### ISSUE TITLE
Pokemon moving away from location point per scan

### ISSUE THREAD

**Issue by Ayysir** [AHAAAAAAA/PokemonGo-Map#1074]
On initial refresh its fine but as it continues, pokemon tend to only show up in a square grid pattern. 
As it further refreshes, everything dies and pokemon disappear.

 
![untitled-poke](https://cloud.githubusercontent.com/assets/1954355/17041468/3909a274-4f74-11e6-9a9e-1d3435ef638b.png)

**Comment by mikeporterdev** [comment]
Many steps are you running this with? It looks very high from the picture.

**Comment by Ayysir** [comment]
@mikeporterdev 20 steps

**Comment by mikeporterdev** [comment]
Thats 400 scans needed. How long does it take the scanner to complete a full cycle, if it's more than 15 minutes, your issue is that the Pokémon are expiring before the scanner can get back to that block.

**Comment by chaze117** [comment]
Try to run multiple scanners with different coords and smaller radius

**Comment by Ayysir** [comment]
whats recommended steps

**Comment by chaze117** [comment]
I usually set 5 or 6. Start the server see what covers the radius go google maps try to find a new coord to a 2nd scanner and set it up and start it over.

**Comment by FrostTheFox** [comment]
I personally run 10 steps, and it works good for me.

**Comment by Ayysir** [comment]
thanks!
