### ISSUE TITLE
Nothing displayed on iPhone 6s iOS 9.3.3 (works on iPhone 4s 9.3.2 & iPhone 5s 9.3.2)

### ISSUE THREAD

**Issue by Schwaitz** [AHAAAAAAA/PokemonGo-Map#1076]
## Expected Behavior
To work on my iPhone 6s.

## Current Behavior
* Does not work on iPhone 6s (9.3.3)
* Works on iPhone 4s (9.3.2)
* Works on iPhone 5s (9.3.2)

## Possible Solution
**Currently updating my iPhone 4s to iOS 9.3.3 to see if that is the problem**, as both iPhones with 9.3.2 are working. Will comment once it finishes updating.

If it does not work, I would assume it is a problem with iOS 9.3.3 compatibility. If it does work, I would assume it is a problem with the iPhone 6s compatibility.

## Your Environment
* **Version used:** Dev branch
* **Environment name and version:** Python 2.7, hosted on Linux (Ubuntu 14.04)
* **Operating System and version:** iPhone 6s (9.3.3)

## Additional Information

I am using Safari web browser.

**Comment by Schwaitz** [comment]
I have updated my iPhone 4s to iOS 9.3.3 and it **DOES WORK**.

This seems to be a problem with the iPhone 6s, and not iOS 9.3.3. Can someone else with an iPhone 6s confirm?

**Comment by orjen** [comment]
Works just fine on 6s/9.3.2, both on Safari and Chrome.

**Comment by Schwaitz** [comment]
Solved. Does not work when browser is in "private" mode.
