### ISSUE TITLE
Pokemon on app differ from the map

### ISSUE THREAD

**Issue by KensonN** [AHAAAAAAA/PokemonGo-Map#1077]
While the PokemonGo-Map shows no Pokemon near my location, the app shows some Pokemon near my location. I currently have a step distance of 2.

**Comment by MonkeyLeeT** [comment]
Which app are you talking about?

**Comment by jabelone** [comment]
Try increasing the step distance a bit.  I find a distance 5-10 will do a few blocks.  Are you running any incense or stuff on the app?  The map doesn't have any sort of incense applied etc.

**Comment by KensonN** [comment]
MonkeyLeeT: I am talking about the nearby tab on Pokemon Go

jabelone: I am not using incense right now. I've used 5, but all the Pokemon are far away.

**Comment by Nicknack1234** [comment]
The nearby tab is pretty broken, I wouldn't use it as the basis of a bug with this repo.

**Comment by KensonN** [comment]
I'm using it as a basis for the bug because with the master branch, the pokemon shown on the map corresponded to the nearby tab. When I switched to the dev branch, it didn't correspond anymore.

**Comment by Slivo-fr** [comment]
Same issue there. Master does show same pokemon as app nearby, but dev does not show some of them. Same range settings

**Comment by medghaim** [comment]
Closing this issue as it is outdated. If this issue still persists on the `develop` branch, please reopen a new issue and update the information therein to reflect the new changes.

Please direct support questions to: https://discordapp.com/invite/Kzp4yky
