### ISSUE TITLE
Question, remove info in the command window

### ISSUE THREAD

**Issue by thomja** [AHAAAAAAA/PokemonGo-Map#1080]
Hey

Where do you do the outputs to the console window? I have added some of my own outputs which I consider are important for me but they tend to get swept away very quickly among all of the things the code outputs. I'd like to remove some of your outputs so that I can see what mine days before they get scrolled up in the command window.

Thanks.

**Comment by aj12ay** [comment]
They are all pretty much print statements in the code.  Go to example.py and remove the print statements from it and all the files that it calls.

**Comment by jabelone** [comment]
Just search through the python program for the print statements.

**Comment by thomja** [comment]
Example.py is from the master revision which is deprecated. It no longer exists.

I did. I could only find one. I removed it and nothing happened.

**Comment by shadow7412** [comment]
They wouldn't be print statements... they would more likely be `self.log` statements.

**Comment by thomja** [comment]
Thanks, now I found some stuff, I tried to comment it out but just ended up with a bunch of errors... This spaghetti code man.

**Comment by medghaim** [comment]
Closing this issue as it is outdated. If this issue still persists on the `develop` branch, please reopen a new issue and update the information therein to reflect the new changes.

Also, please be aware of the incredibly helpful and supportive community at: 
https://discordapp.com/invite/Kzp4yky
