### ISSUE TITLE
Pokemon show up, however the map does not!

### ISSUE THREAD

**Issue by Zach1993** [AHAAAAAAA/PokemonGo-Map#1081]
## Current Behavior
The map should display roads and data. When I updated to the newest commit the roads are now gone.

## Your Environment

* Version used: most recent commit
<img width="1231" alt="screenshot 2016-07-21 16 37 16" src="https://cloud.githubusercontent.com/assets/14190752/17042365/d64cf3b4-4f61-11e6-8bca-1aae8ce406c1.png">

* Python 2.7
* Mac

**Comment by neruve** [comment]
I am running Python 2.7 and windows and have this same issue. Any input?

**Comment by duncanleo** [comment]
I've looked into it and it is an issue with the local storage of the webpage. If you clear the browser cache or use a browser that has never visited the page it works.

**Comment by chaze117** [comment]
Are you using master or dev branch ?

**Comment by neruve** [comment]
dev branch. I like the filter features that don't seem to be in master.

**Comment by Zach1993** [comment]
@chaze117 Dev Branch.

**Comment by chaze117** [comment]
I got this bug when I set the location to city name, the bug disappeared when used coordinates from google maps

**Comment by Zach1993** [comment]
@duncanleo I tried that, did not work for me. Also, now everything is just expired.

**Comment by duncanleo** [comment]
@Zach1993 maybe try using an incognito session?

**Comment by Zach1993** [comment]
<img width="256" alt="screenshot 2016-07-21 11 04 34" src="https://cloud.githubusercontent.com/assets/14190752/17042731/0c45f3aa-4f65-11e6-8eea-3de17b53ef71.png">

**Comment by neruve** [comment]
clearing the cache worked for me. You have to clear it after you close that page.

I closed browser, then opened new session, then cleared cache, then closed, re-opened and then went to localhost:5000 and everything has been working

Windows 10 with Edge browser

**Comment by chaze117** [comment]
Maybe a faster method not just refresh the page with normal method (F5) but a force reload all stuff and maybe clear some cache Ctrl+F5

**Comment by Maxincredible52** [comment]
clearing cache and browser data for that specific domain i am running the map on did the trick for me
