### ISSUE TITLE
Ubuntu Install issues

### ISSUE THREAD

**Issue by HueKall** [AHAAAAAAA/PokemonGo-Map#1082]
Hi All hope you can help,

I get the following errors when trying to run the program but i think this is due to an error when installing the dependencies.

Python v 2.7
Ubuntu 14.04

When attempting to execute the command the following happens:
PokemonGo-Map-develop$ python runserver.py -a ptc -u MYUSER -p MYPASSWORD -l "MYLOCATION" -st 10
Traceback (most recent call last):
  File "runserver.py", line 10, in <module>
    from pogom.app import Pogom
  File "/BORING PATH/PokemonGo-Map-develop/pogom/app.py", line 5, in <module>
    from flask import Flask, jsonify, render_template, request
ImportError: No module named flask

But i did get the following error during the install after using "pip install -r requirements.txt"

"pkg_resources.VersionConflict: (six 1.5.2 (/usr/lib/python2.7/dist-packages), Requirement.parse('six>=1.9'))

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_frank/protobuf-to-dict
Storing debug log for failure in"

Probably something simple but this has be stumped,

**Comment by HueKall** [comment]
Sorry forgot to add i have had a search of the existing issues and install guide but had no joy.

**Comment by medghaim** [comment]
pip install -r requirements.txt

For future reference, please take support/setup questions to: https://discord.gg/3AX2Y
