### ISSUE TITLE
Google AppPasswords for 2Factor accounts are 16 chars but script trims to 15 chars

### ISSUE THREAD

**Issue by kneel23** [AHAAAAAAA/PokemonGo-Map#1083]
I couldn't get the google accounts to work (PTC ones worked fine) and I read in the FAQ that you need to use Google App password for 2Factor'ed accounts.   I created a new one in my google account (its always a 16-char string) and when I try to pass it, the script trims it to 15 and returns the following(below).  
I had tried regular password which did not work and led me to the FAQ and this still didn't work.     While I do have a PTC account i can use, I assume the new PTC account will not see the same higher-level Pokemon that, say, someone at level 20 would see?
__________________________________
[!] PTC login for: foo@gmail.com
[!] Trimming password to 15 characters
Your username or password is incorrect. You have 1 attempts left before you will be locked out of your account for 15 minutes.

**Comment by FrostTheFox** [comment]
What command are you running to start?

**Comment by FrostTheFox** [comment]
I think you're missing something.

**Comment by kneel23** [comment]
I am leaving out the -p [Password] and it asks me for it.  Same command works with PTC account.  Not sure why its trimming to 15 characters is all. 

python example.py -a ptc -u foo@gmail.com -l  "[LAT] [LNG]" -st 10

**Comment by FrostTheFox** [comment]
Set -a google

Also, as far as I know, lower and higher level accounts show no difference in pokemon.

**Comment by ctdearborn** [comment]
Are you trying to use a google account? If so you need to change "-a ptc" to "-a google"

**Comment by kneel23** [comment]
Oh duh.  Thanks
