### ISSUE TITLE
Pokemon number completely off, map not showing up, all pokemon are expired.

### ISSUE THREAD

**Issue by Zach1993** [AHAAAAAAA/PokemonGo-Map#1085]
I am running Python 2.7. 
The problem I am encountering is that
I have cleared my cache to see if it was a local host problem, that did not solve it.
It appears that the Pokemon being displayed are accurate, just the time on them and their information (their number) is incorrect. The pokemon are being updated on my command line just fine. Any ideas? I have been looking through the previous commits but have not been able to narrow it down.
<img width="1280" alt="screenshot 2016-07-21 17 04 26" src="https://cloud.githubusercontent.com/assets/14190752/17042792/a1b5a53e-4f65-11e6-8872-ef74fb46043b.png">

**Comment by KeithPetro** [comment]
Are you on master branch? A recent commit to dev branch changed a function call to fix this issue (two parameters were mixed up, specifically pokemon ID and time).

**Comment by FrostTheFox** [comment]
You're running an old version it looks like. Redownload develop and try again.
