### ISSUE TITLE
Hide common Pokemon doesn't work on mobile

### ISSUE THREAD

**Issue by mark-rodgers** [AHAAAAAAA/PokemonGo-Map#1086]
## Current Behavior
Hide common Pokemon does not work when viewing the map on my phone (Samsung Note 5). When I click the text field where I am supposed to type in names or Pokemon to hide, nothing happens.

## Steps to Reproduce (for bugs)
1. Visit the map in browser on phone
2. Click filter button
3. Click the text box labeled Hide common Pokemon
4. Voilà, broken.

## Your Environment

* Version used: #b4ce978
* Environment name and version (e.g. Python 2.7): Python 2.7.10
* Operating System and version (desktop or mobile): Samsung Note 5

**Comment by npeep** [comment]
I got this working on my Galaxy S6, in Chrome by:

1. Launching site
2. Selecting "Request Desktop Site" or whatever in the options.
3. Check things out, hide a pokemon.  You will not be able to pan/zoom with touch controls.
4. Un-toggle the "Request Desktop Site" or whatever option.
5.  Things should be working, and you will be able to pan around and zoom with your fingers :)

**Comment by mark-rodgers** [comment]
While that is a temporary work around the HTML/CSS just needs to be messed with to get that working

**Comment by medghaim** [comment]
I believe the android app is almost ready :)

**Comment by BillyWM** [comment]
1. Which browser are you using on the Note 5? The stock browser?
2. Does your map page load at all?

I have the stock Android browser as well as Chrome and Firefox on my Android phone, and I'm able to use this feature on the latter two. The map doesn't work at all in the former, because of unrelated broken Javascript.

**Comment by jeckoz** [comment]
guys how to open from phone? im noob at this , pls help

**Comment by BillyWM** [comment]
@jeckoz: Some common questions are covered in the wiki - https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/How-to-make-your-map-available-externally

**Comment by mark-rodgers** [comment]
The map does load but the webui filter input does not work. Running Chrome on Android Marshmallow

**Comment by BillyWM** [comment]
Hmmm, I'm also running Chrome on Android 6 and can't reproduce this.

**Comment by mark-rodgers** [comment]
When I click on the common Pokemon filter all it does is highlight blue. I don't get any drop down nor do i get a keyboard to type
http://i.imgur.com/rH0BG2K.png

**Comment by BillyWM** [comment]
I hit your site on my phone and this is what I see on Chrome on Android 6. Very strange.

![screenshot_2016-07-21-23-29-26](https://cloud.githubusercontent.com/assets/288075/17048556/b44692fe-4f9b-11e6-917e-93f15b2e4381.png)

**Comment by mark-rodgers** [comment]
I noticed the sidebar looked a bit different on your screenshot and the icon on the top left was different. Then it hit me. previous dev branch webui was cached. Cleared cache and all is good. Thanks for the screenshot
