### ISSUE TITLE
Heroku map not loading

### ISSUE THREAD

**Issue by MrThreepwood** [AHAAAAAAA/PokemonGo-Map#1087]
After importing the map to heroku, the map will load, but only for a few brief seconds, afterward it will simple say:

Oops! Something went wrong.
This page didn't load Google Maps correctly. See the JavaScript console for technical details.

However, nothing out of the ordinary shows up. After refreshing again, the exact same thing happens.

I would provide a link to the app, but as it's not working I had to delete it (as there is no way to stop the server once it's uploaded to heroku).

**Comment by FrostTheFox** [comment]
Have you put your own GMaps key in credentials.json?

**Comment by MrThreepwood** [comment]
Yes I have. Using the exact same computer and the same browser (chrome), I am unable to reproduce the issue when I run the service locally.

**Comment by FrostTheFox** [comment]
In that case, I'm not too sure. Heroku instances have been having some issues recently. What did your browser console say? (right click > Inspect > Console)

**Comment by MrThreepwood** [comment]
Hmm, it said I went over my daily limit using that key. However, as best I can tell it's not causing any issues on my local machine. However, using a new key is causing it to work.
