### ISSUE TITLE
Does not find all pokemon

### ISSUE THREAD

**Issue by shme14** [AHAAAAAAA/PokemonGo-Map#1090]
## Expected Behavior
Two servers with overlapping areas should find the same pokemon in those areas.

## Current Behavior
They do not. They are missing some.

## Steps to Reproduce (for bugs)
Start two separate servers that have overlapping areas and wait.

*Notice the extra Pidgy and Paras
These pics are taken 10 secs apart after multiple server loops. Both the missing pkm have more then 5 mins left.

![capture](https://cloud.githubusercontent.com/assets/16787928/17043226/cefe1952-4f71-11e6-8506-f6e0d518d812.PNG)
![capture2](https://cloud.githubusercontent.com/assets/16787928/17043225/cefd779a-4f71-11e6-8296-002ab77ef3f1.PNG)

## Steps to Fix
Follow the steps here:
https://github.com/AHAAAAAAA/PokemonGo-Map/issues/1105

"Changing the scan steps to 0.002 for Longitude and 0.0012 for Latitude provides a much more complete coverage:"

**Comment by shme14** [comment]
Here is another example
![untitled](https://cloud.githubusercontent.com/assets/16787928/17043407/8d1c1262-4f73-11e6-8bb5-7cebf78248c6.png)
![untitled2](https://cloud.githubusercontent.com/assets/16787928/17043406/8d187ff8-4f73-11e6-8b61-06b91cf292d0.png)

**Comment by KMFSousa** [comment]
I also have this issue in the fact that it does not always find all the Pokemon. Compared to the in app "Nearby" feature (which I know barely works) and the Pokemon that show up near my character. This has exhibited its self with Eevee's and Venonat just in the last few minutes. As this is the primary purpose of this hopefully it can be fixed quickly.

**Comment by FoxxMD** [comment]
This was also reported in #998 ([and here are my screenshots of differences](https://github.com/AHAAAAAAA/PokemonGo-Map/issues/998#issuecomment-234425990))

**Comment by Skullmonkey** [comment]
Can also confirm side by side with master branch, dev is not as populated as master.

**Comment by medghaim** [comment]
This is confirmed and being discussed. Currently trying to hunt down the issue. It's not just step size alone -- although reducing that is an improvement, but it is not a fix entirely.

**Comment by aedm** [comment]
Reducing step size to 0.002 made things much better for me.

You could try my solution until a more robust solution is worked out:
https://github.com/AHAAAAAAA/PokemonGo-Map/pull/1093

**Comment by shme14** [comment]
Posted a solution in the original post

**Comment by MonkeyLeeT** [comment]
Closing this issue as it is outdated. If this issue still persists on the `develop` branch, please reopen a new issue and update the information therein to reflect the new changes.
