### ISSUE TITLE
ld error -lpython2.7

### ISSUE THREAD

**Issue by MrCarlosJr** [AHAAAAAAA/PokemonGo-Map#1094]
I'm try run  sudo pip install gpsoauth==0.3.0
but have error:

gcc -pthread -shared -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld build/temp.linux-x86_64-2.7/src/MD2.o -L/usr/lib64 -lpython2.7 -o build/lib.linux-x86_64-2.7/Crypto/Hash/_MD2.so
    /bin/ld: cannot find -lpython2.7
    collect2: error: ld returned 1 exit status
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-k3oWzv/pycryptodomex/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-3GRTQx-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-k3oWzv/pycryptodomex/

**Comment by TheRealGitCub** [comment]
run `apt-get install build-essentials`

**Comment by MrCarlosJr** [comment]
http://pycryptodome.readthedocs.io/en/latest/src/installation.html
