### ISSUE TITLE
Document Wiki Usage Page

### ISSUE THREAD

**Issue by elubin** [AHAAAAAAA/PokemonGo-Map#1097]
Can someone please document the Wiki Usage page with the details of each parameter?  Is there a parameter that would limit the radius of my search?  Once I set the Location, I only need to see within 2-3 miles.

usage: runserver.py [-h] [-a AUTH_SERVICE] -u USERNAME [-p PASSWORD] -l LOCATION -st STEP_LIMIT [-i IGNORE | -o ONLY] [-ar AUTO_REFRESH] [-ol Display only lured Pokestops] [-H HOST] [-P PORT] [-L LOCALE] [-c] [-d] [-m] [-k GMAPS_KEY]

-h : what is h?
-u : username
-p : password
-l : location specified as GPS coordinates like "50.18383, -79.87778"
-st : what is step limit?
-i : ignore what?
-o : only what?
-ar : auto refresh what?

Thanks!  Nice work so far!

**Comment by Drogean** [comment]
h = shows the help screen

this is the only command you need to know, as it will show all valid -switches you can use

ar = used to be auto refresh the webpage icons but it no longer works for this version as of me typing this
o = no longer used
i= no longer used

basically everything was re-written so the usage page is outdated

**Comment by Zach1993** [comment]
use -st, step limit is how far away from your location you want to search. So if you want to see 2-3 miles I am not sure exactly what it would be but probably around 15.
