### ISSUE TITLE
Code question

### ISSUE THREAD

**Issue by daproject85** [AHAAAAAAA/PokemonGo-Map#1099]
Hi guys ,

I'm sorry I'm a newb idk if this is the right place to ask. I'm amazed and fascinated by this ,

How does one know the data structure from niantic ? How do you know their APIs? If they are not publish how are we accessing them ?

**Comment by TheRealGitCub** [comment]
It was "decoded" per-se by people on the PokemonGoDev subreddit. Check out the post explaining the APIs right here: https://www.reddit.com/r/pokemongodev/comments/4svl1o/guide_to_pokemon_go_server_responses/

**Comment by medghaim** [comment]
Closing as this is not an issue. Check the above link for a detailed guide about server requests and response structure!
