### ISSUE TITLE
Suggested Wiki FAQ addition pertaining to gcc missing

### ISSUE THREAD

**Issue by TheRealGitCub** [AHAAAAAAA/PokemonGo-Map#1100]
I attempted to fork and make a pull request for the wiki without realizing that GitHub does not support doing so. I've noticed a few Issues opened up (#1094, #954, #620, #582, #407) where users attempt to run the script without having `gcc` installed. Here's the text of what I wrote:

```
Q: `error: command 'gcc' failed with exit status 1` or `[...]failed with error code 1 in /tmp/pip-build-k3oWzv/pycryptodomex/`  
A: Your OS is missing the `gcc` compiler library. Run `apt-get install build-essentials`
```

**Comment by MonkeyLeeT** [comment]
Done. Thanks!
