### ISSUE TITLE
Gym info box opens twice

### ISSUE THREAD

**Issue by broder22** [AHAAAAAAA/PokemonGo-Map#1103]
## Expected Behavior
Gym info box does not open a second time on top of itself.

## Current Behavior
A second info box opens above the first when a gym is selected and the cursor hovers over its icon. Upon closing both boxes, the info screen will sometimes stay open after hovering over the gym icon again (a different bug?).

## Steps to Reproduce (for bugs)

1. Click on a gym icon, opening its info box.
2. Move the cursor away and wait a few seconds.
3. Hover over the same gym icon

## Your Environment

* Version used: Develop branch
* Environment name and version: Python 2.7.9
* Server: Debian 8.5
* Client: Chrome 52 on Windows 10

**Comment by MonkeyLeeT** [comment]
Closing this issue as it is outdated. If this issue still persists on the `develop` branch, please reopen a new issue and update the information therein to reflect the new changes.
