### ISSUE TITLE
Possible gaps in search pattern

### ISSUE THREAD

**Issue by hazanjon** [AHAAAAAAA/PokemonGo-Map#1105]
I have raised a PR #1102 which shows visually on the map a 100m circle around the coords that have been loaded from the API. This seems to show that the current search step of 0.0025 Is actually too large for Latitude (And partially Longitude). This can be seen in the image below:

![scanned locations](https://cloud.githubusercontent.com/assets/1560723/17044439/fa01f89e-4fb7-11e6-8bc4-3e752c299333.png)

The current search is leaving large horizontal strips of the map unsearched.

## Possible Solution

Changing the scan steps to 0.002 for Longitude and 0.0012 for Latitude provides a much more complete coverage:

![tight locations](https://cloud.githubusercontent.com/assets/1560723/17044527/a7e1424e-4fb8-11e6-9746-25f09bf5b410.png)

This does lead to a duplication of search area, to optimise this I would think running the search as two passes would be beneficial. Each pass taking alternating locations.

**Comment by reyqn** [comment]
#776 will fix it. But yeah you can do that at the moment. 0.00126 should be better

**Comment by FrostTheFox** [comment]
We're working on all of this, please standby.

**Comment by arianizadi** [comment]
Hey i am testing to see if your solution is working. So far it is! @hazanjon

**Comment by ericpadilla** [comment]
where could you change the steps @haranjon? I would love to try it out

**Comment by arianizadi** [comment]
hey @ericpadilla i made a video how to https://www.youtube.com/watch?v=y5qvVBFW-B0 its not the best video but its something.

**Comment by hazanjon** [comment]
@ericpadilla You can change the values in search.py line 38

`yield (x * 0.0012 + initial_location[0], y * 0.0020 + initial_location[1], 0)`

**Comment by hazanjon** [comment]
Actually it may be better to change the pattern entirely to be a Hex pattern

![pattern](http://i.stack.imgur.com/XI4um.png)

**Comment by hazanjon** [comment]
@reyqn Sorry missed your link to #776. You right that will fix this completely :)

**Comment by talentedmrripley** [comment]
Can we get #776 merged soon?

**Comment by hazanjon** [comment]
Closing as this is now fixed
