### ISSUE TITLE
How to run developer zip....there is no example.py file in it

### ISSUE THREAD

**Issue by ashish2612** [AHAAAAAAA/PokemonGo-Map#1108]

**Comment by Imacellist** [comment]
I just merged it with the master branch and it worked.

**Comment by ashish2612** [comment]
You mean to say company developer zip to master zip

**Comment by ericpadilla** [comment]
asish, use the master file for stable version . dev version uses runserver.py

**Comment by FrostTheFox** [comment]
Don't put the developer and master together, put develop separately and use runserver.py instead of example.py.

**Comment by ashish2612** [comment]
its is asking gmaps_key ....how to generate it

**Comment by FrostTheFox** [comment]
https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Google-Maps-API:-a-brief-guide-to-your-own-key

**Comment by medghaim** [comment]
Please take support questions to https://discord.gg/3AX2Y

Closing as this is not an issue.
