### ISSUE TITLE
Heroku doesn't auto update pokemon after timers expire

### ISSUE THREAD

**Issue by shotgunsam419** [AHAAAAAAA/PokemonGo-Map#1112]
## Expected Behavior
Pokemon should re-spawn after the timers expire

## Current Behavior
Pokemon disappear after the timers expire and then I'm left with an empty map.

## Possible Solution
Changing the config under STEP_COUNT refreshes the pokemon. Need to somehow automate this every few minutes or so. 

##Platform
Using the deploy to horoku button

**Comment by hi4c0ck** [comment]
If Pokemon disappear - that means it's disappearin real due original timer. 
if you mean Heroku re-scan issue (crushes after first scan) - there is problem - https://github.com/AHAAAAAAA/PokemonGo-Map/issues/965

**Comment by shotgunsam419** [comment]
The problem is that new pokemon aren't being put onto the map, if I wait long enough, all the pokemon timers run out, and the map is empty until I reset horuko(either by changing the steps or toggling). So yeah, I guess there's an issue in re-scanning then.

**Comment by dronloko** [comment]
Same to me
Thus I've set HOST & PORT variables in Heroku's settings. Now autorefresh in my app works fine :)

**Comment by nenadzero** [comment]
@dronloko Where ? In Config Variables ?

**Comment by dronloko** [comment]
@nenadzero Yeah. In Config Variables I've clicked the "Reveal Config Vars" button and set the HOST variable to "0.0.0.0" and PORT variable to "80"
Like, everything is OK
