### ISSUE TITLE
TypeError: cannot concatenate 'str' and 'ChunkedEncodingError' objects

### ISSUE THREAD

**Issue by HenrySia** [AHAAAAAAA/PokemonGo-Map#1113]
> Exception in thread search_thread:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
>     self.run()
>   File "/usr/lib/python2.7/threading.py", line 754, in run
>     self.__target(*self.__args, **self.__kwargs)
>   File "/home/mediaserver/PokemonGo-Map-develop5/pogom/search.py", line 100, in search_loop
>     search(args)
>   File "/home/mediaserver/PokemonGo-Map-develop5/pogom/search.py", line 77, in search
>     response_dict = send_map_request(api, step_location)
>   File "/home/mediaserver/PokemonGo-Map-develop5/pogom/search.py", line 30, in send_map_request
>     log.warn("Uncaught exception when downloading map "+ e)
> TypeError: cannot concatenate 'str' and 'ChunkedEncodingError' objects

## Expected Behavior
The error should be gracefully handled.

## Current Behavior
Once this happens, no pokemon shows up on the map

## Steps to Reproduce (for bugs)

1. python runserver.py -st 10 -H 0.0.0.0 -P 9004 -u "username" -p "password" -l "Seattle, WA" -k "GoogleServerAPI"

## Your Environment

* Version used: 991a27ef4fb23b3fedf829f1449db46513861638
* Environment name and version (e.g. Python 2.7): Python 2.7.11
* Operating System and version (desktop or mobile): Ubuntu 14.04

**Comment by MonkeyLeeT** [comment]
Closing this issue as it is outdated. If this issue still persists on the `develop` branch, please reopen a new issue and update the information therein to reflect the new changes.
