### ISSUE TITLE
Decouple GUI from API

### ISSUE THREAD

**Issue by coolaj86** [AHAAAAAAA/PokemonGo-Map#1115]
The GUI is becoming a monster (requiring all of ruby, python, and node to build... ugh...), but it could easily be decoupled from the backend (I think the Google Maps API Key is the only thing actually used in the template).

Can we decouple the gui (and maybe get rid of sass?) so that it's just a node project (not a node+ruby+python project) and this remains just a python project?

Perhaps that way we can get more people involved in each of the products individually, with simpler installations for each, and without having to be experts in the package management systems in 3 different programming languages.

I'm working on the node API and trying to get it to the point where it's compatible with this GUI, but I'm on a crummy network connection this week and trying to debug why which version of which python and which ruby dependencies are failing to install for what reason (a lot of network resets) is... annoying...

**Comment by BillyWM** [comment]
What is sass used for currently? Is it just preprocessing an off-the-shelf CSS library? It would make sense to nix it and use pre-minified CSS for that, until it gets to the point that devs here are writing tons of custom CSS and actually need Sass.

I agree depending on 3 different environments is crazy, but is there a Python replacement for Grunt that could do everything Grunt plugins are doing currently, across Win, Mac, Linux?

**Comment by coolaj86** [comment]
That is the question!

What *is* sass being used for?

Why is there grunt at all?

There are 30 million pokemon go users, mostly between the ages of 15 and 30, many of which are a little technical and nerdy, few of whom are the technical elite.

Things like sass, grunt, ES6, etc are simply hipster crapification of the code!!!

There's hardly any documentation for this library, but instead of focusing on what will bring the code down to the level of the type of person that wants to use the code, some group of hispter elite coders decided that it would be cool to overcomplicate the project with the latest and greatest and coolest features that add no value (this thing isn't going on production servers, it doesn't need to be minified or split into hundreds of sub-modules as if it's a gigantic corporate app).

Forgive the angry rant, but how about we structure this thing simply and **reduce** the number of dependencies so that it reaches a larger audience of the target market and provides them the opportunity to participate in a worldwide sensation.

How awesome would it be for a high school student to be able to say that he got this running on his own home server for his friends? Or that he even contributed!?

With limited time, I want to contribute and I am an expert programmer who has used all of python, ruby, and node.js quite a bit and some config files somewhere are a little wonky on my system, I'm out in the boonies where the satellite internet is intermittent and seems to be causing dep downloads to fail, and I haven't been able to successfully build the GUI yet.

**Comment by DevAndArtist** [comment]
I'd love to build a native iOS app in Swift, which only receives some information packages from the backend. :) That would make it way easier and this will allow us to variate the UI.

**Comment by BillyWM** [comment]
I think real hipsters could use Gulp over Grunt :)

For *running* the app, I think it should be Python only. No Node/NPM, no Sass.

For development, I think it's okay to have a slightly higher barrier to entry. In my experience NPM is less of a pain than Pip. The extra install steps would be typing npm -g a bunch of times then npm install to get local dependencies.

That said, I do agree that this project isn't big enough yet to really justify using Grunt (and definitely not Sass). There's one main JS file (map.js) and then  some external libraries. Bundle the externals manually, and have two script tags. Bundling is a best practice to avoid excess HTTP requests which speeds up overall page load....but here we're talking 2 requests vs 1. It hardly matters.

Maybe I'm biased because I already have this stuff installed and know how to use it, but I'm neither strongly in favor of removing it or keeping it.

***ES6 and Babel***

At work I write all ES5. On personal projects I write ES6 with Node 6 and Babel.

ES6 brings some nice conveniences. You don't *need* it because, well....I write ES5 every day, so clearly not! But we could write *better* code with it. Right now all it's doing is parsing some ES6 template strings, but it could be more useful. And the JS could use some help in the quality department.

-------------

I'd be willing to write the docs that help prospective developers set up Node and Grunt, to lower the barrier to entry.

**Comment by coolaj86** [comment]
-1 ES6 it doesn't work in normal browsesr. Why require additional build steps when the benefit is very *very* marginal and using normal javascript the dev file would work in a very large variety of browsers (android, ios, win, chrome, safari, edge, firefox, etc) with no special considerations.

**Comment by coolaj86** [comment]
PR https://github.com/AHAAAAAAA/PokemonGo-Map/pull/1612 begins to address this issue.

**Comment by BillyWM** [comment]
I'm not a rubyist and definitely not a Java dev (ew). I enjoy Javascript and I like ES6. (I LOVE it on the server; callback-hell is asinine. Synchronous appearing generators or ESNext async/await constructs are so much easier to reason about than deeply nested callbacks bouncing you around like they're GOTO statements).

Arrow functions, for example, which "look like Ruby" weren't put into the standard for cool factor. They also preserve the surrounding scope, which makes your life easier (no _self trick or .bind).

But this is just a programming-language holy war that isn't going to go anywhere.

**Comment by BillyWM** [comment]
And re: ES6 doesn't work in normal browsers

It's piecemeal. A lot of it works in normal browsers. Safari on Mac has full support. Chrome, Firefox, and Edge on desktop are around 90%+. Node 6 is over 90% without harmony flags. But mobile is lagging. Using Babel to compile, you can stop worrying about what is supported where, and then, in a few years when ES6 is everywhere, you can drop Babel altogether.

http://kangax.github.io/compat-table/es6/
http://node.green/

**Comment by coolaj86** [comment]
You bring up a valid point: in node.js you can do whatever you want - it'll work using the default installer.

But think of the high school computer teachers that will want to use this code next Friday to teach kids JavaScript and help them catch Pokemon.

If they can show kids how to make the icon size bigger or how to loop through the array differently that's a win.

If it requires each computer to download 2gb of dependencies and run Linux... FAIL.

More than style my concern is barrier to entry for high school students, code camps, etc.

This project should be fun and easy for the 15-year olds playing the game and learning computers.

**Comment by BillyWM** [comment]
I don't think a goal of this project should be to serve as a coding tutorial. If someone wants to use it for that purpose, the onus is on them.

If less experienced developers want to contribute, we should encourage them and write FAQs about getting your environment set up.

>If it requires each computer to download 2gb of dependencies and run Linux... FAIL.

That's not the case now and it shouldn't go that way. Node and Python are cross-platform (save for native module troubles).

**Comment by DevAndArtist** [comment]
> This project should be fun and easy for the 15-year olds playing the game and learning computers.

I must disagree with this. The current codebase isn't fun at all. If kids want to learn the basics of coding, they should grab an iPad (if they can) and play around with the upcoming `Playgrounds` app which will teach them Swift. 

That said, learning from this codebase for a 15 years old kid isn't a good idea. Not every kid is like Geohotz. ;)

***

I support the idea of this project being just a pure backend with another project providing a visual layer on top of it.

**Comment by coolaj86** [comment]
@DevAndArtist I'm not saying that the current codebase is fun, what I'm saying is this:

PokemonGO is literally selling nastalgia. Imagine that you were 12 or 15 again and playing pokemon on your gameboy - when perhaps you were just learning to program in BASIC on a TI-83, or QBASIC on a hand-me-down 486, or JavaScript with those tacky banners that would follow the mouse cursor - back when you were a copy-paste junky that knew just enough to accidentally get suspended for accidentally running an IP scanner on the school network.

Those kids are out there today and they are going to see this project and they're going to want to copy and paste and change values and horse around.

I'm not saying this project should be a tutorial, I'm suggesting that it ought to be something that is easy for that 15-year old kid that you used to be to open up and hack at without knowing 3 programming languages and having advanced computer skills.

But, seriously, having sass and grunt and minifiers? [FizzBuzzEnterpriseEdition](https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition), anyone?

**Comment by efiku** [comment]
Sorry guys but I want to tell something. I don't know if this is right place.
I hope everyone will understand. :stuck_out_tongue: 

___

This project is great  (forks and stars in such a short time) but in my opinion there is some **mess** in code and I want to point some "bugs": 

- Unused code and  two different variable naming conventions  [LINK](https://github.com/AHAAAAAAA/PokemonGo-Map/blob/develop/pogom/customLog.py#L18L25) 
- Variables don't say what they are.  [LINK](https://github.com/AHAAAAAAA/PokemonGo-Map/blob/develop/pogom/transform.py#L3L4)  [LINK2](https://github.com/AHAAAAAAA/PokemonGo-Map/blob/develop/pogom/app.py#L43) 
- I suggest consider   DBAL + ORM  option for python.  [LINK](https://github.com/AHAAAAAAA/PokemonGo-Map/blob/develop/pogom/models.py#L31L40) 
-  [LINK](https://github.com/AHAAAAAAA/PokemonGo-Map/blob/develop/pogom/models.py#L26) Global variables == problem in feature?

Please take care about code health. :) 

### Also I suggest

-  Create wiki docs about API served by backend. *This will help new contributors from front skills*
-  Backend documentation 
-  Create CONTRIBUTING.md file with rules about code style / Pull request / Issues etc.
-  Just a nice REST app to decouple all UI from backend. (Separating application layers ) ( +1  for  HTML/CSS/JS masters ) ( +1 for server health ) (+1 for code quality)  (format: json) 

Of course this is only my suggestions, you do not have to take any attention.
PokemonGo-Map works fine on Linux Debian  ;)

ping @AHAAAAAAA

**Comment by coolaj86** [comment]
@efiku See https://github.com/AHAAAAAAA/PokemonGo-Map/issues/1512, we need to unlock the Wiki.

API Endpoints: https://github.com/coolaj86/PokemonGo-Map-server/blob/server/README.md#api-endpoints

**Comment by efiku** [comment]
@coolaj86 look to code ;) https://github.com/AHAAAAAAA/PokemonGo-Map/blob/develop/pogom/app.py#L21
