### ISSUE TITLE
[bug] lat/long coordinates translated into "real" and back to (wrong) lon/lat coordinates

### ISSUE THREAD

**Issue by crckdns** [AHAAAAAAA/PokemonGo-Map#112]
### Environment info
Operating System:
Debian 3.2
Installed version of Python:
2.7.9

### Steps to reproduce
1.  set coordinates 49.0159633,12.0966408
2. Your given location: Obermünsterstraße 12, 93047 Regensburg, Germany
3.  lat/long/alt: 49.01**62569** 12.0966**912** 0.0 

### What have you tried?
1. dancing on rainbows

no, really, why this buggy translation from and back to coords? Why not just checking via regex?
Otherwise we end up getting coordinates back from a street 100 meters away in bad case because the given lat/long coords have no street nearby.

**Comment by hhu94** [comment]
Addressed in #137.
