### ISSUE TITLE
Map style: Add Pokemon Go "Night" theme

### ISSUE THREAD

**Issue by Whoknowsit** [AHAAAAAAA/PokemonGo-Map#1121]
Thank you for implementing the Pokemon Go theme. However, i would like to choose between Pokemon Go (Day) and Pokemon Go (Night). Alternatively, automatically switch the color set, depending on the visitors time, if Pokemon Go is the currently chosen theme.

**Comment by FrostTheFox** [comment]
Interesting suggestion... I'll mark it.

**Comment by timendum** [comment]
This is present in the develop branch, can we close the issue?
