### ISSUE TITLE
Slight issue with external map :(

### ISSUE THREAD

**Issue by accepttheshrock** [AHAAAAAAA/PokemonGo-Map#1124]
Hi guys, I am using Windows 7 and I have gotten everything to work perfectly. Only one thing refuses to function, and that thing is the external map. I have followed the instructions found within the guide titled "How to make your map available externally," and it was quite helpful, and I can access the map from an external device as long as it is still on the Wi-Fi. I wanted to be able to use my phone to access the map from outside my Wi-Fi network, but every time that I do I find that Google Maps will crash within 10 seconds of opening it. Maps only crashes on my android device when I am not on my Wi-Fi, but it will display some Pokemon around my area for a few seconds. It works flawlessly when on my Wi-Fi however. I tried disabling the router firewall as well as my system's firewall, but it hasn't seemed to help. Any ideas guys?

**Comment by FrostTheFox** [comment]
What build are you running? dev or master? did you get your own API key?

**Comment by goudacoin** [comment]
yea sounds like API key issue :dancer:

**Comment by accepttheshrock** [comment]
Wow, thanks guys :) I'm using the master build and I will see if I can get a key
