### ISSUE TITLE
Rare pokemon notification

### ISSUE THREAD

**Issue by Nordsted** [AHAAAAAAA/PokemonGo-Map#1125]
Could it be possible to highlight or notify when a rare pokemon is found?
Could also be pokemons from a list specified by user :-)

**Comment by andrewda** [comment]
Duplicate of #244 and #483 and #1058

**Comment by Krys1s** [comment]
They were all closed out - still think it is worth having. Very useful when people create a very limited filter - eg everything except snorlax & lapras filtered out.

Scan a huge area and want to run in background all day and alert whenever one pops up.

**Comment by andrewda** [comment]
Addded this in #1149

**Comment by rcoenen** [comment]
I second that. No need to know another Rattata or Drowzee is around the corner.

**Comment by talentedmrripley** [comment]
#1149 has been merged.  This can be closed.
