### ISSUE TITLE
Passwords with an asterisk cause the python example.py command to fail at setup.

### ISSUE THREAD

**Issue by dratjr** [AHAAAAAAA/PokemonGo-Map#1126]
When running the command:
`python example.py -a pic -u USERNAME -p PASSWORD -l LOCATION -st 10`

and the password contains an asterisk, the following output it displayed:

usage: example.py [-h] [-a AUTH_SERVICE] -u USERNAME [-p PASSWORD] -l LOCATION
                  -st STEP_LIMIT [-i IGNORE | -o ONLY] [-ar AUTO_REFRESH]
                  [-dp] [-dg] [-H HOST] [-P PORT] [-L LOCALE] [-ol] [-c] [-pm]
                  [-d]
example.py: error: unrecognized arguments: LICENSE README.md credentials.json example.py locales pokemon.proto pokemon_pb2.py requirements.txt static templates transform.py

**Comment by wcastello** [comment]
Better use develop branch and put password inside quotation marks ""

**Comment by MonkeyLeeT** [comment]
Sorry master branch is no longer supported. And yes as suggested, use "" to enclose passwords with non-ascii characters.
