### ISSUE TITLE
Front-End Mobile Hover and Filters

### ISSUE THREAD

**Issue by Heavywavez** [AHAAAAAAA/PokemonGo-Map#1131]
## Expected Behavior
In mobile, should switch the nav to width:100% maybe, and when use filter of hidden some pokemons, should be delate and select easy. And the Hover should be disable for mobile on the maps.

## Current Behavior
The nav filter option, get 80%, what is not bad but a 100% would be better i think in mobile, after select a hidden pokemon the bar close automatic and can't delete by click the pokemon selected,  the filter bottom do not close the filter unless you click Pokemon Go Map. 

When you are navigate to the gmaps, some pokemons pop-up their location by just moving the map, think detect the map as a hover.

## Context
Well i'm using this in a ubuntu server, and i can access by  typing the IP, but i can't use correctly on mobile device.

## Your Environment
Tested on iPhone6.
Using last dev-branch.

**Comment by MonkeyLeeT** [comment]
Closing this issue as it is outdated. If this issue still persists on the `develop` branch, please reopen a new issue and update the information therein to reflect the new changes.
