### ISSUE TITLE
No Google Maps Javascript API key... (i'm a noob at this)

### ISSUE THREAD

**Issue by WhiteKhone** [AHAAAAAAA/PokemonGo-Map#1135]
I've tried all three versions, and keep getting the same result:

  "No Google Maps Javascript API key entered in credentials.json file!"
pogom.exceptions.APIKeyException: No Google Maps Javascript API key entered in credentials.json file! Please take a look at the wiki for instructions on how to generate this key, then add that key to the file!

**Comment by Xoonio** [comment]
https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Google-Maps-API:-a-brief-guide-to-your-own-key

;)

**Comment by WhiteKhone** [comment]
Will you marry me? no no wait, just shoot me for being so oblivious :[ thank you @Xoonio
