### ISSUE TITLE
Stepping Reverts to Orign Location After Next Location is Specified Over Rest

### ISSUE THREAD

**Issue by robjime** [AHAAAAAAA/PokemonGo-Map#1137]
Stepping Reverts to Orign Location After Next Location is Specified Over Rest in Example.py

https://github.com/AHAAAAAAA/PokemonGo-Map/blob/master/example.py#L606

Line 606 should reference the starting location as next location instead of the orign location.

**Comment by benemorius** [comment]
I suspect this issue doesn't exist anymore on the develop branch.

**Comment by MonkeyLeeT** [comment]
Closing this issue as it is outdated. If this issue still persists on the `develop` branch, please reopen a new issue and update the information therein to reflect the new changes.
