### ISSUE TITLE
Discord channel

### ISSUE THREAD

**Issue by medghaim** [AHAAAAAAA/PokemonGo-Map#114]
Perhaps we can include the discord link in the README.md? I'd like to hop on the channel so we can delegate tasks more easily

**Comment by sykhro** [comment]
Will do.



GitHub issues are for bug reporting.  
For general support, and feature request, join [our discord server](https://discord.gg/kwAcr7e).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

**Comment by ryantheleach** [comment]
expired invite.

**Comment by sykhro** [comment]
Pretty odd, someone will generate a new invite shortly.
