### ISSUE TITLE
pip install -r requirements.txt

### ISSUE THREAD

**Issue by senpai28** [AHAAAAAAA/PokemonGo-Map#1143]
C:\Python27\Scripts\pip install -r requirements.txt

and the result ->

could not open requirements file errno 2 no such file or directory 'requirements.txt'

**Comment by lparkermg** [comment]
I think you'll need the entire directory the requirements.txt file is in similar to how you're running pip itself.

**Comment by Xoonio** [comment]
i think, that pip isn´t in the "path", so he try to start it from there.

if you try this, you have to put the whole path to pokemon as argumend to pip

C:\Python27\Scripts\pip install -r C:\path\to\the\pokemap\requirements.txt

**Comment by MonkeyLeeT** [comment]
Closing this issue as it is outdated. If this issue still persists on the `develop` branch, please reopen a new issue and update the information therein to reflect the new changes.
