### ISSUE TITLE
Can I get jSon for Pokemon Name available on Map?

### ISSUE THREAD

**Issue by andikatanpah** [AHAAAAAAA/PokemonGo-Map#1145]
I'm sorry, i'm not expert pyhton..
can i graph all Pokemon Name available on Map? (json)

i think i can proccess it with simple jquery/javascript to make a notif if a rare pokemons appears on map..

i was try add some code to example.py but i got many error..

view_pokemon.append(pokename);

how to view it on example_fullmap.html ?

opss, i was find it..

$.get(baseURL + "/data", function(response) <- get all data i need it...

**Comment by MonkeyLeeT** [comment]
Closing this issue as it is outdated. If this issue still persists on the `develop` branch, please reopen a new issue and update the information therein to reflect the new changes.
