### ISSUE TITLE
Heroku doenst work as expected on second app

### ISSUE THREAD

**Issue by KevakaBuel** [AHAAAAAAA/PokemonGo-Map#1150]
## Expected Behavior
running like the local script, scanning and upserting pokemon/pokestops/gyms

## Current Behavior
sometimes works, but most times it doenst. Looking at the logs (papertrail) i see that he isnt even trying to get new pokemon etc. Just the usual site refreshs. Seems to happen after the app runs for some time (10 minutes)

## Steps to Reproduce (for bugs)
deploy 2 different apps with 2 different locations and try to run them both. First one seems to run just fine and the second one seems to only run sometimes, but most time there is just nothin.

## Your Environment
Heroku

## Other things i tried
I tried running only one app actively and see if it works that way but with no success

**Comment by AritzBi** [comment]
I have the same problem, looks like after few minutes the script stops scanning new pokemons.

**Comment by MonkeyLeeT** [comment]
Closing this issue as it is outdated. If this issue still persists on the `develop` branch, please reopen a new issue and update the information therein to reflect the new changes.
