### ISSUE TITLE
[SOLVED] how configure example.py for remote access?

### ISSUE THREAD

**Issue by EnricoSx** [AHAAAAAAA/PokemonGo-Map#1152]
thanks for your work!
how can i configure example.py for remote access.

if -H 127.0.0.1  -> access only from localhost  http://127.0.0.1:5000
if -H Pc-Name -> i access from local network http://Pc-name:5000
but if i want remote access? phone->router nat->http://server:5000 block access. why? 
Nat: port 5000 TCP , ANY source -> server:5000 tcp

**Comment by shargon** [comment]
use  -H and your IP address and open the firewall port

**Comment by Wolframcheg** [comment]
-H 0.0.0.0

**Comment by EnricoSx** [comment]
-H Myip
`C:\PokemonGo-Map-master>C:\Python27\python C:\PokemonGo-Map-master\example.py -a
 ptc -u sciamanozx -p Efen1234 -l "45.498359, 11.581922" -st 10 -H 193.238.138.2
34 -dp -dg -ol -o 41,19 -P 30001
[-] register_background_thread called
[-] register_background_thread: not running inside Flask so not starting thread
Traceback (most recent call last):
  File "C:\PokemonGo-Map-master\example.py", line 909, in <module>
    app.run(debug=True, threaded=True, host=args.host, port=args.port)
  File "C:\Python27\lib\site-packages\flask\app.py", line 843, in run
    run_simple(host, port, self, **options)
  File "C:\Python27\lib\site-packages\werkzeug\serving.py", line 677, in run_sim
ple
    s.bind((hostname, port))
  File "C:\Python27\lib\socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 10049] Indirizzo richiesto non valido nel proprio contesto
`

**Comment by EnricoSx** [comment]
-H 0.0.0.0   WORK! Thanks! please add this to wiki
