### ISSUE TITLE
Google map bug ?

### ISSUE THREAD

**Issue by Slam2** [AHAAAAAAA/PokemonGo-Map#1154]
Hi,

I've git pull and correct my gmaps ID, beceause "credentials.json" are replaced. But impossible to load the map. All pokemon/gym/stop are Okay.

Sorry for my bad english x)

**Comment by Xoonio** [comment]
credentials.json are gone. you have to put the kay with "-k <key> after runserver.py

**Comment by Slam2** [comment]
Yes, same problem :(

**Comment by skyshard** [comment]
this may be due to map_style undefined in localstorage
