### ISSUE TITLE
Missing I18n for Pokemon-Filter

### ISSUE THREAD

**Issue by ChristianLuxem** [AHAAAAAAA/PokemonGo-Map#1155]
Hi,

if you will start the Server with -L de, it will show the Pokemon Title in the Map with the german name. But the filter shows anyway the english title. I think the translation for this is missing. 

Tested in the current develop tree.

**Comment by Whoknowsit** [comment]
https://github.com/AHAAAAAAA/PokemonGo-Map/issues/1120

**Comment by MonkeyLeeT** [comment]
Fixed in #1139.
