### ISSUE TITLE
Gmaps_key (The given key has gone over the requests limit in the 24 hour period or has submitted too many requests in too short a period of time.), retrying

### ISSUE THREAD

**Issue by huirfan08** [AHAAAAAAA/PokemonGo-Map#1157]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by k33k00** [comment]
Are you using your own api key as described [here](https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Google-Maps-API:-a-brief-guide-to-your-own-key). If you are, then you have simply had too many requests on your site. 

Are you using it for personal use or are you sharing around the web? If you are sharing it around the web than chances are this will be a continuous problem everyday for you.

**Comment by huirfan08** [comment]
sry can you screen where i can change google map_key, i cant find it

**Comment by k33k00** [comment]
Credntials.json, Put your key in between the quotation marks. Or when running pass -k [api-key]

There is also a [set up video here](https://www.youtube.com/watch?v=nplNFl3SpOI)

Unfortunately I can't screen shot it as i'm running it on a server

**Comment by huirfan08** [comment]
give your facebook, i just dont know where Credntials.json

**Comment by AlphaJuliettOmega** [comment]
use your file explorer's search for Credentials.json?

**Comment by huirfan08** [comment]
no , i find it at google api, i tired, how to fix it, i change my google account but stiil cant,

**Comment by huirfan08** [comment]
help me

**Comment by AlphaJuliettOmega** [comment]
you need to copy the API Key from your Google Account and replace the samilar looking key
in Credentials.json.
did you find the file?

**Comment by huirfan08** [comment]
can you make a video, i cant got Credential.json, video/screenshot

**Comment by AlphaJuliettOmega** [comment]
it's in the root of the PokemonGo-Map repo, same folder where example.py is located.
inside credentials.json it looks like this:
{
	"ptc_client_secret"	: "w8ScCUXJQc6kXKw8FiOhd8Fixzht18Dq3PEVkUCP5ZPxtgyWsbTvWHFLm2wNY0JR",
	"android_id"		: "9774d56d682e549c",
	"service"			: "audience:server:client_id:848232511240-7so421jotr2609rmqakceuu1luuq0ptb.apps.googleusercontent.com",
	"client_sig"		: "321187995bc7cdc2b5fc91b11a96e2baa8602c62",
	"gmaps_key"			: "YOUR KEY HERE"
}

**Comment by huirfan08** [comment]
ok i already try and change the gmaps key, but why same  error ?

**Comment by huirfan08** [comment]
i use pokemonGO-MAP master

**Comment by machadox** [comment]
i got the same problem on 1 of my vps... its like That IP was "blocked" :/
