### ISSUE TITLE
Disable the .db?

### ISSUE THREAD

**Issue by denniskai1234** [AHAAAAAAA/PokemonGo-Map#1164]
Is it possible to disable the .db? With multiply maps running on one server it just creates insane load and ends up crashing.

**Comment by benemorius** [comment]
No it isn't. Possible solutions include:

- give each one its own directory to run in
- add a command line argument for the db filename so each one uses a different file
- fix concurrent database access

**Comment by denniskai1234** [comment]
Just removed the lines which load the db and its working fine now. 

Still sad that it didnt worked out that well, gonna need some rework as you said.

**Comment by jnovack** [comment]
OR, run it in a multiple instances in docker containers whenever #599 gets merged.

**Comment by kodbilenadam** [comment]
@denniskai1234 I need help some on server could you give me a help?

**Comment by denniskai1234** [comment]
@kodbilenadam Help with what?

@jnovack Im running 50 + different locations currently, i was happy to see that it gets placed into the .db file cause each map showed my whole town which is very big. Lets see maybe it gets improved.

**Comment by chuyskywalker** [comment]
You can use mysql now or multiple search scripts, etc.
