### ISSUE TITLE
Map not loading on mobile

### ISSUE THREAD

**Issue by hedqvist** [AHAAAAAAA/PokemonGo-Map#1165]
## Expected Behavior

Expected behavior would to have it  load on all devices

## Current Behavior

Visiting the page via desktop works just fine, but when accessing it via a mobile no map is loaded as background. Only markers are visible. on a grey background.

## Steps to Reproduce (for bugs)

python runserver.py -a google -u USERNAME -p PASSWORD -l "LOCATION" -st 10 -H 0.0.0.0 -P 5000 -k MY_SECRET_KEY

## Your Environment

* Version used: latest develop branch
* Environment name and version (e.g. Python 2.7): Python 2.7.x
* Operating System and version (desktop or mobile): Both

**Comment by commit-sudoku** [comment]
I feel like this bug might have something to do with the CSS for the desktop google maps being applied to the mobile google maps

**Comment by swablueme** [comment]
I have the same issue:
http://i.imgur.com/TFFUqdu.png
Visiting my server on PC is fine but visiting it on iOS doesn't load anything at all.
I have cleared my cache and disabled my adblocker on my phone.

**Comment by niayh** [comment]
Check any cookies you may have for your web address. The switch to local_storage caused me some issues the afternoon

**Comment by toofy7** [comment]
what is my secret key  and i get this error python canot open file runserver.py errno2 no such file or directory please help

**Comment by swablueme** [comment]
I've cleared my cache in all apps and tried three different browsers. Maybe it just affects iPhones ;_: I didn't have any problems with the master branch...

**Comment by hedqvist** [comment]
Tried on Both Android with different browsers and IOS. Still the same, cleared all cache, history, etc.

**Comment by mhelmetag** [comment]
@hedqvist , anything in the logs look suspicious? Since you're using `runserver.py`, I'd assume you on the `develop` branch? I was just using it (while deployed to heroku) and had no issues on Chrome for Android.

**Comment by skyshard** [comment]
this should be the same localstorage issue that i was fixing in #1162

**Comment by hedqvist** [comment]
@skyshard That did indeed fix the issue #1162
