### ISSUE TITLE
retrying_api_req: request error (Unexpected end-group tag.), retrying

### ISSUE THREAD

**Issue by EnricoSx** [AHAAAAAAA/PokemonGo-Map#1167]
C:\Python27\python C:\PokemonGo-Map-master\example.py -a google -u xxxxx@gmail.com -p xxxxx -l "45.504968, 11.408545" -st 10 -H 0.0.0.0 -dp -dg -i 41,19,13,16,21,10 -P 4900

[+] RPC Session Token: eyJhbGciOiJSUzI1NiIsImtpZ ...
[-] retrying_api_req: request error (Unexpected end-group tag.), retrying
[-] retrying_api_req: request error (Unexpected end-group tag.), retrying
[-] retrying_api_req: request error (Unexpected end-group tag.), retrying
[-] retrying_api_req: request error (Unexpected end-group tag.), retrying
[-] retrying_api_req: request error (Unexpected end-group tag.), retrying
[-] retrying_api_req: request error (Unexpected end-group tag.), retrying
[-] retrying_api_req: request error (Unexpected end-group tag.), retrying
[-] retrying_api_req: request error (Unexpected end-group tag.), retrying
[-] retrying_api_req: request error (Unexpected end-group tag.), retrying
[-] retrying_api_req: request error (Unexpected end-group tag.), retrying
[-] retrying_api_req: request error (Unexpected end-group tag.), retrying
[-] retrying_api_req: request error (Unexpected end-group tag.), retrying
[-] retrying_api_req: request error (Unexpected end-group tag.), retrying
[-] retrying_api_req: request error (Unexpected end-group tag.), retrying

**Comment by swablueme** [comment]
I think Niantic's server just died. I can't load the app either.

**Comment by EnricoSx** [comment]
ok, thanks :)
the command works 30 minutes ago

**Comment by tsvetant** [comment]
Looks offline to me https://p.datadoghq.com/sb/1xfifX-a17f211ecb

**Comment by talcohain** [comment]
Yup

**Comment by M4CC** [comment]
Same problem here...
