### ISSUE TITLE
"Scan step failed!" in scanning process, then scanning stops

### ISSUE THREAD

**Issue by tolvaly** [AHAAAAAAA/PokemonGo-Map#1168]
After running the application for more then 5 minutes, on every scan step it will show this error:
"Scan step failed. Response dictionary key error." (see attachment)

After a while scanning is completely stopped, and every pokemon will disappear from the map, and no new pokemons will appear.
![2016-07-22 10_59_15-c__windows_system32_cmd exe - start_work bat](https://cloud.githubusercontent.com/assets/20593548/17051851/69d848ee-5003-11e6-88f2-27ccb1c92cd1.png)

## Steps to Reproduce (for bugs)
1. start the application
2. open up the map
3. let it there for a while, you will be seeing in the console after aprox. 5 minutes
4. after a while will stop scanning, and the map will be empty

## Your Environment
* Version used: 
develop branch, Commit: 168831eb8ed9d644bbe59f58fe4d0bff7d584af1
Date: Friday, July 22, 2016 9:26:29 AM

* Environment name and version: Python 2.7
* Operating System and version: Windows 10

**Comment by lnmtriet93** [comment]
Purge cache and local storage will fix this error

**Comment by tolvaly** [comment]
It fixed! Thank you!

**Comment by BigSmitty72** [comment]
I'm getting the same error now as well... By Purge cache and local storage, are you talking about the browser cache or local temp files?  Or I guess, how do you go about clearing storage cache?
