### ISSUE TITLE
Enhancement Request: Flag to remove verbose responses.

### ISSUE THREAD

**Issue by Valareos** [AHAAAAAAA/PokemonGo-Map#1170]
It is hard to find a specific error or to even make sure it is working properly when the server screen is imbued with the get requests

Is displaying the Get Requests really needed? I would much rather see a message if get requests fail

**Comment by k33k00** [comment]
#1184 - Looks like there's a pull request open for that now

**Comment by chuyskywalker** [comment]
@Valareos this is fixed now in `develop`; you can close this ticket.

**Comment by Valareos** [comment]
thank you :)
