### ISSUE TITLE
Exception in search thread

### ISSUE THREAD

**Issue by tolvaly** [AHAAAAAAA/PokemonGo-Map#1172]
![2016-07-22 12_15_32-c__windows_system32_cmd exe](https://cloud.githubusercontent.com/assets/20593548/17057045/4b28c1ea-5020-11e6-86c6-aae89bac80f0.png)

After this exception, no more scan cycle starts.

## Steps to Reproduce (for bugs)

1. Servers were down, couldn't login user

## Your Environment

* Version used: 
develop branch, Commit: 168831e
Date: Friday, July 22, 2016 9:26:29 AM
* Environment name and version: Python 2.7
* Operating System and version: Windows 10

**Comment by tolvaly** [comment]
I think the same error in the latest version:

![2016-07-22 15_25_07-c__windows_system32_cmd exe](https://cloud.githubusercontent.com/assets/20593548/17057110/b0331ab8-5020-11e6-9198-32746938e079.png)

Same error, after this exception it stops to scan for new pokemons.

Version used: develop branch, Commit: ab503d8eea4ecc1c7214fb6b95bfb6659803db3d [ab503d8] Date: Friday, July 22, 2016 1:00:40 PM

**Comment by AndrewYoungs** [comment]
I am having this error as well. It's been happening in the past several commits.

**Comment by andrewda** [comment]
Is this fixed or still an issue?

**Comment by tolvaly** [comment]
I haven't seen this error for a while, but the application still hangs after 4-5 map scanning iterations. It needs to be restarted

**Comment by wcastello** [comment]
Fixed in #1340
