### ISSUE TITLE
Map just displaying "Flask Google Maps Full Map Example" message

### ISSUE THREAD

**Issue by M4CC** [AHAAAAAAA/PokemonGo-Map#1174]
Hello,

I've managed to get the script running again but now I only get a blank page with "Flask Google Maps Full Map Example" title, no map is being displayed at all.

Do you know what might be going on?

Thanks!

**Comment by zlakomanoff** [comment]
Just setup you google map key

**Comment by MRokas** [comment]
Use latest version. You're using version from 2 days ago.

**Comment by javiermartinn** [comment]
Hi, I'm having the same issue, I've done the steps mentioned to get my API key and replaced it in the credentials.json file, I also have the latest version, but the only thing I can see while running the script is "Flask Google Maps Full Map Example". If you guys could help me it would be really appreciated. Thanks in advance.

**Comment by jowang0319** [comment]
mine too!

**Comment by jowang0319** [comment]
![screen shot 2016-07-22 at 10 43 01 am](https://cloud.githubusercontent.com/assets/13969650/17060674/17fa464e-4ff9-11e6-8181-be3144fc7705.png)
I'mhaving this in my console
