### ISSUE TITLE
Given key has gone over the requests limit ?

### ISSUE THREAD

**Issue by Plop** [AHAAAAAAA/PokemonGo-Map#1177]
Hi,

I have an issue since a few hours, with this message when I'm launching the example.py script :

`retrying_set_location: geocoder exception (The given key has gone over the requests limit in the 24 hour period or has submitted too many requests in too short a period of time.)`

I've been using my own API key in the credentials.json file, and I've check my usage in my Google account : I've not used all my requests at all 
http://imgur.com/a/vzFaP http://imgur.com/a/Prkgx

Could anybody tell me what's going on ?
Thanks.

**Comment by k33k00** [comment]
Out of curiosity how many people use you site?

Try passing the key in your command 

> runserver.py [-h] [-a AUTH_SERVICE] -u USERNAME [-p PASSWORD] -l LOCATION -st STEP_LIMIT **[-k GMAPS_KEY]**

**Comment by Plop** [comment]
Probably around 100.

I will give it a try. It seems that the login servers are down, or at least Niantic Servers, 'cause I can't see any pokemon and the script isn't even trying to get informations.

**Comment by Plop** [comment]
The fault was on the login servers. Everything is back to -almost- normal now.
Thanks.
