### ISSUE TITLE
Pokemon timer continues into the negatives.

### ISSUE THREAD

**Issue by medghaim** [AHAAAAAAA/PokemonGo-Map#118]
Pokemon not despawning after their expiry timer reaches 0 (timer continues into the negative)

**Comment by crckdns** [comment]
confirming

**Comment by foodforarabbit** [comment]
Hey yea I added this feature right now it goes into negatives because there
is no defined behaviour otherwise. I think that pokemon with timers in the
negative should be removed, but that is outside of the scope of the timer.
I can set the text to "expired" instead of negative, but it wouldn't really
change anything.

**Comment by nborrmann** [comment]
I don't think they should be instantly removed after the timer has expired. This might seem like a bug to users if the pokemon they hunted is suddenly gone.

I like the idea of changing the label to "expired".

Also, server-side purging of outdated pokemon is implemented in #101 but needs to be merged.

**Comment by Johanneshn** [comment]
Maybe they turn black & white and fade out slowly when the timer have expired

**Comment by denniskai1234** [comment]
I dont think i would count it as a bug if the pokemon dissapears? If i see it the first time maybe i would check whats going on and see oh there is a countdown maybe its gone.

**Comment by LasseSLambertsen** [comment]
They should dissapear, when countdown reaches zero.
Else the map risk getting crowded, ift running for too long :)

**Comment by medghaim** [comment]
Not sure the animation would be worth the effort, @Johanneshn. If someone's actively tracking a pokemon, they'll actively be aware of time left (its in the infobox) which even counts down now. So I doubt they'll be surprised when it hits 0 and disappears.

**Comment by nikisby** [comment]
The expired pokemons should definitely be removed. The goal is to show only those pokemons you can catch, there's no need to leave the map crowded with those "ghosts". I also think the animation is reduntant.

**Comment by xdtrammell** [comment]
Recorded a gif of the bug, http://i.imgur.com/FbEnVs1.gifv

**Comment by DerScreever** [comment]
yeah we know already. this would be fixed with #101
