### ISSUE TITLE
getting error :(

### ISSUE THREAD

**Issue by Aakashmangla2000** [AHAAAAAAA/PokemonGo-Map#1183]
## Current Behavior
[-] retrying_api_req: request error (Unexpected end-group tag.), retrying
[-] retrying_api_req: request error (Unexpected end-group tag.), retrying

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by jonathan-dejong** [comment]
Servers are down

**Comment by jonathan-dejong** [comment]
http://ispokemongodownornot.com/

**Comment by Aakashmangla2000** [comment]
Nope they are working :/

**Comment by meagerfindings** [comment]
I'm thinking the servers are up again, but struggling. My phone could sign in but the map took a few more minutes to login.

**Comment by jonathan-dejong** [comment]
Might be something like that. 
My regular app is struggling as well and my map just keeps hittin 200 errors:
`"GET /raw_data?pokemon=true&pokestops=false&gyms=true HTTP/1.1" 200 ` as well as not finding any JSON object to decode from time to time. 

Either that or develop branch is broken.

**Comment by NikXO6** [comment]
servers are down. can't login on phone too.

**Comment by Aakashmangla2000** [comment]
working fine now
