### ISSUE TITLE
pip install -r requirements.txt

### ISSUE THREAD

**Issue by nerakai** [AHAAAAAAA/PokemonGo-Map#1185]
So when I run the line pip install -r requirements.txt I get the error: 
Fatal error in launcher: Unable to create process using '"'
Anyone know what's going on here?

I had originally got to the point where I could put in my username and pw but that didn't work since I was using python 3.5 not 2.7 so I uninstalled 3.5 and installed 2.7 and now I'm at this error and I've no idea how to get it to work

**Comment by MRokas** [comment]
reinstall pip.

**Comment by nerakai** [comment]
I've already tried running get-pip.py again

**Comment by Tharbad** [comment]
You should use pip2.7 if you have other version installed.
Also use sudo.

**Comment by nerakai** [comment]
How do I use pip 2.7
what's sudo?

**Comment by MRokas** [comment]
What OS are you using? Win or *nix?

**Comment by medghaim** [comment]
Please do not open issues for issues _not_ pertaining to bugs/errors. You can ask these questions here: https://discord.gg/hGe4A

**Comment by nerakai** [comment]
.... but I am getting an error???

**Comment by sohayb** [comment]
I fixed that error with a sudo

**Comment by nerakai** [comment]
From what I've looked up sudo is for Unix os's and I'm on Win10

**Comment by MRokas** [comment]
Run cmd as admin

**Comment by nerakai** [comment]
Nope still nothing
