### ISSUE TITLE
Should we add generated files to gitignore?

### ISSUE THREAD

**Issue by nekitk** [AHAAAAAAA/PokemonGo-Map#1186]
There are a lot of merge conflicts now because of css and js min files.

## Possible Solution

* Add generated css and js files to gitignore
* Add grunt building to setup.bat

Cons:
* It'll be more complex for regular users to launch project because they'll need to install Node.js

If others agree I can do it later today.

**Comment by mikeporterdev** [comment]
Normally I would agree but this project seems to attract an awful lot of non-technical users that would require even more support.

**Comment by nekitk** [comment]
It's probably better to make another branch with stable version and dist-files included. For example, add them to master and leave develop branch for devs. .gitignore-s will differ though.

**Comment by BillyWM** [comment]
Yeah, non-technical users shouldn't have the bleeding edge. It would solve other problems than this one. This check for example is completely unnecessary: https://github.com/AHAAAAAAA/PokemonGo-Map/pull/1162. Users should just be told to clear their localStorage (and shouldn't have had access to rapidly changing code).

Master Stable and develop is Canary; If you're not prepared to handle it you shouldn't be in it :)

**Comment by chuyskywalker** [comment]
A pre-built artifact would resolve most of this. Right now, people are instructed to install git, clone things, install python, apt/yum a bunch of build tools (gcc is required) and so on. Now that the dockerfile is in `develop`, it'd make more sense to point people that direction, imo. Ala:

```
How to install:

1. Install [Docker](https://www.docker.com/products/docker)
2. Run `docker run -ti --rm pokemongo-map -h`
3. Run with config flags that work for you!
```

Thus leaving the git development area for, well, development.

**Comment by Chlodochar** [comment]
I agree that dist files should be gitignored. The unnecessary merge conflicts are starting to pop up (#1515).

**Comment by chuyskywalker** [comment]
Guess this can be closed now :)
