### ISSUE TITLE
Does the type of Pokemon vary on the account used to log in?

### ISSUE THREAD

**Issue by clinton2111** [AHAAAAAAA/PokemonGo-Map#1188]
So the question I have is I am currently using my google account to use your tool which is also my main Pokemon Go account. I am a bit worried about getting banned so made a new PTC account. I wanted to know does the Pokemon that spawn in your surrounding vary on the level of your account used to log into the tool? or does everyone see the same Pokemon irrespective of their trainer level?

**Comment by MRokas** [comment]
No it doesn't. Everyone sees same wild pokemons, but occasionally some pokemons spawns just for you(that's unconfirmed and just my theory from what I've seen so far)
