### ISSUE TITLE
Google Login not accepted

### ISSUE THREAD

**Issue by Quebroph** [AHAAAAAAA/PokemonGo-Map#1189]
System is giving me this error starting up the server with this command:

`python runserver.py -a google -u EMAIL -p PASS -l "LOCATION" -st 10 -H IP.IP.IP.IP -ar`

<img width="799" alt="bildschirmfoto 2016-07-22 um 13 03 12" src="https://cloud.githubusercontent.com/assets/2054568/17055400/ce304d38-500c-11e6-9407-9908b2362847.png">

Is there a typo mistake?
What does -ar do?

**Comment by MRokas** [comment]
remove ar argument

**Comment by Quebroph** [comment]
works. Why is it causing problems?

**Comment by kangoo13** [comment]
ar is autorefresh I guess you forgot to put the argument after it

**Comment by Quebroph** [comment]
I put -ar at the end.

**Comment by Skullmonkey** [comment]
-ar got depreciated (yesterday) and no longer is an argument.

**Comment by MRokas** [comment]
@kangoo13, @Quebroph  - AR argument has been removed. Using any invalid/non-existant argument causes stuff like that.

**Comment by medghaim** [comment]
Please read the wiki, or ask for help in https://discord.gg/hGe4A.
