### ISSUE TITLE
Error after login

### ISSUE THREAD

**Issue by MarFerPra** [AHAAAAAAA/PokemonGo-Map#119]
### Environment info
Operating System: Ubuntu 16.04

Installed version of Python: 2.7

### Steps to reproduce
1. Install requirements
2. Launch map as said.
3. Check terminal for error message.

### What have you tried?
1. Running the program as sudo shows the same error.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

`[-] looping: step 0 of 25
Exception in thread search_thread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "example.py", line 489, in main
    '<center class="label-countdown" data-disappears-at="'+disappear_timestamp+'">'+disappears_at+'</center>'
TypeError: coercing to Unicode: need string or buffer, float found`

**Comment by sykhro** [comment]
Already fixed, pull latest master.

**Comment by MarFerPra** [comment]
Found the error, on line 489 in 'example.py' variables needed to be included in the string as str(variable).

**Comment by MarFerPra** [comment]
Oh right, cool, sorry.
