### ISSUE TITLE
BUG: Filter Search Box's

### ISSUE THREAD

**Issue by craigbaines** [AHAAAAAAA/PokemonGo-Map#1191]
This seems pretty hit an miss but when i go to type in my notification box, it seems to switch itself back to the hide box when i click on it.

It's doing it one moment then it seems fine the next! Anyone else experiencing this, or is it my pc being a spazz. 

![type](https://cloud.githubusercontent.com/assets/9383958/17055769/f81efc44-5006-11e6-979d-fcc99eff6dd8.gif)

**Comment by AndreasEnemyr** [comment]
How did you get that?

**Comment by craigbaines** [comment]
Just keep adding to your notification box, it seems to start doing it randomly. Im honestly not sure lol.

**Comment by AndreasEnemyr** [comment]
I mean, how can you choose what to see? I don´t have that window?

**Comment by MatthiasJ** [comment]
it occurs when you exceed a certain number of pokemon in that list

**Comment by hedqvist** [comment]
That menu also seems to cause some issues on ios devices. Having a hard time to select each pokemon form the list on Iphone 5S. Both Chrome and Safari.

**Comment by esteinborn** [comment]
@AndreasEnemyr He is using the "develop" branch on the repo.

@craigbaines I am experiencing this issue in Safari OSX, but not Chrome Latest OSX

**Comment by esteinborn** [comment]
@craigbaines May want to create a new issue using the Issue template. Seem to get better responses when using the proper template: https://github.com/AHAAAAAAA/PokemonGo-Map/issues/new

**Comment by craigbaines** [comment]
I think it just got fixed, yet to try it though

**Comment by esteinborn** [comment]
could you post your fix if you fixed it? I'm still experincing the issue.

**Comment by craigbaines** [comment]
Not me, it got merged

**Comment by craigbaines** [comment]
#1234
