### ISSUE TITLE
get_profile returned no-len payload

### ISSUE THREAD

**Issue by devian223** [AHAAAAAAA/PokemonGo-Map#1193]
I'm getting a strange output which I have never seen before

[-] retrying_get_profile: get_profile returned no-len payload, retrying

I also cannot login on Pokemon Go with my PTC account, while the servers are up.

Edit: I just saw that there are currently difficulties with the PTC accounts, maybe that is the issue. Maybe. Still strange that I cannot log into the Pokemon Go app

**Comment by medghaim** [comment]
Please use the `develop` branch. Also yeah, their servers are wonky right now.
