### ISSUE TITLE
[Dev] Skips a lot of Pokemon when searching

### ISSUE THREAD

**Issue by snake-345** [AHAAAAAAA/PokemonGo-Map#1195]
Screenshots:
**Master**
[http://imgur.com/yxs9cas](http://imgur.com/yxs9cas)
**Dev**
[http://imgur.com/a/BMP31](http://imgur.com/a/BMP31)

Lat/Lng: 54.711245, 20.508262

**Comment by MaximilianFrick** [comment]
i figured out the same issue. Have the feeling that master has a better coverage than develop.

**Comment by pmmsoares** [comment]
I confirm that, its very strange but dev skips more tan half of the pokemons on the map. Very strange issue.

**Comment by Nicknack1234** [comment]
Which is more accurate? Is Master creating pokemon that aren't really there or is Dev missing some?

**Comment by snake-345** [comment]
Master more accurate. I cought pokemons by master. Without errors)

**Comment by pmmsoares** [comment]
Actually never had a problema with Master, every Pokemon was there, Dev otherwise dont show half of them.

**Comment by noaqzz** [comment]
You have to manually change the parameters.

> Def generate_location_steps(initial_location, num_steps):
    pos, x, y, dx, dy = 1, 0, 0, 0, -1

    while -num_steps / 2 < x <= num_steps / 2 and -num_steps / 2 < y <= num_steps / 2:
        yield (x * 0.0015 + initial_location[0], y * 0.0015 + initial_location[1], 0)

        if x == y or (x < 0 and x == -y) or (x > 0 and x == 1 - y):
            dx, dy = -dy, dx

        x, y = x + dx, y + dy

**Comment by snake-345** [comment]
Omg, maybe fix it in dev branch? instead manualy edit it)

**Comment by snake-345** [comment]
Dev features is cool but it not need if dev branch can't find all pokemons

**Comment by Nicknack1234** [comment]
They are looking in to more efficient search routines and options as adjusting the variable also means it increases the time to complete a loop. Its the dev branch because its in development, This has been reported quite a few times before this its all there in the open issues.

**Comment by FrostTheFox** [comment]
This is a known issue, we're working on improving the effectiveness of search routines.

**Comment by medghaim** [comment]
Pull request for a temporary fix to put an end to issues like these being opened.

**Comment by medghaim** [comment]
Aaaaand it's 'live'.

**Comment by snake-345** [comment]
Aaaaaand still it does not work properly
