### ISSUE TITLE
UnicodeDecodeError when going to the map

### ISSUE THREAD

**Issue by kangoo13** [AHAAAAAAA/PokemonGo-Map#1196]
So everything is working fine, the script is well running and finding pokemons in my area but when I enter the url to go on my browser to find the pokemon I have an exception and the map reveals me 0 pokemon.

http://imgur.com/a/u8y64  => error

The error is coming back everytime that I reload the browser.
I am using python2.7

My cmd line is:

C:\Python27\Python.exe runserver.py -a google -u "xxxxxx" -p "xxxxxx" -l "3 chemin des menestrels istres" -st 5

Note that the error is coming on STABLE and DEV

EDIT : I found out that the error comes from the browser trying to load the pokemon on the map, as you can see here : 
![image](https://cloud.githubusercontent.com/assets/9050016/17056306/d6949c9e-5012-11e6-8c92-e3b66d7e652b.png)

EDIT2 : Ok I fixed it by myself. My path to the icons was "C:\Users\Aurélien" and Aurélien contains an "é" this provocated the error...

**Comment by MonkeyLeeT** [comment]
Closing this issue as it is outdated. If this issue still persists on the `develop` branch, please reopen a new issue and update the information therein to reflect the new changes.
