### ISSUE TITLE
Not Getting All Pokemon On Map Like Master Used To (PICS)

### ISSUE THREAD

**Issue by rushingfitness** [AHAAAAAAA/PokemonGo-Map#1199]
## Expected Behavior
All pokemon from the api should be displayed on the map

## Current Behavior
So I noticed something on the develop branch yesterday and just confirmed it. It seems that whatever way we are now adding pokemon to the map on the develop branch is not getting all of the pokemon that the master branch used to get (The latest master I have is 0394fc21417a3a4652404b301a1459e14d2da06b, didn't want to pull anything down in an effort to not tamper with the test). Screenshots at the bottom

## Possible Solution
I don't write in Py, but I would assume looking over how we're now dealing with pokemon from the api, including exceptions (maybe it's not currently handling something that master used to?), 
and comparing it to how we did with master.

## Steps to Reproduce (for bugs)
1. Run the develop branch server, flags I chose were `-a "goog", -p, -u, -l, -st "5", -P, -k`
2. Run a simultaneous server on master (again I didn't pull down the latest master and am on a commit before the develop branch was created and migrated to). Flags I chose were `-a "goog", -u, -p, -l, -st "5", -ar "2"`
3. Look at both webpages and see what pokemon are not being displayed on the develop server that are being served up by the master server

## Context
I realized this issue when I noticed that pokemon that used to be displayed outside of my apartment on master are no longer showing up on develop. This is IMHO a pretty big deal as it means the tracker is ineffective at tracking all pokemon. Here are the screenshots of Boston Massachusetts. 

<img width="1680" alt="screenshot 2016-07-22 07 50 11" src="https://cloud.githubusercontent.com/assets/3672033/17056734/6ed61f62-4fe3-11e6-8262-ac4006535c91.png">
<img width="1680" alt="screenshot 2016-07-22 07 50 19" src="https://cloud.githubusercontent.com/assets/3672033/17056733/6ed2cf60-4fe3-11e6-9f78-138c9eaccb86.png">

## Your Environment
* Version used:
    - master branch (0394fc21417a3a4652404b301a1459e14d2da06b)
    - develop branch (0394fc21417a3a4652404b301a1459e14d2da06b)
* Environment name and version (e.g. Python 2.7): Py 2.7.10
* Operating System and version (desktop or mobile): Macbook Pro

**Comment by medghaim** [comment]
A temporary fix has _just_ been pushed. The result is a smaller search area, but complete coverage.
