### ISSUE TITLE
New Proto

### ISSUE THREAD

**Issue by rubenvereecken** [AHAAAAAAA/PokemonGo-Map#12]
Mind pushing the new proto you use?

EDIT: I ask because I see a HeartbeatPayload referenced but don't see it defined anywhere, though the app crashes before it gets to this point.

**Comment by pavog** [comment]
It would be great. The app crashes for me, too.
I want to use it so bad. It seems so nice :heart:

**Comment by marauder37** [comment]
@rubenvereecken that's a very interesting point, the .proto file doesn't match the compiled pb2. But it doesn't come from this project. You can get it at https://github.com/leegao/pokemongo-api-demo/blob/simulation/pokemon.proto and we should update our copy

**Comment by sykhro** [comment]
Solved with 0b3a6ed
