### ISSUE TITLE
Zoom out button is out of screen border on mobile

### ISSUE THREAD

**Issue by r-darwish** [AHAAAAAAA/PokemonGo-Map#1200]
## Expected Behavior
Both zoom in and zoom out button should appear on the mobile screen.

## Current Behavior

https://i.imgur.com/g6sOeKx.png

## Possible Solution

Zoom using the multi-touch

## Steps to Reproduce (for bugs)

1. Open the map in Chrome's mobile simulation or on a real mobile device

## Context

This is probably caused due to the new navbar as it doesn't occur on the master branch.

## Your Environment

* Version used: Latest develop
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): Chrome simulating iPhone 6s or a real Nexus 5x

**Comment by MRokas** [comment]
In your screenshot I see there's white borders(body element's margins. Seems to be something wrong with loaded css. Could you check if none returns 404?

**Comment by r-darwish** [comment]
http://i.imgur.com/lKHkTe2.png

Seems that all CSSs are loaded

**Comment by MRokas** [comment]
Oh, it was just bad crop then. But it works fine for me on Mobile, Chrome+resized and Firefox+resized. I will try ask in discord if anyone can reproduce it.

**Comment by r-darwish** [comment]
https://developers.google.com/web/tools/chrome-devtools/iterate/device-mode/?hl=en

Can you try this? I set it up to iPhone 6 plus

**Comment by Munskin** [comment]
Same here on Chrome -W10
http://imgur.com/a/o8kc2

**Comment by MRokas** [comment]
@r-darwish that's what I used.

**Comment by pmmsoares** [comment]
Same in Edge.

**Comment by M4CC** [comment]
Same problem here.

**Comment by MRokas** [comment]
It's caused by https://github.com/AHAAAAAAA/PokemonGo-Map/pull/1158

**Comment by MRokas** [comment]
Pull request to fix this, has been sent.

**Comment by MonkeyLeeT** [comment]
Closing this issue as it is outdated. If this issue still persists on the `develop` branch, please reopen a new issue and update the information therein to reflect the new changes.
