### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by BullyWiiPlaza** [AHAAAAAAA/PokemonGo-Map#1202]
I'm using Windows 10 64-bit and I installed Python from [here](https://www.python.org/ftp/python/3.5.2/python-3.5.2.exe). I downloaded and installed `pip` from [here](https://bootstrap.pypa.io/get-pip.py).

The Python location is as follows:
```
>where python
C:\Python34\python.exe
```

If I run the example.py script, I'm getting the following syntax error:
```
>python example.py
  File "example.py", line 103
    print '[-] {}'.format(message)
                 ^
SyntaxError: invalid syntax
```

Uncommenting yields another error:
```
>python example.py
  File "example.py", line 160
    except (GeocoderTimedOut, GeocoderServiceError), e:
                                                   ^
SyntaxError: invalid syntax
```

Please fix your script or tell me what I did wrong.

**Comment by SimpleCookie** [comment]
Use python 2.7.x, you're most likely using pyton 3+

**Comment by BullyWiiPlaza** [comment]
No, that doesn't work either:
```
>C:\Python27\Python example.py
Traceback (most recent call last):
  File "example.py", line 4, in <module>
    import flask
```
