### ISSUE TITLE
Area of Scan Overlay

### ISSUE THREAD

**Issue by jnovack** [AHAAAAAAA/PokemonGo-Map#1203]
Do you get back coordinates for your scanning locations?

Is it possible to add a rectangle with the area it scanned at like 5% transparency so we know what area is in our search radius (and whether can shrink or enlarge it for our needs)?

Do I need a 5 Search Radius? Do I need a 6??  I don't know. I'd like to do the minimum required for my needs.

https://developers.google.com/maps/documentation/javascript/shapes#rectangles

**Comment by DeastinY** [comment]
If I remember correctly it once was based on the steps from POGO. But this seems not to be the case anymore

**Comment by k33k00** [comment]
[#1102] Something similar to this is sitting in the pull request queue. Just a matter of waiting to see if it gets merged. In the mean time you could clone their version or modify the files your self.
