### ISSUE TITLE
Google 2-step verification

### ISSUE THREAD

**Issue by SimpleCookie** [AHAAAAAAA/PokemonGo-Map#1204]
I haven't found any way to enter a valid sms code, will it be included in a later release?

Or does someone have a google account without it which also has a pokemon go account which you can lend me?

**Comment by adambowles** [comment]
Make a new google account and log into Pokemon with that, takes 30 seconds.

**Comment by adambowles** [comment]
Or make a pokemon trainer account: https://club.pokemon.com/uk/pokemon-trainer-club/sign-up/

**Comment by invisiblek** [comment]
create an app password and use that to log in: https://security.google.com/settings/security/apppasswords

**Comment by SimpleCookie** [comment]
@invisiblek thanks man, that's a extremely good workaround imo! Didn't know about that one.
