### ISSUE TITLE
App crashes on Heroku after checking for logintimer (remaining login time)

### ISSUE THREAD

**Issue by DanielVolz** [AHAAAAAAA/PokemonGo-Map#1205]
<img width="745" alt="screenshot 2016-07-22 14 29 25" src="https://cloud.githubusercontent.com/assets/3275994/17057224/fde226b2-5018-11e6-8271-dd6f262ca287.png">

Locally it works flawlessly. I'm on the newest dev commit.
And I used google auth.

**Comment by birdwell** [comment]
I think there have been other issues like this open. I ran into the same problem.

**Comment by DanielVolz** [comment]
Yeah I noticed this to:
https://github.com/AHAAAAAAA/PokemonGo-Map/issues/1141
https://github.com/AHAAAAAAA/PokemonGo-Map/issues/965
https://github.com/AHAAAAAAA/PokemonGo-Map/issues/1112
https://github.com/AHAAAAAAA/PokemonGo-Map/issues/1071

**Comment by birdwell** [comment]
Yeah, I am getting happening over and over again once it completes.
![screen shot 2016-07-22 at 8 26 51 am](https://cloud.githubusercontent.com/assets/3323856/17058463/3c64947a-4fe6-11e6-87ef-7a2d74ebb1f4.png)

**Comment by MonkeyLeeT** [comment]
Closing this issue as it is outdated. If this issue still persists on the `develop` branch, please reopen a new issue and update the information therein to reflect the new changes.
