### ISSUE TITLE
Cant connect to webserver

### ISSUE THREAD

**Issue by mathisen99** [AHAAAAAAA/PokemonGo-Map#1208]
hello i have everything upp and runing with no errors on a debian 8 server.. 
but i cant seem to connect to it from inside the LAN 
when i connect to 192.168.XXX.XXX:5000 i just get connection refused....
am i missing something here ???

 python example.py -a ptc -u ********* -p ********** -l "60.1576254 19.9492077" -st 10
[-] register_background_thread called
[-] register_background_thread: not running inside Flask so not starting thread
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
[-] register_background_thread called
[-] register_background_thread: initial registration
[+] Locale is en
 * Debugger is active!
[+] Getting initial location
 * Debugger pin code: 259-292-642
[!] Your given location: 5 Sundblomsvägen, 22150, Åland Islands
[!] lat/long/alt: 60.1571926 19.9489499 0.0
[!] PTC login for: mathisen82
[+] RPC Session Token:
and so on........

**Comment by MRokas** [comment]
use `-H 0.0.0.0` and make sure port 5000 is open.

**Comment by mathisen99** [comment]
thx that did the trick.. my bad..
Solved
