### ISSUE TITLE
API key request limit, new key generated, tried in master and dev builds. not working

### ISSUE THREAD

**Issue by tommywake** [AHAAAAAAA/PokemonGo-Map#1210]
Have followed all instructions and tried on both builds, new key successfully generated, however when attempting to run server with new credentials assigned, the request limit remains, have restarted pc with no effect. server is for private use only and new key certainly not over used. any ideas?

**Comment by tommywake** [comment]
was working great before the public api hit limit

**Comment by medghaim** [comment]
Please take support questions to: https://discord.gg/hGe4A
