### ISSUE TITLE
Exception during PTC outage locking up threads when multiple running

### ISSUE THREAD

**Issue by morelup** [AHAAAAAAA/PokemonGo-Map#1211]
## Expected Behavior
May be out of scope of the project (and I may be using in an unintended way).  I realized i could have multiple sessions running with multiple ptc accounts all updating to the same map. 

## Current Behavior
The problem comes in when there are PTC login issues (not like that happens often :D )  it results in the same error from 1176 (and 1173), one of the threads will succesfully handle the exception and log back in, but the other sessions will hang.

Also, I only notice this after the first search, the intial time logging in will result in the same exceptions but recover fine.

## Possible Solution

Handling the exception may fix the issue but I am not certain what is causing the hanging, it appears when I do this that the login script is single threaded and only one thread can login at a time (i've noticed when i start them all up at the same moment only one will attempt a login, and the others will wait)

## Steps to Reproduce (for bugs)

1.Create 3-4+ different PTC accounts and log them in on the same machine (during PTC outage times)
2.Wait for the re-login cycle after the initial searches.
3.
4.

## Context

Just means the system isn't set it and forget it if I plan to be multiple places in the city in the evening.  Not an end all be all failure but I also don't know if this error happens during single usage.

## Your Environment

* Version used: Latest development version as of posting this.
* Environment name and version (e.g. Python 2.7): 2.7
* Operating System and version (desktop or mobile): Windows 10

**Comment by MonkeyLeeT** [comment]
Closing this issue as it is outdated. If this issue still persists on the `develop` branch, please reopen a new issue and update the information therein to reflect the new changes.
