### ISSUE TITLE
Map doesn't load on mobile (iOS)

### ISSUE THREAD

**Issue by swablueme** [AHAAAAAAA/PokemonGo-Map#1217]
## Expected Behavior
All devices display the map and the pokemon.

## Current Behavior
Visiting the page via desktop loads perfectly fine (aka map, pokemon, etc), but when accessing it via a mobile (iO8.3) no map is loaded. Have attempted loading this in Chrome, Safari and Mercury - all three are blank and the cache has been wiped. Adblockers have been disabled for this task. It is completely blank: see this image http://i.imgur.com/kbybTyi.png 

In the Master branch, the map loaded perfectly on iOS. 

## Steps to Reproduce (for bugs)

1. python runserver.py -a PTC -u USERNAME -p PASSWORD -l "COORD1 COORD2" -st 9 -P 1025 -H SERVERADDRESS
2. SERVERADDRESS:1025 

## Context

;_;
## Your Environment

* Version used:  Latest development branch. I already have the #1162 fix  http://i.imgur.com/KPhM2Rr.png
* Environment name and version (e.g. Python 2.7): Server itself is running Debian 7 and is running I believe python 2.7.12
* Operating System and version (desktop or mobile):   **iOS8.3 Chrome/Mercury/Safari** to accesss SERVERADDRESS:1025 → it doesn't work on any of the three browsers and **Windows 10  Chrome** to accesss SERVERADDRESS:1025 → Works PERFECTLY

Does anyone else have this issue?

**Comment by roland3** [comment]
Same, iOS 9.3.2 Safari

**Comment by Bakies** [comment]
Pokemon and stops/gyms are showing up but the map itself does not show up for me on Chrome on Android 7.0

**Comment by Bakies** [comment]
Just kidding I pulled and its working now 
commit d59e1b9cb00a40ade203850973a3a777c0f0ee6e

**Comment by k33k00** [comment]
You will likely need to empty your cache and cookies. Which I have no idea how to do on IOS.

However on android open your chrome, go to history & click clear browsing data. Check cookies and site data, & cached images and files. Then click clear data.

If that doesn't work try checking request desktop site - **try this first**

**Comment by billbo99** [comment]
I have cleared the cache on my iphone (iOS 9.3.3) for both 'chrome' & 'safari' either way the page fails to load, and I get the error

```
Sorry! Something went wrong.
This page didn't load Google Maps correctly.
See the JavaScript console for technical details
```

however I do not know how to get to the console on my iphone to get to the true error message

**Comment by swablueme** [comment]
I wiped the cache a few times as stated in the op tried a desktop request and it still shows up blank.
