### ISSUE TITLE
Add caching data support

### ISSUE THREAD

**Issue by KonstantinKuklin** [AHAAAAAAA/PokemonGo-Map#122]
We should think about caching for the loaded data.
Also on loading command add one new flag --use-cache

**Comment by KonstantinKuklin** [comment]
also import\export for loaded information will be useful I think. It will be the first step to exchange information inside community

**Comment by JZ6** [comment]
cache planned for gym/pokestops location,
not for pokemon for obvious reasons

**Comment by DerScreever** [comment]
Im sorry, but we dropped the support for the master branch (example.py). 
This branch is deprecated.  
The new branch contains a much cleaner structure so pls report only issues related to the develop branch. 

Your development team
