### ISSUE TITLE
no monster, gym and pokestop on heroku

### ISSUE THREAD

**Issue by wellart** [AHAAAAAAA/PokemonGo-Map#1220]
no monster, gym and pokestop on heroku, just show the map, i already follow the instruction

**Comment by birdwell** [comment]
@wellart For help, go to the discord community. These tickets are for bug fixes. You haven't provided enough information for them to help you or fix a potentially problem.

**Comment by apoc254** [comment]
actually, this is accurate. It looks like the map is only drawing wild pokemon, despite the code being set up to handle gyms, pokestops and lures.

**Comment by GraafG** [comment]
Does this help?
I created a video: "How to install Pokemaps on Heroku":
https://www.youtube.com/watch?v=uv7za9LaxJk

**Comment by wellart** [comment]
https://peta-pokemongo.herokuapp.com/ i already follow on the video and get source from dev
