### ISSUE TITLE
Issue with login userName and Password

### ISSUE THREAD

**Issue by fankaisong** [AHAAAAAAA/PokemonGo-Map#1222]
first I used my gmail and both of my gmail could not log in due to incorrect password. However, I created a Trainer account with pure number as my password and it worked! 
I assume somehow this program has issue of reading special characters.  what do you think?

**Comment by SimpleCookie** [comment]
Did you specify the flag -a google -u username when attempting to use google?

**Comment by Tigershark2005** [comment]
and use quotes, special characters may be troublesome depending on which ones, since it's still command line

**Comment by fankaisong** [comment]
@SimpleCookie  Thank you I think that is my problem!
