### ISSUE TITLE
Notification of Pokemon

### ISSUE THREAD

**Issue by louispires** [AHAAAAAAA/PokemonGo-Map#1224]
## Expected Behavior
When Notification is clicked, the new map should open and navigate to the newly found Pokemon.

## Current Behavior
A new map is opened at the default location with no way of knowing where the newly spawned pokemon has appeared.
With the new -ns command, we can be running quite a few searches and the found pokemon could be anywhere.

## Possible Solution
When clicking the notification, open a new map and navigate to the exact location of the newly found pokemon.

## Steps to Reproduce (for bugs)

1. - Expand Filter
2. - Add common pokemon to "Notify of Pokemon"
3. - When Pokemon is found a notification is shown
4. - Click the Notification

## Context
I have a few servers running all over the place, since the search is looking within all the available locations, I have no idea which location actually has the specific Pokemon I'm looking for.

## Your Environment
Revision: 574
Windows 8.1
Python 2.7
Desktop

**Comment by ChristianLuxem** [comment]
Yes should be a Feature. Good Idea.
