### ISSUE TITLE
Remote access

### ISSUE THREAD

**Issue by thomja** [AHAAAAAAA/PokemonGo-Map#1226]
Hey

How do I get remote access to the server?

The master branch used flask and then I could just change the start params. Now I can't find flask anywhere in the .py files.

Thanks!

**Comment by adambowles** [comment]
`-H 0.0.0.0`

**Comment by k33k00** [comment]
Depending on what you're running. I run a ubuntu server over at digital ocean, I simply run it on port 80. I can then type the public IP and it's done.

**Comment by thomja** [comment]
I found the args just after posting this in the runserver.py.

It contains app.run but not sure if it's such a smart idea to replace the host param that is already in there. But will try with the -H command!

**Comment by TGM** [comment]
./runserver.py -H IP -P PORT

**Comment by skeldoor** [comment]
Would using "./runserver.py -H IP -P PORT" allow for execution via shell etc? How would be best for this?

**Comment by thomja** [comment]
Great got it running at my IP! Now I have to figure out why I can't move the map on my phone but that's another issue I guess.

@skeldoor I would recommend using something like putty for remote execution. But remember that the command window has to stay. I'm using a raspberry pi so Ima plug into a monitor and run a command window on it instead.

**Comment by k33k00** [comment]
I still have to connect to shell via port 22.

My args are _-H [public IP] -P 80_

Though you could use a different port and access via [public IP]:[selected port]

If you run from home, you may have to set up port forwarding on your router

**Comment by Quebroph** [comment]
I´m doing it via ssh.

**Comment by Tigershark2005** [comment]
The -H is like a binding in IIS. But you're really limiting yourself by going explicit. Use -H 0.0.0.0. That way it can be used with localhost, internal, or external IP. The host parameter is just a binding.

**Comment by Quebroph** [comment]
-H 0.0.0.0 made problems on my webserver for domain http://pokemap-goe.de:5000 yesterday. Now I´m using the IP of the webserver for -H parameter.

**Comment by Tigershark2005** [comment]
Do you own that domain?

**Comment by jonathan-dejong** [comment]
I've got a bash script setup in my digital ocean droplet. Called it run_pokemon.sh and placed it in root (because I got my whole setup in root.. shut up!).

`
#!/bin/bash
SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/PokemonGo-Map

#First kill all instances of runserver
pkill -f runserver.py

#Then we boot them up again!
cd PokemonGo-Map
python runserver.py -a ptc -u <myuser1> -p <mypw1> -l "55.699426 13.189148" -st 10 -H <myip> -P 5000
python runserver.py -a ptc -u <myuser2> -p <mypw2> -l "55.711516 13.200245" -st 10 -H <myip> -P 5000
`
I then got a cron job running every 30min to restart the map (just because there's sometimes issues with it long running or if server has dropped). 

`30 * * * * /bin/bash /root/run_pokemon.sh`

This is added to crontab using `sudo crontab -e`

**Comment by craigbaines** [comment]
@jonathan-dejong So this allows you to search in two spots, and all that infomation gets displayed in one map? 

Im trying it now myself, but once i booted up the second account, the first seems to of stopped searching. Any idea?

**Comment by jonathan-dejong** [comment]
@craigbaines Supposedly yes. I have no real way of confirming this works tho :/ 
In my case these locations are fairly overlapping since I live in a pretty small city. 

I read in another issue/pr that this was possible to do.

**Comment by craigbaines** [comment]
I read that too, i thought with you having done it you might be able to confirm it. 

Here's how my two consoles are looking since starting the second, you can clearly see the two area's im trying to do, the first has stopped searching though...

![gg](https://cloud.githubusercontent.com/assets/9383958/17061749/f540e778-5027-11e6-8c28-7571d90a044d.png)

**Comment by jonathan-dejong** [comment]
Lol you got shitloads of pincir :O 
Since it runs by the shell script I do not have any echo/logs to look at to determine if they are both operating. 

I guess I could try changing the seconds latlon to further away and check my map. 
I also read in another pr that this could be done but you had to set different ports (but both would save to the same DB since its the same script location). 

I'm gonna try same port first, then switch and see if there's a difference.

**Comment by craigbaines** [comment]
Yep i remember reading the same thing. Let me know how you get on, for me it definitely doesn't seem to work. When i tried to run that multi threading pull request i was getting locked database errors, could it maybe be  a similar thing?

**Comment by jonathan-dejong** [comment]
Have not seen the multi threading pr?

**Comment by craigbaines** [comment]
#810

**Comment by jonathan-dejong** [comment]
Ah, Have not tried that pr :) I honestly don't feel up for forking and pulling in prs here and there. I just run with the current dev version and do a pull req when I consider something valuable has happened :) 

In any case it appears my second runserver is not happening when on the same port. I'll try switching ports now.

**Comment by craigbaines** [comment]
Even on a second port it still doesn't seem to work for me :(

**Comment by jonathan-dejong** [comment]
same here. Second map on port 5001 isn't even running at all.

**Comment by craigbaines** [comment]
Knew it was all too good to be true lol

**Comment by jonathan-dejong** [comment]
lol, we'll probably see it in a pr later on. Perhaps that multi threading pr tweaked for multiple accounts. I've seen others talking about being able to add multiple accounts and locations to a config file. 

Give it a day or two ;)

**Comment by craigbaines** [comment]
That would be ideal yeah, fingers crossed. Glad we managed to do a little myth-busting though lol.

**Comment by k33k00** [comment]
@jonathan-dejong  fixed it 

python runserver.py -a google -u \**@gmail.com -p ** -l "\**" -st 3 -ns &
python runserver.py -a google -u **@gmail.com -p ** -l "\**" -st 5 -H 0.0.0.0 -P 80

**Comment by craigbaines** [comment]
I still got the error however i have found a fix if you dont mind scrapping pokestops

#1319

**Comment by k33k00** [comment]
strange it's working fine for me. Just needed to run all but with -ns flag

**Comment by craigbaines** [comment]
I think the issue i was having was all the pokestops, central park is littered with hundreds of them. They were making it slow and i guess locking up the database. Scrapping them has got rid of my problem an found so many more pokemon!

**Comment by jonathan-dejong** [comment]
@k33k00 

You're only running the -ns flag on the first one and specify host and port on the second? 
Or did you just sloppy-type your commands and left som out? :)

**Comment by craigbaines** [comment]
-ns is for the second, third, fouth etc instance's i believe.

**Comment by jonathan-dejong** [comment]
So you would only need to specify host and port on the first one and then -ns on each other one

**Comment by craigbaines** [comment]
i left the host an port in the others, i just simply added a -ns to the end an wollah!

**Comment by jonathan-dejong** [comment]
same as the "original?

**Comment by craigbaines** [comment]
```
1) python runserver.py -a google -u "******" -p "******" -l "40.783879, -73.964772" -st 10 -H 0.0.0.0 -P 7000

2) python runserver.py -a google -u "******" -p "******" -l "40.792031, -73.958578" -st 10 -H 0.0.0.0 -P 7000 -ns

3) python runserver.py -a google -u "******" -p "******" -l "Central Park, New York, NY" -st 10 -H 0.0.0.0 -P 7000 -ns
```

They produced this in no time at all now pokestops are disabled: 

![nb](https://cloud.githubusercontent.com/assets/9383958/17070337/3813b514-5053-11e6-9669-0958f9014d1f.png)

**Comment by k33k00** [comment]
sorry I'm a little late with the reply it seems. I put them that way around for no reason really, just random. 

I left out the host & port as that is for the webserver, which -ns disables anyway.  No need to add arguments that won't be used

**Comment by k33k00** [comment]
This is exactly what I'm running minus the personal info.
```
#!/bin/bash
SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/PokemonGo-Map

#First kill all instances of runserver
pkill -f runserver.py

#Then we boot them up again!
cd PokemonGo-Map
python runserver.py -a google -u **@gmail.com -p **** -l "ST5***" -st 5 -ns &
python runserver.py -a google -u **@gmail.com -p **** -l "ST5***" -st 5 -H 0.0.0.0 -P 80
```

Here are my results. 
![image](https://cloud.githubusercontent.com/assets/3812864/17070703/69c66ab4-5055-11e6-9b7b-72e9210b3c2c.png)

**Comment by jonathan-dejong** [comment]
Thanks :) 

Just a question, why do you run the -ns as background process (&)?
Are you triggering the shellscript manually and don't want the output? 

I just did a pull req and commented out the pokestops code but now I'm seeing this error instead:
`AttributeError: 'Namespace' object has no attribute 'settings'`

Maybe I should revert..

**Comment by k33k00** [comment]
At the moment yes it is still launched manually.

Not got around to cron just yet. It's on my todo list, I just want it to run for 8 hours without it totally dying first

I'm running a commit from a few hours ago still

**Comment by jonathan-dejong** [comment]
Thanks for the help btw. I got it up and running now for like 24h straight. I'm able to run 6 instances with pokestops commented out.
