### ISSUE TITLE
Dont show map

### ISSUE THREAD

**Issue by zeoril** [AHAAAAAAA/PokemonGo-Map#1229]
Here's a garbage , no errors in the console
![default](https://cloud.githubusercontent.com/assets/10652264/17059635/d0b40424-502e-11e6-89e9-f2abe63a3d51.png)

**Comment by Bakies** [comment]
Are there errors on the webpage?
Open your chrome inspect  element and look at console

**Comment by k33k00** [comment]
Try clearing the cache and hard reload. 

When on browser press F12 to open browser dev tools. Then right click the refresh button and select clear cache and hard reload.

**Comment by zeoril** [comment]
Do not loads resources
![screenshot_1](https://cloud.githubusercontent.com/assets/10652264/17060072/f83ee6f6-5030-11e6-98fb-2bd1973fc0b8.png)
