### ISSUE TITLE
Flask Error

### ISSUE THREAD

**Issue by Lagli1** [AHAAAAAAA/PokemonGo-Map#1231]
When installing, I am receiving the following error. This is after running python example.py -a ptc -u [USERNAME] -p [PASSWORD] -l "[LOCATION]" -st 10 (but changing everything to my login/location/etc.)

Traceback (most recent call last):
  File "runserver.py", line 11, in <module>
    from pogom.app import Pogom
  File "/home/laura/Documents/pogom/app.py", line 5, in <module>
    from flask import Flask, jsonify, render_template, request
ImportError: No module named flask

**Comment by frdmn** [comment]
Please checkout the `develop` branch and retry :)

**Comment by Lagli1** [comment]
@frdmn I'm already using the develop one

**Comment by wcastello** [comment]
It's what the error says, you don't have Flask. Run pip on the requirements and try again.

**Comment by timehm** [comment]
Well having the same bug here some specifics https://cdn.discordapp.com/attachments/204862053721178113/206058368870121474/unknown.png
https://images-ext-1.discordapp.net/eyJ1cmwiOiJodHRwczovL2Nkbi5kaXNjb3JkYXBwLmNvbS9hdHRhY2htZW50cy8yMDQzMzkxNjk0NTgxMjY4NDkvMjA2MDQ3Mjk4ODIyNzMzODI0L3Vua25vd24ucG5nIn0.Onl91nC_wPEw5PbB5QMI4aW4Ch4.png
https://cdn.discordapp.com/attachments/204339169458126849/206053929522298880/unknown.png
Id one it as an admin with both developer, and master.

**Comment by nekoyokoshima** [comment]
make sure you run 

`pip install -r requirements.txt`

**Comment by wyudong** [comment]
As @nekoyokoshima said, install dependencies when you checkout a new branch for the first time. For Mac, running `sudo pip install -r requirements.txt` works for me.

**Comment by timehm** [comment]
not helpful did you eve see the image neko? Its when that gets corrupted one of the files stopped working, the fix though is to uninstall python, delete the python folder in c:/ and then install it again.

**Comment by timehm** [comment]
Specifically for me it was Markupsafe

**Comment by bwithbroe** [comment]
I'm having the same problem. It is NOT helped by running `sudo pip install -r requirements.txt`. Both `pip list` and `pip show flask` seem to indicate that flask is already installed. Any other suggestions?

**Comment by andrewda** [comment]
Closing this as it's not related to PokemonGo-Map. Feel free to keep discussing solutions, though.
