### ISSUE TITLE
New Feature Request!

### ISSUE THREAD

**Issue by neruve** [AHAAAAAAA/PokemonGo-Map#1232]
Any possibility to add a place for the pokemon to mark if it is caught to remove it from the map? This would come in handy so you don't pull the map up later and think there is a new one there when it turns out it is the same one you caught like 10 min ago.

**Comment by Tigershark2005** [comment]
I see what you're going for but I'm not sure it would be practical. They don't stick around very long anyway. If you go a few blocks to catch one, then go back to where you were first, it would be gone. Also gone from the map. It would be a temporary store of a boolean flag as far as the programming goes but I really don't see it being useful when you're actually out and about, since they're removed when they expire anyway.

**Comment by craigbaines** [comment]
Maybe something super simple, clicking on the image replaces it with a greyed out one or something? Even if it only lasted until you refresh it would be handy.

**Comment by Tigershark2005** [comment]
Greyed out may require a second set of icons to be created though. I'm thinking there's a chance that right-clicking could flag that one as expired early, most likely by changing its time in the pokemon variable or temp db, causing the script to take it off the map and show in the console that it scavenged it. I guess it would then depend on if it's discovered again before it actually expires.

**Comment by jonathan-dejong** [comment]
right clicking is a bad idea since lots of ppl use this on their touch devices. If this would be implemented I'd rather see an additional link/button in the infowindow "Mark as caught" or something. No new graphics, no hidden interaction.

**Comment by Tigershark2005** [comment]
I only use it on my Android, but right-click is long press or double touch on mobile. Would still work fine.

**Comment by jonathan-dejong** [comment]
@Tigershark2005 I use it on my android as well but it just seems stupid to me to add it as a right click or long press (for touch) as it's another hidden interaction. People would either have to accidentally stumble upon it or read about it (and judging from the amount of duplicate questions here and in the chat people *don't read*)

**Comment by welshboy** [comment]
I think a link/button in the popup once you click on the pokemon would be a good idea. Rather than long press/right click

**Comment by chuyskywalker** [comment]
> Greyed out may require a second set of icons to be created though

A CSS filter should be able to do that... yeah http://caniuse.com/#feat=css-filters and thus:

```
.caught {
  filter: grayscale(100%);
}
```
