### ISSUE TITLE
Usage page on wiki shows -ar switch, gives error.

### ISSUE THREAD

**Issue by JKapitein** [AHAAAAAAA/PokemonGo-Map#1236]
The -ar switch throws an exception in the search thread because it matches the -a switch, setting the authentication provider to 'r', and -ar is apparently not in yet (I just pulled).

**Comment by Tigershark2005** [comment]
It was in the master branch, it's not being used in develop. There are a number of things I've found that need to be updated but I can't find any way to contact the moderators or anything to let them know. No message, not contact button. Unfortunate.

**Comment by JKapitein** [comment]
They'll see it eventually here. It oscillates in and out of the usage page of the wiki (which is awful now compared to the first few revisions, by the way), so does generate quite a few tickets. Should probably be fixed.

**Comment by FrostTheFox** [comment]
@JKapitein The wiki was originally made for master, we haven't had time recently to work on overhauling the wiki, Some things in there have been deprecated in dev, but still exist in master, which is probably why it's not gone.

**Comment by FrostTheFox** [comment]
@Tigershark2005 We have a discord for reporting these things. https://discord.gg/Kzp4yky

**Comment by Tigershark2005** [comment]
It's not really a wiki if it can't be edited

**Comment by commanderjsoc** [comment]
Using `example.py ........ -ar 1` worked for me

**Comment by FrostTheFox** [comment]
@commanderjsoc That would be the master branch. That still has -ar. We're talking about dev branch here.
