### ISSUE TITLE
Detected Pokemons depending on level of connecting account

### ISSUE THREAD

**Issue by Quebroph** [AHAAAAAAA/PokemonGo-Map#1239]
Dear community,

i am running a pokemap for my city Göttingen, Germany. I use my own lvl1 account (not even one Pokèmon caught) for scanning the city.

As is see on http://pokemap-goe.de there are just basic/low pokemon appearing.

How can we handle this?
Is it possible to run different instances with diffent accounts with different levels an give the user the chance to switch the maps by level?

**Comment by BillyWM** [comment]
I think you're just getting unlucky. I've seen Electabuzz, Hitmonlee, Dratini, Magmar, Jolteon, Pidgeot...

**Comment by craigbaines** [comment]
Does your level matter? I though everyone saw the same pokemon? You just got different CP's ?

**Comment by Tigershark2005** [comment]
@craigbaines that's accurate. I have had instances where something pops for my game client but wasn't on the map, even with very small scans to test what was happening. To me, that means the game occassionally spawns one/some just for your client. It would make sense in the case of incense or lures.

**Comment by Quebroph** [comment]
Ok - thanks for the answers. 

1.  How do you set up your search-locations to scan the complete city?
Manual/Automatic?! Are the any helper, which generate the code?

2. How do you run/start/stop all instances in background of the server?

3. How do you check if all instances are running? (and reactivate them if offline)?

**Comment by FrostTheFox** [comment]
We have no evidence that different level accounts produce different pokemon. The search methods are being worked on at the moment.

**Comment by jonathan-dejong** [comment]
@Quebroph for 2/3 check my answer here: https://github.com/AHAAAAAAA/PokemonGo-Map/issues/1226

**Comment by CarlTaylor1989** [comment]
You can see all pokemon regardless of level.
