### ISSUE TITLE
Endless cycle

### ISSUE THREAD

**Issue by KonstantinKuklin** [AHAAAAAAA/PokemonGo-Map#124]
The script can not get enough and it all is not enough!
as soon as the download has finished, so it continues again ... (commit hash 204c2156bab8e411d76fcd4bc7a820d3b61a1ad9 )

> [-] retrying_api_req: request error (('Connection aborted.', BadStatusLine("''",))), retrying
> ('Completed:', 96.0, '%')
> [-] looping: step 96 of 100
> ('Completed:', 97.0, '%')
> [-] looping: step 97 of 100
> ('Completed:', 98.0, '%')
> [-] looping: step 98 of 100
> ('Completed:', 99.0, '%')
> [-] looping: step 99 of 100
> ('Completed:', 100.0, '%')
> [-] register_background_thread called
> [-] register_background_thread: queueing
> [-] main
> [!] Your given location: ul. ********, Moskva, Russia
> [!] lat/long/alt: ***** ****** 0.0
> [+] RPC Session Token: TGT-7712*********** ...
> [+] Received API endpoint: https://pgorelease.nianticlabs.com/plfe/135/rpc
> [+] Login successful
> [+] Username: *****
> [+] You started playing Pokemon Go on: 2016-**-** ********
> [+] POKECOIN: 0
> [+] STARDUST: 0
> [-] looping: step 0 of 100
> ('Completed:', 1.0, '%')
> [-] looping: step 1 of 100
> ('Completed:', 2.0, '%')
> [-] looping: step 2 of 100
> ('Completed:', 3.0, '%')
> [-] looping: step 3 of 100

**Comment by nborrmann** [comment]
working as intended.
