### ISSUE TITLE
Java EE server support

### ISSUE THREAD

**Issue by RSginer** [AHAAAAAAA/PokemonGo-Map#1241]
## Expected Behavior
I want no make a java ee server with restful webservice api to provide the pokemon location but i dont know python can you provide my a rest api to consume in java?

Windows 8.1
Netbeans IDE
Java 8

**Comment by frdmn** [comment]
There is no API docu yet. Check this though:

https://github.com/AHAAAAAAA/PokemonGo-Map/blob/develop/pogom/app.py#L18-L22
