### ISSUE TITLE
Is there any option to search only Pokemons?

### ISSUE THREAD

**Issue by vadimsvs** [AHAAAAAAA/PokemonGo-Map#1243]
How to delete Gyms and Pokestops from search script? I believe it will run faster if it will not check gyms and pokestops every time.
Thanks.

**Comment by DanielVolz** [comment]
Same as: https://github.com/AHAAAAAAA/PokemonGo-Map/issues/1205

**Comment by Tigershark2005** [comment]
You can stop them from displaying but realize that what is being returned from the server is a very basic set of information. Technically, yes it would speed it up, but that transaction consists of a couple lines of text. You canstop it from displaying in the map, which may actually take longer than the transaction itself. use Filter in the top left.

**Comment by vadimsvs** [comment]
Filter on website will not trigger to stop searching by script.

**Comment by Tigershark2005** [comment]
Right. I said it would stop it from displaying. Not that it wouldn't stop asking for it.

**Comment by Quebroph** [comment]
There should come a admin interface for the pokemap soon ;)

**Comment by ChristianLuxem** [comment]
I am not sure about the API, but you are right, if there is a possibility to search only for pokemons in the backend, without the gyms, which are possible not displayed, we should avoid to search for them. 
This should be a performance enhancement. 
Something like: 
function generateAPICall:
 if (DisplayPokemons) : 
      API + "?searchPokemon=true"
if (DisplayPokestops)
    API + "&searchPokeStops=true"
.....

**Comment by fankaisong** [comment]
I want to know the -st 10 (foot step), does that apply for i foot step= 50m or just our regular foot step?

**Comment by alpadev** [comment]
How is foot steps related to that issue? Also how about utilizing the search before asking already answered questions?

RTFM: https://guides.github.com/features/issues/
