### ISSUE TITLE
Question: Pokemon spawns?

### ISSUE THREAD

**Issue by pickett2k** [AHAAAAAAA/PokemonGo-Map#1246]
Sorry guys I'm just wondering, does it make a difference what account you login to the server with as to what Pokemon you will see? I'm using a brand new level 1 seperate account to login but will this mean it doesn't show rarer and higher level Pokemon on the map due to my level?

Thanks

**Comment by Miskerest** [comment]
pickett2k: this is more of a game-design question, but either way...
I believe pokemon spawns are universal for all players, the only variance is their CP range. I could be mistaken, though.

**Comment by pickett2k** [comment]
Apologies if not really relevant here, I just figured most people without access to the back end spawns wouldn't be able to answer that anyway , glad that's the case

**Comment by CarlTaylor1989** [comment]
No you can see all pokemon regardless of level
