### ISSUE TITLE
New Cors Option in Easy Setup / Requirements

### ISSUE THREAD

**Issue by Erin6641** [AHAAAAAAA/PokemonGo-Map#1247]
I believe the following line
Easy Setup/requirements.txt
16 +flask-cors==2.1.2

needs to be changed to
Easy Setup/requirements.txt
16 +flask_cors==2.1.2

Forgive me if I am stupid, this seemed to be the only thing that worked to fix it for me.

**Comment by KnightHawk3** [comment]
Are you sure that works?

https://pypi.python.org/pypi/Flask-Cors/2.1.2

Flask-cors is a package but flask_cors is not a package on PyPi?

**Comment by Erin6641** [comment]
Like I said, changing it was the only thing that worked for me. Before I did that, the easy setup would not run. It would throw an error.

**Comment by KnightHawk3** [comment]
Can you share the error?

**Comment by Erin6641** [comment]
It is long gone in the cmd but I might be able to re-create by changing it back. Give me a bit
