### ISSUE TITLE
Speed up searching

### ISSUE THREAD

**Issue by resper** [AHAAAAAAA/PokemonGo-Map#1254]
Hello,

is there a possibility to speed up the search? I just found the delay time between the loops.

Sites like Pokevision, that looks like the same source, have a higher speed scan.

**Comment by fankaisong** [comment]
can anyone tell me the advantages of using this one? from what I have seen, this program requires installation, but pokevision.com does not. however, it is not limited for scanning.

**Comment by shivampaw** [comment]
@fankaisong Pokevision isn't open source, longer development times and it's servers are unstable while you can use this on your own server and set it up.

**Comment by codengine** [comment]
I believe it is in order to prevent banning for too frequent queries and would be cautious. An option would be good.
