### ISSUE TITLE
how do you run the dev branch?

### ISSUE THREAD

**Issue by delrio1110** [AHAAAAAAA/PokemonGo-Map#1256]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by xijbx** [comment]
It's kind of helpful to actually fill in the form. Anyway, it's not the same as running the master branch.

`python runserver.py -a ptc -u username -p password -l "your location" -st 10`

Change ptc depending on whether you're logging in with Gmail or PTC, and username/password to your username/password. And change "your location" to the location you're going to start the map at (like your post code or ZIP code).

**Comment by delrio1110** [comment]
sorry and thank you sir

**Comment by delrio1110** [comment]
this is what keeps spamming over and over
 
2016-07-22 12:19:44,974 [   auth_ptc] [   INFO] PTC Login successful
2016-07-22 12:19:45,101 [     search] [   INFO] Failed to login to Pokemon Go. Trying again.

**Comment by xijbx** [comment]
The PG servers are likely inaccessible, or the account is banned perhaps?

**Comment by delrio1110** [comment]
im able to run the same account on the master and it starts, strange. Ill create a new account

**Comment by delrio1110** [comment]
still no luck, any suggestions?
this is what im running:
python runserver.py -a ptc -u {myusername} -p {myPassword} -l "25.974252, -80.350158" -st 10 

![2016-07-22_1237](https://cloud.githubusercontent.com/assets/1231453/17064166/2c4b778e-5009-11e6-9fee-390f76c4afdd.png)
