### ISSUE TITLE
Missing "owned_by_team" key for neutral gyms

### ISSUE THREAD

**Issue by SuperMartas** [AHAAAAAAA/PokemonGo-Map#1258]
Hi,
I found out that if some gym is neutral in a scan, the scan will fail with this message:
`Scan step 1 failed. Response dictionary key error.`
I also found out that the key "owned_by_team" returned from PGO API is missing, so the response (f variable from models.py:99 respectively) looks like this (concrete values are intentionally falsified):
`{'last_modified_timestamp_ms': 1469196728070L, 'latitude': 1.234567, 'enabled': True, 'id': u'xxx', 'longitude': 1.234567}`

**Comment by wcastello** [comment]
Can you give me a location where there is some neutral gym so I can check this?

**Comment by SuperMartas** [comment]
50.071986, 16.929946

**Comment by azotov** [comment]
I confirm the bug. The problem can be solved by adding the following code in pogom/models.py  after the line "_else:  # Currently, there are only stops and gyms_" and before assigning values to _gyms[f['id']]_ variable:
```
                if not 'owned_by_team' in f:
                    f['owned_by_team'] = 0
                    f['gym_points'] = 0
                    f['guard_pokemon_id'] = 0
```

**Comment by SuperMartas** [comment]
468b64252988afc8932574c492fef5e7c55997db fixed it.
