### ISSUE TITLE
Question: Pokedex 

### ISSUE THREAD

**Issue by craigbaines** [AHAAAAAAA/PokemonGo-Map#1259]
Quick question, is your pokedex info available, more specifically what Pokemon you have caught / not caught? 

If so, would a toggle option for automatically sending notifications for un-caught Pokemon be a possibility?

Just a random thought. 

Thanks

**Comment by xijbx** [comment]
It should be available on the API provided you've used the same info to log in to PG as your main account (I use a secondary account myself). This could be pretty cool if not already in implementation.

**Comment by shivampaw** [comment]
It would be possible but nobody here should be using their main account as it can get banned.

**Comment by craigbaines** [comment]
Never even thought about the fact i use a new account for the map an not my main! Doh! lol.

**Comment by xijbx** [comment]
Using a second account is good as if it gets banned, I can just make another. 8)

**Comment by karezhest** [comment]
Maybe with a button on pokemon info?

**Comment by craigbaines** [comment]
Or logging in with your main and hitting a save/update pokedex info button or something before logging in your second account, an have it run off that.

**Comment by BillyWM** [comment]
@craigbaines: I still wouldn't recommend that. The protocol isn't mapped 100% (some pieces are still marked 'unknown' but given a value anyway). Even if you're not warping, there's a slim chance they can still detect you're running 'headless' and ban you.
