### ISSUE TITLE
error code 1 with pycryptodomex

### ISSUE THREAD

**Issue by wolv32** [AHAAAAAAA/PokemonGo-Map#1261]
When I run pip install -r requirements.txt I get an "error code 1" issue with pycryptodomex.

`Command "/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -u -c "import setuptools, tokenize;__file__='/private/var/folders/b3/z9krs0gs0kj10d7zfb5f64w00000gn/T/pip-build-OIoHvK/pycryptodomex/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/b3/z9krs0gs0kj10d7zfb5f64w00000gn/T/pip-qwZCl5-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/b3/z9krs0gs0kj10d7zfb5f64w00000gn/T/pip-build-OIoHvK/pycryptodomex/`
## Full Pastebin

http://pastebin.com/YWFaqhfA

Last night during my attempts I had a similar error code 1 with gpsouath, for what that's worth.

## Environment

* Environment name and version (e.g. Python 2.7): pip 8.1.2, Python 2.7.12, setuptools 24.3.0
* Operating System and version (desktop or mobile): Desktop Mac OS 10.11.5

Thanks in advance!

**Comment by cjhwick** [comment]
Had this same issue, install the command line tools, user xcode-select -switch and point it to the directory the tools are in. Should work after that.

**Comment by wolv32** [comment]
Thank you very much. Appears to have fixed things.

Used:
`xcode-select --install`
then
`xcode-select -p`
then
`pip install -r requirements.txt`

Worked perfectly. Really appreciate it!

**Comment by serg06** [comment]
Solution for normal people who don't have xcode-select:

`pip install --upgrade pip`

then

`pip install -r requirements.txt`
