### ISSUE TITLE
Nginx reverse proxy, characters not showing

### ISSUE THREAD

**Issue by ScouseTS** [AHAAAAAAA/PokemonGo-Map#1263]
Hi,

I'm using nginx proxy_pass in order to make my install public facing for myself and a friend, I know they're useless at remember ports hence the proxy_pass

Has anyone managed to get theres working with nginx? When I set it via nginx none of the characters appears, if I test it via localhost it displays them fine.

Possibly a bug?

**Comment by KazWolfe** [comment]
Running here on proxy_pass just fine.

You need to use a later version -- the earlier ones rely on the files being at the root dir, which they may or may not be depending on your setup.

**Comment by mrjack711** [comment]
Hi, 

I'm having this same problem.
Using latest develop

Site config in nginx:


                location /pokemap {
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Host $http_host;
                proxy_set_header X-NginX-Proxy true;
                proxy_pass http://ip-address:5000/;
                proxy_redirect off;
        }

Is there something else thats needed in the nginx site?

Thanks

**Comment by KazWolfe** [comment]
Using commit c5a15376e4fae4430dcc7d5e2865e0ece33de8c8, the following config works:

```
	location /slo/ {
		proxy_pass http://127.0.0.1:3718/;
	        proxy_set_header Host $host;
	        proxy_set_header X-Real-IP $remote_addr;
	        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	        proxy_set_header X-Forwarded-Proto $scheme;
	}
```

Replace 3718 with the port you're currently running on.

**Comment by nekoyokoshima** [comment]
You can also use the -H and -P options while instantiating the server 

ex.  python example.py -a ptc -u <user> -p <passwd> -l "locX locY" -st 10 -H 0.0.0.0 -P 3718

**Comment by mrjack711** [comment]
Its working now.

I needed the extra / after the location.
Mine is now:

            location /pokemap/ {
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $http_host;
            proxy_set_header X-NginX-Proxy true;
            proxy_pass http://ip-address:5000/;
            proxy_redirect off;
    }

Thanks for your example
