### ISSUE TITLE
ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by iluminator5** [AHAAAAAAA/PokemonGo-Map#1264]
Hello!

I did everything right an now it's searching for pokemon like it should be. But when I go to Google Chrome and type in http://localhost:5000, I get ERR_CONNECTION_REFUSED.

Port is open(I checked) and firewall isn't blocking it. I am running on Windows XP SP3.

If you have any suggestions please tell me.

**Comment by andrewda** [comment]
Try setting the port to something else, like 8005, using `--port 8005`.

**Comment by iluminator5** [comment]
Yeah, about that...how do I change the port?

**Comment by andrewda** [comment]
Use `--port 8005` when running `runserver.py` or `example.py`.

**Comment by iluminator5** [comment]
So I put `--port 8005` right after `example.py` in the last command before searching for pokemon. It still doesn't work. It gives the same error. It's like I can't connect to any local host ports.

**Comment by VIPkiller17** [comment]
Are you trying to connect from another device? If so try using your system's (on which you opened the port) IPV4 adress with the port ex.: 168.254.67.23:5000 and not localhost.

**Comment by iluminator5** [comment]
No, I am trying to connect from the same device that I opened the port on, my PC.

**Comment by hugecannon** [comment]
@iluminator5 For me it was the missing `--host 0.0.0.0` argument to runserver.py.

Not sure when that was added

**Comment by cajunjoel** [comment]
I had to put in the IP of my server for --host, so instead of --host 0.0.0.0, I put in --host 123.456.789.123 (or whatever)... That seemed to work well.

**Comment by iluminator5** [comment]
Nope...still doesn't work after trying all the suggested changes.
