### ISSUE TITLE
The map height is incorrect

### ISSUE THREAD

**Issue by Xolus** [AHAAAAAAA/PokemonGo-Map#1268]
## Expected Behavior

Full page Google maps

## Current Behavior

Google Maps height is only at ~100px. Unable to see anything

example: https://gyazo.com/8aed47e22859edf2e36d728a2b2f57be

## Possible Solution

I honestly have no idea

## Steps to Reproduce (for bugs)
1. Run server
2. Go to site

## Your Environment
* Version used: Develop, Newest as of 18:20 ( Amsterdam Time )
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): Windows 10 & Android Marshmallow

**Comment by tripout** [comment]
I can confirm the same thing is happening to me as well.  I was just about to post a bug.

**Comment by MrFoxxington** [comment]
I'm getting this issue too.

Using nginx to proxy requests.
Browsing to IP:5000 seems to work fine though.

**Comment by blankse** [comment]
Possible fix: https://github.com/AHAAAAAAA/PokemonGo-Map/pull/1277

**Comment by Xolus** [comment]
This fixed it
Thanks @blankse

**Comment by MRokas** [comment]
It was fixed in #1221 ...
