### ISSUE TITLE
not showing pokestops and gyms

### ISSUE THREAD

**Issue by BartDuwez** [AHAAAAAAA/PokemonGo-Map#1269]
<img width="620" alt="capture" src="https://cloud.githubusercontent.com/assets/17930371/17063806/66fd3946-5039-11e6-82d9-de4065b7272f.PNG">

As you can see, its only showing the pokemons, but there's tons of stops and gyms there. I dont know how to fix it, or what i am doing wrong, probably something really stupid.

* Version used: newest version
* Environment name and version (e.g. Python 2.7): python 2.7 link from wiki
* Operating System and version (desktop or mobile): Windows 10 in bootcamp on macbook pro

**Comment by Faustvii** [comment]
Have you enabled them in the Filter menu? http://i.imgur.com/5MtM5fb.png

**Comment by BartDuwez** [comment]
i dont see any menu... i'm on firefox i'll try chrome

**Comment by Faustvii** [comment]
If you're not seeing the menu you must be running the master branch build. I would recommend switching to the develop version. I've got no issues in firefox with the develop build.

**Comment by BartDuwez** [comment]
Thanks it worked, i had to do the api key thing first, but now i have the complete map with all stops and gyms :) thanks

**Comment by Faustvii** [comment]
Glad to hear that the issue has been solved.
Remember to close the issue.
