### ISSUE TITLE
Ignore and Only do not appear to be working

### ISSUE THREAD

**Issue by Darkrift411** [AHAAAAAAA/PokemonGo-Map#127]
I started the script with:
python example.py -u XXXX -p XXXX -l "xxx.xxx -xxx.xxx" -st 4 **-i 16,19,23,27,41,46,56,63,64,74,84** 2>/dev/null

It started correctly and began showing pokemon however it appeared to be showing all. I saw lots of Ekans (in ignore list) and also an Evee (not in ignore list). Figuring I might have mis-used -i, I changed it to --ignore:
python example.py -u XXXX -p XXXX -l "xxx.xxx -xxx.xxx" -st 4 --ignore 16,19,23,27,41,46,56,63,64,74,84 2>/dev/null

Exact same results. I am showing pokemon on the map that are and are not listed in the ignore list. Again, hoping I was 'Doing it Wrong'[TM]
I tried putting the list in quotes (eg. " --ignore "16,19,23,27,41,46,56,63,64,74,84" ) however this also did not do anything.

### Environment info
Operating System: Linux (mint)

Installed version of Python: 2.7.6

### Steps to reproduce
1. Start the scanner with pokemon to ignore
2. View the map
3. Notice ignored pokemon are displayed

### What have you tried?
1. Multiple different formats for the command to ensure reduced chance of user-error

**Comment by nborrmann** [comment]
you need to use pokemon names, not ids.

**Comment by Darkrift411** [comment]
Awesome, that works for me. I would recommend editing this to show it needs that text added to the README as it shows:

| -i, --ignore | Comma-separated list of PokÃ©mon to ignore |

I would assume most would guess it is based on ID and try that first as I did. Thanks again for the quick response!

**Comment by Grabbed** [comment]
For anyone wondering, it will need to look something like this: **-i Spearow,Rattata,Drowzee,Zubat,Pidgey,Venonat,Weedle,Paras,Shellder,Krabby,NidoranF,NidoranM,Goldeen,Fearow,Caterpie,Pidgeotto,Jynx**

**Comment by Darkrift411** [comment]
Issue would appear to be resolved by https://github.com/AHAAAAAAA/PokemonGo-Map/commit/e5778491237e757defde038911fc4bddb15d41ff

 +| `-i` `--ignore`            | Comma-separated list of Pokémon names to ignore |          | 

I think this can be marked as resolved now. Many thanks.

**Comment by JZ6** [comment]
fixed
