### ISSUE TITLE
"Login Details Here," no map present

### ISSUE THREAD

**Issue by KazWolfe** [AHAAAAAAA/PokemonGo-Map#1273]
## Expected Behavior

The map should load, instead of the "Login Details Here" message

## Current Behavior

See image:
![screenshot from 2016-07-22 09-29-37](https://cloud.githubusercontent.com/assets/5192145/17063965/d66d7336-4fee-11e6-9fec-f4ca40d489ad.png)

## Steps to Reproduce (for bugs)

1. Open the webpage

## Context

I an unable to view the map due to this error.

## Your Environment

* Version used: Commit 006f7a773b49aba83d6b293ba989c3adb2881536
* Environment name and version (e.g. Python 2.7): Python 2.7.6
* Operating System and version (desktop or mobile): Server -- Ubuntu 14.04 LTS, Client -- Any
* Login method used: Google

**Comment by Faustvii** [comment]
Try doing a CTRL + F5 refresh to clear the cache, that fixed it for me.

**Comment by KazWolfe** [comment]
Caches cleared on client with no such success.

**Comment by Faustvii** [comment]
Can you try updating to this commit https://github.com/AHAAAAAAA/PokemonGo-Map/commit/c5a15376e4fae4430dcc7d5e2865e0ece33de8c8

**Comment by KazWolfe** [comment]
There we are.

Fixed as of commit c5a15376e4fae4430dcc7d5e2865e0ece33de8c8
