### ISSUE TITLE
DEV Location not appearing

### ISSUE THREAD

**Issue by SkyBadPT** [AHAAAAAAA/PokemonGo-Map#1278]
I saw one print screen on twitter with the option of location but this is not appearing in my website, and im using the DEV version, this is the screenshot: https://pbs.twimg.com/media/Cn-yPItUMAAz1oT.jpg:large 
how can activate it?

**Comment by FrostTheFox** [comment]
It's not put into the dev version yet. It's awaiting approval.

**Comment by SkyBadPT** [comment]
Oh sure thanks!!
