### ISSUE TITLE
Localization should change Pokedex Link

### ISSUE THREAD

**Issue by ChristianLuxem** [AHAAAAAAA/PokemonGo-Map#1282]
## Expected Behavior
If i change the Localization to germany and click on the link to the pokedex of a Pokemon on my map, i want to go to the german Pokedex, not to the english Pokedex.

## Possible Solution
The link for a pokedex is the following: http://www.pokemon.com/us/pokedex/grimer
Just do the following: split it up with something like  www.pokemon.com/ + locale + "/pokedex" + name

## Steps to Reproduce (for bugs)

1.Open Map with Location "de" or something else
2.Click on a Pokemon
3.Click on the number of the pokemon in the popup
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by blankse** [comment]
I created a PR https://github.com/AHAAAAAAA/PokemonGo-Map/pull/1285
