### ISSUE TITLE
REQUEST: Phone tracking based on location.

### ISSUE THREAD

**Issue by neruve** [AHAAAAAAA/PokemonGo-Map#1294]
So I have a dynamic DNS service on my router so I can access stuff from home. So I run this on my home server. Is there a way to make it update the location based on the browser location I am using to view the site? 

Example. Right now I have a few batch files that I run depending on where I am (home and work)

It would be cool when I was out and about it would update the scan location based on where my phone is. So If I went to lunch at lets say McDonalds down the street it would show me things around there.

I don't even know if this could be implemented. Not sure how it would work. Or maybe a feature on the page that you can click to pull your current location.

**Comment by timelf123** [comment]
Definitely doable with current geolocation APIs, `watchPosition` on Firefox, and calling `getCurrentPosition` periodically in other browsers

**Comment by neruve** [comment]
hopefully someone makes this happen. Way over my head haha.

**Comment by prajwalkman** [comment]
It's on the way:
https://github.com/AHAAAAAAA/PokemonGo-Map/pull/1255

**Comment by neruve** [comment]
Thank you!

**Comment by timelf123** [comment]
https://github.com/AHAAAAAAA/PokemonGo-Map/pull/725 - works works by scanning your location periodically (not currently configurable, set to 20s)

https://github.com/AHAAAAAAA/PokemonGo-Map/pull/1255 - works by clicking a button to update your location

**Comment by neruve** [comment]
How does this effect the way things are ran initially? Do you still have to input a location in the runserver.py command or is this done automatically when its opened from a browser now?

**Comment by talentedmrripley** [comment]
@neruve You still need to specify a starting location.  You can't launch the process without it.
@timelf123 I believe #725 has a feature to adjust the refresh time.  But I can't find the comment about it right now.
