### ISSUE TITLE
pokemon go map and filter and nothing more, i don't know the cmd runs right but the local host doesnt want display map and other

### ISSUE THREAD

**Issue by ramil111** [AHAAAAAAA/PokemonGo-Map#1297]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by neruve** [comment]
Are you getting an error about javascript not loading the map?

**Comment by balletboy927** [comment]
@neruve I have the same issue as @ramil111. I am getting a java script error message (see below). I've clear the cache and local storage and still no dice. Any ideas?
<img width="1298" alt="screen shot 2016-07-22 at 6 27 30 pm" src="https://cloud.githubusercontent.com/assets/20594199/17074963/0f6f2b34-503a-11e6-9e9f-a105ec367a86.png">

**Comment by balletboy927** [comment]
Figured it out. I entered my API key incorrectly
