### ISSUE TITLE
App refreshable

### ISSUE THREAD

**Issue by brntphish** [AHAAAAAAA/PokemonGo-Map#1303]
I am going to attempt to wrap this into a swift app to allow the app to grab your current location when a refresh button is pressed.

I should be able to include the python binaries in the app bundle. This will allow the app to run from a Mac so that u can have a "Pokemon go mobile command center"

**Comment by genericapplesauce** [comment]
This should be a pull request not an issue. OP, if you could close this, that'd be great.
