### ISSUE TITLE
Flask module not found with latest update

### ISSUE THREAD

**Issue by Zach1993** [AHAAAAAAA/PokemonGo-Map#1304]
When I try to run the latest dev branch I get an error 
" Traceback (most recent call last):
  File "runserver.py", line 10, in <module>
    from flask_cors import CORS, cross_origin
ImportError: No module named flask_cors"

Any ideas on how I can import CORS? It has been working like a dream until my last sync.

**Comment by timdine** [comment]
Rerun the installation of the requirements.txt.  There is a new module that needs installing.

**Comment by mleahy314** [comment]
or type this
pip install -U flask-cors

**Comment by Zach1993** [comment]
Perfect! Thanks.
