### ISSUE TITLE
Map stops showing pokemon after a certain amount of time?

### ISSUE THREAD

**Issue by theblackmarmoset** [AHAAAAAAA/PokemonGo-Map#1309]
When the program finishes looping as in it gets to 100% 100/100...  it still continues looping but new pokemon don't show up.  Only the old pokemon show up and once they expire no pokemon show up until I restart the server.  Anyone know a fix?

**Comment by devinjparsons** [comment]
Are you on the master branch? If so this was a problem, I would switch to develop branch. More features and much more stable.

**Comment by theblackmarmoset** [comment]
Okay, I'm not sure how to use the develop branch.  I am on the master branch because I tried getting develop branch to work with no success.   I'll post the error I get when I try to use develop branch again here.   Brb downloading develop branch.

**Comment by theblackmarmoset** [comment]
Actually could you link me to the download for the develop branch?  I can't seem to find it.

**Comment by JiayiZ** [comment]
I met the same problem. I am not sure if it was master branch, because I used the link in the wiki Heroku-Deployment to deploy it to the server. I also tried to set AUTO_REFERESH, but didn't help.

**Comment by skywalkerx86** [comment]
use git to switch branches from master to develop

**Comment by theblackmarmoset** [comment]
@skywalkerx86 How?

**Comment by theblackmarmoset** [comment]
I'm really bad with this stuff

**Comment by theblackmarmoset** [comment]
lol jk, just got it.

**Comment by theblackmarmoset** [comment]
Am I able to use the -o feature in the develop branch?

**Comment by theblackmarmoset** [comment]
This is the error I get.  Anyone know how to fix it? http://prntscr.com/bw94aj

**Comment by genericapplesauce** [comment]
Actually, I'm on the most recent develop, and I still have the issue of the map not updating after it reaches 100% in the scan.

**Comment by theblackmarmoset** [comment]
I'd still like to know how to run it on the develop branch so if anyone knows a fix to the error I got up there please tell me. <3

**Comment by ShawnHardwick** [comment]
Might be related to how the PTC servers were down when you attempted and just came up a little while ago.

**Comment by theblackmarmoset** [comment]
Yeah it's working now.  But how do I get rid of the red marker thing?  Would be nice to know. http://prntscr.com/bwax49

**Comment by mhelmetag** [comment]
@theblackmarmoset, that exception had to do with a not so graceful login. That has been resolved on the develop branch. I have been running my instance for a few hours now with no issues.
