### ISSUE TITLE
[develop] Webpage - nav button doesnt work now

### ISSUE THREAD

**Issue by prajwalkman** [AHAAAAAAA/PokemonGo-Map#1310]
## Expected Behavior
Nav button used to work

## Current Behavior
Just navigates to `/#nav` and does nothing

**Comment by devinjparsons** [comment]
+1 Same

**Comment by rubenverhoef** [comment]
same here, after the merge with #1052

**Comment by JZ6** [comment]
reverted
check again please

**Comment by prajwalkman** [comment]
Yes, it works again now.

**Comment by parkershepherd** [comment]
Browser/os? I wasn't able to replicate the bug on Chrome/Firefox (OSX)

**Comment by prajwalkman** [comment]
I'm on chrome 51.0.2704.103 m
Windows 7 enterprise sp1

**Comment by rubenverhoef** [comment]
works again

**Comment by andrewda** [comment]
@parkershepherd I also was unable to replicate the bug using Chrome on OS X 10.11

**Comment by rubenverhoef** [comment]
i'm using chrome  51.0.2704.106  on windows 10

**Comment by devinjparsons** [comment]
@andrewda I haven't pulled reverted code yet, here is what the developer console says in my chrome instance on OSX 

Uncaught TypeError: Cannot read property 'SearchBox' of undefined  map.js:121

**Comment by parkershepherd** [comment]
Created a new fix branch, found a line that got deleted https://github.com/AHAAAAAAA/PokemonGo-Map/pull/1317

**Comment by parkershepherd** [comment]
@devinjparsons I've been seeing that one since https://github.com/AHAAAAAAA/PokemonGo-Map/pull/1225 adding `?libraries=placces` to the google script tag fixes _that_ error, but another error is caused because the search box element is still missing

**Comment by devinjparsons** [comment]
@parkershepherd good to know, thanks.  I saw that in the commit where the location searching was added, everything was there except for the searchbox element, so that makes sense
