### ISSUE TITLE
How change radius scanning map?

### ISSUE THREAD

**Issue by HacksLua** [AHAAAAAAA/PokemonGo-Map#1318]
Hello) I do not understand where and how to change the scan range) help pls)

**Comment by rbdeveloper** [comment]
As described in the [Wiki:](https://github.com/AHAAAAAAA/PokemonGo-Map/wiki)

> Additionally, you can change the 10 after -st to any number. This number indicates the number of steps away from your location it should look, higher numbers being farther.

**Comment by HacksLua** [comment]
Thanks you)
