### ISSUE TITLE
Running multiple instances gets database locked error

### ISSUE THREAD

**Issue by craigbaines** [AHAAAAAAA/PokemonGo-Map#1319]
I keep reading about being able to run a second instance with a second user, an it being able to populate one map.

When trying to run a second instance with -ns, i get the following error, this error also happened to me when i was trying out one of the multi thread pull requests a day or so ago. 

`"Exception in thread search_thread: Traceback (most recent call last): File "C:\Python27\lib\threading.py", line 530, in __bootstrap_inner self.run() File "C:\Python27\lib\threading.py", line 483, in run self.__target(*self.__args, **self.__kwargs) File "c:\Users\Craig\pokemon3\pogom\search.py", line 96, in search_loop search(args) File "c:\Users\Craig\pokemon3\pogom\search.py", line 79, in search parse_map(response_dict) File "c:\Users\Craig\pokemon3\pogom\models.py", line 134, in parse_map bulk_upsert(Pokemon, pokemons) File "c:\Users\Craig\pokemon3\pogom\models.py", line 151, in bulk_upsert InsertQuery(cls, rows=data.values()[i:min(i+step, num_rows)]).upsert().exec te() File "C:\Python27\lib\site-packages\peewee.py", line 3237, in execute return self._insert_with_loop() File "C:\Python27\lib\site-packages\peewee.py", line 3220, in _insert_with_lo p .upsert(self._upsert) File "C:\Python27\lib\site-packages\peewee.py", line 3244, in execute cursor = self._execute() File "C:\Python27\lib\site-packages\peewee.py", line 2656, in _execute return self.database.execute_sql(sql, params, self.require_commit) File "C:\Python27\lib\site-packages\peewee.py", line 3492, in execute_sql self.commit() File "C:\Python27\lib\site-packages\peewee.py", line 3316, in __exit__ reraise(new_type, new_type(*exc_args), traceback) File "C:\Python27\lib\site-packages\peewee.py", line 3485, in execute_sql cursor.execute(sql, params or ()) OperationalError: database is locked`

If anyone can shine some light on this and if its a problem my end give me a pointer in the right direction i'd appreciate it, or is it an issue with the server itself?

**Comment by docrockulus** [comment]
#744

**Comment by craigbaines** [comment]
Thanks!

I just used @TheReaperr fix by commenting in models.py:

#if pokestops:
# log.info("Upserting {} pokestops".format(len(pokestops)))
# bulk_upsert(Pokestop, pokestops)

Im doing it for central park so theres hundreds of pokestops an i dont care about them. Not only is it getting rid of the error, but im finding way way wayyyy more pokemon! Which was one of my other problems with this dev branch,

**Comment by denniskai1234** [comment]
Should be a MySQL Server way faster for this? I love the database, it allows you to connect multiply maps to one but when you run as you said some if them they just crash..

**Comment by craigbaines** [comment]
Ditching pokestops has got rid of my error, im now running three instances, ontop of that there are 10x's as many pokemon. 

As i said in #998

"Am i right in assuming that in earlier versions the parameter to turn on the pokestops when launching meant that when it was off, they never got ran (like my example now) where as now in the most current dev they seem to be running at all times, an i simply have the ability to view them or hide them?"

The fact central park, where im running the map, has hundreds of pokestops, my guess is thats whats causing the problems with so few pokemon / long loop times. Ditching them has made this 100x's better for me, just look:

![dddddddd](https://cloud.githubusercontent.com/assets/9383958/17069410/6601cd08-504e-11e6-9a5d-963543379071.png)

**Comment by Daegalus** [comment]
We need to add the No Pokestop, No Gym switches from master back in. I have maps up in SF and i need to turn those off by commenting out the code. (i just comment out the for loops processing the information), keeps the DB lighter, no processing as everything is 0 length ofr Gyms and Stops. and I get far more pokemon. a MySQL pull request seems to be up, and that might help.

**Comment by xerebz** [comment]
+1 for adding no pokestop, no gym

**Comment by jaretburkett** [comment]
This isnt the place, but I cant find it anywhere. How are you running multiple workers craigbaines?

**Comment by chuyskywalker** [comment]
This is basically the very definition of the limit sqlite has, see [their own FAQ on the matter](https://www.sqlite.org/faq.html#q5).

To genuinely solve this problem you need to run mysql. I'd _almost_ suggest that our "fix" for this is to, upon startup, detect if this instance is trying to open an already open sqlite db and, if so, bail out with a message like "Use MySQL if you want multiple searchers".

**Comment by AHAAAAAAA** [comment]
This is a known issue with sqlite, please switch to mysql to avoid it. Really nothing we can do here.

**Comment by Powerfists** [comment]
I feel like a noob. But can we get a guide on how to use mysql instead of sqlite?

**Comment by GenuineSounds** [comment]
If you don't want to switch over to MySQL just put the instance (or just the database) into a RAM drive or fast SSD. I even have my MySQL database in a RAM drive where changes to the disk are stored every couple seconds to HUGELY reduce IO writes on my SSD.
