### ISSUE TITLE
"High" Step Count

### ISSUE THREAD

**Issue by denniskai1234** [AHAAAAAAA/PokemonGo-Map#132]
If i raise the steps to 10 it shows up this:

http://pastebin.com/w650Lx7N

2-3 Versions ago it was working fine.

**Comment by mroge009** [comment]
This seems to be a new error. I have been getting this with a step count of 3.

**Comment by denniskai1234** [comment]
Did one step now, website is reachable but it dosent load any data to it.

Full output from the script: http://pastebin.com/mdpcuimG

**Comment by AHAAAAAAA** [comment]
I can't replicate. Can you pull and then share the command you use and and your system info (OS, Python version) alongside the error?

**Comment by denniskai1234** [comment]
Debian 7 amd64
python --version
Python 2.7.10
python example.py -u nope -p nope -l "51.9606649, 7.626134699999966" -st 1

http://pastebin.com/PXssMNQM output after running the command

**Comment by Octylpy** [comment]
You need to specify what account type you're using (Google or PTC). Add `-a ptc` or `-a google`

**Comment by denniskai1234** [comment]
Did that also, dosent change anything.

**Comment by AHAAAAAAA** [comment]
@Octylpy no need to specify actually, the default is ptc.

@denniskai1234 the order of the -a doesn't matter either.

**Comment by Lazarix** [comment]
Can you try using a road name and city name instead of lat long coords?

**Comment by Vivicus** [comment]
I actually get this same error.  

Operating environment:
Operating System: Windows 10 x64, Intel

Installed version of Python:
Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)] on win32

Command line looks as follows:

.\example.py -a ptc -u rutabagaman -p [snip] -l "[actual address of a house/apartment]" -st 10

The following occurs-

[-] register_background_thread called
[-] register_background_thread: not running inside Flask so not starting thread
 * Restarting with stat
[-] register_background_thread called
[-] register_background_thread: initial registration
 * Debugger is active!
[+] Locale is en
 * Debugger pin code: 333-147-751
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[!] Your given location: [Actual address]
[!] lat/long/alt: [Snipped]
[!] PTC login for: rutabagaman
[+] RPC Session Token: [Tokens are bad, m'kay]
[+] Received API endpoint: https://pgorelease.nianticlabs.com/plfe/178/rpc
[+] Login successful
[+] Username: RutabagaBro
[+] You started playing Pokemon Go on: 2016-07-17 14:15:48
[+] POKECOIN: 0
[+] STARDUST: 100
[-] looping: step 0 of 100

All 100 steps occur.

**Comment by JZ6** [comment]
fixed
