### ISSUE TITLE
[Bug] develop script show less pokemon than master script

### ISSUE THREAD

**Issue by ProtoxiDe22** [AHAAAAAAA/PokemonGo-Map#1320]
## Expected Behavior
The script should find all the pokemons in the scanned area

## Current Behavior
the script shows much less pokemon than the old script in master branch
i tried lowering the step distance as of issues #1105 #1090 #998 and others but i still see less pokemon on the new map than the old one (while running both script simultaneously)

## Your Environment
* Version used: commit 9ccfd39f0b68f6b0ab5eda0187807154eaac3aa1
* Environment name and version (e.g. Python 2.7): python 2.7
* Operating System and version (desktop or mobile): ubuntu 16.4 vps

**Comment by denniskai1234** [comment]
Same here.

**Comment by ProtoxiDe22** [comment]
@denniskai1234 have you also tried lowering step distance?

**Comment by denniskai1234** [comment]
Yep. It does show less and if i raise the steps it dosent show that much more.

**Comment by craigbaines** [comment]
check out my last comment here #998
