### ISSUE TITLE
Error when trying to use develop branch.

### ISSUE THREAD

**Issue by theblackmarmoset** [AHAAAAAAA/PokemonGo-Map#1321]
http://prntscr.com/bw94aj  I always get this error and can't find the fix for the life of me!  Please help.

**Comment by devinjparsons** [comment]
servers seem to be down right now or having issues, i'm seeing the same error where it was working previously with no code changes

**Comment by Hoborific** [comment]
Careful, you might get the thumb for telling people PTC is unstable/down right now.

**Comment by theblackmarmoset** [comment]
So there's no fix for it?

**Comment by Fredyy90** [comment]
got the same problem, sometime it trys to get an accesstoken an dies, and sometimes it dies earlier with the same error

**Comment by Rebosar** [comment]
If the servers are down, there isn't anything that can be done.

**Comment by theblackmarmoset** [comment]
the server works perfectly with the master branch though.

**Comment by Captainohair** [comment]
I had this. I removed the tab in the credentials file before the key in the JSON with three spaces and it worked just fine.

**Comment by Faustvii** [comment]
I wonder if we can add something to catch the error so it doesn't require a application reboot to resume functionality.

**Comment by theblackmarmoset** [comment]
In the develop branch is there a feature like in the master branch to filter out pokemon?

**Comment by Faustvii** [comment]
@theblackmarmoset There is a filter a UI filter in the develop branch and a notify feature for specific pokemons.

**Comment by devinjparsons** [comment]
This error is an error about loading the json from the server, not creds file.

**Comment by jangrewe** [comment]
This is presumably because PTC is down, and #1292 would at least keep it from dying completely.

**Comment by devinjparsons** [comment]
Line 54 of the auth_ptc.py file should have a try except around the json.loads.  then return false on login so it can retry.

**Comment by vinsilsim** [comment]
same here

**Comment by devinjparsons** [comment]
or #1292 works too :)

**Comment by theblackmarmoset** [comment]
Yeah it did return a failed login but after a few failed login attempts I got the same error about the JSON file thing.

**Comment by devinjparsons** [comment]
@theblackmarmoset yeah its failing in a place they didn't have a catch for it, so the app is crashing instead of retrying

**Comment by theblackmarmoset** [comment]
Ohh okay.  So once the servers are back up this error should go away?

**Comment by devinjparsons** [comment]
Should and it looks like a better fix for login issues is about to be commited #1292

**Comment by theblackmarmoset** [comment]
Awesome!  Thanks for the help. :)

**Comment by vinsilsim** [comment]
Servers are offline now?

**Comment by prajwalkman** [comment]
Only the PTC login. I think the google logins still work.

**Comment by vinsilsim** [comment]
@prajwalkman how can I enable map click? you know?

**Comment by devinjparsons** [comment]
Just switched my 4 instances to all use google logins, no more dealing with PTC issues (at least for login)

**Comment by MonkeyLeeT** [comment]
#1292 is merged, try it out boys and girls.

**Comment by kuldeeppatel123** [comment]
@devinjparsons  can i use any gmail address to login ?
or need to register some where ?

**Comment by Fredyy90** [comment]
You can use a fresh Gmail account and just login, it works just switched
from ptc to Google

kuldeeppatel123 <notifications@github.com> schrieb am Sa., 23. Juli 2016,
00:24:
