### ISSUE TITLE
GETTING THIS ISSUE, PLEASE RESOLVE MATE 

### ISSUE THREAD

**Issue by Akshat1295** [AHAAAAAAA/PokemonGo-Map#1326]
retrying_get_profile: get_profile returned no-len payload, retrying
retrying_get_profile: get_profile returned no-len payload, retrying

**Comment by Rohmin** [comment]
PTC login? probably server down

**Comment by Akshat1295** [comment]
though if I put up any other location other then mine (region), the servers work perfectly well

I am using this syntax

example.py -u -p -st 15 -ar 10 -l "Gumanpura, Rajasthan, India"

**Comment by cab13140** [comment]
PTC is down actually, try with google auth mate !

**Comment by rbdeveloper** [comment]
Also, do you use master branch? Try developer branch, lots of bugfixes already merged.

**Comment by FrostTheFox** [comment]
Support for master branch has been dropped. For support, please use the develop branch.
