### ISSUE TITLE
No "-ar" feature in develop branch?

### ISSUE THREAD

**Issue by theblackmarmoset** [AHAAAAAAA/PokemonGo-Map#1331]
I've tried using -ar 5 in the develop branch but it just comes up with this error.   http://prntscr.com/bw9r03

**Comment by Frozire** [comment]
The auto refresh functionality should no longer be needed as pokemons are added directly to the map with no need for refreshing.

**Comment by theblackmarmoset** [comment]
Oh thanks!  Honestly helped me a lot there and saved my sanity. :)
