### ISSUE TITLE
Biggest pokemans I've ever seen.

### ISSUE THREAD

**Issue by medghaim** [AHAAAAAAA/PokemonGo-Map#134]
![This happened](http://i.imgur.com/9tlnwPM.png)

It looks like it's grabbing the new sprite for nidoran/nidorino, as opposed to the older 2d one. It's also much bigger.

**Comment by DerScreever** [comment]
Confirm have the same problem

**Comment by nakami** [comment]
did you wipe your cache?

**Comment by olipayne** [comment]
it's definitely a cache issue, old icons vs new

**Comment by medghaim** [comment]
I did not. Will test when I get back

**Comment by medghaim** [comment]
Confirmed to be a cache thing. Oops :(
