### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'settings' - develop branch

### ISSUE THREAD

**Issue by mewm** [AHAAAAAAA/PokemonGo-Map#1343]
## Expected Behavior
Python script should execute

## Current Behavior
Running ```runserver.py```, exits with ```AttributeError: 'Namespace' object has no attribute 'settings'```

## Steps to Reproduce (for bugs)
```
git clone https://github.com/AHAAAAAAA/PokemonGo-Map.git
cd PokemonGo-Map
pip install -r requirements.txt
python runserver.py -a ptc -u XXX -p XXX -l "x,y" -st 8
Traceback (most recent call last):
  File "runserver.py", line 13, in <module>
    from pogom.app import Pogom
  File "/var/www/PokemonGo-Map/pogom/app.py", line 11, in <module>
    from .models import Pokemon, Gym, Pokestop
  File "/var/www/PokemonGo-Map/pogom/models.py", line 12, in <module>
    from .customLog import printPokemon
  File "/var/www/PokemonGo-Map/pogom/customLog.py", line 5, in <module>
    args = get_args()
  File "/var/www/PokemonGo-Map/pogom/utils.py", line 58, in get_args
    if (args.settings) :
AttributeError: 'Namespace' object has no attribute 'settings'
```

## Your Environment
I've tested this on ubuntu trusty 64bit with Python 2.7.6 and osx el capitan with Python 2.7.10

----
The command I run might not be easy to distill from the above, but it's ```python runserver.py -a ptc -u user -p pass -l "x,y" -st 8```

**Comment by falkben** [comment]
I am also getting this.  

Just wanted to add in case you hadn't done this, that you need to set the google maps credentials (now under config/credentials.json).

**Comment by mikevelasquez02** [comment]
Same for me. The command I use to run is
python runserver.py -a ptc -u "uname" -p "pass" -l "x,y" -st 7 -H "IP" -P "port"

**Comment by neruve** [comment]
I am also getting this. I use the same as mikeelasquez02

**Comment by cookandy** [comment]
I'm also getting it with this command:

`python runserver.py -a "google" -u "xxx@gmail.com" -p "xxx" -l "xxx" -st 20 -H 0.0.0.0 -P 5000 -k xxx`

**Comment by FrostTheFox** [comment]
We're aware of this and are working to fix it.

**Comment by sandsaber** [comment]
Thank you

**Comment by mikevelasquez02** [comment]
I got it to work... the file utils.py in the folder pogom, line 58, I commented the whole if statement

#    if (args.settings) :
#        args = parse_config(args)
#    elif args.password is None:
#        args.password = getpass.getpass()

**Comment by mewm** [comment]
@falkben yes, I've made that change already, but thank you anyways.
Someone has committed an empty ```credentials.json``` (instead of having it git ignored) so one constantly have to stash the credentials before every pull...

**Comment by Heavywavez** [comment]
is this fixed? i did what @mikevelasquez02  said and its worst... hahaha

**Comment by mikevelasquez02** [comment]
@Heavywavez Here is what I have.
![capture](https://cloud.githubusercontent.com/assets/8298055/17071423/1f4ac9f4-5027-11e6-933b-f3d4fd297054.JPG)

**Comment by Heavywavez** [comment]
@mikevelasquez02  that's what i did man and got another type of errors. 
![screen shot 2016-07-22 at 4 22 35 pm](https://cloud.githubusercontent.com/assets/8387820/17071671/99953220-5028-11e6-8749-57ebe828f1b8.png)

**Comment by mikevelasquez02** [comment]
@Heavywavez they seem to be error from Python itself, I'm not sure. The error of the args.settings was already solved in the develop branch. Perhaps if you pull the updated files from it, your error could be solved. Also, did you run the "pip install -r requirements.txt" command?

**Comment by Heavywavez** [comment]
@mikevelasquez02  actually after i run the pip -install --upgrade requirements thats start happen...  .-.

**Comment by mikevelasquez02** [comment]
@Heavywavez Which OS are you running? I am on Ubuntu 14.04 LTS

Try making a backup of the folder /usr/local/lib/python2.7/dist-packages/ 
Then, delete the folder (Keep the backup securely stored)
Reinstall "pip" (You can see the guide in the Wiki)
Then, try running pip install -r requirements.txt (I had to do everything as sudo... even this command)

I tried to replicate your problem, but I could not. I did the above steps to reset and reinstall the requirements.

**Comment by mewm** [comment]
I'm not sure which commit solved this, but after a fresh pull this morning, this issue has been fixed, thus closing this thread! The activity on this repo is amazing.
