### ISSUE TITLE
New DEV update how to START?

### ISSUE THREAD

**Issue by SkyBadPT** [AHAAAAAAA/PokemonGo-Map#1344]
with the new update using the config how can i start the server?

**Comment by rmonk** [comment]
Use runserver.py instead of example.py, but most of the options are the same.

**Comment by SkyBadPT** [comment]
@rmonk im using the runeserver.py but i need to put the user/password/location? becasue i set them in config.ini if i need to put them when i start the server what is the point of config.ini?

**Comment by npeep** [comment]
They just pushed a new commit, now there is a -se switch to use the settings.

**Comment by npeep** [comment]
Buuuuttttt running "runserver.py -se" doesn't do anything. :|  Still searching!

**Comment by SkyBadPT** [comment]
@npeep  I think they will revert the last commits because it's fuck'd up :/

**Comment by mattb91** [comment]
You have to set the gmaps api key in the credentials.json file in the config folder also I assume that running with -se will only work if you have put your settings in the settings file in the config folder
