### ISSUE TITLE
Suggestion on adding something like PRIM algo to walk on map

### ISSUE THREAD

**Issue by Bzzz666** [AHAAAAAAA/PokemonGo-Map#135]
https://pypi.python.org/pypi/PRIM/0.4

**Comment by medghaim** [comment]
I think that might be a little past the scope of the project. Depends on where AHAAAA wants to take it.

**Comment by Bzzz666** [comment]
I think it will be useful because of lowering queries to pokego servers and faster "true" movin\searching

**Comment by AHAAAAAAA** [comment]
Looks interesting, lets sit on this for a bit.

**Comment by DerScreever** [comment]
Im sorry, but we dropped the support for the master branch (example.py). 
This branch is deprecated.  
The new branch contains a much cleaner structure so pls report only issues related to the develop branch. 

Your development team
