### ISSUE TITLE
I get Importerror: no module named flask every time i try to do this cd C:/Pokemongo pip install -r requirements.txt   please help

### ISSUE THREAD

**Issue by toofy7** [AHAAAAAAA/PokemonGo-Map#1353]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by leqwasd** [comment]
Run this:
`pip install setuptools==21.2.1`
and then repeat what you did.

**Comment by toofy7** [comment]
thanks @leqwasd
