### ISSUE TITLE
Any way to get rid of the marker thing?

### ISSUE THREAD

**Issue by theblackmarmoset** [AHAAAAAAA/PokemonGo-Map#1354]
It's hard to describe but this maker just covered a pikachu and I kinda want to get rid of it.  Ik it's kinda picky but I think it would make the map that much better. :)  [Here is the marker I'm talking about: http://prntscr.com/bwax49]

**Comment by Truesh00ter** [comment]
Try out commenting from line 811 until the closing square bracket:

    pokeMarkers = [{
        'icon': icons.dots.red,
        'lat': origin_lat,
        'lng': origin_lon,
        'infobox': "Start position",
        'type': 'custom',
        'key': 'start-position',
        'disappear_time': -1
    }]

**Comment by theblackmarmoset** [comment]
What do you mean try commenting?  I'm not good with coding at all so I'd need some type of step by step tutorial. lol

**Comment by theblackmarmoset** [comment]
I'm also using the develop branch so the lines dont go to 811 in runserver.py

**Comment by Truesh00ter** [comment]
http://lmgtfy.com/?q=out+commenting+python

Sorry to be a dick but a little pro-activeness goes a long way.

Use the search function of your favourite texteditor to find the lines.

Oh and it's a develop branch for a reason, no one is brave enough to give support to a dev branch.

**Comment by devinjparsons** [comment]
@Truesh00ter to be honest you could have at least included the file you were referring to when you said on line 811.

**Comment by theblackmarmoset** [comment]
Oh, so in the dev branch you aren't able to get rid of the marker thing?

**Comment by Valareos** [comment]
Actually the Dev branch is the only one accepting trouble tickets. the master branch is depreciated.

and @Truesh00ter , I am rather good with coding myself, and I cant find the lines you referencing at all. it WOULD help if you stated what file to edit

**Comment by devinjparsons** [comment]
In the develop branch its now in the PokemonGo-Map/static/map.js file on line 107

you can comment it out by replacing the below code with this
`marker = new google.maps.Marker({
        position: {
            lat: center_lat,
            lng: center_lng
        },
        map: map,
        animation: google.maps.Animation.DROP
    });`

`marker = new google.maps.Marker({
    //    position: {
    //        lat: center_lat,
    //        lng: center_lng
    //    },
    //    map: map,
    //    animation: google.maps.Animation.DROP
    //});`

**Comment by Valareos** [comment]
and @theblackmarmoset  to comment out a line you put a # in front of it.

Some sort of coding here
#this coding gets ignored

**Comment by devinjparsons** [comment]
since this is a js file you will be editing make sure to use // for comments

**Comment by theblackmarmoset** [comment]
@Valareos  @devinjparsons  Thank you both for helping me out but when I open the map.js file there are no line numbers.  Am I opening it with the wrong program or something?

**Comment by devinjparsons** [comment]
get notepad++ and open it with that will have line numbers on the margin https://notepad-plus-plus.org/

**Comment by theblackmarmoset** [comment]
OH! that works a lot better!  thank you! @devinjparsons

**Comment by AndrewYoungs** [comment]
Err not sure if this refers to the location marker or the step circle markers but is there a way to get rid of the step circle markers that appear in the post-multithread merge?
