### ISSUE TITLE
no pockemons on mobile map

### ISSUE THREAD

**Issue by Dimatert9** [AHAAAAAAA/PokemonGo-Map#1358]
no pokemons on mobile map.  Develop branch.

![](https://pp.vk.me/c631930/v631930910/3f636/QNgETIVhlH8.jpg)

![](https://pp.vk.me/c637520/v637520816/fb/gOb4cky5mSo.jpg)

**Comment by devinjparsons** [comment]
Have you checked the logs? Does it say anything about authentication issues? Servers have been up and down lately.

**Comment by Dimatert9** [comment]
where i can see logs?

**Comment by Dimatert9** [comment]
in conosole all good.
![2016-07-22 21 40 28](https://cloud.githubusercontent.com/assets/8667294/17072067/33f15732-506e-11e6-80b5-0dc9fc128c76.png)

**Comment by devinjparsons** [comment]
under the filter nav button you didn't accidentally uncheck pokemon did you?  thats the only reason i would think you wouldn't be seeing them on the mobile but can on desktop

**Comment by Dimatert9** [comment]
http://195.88.208.144:5000

In filter all on. You can check this.

**Comment by devinjparsons** [comment]
Hmm, i see some pokemon but not as much as you would expect.  what is your step value set at? how long does it take to go from 0% to 100% (should be able to determine this by looking at console and the timestamp for each line.

**Comment by Dimatert9** [comment]
![screenshot_20160723-010134](https://cloud.githubusercontent.com/assets/8667294/17072465/20a4d728-5071-11e6-9e0b-d3c958e19fa9.png)
![screenshot_20160723-010123](https://cloud.githubusercontent.com/assets/8667294/17072466/20a665de-5071-11e6-9f31-6e7338f16b24.png)
![screenshot_20160723-010104](https://cloud.githubusercontent.com/assets/8667294/17072467/20aafa5e-5071-11e6-943b-914d57cb94ab.png)

**Comment by devinjparsons** [comment]
Oh yeah I just looked at your console, you are using way too big of step value (-st) should only be at most 10 as it will finish the loop before the first start expiring.  Mine with a value of 7 finishes in 2 min and most pokemon expire in 10-15 min.  with a value of 7 i have 49 steps i go through, you have 4000

**Comment by Dimatert9** [comment]
Thanks. Change st to 10 and i can see Pokemons on map.
