### ISSUE TITLE
Suggestion: poke location coordinate

### ISSUE THREAD

**Issue by gian310583** [AHAAAAAAA/PokemonGo-Map#136]
Suggest on adding poke location coordinate where users can copy and paste to google map.

**Comment by hhu94** [comment]
Related to #173. Should we display the coordinates as well, or is a link to Google Maps fine?

**Comment by gian310583** [comment]
I think link to google map is great cause users can then scan a certain area, get a google coordinate, and start walking there.

**Comment by JZ6** [comment]
no need
