### ISSUE TITLE
Map stops showing new Pokemon after a while

### ISSUE THREAD

**Issue by guest136** [AHAAAAAAA/PokemonGo-Map#1363]
UPDATE:  

Problem with masterbranch solved by using develope branch.

I have solved the problem with the multiple Locations on one map. I had to open the multiple cmds from one directory.

**But another Problem appeared after some minutes the second command/location starts to get errors.**

2016-07-23 04:04:57,976 [auth_google] [ INFO] Google login for: AAAAAA@gma il.com
2016-07-23 04:04:58,150 [auth_google] [ INFO] Google Login failed.
2016-07-23 04:04:58,150 [ search] [ INFO] Failed to login to Pokemon Go. T rying again.
2016-07-23 04:04:59,154 [auth_google] [ INFO] Google login for: AAAAAA@gma il.com
2016-07-23 04:04:59,326 [auth_google] [ INFO] Google Login failed.
2016-07-23 04:04:59,326 [ search] [ INFO] Failed to login to Pokemon Go. T rying again.

**Comment by ericpadilla** [comment]
use dev please. no more support for master

**Comment by guest136** [comment]
Ok, I have installed the dev branch, could u tell me how to run multiple instances on one map and how to add a sound alarm when a pokemon is found?

**Comment by devinjparsons** [comment]
Run the same command multiple times, probably in multiple shell/cmd windows, but change the port for each one, if you don't need to see the maps for the other scanners, add -ns to the arguments for the instances after the first one.  There are chrome alerts, i have my sound off so not sure if it plays a sound or not, i think it does.  So in the filter nav bar, add the pokemon you want to be alerted on and make sure you have allowed notifications for the site.

**Comment by guest136** [comment]
I copy pasted the dev branch folder so that they have different directions and opened "GIT Bash Here" in every folder i think its the same like cmd.

On the map http://127.0.0.1:5000/ it only shows the pokemon from the first folder and location but not from the second folders with the -ns command location.

These are my commands in the console:

Armenia@Aram MINGW64 ~/Downloads/PokemonGo-Map-develop (3)/PokemonGo-Map-develop - Kopie
$ python runserver.py -a google -u ...@gmail.com -p ... -l "40.717022 -74.006008" -st 10 -sd 5 -P 5000


Armenia@Aram MINGW64 ~/Downloads/PokemonGo-Map-develop (ss3)/PokemonGo-Map-develop
$ python runserver.py -a google -u ....@gmail.com -p ... -l "40.742580 -73.997011" -st 10 -sd 5 -P 5010 -ns

**Comment by danielbennifer** [comment]
@guest136 Are you running each additional instance / command with a unique port? And, are those ports opened up for use?
