### ISSUE TITLE
Credentials.example.json File Needs Changed

### ISSUE THREAD

**Issue by HisAirness** [AHAAAAAAA/PokemonGo-Map#1364]
When creating your personal API key, particularly switching from Master to Develop you need to copy and paste your new API key into the "credentials.json" file. Then run the script on terminal and it should work. 

The problem is that when you download the most current Develop version there is no .json file named credentials.json 

There is only the credentials.example.json file.

I haven't seen it posted anywhere but the current credentials.example.json file is the same exact file that you need to paste your API in. If you just paste your API in it and don't rename it the script will NOT work you will get an error.

RENAME THE FILE to **credentials.json** this will allow the script to run successfully.

**_PLEASE update the Host Files with the proper name so we don't have to go in and change it._**

**Comment by Bakies** [comment]
This is intended

**Comment by hhu94** [comment]
It's named credentials.example.json because credentials.json is in .gitignore. This is done in order to avoid users commiting their API key to their forks.

**Comment by ShawnHardwick** [comment]
GMAPS_KEY is also populated if you ruin the easy setup. Like said before, this is all intended, but could be communicated better.

**Comment by knobunc** [comment]
Someone just did the rename on the devel branch... that will make git pulls harder for people unfamiliar with git because they will have a local change.  Hence why the example file was there before.

**Comment by Zach1993** [comment]
It is also now in the Config folder. Is the easy install code updated to handle the file change?

**Comment by rfiorenzano** [comment]
I've just moved from the Master to Develop branch as well and do not seem to be having any luck with updating the GMaps API Key that I created. I had this working on the Master branch and duplicated the credentials.json from the Master branch to be used with Develop with no luck.

I also used the credentials.example.json, renamed it to credentials.json, and placed my GMaps API key there to no avail.

Additionally, I've tried to use the "-k" switch to have the GMaps API key provided right off the command and had no success there either.

Please advise - and thanks in advance.

**Comment by FrostTheFox** [comment]
credentials.json is rip, not relevant anymore.
