### ISSUE TITLE
110% Scan Completion

### ISSUE THREAD

**Issue by KazWolfe** [AHAAAAAAA/PokemonGo-Map#1370]
## Expected Behavior

Scan percentage should be 0% to 100%, at which point it restarts.

## Current Behavior

Console displays:

```
2016-07-22 15:20:52,878 [     search] [   INFO] Scanning step 395 of 631.
2016-07-22 15:20:53,020 [     models] [   INFO] Upserting 1 pokemon
2016-07-22 15:20:53,026 [     models] [   INFO] Upserting 10 pokestops
2016-07-22 15:20:53,032 [     models] [   INFO] Upserting 5 gyms
2016-07-22 15:20:53,038 [     search] [   INFO] Completed 175.56% of scan.
```

## Steps to Reproduce (for bugs)

1. Start a scan
2. View console

## Context

Visual bug, low importance.

## Your Environment

* Version used: Commit fe39d489a381046f70794430ac2d77e70a54ff21
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): Ubuntu Server 14.04 LTS

**Comment by devinjparsons** [comment]
I'm guessing the code was never intended to have such a high step value that you are setting.  631 steps is a lot of steps, if the scan isn't finished and restarting within 10 min then you are missing out on pokemon because of their expiry time.  How long was this current scan running for?

**Comment by KazWolfe** [comment]
One of these scans finishes in about 8 or 9 minutes.

**Comment by devinjparsons** [comment]
Ok, so you wont be missing any pokemon, but i bet they have the top value being 300 or so.  Is their a reason for your high step value? Or was it just testing?

**Comment by KazWolfe** [comment]
It covers my entire town, so that's the reasoning

**Comment by devinjparsons** [comment]
Ah ok, If i was wanting that coverage i would probably run 4 or 5 instances in parallel to be able to lower the step value and get the coverage you want.  But its up to you, the 4 or 5 instances would allow for more precise timing throughout your town.  You can run just one instance as a web interface where the others being run with the -ns tag will just be scanners.

**Comment by KazWolfe** [comment]
I was considering that, but there's no reliable way to define sources yet (#1368). Therefore I can't really do much with multiple scanners.

**Comment by hazanjon** [comment]
The search pattern has just been updated, it seems the percentage is still being calculated based on the old pattern (square)

The fix:

`log.info('Completed {:5.2f}% of scan.'.format(float(step) / num_steps**2*100))`
to:
`log.info('Completed {:5.2f}% of scan.'.format(float(step) / total_steps*100))`

**Comment by devinjparsons** [comment]
@KazWolfe For your use case you would want it in one database, and then one map, unless you were planning on sharing this with other people and wanted your data to be segregated from the others.

**Comment by devinjparsons** [comment]
I run 5 scanners right now and they get all the data and are viewable on one map.

**Comment by KazWolfe** [comment]
@devinjparsons Yeah, but running five on one server makes no sense from a load-balancing standpoint. I can run multiple on one box, but that won't scale reliably.

**Comment by devinjparsons** [comment]
True, but with this problem you are running into the pokemon expiry time, so your scan leaves very little time to actually make it to the outer rings of your scan.  My reasoning wasn't for scalability or load balancing, it was based on i know how long the scans take and how long the pokemon exist. So since they will disappear at a set time, to get the most data i needed to run it all in parallel

**Comment by theblackmarmoset** [comment]
I agree with @devinjparsons if that means anything.  I know nothing about programming at all but I like to think my opinion still matters. lol

**Comment by shivampaw** [comment]
A pull request has been submitted for this. Wait for it to be committed of if it is bugging you, you can manually change the file: https://github.com/AHAAAAAAA/PokemonGo-Map/pull/1374/files

**Comment by wcastello** [comment]
Fixed.
