### ISSUE TITLE
Authentication loop error after a certain amount of time.

### ISSUE THREAD

**Issue by SimonTellsAll** [AHAAAAAAA/PokemonGo-Map#1371]
## Expected Behavior
After several full scans the app should continue through iterations, but instead stalls and fails to login.

## Current Behavior

After a certain amount of time (not sure how long) the app gives the following error repeated several times. I have to restart the dyno manually and it logs in perfectly fine. Server status was perfectly fine, and worked as soon as the dyno was restarted.

```
2016-07-22T22:18:41.957550+00:00 app[web.1]: 2016-07-22 22:18:41,957 [auth_google] [   INFO] Google login for: xxx
2016-07-22T22:18:42.401440+00:00 app[web.1]: 2016-07-22 22:18:42,401 [auth_google] [   INFO] Google Login successful.
2016-07-22T22:18:42.551443+00:00 app[web.1]: 2016-07-22 22:18:42,551 [     pgoapi] [  ERROR] Login failed - unexpected server response!

```

## Steps to Reproduce (for bugs)

1. Deploy on Heroku
2. Have a -sd 20 extra var
3. Wait until it stalls

## Context
Ideally if it fails more than say 5 times, It should take a 30second break and restart. Something that would hopefully fix the issue of it stalling.

## Your Environment

* Version used: Heroku - Dev branch

**Comment by ApocUSB190** [comment]
I just fixed this (https://github.com/AHAAAAAAA/PokemonGo-Map/pull/1367), see the changes made in this pull request if you want to do it now.

**Comment by Krys1s** [comment]
Duplicate of #1315 

I believe #1367  supposed to fix?

**Comment by Krys1s** [comment]
Just applied the fix - see what happens in 30 mins =)

**Comment by ApocUSB190** [comment]
@Krys1s thanks, please comment on the pull request if it works so the devs can see.

**Comment by SimonTellsAll** [comment]
Thanks working for me
