### ISSUE TITLE
Can't start server but i have all the info in config.ini

### ISSUE THREAD

**Issue by SkyBadPT** [AHAAAAAAA/PokemonGo-Map#1375]
Can't start the server im getting this error and the credentials and config.ini are correct and with the info on it
```
python runserver.py
usage: runserver.py [-h] [-se] [-a AUTH_SERVICE] -u USERNAME [-p PASSWORD] -l
                    LOCATION -st STEP_LIMIT [-sd SCAN_DELAY] [-dc] [-H HOST]
                    [-P PORT] [-L LOCALE] [-c] [-d] [-m] [-ns] [-k GMAPS_KEY]
                    [-C] [-D DB]
runserver.py: error: argument -u/--username is required

```

**Comment by mark-rodgers** [comment]
As far as I can tell the config.ini is not really implemented yet. You still need to pass all the parameters in when calling the script

`python runserver.py -H 0.0.0.0 -u ******** -p ******** -l "type your location here"`

**Comment by devinjparsons** [comment]
try python runserver.py -se

**Comment by Zach1993** [comment]
Its true, it was implemented but it messed things up. Go back to the traditional way.

**Comment by Xoonio** [comment]
actually it dosn´t work to put it in the config.ini. you have to use the "old way"

**Comment by SkyBadPT** [comment]
@devinjparsons with -se give me the same error.

@Zach1993 , @Xoonio Yes i will use the old way, thanks.
