### ISSUE TITLE
Suggestion: add ability to use proxy for request

### ISSUE THREAD

**Issue by epanchee** [AHAAAAAAA/PokemonGo-Map#138]
Due to the unrealesed state of PokemonGo in many countries the developers sometimes closes ptc for request from such countries. It would be great to add option for proxying requests.

**Comment by phlash** [comment]
Already supported in the requests module used by the code, set these environment variables:
HTTP_PROXY=<proxy URL>
HTTPS_PROXY=<proxy URL>
where <proxy URL> is something like: http://myfavorite.proxy:port

Docs here: http://docs.python-requests.org/en/master/user/advanced/#proxies

**Comment by epanchee** [comment]
I've found that this feature would be usefull because Google maps set view limit for ip (as I understood). 
I should be something like example.py ... -pr proxy_list, where proxy_list is file which contains one proxy:port per line.

@phlash unfortunately, your approach didnt work for me. Tried like this: export HTTP_PROXY=52.36.84.86:8083

**Comment by DerScreever** [comment]
Im sorry, but we dropped the support for the master branch (example.py). 
This branch is deprecated.  
The new branch contains a much cleaner structure so pls report only issues related to the develop branch. 

Your development team
