### ISSUE TITLE
Gitflow / Work in Progress

### ISSUE THREAD

**Issue by Xoonio** [AHAAAAAAA/PokemonGo-Map#1380]
No bug, just n idea.

Many people use your scripts and your range is awesom.
in fact that mean, you have to look for all the problems. Many issues are opened with some ... queststions (couse they don´t understand what you are doing).
Maybe it will be better if you try a "gitflow" with a "masterbruch", a dev brunch and feature branches.
everytime you chance the startparameter or something the user have to do a chance, you can do a new version tag in "master".
think that will slow down the issuerate and give the project an professionel face.

regards

Xoonio

**Comment by Xoonio** [comment]
if you say that isn´t a "mastered" version, you can put a "RC"-"Test"-brunch or something like that between the dev and the Masterbranch.

**Comment by FrostTheFox** [comment]
Somewhat implemented.
