### ISSUE TITLE
https://github.com/AHAAAAAAA/PokemonGo-Map.wiki.git

### ISSUE THREAD

**Issue by mills56** [AHAAAAAAA/PokemonGo-Map#1382]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by shivampaw** [comment]
Nice to see there's no problem :)

**Comment by theblackmarmoset** [comment]
LOL
