### ISSUE TITLE
Reports of pokemon showing up late on map

### ISSUE THREAD

**Issue by Valareos** [AHAAAAAAA/PokemonGo-Map#1385]
I am getting reports from users on my map  that the pokemon are showing up about 10-15 min later on the map than they are in pokemon go.  I have no way of testing it. Has anyone else experienced similar issues?

**Comment by shivampaw** [comment]
I've experienced pokemon showing on Pokemon go but not the map. However I do know that the searching algorithms are being looked into for better accuracy.

**Comment by Valareos** [comment]
Ok, Issue I have found is how the client side map determines what pokemon are visible. It uses the client clock, not the server clock.

This means that if a person has their computer clock set too fast, pokemon wont show up that are actually still there. (one example is someone who has it set 10 min ahead was seeing very few pokemon)

Set too slow, and they may see pokemon that actually are no longer there.

It appears then the accuracy of the clients clock affects accuracy of pokemon on map.  This MIGHT be where some reports of missing pokemon are actually coming from.

The program really should rely on the server clock, that way it cuts out the issue of everyones clock being slightly different

**Comment by Rhynocerous** [comment]
Having your clock set 10 minutes fast seems bizarre. I was going to guess you just had a wide search area and it was taking ~10 minutes to get through the whole thing.

**Comment by Valareos** [comment]
Not to bizzare.  I regularly have the clocks in my house set 10 min fast, because it means if I need to leave the house by 1 to get somewhere by 2, Im actually leaving at 12:50 though clock says 1, making sure I am 10 min early to wherever I need to go.  Someone setting a tablet or a phone similarly is not unheard of

**Comment by shivampaw** [comment]
Most people normally have their clocks auto set tbh. What step value do you use?

**Comment by Valareos** [comment]
My step value is 10.

**Comment by Yivoe** [comment]
I'll just add, I was using a version that was a couple days old, scanned the area around my apartment, then I updated to the newest version up right now and the scan only showed about half the pokemon that I was getting before.  I've been looking at the map a lot over the last couple days and I can definitely tell it is missing some pokemon on the scans.

**Comment by lowkey2446** [comment]
yup, the new version is missing pokemon. has nothing to do with what time you have set on your device.

**Comment by Valareos** [comment]
Please note this issue is not about missing pokemon but a time delay in pokemon showing up, which IS based on if a client's time is not in sync with server time

**Comment by shivampaw** [comment]
For the missing Pokemon one add  "-t 1" to the command for running it

**Comment by Valareos** [comment]
reports of this issue has gone away since the thread fix. Closing out issue
