### ISSUE TITLE
Login with Google Account

### ISSUE THREAD

**Issue by vortex9** [AHAAAAAAA/PokemonGo-Map#139]
Hi
Try to login with google account (with 2FA)

``
C:\Python27>python.exe c:\Python27\PokemonGo-Map-master\example.py -a google -u
mymail -p mypassformail -l "location" -st 10
``

But have this `[-] Wrong username/password`
Debugger pin code: 120-681-369

Any suggestions?

**Comment by FRedEnergy** [comment]
Make sure you're entering google login, the part before `@gmail.com`.

**Comment by DerScreever** [comment]
The google login work for me

**Comment by Temetz** [comment]
Working here as well. Would you mind trying with:
``` -a google -u "youremail@gmail.com" -p "youpassword"```

youremail@gmail.com may also be something else than @gmail.com, so try entering your full google account username. So for example "youremail@yahoo.com" or whoever your provider is.

**Comment by vortex9** [comment]
Try full full variant with @ gmail, try short  - without
Try put username and password in quotes, try without quotes

not working

Try another google account without 2FA - work....

**Comment by vortex9** [comment]
Enable on second account 2FA and get same error.
Your script don't work with 2FA

**Comment by cstewart90** [comment]
@vortex9 Go to https://security.google.com/settings/security/apppasswords and generate an app password and use that password instead of your google account password. Also you should probably rename the issue to mention two factory/2fa since I think @DerScreever and others seems to have missed that part..

**Comment by vortex9** [comment]
@cstewart90 awesome. apppasswords work!
