### ISSUE TITLE
Scan percentage goes over 100% and Delay between scan not working.

### ISSUE THREAD

**Issue by Mr-Protocol** [AHAAAAAAA/PokemonGo-Map#1393]
## Expected Behavior
Accurate scanning with steps saying 100%
After 100% or step X of X is completed, scan delay.

## Current Behavior
Scanning percentage goes over 100% and notifies of the wait for next scan but instantly scans again.
![bug](https://cloud.githubusercontent.com/assets/1323342/17073969/e9435a84-5043-11e6-9ffe-a95b2eb0bdea.JPG)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: Commit on Jul 22 23:55:29
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): Ubuntu Server 16.04.1 LTS

**Comment by mhelmetag** [comment]
Seeing this as well.

**Comment by shivampaw** [comment]
Pull request was submitted. Keep pulling the git as it will be committed soon.

**Comment by mhelmetag** [comment]
Fixed by https://github.com/AHAAAAAAA/PokemonGo-Map/pull/1374

**Comment by Mr-Protocol** [comment]
I'm on #1391 and still have this issue.

**Comment by Krys1s** [comment]
hasn't been committed yet

**Comment by Mr-Protocol** [comment]
Unless i'm reading 1374 wrong, it was committed 2 hours ago.
