### ISSUE TITLE
Domain connection issues.

### ISSUE THREAD

**Issue by joveice** [AHAAAAAAA/PokemonGo-Map#1399]
Not sure if this is this programs issue or my server.
Using linux ubuntu server 14.
Trying to have it behind a domain, but each time I connect in the browser to the webadress it just sends me to my webpage, not the pokemon map.
connecting localy works as it should, and exsternaly does too as long as you use ip:port and not test.mydomain.com that points to myip with port 5000

**Comment by mattb91** [comment]
If you can connect via ip:port then it's not a PokemonGo-Map issue. Just a shot in the dark but it sounds an issue with your web server config.

**Comment by joveice** [comment]
Do you have any idea on how to fix it, or do I need to wait for someone that knows more about it?

**Comment by mattb91** [comment]
Maybe this can help http://serverfault.com/questions/195611/how-do-i-redirect-subdomains-to-a-different-port-on-the-same-server

**Comment by bobys16** [comment]
i know to fix this .
just add -H 0.0.0.0 on run commands that will fix that /
i that problem tomorrow and fix by typing that XD ..

**Comment by joveice** [comment]
@bobys16 It's not that easy. I can access it so that's not the problem. I just have a website interfearing with domain setup.

**Comment by joveice** [comment]
@mattb91 this sorta helped, new issue tho I can connect to test.mydomain.com and get redirected to mydomain.com:5000 but that does not respond what do I have to do here?

**Comment by chuyskywalker** [comment]
This is an issue unique to your server. Without knowing how your server, domain, applications, etc are all setup, no one is really going to be able to realistically be able to help.

The map app will listen on an ip:port combo -- if you've got some special setup that prevents direct access as such, you're going to have to work out why it's not working. Check log files, and if that fails, turn up debug levels of notices and check them again to see how your traffic is being routed.

Good luck.
