### ISSUE TITLE
Auth with Google account?

### ISSUE THREAD

**Issue by me-12** [AHAAAAAAA/PokemonGo-Map#14]
Is it possible to implement a authentication via google account? Because right now it looks like the Pokemon Go login server are very unstable. And I am not able to login at all.

**Comment by mpah** [comment]
I've started some google auth work which gets the login to work, however the map scanning part doesn't work (it just skips through the completed % very quickly)

https://github.com/mpah/PokemonGo-Map/commit/7ba6c05532237c1ce7ade3d2b9fb91f0913b4804

**Comment by marauder37** [comment]
See if this commit helps with Google auth: https://github.com/tejado/pokemongo-api-demo/commit/b4b052c2b4c17ffd53cca2941ca67a893ed07116

**Comment by asam1989** [comment]
Hi,

We really need Google Auth support.

PTC has been down for hours.

**Comment by mpah** [comment]
@marauder37 I have added that but its not enough

**Comment by DerScreever** [comment]
same here. 
Added the commit for google auth but not working.
Only see some empty map ^^

**Comment by mpah** [comment]
Ok I've got it wo work and created a pull request. You need to include it inside heartbeat as well @DerScreever

**Comment by DerScreever** [comment]
@mpah 
Did the same but for me it was not working :D

**Comment by asam1989** [comment]
Is there an easy way to update my files - Im kinda new here.

**Comment by marauder37** [comment]
Go into your branch and type `git pull` or `git pull origin master` . If that doesn't work we'll try something else

**Comment by asam1989** [comment]
Is that something i do with Desktop github?

**Comment by marauder37** [comment]
Sorry, I haven't used Desktop Github. Try https://help.github.com/desktop/guides/contributing/syncing-your-branch/

**Comment by marauder37** [comment]
I have a Mac and I type stuff in to the console. You will definitely be able to merge the new code with Desktop Github and those instructions

**Comment by asam1989** [comment]
Im using mac my self and executing the commands there, but i dont know how to update the files through the terminal.

**Comment by DerScreever** [comment]
git pull 
is the command for terminal

**Comment by sykhro** [comment]
I'm closing this since there's already a pull request for this, it just awaits a rebase.
