### ISSUE TITLE
Google Maps footer css not showing

### ISSUE THREAD

**Issue by bengalaviz** [AHAAAAAAA/PokemonGo-Map#1409]
## Expected Behavior

Should be able to see the "+" and "-" zoom buttons.

## Current Behavior

+ and - buttons are partially hidden. CSS issue.

## Steps to Reproduce (for bugs)

1. Open website in URL
2. Can't zoom out as the "-" zoom button is not showing.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):
Have seen issue with both Safari and Chrome.

**Comment by medghaim** [comment]
I believe this is a known issue which the Front end guys will take care of.
