### ISSUE TITLE
Any way to get rid of the colored circle overlay?

### ISSUE THREAD

**Issue by GhettoGosu** [AHAAAAAAA/PokemonGo-Map#1410]
Just wondering if there is a section of code I can comment out to remove these from the map.
![image](https://cloud.githubusercontent.com/assets/20606346/17074970/01524fd2-5043-11e6-8d53-daf8ff6dfac2.png)

**Comment by mattb91** [comment]
Just click filter and then click the scanned locations

**Comment by GhettoGosu** [comment]
Can't believe I didn't see that. Thanks
