### ISSUE TITLE
Error in launch : File "runserver.py", line 11, in <module>     from flask_cors import CORS, cross_origin ImportError: No module named flask_cors

### ISSUE THREAD

**Issue by Yfksw65** [AHAAAAAAA/PokemonGo-Map#1411]
on a debian 8.3 with python etc.. 

python runserver.py -a google -u account@gmail.com -p password -l "location" -st 10

Error : 

Traceback (most recent call last):
  File "runserver.py", line 11, in <module>
    from flask_cors import CORS, cross_origin
ImportError: No module named flask_cors

**Comment by jault3** [comment]
did you `pip install -r requirements.txt`? other things to check include

- ensure `pip install -r requirements.txt` did not error
- python 2 is being used
- if you are using a virtual environment (virtualenv or something similar) you activated it

**Comment by Valareos** [comment]
latest commit requires new modules, so you have to redo the requirements install check

**Comment by yiting007** [comment]
Hi, I'm having the same issue.

I ran `pip install -r requirements.txt` and got

```
Requirement already satisfied (use --upgrade to upgrade): Flask==0.11.1 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): Jinja2==2.8 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe==0.23 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): Werkzeug==0.11.10 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): argparse==1.2.1 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): click==6.6 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): itsdangerous==0.24 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): peewee==2.8.1 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 8))
Requirement already satisfied (use --upgrade to upgrade): wsgiref==0.1.2 in /usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7 (from -r requirements.txt (line 9))
Requirement already satisfied (use --upgrade to upgrade): geopy==1.11.0 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 10))
Requirement already satisfied (use --upgrade to upgrade): protobuf==2.6.1 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 11))
Requirement already satisfied (use --upgrade to upgrade): requests==2.10.0 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 12))
Requirement already satisfied (use --upgrade to upgrade): s2sphere==0.2.4 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 13))
Requirement already satisfied (use --upgrade to upgrade): gpsoauth==0.3.0 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 14))
Requirement already satisfied (use --upgrade to upgrade): protobuf-to-dict==0.1.0 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 15))
Requirement already satisfied (use --upgrade to upgrade): flask-cors==2.1.2 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 16))
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/local/lib/python2.7/site-packages (from protobuf==2.6.1->-r requirements.txt (line 11))
Requirement already satisfied (use --upgrade to upgrade): future in /usr/local/lib/python2.7/site-packages (from s2sphere==0.2.4->-r requirements.txt (line 13))
Requirement already satisfied (use --upgrade to upgrade): pycryptodomex>=3.0 in /usr/local/lib/python2.7/site-packages (from gpsoauth==0.3.0->-r requirements.txt (line 14))
Requirement already satisfied (use --upgrade to upgrade): Six in /Library/Python/2.7/site-packages (from flask-cors==2.1.2->-r requirements.txt (line 16))
```

Then ran `python runserver.py -a google -u [USERNAME] -p [PASSWORD] -st 10 -k [Google Maps API key] -l "[LOCATION]" ` and got

```
Traceback (most recent call last):
  File "runserver.py", line 10, in <module>
    from flask_cors import CORS, cross_origin
ImportError: No module named flask_cors
```

I am using the master branch, my Python version is `2.7.10` and I am using `OS X EI Capitan 10.11.4`.

Thanks.

**Comment by EvKoh** [comment]
Same error

**Comment by Amidee89** [comment]
+1 here, flask seems to be fine otherwise

**Comment by Amidee89** [comment]
once commented, when trying to import pogom.app it will fail at from flask import Flask, jsonify, render_template, request
definitely something is wrong with Flask import here, can't really understand why

**Comment by droydi** [comment]
Having same issue with OSX, haven't tried on linux setup yet. Relevant?

**Comment by RaimundWege** [comment]
I've installed python with homebrew and run into the same issue. After a while I've found out that I've used another installed version of phyton. Run `which python` to look which version you're using. The solution was to fix my path variable.

**Comment by Amidee89** [comment]
If pip is tied to python3, modules will result installed and which Python could just result in expected 2.X
So @yiting007 and OP should definitely try using pip2 instead of pip

**Comment by yiting007** [comment]
hmm..

```
➜  PokemonGo-Map git:(yiting) ✗ pip --version
pip 8.1.2 from /usr/local/lib/python2.7/site-packages (python 2.7)
➜  PokemonGo-Map git:(yiting) ✗ pip2 --version
pip 8.1.2 from /usr/local/lib/python2.7/site-packages (python 2.7)
```

`pip2 install -r requirements.txt` does the same thing, and I still get that error :(

`sudo -H` won't help neither.

**Comment by equiliym** [comment]
have you guys tried manually installing your addons?
`pip install -U flask-cors`
try that one and see what does it tell you after.. i had to manually install a couple and it worked without problems

**Comment by bertolo1988** [comment]
same error

**Comment by MDashK** [comment]
Can't make this work in no way....

I get the error mentioned in the thread, but I can't get flask to install in no way... I always end up getting this error: http://i.imgur.com/vBClfAA.png

**Comment by severedspirit** [comment]
Getting this error too on macOS 10.11 on python 2.7

**Comment by serg06** [comment]
Found a solution:

* Open runserver.py with a text editor
* Add `sys.path.append('C:/python27/lib/site-packages')` anywhere between `import os` and `from flask_cors import ...`
* If needed, replace the path between the single-quotes to where flask_cors is installed

**Comment by MDashK** [comment]
Yeah... My issue is with a Unicode character, that i've found out that it's related to my username in Windows having a special character in the folder's name... Since Python tries to use the TEMP folder inside that special character folder, all goes to hell and nothing installs... And honestly I have no idea how to fix or "go around" that... Because I can't simply change my username folder's name... So...

**Comment by Barnet8** [comment]
Hi

I had the same issue.

You need to launch: 

sudo -H pip install --ignore-installed flask_cors
sudo -H pip install --ignore-installed protobuf_to_dict
sudo -H pip install --ignore-installed gpsoauth

And for me i needed to accept xcode license so:

sudo xcodebuild -license

Press space to the end and enter : agree

Now it's work!

**Comment by Misstag** [comment]
On my LinuxMint 17.3, I had both these directories:
/usr/local/lib/python2.7/dist-packages
/usr/local/lib/python2.7/site-packages

The 2nd was empty and the first one gets the extensions, but sys.path uses that one

**python**
Python 2.7.12 (default, Jul 25 2016, 08:36:00) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> **import sys**
>>> **sys.path**
['', '/usr/local/lib/python27.zip', '/usr/local/lib/python2.7', '/usr/local/lib/python2.7/plat-linux2', '/usr/local/lib/python2.7/lib-tk', '/usr/local/lib/python2.7/lib-old', '/usr/local/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/site-packages']

So I made a link from the 2nd to the 1st using:
**cd /usr/local/lib/python2.7
mv site-packages site-packages.REMOVED
ln -sf site-packages dist-packages**

**Comment by severedspirit** [comment]
The way I solved it was this
```
python -m virtualenv flask-cors
source flask-cors/bin/activate
pip install flask-cors
```
And continue as normal

**Comment by MichaelJAndy** [comment]
In my cause the error was occurring because I set up my virtualenv but was running the app with `# ./runserver,py` which actually calls `#!/usr/bin/python` instead of calling the virtualenv python with the installed packages

So end to end you'd do it something like:
```
# pip install virtualenv
# virtualenv --no-site-packages --distribute -p /usr/local/bin/python2.7 env
# source env/bin/activate 
# pip install -r requirements.txt
# python runserver.py
```

**Comment by wmmc** [comment]
On a mac, I put this line: `sys.path.append('/usr/local/lib/python2.7/site-packages')` on line 7 ish of runserver.py.
And used python2 / pip2 instead of 3. Which seemed to work. 👍
