### ISSUE TITLE
[Enhancement] Multi Thread

### ISSUE THREAD

**Issue by jasonfoy21** [AHAAAAAAA/PokemonGo-Map#1419]
What I see from the little bit of code I've read over and the experience of running the program, it's really slow because you are running in series for each GPS location request. 

Have you thought about multi threading your requests and then having the thread return only the wanted endpoints/data for the map marker.

If you allowed for a @param INT to be set to specify the thread count for the system running and then handed the call to the pokemon api to each thread, It might allow for a faster scan.

**Comment by medghaim** [comment]
Update `develop` branch, multithreaded searching is live.
