### ISSUE TITLE
VERY MINOR: Readme.md preview image

### ISSUE THREAD

**Issue by medghaim** [AHAAAAAAA/PokemonGo-Map#143]
Preview image for readme.md features the wrong icons for pokemans!

**Comment by dwilson08** [comment]
Not sure what you mean.

This one: https://cloud.githubusercontent.com/assets/7145349/16916971/6bd3343a-4cb4-11e6-86cc-e3bc9399a9b0.png?

Those are the correct icons, they were recently merged. If your icons don't look like that and you've run this program before today try clearing your browser cache. (On Chrome, Press F12 > Right click on Refresh Icon > "Empty Cache and Hard Reload")

**Comment by medghaim** [comment]
I thought we went the 2D sprite route? :s

**Comment by DerScreever** [comment]
first of all: the icons stuff we do now will later change. when the fronteend-team did their job.
at this moment the icons look like the posted screenshot.
so i close this now.
