### ISSUE TITLE
Suggestion to the developer

### ISSUE THREAD

**Issue by guest136** [AHAAAAAAA/PokemonGo-Map#1430]
Hello, I thought to myself there are so manny ppl having problems using the Pogomap. Why not creating one stable map of Manhattan like a website. I think the big part of us is trying to get this map work with the location of Manhattan so wouldnt it be a better idea if you create a stable Manhattan map first for the users here - that would be a big favor to us all.

**Comment by chuyskywalker** [comment]
You want something more like https://pokevision.com/
