### ISSUE TITLE
Is the Example.py file no longer available in this version? 

### ISSUE THREAD

**Issue by davidcoronado** [AHAAAAAAA/PokemonGo-Map#1434]
## Expected Behavior
I was expecting to run, "python example.py -a google -u username -p password -l "location "-st 10" and I expected it to work.

## Current Behavior
Instead when I ran that command I got this error, "Python: can't open file 'example.py': [Errno 2] No such file or directory".

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by gilegue** [comment]
The new syntax should be runserver.py in this version

**Comment by rfiorenzano** [comment]
If you're still running within the "master" branch (which is no longer being updated per the wiki) - you should still be able to use this as I am currently using it.

Make sure to run the help for the script to make sure you're utilizing the necessary switches for the server to run.

$ python example.py -a ptc -u User -p Pass -l Location -st Steps

This should be the be the minimum to run utilizing Host=127.0.0.1 and Port=5000 to access a local session run from the same system that ran the script.

**Comment by gilegue** [comment]
Unless you are downloading the master stream manually, the current version already use runserver.py in it
