### ISSUE TITLE
Awesome, love the auto refresh with new API

### ISSUE THREAD

**Issue by littlejob** [AHAAAAAAA/PokemonGo-Map#1441]
How might one publish this to access externally?

**Comment by ShawnHardwick** [comment]
On the Wiki

Deploy to Heroku:
https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Heroku-Deployment

or 

Expose your local instance:
https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/How-to-make-your-map-available-externally

**Comment by littlejob** [comment]
Windows.. ehh. Gives me a direction at least. Thanks
