### ISSUE TITLE
Error pysqlite or sqlite3 must be installed in new version

### ISSUE THREAD

**Issue by FaustKnight** [AHAAAAAAA/PokemonGo-Map#1445]
With the new version (stable and dev) I receive the following when attempting to start the server:

Traceback (most recent call last):
  File "runserver.py", line 47, in <module>
    create_tables()
  File "/home/*****/public_html/cgi-bin/pogohome/pogom/models.py", line 193, in create_tables
    db.connect()
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3402, in connect
    **self.connect_kwargs)
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3657, in _connect
    raise ImproperlyConfigured('pysqlite or sqlite3 must be installed.')
peewee.ImproperlyConfigured: pysqlite or sqlite3 must be installed.

## Expected Behavior
In the previous version (V1) the script runs without error

## Your Environment
Have tried running both as user and as root

Running on CentOS (cPanel server)
Have both Python 2.6 and 2.7

# which sqlite3
/usr/bin/sqlite3

# which python
/usr/bin/python

# which python2.7
/usr/local/bin/python2.7

# pip list
click (6.6)
coverage (4.1)
coveralls (1.1)
docopt (0.6.2)
Flask (0.11.1)
Flask-Cors (2.1.2)
Flask-GoogleMaps (0.2.0)
future (0.15.2)
geopy (1.11.0)
gpsoauth (0.3.0)
itsdangerous (0.24)
Jinja2 (2.8)
MarkupSafe (0.23)
mysql-connector-python (2.2.0)
MySQL-python (1.2.5)
peewee (2.8.1)
pip (8.1.2)
protobuf (2.6.1)
protobuf-to-dict (0.1.0)
pushbullet.py (0.10.0)
pycryptodomex (3.4.2)
python-magic (0.4.12)
requests (2.10.0)
s2sphere (0.2.4)
setuptools (24.0.3)
six (1.10.0)
websocket-client (0.37.0)
Werkzeug (0.11.10)
wheel (0.29.0)

**Comment by FaustKnight** [comment]
Looks like this is an environment issue. Recompiling Python.

**Comment by FaustKnight** [comment]
Confirmed, had to recompile with -enable-loadable-sqlite-extensions

**Comment by nickg819** [comment]
How did you recompile? everything checks out until i try using runserver.py

**Comment by FaustKnight** [comment]
I'm working on CentOS, when I recompiled I did:

./configure --enable-loadable-sqlite-extensions && make && make altinstall

altinstall because I'm running dual python versions
