### ISSUE TITLE
getting the cp of the pokemon scanned as well

### ISSUE THREAD

**Issue by mikila85** [AHAAAAAAA/PokemonGo-Map#1454]
Hi,
first of all, awesome work :+1:  thx for sharing.

Is there a way to get the CP of the pokemon and mark it on map?
I tried debugging and breaking on the "WildPokemon" but it doesnt include the CP info i guess another async request should be made and later add the info to the visible list.
I can develop it and do a pull request if you point me in the right direction.

**Comment by Yivoe** [comment]
isn't the CP info based on the profile you're currently using?  If your using a fake profile to scan, then it wouldn't help much when you got on your real one to go catch it.

**Comment by mikila85** [comment]
ohhhh....
you right...

what about "cp?" pokemons?
any indicator there?

**Comment by Yivoe** [comment]
Again, same issue.  Unless you're running this program using your main account's credentials (which you shouldn't because this is most likely considered cheating).

**Comment by mikila85** [comment]
maybe "cp?" is a general definition of a wild pokemon

**Comment by bfayers** [comment]
Pokemon's CP is shown based on account level. Doing this would also require entering a capture as far as I'm aware making the pokemon just disappear faster.

**Comment by medghaim** [comment]
Do not run this with your main account. This has been discussed. It would be a bad addition because not only would it promote use of your main account, but most (hopefully all) users do not use their real accounts.
