### ISSUE TITLE
New Updated Files Won't Work

### ISSUE THREAD

**Issue by kwilson27** [AHAAAAAAA/PokemonGo-Map#1460]
When I run the following code: python runserver.py -u [Username] -p [Password] -st 10 -k -l [My Location]

I get the following error:

Traceback (most recent call last):
  File "runserver.py", line 10, in <module>
    from flask_cors import CORS, cross_origin
ImportError: No module named flask_cors

any suggestions? the old way works running as example.py however I want to try the new way with runserver.py.

**Comment by keaza** [comment]
You need to use pip2 to install requirements.

`pip2 install -r requirements.txt`

Should fix it

**Comment by kwilson27** [comment]
This is what I get
 
pip2 install -r requirements.txt
Traceback (most recent call last):
  File "/usr/bin/pip2", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip2')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name IncompleteRead

**Comment by keaza** [comment]
Ok.... in the East Setup folder there is a script called get-pip.sh try that see if that helps with the pip error

**Comment by kwilson27** [comment]
Could the problem be that I am running it on Kali linux?

Because I have updated & upgraded kali linux, I have used get-pip.py and then I try to run "pip2 install -r requirements.txt" and I get:

/usr/bin/pip2: No such file or directory

**Comment by keaza** [comment]
then now, try the pip install -r requirements.txt


What i would do, if not install pip2 and try install the requiremnts

**Comment by kwilson27** [comment]
Okay thank you I got it working now, with pip instead of pip2. Is there a way where I don't have to put in my GMAPS_KEY and it can just pull it from the config file instead?

**Comment by keaza** [comment]
You need to put that in config/credentials.json

**Comment by kwilson27** [comment]
I did, so do I then need to state -k? or can I take it out and it will run automatically?

Also does this new update fix the problem with the every 15-30 mins the python script expires? (meaning the Pokemon disappear and you have to re-run the code)

**Comment by keaza** [comment]
You no longer need the -K option. 

I have been tinking with the code so cant comment to find out if this issue is fixed,

**Comment by kwilson27** [comment]
Thank you very much for all your help! :) Everything works, just hoping the 15-30 min python script expire issue is resolved.

**Comment by keaza** [comment]
Glad i can help.
