### ISSUE TITLE
Map Not Showing

### ISSUE THREAD

**Issue by empyrean888** [AHAAAAAAA/PokemonGo-Map#1462]
py runserver.py is working and it's scanning and detecting gyms, pokemons, and pokestops
but map is not showing in my browser

* Version used: Newest (Stable)
* Python 2.7
* Desktop Browser (Chrome & Firefox)

![issue](https://cloud.githubusercontent.com/assets/20609086/17076500/0e0d9830-50de-11e6-974d-4b4df0761ba1.jpg)

**Comment by keaza** [comment]
Have you entered in your Google maps API key? into the config file?

**Comment by empyrean888** [comment]
Yes i did. 1st in the json file and I tried entering it again in the config.ini, and still like that

**Comment by jlroettger** [comment]
What's your debug console look like in the browser? (F12)

**Comment by empyrean888** [comment]
The 'console' tab is empty

**Comment by jlroettger** [comment]
On refresh with devtools open?

**Comment by Nomaxxx** [comment]
Same problem...[https://s31.postimg.org/mqvnw7vnf/Clipboard01.jpg](url)

**Comment by jlroettger** [comment]
Do you have javascript disabled? Are all the resources being loaded in the network tab?

**Comment by Nomaxxx** [comment]
Allow all sites to run JavaScript (recommended)

**Comment by Rainexxx** [comment]
Map not showing, out of error 500
https://s32.postimg.org/6qxax1rz9/2016_07_23_13_08_58.png

**Comment by jsynx** [comment]
Same problem for me, no map is showing ... Except I don't have the names of the pokemons either (compared to what empyrean888 got). Javascript is enabled and I tried both on firefox and google chrome with no luck. Here's what it looks like : 
![screen](https://cloud.githubusercontent.com/assets/20609990/17076951/ea13c6b6-50bf-11e6-9ef2-19b644570e91.png)

**Comment by jsynx** [comment]
Additionally, I noticed that when trying to open the map with the script running, I get a bunch of errors : 
![screen2](https://cloud.githubusercontent.com/assets/20609990/17076969/80e70472-50c0-11e6-98a3-b0645bc38e0a.png)

**Comment by jlroettger** [comment]
Did you install using `setup.bat` in the `Easy Setup` folder?

**Comment by jsynx** [comment]
I did install using the setup.bat of my developpement branch folder yes. I am using the following command line : C:\Python27\python runserver.py -a google -u mail@gmail.com -p ******* -l "48.631826, 2.551389" -st 10

**Comment by jlroettger** [comment]
Try adding ` -P 8088 -H 0.0.0.0` and then visiting `localhost:8088`

**Comment by empyrean888** [comment]
I tried to install with the easy setup and the normal way using pip
The commands were
py runserver.py -a ptc -u [username] -p [password] -l "Coordinates" -st 30 -H 0.0.0.0 -L en 
(On the youtube desc one)
and
py runserver.py -a ptc -u [username] -p [password] -st 30 -k [GmapAPI] -l "Coordinates"
(On wiki example)
But both have the same result

I tried adding the -P 8088 and still the same when I opened localhost:8088

**Comment by jlroettger** [comment]
If that doesn't work, try moving the whole folder to the root of your `C:` drive. Do you have a non-ascii character in the directory filepath?

**Comment by erdalgns** [comment]
Have you enabled Google Maps Javascript API? It was the problem for me.

**Comment by jsynx** [comment]
Tried adding -P 8088 -H 0.0.0.0 but still displays the same as my previous screenshot... HOWEVER, my developement folder was in my downloads folder (which has characters like "é" in it in my language), and moving it to the root C:/ solved everything ! Thanks a lot jilroettger ;).

**Comment by jlroettger** [comment]
Great! Glad that worked :) Happy hunting!

**Comment by Tyroniel** [comment]
Mine is the same, Tried to move the folder to C and there isn't any non-ascii. But some code appearing on my console
![mine](https://cloud.githubusercontent.com/assets/20611443/17077555/44b9f1b0-50fe-11e6-80b0-333889855d05.jpg)

**Comment by empyrean888** [comment]
putting it in root doesn't work for me, I tried to find the solution in the internet and it's because I have installed dreamweaver. I uninstalled dreamweaver and it works now, only on firefox though. 

Here's the link : 
http://stackoverflow.com/questions/22839278/python-built-in-server-not-loading-css

Thanks for your help guys,
