### ISSUE TITLE
Make option for just gym scan

### ISSUE THREAD

**Issue by Nulifyer** [AHAAAAAAA/PokemonGo-Map#147]
I used the -o options to set pokemon exclusive search for "none" , this works but it is still s slow process is there a way you could make a gym search that would be faster because it doesn't have to search for pokemon. tried changing the source a bit to do this but mess up my copy of the program and had to reset it ( i'm still learning about protobuf and python which i've never used before )

**Comment by DerScreever** [comment]
we could add an option to disable the pokemon search i think.

**Comment by Nulifyer** [comment]
great cause ive been trying to make a territory map and this is the best api for that that ive seen so far good work

**Comment by DerScreever** [comment]
added the enhancement label. we will do this later.

**Comment by 0x539** [comment]
You can achieve this buy using the -o option for example:

python example.py -a ptc -u USER -p PASSWORD -l "Central Park, NY" -st 10 -dp -dg -o lol

**Comment by hhu94** [comment]
I can add this, but a question first. Should I make a --display-pokemon flag that defaults to True or a --disable-pokemon flag that defaults to False?

**Comment by Nulifyer** [comment]
@hhu94 
the goal is to be able to use this api to query the pokemon go servers for all pokestops , gyms and their current owner and be able to display this on google maps. this api does this well and I would like to use it only i don't need to slow down the process by looking for pokemon at the same time.  if someone could add the ability to only query about gyms and  pokestops to speed up the process i would appreciate it.

**Comment by hhu94** [comment]
I have implemented a flag that allows me to disable pokemon scanning, but I have noticed that it didn't improve speed by a significant margin. I believe this is because the bulk of the time spent by the script is in getting the heartbeat data from the server, not in processing said data.

Thus I decided to not make a pull request for this flag.

If you need performance improvements, please take a look at the discussion in #62

**Comment by JZ6** [comment]
fixed
