### ISSUE TITLE
Pokemon icons won't showing up

### ISSUE THREAD

**Issue by nendraharyo** [AHAAAAAAA/PokemonGo-Map#1470]
Help please i have opened the pokemon go map but the only things showing up are gyms, pokestops, and scanning bubbles. But in the command prompt it says upserting pokemons. I opened the developer option in chrome and the icon source is not showing up. Can anybody helping me to make the pokemon icons showing up? i'm a beginner in programming language.
![capture](https://cloud.githubusercontent.com/assets/20609166/17076984/9a62d6fe-50b8-11e6-94b5-7c7e426a76ec.PNG)

**Comment by Sokrad** [comment]
I have the same issue :(

**Comment by Sokrad** [comment]
I found this. he get no pokemons to mark :/

console.log(result);
![image](https://cloud.githubusercontent.com/assets/2326970/17077570/c86cb6c0-50d4-11e6-989f-a7427e5a271d.png)

**Comment by nendraharyo** [comment]
I've tried it in another browser and still not working :(

**Comment by Sokrad** [comment]
go to /pogom/app.py

line 34:             d['pokemons'] = Pokemon.get_active()

and change to 

            d['pokemons'] = Pokemon.get_all()

this work for me

**Comment by nendraharyo** [comment]
I've changed it and still not working

**Comment by vinsilsim** [comment]
@Sokrad dont work for me

**Comment by Alukardz** [comment]
@sokrad this combined with https://github.com/AHAAAAAAA/PokemonGo-Map/issues/1477 @dienot fix is making a lot more pokemons appear on my map

**Comment by nendraharyo** [comment]
@Alukardz used that to and still no pokemon in the map :(

**Comment by nendraharyo** [comment]
The console founds the pokemon but not showing them in the map, why is that?
![ss](https://cloud.githubusercontent.com/assets/20609166/17078189/7868a804-50e4-11e6-9c29-df2f04d25920.PNG)

**Comment by eiswuerfel** [comment]
I had a wrong systeme timezone.

**Comment by nendraharyo** [comment]
@eiswuerfel god it works, thankyou so much hahaha, i changed it to london timezone
