### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by denniskai1234** [AHAAAAAAA/PokemonGo-Map#1483]
The current develop version uses 33%~ of my CPU, the old master version just 1-3% per instance.

Im using Python 2.7.10

python runserver.py -a ptc -u username-p password-l "Dortmund, Deutschland" -st 10 -H 0.0.0.0 -P 4444 -L de

**Comment by cNyhuus** [comment]
It might be because it now uses 5 theads per default i guess. Before it did only used one.

You can thange it by adding -t 1 to your command line

**Comment by denniskai1234** [comment]
Yeah, found that out and changed it, still thanks!
