### ISSUE TITLE
while scanning, localhost:5000 cannot connect with browser

### ISSUE THREAD

**Issue by puaykai** [AHAAAAAAA/PokemonGo-Map#1485]
## Expected Behavior
When scanning for pokemon, should still be able to connect to server

## Current Behavior
When scanning for pokemon, unable to connect to server

## Steps to Reproduce (for bugs)

1. run this 
python runserver.py -a google -u **** -p **** -l "50.255022, 28.658587" -
st 25 -H 0.0.0.0 -P 3141 -t 20 -sd 10
2.
go to browser and type this
localhost:5000

## Your Environment
windows operating system
python 2.7

**Comment by mewm** [comment]
That's because you are binding port 3141 and not 5000. Try connecto ```http://localhost:3141``` instead
