### ISSUE TITLE
No config\credentials.json file in folder

### ISSUE THREAD

**Issue by IAmYeled** [AHAAAAAAA/PokemonGo-Map#1488]
I have downloaded the zip file from [here](https://github.com/AHAAAAAAA/PokemonGo-Map) and after runnig it I get an errror: 

> pogom.exceptions.APIKeyException: No Google Maps Javascript API key entered in \
> config\credentials.json file! Please take a look at the wiki for instructions on
>  how to generate this key, then add that key to the file!

But I don't have a config\credentials.json file. Even in the github I can't see one ([picture](http://up416.siz.co.il/up1/imjtbzz1z2kn.png)).

**Comment by Sp4rkR4t** [comment]
Have you ran the easy setup batch file yet?

**Comment by tpmodding** [comment]
it is in the CONFIG directory

**Comment by IAmYeled** [comment]
@tpmodding Thank you :)
