### ISSUE TITLE
Multiple pokemons, shown on map with high time (45+ min) not in pokemon go

### ISSUE THREAD

**Issue by cNyhuus** [AHAAAAAAA/PokemonGo-Map#1495]
## Current Behavior
When the use of --mock is applied, some pokemons appear around the location on the map. But they are not really there.

## Steps to Reproduce (for bugs)
1. Start the runserver.py with the --mock
2. Do not start any workers
3. Load the map in the browser

## Context
I have four pokemons on my Pokemon GO map, that cannot be found at the locations.
Its a Charizard, Venusaur, Ivysaur and a Bulbasaur.

The timer on them is strange too, when i first saw them, it said about 45 minuts before expiring.

I can add that, if i shutdown all my python processes, and deleted the .db file, then start it again;
They are still there, but the timer gets resettet to 60 min to expire. very strange.

![multiple not in pokemon](https://cloud.githubusercontent.com/assets/20610367/17077549/064973ee-50d4-11e6-9b41-88a65fa46625.PNG)

## Your Environment
Python 2.7
Current master build
Windows server 2012 R2

**Comment by cNyhuus** [comment]
Dont know, but maybe this problem could realaet to https://github.com/AHAAAAAAA/PokemonGo-Map/issues/1388

**Comment by cNyhuus** [comment]
Update to the bug.

I found that, it only happens if i use --mock as an argument. They spawn instantly, if i only run a python runserver.py with --mock and no workers.

So it seems like a bug that is happening, if you use the --mock argument.

**Comment by MonkeyLeeT** [comment]
Mock does insert mock objects, so it's intended. behavior.
