### ISSUE TITLE
cant run, some erroros

### ISSUE THREAD

**Issue by buzzo123** [AHAAAAAAA/PokemonGo-Map#1501]
when i try to lunch  runserver.py i have one of this error:

socket.error: [Errno 98] Address already in use

geopy.exc.GeocoderUnavailable: Service not available

geopy.exc.GeocoderTimedOut: Service timed out

i use this command: "python runserver.py -a google -u username -p password -l "Santa Monica Pier" -st 7 -H 0.0.0.0 -L en"
why this error?

**Comment by kurohai** [comment]
You are trying to run two different programs on the same network port. Are you installing this onto a server that is already running a web application? What port number are you using?

**Comment by buzzo123** [comment]
i have to modify config.ini to run differnet port from 5000?

**Comment by cNyhuus** [comment]
You can add the argument -P or --port to your command, and specify it there.

Eg: python runserver.py -a google -u username -p password -l "Santa Monica Pier" -st 7 -H 0.0.0.0 -P 5001 -L en"

**Comment by buzzo123** [comment]
thanks! now works, but i cant see pokemon, only the map

**Comment by buzzo123** [comment]
i have this in terminal: 
2016-07-23 13:35:37,136 [auth_google] [   INFO] Google Login failed.
2016-07-23 13:35:37,136 [     search] [   INFO] Failed to login to Pokemon Go. Trying again.
2016-07-23 13:35:38,138 [auth_google] [   INFO] Google login for: myusername

**Comment by kurohai** [comment]
You need to supply the username and password for your google account that is tied to Pokemon GO. You can put it in the command line options.

**Comment by buzzo123** [comment]
the username is the email? name@gmail.com ?

**Comment by buzzo123** [comment]
i try this command: python runserver.py -a google -u username -p pass -l "Santa Monica Pier" -st 7 -H 0.0.0.0 -P 5001 -L en

but dont work i have this message:
geopy.exc.GeocoderUnavailable: Service not available

and when im in this in terminal:

2016-07-23 13:35:37,136 [auth_google] [ INFO] Google Login failed.
2016-07-23 13:35:37,136 [ search] [ INFO] Failed to login to Pokemon Go. Trying again.
2016-07-23 13:35:38,138 [auth_google] [ INFO] Google login for: myusername

**Comment by buzzo123** [comment]
i try all: only name before @, the entore google mail but nothing, i've the same result:

Failed to login to Pokemon Go. Trying again.

i think is a problem server, it's possible?

**Comment by Sejadis** [comment]
i assume you created a new google account for this?
you have to login to pokemon go app and play till you choose the player name

**Comment by cNyhuus** [comment]
Or you could go the the pokemon trainer club website, and create yourself a new ptc account.

Its not a good idea to use your own account (if you are trying to do that)

**Comment by buzzo123** [comment]
i dont undestand, for the username i have to use my username in game or my google username?

**Comment by buzzo123** [comment]
i dont have created a new account, i play pokemon go with mt account and try to login at pokemap with the same account, i try name@gmail.com and only "name" but nothing

**Comment by buzzo123** [comment]
ok, now ptc account works!

**Comment by cNyhuus** [comment]
buzzo123, i would recommend you to create a pokemon trainer club account to use with the map.

Using your own account, can get it banned, as the Pokemon go map is agienst the ToS of the game.
(as far as i have understanded)

**Comment by Sejadis** [comment]
name@gmail.com would be correct but you shouldnt use your main account
you probably have 2step authentification activated and thats why it doesnt work

@cNyhuus  while your advise is completely correct - with the ptc server problems its way easier to create a new google account instead of a new ptc account :)

**Comment by kurohai** [comment]
In that case you should create a PTC account. If the page says they are doing maintenance, try to go to the site on your phone. I was able to create an account on my phone last night while the page said under maintenance every time I tried on my PC.

You should have two different PTC accounts. The one you already have to play the game, and a new one to use the map. This software technically violates the TOS. Niatic can ban/ suspend/ delete your account if they feel like it.

**Comment by buzzo123** [comment]
i have already ptc account ;), yes i have 2 step authentication, now i understand why don't works, thank everybody guys :)
