### ISSUE TITLE
Some iOS versions can't load the map properly

### ISSUE THREAD

**Issue by LemonCaik** [AHAAAAAAA/PokemonGo-Map#1502]
## Expected Behavior
Website should load with the map and icons showing up

## Current Behavior
When loading the website on an ios8 device, the page stays blank with only the topbar and filter.
Console(iOS 8.1):

> [Error] SyntaxError: Invalid character: '`'
> 	(anonymous function) (map.js:152)
> [Error] InvalidValueError: initMap is not a function
> 	Yg (js:96:425)
> 	(anonymous function) (js:131)
> 	Load (js:21)
> 	(anonymous function) (js:130:600)
> 	global code (js:131)
> [Error] Failed to load resource: the server responded with a status of 404 (Not Found) (cross.png, line 0)

I've also found issues on iOS 9.1-eish devices where no icons (pokestops, pokemons or gyms) load into the map
Console(iOS 9.1):

> [Error] QuotaExceededError: DOM Exception 22: An attempt was made to add something to storage that exceeded the quota.
> 	updateMap (map.js:410)
> 	global code (map.js:496)
> [Error] ReferenceError: Can't find variable: Notification
> 	(anonymous function) (map.js:2)
> [Error] QuotaExceededError: DOM Exception 22: An attempt was made to add something to storage that exceeded the quota.
> 	initMap (map.js:104)
> 	(anonymous function) (js:96:451)
> 	(anonymous function) (js:49:102)
> 	(anonymous function) (js:46:443)
> 	(anonymous function) (js:49:159)
> 	(anonymous function) (js:102:1461)
> 	(anonymous function) (js:46:443)
> 	(anonymous function) (js:102:1568)
> 	hc (js:48:388)
> 	Rb (js:102:1308)
> 	(anonymous function)
> 	global code (js:134)
> [Error] Failed to load resource: the server responded with a status of 404 (NOT FOUND) (cross.png, line 0)
> [Error] QuotaExceededError: DOM Exception 22: An attempt was made to add something to storage that exceeded the quota.
> 	updateMap (map.js:410)

## Steps to Reproduce (for bugs)
1. python runserver.py -a google -u <username> -p <password> -l <location> -st 15 -H 0.0.0.0 -P 6999
2. Open <local-ip>:6999 on the device

## Context
It's not allowing any of these devices to use the PokemonGo-Map. Upgrading the firmware isn't ideal considering some jailbroken devices run these versions of iOS and iOS 9.3.3 isn't jailbroken yet.
I've also tested it on 9.2+ and it seems to be running fine

## Your Environment
* Version used: <head> revs of the master and develop branch
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): Host on Ubuntu 16.04 and iOS versions 8.1 and 9.1

**Comment by MRokas** [comment]
This requires transpiling code from ES6 to ES5. I will pass it to dev team.

**Comment by LemonCaik** [comment]
Thanks. Meanwhile I used the changes on #1140 and got it working, maybe you could have them merge it on the develop branch

**Comment by DevAndArtist** [comment]
My iPhone 6 Plus with iOS 10 Beta 2 loads only once and keeps the map blank (no pokemon) after changing the location or refreshing/reloading the page.

**Comment by MRokas** [comment]
@DevAndArtist - perhaps your Maps API key is expired?

**Comment by swablueme** [comment]
iOS 8.3 is borked as I describe here: https://github.com/AHAAAAAAA/PokemonGo-Map/issues/1217
I'm currently on iOS8.3 to preserve my jailbreak. :(

**Comment by DevAndArtist** [comment]
@MRokas It's working fine on my mac, but as soon as I try to change the location on my iPhone, any Pokémon disappears (only on my iPhone; still fine on my mac).

**Comment by DevAndArtist** [comment]
@swablueme mine is not fully blank, I still see the map, but I don't see any annotations.

**Comment by LemonCaik** [comment]
@swablueme you can fix that with the changes on #1140 and then re-building with grunt
