### ISSUE TITLE
Can't follow the "Get Directions" if using Google Maps in French (or another language)

### ISSUE THREAD

**Issue by Plop** [AHAAAAAAA/PokemonGo-Map#1503]
## Expected Behavior
Being able to get directions to the wanted pokestop/pokemon with Google Maps

## Current Behavior
If using Google Maps in French, "Current Location" isn't recognized by the app, and it doesn't work.

## Possible Solution
If -L fr is selected, replace "Current Location" by "Votre position"

Would really be great for hunting. Thanks.

**Comment by Plop** [comment]
@betrisey , will you do a PR for this ? Thanks

**Comment by betrisey** [comment]
@Plop C'est fait :)

**Comment by Plop** [comment]
Niquel, merci @betrisey :D
