### ISSUE TITLE
New build not finding all pokemons

### ISSUE THREAD

**Issue by Naprosnia** [AHAAAAAAA/PokemonGo-Map#1507]
Previous versions find more Pokemon than the current build.

**Comment by MRokas** [comment]
Are you using latest version? What OS you're using? What arguments did you use?

**Comment by Naprosnia** [comment]
windows.
start python runserver.py -a PTC -u un -p pw -l "-33.86599699203773, 151.20813846588135" -st 10

same with google account

**Comment by Naprosnia** [comment]
with yesterday's release, find lot more pokemon.

**Comment by cNyhuus** [comment]
Use the paremeter -t 1 to set threads to only use one.

The new build uses 5 per default, that there is an issuse with that. There is another issuse on here about that.

**Comment by Naprosnia** [comment]
old version
https://postimg.org/image/48mpyae7r/][img]https://s31.postimg.org/48mpyae7r/old.png
new version
https://postimg.org/image/jsu3otoc7/][img]https://s31.postimg.org/jsu3otoc7/new.png

cNyhuus, i'll try.

**Comment by Naprosnia** [comment]
cNyhuus, works ;)
