### ISSUE TITLE
Make Wiki editable

### ISSUE THREAD

**Issue by coolaj86** [AHAAAAAAA/PokemonGo-Map#1512]
I'd like to update the quickstart on the wiki and add some step-by-step for developing, but the wiki is locked.

Can we get that unlocked so that people can update it willy-nilly? This is a fast-moving project and I'm sure many others have valuable knowledge they could contribute and update.

**Comment by FallenArchangel** [comment]
I second this.  Besides, there are a few pages with conflicting information.

At the top it might say something, but at the bottom it will be different because it was for an older version.

**Comment by chuyskywalker** [comment]
There is a github project for the enhanced wiki now. https://www.jonaharagon.com/PoGoMapWiki/#!index.md
