### ISSUE TITLE
Commend Help

### ISSUE THREAD

**Issue by NeoVilsonWong** [AHAAAAAAA/PokemonGo-Map#1523]
-t - Number of threads

this commend not avalible?

**Comment by darcycartwright** [comment]
Run  `'runserver.py -h'` and if it's not listed, update the version of PokemonGo-Map you are running.

**Comment by Skullmonkey** [comment]
Still works for me... Are you putting anything after it?

On windows, run "-t 1" otherwise youll lose a lot of pokemon.

**Comment by NeoVilsonWong** [comment]
@darcycartwright  how to update? i direct git clone 

example.py: error: unrecognized arguments: -t

**Comment by NeoVilsonWong** [comment]
@Skullmonkey , i cant used this commend if possible i want run more fast threat 

example.py: error: unrecognized arguments: -t

**Comment by NeoVilsonWong** [comment]
Solve!!!
