### ISSUE TITLE
Doesn't clear old pokemon

### ISSUE THREAD

**Issue by michaelowens** [AHAAAAAAA/PokemonGo-Map#153]
It seems to keep old pokemon when fetching new ones, so I e.g. had 2 magmars at the same spot (which was probably 1, with a couple of minutes diff between disappearing time) and after a while both already disappeared, but stayed on the map till restart of script.

### Environment info
Operating System: Ubuntu (for the app), windows + chrome (for viewing)

Installed version of Python: 2.7.6

### Steps to reproduce
1. Let app run for several iterations
2. View map

### What have you tried?
1.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by DerScreever** [comment]
we already working on this with #101

**Comment by michaelowens** [comment]
Ah my bad, must have missed that ticket when searching for an existing issue!
