### ISSUE TITLE
example.py and runserver.py

### ISSUE THREAD

**Issue by KobusPretorius** [AHAAAAAAA/PokemonGo-Map#1546]
So the example.py extension apparently doesn't work anymore and when using runserver.py I get this: 
![untitled](https://cloud.githubusercontent.com/assets/20614395/17078840/478cc37c-50fe-11e6-9a21-1898f39ee600.jpg)

**Comment by KobusPretorius** [comment]
Yes I did add a space to the 10

**Comment by MRokas** [comment]
can we see whole command you used?

**Comment by KobusPretorius** [comment]
Just edited the pic

**Comment by MRokas** [comment]
Your command has some errors. use this format
`-a x -u x -p x -l 00.980307,00.257870 -st 9 -H 0.0.0.0 -P 4444 -t 10`

**Comment by KobusPretorius** [comment]
![2](https://cloud.githubusercontent.com/assets/20614395/17078910/2e8068ea-5101-11e6-87ed-ad7b3301df1d.jpg)

**Comment by MRokas** [comment]
You've to copy in your google maps api key.

**Comment by KobusPretorius** [comment]
Where would I find it on windows or my phone? and how please

**Comment by KobusPretorius** [comment]
localhost:5000 not working?

**Comment by MRokas** [comment]
any more errors thrown?

**Comment by KobusPretorius** [comment]
Not command prompt, but localhost

**Comment by MRokas** [comment]
if you cant access it, it means there was errors in command prompt

**Comment by KobusPretorius** [comment]
![3](https://cloud.githubusercontent.com/assets/20614395/17079083/11d426c8-5106-11e6-851e-d1cf6d22c46b.jpg)
