### ISSUE TITLE
Change Your Location Not Working

### ISSUE THREAD

**Issue by mrachimv** [AHAAAAAAA/PokemonGo-Map#1558]
Change Your Location Not Working

**Comment by rayfarias56** [comment]
Also not working for me, but I'm not sure if it's user error on my part. Currently deployed via heroku. Everything's working, but location updating. Not sure how submitting a location works. Any ideas? (currently looking through things to try to figure this out on my own.

**Comment by viruzofficial** [comment]
Also not working for me, have no plan how this should work.

**Comment by matpag** [comment]
i've used master version and it's working fine for me

**Comment by N3evin** [comment]
Yeah i am having the same issue, using their latest V2 of the map in master. Notice that whenever i search it request for correct google map js API, which was already provided and the map is working. It seems like it's just not reading the correct API key that was included when config.

**Comment by rayfarias56** [comment]
So I don't know if other people here are using the Google Maps Api Key from the project yesterday, but the developers console in chrome says the query limit has been reached for the day. I think the problem is tied to that. I'm trying my own key now and I'll post back asap.

**Comment by rayfarias56** [comment]
Yes a quick api key update to heroku solved my issue. If anyone here was lazy and skipped that step as I did, just quickly follow the steps here: https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Google-Maps-API:-a-brief-guide-to-your-own-key. 


N3evin, are you running the app locally or from heroku or other?

**Comment by N3evin** [comment]
Using heroku, is there anyway to edit the credential.json from heroku?

**Comment by matpag** [comment]
I'm using the system config vars instead of credentials.json for all the variables to set

**Comment by yihengli** [comment]
Hi guys, I am having the same issue here. Basically I just followed the steps:
https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Heroku-Deployment
(Use the button <- Delploy to Heroku)
In terms of the Config, I am using my own google API. 

It works fine with my original address in the first config. However it doesn't work when I am trying to search a new location from the web. Everytime I searched, I found an error in console:

This API project is not authorized to use this API. Please ensure this API is activated in the Google Developers Console

**Comment by yihengli** [comment]
IT'S SOLVED!

I enabled almost everything from the google map API. (originally just google map js api) Then, it works. Maybe the search function used some other API things I haven't figured out yet.

**Comment by N3evin** [comment]
Ah thanks! We need to enable "Google Places API Web Service" too.
