### ISSUE TITLE
Loacation error

### ISSUE THREAD

**Issue by Wojozoo** [AHAAAAAAA/PokemonGo-Map#156]
Hi,
I have get an error when trying to run the script. 
Hope some of you can help me out.

### Environment info
Operating System:
Os X

Installed version of Python:
2.7

### Steps to reproduce
1. Follow the installation description
2. $ python example.py -a google -u [Gmail-username] -p Password -l "City, Country" -st 5

### Logs or other output that would be helpful
-bash: 12: command not found
usage: example.py [-h] [-a AUTH_SERVICE] -u USERNAME -p PASSWORD -l LOCATION
                  -st STEP_LIMIT [-i IGNORE | -o ONLY] [-d] [-c] [-dp] [-dg]
                  [-H HOST] [-P PORT] [-L LOCALE]
example.py: error: argument -l/--location is required

**Comment by DerScreever** [comment]
yes you need to pass an location: example 
python example.py -u test -p test **-l "New York"** -st 5

**Comment by Wojozoo** [comment]
Thanks for your fast replay.
Thats what I have tried:
python example.py -a google -u [Gmail-username] -p Password **-l "City, Country"** -st 5
and
python example.py -a google -u [Gmail-username] -p Password -l **"City"** -st 5

**Comment by DerScreever** [comment]
so it work now?
pass it without, so City Country

**Comment by numanWD** [comment]
Could be because your password has special characters, try to change it with a simple one

**Comment by Wojozoo** [comment]
Thanks, that solved the issue.
