### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by BlayzerQ** [AHAAAAAAA/PokemonGo-Map#157]
Infinite cycle looping steps.
After 
('Completed:', 100.0, '%')
[-] register_background_thread called
[-] register_background_thread: queueing
wait sometimes and repet. A get this messeges, sometimes [-] retrying_api_req: request error (('Connection aborted.', BadStatusLine("''",))), retrying
and web-server on IP:5000 dont started.

**Comment by rclavel** [comment]
After `('Completed:', 100.0, '%')`, the map is loaded, you have to connect to localhost:5000 to see it.
The reloading after is just a refresh, it is normal.

**Comment by BlayzerQ** [comment]
i start this app on dedicated server, and try connect to IP:5000 and nothing.

**Comment by g3r4n** [comment]
you have to had "-H 0.0.0.0" to the command line

**Comment by BlayzerQ** [comment]
-H or -P - get error.

**Comment by g3r4n** [comment]
`python example.py -H 0.0.0.0 -a ptc -u nope -p nope -l "Nantes, France" -st 10 
`
works for me

**Comment by BlayzerQ** [comment]
error: unrecognized arguments: -H 0.0.0.0

**Comment by rclavel** [comment]
You should `git pull`

**Comment by BlayzerQ** [comment]
python example.py -H 0.0.0.0 -a ptc -u BlayzerQ -p mypass -l "Zalesnaya ulitsa, Kazan" -st 5

**Comment by BlayzerQ** [comment]
i het zip from github and put content to my server.

**Comment by rclavel** [comment]
You have to do it again, this project is updated very frequently.

**Comment by TheWebSmith** [comment]
Download again and put the new ones on your server. It should work. I'm using almost the same command.

**Comment by g3r4n** [comment]
i think the best way is to clone it on the server and made frequently some git pull.

**Comment by BlayzerQ** [comment]
Thanks! This work!
