### ISSUE TITLE
Feature request: remove gmaps labels

### ISSUE THREAD

**Issue by Skullmonkey** [AHAAAAAAA/PokemonGo-Map#1573]
Add a toggle to remove the street names and other lables on GMaps. I know my city very well and they are a distraction to me.

**Comment by joveice** [comment]
Could be cool if possible

**Comment by TheReaperr** [comment]
Open up static/map.js  in function initMap() theres styles:[...]. There you can set up how your google maps looks like. Find the entry for the labels.

I didn't really like the default look so I looked up a good one on snazzymaps.com ( I'm using https://snazzymaps.com/style/52112/dark-grey-w-contrast)

**Comment by Skullmonkey** [comment]
This is all fine and dandy short time, but this file constantly gets updated and I would have to go in and manually edit the file each time it gets updated. A toggle would be nice so it stays in place.
