### ISSUE TITLE
Got this after running for a little while.

### ISSUE THREAD

**Issue by JudGithub** [AHAAAAAAA/PokemonGo-Map#159]
http://pastebin.com/raw/DWPNW95U

**Comment by medghaim** [comment]
How long is a little while?

**Comment by JudGithub** [comment]
maybe 10mins

**Comment by TheWebSmith** [comment]
Same here after completing one loop. It was completing the old loop:
`[-] looping: step 48 of 49`
`('Completed:', 100.0, '%')`
`[-] register_background_thread called`
`[-] register_background_thread: queueing`
then printing out the location and token and after that the error occured.

**Comment by BrodrickChilds** [comment]
This usually means it wasn't able to connect to the server in my experience.  Read: they're on fire

**Comment by JudGithub** [comment]
I just think the script needs more try: catch: continue

**Comment by pace-noge** [comment]
That happen if hitting google too often

**Comment by JZ6** [comment]
fixed
