### ISSUE TITLE
Running many servers, worried about amount of data usage

### ISSUE THREAD

**Issue by Schwaitz** [AHAAAAAAA/PokemonGo-Map#1590]
Hello there,

I am running about 9 different server instances. 4 of them for friends, and 5 of them for detailed updates of my hometown (strategically placed for staying up-to-date).

The basic idea is that on port :5000, I am receiving **all** of data from the updates on ports :5001, :5002, :500X, etc. I don't care about getting the updates on the server scanning in California, because I am on the east coast.

I've figured out that the Pokemon location data is hard-stored in files. Is the only way to get around this to make 4 separate folder copies?

Thanks!

Justin

**Comment by Hoekynl** [comment]
If I understood this correct :
So you have 1 folder, with the pokemon go map files, and you run 9 servers from that folder?
You could make a second folder with seperate map files, and run the 5 servers from that folder while running the other 4 from the other folder for your friends?
Folder 1 > Hometown
Folder 2 > Friends

**Comment by Schwaitz** [comment]
@Hoekynl Exactly. Is that just what it takes, and what I should do? I am perfectly okay with doing that, just want to make sure that is the easiest way.

**Comment by Hoekynl** [comment]
I guess that is the easiest way. 

Also I read adding the -ns argument allows you to execute the server without using a extra port, so your friends server will only take port 5000 and your hometown one can use 5001. Though im not sure it works

**Comment by Schwaitz** [comment]
@Hoekynl, I've been using the -ns argument for the precise map so that I don't have to be running 4 additional web servers that I don't need. I think this works. I'm going to close this.
