### ISSUE TITLE
Best method for multiple instances with mysql?

### ISSUE THREAD

**Issue by mattb91** [AHAAAAAAA/PokemonGo-Map#1594]
I don't see a flag to choose mysql when running the runserver from the command line. Is it possible to have multiple config.ini and choose which to use?

**Comment by Yakovlevam** [comment]
In pogom/utils.py
comments
#    args.location = Config.get('Search_Settings', 'Location')
#    args.port = Config.get('Misc', 'Port').
then run 
 ./runserver.py -se -l "X X" -p Z

**Comment by abighairyspider** [comment]
is it possible to run multiple instances with different locations/accounts using the same mysql DB and web server?

**Comment by mattb91** [comment]
Not home right now to test but if I understand correctly I can runserver.py -se to have them all using the same database and then throw my -u -p -l location flags

**Comment by abighairyspider** [comment]
runserver.py -se -u -p -l on the second process threw an error. i was able to get it to run with runserver.py -se -ns -u -p -l, but it's not showing the second scan area on the map.

**Comment by mattb91** [comment]
Same here not sure what the issue is. Maybe the second process can't update the database? Haven't been able to look in to it.

**Comment by abighairyspider** [comment]
ok. it looks like even if you use the -l flag and enter a new location the location from config.ini is being used.

**Comment by mattb91** [comment]
Ahh can it be ran without a location in the config.ini

**Comment by abighairyspider** [comment]
OK. I got it working. You basically need a new folder for each instance with it's own config.ini. Once you have them setup run the second instance using the -se and -ns arguments. sloppy, but it works.

**Comment by AKhozim** [comment]
`E:\
cd E:\PokemonGo-Map-master
start python runserver.py -u loganwww -p 123asd -st 10 -l "-1.276948, 116.837443" 
cd E:\PokemonGo-Map-master\$BB
start python runserver.py -se -ns -u testbpn1 -p 123asd -st 10 -l "-1.242440, 116.862462" 
cd E:\PokemonGo-Map-master\$SMALA
start python runserver.py -se -ns -u testjkt1 -p 123asd -st 10 -l "-1.241928, 116.893350"
cd E:\PokemonGo-Map-master\$BANDARA
start python runserver.py -se -ns -u kentangtamvan -p 123asd -st 10 -l "-1.260365, 116.899906"
pause`
@abighairyspider i tried to do it like this but i can only see the first instance with no -ns and -se to work in the map

**Comment by mattb91** [comment]
War
