### ISSUE TITLE
A Charmander, Charmeleon, Charizard, Bulbasaur, Ivysaur, and Venusaur are constantly spawning on server start 

### ISSUE THREAD

**Issue by Schwaitz** [AHAAAAAAA/PokemonGo-Map#1595]
## Current Behavior
As explained in the title, a Charmander, Charmeleon, Charizard, Bulbasaur, Ivysaur, and Venusaur are spawning in the same locations when I start the server. I have visited the location that they consistently spawn at, and sadly, they are not actually there. Another strange thing is that they start with 60 minutes on the timer.

[Here is a screenshot showing what I mean](http://i.imgur.com/sHVd9Qo.png).

## Possible Solution
I have no idea why this would be happening.

## Your Environment
* Version used: Dev branch within the last few hours
* Environment name and version: Python 2.7
* Operating System and version: Linux (Ubuntu 14.04)

**Comment by ELusiveLPFAN** [comment]
same thing, after adding parameter -m on start.

**Comment by docrockulus** [comment]
delete pogom.db and restart the scans

**Comment by ELusiveLPFAN** [comment]
What if I told you that I remove it, but nothink..?

**Comment by Kiniamaro** [comment]
then you better get your sneakers on and start catching them pokemons!

**Comment by IlluNV** [comment]
The param -m will is said to be "mock-mode" and describes it self as "starts only the webserver but nut the search", in fact it starts the web server yes, but it will also insert "dummy" objects. So just start one server without -ns and let it fetch from the the rest instead of using -m on one

**Comment by ELusiveLPFAN** [comment]
Thanks bro!

**Comment by IlluNV** [comment]
No problem, just had the same problem so i was looking through the code and found the answer ^^

**Comment by cNyhuus** [comment]
Exactly was i see in my issuse aswell: https://github.com/AHAAAAAAA/PokemonGo-Map/issues/1495

**Comment by MonkeyLeeT** [comment]
Mock does insert mock objects, so it's intended. behavior.
