### ISSUE TITLE
Example.py not found

### ISSUE THREAD

**Issue by ktorti** [AHAAAAAAA/PokemonGo-Map#1606]
I pulled the latest updates and after I did I got this error.

can't open file 'example.py': [Errno 2] No such file or directory

**Comment by Gamewalker** [comment]
You need to pull from the develop branch and not from master

**Comment by BillyWM** [comment]
Which branch?

Master and Develop use runserver.py

Only the old 1.0 uses example.py

**Comment by mattb91** [comment]
in case it wasn't clear example.py is now call runserver.py
