### ISSUE TITLE
Search in a rectangle not in a square

### ISSUE THREAD

**Issue by g3r4n** [AHAAAAAAA/PokemonGo-Map#161]
Why not search in square ?
![capture d ecran 2016-07-18 a 22 38 07](https://cloud.githubusercontent.com/assets/10941033/16929501/5b3c4308-4d38-11e6-90f9-fcc609105af7.png)

**Comment by AHAAAAAAA** [comment]
It's actually the same distance along both longitude and latitude, what you're seeing is the result of map projections. Your issue is with the archaic [Mercator map projection](https://en.wikipedia.org/wiki/Mercator_projection) system used since 1569, not our code!

**Comment by g3r4n** [comment]
ok 😄
