### ISSUE TITLE
Google Login fails when port forwarding flags are enabled

### ISSUE THREAD

**Issue by praxandanthilus** [AHAAAAAAA/PokemonGo-Map#1614]
Google login failing when I attempt to run the script with port forwarding enabled.

## Expected Behavior
Script should run fine with all proper variables specified. Port forwarding set up through my router's firewall last night.

## Current Behavior
Attempt to run the script gives me the error "Google login failed. Failed to login to Pokemon Go. Trying again." Script indefinitely attempts to log in to the server and fails.

## Steps to Reproduce (for bugs)
my command line is the following:
python runserver.py -a google -u myemail -p mypassword -l "my coords" -t 1 -h -0.0.0.0 -p 5001

## Context
I had this setup and working perfectly last night with the old master. Don't know why it doesn't work anymore with these flags. Please help!

## Your Environment
Windows 8.1 Python 2.7

**Comment by tj1627** [comment]
Port flag should be a capital P not a lowercase p. I ran into this too a while back.

**Comment by praxandanthilus** [comment]
Thanks, it worked! This can be closed.
Unrelated question...if I stop my server and start it again, the scanned pokemon and gyms, etc., remain. How can I get the map to clear again when I restart?

**Comment by FrostTheFox** [comment]
afaik, you can't get it to clear them. it should remove them soon after you start again, because they will be expired by then.
