### ISSUE TITLE
Create a plain map without GUI

### ISSUE THREAD

**Issue by andrewda** [AHAAAAAAA/PokemonGo-Map#1622]
## Expected Behavior
We should be able to access a non-GUI version of the map. This will make it much easier for developers looking to port PokemonGo-Map (such as [PokemongGo-DesktopMap](https://github.com/mchristopher/PokemonGo-DesktopMap)) to incorporate the map with more appropriate GUI mechanics that fit well with the port. To make this work, we'll also need to add back some more command-line arguments so that the GUI mechanics on ports are able to change things about the map (this is addressed in #1608).

## Possible Solution
Something similar to the current `map.html` file without the GUI.

## Context
This will make it a lot easier to port this repository into other applications.

**Comment by adrianocr** [comment]
@andrewda  If you look inside pogom/app.py you will see that there's a route named "raw_data". That route outputs JSON. Why don't you simply fork the repo and remove any GUI interface and simply use the raw JSON output? Problem solved.

**Comment by andrewda** [comment]
@adrianocr In that case, it wouldn't be much of a port of PokemonGo-Map and more of an addition to the pgoapi. I see what you're saying, but it would be much easier for other developers if we were to make an easily accessible raw map, as opposed to just the raw JSON data.
