### ISSUE TITLE
[Feature Request] argument to hide "Change your location" feature

### ISSUE THREAD

**Issue by thomasmoors** [AHAAAAAAA/PokemonGo-Map#1633]
Please add an argument (I might try it myself) to hide this feature if someone has a public instance which should help not overusing the pogo account.

**Comment by denniskai1234** [comment]
Go to the map.html located in the templates folder, go to line 48 and chane this:

http://pastebin.com/0W1rJXM2

to this:

http://pastebin.com/WBSRyUbU

Restart the Server and the Option will be gone.

**Comment by thomasmoors** [comment]
Thank you

**Comment by horatiulefter** [comment]
not working

**Comment by thomasmoors** [comment]
@horatiulefter I just add `disabled` to the input element, it's a fix that's easy to bypass but it does the trick for me
