### ISSUE TITLE
Pip not a valid command

### ISSUE THREAD

**Issue by AssaultBird2454** [AHAAAAAAA/PokemonGo-Map#1635]
when trying to setup the map the command pip is not valid

I am using a script that JZ6 provided on the discord server as i wanted to export all the pokestops and gyms to a CSV. I was using the wrong version of python them i got the correct version but now it is giving me an error where an import is missing a modal (Requirements)

OS: Windows 8.1 Industry Standard (Pro) x64

**Comment by AssaultBird2454** [comment]
oops i will upload the script he gave me
[jzscrawler.zip](https://github.com/AHAAAAAAA/PokemonGo-Map/files/379969/jzscrawler.zip)

**Comment by wethegreenpeople** [comment]
Could you copy/paste the error?

**Comment by AssaultBird2454** [comment]
-=-=-Bash-=-=-
$ pip install -r requirements.txt
bash: pip: command not found

Fixed the pip issue but now i get this... i dont have the requirements file

**Comment by AssaultBird2454** [comment]
now i get this stuff when i try and run it

`Traceback (most recent call last):
  File "main.py", line 7, in <module>
    import pokemon_pb2
  File "C:\Users\AssaultBird2454\Desktop\source\pokemon_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
ImportError: No module named google.protobuf`

**Comment by balancedinsanity** [comment]
help
im getting bash: pip: command not found
i cant figure it out
