### ISSUE TITLE
Barely any pokemon are showing

### ISSUE THREAD

**Issue by InstallGentoo11** [AHAAAAAAA/PokemonGo-Map#1636]
After the newest version with the new options and stuff I barely get any pokemon showing around. Even pokevision is now showing me more than this. I am using Python 2.7 and a Windows 7 PC.

**Comment by Secret0tter** [comment]
Me and many other users were having this problem. Adding "-t 1" to the end of your command chain should fix it. It did for me. It will slow down the search though.

**Comment by callmeron** [comment]
See #1540 for discussion about this. I would close this out as a dupe of the referenced Issues.
