### ISSUE TITLE
Wrong Pokemon icon 

### ISSUE THREAD

**Issue by alagabba** [AHAAAAAAA/PokemonGo-Map#1638]
Hello Guys,

I updated to the newest develop Version and i see a wrong Pokemon icon on my Map.

![wrong](https://cloud.githubusercontent.com/assets/20617427/17080264/ec978ff8-5128-11e6-949d-1e7a2b036cdf.png)

Is this a failure? 

*Edit Another Pokemons too

**Comment by cNyhuus** [comment]
Could be this commit: https://github.com/AHAAAAAAA/PokemonGo-Map/commit/3f67317268338dda0c56c55e62e274eec8d25636

@fettlaus has commented, that it has changed a staryu to a ditto

**Comment by thefernman** [comment]
Same here, Ditto pokemon image but Staru detail name.

**Comment by fettlaus** [comment]
Already reverted. Please close issue

**Comment by alagabba** [comment]
Thanks guys problem solved
