### ISSUE TITLE
Sprite needs fixing...

### ISSUE THREAD

**Issue by Skullmonkey** [AHAAAAAAA/PokemonGo-Map#1641]
## Expected Behavior
Pokemon images to line up with actual pokemon

## Current Behavior
Staryu looks like ditto. It would make sense the other way around but...

## Possible Solution
Fix sprite location to Staryu

## Steps to Reproduce (for bugs)
1. Run program
2. Wait until Staryu
3. Get really really REALLY freaking excited because it looks like Ditto
4. Click on it
5. Cry in a corner because it is not Ditto
6. Depression

![capture](https://cloud.githubusercontent.com/assets/396053/17080278/244709b0-50f7-11e6-8769-01e1a337fd9c.PNG)

**Comment by cNyhuus** [comment]
Could be this commit: https://github.com/AHAAAAAAA/PokemonGo-Map/commit/3f67317268338dda0c56c55e62e274eec8d25636

@fettlaus has commented, that it has changed a staryu to a ditto

There is also another issuse on this problem: https://github.com/AHAAAAAAA/PokemonGo-Map/issues/1638

**Comment by FrostTheFox** [comment]
Just been reverted.
