### ISSUE TITLE
I made new icons for gyms and pokestops

### ISSUE THREAD

**Issue by crusardri** [AHAAAAAAA/PokemonGo-Map#1642]
Hi, i made new icons for the map.
Here is the images
http://imgur.com/a/I0iyk
And here is the preview
![](http://i.imgur.com/mqkh9FD.png)

Sorry for my bad english

**Comment by andrewda** [comment]
:+1: They look great!

**Comment by JoshuaGarrison27** [comment]
Looks great but am I the only person that things they are just a little too big?

**Comment by HinoReo** [comment]
@JoshuaGarrison27 +1. Too big and it's hard on eyes, imo.

**Comment by andrewda** [comment]
@JoshuaGarrison27 @HinoReo I believe you are able to change the size of them when placing them on the map using the Google Maps API. Won't be difficult to make them smaller at all.

**Comment by JoshuaGarrison27** [comment]
@andrewda I'm sure you can. I'm just thinking about the user average user.

**Comment by ShawnHardwick** [comment]
I agree with making them smaller, but adding a black outline/stroke would probably make it look more clean as well.

**Comment by medghaim** [comment]
These are really clean, but I agree with the others. Too big and perhaps missing a thin black border? It's hard on the eyes.

**Comment by medghaim** [comment]
Also, this is something you should send in a pull request with - not open an issue for. Please send in a PR and have the community discuss :)
