### ISSUE TITLE
Drowzee Icon showing as lickatounge

### ISSUE THREAD

**Issue by Sharke** [AHAAAAAAA/PokemonGo-Map#1644]
## Expected Behavior
Drowzee should show correct image

## Current Behavior
it is currently showing the image of a different pokemon

## Steps to Reproduce (for bugs)
Using latest dev build with MySQL on windows

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by Skullmonkey** [comment]
Already reverted.

**Comment by Sharke** [comment]
Thanks.
