### ISSUE TITLE
-bash: !1: event not found Error when attempting to run program

### ISSUE THREAD

**Issue by drurx7** [AHAAAAAAA/PokemonGo-Map#1645]
I'm getting an error message "-bash: !1: event not found" when trying to run the program using the below command. Running Python V2.7.5 in OSX terminal and recently completed the installation of PokemonGo-Map-master using the instructions provided in the project wiki. I double checked for the correct password and am running the program inside of the unzipped file.

command used:

python runserver.py -a google -u [new_acct@gmail.com] -p [gmail pwd] -st 10 -k [new google api key] -l "[lat long]"

**Comment by BillyWM** [comment]
Don't post your password here, but does it have an exclamation point in it?

If so, you have to escape it with a backslash.

so -p hunter!2

becomes

-p hunter\!2

In Bash, "!" is a shortcut to do the last command you entered

**Comment by drurx7** [comment]
Wow, that was it. Thanks so much for your help!
