### ISSUE TITLE
Lured Active but is not Active

### ISSUE THREAD

**Issue by alagabba** [AHAAAAAAA/PokemonGo-Map#1647]
Lured not Active Ingame but map sayed yes 

![lured](https://cloud.githubusercontent.com/assets/20617427/17080330/497dacb4-512b-11e6-89d0-028f00738404.png)

Develop Version actually 

Edit* Timer goes higher by refresh site

Edit2* Now is the Lured Inactive, is this normal?

**Comment by andrewda** [comment]
> Lured Pokémon: undefined - # 92

Well, something's definitely broken... I'll go take a look.

**Comment by andrewda** [comment]
#1669 should fix this issue :)
