### ISSUE TITLE
Make icons smaller

### ISSUE THREAD

**Issue by JakeCooper** [AHAAAAAAA/PokemonGo-Map#165]
The current icons are massive. It would be fantastic if they could be halved or even quartered.
![image](https://cloud.githubusercontent.com/assets/5499880/16929635/7c7d3fb8-4ced-11e6-951c-afa1e98cc362.png)

**Comment by rclavel** [comment]
Actually I also would like to control the image size, but to make them bigger (for example on mobile: it is very small and hard to click)

**Comment by DerScreever** [comment]
yeah true there are massiv. but we stop to change the icons all the time until the frontend-team give the okay.
