### ISSUE TITLE
No map is showing up

### ISSUE THREAD

**Issue by themightyjoe** [AHAAAAAAA/PokemonGo-Map#1655]
When I go to launch localhost:5000, no map shows up. I get the text that is supposed to appear when the "filter" button is clicked on, but no map. The program appears to be running because I am getting notifications about the pokemon as they spawn, I just can't see them. I've attached a screenshot.
![screenshot](https://cloud.githubusercontent.com/assets/20617659/17080391/13dbc152-50e2-11e6-95d7-5e1abf124888.jpg)

I've tried clearing cache, using different browsers, and neither helped. I've verified that my Gogle maps API is enabled. I even tried changing the API. Occasionally I get an "initMap is not a function" error in the developer window within Chrome. 

I'm using Windows 7, chrome browser, and Python 2.7.12. I had the original version working, but this new updated version isn't playing nice with me

**Comment by Hoekynl** [comment]
Installed the new requirements.txt? It has new programs to be installed.
Else it might be permissions ?

**Comment by themightyjoe** [comment]
Yep, I installed the new requirements.txt. I also just ran it again with the --update flag at the end and I'm still having the same issue.

Looks like #1462 and #1564 are similar issues, however the solutions there haven't worked for me.
