### ISSUE TITLE
[Graphics] new Gym badges

### ISSUE THREAD

**Issue by MikeDuister** [AHAAAAAAA/PokemonGo-Map#1671]
## Gym icon redesign
I felt the need to make new gym icons. These are in the form of little shields/badges.  
![screenshot_106](https://cloud.githubusercontent.com/assets/1430696/17080647/16959882-5137-11e6-8d49-b76db225cb82.png)

Icons can be found here: http://imgur.com/a/XZNE9

With the addition of one for your 'favorite' team:
![shit-big](https://cloud.githubusercontent.com/assets/1430696/17080660/6a908406-5137-11e6-9ac6-2616e5fa3931.png)

**Comment by andrewda** [comment]
:+1: I like 'em!

**Comment by callmebackdraft** [comment]
@MikeDuister got my +1
why not do a PR ?

**Comment by kevinpark1217** [comment]
@MikeDuister Do you want me to make the changes and do the PR? I'll make sure to give you the credits and link this thread if you already haven't done it.

**Comment by MikeDuister** [comment]
@kevinpark1217 That would be great, I have to get used to the use of git tbh and I feel like starting with such a massive project is not a good start.

**Comment by jakeyjdavis** [comment]
Do you still have the high-res icons?

**Comment by MikeDuister** [comment]
@jakeyjdavis yes, here they are: http://imgur.com/a/Qnvu9

**Comment by jakeyjdavis** [comment]
Thank you
