### ISSUE TITLE
Toggle for changing locations

### ISSUE THREAD

**Issue by primaxius** [AHAAAAAAA/PokemonGo-Map#1672]
Please add a toggle to allow or disallow the changing of locations.

**Comment by Skullmonkey** [comment]
Was done in #1616 

Add "-fl" in your command line.

**Comment by Chlodochar** [comment]
It seems to be doing this only client-side. It should disable `/next_loc` as well. Probably returning 403 from next_loc should be enough.

**Comment by EdenGottlieb** [comment]
@Chlodochar  Your wish is my command. #1688

**Comment by horatiulefter** [comment]
not working with heroku , any ideas?

**Comment by EdenGottlieb** [comment]
@horatiulefter You're probably implementing it wrong. the key needs to be EXTRA_ARGS and the value needs to be -fl  .
