### ISSUE TITLE
Not All Pokemon Appear on Map

### ISSUE THREAD

**Issue by calebbait** [AHAAAAAAA/PokemonGo-Map#1681]
**## Current Behavior**
Map doesn't show all Pokemon that it finds, scanner doesn't find all Pokemon that exist. Some scanned Pokemon appear in console but not on the map, and some Pokemon that appear in my game don't appear on either.

**## Steps to Reproduce (for bugs)**
1. python runserver.py -u myuser -p mypas -st 12 -l "mylocation" -dc
2. Map scans, establishes Pokestops and Gyms, and some Pokemon
3. Some Pokemon that appear in the console (and in my game) don't appear on the map

**## Your Environment**
* Version used: Latest source code (not release)
* Environment name and version: Python 2.7
* Operating System: Windows 10

**Comment by calebbait** [comment]
https://github.com/TheZ3ro/pkmngo-map Seems to be mostly accurate except for a few bugs, maybe something in his code can help.

**Comment by QuadTog** [comment]
Multi threading is set to 5 threads natively. Try invoking "-t 1" in your CMD line to fix it.

Currently there's a thread issue with Pokemon so they don't all get upset correctly.

**Comment by calebbait** [comment]
Thanks QuadTog, that solved my issue!

**Comment by calebbait** [comment]
Okay, so while what QuadTog said did help significantly, there are still spawns that do not appear on the map that I know are there.

**Comment by calebbait** [comment]
Okay, so while what QuadTog said did help significantly, there are still spawns that do not appear on the map that I know are there.

**Comment by calebbait** [comment]
Restarting the scanner fixed the issue.
