### ISSUE TITLE
How can I run multiple instances at the same time?

### ISSUE THREAD

**Issue by gosp07** [AHAAAAAAA/PokemonGo-Map#1682]
How can I run multiple bots to track and have them show in the same map?Or if I cant merge them can I open seperated tabs to see different ones.Like lets say normally its on Lh:5000 can I Run another in lh:4000 , if I cant merge multiple ones

**Comment by Data33** [comment]
Open two instances, one in Lh:5000 and one in Lh:4000 for example.
Make sure they write to the same database file (should be by default if you ran both instances from the same folder).
When you look at either instance in your browser they should already be merged :)

**Comment by salemgolemugoo** [comment]
Duplicate #1472

**Comment by delrio1110** [comment]
run main first python runserver.py -a ptc -u {USERNAME} -p {PASSWORD} -l {LOCATION} -st 10
then run second one with (-ns) run main first python runserver.py -a ptc -u {USERNAME} -p {PASSWORD} -l {LOCATION} -st 10 -ns

**Comment by delrio1110** [comment]
like  salemgolemugoo  said, just use the -ns switch

**Comment by gosp07** [comment]
ok thanks I got my answer but gonna ask this one out cuz I'm dumb on this subject do I need to open a second cmd for the other trackings or I just need to write the -ns addeds ones to the same cm , and can I use 1 ptc for all or do I need multiple ones(this one doesnt need answer at worst I can get ptc acounts)

**Comment by callmebackdraft** [comment]
multiple CMD windows

you can use 1 ptc, however i would advise against it
better to use multiple, if they see 1 account jumping at a high speed all through big regions it is to get banned for sure

**Comment by gosp07** [comment]
Thanks I did it

**Comment by Zerotask** [comment]
Should the instances run on own ports or can they all run on the default port?
