### ISSUE TITLE
Turn off Pokestops

### ISSUE THREAD

**Issue by Envvi** [AHAAAAAAA/PokemonGo-Map#1683]
Hi all, I've noticed that "Upserting pokestops" takes quite a long time each (from one second to sometimes 20 seconds) is it possible to disable it so it never searches for them?

**Comment by BillyWM** [comment]
Yes. You have to run with a config.ini file, then add the "-se" option to the command line

**Comment by Envvi** [comment]
I have it running with the config.ini file now. What is the parameter to disable pokestops? Also it appears as though on the second run through the search is much slower (sometimes up to 2 minutes for just 20 steps)

**Comment by BillyWM** [comment]
In Search_Settings.

If you write something on these lines the feature will be disabled

```
disable_pokemon: 
disable_pokestops: 
disable_gyms: 
```

**Comment by EdenGottlieb** [comment]
Isn't running the app with the -nk flag does exactly the same thing?
https://github.com/AHAAAAAAA/PokemonGo-Map/pull/1372

**Comment by BillyWM** [comment]
@EdenGottlieb Probably. There's so very many flags now :)

**Comment by Envvi** [comment]
https://i.gyazo.com/5df9ebc4db29f5ad35cf4f0aa2b1e3fd.png

Like this? There wasn't anything like it present already, so I added it. I also tried to add "true" after it but it will still process Pokestops. And to give an idea it runs to 50% in about 30 seconds then it starts processing pokestops for three steps and that alone takes about 30 seconds.

**Comment by BillyWM** [comment]
Which branch are you running? Looks like only develop has this setting right now.

**Comment by Envvi** [comment]
Ah ok thanks. Develop has this feature.

**Comment by swtrpeter** [comment]
Where do u find the search settings ?
