### ISSUE TITLE
Gyms showing up that aren't really there?

### ISSUE THREAD

**Issue by DeviantEng** [AHAAAAAAA/PokemonGo-Map#1689]
Running the latest dev branch, but was having this issue a couple hours ago.  Running a mysql db, and running 2 separate scripts (one to start web only without scanning; `-m`, and one to start multiple scans on different locations; `-ns`).  When I start the web script, I am seeing gyms nearby that aren't really there.  My town has no gyms, in fact, but yet I see 6 within a mile of me.  I can toggle them off, as expected, but why are they showing up to begin with? 

To test, I dropped my db (currently have no db), and run a script to start the web instance.  Script runs:
```
/usr/bin/python /opt/PokemonGo-Map/runserver.py -a ptc -u USERNAME -p PASSWORD -l "Dallas, TX" -st 0 -H 0.0.0.0 -m >> /var/log/pokemap/web.log 2>&1 &
```

Running on CentOS 7 with Python 2.7.

**Comment by wertel** [comment]
Looks like `-m` option makes random pokemon and gym. Maybe because it's a "Mock mode".

**Comment by DeviantEng** [comment]
Ah, I wasn't clear on that.  I thought `-m` just started the webserver and not the scanner.

**Comment by DeviantEng** [comment]
I removed `-m` from my startup, and I'm still seeing those gyms.  Do I need to dump my db and rebuild?

**Comment by wertel** [comment]
I wiped my db. Web only option exist in pull request [#1700](https://github.com/AHAAAAAAA/PokemonGo-Map/pull/1700)

**Comment by callmebackdraft** [comment]
gyms and pokestops stay in db, rebuild wouldnt be necesary just delete it and rerun your code

**Comment by DeviantEng** [comment]
Dropped by db and restarted my scanners and those fake gyms are gone. The description of -m needs to be updated to reflect the dummy data.  

Looking forward to #1700.

Thanks!
