### ISSUE TITLE
Heroky Deploy issue

### ISSUE THREAD

**Issue by kwstasna** [AHAAAAAAA/PokemonGo-Map#1691]
Hello.
I have delpoyed on heroku and i gave the same link to some friends.
So when I scan from Athens i get some results, but when im searching for example London with my iPhone, my results stop to be shown for the City of Athens and the results of the second request (London) continue normally.
I dont know if this is a bag or if i am doing anything wrong.

**Comment by medghaim** [comment]
Please take support questions to: https://discord.gg/2wwnH
