### ISSUE TITLE
Is there a way to implement different tracking system?

### ISSUE THREAD

**Issue by gosp07** [AHAAAAAAA/PokemonGo-Map#1693]
I was using a branch before but I needed to use dev version to be able to use multiple bots. What my problem is the map I used before had a faster tracking.Is there way I can implement that on to the devs bot?

**Comment by matslarson** [comment]
increase the number of scanning threads using -t [value] when you run the script

**Comment by medghaim** [comment]
Closing as not an issue. Please take support questions to: https://discord.gg/2wwnH
