### ISSUE TITLE
Error if location string contains special characters

### ISSUE THREAD

**Issue by dianasalsa** [AHAAAAAAA/PokemonGo-Map#17]
Not a huge issue, but I noticed that when the location string contains special characters (such as ä,ö,ü for example) the startup fails due to a **geopy.exc.GeocoderQueryError** error

So maybe there is a problem with the encoding somewhere.

![geocoder_error](https://cloud.githubusercontent.com/assets/15210597/16901855/6ec51eac-4c4f-11e6-9d1e-eeafc394a718.PNG)

**Comment by marauder37** [comment]
I just tested with `--location Québec` and it's working for me. Can you get the latest code and try again? If it's still not working let us know what location you're trying to use.

**Comment by dianasalsa** [comment]
I downloaded the code again, the error remains, this time it appeared directly in the command window.

I used the city "München" (which is the German word for Munich). As you can see in the screenshot, if I use the correct German spelling, it throws an error; as soon as I replace the special character with normal letters, it works.
![geocoder_exception](https://cloud.githubusercontent.com/assets/15210597/16902587/be2a43f0-4c63-11e6-916b-36799f9fc717.png)

**Comment by marauder37** [comment]
![image](https://cloud.githubusercontent.com/assets/1592348/16902824/e72c4754-4cad-11e6-9d9b-7dc0ff9ad887.png)

I wonder if it's a Windows Shell thing. I basically pasted your München into my terminal and it went.

**Comment by dianasalsa** [comment]
I think I can confirm that: I tried it on a different windows machine, same error happens. I then tried on the same machine on a linux partition, here there are no problems.

**Comment by sykhro** [comment]
I did some testing myself, it's a Windows-related issue and not on our end, closing

**Comment by sykhro** [comment]
Solved with ff7cff9689
