### ISSUE TITLE
Delay in finding Pokestops at center

### ISSUE THREAD

**Issue by BillyWM** [AHAAAAAAA/PokemonGo-Map#1713]
Running the very latest develop. Same was happening with an older version from today.

It seems that it doesn't load the stops and gyms near the actual location of your request until it makes a second pass.

-----------------------------------

***Test***

Centered the map on Sunrise Mall, Citrus Heights, CA.

This mall has 5 stops and a gym inside:

https://cloud.githubusercontent.com/assets/288075/17081172/7de00912-5102-11e6-9c90-ea297ef3e41a.png

Almot done...still not showing...

https://cloud.githubusercontent.com/assets/288075/17081190/2af2301c-5103-11e6-9f7e-81f6aa322f54.png

Second pass. There's the stops:

https://cloud.githubusercontent.com/assets/288075/17081192/47ca552a-5103-11e6-91e1-9f4356adfed4.png

Looks like it still missed the gym until even later:

https://cloud.githubusercontent.com/assets/288075/17081195/5a98180e-5103-11e6-901f-6b43068e5741.png

**Comment by hhu94** [comment]
I believe this is intended. We wanted to speed up the pokemon loading, so stops and gyms are not loaded until the first pass is completed.

**Comment by BillyWM** [comment]
Why only the center? As you can see it's getting stops while it scans (this is a fresh DB).

**Comment by MonkeyLeeT** [comment]
Those stops outside center...how could it even be there if scanning is not yet there?

**Comment by BillyWM** [comment]
@MonkeyLeeT: That's a good question too but that's what it's doing. I watched it scan and they popped up that way. Maybe just a discrepancy because the circles don't precisely match the scan area.

**Comment by jangrewe** [comment]
It's either after the first pass or after 50 steps, IIRC. And that's intended to give newbies instant gratification.

**Comment by BillyWM** [comment]
Alright. Known behavior. Closing.
