### ISSUE TITLE
[Feature Request] Flag to disable the ability to change your location

### ISSUE THREAD

**Issue by Shugabuga** [AHAAAAAAA/PokemonGo-Map#1714]
I am suggesting a feature that will allow one to disable the ability to change the location in the GUI.

## Expected Behavior and Possible Solution
This could be done using a flag like `-dlc` or `--disable-location-changes` that, when used, will hide the "Change Your Location" settings in the web interface (and disable the ability to drag the marker to do the same thing).

## Current Behavior
There is no way (as far as I am concerned) to do this currently.

## Context
This could be useful if you are hosting a map for the community and don't want users to change the location, inconveniencing other users of said map.

### Current Behavior:
<img width="256" alt="Current Behavior" src="https://cloud.githubusercontent.com/assets/10801851/17081206/1de44fc6-511d-11e6-85d8-3d70bf4ef611.png">

### Proposed Behavior:
<img width="260" alt="Proposed Behavior" src="https://cloud.githubusercontent.com/assets/10801851/17081205/1de3419e-511d-11e6-95bd-593f5259133e.png">

**Comment by Skullmonkey** [comment]
You can do it with "-fl"

**Comment by jmccorm** [comment]
I had the same concern. Thanks for the info, Skullmonkey.

**Comment by atomoton** [comment]
-fl only disables the search, but does not stop one from dragging the marker.

**Comment by danielbennifer** [comment]
@atomoton Does dragging and dropping the marker work? I don't see that on my version. Is it disabled by default?

**Comment by atomoton** [comment]
Working for me, yes

**Comment by danielbennifer** [comment]
@atomoton Thanks mate. I'll fire it up again shortly and take another look. I may have simply overlooked it.
