### ISSUE TITLE
Request to contribute to UI control

### ISSUE THREAD

**Issue by yang6lang1** [AHAAAAAAA/PokemonGo-Map#1716]
Hi, I am really interested in what you guys are doing here. I have some UI experience and I would like to contribute a bit after testing the dev build a bit (It failed at helping me catching a blastoise lol).
I am wondering is it ok for me to implement the functionality to double click to reposition the google marker? Is this against the original UI design? This for sure will have to disable the disableDoubleClickZoom function so I want to ask you guys' opinion.

Thanks!

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by thinklarge** [comment]
Not sure if this changes anything for you (because I tried to double click to move my marker too) but you can drag and drop the marker if you'd like.  It will move and recenter your search as well.

**Comment by yang6lang1** [comment]
True. It's just that in the case where there's many unfiltered pokemons its hard to drag. But I guess it's optional.

**Comment by medghaim** [comment]
Having the form in your issue, but not filling it out, and writing a paragraph on top doesn't help anyone. Please reopen your issue but fill out the form.

**Comment by medghaim** [comment]
Also, this _is not_ an issue. Please direct questions of help or support to: https://discordapp.com/invite/Kzp4yky

**Comment by yang6lang1** [comment]
Thanks for the feedback. New to the open source community and the processes. :)
