### ISSUE TITLE
Crashed on second step

### ISSUE THREAD

**Issue by pokeemerald** [AHAAAAAAA/PokemonGo-Map#1717]
Suddenly, when I run the script on my server machine, I'm getting the following error.
Screenshot added.
python runserver.py -a google -u xxx@gmail.com -p xxx --host xxxx -L de -l xxxx,xxxx -st 10

## Expected Behavior
It should normally keep on scanning.

## Current Behavior
Crashes on second step

## Steps to Reproduce (for bugs)
I don't know, it suddenly started happening.

## Your Environment
* Version used: development-branch
![ss 2016-07-24 at 03 38 14](https://cloud.githubusercontent.com/assets/20153687/17081227/8e01634c-5150-11e6-8af5-e07aa47bbeaa.png)

* Environment name and version (e.g. Python 2.7): Python 2.7.12
* Operating System and version (desktop or mobile): Windows Server 2008 R2

**Comment by thinklarge** [comment]
Did you have quotes around your lat long?

**Comment by pokeemerald** [comment]
No I don't

**Comment by pokeemerald** [comment]
It's weird because the search.py doesn't have a line 164

**Comment by pokeemerald** [comment]
I just found out that running it on my desktop works completely fine

**Comment by pokeemerald** [comment]
I do also receive a None in the command line at the beginning of the script

**Comment by medghaim** [comment]
Please direct support questions to: https://discordapp.com/invite/Kzp4yky
