### ISSUE TITLE
No pokemon showing up

### ISSUE THREAD

**Issue by lucidrain** [AHAAAAAAA/PokemonGo-Map#1719]
Is anyone else having an issue where the map isn't showing any Pokemon? It is showing all the stops, gyms, etc but no pokemon. I thought maybe my account had been banned or something, because it was working perfectly this morning, so I created a new one and I'm getting the same result. I'm currently running the latest "PokemonGo-Map-master" and Python 2.7.12

**Comment by medghaim** [comment]
I'm closing the issue as it's not properly formatted. Feel free to resubmit, but this time fill out the default form. 

Also, please direct support questions to https://discordapp.com/invite/Kzp4yky

**Comment by zhengyangfeng00** [comment]
had a similar issue a few minutes back and bouncing the server resolved it.

**Comment by Miioff** [comment]
I have a similar issue. Worked once, but after I turned of the terminal and tried to relaunch server it didn't work anymore.
After restarting multiple times it's still not working...
