### ISSUE TITLE
[Question] Does the level of the account affect the pokemon you are able to see?

### ISSUE THREAD

**Issue by zhengyangfeng00** [AHAAAAAAA/PokemonGo-Map#1720]
When using a new account which has level one, is it able to see all high level / rare pokemons?

**Comment by EdenGottlieb** [comment]
Yes. All pokemons appear on all accounts, no matter what level they are.

**Comment by medghaim** [comment]
This is _not_ an issue. 
Support questions here: https://discordapp.com/invite/Kzp4yky
