### ISSUE TITLE
Change your location not working

### ISSUE THREAD

**Issue by blackhattristar** [AHAAAAAAA/PokemonGo-Map#1724]
I used to be able to type in a location under the Change your location setting and change my location and load more Pokémon but now it doesn't work.

## Expected Behavior

When you type in a location it should show possible options again and take you to the changed location.
## Current Behavior

Right now when you type in the name of the location, it goes nowhere and the text disappears. 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by superwesker1988** [comment]
I have the same issue. Is there a fix for that?

**Comment by blackhattristar** [comment]
My fix was changing the gmaps_api. Hope this helps!

**Comment by superwesker1988** [comment]
Yes, I enable web service api of my key, then the function is back. Don't know why it used to work though.
