### ISSUE TITLE
NEED: most accurate version.

### ISSUE THREAD

**Issue by ericpadilla** [AHAAAAAAA/PokemonGo-Map#1731]
I've been trying and comparing dev build as well as the v2.0 but i found that both does not detect pokemon in nearby list fully. Could you let me know which version is the most accurate one? thanks!

i used python runserver.py -a ptc -u ******* -p ****** -l "********, -*******" -st 7 -t 1 -H 0.0.0.0 -P 5000

**Comment by DrTeej** [comment]
Ran into the same issue. Just submitted a issue on it. 
Is this what you're seeing? https://github.com/AHAAAAAAA/PokemonGo-Map/issues/1730

**Comment by ericpadilla** [comment]
mine is not that bad, just missing out few pokemon at most three.

**Comment by DrTeej** [comment]
But similar situation. Wonder why it's not detecting properly. I tried to use more threads - but doesn't seem to help.

**Comment by ericpadilla** [comment]
i have no idea, i noticed that the old rectangle scans more that the circle now.

**Comment by coolaj86** [comment]
See https://github.com/AHAAAAAAA/PokemonGo-Map/issues/1621

It looks like you can use `-t 1` and a few other flags and then delete your db.

**Comment by ericpadilla** [comment]
ok thanks!
