### ISSUE TITLE
ImportError: No module named s2sphere

### ISSUE THREAD

**Issue by roberthuttinger** [AHAAAAAAA/PokemonGo-Map#1732]

**Comment by coolaj86** [comment]
Did you do this?

```bash
pip install -r requirements.txt
```

**Comment by NgJason** [comment]
Always run " pip install -r requirements.txt " if you encounter No module errors.

**Comment by roberthuttinger** [comment]
went thru entire process again ran installation and I get :

`Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/fn/f4ytx3x56h790kc6sww0sxw40000gn/T/pip-build-kAOVjU/argparse/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/fn/f4ytx3x56h790kc6sww0sxw40000gn/T/pip-w49fHK-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/fn/f4ytx3x56h790kc6sww0sxw40000gn/T/pip-build-kAOVjU/argparse/`
