### ISSUE TITLE
Pokemon No Longer Appearing 15-20 minutes

### ISSUE THREAD

**Issue by Chizley** [AHAAAAAAA/PokemonGo-Map#1734]
When I first start up the script, everything works fine, and all Pokemon appear normally. However, after about 15-20 minutes, new Pokemon stop appearing and the old ones start to expire until there is nothing left on the map. Help please?

**Comment by Nitric81** [comment]
This was a common issue but with his latest version I no longer have this problem.

**Comment by Kryakz** [comment]
try moving the orange pin around?

**Comment by medghaim** [comment]
Please please please use the format provided. Takes you 20 seconds, but we have 239 issues and I have to sort through what's worthy, what's a feature request, what's an actual bug. It hinders development! 

Make sure you've updated your branch, and use this to discuss support: https://discord.gg/k58Nn
