### ISSUE TITLE
Installing sound alert on OLD version

### ISSUE THREAD

**Issue by ericpadilla** [AHAAAAAAA/PokemonGo-Map#1738]
I have an old version that i found better but i want to install the sound notification that the new ones have. Could someone guide me? thanks!

**Comment by Sharke** [comment]
You install the sound alert by using the latest version. :)

**Comment by FrostTheFox** [comment]
old version is no longer supported.

**Comment by ericpadilla** [comment]
okay thanks @FrostTheFox !
