### ISSUE TITLE
Can't view from mobile browser

### ISSUE THREAD

**Issue by BrodrickChilds** [AHAAAAAAA/PokemonGo-Map#174]
Usually when I'm hosting something locally I can connect to it from my phone by doing {{ip_address}}:{{port#}}  (ie 192.xxx.x.xxx:3000) but that's not working for the pogo map.  Any idea why?

**Comment by olipayne** [comment]
You need to tell Flask to listen on all hosts, start with command `-H 0.0.0.0`

**Comment by BrodrickChilds** [comment]
Oh awesome, thanks for the quick response
