### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by Arijit11** [AHAAAAAAA/PokemonGo-Map#1742]
Hey there,

I tried the method mentioned and it all went smooth upto this command:
C:\Python27\python runserver.py -a ptc -u xxx -p xxxx -l "Central Park, Manhattan" -st 10

This is where it shows an error "ValueError: No JSON object could be decoded"

Any help would be really good!

**Comment by medghaim** [comment]
Closing. Please, please, please use the format provided in your issue report.

Support questions here: https://discord.gg/k58Nn
