### ISSUE TITLE
india doesn't work

### ISSUE THREAD

**Issue by RedFalconv2** [AHAAAAAAA/PokemonGo-Map#1744]
it doesn't work in india

**Comment by andrewda** [comment]
What's the issue?

**Comment by medghaim** [comment]
I _believe_ niantic started shutting countries out, where it hasn't released.

**Comment by RedFalconv2** [comment]
i'm in bangalore, india and it doesn't work

**Comment by RedFalconv2** [comment]
no pokemon

**Comment by medghaim** [comment]
I believe niantic started shutting countries out, where it hasn't released.

**Comment by RedFalconv2** [comment]
i don't think so

**Comment by medghaim** [comment]
http://timesofindia.indiatimes.com/tech/tech-news/Pokemon-Go-draws-a-blank-in-Kolkata/articleshow/53354876.cms

**Comment by andrewda** [comment]
@medghaim I saw that on Reddit somewhere I think, yea.

**Comment by medghaim** [comment]
It's not us, it's Niantic.

**Comment by JZ6** [comment]
lmfao

**Comment by JZ6** [comment]
bangloreindia pls do the needful arshole @medghaim

**Comment by RedFalconv2** [comment]
is'nt there way to bypass?

**Comment by RedFalconv2** [comment]
why did u edit my comment i'm not from bangalore

**Comment by JZ6** [comment]
RedFalconv2 commented 5 minutes ago
i'm in bangalore, india and it doesn't work

**Comment by RedFalconv2** [comment]
i ment bang lure

**Comment by FrostTheFox** [comment]
works for me in pune, india

**Comment by JZ6** [comment]
lmao fucking tolo

**Comment by RedFalconv2** [comment]
ill just use pokevision

**Comment by Olathurl** [comment]
In soviet, pokevision uses you!
