### ISSUE TITLE
Feature-Request: No location on --server-only

### ISSUE THREAD

**Issue by CorruptComputer** [AHAAAAAAA/PokemonGo-Map#1748]
Is it possible to change it to be so that if no location is specified it just starts as something like this: 
![image](https://cloud.githubusercontent.com/assets/5573038/17081851/0fd62dc6-512e-11e6-8ff1-40b4ff865cdb.png)

And the user could zoom in to where they want?

**Comment by medghaim** [comment]
Closing. Please, please, please use the format provided in your issue report.

Support questions here: https://discord.gg/k58Nn

**Comment by CorruptComputer** [comment]
@medghaim Could you re-open this, I updated my format to match the template.

**Comment by C-5** [comment]
None match the Template
