### ISSUE TITLE
[Question] Using alternate DB

### ISSUE THREAD

**Issue by jsnoble** [AHAAAAAAA/PokemonGo-Map#1750]
I went through the wiki and it wasn't clear,  but i remember reading about there being tickets for mysql support besides sqlite. I was wondering how to enable using mysql (couldn't tell from the list of command line options) because i was planning on running a few searcher processes and a single webserver. Any help on that or an update on the wiki would be great. Thanks for all the hard work, great job!

**Comment by medghaim** [comment]
Sorry to ninja close. But stick to the format. If you feel you can't really fit it into the format, that's a sign you should discuss in https://discord.gg/k58Nn

We're all really friendly there, I swear! :)
