### ISSUE TITLE
Failed Building wheel for MarkupSafe

### ISSUE THREAD

**Issue by nevermoregreater** [AHAAAAAAA/PokemonGo-Map#1751]
When i go to install i'm getting this issue

Command "c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\jake\\appdata\\local\\temp\\pip-build-9l5jrl\\MarkupSafe\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\jake\appdata\local\temp\pip-b7wjaf-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\jake\appdata\local\temp\pip-build-9l5jrl\MarkupSafe\

**Comment by medghaim** [comment]
Closing. Use the format provided when you open an issue.
