### ISSUE TITLE
"Stale" pokemon remain on map

### ISSUE THREAD

**Issue by BrodrickChilds** [AHAAAAAAA/PokemonGo-Map#177]
With the new looping feature (which is awesome!) it seems that "stale" pokemon stay on the map (ones that have expired, even after a loop has run after it should have vanished).

**Comment by medghaim** [comment]
This will be resolved soon with upcoming merges. @sykhro is working on it!

**Comment by BrodrickChilds** [comment]
Awesome!  Keep up the good work gents.  I looked for it in issues and didn't see it already.  I tried to contribute on the first day but real work came up :(.

**Comment by DerScreever** [comment]
this is fixed now
