### ISSUE TITLE
[Re-created] What is the process "fuzzyflakes"? What does it do?

### ISSUE THREAD

**Issue by Schwaitz** [AHAAAAAAA/PokemonGo-Map#1780]
Hello again,

So I'm running many servers, and thus far, I've been using sudo killall -v python2.7 as my "kill switch". I've noticed that there are some lingering processes named "fuzzyflakes" after killing all of the python scripts. What are these processes, and what do they do? Should I kill them as well with my script?

Thanks!

Justin

**Comment by lparkermg** [comment]
Have you searched in google for what it could be and if it's any relation to python itself?

**Comment by Schwaitz** [comment]
@lparkermg For some strange reason, I thought it had something to do with this project. I have some recollection of going to the repo and seeing the word, but I guess that must have been my imagination. Closing now.
