### ISSUE TITLE
can't access the web page

### ISSUE THREAD

**Issue by tesarwijaya** [AHAAAAAAA/PokemonGo-Map#1797]
i run it on debian,
i can run the runserver.py properly but when i tried to see the web page it refuse the connection.
help

**Comment by BlazeMuisNL** [comment]
Are you getting any errors? If so, please paste them here.

Are you also sure that no firewall is blocking the port?

**Comment by medghaim** [comment]
Closing. Please follow the provided format when submitting an issue. Thank you!
