### ISSUE TITLE
-i IGNORE option seems to have stopped working

### ISSUE THREAD

**Issue by BrodrickChilds** [AHAAAAAAA/PokemonGo-Map#180]
TSIA

**Comment by favll** [comment]
It still works for me. Are you running the newest commit? Are you using it correct:
Usage: `-i rattata,spearow,pidgey`

**Comment by BrodrickChilds** [comment]
Yeah, I should be.. Let me see if there's a new version in the last 5 minutes
There was, let's see if that fixes it.

**Comment by BrodrickChilds** [comment]
UPDATE: seems the commit between 10 and 5 minutes ago fixed it.  Thanks!
