### ISSUE TITLE
[INFO] Waiting 100 seconds before beginning new scan.

### ISSUE THREAD

**Issue by roflinger** [AHAAAAAAA/PokemonGo-Map#1800]
Any idea how I can change this to 5 seconds or 0 ? 
Don´t wanna  wait 100 seconds. might decide to get a pokemon or not :(

**Comment by LiquidzDEV** [comment]
In your Command Line you must have something like -sd 100, change it to something lower (100 are the seconds)

**Comment by roflinger** [comment]
haha lol - stupid thx
