### ISSUE TITLE
Reading Only First Word of Location

### ISSUE THREAD

**Issue by sheikhsabayyal** [AHAAAAAAA/PokemonGo-Map#1807]
Whenever the location is entered, if it includes more than word. the runserver.py gives error. 

e.g. I entered Manhattan, New York

usage: runserver.py [-h] [-se] [-a AUTH_SERVICE] [-u USERNAME] [-p PASSWORD]
                    [-l LOCATION] [-st STEP_LIMIT] [-sd SCAN_DELAY] [-dc]
                    [-H HOST] [-P PORT] [-L LOCALE] [-c] [-d] [-m] [-ns]
                    [-k GMAPS_KEY] [-C] [-D DB] [-t NUM_THREADS]
runserver.py: error: unrecognized arguments: New York

Works with only a single word like Manhattan

Even if I get it work with only Manhattan, from the local host, changing map doesn't work.

**Comment by Pedrock** [comment]
Use quotation marks (").

**Comment by Skullmonkey** [comment]
Have you wrapped it in quotation marks? 

-l "New York"

**Comment by sheikhsabayyal** [comment]
I tried that couple of times before for like an hour continuously, it showed the same error, for some reason it just worked now. 

Thanks!

**Comment by sheikhsabayyal** [comment]
Again the same error. 
python runserver.py -a ptc -u xxxxxx -p xxxxxx -l “Brooklyn Museum, Brooklyn” -st 10
usage: runserver.py [-h] [-se] [-a AUTH_SERVICE] [-u USERNAME] [-p PASSWORD]
                    [-l LOCATION] [-st STEP_LIMIT] [-sd SCAN_DELAY] [-dc]
                    [-H HOST] [-P PORT] [-L LOCALE] [-c] [-d] [-m] [-ns]
                    [-k GMAPS_KEY] [-C] [-D DB] [-t NUM_THREADS]
runserver.py: error: unrecognized arguments: Museum, Brooklyn”

**Comment by Pedrock** [comment]
You seem to be using “ instead of "

**Comment by sheikhsabayyal** [comment]
how to resolve it?

**Comment by Pedrock** [comment]
python runserver.py -a ptc -u xxxxxx -p xxxxxx -l "Brooklyn Museum, Brooklyn" -st 10

**Comment by sheikhsabayyal** [comment]
That must be a bug in Mac Notes app. I saved the line there and edit it with new locations. It converts  "" to  “” automatically. 

Thanks though
