### ISSUE TITLE
Duplicated pokemon over multiple instances

### ISSUE THREAD

**Issue by kara71** [AHAAAAAAA/PokemonGo-Map#1819]
I currently have a Debian server running with 3 instances on 3 different ports (launched with the exact same command except the -P), and all three instances are set to different locations.
The problem is, whene a rare (=notifications enabled) pokémon spawns on an instance, all three get notifications for it, even if it's really far away. I can also see on the /mobile page that pokémon are common to all three (but the distances are correct, like 10 poké at <1km, and 20 poké at >500km).
Thanks for all the good work, keep it up ! :)

**Comment by cNyhuus** [comment]
Do you use seperate .db files, or do you run from the same?

Im no expert, but i think that, if you use the same .db file all instances will get the update, as they read from the same .db file, unless you have specified otherwise (-D // --db)

**Comment by kara71** [comment]
Alright thanks a lot ! I didn't find the db option very well documented, but maybe I scrolled past it.
