### ISSUE TITLE
local variable 'poke' referenced before assignment

### ISSUE THREAD

**Issue by Vivicus** [AHAAAAAAA/PokemonGo-Map#182]
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discordapp.com/invite/qbpVH6b).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System: Windows 10 x64, Intel

Installed version of Python:
Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)] on win32

### Steps to reproduce
1.  Install latest from git repo
2. Run "pip install -r .\requirements.txt" in powershell
3. .\example.py -a ptc -u rutabagaman -p [snipped] -l "[snipped]" -st 10

### What have you tried?
1.  Literally ran it three times just to confirm the bug was reproducible.  Have not attempted to debug yet

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

[-] register_background_thread called
[-] register_background_thread: not running inside Flask so not starting thread
 * Restarting with stat
[-] register_background_thread called
[-] register_background_thread: initial registration
 * Debugger is active!
[+] Locale is en
 * Debugger pin code: 333-147-751
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[!] Your given location: [Snippped]
[!] lat/long/alt: [Snipped]
[!] PTC login for: rutabagaman
[+] RPC Session Token: [snipped, because session token reveals are bad!]
[+] Received API endpoint: https://pgorelease.nianticlabs.com/plfe/183/rpc
[+] Login successful
[+] Username: RutabagaBro
[+] You started playing Pokemon Go on: 2016-07-17 14:15:48
[+] POKECOIN: 0
[+] STARDUST: 100
[-] looping: step 0 of 100
Completed: 0.0%
[-] looping: step 1 of 100
Completed: 1.0%
[-] looping: step 2 of 100
Completed: 2.0%
[-] looping: step 3 of 100
Completed: 3.0%
[-] looping: step 4 of 100
Completed: 4.0%
[-] looping: step 5 of 100
Completed: 5.0%
[-] looping: step 6 of 100
Exception in thread search_thread:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\pogomap\example.py", line 564, in main
    pokemonsJSON, ignore, only)
  File "C:\pogomap\example.py", line 627, in process_step
    disappear_timestamp = time.time() + poke.TimeTillHiddenMs \
UnboundLocalError: local variable 'poke' referenced before assignment

**Comment by DerScreever** [comment]
One of the best bug reports i saw.

**Comment by Vivicus** [comment]
Are there any additional logs I can get you that you guys generate?

**Comment by DerScreever** [comment]
nah dont needed i think
the error is clear :-)

"C:\pogomap\example.py", line 627, in process_step disappear_timestamp = time.time() + poke.TimeTillHiddenMs \ UnboundLocalError: local variable 'poke' referenced before assignment

**Comment by Vivicus** [comment]
Okay, just making certain.  I could probably dig through the py myself to find it but coming up to speed on Flask given that I don't know it at all would be painful.

**Comment by aidanhs** [comment]
https://github.com/AHAAAAAAA/PokemonGo-Map/commit/60864bc29c8904dd819c6c14ce8ef840fa536f46#diff-3b5e31446f546cea5285cfd44d32d046L627

Bad indenting which needs reverting I guess (untested since I'm not using this). Possible workaround - use 60864bc29c~1.

**Comment by Znuff** [comment]
Same thing on Ubuntu 14.04, x64, Python 2.7.6.

Happens on Step 5/100.

**Comment by michi0987** [comment]
Same on windows 10 python 2.7.11 . Happens on first step

**Comment by sykhro** [comment]
Tried latest commit?

**Comment by Dmurph24** [comment]
The issue is still here

**Comment by Vivicus** [comment]
Latest (Commit 00b9fdb4d89b26ed65d98b9561b0a5b3be12e9b9) does not appear to have resolved.

**Comment by cjboo** [comment]
Lines 637:651 need to be brought into scope. (indented one) That solved this issue for me.

**Comment by Vivicus** [comment]
Can confirm CJBoo's fix.  Offending code fix as follows:

`    for poke in visible:
        pokename = pokemonsJSON[str(poke.pokemon.PokemonId)]
        if args.ignore:
            if pokename.lower() in ignore:
                continue
        elif args.only:
            if pokename.lower() not in only:
                continue

        disappear_timestamp = time.time() + poke.TimeTillHiddenMs \
            / 1000

        if args.china:
            (poke.Latitude, poke.Longitude) = \
                transform_from_wgs_to_gcj(Location(poke.Latitude,
                    poke.Longitude))

        pokemons[poke.SpawnPointId] = {
            "lat": poke.Latitude,
            "lng": poke.Longitude,
            "disappear_time": disappear_timestamp,
            "id": poke.pokemon.PokemonId,
            "name": pokename
        }`

**Comment by Vivicus** [comment]
Closing since it appears to be fixed tentatively.

**Comment by Znuff** [comment]
This broke credentials now.

**Comment by AndrewFrauens** [comment]
It looks to me like lines 657-671 could be indented to fix this problem.  Could someone else look at that?
