### ISSUE TITLE
Daily Google maps API request limit reached (enable user defined api keys)

### ISSUE THREAD

**Issue by Temetz** [AHAAAAAAA/PokemonGo-Map#183]
### Environment info
Operating System:
Ubuntu 14.04
Installed version of Python:
2.7.6

### Steps to reproduce
1. Reload http://127.0.0.1:5000
2. Map does not load / displays an error.
3. Check console.

More details: https://developers.google.com/maps/faq#usagelimits?utm_referrer=v3

### What have you tried?
1. Should change to user defined Google Maps API key so users wont consume developers quota.

### Logs or other output that would be helpful
https://developers.google.com/maps/faq#usagelimits?utm_referrer=v3

**Comment by BlayzerQ** [comment]
Confirm.

**Comment by hhu94** [comment]
I'm not experiencing this issue. I wonder why that is?

**Comment by Plop** [comment]
Experiencing this issue too.

**Comment by Temetz** [comment]
I think we are just barely on the edge of the request limit.

Current workaround is:
1. Go to: https://console.developers.google.com/
2. Enable Google Maps Javascript API
3. Generate yourself a browser javascript api key
4. paste the key to example.py where it says `GOOGLEMAPS_KEY = 'yourapikeyhere'`

**Comment by HenrySia** [comment]
Thanks for the suggested workaround @Temetz. I'm trying it now.

**Comment by Trozz** [comment]
I think it would be better to have this either coming from a settings file or as an arg

**Comment by JZ6** [comment]
will be in a setting file soon

**Comment by hhu94** [comment]
@JZ6 Isn't it already in credentials.json?
