### ISSUE TITLE
Amount of threads don't have a lot of impact.

### ISSUE THREAD

**Issue by TheReaperr** [AHAAAAAAA/PokemonGo-Map#1830]
Right now it starts <amount of threads> steps at the same time, then upserts the results and start the steps all at the same time again.

I decided to check out how many threads was fastest to do a -st 5 scan and I noticed that from 5 threads onward, the total scantime doesn't decrease.

Why don't the threads start scanning the next step after insterting instead of waiting for all threads to finish upserting?

**Comment by chuyskywalker** [comment]
It's kind of a moot point right now since having multiple threads causes fewer pokemon to show up. Hitting the servers that fast for a single user causes scans to not work right.

**Comment by ghormoon** [comment]
this is solved here https://github.com/AHAAAAAAA/PokemonGo-Map/pull/1835

**Comment by TheReaperr** [comment]
Oh wow that works amazing!
