### ISSUE TITLE
Import Error: No Module Named Cryptodome.PublicKey

### ISSUE THREAD

**Issue by alexanderrock** [AHAAAAAAA/PokemonGo-Map#186]
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discordapp.com/invite/qbpVH6b).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System: Linux Mint 17.3 Rosa

Installed version of Python: 2.7.6

### Steps to reproduce
1. python example.py -a ptc -u USERNAME -p PASSWORD -l "Meersburg, DE" -st 5 -H localhost -P 8000
2.
3.

### What have you tried?
1.

### Logs or other output that would be helpful
Traceback (most recent call last):
  File "example.py", line 28, in <module>
    from gpsoauth import perform_master_login, perform_oauth
  File "/usr/local/lib/python2.7/dist-packages/gpsoauth/__init__.py", line 4, in <module>
    from . import google
  File "/usr/local/lib/python2.7/dist-packages/gpsoauth/google.py", line 4, in <module>
    from Cryptodome.PublicKey import RSA
ImportError: No module named Cryptodome.PublicKey

**Comment by medghaim** [comment]
Give it the ol' one-two:

`pip install pycryptodome`

**Comment by alexanderrock** [comment]
Tried, but it can't be compiled

Failed building wheel for pycryptodome

Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-VyB93F/pycryptodome/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-mRy7zs-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-VyB93F/pycryptodome/

**Comment by medghaim** [comment]
"It supports Python 2.4 or newer, all Python 3 versions"

You're 2.7 yeah?

**Comment by alexanderrock** [comment]
python -V
Python 2.7.6

**Comment by nakami** [comment]
when i installed the requirements today, some of the got moved to the python 2.6 directory. you just have to copy them over. 

i did `pip install -r requirements.txt --user` and the some of the folders ended up in ~/lib/python2.6  instead of ~/lib/python2.7

**Comment by Vivicus** [comment]
@alexanderrock , try the following command:

pip -V (Casing is important, here!)

It should return both which version of pip it is running, and where it is running from.  If you have multiple versions of Python installed and your PATH variables are wonky, this could be an issue.

**Comment by alexanderrock** [comment]
Have installed python-dev and then "pip install pycryptome and pycryptdomex and it worked
