### ISSUE TITLE
No Gmaps api key

### ISSUE THREAD

**Issue by laemoy** [AHAAAAAAA/PokemonGo-Map#1865]
Command show no gmaps api key entered. So i followed instruction but when i open the web that with https://console.developers.google.com  , it shows nothing on my google chrome( a white screen).

is there any other way to get that key?

**Comment by Ayysir** [comment]
@laemoy https://console.developers.google.com/apis/credentials

**Comment by laemoy** [comment]
@Ayysir  still not working with whole black screen in chrome, i tried log out my google account first and click that web link and log in, but it is same with nothing shown. I also unable all extensions.

**Comment by Sejadis** [comment]
well easiest solution would probably be to just use an other browser

**Comment by laemoy** [comment]
@Sejadis  yes im using my ipad right now witch is working, my IE on my computer is not working either
