### ISSUE TITLE
Location change does not stop current scan

### ISSUE THREAD

**Issue by 123456abcdef** [AHAAAAAAA/PokemonGo-Map#1874]
I guess since commit [d4a5d16](https://github.com/AHAAAAAAA/PokemonGo-Map/commit/d4a5d169941f37f63ffdc07301f055569ab49748) the change of the location does not stop the current scan as before, even though the log messages are printed in the console:
> [        app] [   INFO] Changing next location: xx.xxx,xx.xxx
> [     search] [   INFO] New location found. Starting new scan.

Can someone confirm this?

Also you could get rid of the constant output
> [     search] [   INFO] Search queue depth is: 99

## Expected Behavior
Change the location marker position by dragging / entering new location in the options, current scan should be interrupted and new scan at new location should start.

## Current Behavior
Location change is detected, but old location is still scanned (verified by enabling green circle overlay). At some (random?) point scan starts at new location.

## Possible Solution
?

## Steps to Reproduce (for bugs)
1. Start app.
2. Enable scanned area overlay.
3. Change location.
4. Check if new location gets scanned.

## Your Environment

* Version used: most recent / pulled before
* Environment name and version (e.g. Python 2.7): Firefox
* Operating System and version (desktop or mobile): OSX

**Comment by jfabri63** [comment]
Can confirm it isn't working anymore, it's a lot faster but you cant change :'(

**Comment by 2-m** [comment]
Yeah, it doesn't seem to interrupt the scan anymore, and I'm not sure at what point it swaps over

**Comment by Danm72** [comment]
I believe the following line in map.js is the error
`        $.post("next_loc?lat=" + loc.lat() + "&lon=" + loc.lng(), {}).done(function (data) {
`

**Comment by AHAAAAAAA** [comment]
#1927 fix?

**Comment by wesleytsai** [comment]
^ Yeah, it should fix it. I assume it's the same issue as #1921

**Comment by 123456abcdef** [comment]
Yes fixed for me! I close this then. Thx!
