### ISSUE TITLE
Pokemon and gyms appearing but not existing ingame. Pokemon with 2+ hours of spawn time.

### ISSUE THREAD

**Issue by Plop** [AHAAAAAAA/PokemonGo-Map#1876]
## Current Behavior

Having Pokemon with 2+ hours of spawn time. These Pokemon are not present in the game.
![](http://img15.hostingpics.net/pics/378665Bugdenoinoir.png)

Having Gyms that don't exist.
![](https://uploads.autrui.fr/2016-07-24_21-11-43.png)

Using MySQL.

## Steps to Reproduce (for bugs)

1. Launched webserver with python runserver.py with MySQL and 4 threads.
2. Open the map
3. Sometimes see Gyms and Pokemon that are not there. Pokemon have 2+ hours of spawn time. Never spawned, never will.

## Your Environment

* Version used: 
develop b3af047
commit 2c04f78b7977c1a9caf45313cef7710ee843cea3
Author: pyr0ball <pyroballpcs@gmail.com>
Date:   Sun Jul 24 02:13:20 2016 -0700

* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): Debian

**Comment by Dimatert9** [comment]
Update local time on your server host.

**Comment by Plop** [comment]
The local time on my server is already up-to-date.
I'm not sure of what I should do.

**Comment by Lexazan** [comment]
Are you using -m (mock mode) switch? If yes, it will load a bulk data in circle near your start location.

**Comment by Plop** [comment]
Oh, well. Yes, I'm using it. So, I just shouldn't use it ?
I've launched the script with the -m mode, but the fake gyms are still appearing. Should I erase the MySQL db ?
Is there a PR to resolve this bug ?
Thanks.
