### ISSUE TITLE
Impossible to access from WAN

### ISSUE THREAD

**Issue by FlorentDC** [AHAAAAAAA/PokemonGo-Map#1877]
Hey, that's weird.

I'm following this repo for a while, and i've implemented a lot of things from the pull requests, I think that I understand how this things work, but since the v2 I can't access the map from the WAN.

I've tried to change the configs and run with -se, but the map is unreachable, same with -H & -P arguemnts, same with Host and Port hard coded, and same when i change the 'default' value in pogom/utils.py.

I tried to retry from the begining 3 times (deleting everything and retrying), but nothing 

I search in issues and it seems l'ike I'm the only one with this bug hm ?
If someone would have an idea, or somewhere to hard-code it in a file, that would be great !

Excuse my english, I'm French (:

**Comment by Animosity** [comment]
This is a network configuration issue (your unique gateway/router combination, and/or your server firewall configurations are at fault).

**Comment by fust** [comment]
Are you behind a NAT router? If so, make sure you forwarded the specified port to the machine running the PokemonGo-map instance.

**Comment by FlorentDC** [comment]
I thought that it wasn't due to NAT or something else, because accessed it well when I was using the master & dev branches, but if both of you tell it to me, i'll dig this way, thanks guys and sorry and sorry for that false positive

**Comment by Beeneh** [comment]
So i've got the same issue. I try to run the following command (anonymized of course): 

`python runserver.py -u username -p password -k [api key] -l "[location]" -st 10 -H 1.2.3.4 -P 5000`

and it returns: 

`2016-07-24 21:35:34,196 [  runserver] [   INFO] Parsed location is: [location] (lat/lng/alt)
2016-07-24 21:35:34,196 [     search] [   INFO] Map iteration: 0
2016-07-24 21:35:34,196 [     search] [   INFO] Attempting login to Pokemon Go.
Traceback (most recent call last):
  File "runserver.py", line 83, in <module>
2016-07-24 21:35:34,196 [   auth_ptc] [   INFO] PTC login for: [username]
    app.run(threaded=True, debug=args.debug, host=args.host, port=args.port)
  File "D:\Python27\lib\site-packages\flask\app.py", line 843, in run
    run_simple(host, port, self, **options)
  File "D:\Python27\lib\site-packages\werkzeug\serving.py", line 694, in run_simple
    inner()
  File "D:\Python27\lib\site-packages\werkzeug\serving.py", line 656, in inner
    fd=fd)
  File "D:\Python27\lib\site-packages\werkzeug\serving.py", line 544, in make_server
    passthrough_errors, ssl_context, fd=fd)
  File "D:\Python27\lib\site-packages\werkzeug\serving.py", line 464, in __init__
    HTTPServer.__init__(self, (host, int(port)), handler)
  File "D:\Python27\lib\SocketServer.py", line 417, in __init__
    self.server_bind()
  File "D:\Python27\lib\BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "D:\Python27\lib\SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "D:\Python27\lib\socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 10049] The requested address is not valid in its context
Exception in thread search_thread (most likely raised during interpreter shutdown):`

running the same command and using -H localhost works fine, as would omitting it altogether, but I can't access it externally if I do (of course). I used to be able to do this on the previous version.

I did reinstall python, and made sure that the old python install was removed. did I miss some setting elsewhere?

**Comment by fust** [comment]
Could you try to bind the server to IP 0.0.0.0 (i.e. all interfaces) instead of a specific one and see if that resolves the problem?

Do note that the IP to bind to must belong to the machine running the server, not your router/modem's public IP.

**Comment by fust** [comment]
Just tried some things to see if the tracebacks would match, this exact error happends when an invalid IP is specified. I think a more useful message should be displayed instead of an exception since a lot of users can't make sense of these errors

**Comment by Beeneh** [comment]
ah, running it on all interfaces did the trick! thanks a bunch!

**Comment by FlorentDC** [comment]
That worked too, thanks ! :)

**Comment by guysoft** [comment]
Can you guys give a more detailed explernation on how you got that to work? I tried adding 0.0.0.0 in config.ini misc section and it didn't help  (using develop branch).
