### ISSUE TITLE
Documentation on search threads argument?

### ISSUE THREAD

**Issue by adrianocr** [AHAAAAAAA/PokemonGo-Map#1883]
I notice there's an option to pass the number of search threads to the app. Is it based on CPU cores? Workers?

I see that the default is one search thread. If I set it to 2, or 3, or 4, what can I expect?

**Comment by shivampaw** [comment]
It will use more CPU because it is doing more at once. However some people have found using more than 1 thread causing some pokemon to not show.

Also, the highter the threads the faster it searches.
