### ISSUE TITLE
Feature Request - Show only lured pokestops

### ISSUE THREAD

**Issue by ngg** [AHAAAAAAA/PokemonGo-Map#1895]
There are too many pokestops in larger cities, it would be really nice to see only the lured ones.
This could be either an independent switch or it could be merged together with the lured pokemons switch.

**Comment by timikx** [comment]
I would also change size of pokestops to smaller or different icon

**Comment by tkSimon** [comment]
@timikx Different icons are on their way, I think: #1829

**Comment by ngg** [comment]
Merged: https://github.com/AHAAAAAAA/PokemonGo-Map/pull/1982
