### ISSUE TITLE
Pokemon not appearing on map

### ISSUE THREAD

**Issue by bananamanpoke** [AHAAAAAAA/PokemonGo-Map#1905]
Pokemon are no showing up on the UI when I run the code, but it shows that the code is finding them and upserting. 

## Expected Behavior
It should show the pokemon that it is upserting. 

## Current Behavior
No pokemon are appearing when there should be.

## Your Environment

* Version used: master
* Environment name and version (e.g. Python 2.7): python 2.7
* Operating System and version (desktop or mobile): desktop windows 7

**Comment by callmebackdraft** [comment]
have you openened the option menu (top left of screen) en activated the Pokemon slider

**Comment by fidian** [comment]
I'm not sure if you want to be a bit adventurous, but I couldn't get the `master` branch to work, however switching to the `develop` branch solved all of my problems.

**Comment by mst1903** [comment]
I have the same issue. when i hover around in the map it shows me the popup dialogs for the pokemon, but i can't see the pokemons themselves

**Comment by shadow7412** [comment]
Who thought that change to activate the pokemon slide was a good idea?
It definitely should be on by default.

**Comment by mst1903** [comment]
It is ON in my case, but they still don't show up on the map

**Comment by mst1903** [comment]
![image](https://cloud.githubusercontent.com/assets/6215167/17087509/1b12c972-520c-11e6-8fe8-cc1758a36a99.png)

**Comment by KouhaiKiller** [comment]
I'm still having this issue. This is what shows up for me: http://puu.sh/qdhTC.png

**Comment by bananamanpoke** [comment]
Yea I have the pokemon slider on. I don't see any invisible pokemon when I hover though.

**Comment by lgcjoker** [comment]
I also am having the same issue.  When I bring up the debug windows this is what I see.
![untitled](https://cloud.githubusercontent.com/assets/16456136/17088363/b9e317d2-51df-11e6-8146-485f6817e9d2.png)

**Comment by invisiblek** [comment]
This is almost certainly due to caching issues after we went to the sprite. Closing this as there's no way its still an issue (if it is, its something else, the code base is not exhibiting these issues currently)
