### ISSUE TITLE
No markers appear on Mobile browsers.

### ISSUE THREAD

**Issue by tashonleo** [AHAAAAAAA/PokemonGo-Map#1907]
## Expected Behavior
Pokemon, stops, gyms etc should appear on the map as they do on desktop. It worked on my early versions!

## Current Behavior
Everything works fine on desktop but the map is completely empty on my iPhone. No markers or anything.

## Steps to Reproduce (for bugs)
Setup instances as per instructions.
Visit url on mobile device.

https://tashon-pgo.herokuapp.com/ <--- New version, empty map on mobile.
http://e2de9901.ngrok.io/ <--- Old version, works fine.

## Context
I'd like to be able to use this while out and about. Yes, the old version works fine but the new version doesn't.

## Your Environment
* Version used: Master as of 25/07/16 00:48 GMT (19:48 EST)
* Environment name and version (e.g. Python 2.7): Heroku Deployment as well as a Python 2.7 setup on Win 7 locally.
* Operating System and version (desktop or mobile): iOS 9.3

**Comment by Alok-Sharma** [comment]
Your link works fine for me, on mobile. There's a switch for displaying Pokemons in the options menu, are you sure you activated that?

**Comment by Aphit** [comment]
@tashonleo In my experience yesterday and today using this application, I had to use Chrome application on my iphone 6 in order to see any pokemon on the map.  For some reason, Safari wouldn't show them.

**Comment by tashonleo** [comment]
I've found out what's going on! The newer versions don't work well with incognito mode/in private browsing on mobile browsers it seems. Switched back to normal browsing and all is well!

I'll take a look at the html tomorrow and see if I can get it to work on both modes.

**Comment by Aphit** [comment]
@tashonleo I had that problem on 1.0 as well and it fixed it, but it seems like Safari still does not work well on this version on my iPhone 6.

**Comment by kgurnani96** [comment]
@tashonleo this happens because iOS safari (or well any other safari for that matter) doesn't allow localstorage to be used in private/incognito mode. A quick look at the console in the safari debugger shows this `[Error] QuotaExceededError: DOM Exception 22: An attempt was made to add something to storage that exceeded the quota.` thrown.

**Comment by invisiblek** [comment]
that patch should allow the javascript to continue if localStorage isn't supported in your browser (which apparently is the case with safari + incognito?)

please test
