### ISSUE TITLE
Clicking on 'options' a second time doesn't collapse the options back on ios safari

### ISSUE THREAD

**Issue by kgurnani96** [AHAAAAAAA/PokemonGo-Map#1920]
A second click on 'options' should collapse all the options appearing

## Expected Behavior
- click 'options'
- options appear
- click 'options' again
- options collapse 

## Current Behavior
- click 'options'
- options appear
- click 'options' again
- nothing

## Possible Solution
I'll update when i get time to check it more

## Steps to Reproduce (for bugs)
1. click 'options'
2. options appear
3. click 'options' again

## Context
idk, expected behavior?

## Your Environment
* Version used: safari 9~ (idk really)
* Environment name and version (e.g. Python 2.7): python 2.7
* Operating System and version (desktop or mobile): iOS 9.3 iphone 6s

**Comment by swtrpeter** [comment]
Does not collapse on android using chrome either.
