### ISSUE TITLE
Moving marker to change location does not stop scan of previous location causing delay in new location scan

### ISSUE THREAD

**Issue by swtrpeter** [AHAAAAAAA/PokemonGo-Map#1921]
## Expected Behavior
After moving marker to new location on the map the current scan that was in process does not stop. The new location scan will not start until the last scan of the previous location has finished.

## Current Behavior
After moving marker to new location on the map the current scan that was in process does not stop. The new location scan will not start until the last scan of the previous location has finished.

## Possible Solution
Unknown

## Steps to Reproduce (for bugs)

1.Open map once scan has started drag marker to new location 
2. open scanned locations and watch it continue to scan previous location
3.
4.

## Your Environment
python 2.7
Desktop and mobile
Windows 7 and android using chrome browser

**Comment by tkSimon** [comment]
Changing location should clear the search queue, which it currently doesn't.

**Comment by tkSimon** [comment]
Are you using master or develop branch?

**Comment by swtrpeter** [comment]
develop

**Comment by tkSimon** [comment]
@wesleytsai Will you create a PR?

**Comment by wesleytsai** [comment]
Hahahah it's one line, but okay
