### ISSUE TITLE
Map doesn't display its just a white screen with title and options menu

### ISSUE THREAD

**Issue by f1onx** [AHAAAAAAA/PokemonGo-Map#1923]
I used a former version that still ran the example.py and everything worked perfect.  Upon trying to update to a more recent version all I get when loading the map is the title bar and the options menu and a completely blank map area (just white screen not even a map).  Any ideas how to fix it?

**Comment by jmccorm** [comment]
Does this describe the problem?
https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Google-Maps-API:-a-brief-guide-to-your-own-key

**Comment by medghaim** [comment]
Closing! Please use the format provided when you create the issue. It's there to help everyone! Reopen with the proper format, please.
