### ISSUE TITLE
Map doesn't display.  Just white screen and title/options bar

### ISSUE THREAD

**Issue by f1onx** [AHAAAAAAA/PokemonGo-Map#1926]
Map doesn't display.  Just white screen and title/options bar
http://prnt.sc/bx3hmn
## Expected Behavior

Map should display an actual map with locations on it.
## Current Behavior

I am getting a white screen where the map should be and can only see the title/options bar.  It looks like it says "login details here" up at the top under the menu bar
## Possible Solution

Unknown as a previous version using example.py worked fine
## Context

I am unable to use the map as intended or even see a map displayed
## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): Win 10

**Comment by megahambone** [comment]
IE and Edge no longer work on the most current branch. Chrome does and Firefox does, just an FYI.

**Comment by f1onx** [comment]
Welp I feel like a schmuck.  Works in chrome.  Thanks!
