### ISSUE TITLE
Heroku Deployment

### ISSUE THREAD

**Issue by ericpadilla** [AHAAAAAAA/PokemonGo-Map#1942]
Can anyone guide me through the manual heroku deployment? The easy button version does not remove expired pokemon automatically. Thanks!

**Comment by c133** [comment]
it...does...though?

**Comment by Ayysir** [comment]
?? expired pokemon removal is dealing with code not heroku...which is a free server....

**Comment by ericpadilla** [comment]
I clicked wiki>heroku deployment> then i choose the easy heroku deployment but i think that version does not remove expired pokemon in the browser unless i refresh the page.

**Comment by ericpadilla** [comment]
Nevermind, now it is removing expired pokemon perfectly. Thanks guys!
