### ISSUE TITLE
Pokemon missing even with -t 1

### ISSUE THREAD

**Issue by alvingmc** [AHAAAAAAA/PokemonGo-Map#1944]
Like many people have mentioned some pokemon are missing
I have tested this with -t 1 and it still missed a pokemon that was 1 block away from me.

It was on my nearby tracker on Pokemon Go and it also showed up on pokevision. I also went to that area and the Gengar was there.  It has around 5 minutes left on the timer when I checked the map..

## Expected Behavior
Gengar should have been found on the map with the   -t 1 option on as it was only 1 block away from me

## Current Behavior
Some pokemon are not found even with the -t 1 option as others have mentioned as a fix

## Possible Solution
A fix to the algorithm?

**Comment by ericpadilla** [comment]
it missed at most 3 pokemon for me.

**Comment by rjwestman** [comment]
it is missing tons of pokemon for me too =(

**Comment by ericpadilla** [comment]
I think the best solution we have now is only adding -t 1 to the command

**Comment by jheath** [comment]
I was experiencing an issue where no pokemon were displaying at all.  I just realized the cause was my server time being about 16 minutes ahead.  I reset the time using ntpdate and voila! Pokemon found.
Might be of help to someone else.

**Comment by wcastello** [comment]
Please try the latest develop version and reopen if the issue persists.
