### ISSUE TITLE
Commit 20a927a redundant with PR #1484 (geolocation feature is now implemented twice)

### ISSUE THREAD

**Issue by frdmn** [AHAAAAAAA/PokemonGo-Map#1950]
## Possible Solution

Since #1484 is more intuitive I think 20a927a429386f2c88a40de55d05e8e184606974 should be reverted (at least the geolocation bits)

/cc @AHAAAAAAA

**Comment by AHAAAAAAA** [comment]
#725 adds ability to search based on new geolocation, but I agree that this is redundant. Specifically, why is there a toggle in options for this? It's very unintuitive.

**Comment by invisiblek** [comment]
Well, I think the toggle in options keeps it on your, follows you around. The icon on the map is a one shot "jump to my location".

With the toggle on, we should hide the icon imo.

Semi-related: "Geolocation" vs "Change Your Location" need some clarifying, its no immediately obvious what they do. Does it change the scan location or the spot on the map you're currently looking at? (I know the answer to this, but a new user wouldn't)

**Comment by invisiblek** [comment]
I have an idea for this, I'll get something up shortly

**Comment by invisiblek** [comment]
what about something like this? https://github.com/AHAAAAAAA/PokemonGo-Map/pull/2357

**Comment by AHAAAAAAA** [comment]
Works for now, closing this.
