### ISSUE TITLE
Lured Pokemon toggle

### ISSUE THREAD

**Issue by AHAAAAAAA** [AHAAAAAAA/PokemonGo-Map#1952]
Lured Pokemon switch incredibly buggy. Toggling often:

* turns on all wild pokemon.
* does nothing, unless display pokestops also enabled.

I think it's also a pointless switch. It should be on by default. Whenever people have 'Show wild pokemon toggled', then that should include the Lured Pokemon by default.

**Comment by invisiblek** [comment]
https://github.com/AHAAAAAAA/PokemonGo-Map/pull/1995
