### ISSUE TITLE
Only show lured pokestops

### ISSUE THREAD

**Issue by AHAAAAAAA** [AHAAAAAAA/PokemonGo-Map#1954]
We had this feature in v1.0 and it was never reintroduced. It's been getting requested a lot. Show only pokestops that are currently lured. This could be a checkbox under Show Pokestops toggle, no need for it to be its own toggle.

**Comment by georgo** [comment]
Suggestion can be found in PR #1982

**Comment by AHAAAAAAA** [comment]
Done. #1982
