### ISSUE TITLE
Stop notified icon bounce after given time

### ISSUE THREAD

**Issue by FabianSperrle** [AHAAAAAAA/PokemonGo-Map#1955]
Since #1831 map icons of notified Pokémon bounce, which is nice. Nonetheless I believe that the bouncing should stop eventually, before the 15 minutes run out.

## Expected Behavior

- I get notified of a new Pokémon and click the notification. The map shows the bouncing Pokémon for another 60 seconds, then the bouncing stops.
- I don't react when I get the notification, the bouncing stops after 120 seconds.

## Current Behavior

Bouncing does not stop until the Pokémon is removed from the map.

## Steps to Reproduce (for bugs)

1. Load map, add a Pokémon to be notified about
2. Wait for it to appear
3. Icon never stops bouncing

## Context

You can't always run to all Pokémon, the remaining bounce animation is distracting and not helpful. 

## Your Environment

* Version used: Latest dev #d7aa801
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): Heroku dyno, affects all end user devices

**Comment by MikeDuister** [comment]
Made a PR in which the bounce animation stops after 3000ms (= 4 bounces)
