### ISSUE TITLE
UnboundLocalError: local variable 'poke' referenced before assignment

### ISSUE THREAD

**Issue by Orrielel** [AHAAAAAAA/PokemonGo-Map#197]
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discordapp.com/invite/qbpVH6b).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System: Win7

Installed version of Python: 2.7.12

### Steps to reproduce
1. Start scanning
2. Randomly happens before scanner hits 10%

### What have you tried?
1. Not catching pokemons

### Logs or other output that would be helpful
Completed: 3.0%
[-] looping: step 4 of 100
Exception in thread search_thread:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "example.py", line 575, in main
    pokemonsJSON, ignore, only)
  File "example.py", line 639, in process_step
    disappear_timestamp = time.time() + poke.TimeTillHiddenMs \
UnboundLocalError: local variable 'poke' referenced before assignment

**Comment by michi0987** [comment]
It has been already reported. https://github.com/AHAAAAAAA/PokemonGo-Map/issues/182

**Comment by Orrielel** [comment]
I just noticed, fuck me for not searching first.

**Comment by Vivicus** [comment]
And fixed in #190 .

**Comment by DerScreever** [comment]
fixed
