### ISSUE TITLE
Why are all the switches are OFF when deploying on heroku ?

### ISSUE THREAD

**Issue by monu11296** [AHAAAAAAA/PokemonGo-Map#1972]
When I used it on my localhost the switches for Pokemons and Gyms are ON whereas other switches are OFF. 
But when I deployed it on Heroku the all the switches were OFF. 

Can someone please help me how can I make all the switches ON or OFF on heroku or in local system.

**Comment by Algent** [comment]
This also true outside of Heroku, if I open the one on my machine from a new browser I get the same result.
Probable cause: All switches have default set to false or are not defined until changed.

**Comment by m0rtem** [comment]
Can also confirm this happens to me.

**Comment by Scildrei** [comment]
I can confirm this too.

**Comment by tiwiz** [comment]
I can confirm it as well

**Comment by medghaim** [comment]
I too can confirm this. Will try looking into it. Help is appreciated, not too familiar with Heroku!

**Comment by Algent** [comment]
#1694 May already be enough to fix this.

**Comment by chuyskywalker** [comment]
Agreed, I don't see this effect with #1694 anymore.
