### ISSUE TITLE
Pokemon removed from map re-appear after zoom change

### ISSUE THREAD

**Issue by Sp4rkR4t** [AHAAAAAAA/PokemonGo-Map#1975]
## Expected Behavior
If you remove a pokemon via it's pop-up dialog box option it should stay removed from the map

## Current Behavior
If you remove a pokemon and then change zoom level the pokemon re-appears

## Possible Solution
No clue guv.

## Steps to Reproduce (for bugs)
1. Select a pokemon
2. Choose remove via it's dialog box and pokemon will disappear
3. Change zoom level
4. Pokemon re-appears.

## Context
Changing the zoom level makes it look like a new pokemon has appeared when it's simply one you have already removed from the map.

## Your Environment

* Version used: develop
* Environment name and version (e.g. Python 2.7): Python 2.7 heroku app
* Operating System and version (desktop or mobile): chrome on windows 10 desktop

**Comment by medghaim** [comment]
> **Possible Solution**
> 
> No clue guv.

Tellin' it like it is! Adding to 2.1.0 milestone.

**Comment by CarlTaylor1989** [comment]
Well spotted!

**Comment by b4card1** [comment]
i can confirm this bug, i noticed it as well in the develop branch

**Comment by invisiblek** [comment]
https://github.com/AHAAAAAAA/PokemonGo-Map/pull/2203
