### ISSUE TITLE
geopy.exc.GeocoderQuotaExceeded: The given key has gone over the requests limit in the 24 hour period or has submitted too many requests in too short a period of time.

### ISSUE THREAD

**Issue by Plop** [AHAAAAAAA/PokemonGo-Map#1978]
Hi,

I'm having issue launching the runserver.py, having this error : 
`geopy.exc.GeocoderQuotaExceeded: The given key has gone over the requests limit in the 24 hour period or has submitted too many requests in too short a period of time.`

Checked on console.developers.google.com, my quota is NOT exceeded. Created another project and another API key, same problem.

Is this a Google related problem or a PTC one ?

Thanks.

![](http://i.imgur.com/RQxnFNn.png)

**Comment by Plop** [comment]
Also tried with a Google account freshly created, with a brand new project and API key from this account, still got the error. Google login for running the script.

So : running the script with Google auth, using a new project and API key from a brand new Google account, still got the error. I git pulled the latest origin develop commit.

**Comment by DerScreever** [comment]
for me it work with ptc and google accounts. running 4 servers with same key. all work good.

**Comment by isnuryusuf** [comment]
same think with me
