### ISSUE TITLE
disappears time

### ISSUE THREAD

**Issue by BlayzerQ** [AHAAAAAAA/PokemonGo-Map#198]
How i can change disappears time to my time zone?

**Comment by Trozz** [comment]
Change the timezone of your system, the time should already be in your local time.

run `date` and check the timezone that comes back

**Comment by vintagesucks** [comment]
It's using the same timezone as the system it's running on. If you run this on a server you have to change the timezone to your local one.

**Comment by volksport** [comment]
+1 all/most servers are running UTC. I intend to run this on a server, not my laptop/pc. You can have it be a setting in the startup or have the frontend handle it.

**Comment by Trozz** [comment]
you can easily change the time on a server, using the local time of the system would be a better idea than attempting to change the time based within the application.

RHEL/Fedora/CentOS
```
sudo ln -s /usr/share/zoneinfo/%Area%/%City% /etc/localtime
```

Debian/Ubuntu
```
sudo dpkg-reconfigure tzdata
```

**Comment by JZ6** [comment]
fixed
