### ISSUE TITLE
What does the geolocation Option do ? 

### ISSUE THREAD

**Issue by salmanhasni** [AHAAAAAAA/PokemonGo-Map#1980]
I m on Dev branch

**Comment by denny99** [comment]
Placing the marker at your own location.

**Comment by salmanhasni** [comment]
Thanks @denny99

**Comment by salmanhasni** [comment]
does it scans my nearby my location too ? @denny99

**Comment by denny99** [comment]
it's scanning like always, depending on the steps configured.

**Comment by salmanhasni** [comment]
Thanks
