### ISSUE TITLE
Is there any chance to view higher level Pokémons with second account?

### ISSUE THREAD

**Issue by wexstorm** [AHAAAAAAA/PokemonGo-Map#1981]
Is there any chance to see higher level Pokémons with a second (fresh) account, or do you have to play with this account to get higher XP?
Or is it a problem of my patience and the server returns all Pokémons wihtout regarding the XP of the logged in user?

Thanks!

**Comment by k33k00** [comment]
The server returns all pokemon. It doesn't matter on your level at all

**Comment by wexstorm** [comment]
Thank you very much!
