### ISSUE TITLE
Pokestops are undefined and show weird informations

### ISSUE THREAD

**Issue by Plop** [AHAAAAAAA/PokemonGo-Map#1984]
Since I git pulled the last develop commit, the Pokestops are really weird

Deleted the MySQL db, but still got this bug.

![](http://i.imgur.com/2ibxbzI.png)

**Comment by FabianSperrle** [comment]
Can confirm this.

**Comment by Yossi** [comment]
could this be related to #1943 ?

**Comment by DerScreever** [comment]
@Yossi yes it is im running latest version before that commit and for me it work.

**Comment by 123456abcdef** [comment]
I guess there is another problem, even though I disabled Pokestops, I get the information bubble if I hover over the position of a Pokestop.

**Comment by DanielVolz** [comment]
I think its a problem with lured pokemons. They don't have an icon and their informations are not correct.

If you disable lured pokemon, the stops are fine.

**Comment by 123456abcdef** [comment]
@DanielVolz You are right, disabling and enableing `Lured Pokemon` fixed that problem!

**Comment by medghaim** [comment]
#1952
