### ISSUE TITLE
Marker still drags when -fl is on

### ISSUE THREAD

**Issue by EdenGottlieb** [AHAAAAAAA/PokemonGo-Map#1996]
## Expected Behavior

When -fl, User should not be able to drag marker - it needs to stay where it is when dragged.
## Current Behavior

When -fl (fixed-location) is set, marker still drags, but upon drop immediatly returns to its original position. This is because of commit #1688 that returns 403 FORBIDDEN from /next_loc.

I tried to fix it by changing the marker's draggable attribute but with no luck, it is for some reason not respected - both 'true' and 'false' values allow the user to drag the marker.

## Your Environment

* Version used: Latest dev 6c01f06
* Environment name and version (e.g. Python 2.7): Python 2.7.10
* Operating System and version (desktop or mobile): Mac OS X, Safari and Chrome

**Comment by philipp-r** [comment]
Already reported https://github.com/AHAAAAAAA/PokemonGo-Map/issues/1701

**Comment by medghaim** [comment]
Closing duplicate.
