### ISSUE TITLE
Will it be possible to scan the map without account?

### ISSUE THREAD

**Issue by houkensjtu** [AHAAAAAAA/PokemonGo-Map#1999]
A very similar Web APP is already online today. I don't how many of you have seen this...
https://pokevision.com/

It seems they didn't open any source code. Interesting thing is, in this Web APP one doesn't even need an account to display the Pokemon, which makes me think, will there be a smarter way to scan the map without account? ( Maybe they are just applying their account in the backend where we couldn't see)

**Comment by Cronick** [comment]
They are using their own accounts in the backend.

**Comment by DerScreever** [comment]
everyone running this code need to set an account for scanning. the users that open then map from someone who host this need no account.

**Comment by houkensjtu** [comment]
@Cronick Yeah that's the most reasonable possibility. But imagine how huge amount of request will be sent out through their account, they may easily catch the server maintainer's eye and get banned soon...

**Comment by swablueme** [comment]
Pokevision probably has a script to autocreate and utilise new accounts.

**Comment by Cronick** [comment]
@houkensjtu Probably, but as you can still see Pokemons, Pokestops and Gyms, while you are soft-banned. There is not really much to do, unless they change so you can't see anything while you are soft-banned, but then the "soft-ban" concept disappears at some points.

**Comment by houkensjtu** [comment]
Yeah anyway those guys did a great job and it's certainly now a better solution for those who don't want to touch the command line. But for us, source code is much more important than game itself :)

**Comment by C-5** [comment]
Sencesation
