### ISSUE TITLE
Scanned Locations does not show up anymore.

### ISSUE THREAD

**Issue by trippyhat** [AHAAAAAAA/PokemonGo-Map#2004]
## Expected Behavior
Turning on Scanned Location should highlight the locations being scanned on the map. This was originally working by showing green circles where the user was currently walking.

## Current Behavior
Scanned location does not show up on the map when turned on.

## Your Environment
python 2.7

**Comment by medghaim** [comment]
Closing. Reopen your issue and fill out the form please. OS? What command did you run? Browser? have you cleared cache?

Please take support questions to: https://discord.gg/Kamn6 
You're more likely to get thorough 1on1 responses there.
