### ISSUE TITLE
Finding spawn locations for pokemon

### ISSUE THREAD

**Issue by commanderjsoc** [AHAAAAAAA/PokemonGo-Map#2009]
## Expected Behavior

This feature would note recent spawns and if many of the same pokemon spawned in the same general place then It would register the stop as a spawn point. The spawnpoint should be saved and pogomap shouldn't have to reregister it when you restart the server.

## Current Behavior

As of right now I know of one spawn point for dratini's. (33.786632, -118.290081) I didn't use pogomap to find this. You can try testing it on this location

## Possible Solution

if there are more than X pokmon of type Y within Z min then:
   add average location as spawnpoint

## Steps to Reproduce (for bugs)

NONE 

## Context

I am trying to find good places to farm certain pokemon

**Comment by roland3** [comment]
Pretty much overlaps with #1056
