### ISSUE TITLE
Pokemons aren't loading on Iphone =(

### ISSUE THREAD

**Issue by aboldin** [AHAAAAAAA/PokemonGo-Map#2013]
Something with memory or what? Any ideas?
![kn35pyuk5ye](https://cloud.githubusercontent.com/assets/14088450/17105350/0a2bd702-52b1-11e6-9ab0-253f4c79a91e.jpg)
![opovljnuf1o](https://cloud.githubusercontent.com/assets/14088450/17105351/0c354c9a-52b1-11e6-94b1-2d5fbed81b31.jpg)
https://zloyboldin.ru:8000/ or https://zloyboldin.ru:8001/

(DON'T ALLOW YOUR LOCATION TO BE DETECTED, OR MAP WILL SCROLL TO YOU)

**Comment by aboldin** [comment]
@andrewda link pls to duplicate? I dont see it

**Comment by andrewda** [comment]
#1628
