### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by vellrya** [AHAAAAAAA/PokemonGo-Map#2015]
My previous issues had been banned( Probably because I did not use the provided template. Okay, try again.

When I run pip install -r requirements.txt I had this (1 pic) error. If I'll try to use Python runserver.py -etc I had error 2. Too most if I start setup.bat. need help)

## Expected Behavior
Map should work)00)

## Current Behavior

![img_20160725_172108](https://cloud.githubusercontent.com/assets/13716114/17105599/9cb6288c-5290-11e6-97cb-c311d39b616c.jpg)
![img_20160725_172216](https://cloud.githubusercontent.com/assets/13716114/17105607/a56d9780-5290-11e6-8b32-70e4d0b63f4e.jpg)

## Steps to Reproduce (for bugs)

1. Nothing

## Your Environment

* Version used:  newest develop
* Environment name and version (e.g. Python 2.7): Python 2.7.12
Operating System and version (desktop or mobile): OS Windows 7.

**Comment by katerynaCh** [comment]
Do you have cyrillic letters in your computer name? This often causes the UnicodeDecodeError in windows

**Comment by vellrya** [comment]
I know this too. But I already rename my computer.

**Comment by dthall43** [comment]
This happens when you are trying to use pip from python 3.5 make sure your python version is 2.7 I would uninstall 3.5 and repair 2.7. Your path variables may also be fudged up.

**Comment by vellrya** [comment]
Thx, but I hadn't Python 3.5 installed. Any other idea?

**Comment by andrewda** [comment]
This is not an issue with PokemonGo-Map.
