### ISSUE TITLE
Map center shifts to SE after refresh

### ISSUE THREAD

**Issue by AHAAAAAAA** [AHAAAAAAA/PokemonGo-Map#202]
New bug, the map center is shifting when I refresh the second time after it starts loading pokemon.

**Comment by AHAAAAAAA** [comment]
Fixed it, it was problem with yang's mods to location scanner algo and map display.

**Comment by towicode** [comment]
@AHAAAAAAAI think the pointer is still on the original location but it seems to me the scan is still shifting to the SE.

**Comment by nickgarvey** [comment]
See my comment on https://github.com/AHAAAAAAA/PokemonGo-Map/issues/231#issuecomment-233512629 for a possible root cause

**Comment by JZ6** [comment]
fixed
