### ISSUE TITLE
Ubuntu digitalocean droplet remote access

### ISSUE THREAD

**Issue by shiznewski** [AHAAAAAAA/PokemonGo-Map#2027]
I have installed pokemogo-map 2.0 and it runs. I only have command line access to my droplet. I have the runserver.py set to -P 5000 -H 0.0.0.0 but when i go to http://dropletip:5000 it doesn't connect. 

I am a linux rookie, do i have to do port forwarding somehow in the IPTABLES?

Any help would be great. Decided to use a droplet so i don't have to use my homepc constantly.

**Comment by Minkey27** [comment]
No, you shouldn't have to port forward or anything. I'm not sure what is going wrong. What is the console outputting? Are you getting errors? You should still be able to get to your droplet and see the map.

**Comment by shiznewski** [comment]
Had to run out for lunch, but there was no errors reported. The command line output was very slow. maybe i need a more powerful droplet. maybe the 512 ram can't handle it.

I'll report back in 30

**Comment by BlazeMuisNL** [comment]
Should run just fine on 512MB RAM.

I have several servers, I started with a droplet for pokemap as well, worked just fine and RAM usage was around 200-300MB (depends on scanned area/steps).

I'm running it on a Dedicated server now though, with an Intel Xeon 1245v2 and 16GB DDR3 RAM, runs much smooter on that I must say.

**Comment by matslarson** [comment]
512MB should be plenty, I've been running multiple instances on 256

**Comment by shiznewski** [comment]
Well your both right. came back from lunch restarted the droplet and worked instantly. Sorry for the "issue". 

While i have you guys, How do i kill the process when its running? I tried looking through the process list and didn't see an obxious process to kill

**Comment by Unsworth94** [comment]
`pkill -9 python` will kill all running python processes.

**Comment by shiznewski** [comment]
thanks a lot. appreciate all the help.
