### ISSUE TITLE
Server status symbol on map ui to indicate issues.

### ISSUE THREAD

**Issue by Sp4rkR4t** [AHAAAAAAA/PokemonGo-Map#2030]
## Current Behavior
At the minute if you are deploying a map for example to heroku and you don't see the console output if there is an issue with a build you have pushed you may well not see it at all and the map will just sit there being dumb.

## Possible Solution
In the electron port for windows there is a server status icon which will tell you if the map is having problems connecting, etc I feel something like this on the map would be of real benefit to users.

## Steps to Reproduce (for bugs)
1. deploy to heroku
2. get no feedback on issues.

## Context
A couple of times I've pushed builds to heroku and it has either been sluggish or not drawn the pokemon at all and there is no easy way to see what is happening.

**Comment by andrewda** [comment]
#1171
