### ISSUE TITLE
The "-ar" feature is not working

### ISSUE THREAD

**Issue by daproject85** [AHAAAAAAA/PokemonGo-Map#2035]
using Dev edition. 

when running "_$ python runserver.py -a ptc -u XXXXX-p XXXXXX-l "XXX" -st 10 -ar 10_

usage: runserver.py [-h] [-se] [-a AUTH_SERVICE] [-u USERNAME] [-p PASSWORD]
                    [-l LOCATION] [-st STEP_LIMIT] [-sd SCAN_DELAY] [-dc]
                    [-H HOST] [-P PORT] [-L LOCALE] [-c] [-d] [-m] [-ns] [-os]
                    [-fl] [-k GMAPS_KEY] [-C] [-D DB] [-t NUM_THREADS] [-np]
                    [-ng] [-nk]
**runserver.py: error: unrecognized arguments: 10**

**Comment by EdenGottlieb** [comment]
AFAIK There is not -ar parameter...

**Comment by Sejadis** [comment]
read 

> usage: runserver.py [-h] [-se] [-a AUTH_SERVICE] [-u USERNAME] [-p PASSWORD]
[-l LOCATION] [-st STEP_LIMIT] [-sd SCAN_DELAY] [-dc]
[-H HOST] [-P PORT] [-L LOCALE] [-c] [-d] [-m] [-ns] [-os]
[-fl] [-k GMAPS_KEY] [-C] [-D DB] [-t NUM_THREADS] [-np]
[-ng] [-nk]  

and you see no -ar flag anymore - map does update on itself now

**Comment by daproject85** [comment]
thanks... does the master branch also have AR now ? can you please tell me what the differences are right now between master and dev?

**Comment by philipp-r** [comment]
@daproject85 master branch has autorefresh. Differences can be viewed here: https://github.com/AHAAAAAAA/PokemonGo-Map/compare/master...develop
