### ISSUE TITLE
Geolocation option should be unavailable with --fixed-location

### ISSUE THREAD

**Issue by silverwind** [AHAAAAAAA/PokemonGo-Map#2037]
## Expected Behavior
Users should not be able to change the location when the server was started with `--fixed-location`.

## Steps to Reproduce
1. Start server with `--fixed-location` or `-fl`
2. Notice that the Geolocation checkbox is available on the web interface

**Comment by trol4ever** [comment]
I'm too lazy to make a pull request and submit the change at the moment. Just apply the same styling to the Geolocation button as the 'Change your location' textfield has.

In a more step by step explanation:
1. Go to templates\map.html
2. Right click it and edit it with a text editor.
3. Go to line 100.
4. You should see `<div class="form-control switch-container">`
5. Change that line to `<div class="form-control switch-container" style="display:{{is_fixed}}">`
6. Save and restart the webserver.

**Comment by silverwind** [comment]
Looks like this is fixed in https://github.com/AHAAAAAAA/PokemonGo-Map/commit/d838ee910439b285786b8aa7e2078c1a1a5de60c.
