### ISSUE TITLE
Not showing Pokemon

### ISSUE THREAD

**Issue by papi83dm** [AHAAAAAAA/PokemonGo-Map#2046]
I just deployed it to heroku and the map is not showing any pokemon.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by bj0rge** [comment]
When you posted your issue, Niantic servers were experiencing troubles for loggin in with PTC. Have you tried again?

**Comment by papi83dm** [comment]
Thanks, Is there any documentation on how I can make my own API calls to the PTC servers?

**Comment by bj0rge** [comment]
Not sure of that.
I was experiencing troubles too at this time, and saw on [ispokemongodownornot](http://ispokemongodownornot.com/) that servers were down for PTC, but not for Google Accounts, maybe due to the launch in HongKong.
Have you tried to start your server again?
