### ISSUE TITLE
Help with Windows Webserver Firewall / Map not reachable

### ISSUE THREAD

**Issue by Mumpitz** [AHAAAAAAA/PokemonGo-Map#2047]
## Expected Behavior
I've set up the script on a Windows Webserver installation. The config.ini has 0.0.0.0 as Host and 5000 as Port specified. In the Windows Firewall i've added an inbound Rule for the python.exe Executable to accept from every Port and an inbound Rule for Port 5000 explicitly, as well.

## Current Behavior
Currently i get a Webpage not available, ERR_CONNECTION_TIMED_OUT, when i try to reach the Server over Port 5000. Locally with localhost:5000, it works.

## Possible Solution
Other Firewall rules? Or is it possible to use the existing IIS Webserver and only get the Data from the Python Script?

## Context
I had it running a while, until i shut down the process to update the files. After the Update, the Map was not available externally anymore. The same Issue occurred the day before, but i don't see what i might have done to get it working again.

I also would like to run the Script or maybe multiple Workers as services, so that i don't need to log on to the Server to start it. I would appreciate every hint on what i'm doing wrong and what i would need to do, to do it right. The Wiki was sadly no help to me.

## Your Environment
Windows Server Web SP2 (32-Bit)
The Repo should be at commit: ff835fb9a8199608b88a3ea5207177b7d021e729
Due to no Git, i have to download and copy the files everytime

**Comment by BlazeMuisNL** [comment]
Have you also thought about forwarding the port in your router? That might be the issue here.. 

If you did, try changing 0.0.0.0 to your outbound IP (You can find your outbound IP at www.whatismyip.com).

**Comment by heartfrappe** [comment]
Are you still using the switches for -H 0.0.0.0 -p 5000 when running the script? I wasn't able to access the map remotely until I rand the script with the -H and -p switches defined.

**Comment by Mumpitz** [comment]
@BlazeMuisNL: There is no Router, because its a Root-Server. I could try to set the IP to the Servers IP.

@heartfrappe: Currently I use the config.ini File. But i was thinking about multiple workers, and from the Wiki Page about that, i would need to exclude things from the config and write it to the call.

I've tried now your suggestions. Using 0.0.0.0 as well as the Server IP and both in combination with the config.ini and without the -se Flag. Nothing worked. And over localhost it is only reachable when started with 0.0.0.0, but that is obvious i think.

**Comment by beranPro** [comment]
what about outbund communication? Is this blocked?
I'm running it on a server too, with no problems.

**Comment by Mumpitz** [comment]
Is it still Port 5000 or Port 80 for Outbound Rules? There is an IIS running on Port 80 that works fine, so Port 80 is open.

I've copied the Rules over from Inbound to Outbound. For the python.exe on every Port and for Port 5000 explicitly. No Success.

**Comment by Mumpitz** [comment]
I've now installed git to be able to simply switch branches. Currently i am using the develop Branch, but no changes. I expect a faulty Firewall Setup, but i don't know what else to change.

I mean, i've created two ingoing rules:
`Python27; Profile: any; Active: true; Action: grant; Programm: D:\Python27\python.exe; Local Address: any; Remote Address: any; Protocol: all; Local Port: any; Remote Port: any;`

`Port5000; Profile: any; Active: true; Action: grant; Programm: any; Local Address: any; Remote Address: any; Protocol: TCP; Local Port: 5000; Remote Port: any;`

And one two outgoing rules that are setup identically.

There is a Website Served over IIS. The WWW-Services Rule is active. So Port 80 is free if this matters.

**Comment by Mumpitz** [comment]
OMFG, I was wasting a whole day of researching that Issue, just to hear from my colleague that port 5000 is blocked by our office firewall. \**head-to-the-wall*\*

In the end, everything works perfectly fin with just the python.exe inbound rule, the config.ini file and the 0.0.0.0 and 5000 specified in it. My call is like that: `python runserver.py -L de`
Everything works as expected. Sorry for my incompetence. I feel ashamed.
