### ISSUE TITLE
Suggestion: save login and password to PTC in file

### ISSUE THREAD

**Issue by michi0987** [AHAAAAAAA/PokemonGo-Map#205]
Make us able to save our login in password to PTC for example in credentials.json so we don't have to enter same thing every time.

**Comment by XoneFobic** [comment]
Coming from a NodeJS background, dotenv always helped me lots getting environment parameters to a file (which you then gitignore and leave an example for people to fill in)

The python version of the package I generally use, seems to be https://pypi.python.org/pypi/python-dotenv

My Python experience isn't good enough at this point in time to make a proper pull request.

**Comment by JZ6** [comment]
will be making a settings file

**Comment by medghaim** [comment]
Check out the `develop` branch :) This has been implemented.
