### ISSUE TITLE
Current Location Button Not showing.

### ISSUE THREAD

**Issue by jde1126** [AHAAAAAAA/PokemonGo-Map#2061]
## Expected Behavior
There is suppose to be a location button about the "+ & -"

## Current Behavior
The button is not showing.

## Your Environment
Current Gut Pull
MacBook Pro (Newest OS)
Chrome, and Safari (Both not working)
Phython 2.7 (As  Told)

I use: "python runserver.py -se" to start:

Config.ini:
#Provide Pokemon Go Credentials here. This section must be filled out!
[Authentication]
# ptc or google
Service: ptc
Username: ------
Password: ------

[Search_Settings]
Steps: 5
Location: 7602 Berrywood Circle, Huntersville, NC 28078, USA
#Time delay before beginning new scan
Scan_delay: 1

[Misc]
#you need a google maps api key to run this!
Google_Maps_API_Key : --------
Host: 127.0.0.1
Port: 5000

**Comment by Gamewalker** [comment]
Just pulled from develop and got the button.

**Comment by jde1126** [comment]
I just pulled it as well, still not working....

**Comment by henningphan** [comment]
try shift+F5 so you load the latest js and does not run an old version. Browsers cache things
