### ISSUE TITLE
What's the point of confit.ini

### ISSUE THREAD

**Issue by daproject85** [AHAAAAAAA/PokemonGo-Map#2066]
If we are proving location and account and steps in CLI then what the point of this file

**Comment by invisiblek** [comment]
if you're planning to spin up several instances, having a config file is nice

**Comment by BillyWM** [comment]
>If we are proving location and account and steps in CLI then what the point of this file

If you use config.ini, you don't have to do that

**Comment by colwellkr** [comment]
At the moment the develop branch does not seem to pull from the config.ini. Is this a bug or not yet implemented?

**Comment by invisiblek** [comment]
https://github.com/AHAAAAAAA/PokemonGo-Map/pull/2021

**Comment by BillyWM** [comment]
It does. You have to pass the -se flag. If it still doesn't, that's a bug
