### ISSUE TITLE
configargparse

### ISSUE THREAD

**Issue by overload08** [AHAAAAAAA/PokemonGo-Map#2075]
I have an error on last commit

## Current Behavior
When I launch the server : 

Traceback (most recent call last):
  File "/opt/PokemonGo-Map/runserver.py", line 13, in <module>
    from pogom.app import Pogom
  File "/opt/PokemonGo-Map/pogom/app.py", line 12, in <module>
    from pogom.utils import get_args
  File "/opt/PokemonGo-Map/pogom/utils.py", line 6, in <module>
    import configargparse
ImportError: No module named configargparse

## Steps to Reproduce (for bugs)
git clone -b https://github.com/AHAAAAAAA/PokemonGo-Map.git
Edit config
run runserver

## Your Environment
* Version used: Last commit
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): Debian 8

**Comment by invisiblek** [comment]
sudo pip install configargparse

**Comment by overload08** [comment]
No way, i forgot pip install -r requirements.txt...

**Comment by RemyLebeau** [comment]
```
C:\Python27\Scripts\PokemonGo-Map-develop>pip install -r requirements.txt

Collecting configargparse==0.10.0 (from -r requirements.txt (line 5))
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03CFD870>: Failed to establish a new connection: [Errno 10061] No connection could be made because the target machine actively refused it',))': /simple/configargparse/

```

Any ideas?
