### ISSUE TITLE
I can not Start the script

### ISSUE THREAD

**Issue by alagabba** [AHAAAAAAA/PokemonGo-Map#2078]
Since last update the delelop version can i not start the script anymore.
I Start the Script and the Console closed every sec. 

I use this
C:\Python27\python.exe runserver.py -a google -u Login -p PW -l "Location" -st 10 -L de -t 1

Is this a new Problem?

**Comment by numb401** [comment]
run `pip install -r requirements.txt`

some of the packages have changed

**Comment by alagabba** [comment]
Is this not automatical in the setup.bat file? 

i run it "pip install -r requirements.txt" still not work

**Comment by sfjuocekr** [comment]
rm $(find |grep \\.pyc)

But I just tested the current dev branch and it works fine here.

**Comment by tr1p0z** [comment]
this is a shit now for start lol

**Comment by polyisobutylene** [comment]
Program seems to be taking preference on using the config/config.ini file if it exists even if username and password are set on the flags

config.ini should not be included in the repo anymore, you will have to delete the file yourself or update to the new syntax if you want to use it

**Comment by alagabba** [comment]
I Download last develop Version again and i delete all my files.

Problem still not work and yes is the new config.ini, i deleted this and i started the tool with -k but my map not still showing (White Page)

I use Windows 10 64 Bit

**Comment by AHAAAAAAA** [comment]
We moved over to a unified, clean config file approach. All devs will adjust appropriately. Please use master branch if you're having issues, we won't solve issues for develop.

**Comment by tr1p0z** [comment]
<3

**Comment by alagabba** [comment]
develop run it now :P
