### ISSUE TITLE
Re-include hidden pokemon

### ISSUE THREAD

**Issue by 0c7avia** [AHAAAAAAA/PokemonGo-Map#2083]
Hi, I'm using the "Active Development" version and I wonder how to make Pokemon that I excluded be shown again...
## Expected Behavior

Since excluding Pokemon was so easy, I expected the option to re-show them again.
## Current Behavior

I don't find this option in the "options"-menue on the left of the map. I also can't find any file where a list of excluded Pokemon could be found and edited.
## Possible Solution

Since excluding doesn't seem to be a big deal, I'd like the option to re-include specific Pokemon or understand how to do this manually.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: I downloaded the package a few hours ago
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile):

**Comment by AHAAAAAAA** [comment]
just remove them from your exclude, there's an x button. Also, we will not be accepting issues for develop branch. Use release branch.
