### ISSUE TITLE
Navbar not scrollable when Notify or Hide Pokemon are large.

### ISSUE THREAD

**Issue by AHAAAAAAA** [AHAAAAAAA/PokemonGo-Map#2085]
When adding multiple pokemon to Notify or hide, list grows off screen and sidebar isn't scrollable.

Example:
<img width="209" alt="screenshot 2016-07-25 15 27 10" src="https://cloud.githubusercontent.com/assets/1760334/17118078/5ddd8d3a-527c-11e6-96f0-24c8ba4965f3.png">

**Comment by DeviantEng** [comment]
Can confirm, have this bug too on the develop branch.

**Comment by callmebackdraft** [comment]
Pull Request:#2106  posted to fix this

**Comment by Algent** [comment]
For me this was already fixed after #2082

**Comment by callmebackdraft** [comment]
@Algent still it seems to be part of a bigger "issue" adding extra options to the options menu doesnt initiate scrollbar as necessary in some browser (mainly Edge)

**Comment by AHAAAAAAA** [comment]
Solved
