### ISSUE TITLE
Argument errors after config cleanup

### ISSUE THREAD

**Issue by willgrnr** [AHAAAAAAA/PokemonGo-Map#2087]
After the config cleanup (#2021) I am getting a couple argument required errors. I'm not sure whether I should be uncommenting/deleting # on the lines in config.ini that I want to use so I have tested both ways.

With #: `runserver.py: error: argument -k/--gmaps-key is required`
Without #: `runserver.py: error: arguments -u/--username, -l/--location, -st/--step-limit are required`

I am up to date on commits as of this post. config.ini originates from config.ini.example. Python 2.7 on Ubuntu 16.04.

config.ini: https://gist.github.com/willgrnr/46a5ca83bdbc579b87d6c8eda1942131

**Comment by EdenGottlieb** [comment]
+1

**Comment by Algent** [comment]
> Without #: `runserver.py: error: arguments -u/--username, -l/--location, -st/--step-limit are required`

I got the same error at first but forgot to uncomment username & password.

**Comment by jonfaustman** [comment]
I was able to get it running with some of the required settings in `config.ini` but not all of them. `username`, `step-limit` and `gmaps-key` worked fine. `password` and `location` did not. Was able to get it running by using the command line flag for location, and inputting password on prompt.

**Comment by Plop** [comment]
Having the same problem 
`runserver.py: error: argument -k/--gmaps-key is required`

I only let dg-name and every search settings commented. Otherwise, everything is uncommented. So I have set the gmaps-key correctly.

**Comment by EdenGottlieb** [comment]
This Config.ini is especially confusing, because it was built by someone who knows ini files for people who don't. Here's my take o this file:

Only lines saying Authentication settings, Database settings etc. need a # at the start. Lines with settings (key:value) do not.

As for the flags no-pokemon, no-pokestops, no-gyms: If you want to turn them on, write True. If not, DELETE them (no other way).

If you're using sqlite, delete line db-host, db-name, db-user and db-pass.

Everywhere else, simply write what is mentioned as default and you'll be fine.

Cheers.

**Comment by DeirhX** [comment]
The core of the problem and I observed in debugger:
ConfigFileParserException: Unexpected line 0 in config/config.ini: ��#{Unicode characters follow{

Basically it was saved as Unicode but is not being read so.

**Comment by willgrnr** [comment]
@EdenGottlieb lines in config.ini that you aren't using should remain commented as per https://docs.python.org/2/library/configparser.html

From what I understand of #2021, if a line is uncommented in config.ini then it is used, otherwise use flags in CLI.

**Comment by EdenGottlieb** [comment]
@willgrnr Whoops, you're right. I updated my comment.

**Comment by Rikilsta** [comment]
ITS NOT WORKING WHY??? IT WAS WORKING BEFORE 
runserver.py: errors : arguement -k--gmaps-key is required
I ENTERED MY GMAPS API KEY AND ITS STILL GIVING ME THIS ERROR WHY??? I PUT THE QUOTES LIKE THE GUIDE SAYS AND I EVEN PUT A CREDENTIALS.JSON TO SEE IF IT WORKS.
#GMAPS KEY "xxxxxxxxxxxxxxxxx"

**Comment by willgrnr** [comment]
@Rikilsta you are getting thumbs down because the manner of your comment is that of a 2 year old if they could type. If you are not using the develop branch then please post a separate issue. If not, then read #2021.

**Comment by invisiblek** [comment]
weird its working fine for me =/

**Comment by Alok-Sharma** [comment]
Was having the same issue. Removing the "#" from auth-service, username, password db-type, location, step limit and gmaps_key worked for me (by filling in appropriate values ofc)

**Comment by willgrnr** [comment]
Seems to be working again for me with the last pull, however I've got some more funky business that might warrant its own issue.

`runserver.py -l "Toronto"` runs fine. 
`~/map/runserver.py -l "Toronto"` throws the gmaps-key required error

**Comment by invisiblek** [comment]
oh, i think i see what's up, fix incoming...

**Comment by invisiblek** [comment]
https://github.com/AHAAAAAAA/PokemonGo-Map/pull/2182

**Comment by kaustubh94** [comment]
For anyone who seems to be getting this issue : runserver.py: error: argument -k/--gmaps-key is required
use this
Fix : python runserver.py -a ptc -u ****** -p ****** -l "Some Location" -st 10 -k "replace this with google api without quotes"
