### ISSUE TITLE
Pokemon spawn timer

### ISSUE THREAD

**Issue by mrmrblakey** [AHAAAAAAA/PokemonGo-Map#2091]
I have noticed that the Pokemon spawn timer has been extended.
Now whether this is Niantic prolonging the life of pokemon to ease of on the servers, I don't know, however it appears that the pokemon that have just spawned are actually still live in game.
The pokemon at the end of their life do not appear in game.
I am unsure as to whether or not that it is infact Niantics attempt to make it harder for us to find the pokemon or it is a problem within the code.
I am using the latest update with the stable master map.

Kind regards,
mrblakey.

**Comment by commanderjsoc** [comment]
@mrmrblakey Does this happen with the develop branch?

**Comment by mrmrblakey** [comment]
I have not tried this with the develop branch, I will try it and get back to you tomorrow.

Regards,
mrblakey.

**Comment by commanderjsoc** [comment]
You're so formal ;) Look forward to the results.

With highest respect,
commanderjsoc 😉

**Comment by mrmrblakey** [comment]
Commanderjsoc,

Your jest at mocking me has been taken lightely, quite amusing.
I have done this with the develop branch and it appears the results are the same. Extended spawn time and pokemon not appearing when they are nearing the end of their life. The spawn time for some has been extended up to 50 minutes and when nearing ~10-20 minutes, they do mot spawn in game but still appear on the map.

Regards,
mrblakey.

**Comment by commanderjsoc** [comment]
Alright, all pokemon spawns only last for at most 15min. I would suspect the system time is causing these problems. I also tried this on the devbuild, but I dont have this problem. Make sure that your time is not 1 hour in the future(or past).

**Comment by mrmrblakey** [comment]
Commanderjsoc,

This appears to have resolved my problem, I thank you for your help and hope this will help others in the future.

Kinds regards,
mrblakey.

**Comment by commanderjsoc** [comment]
No problem! Can you or a moderator get this issue closed?
