### ISSUE TITLE
geopy.exc.GeocoderTimedOut: Service timed out

### ISSUE THREAD

**Issue by RemyLebeau** [AHAAAAAAA/PokemonGo-Map#2096]
I was running the server fine yesterday.  I have both the latest Master and latest Dev builds installed, both ran fine yesterday.  I am using my own Google API key.

This morning (after PC reboot), neither is working, with apparently similar problem.  I got a new API key, still the same problem.

Here is what happens when I try to run it:
```

C:\Python27\Scripts\PokemonGo-Map-develop>C:\Python27\python runserver.py -a ptc -u *********** -p ******** -l "-34.006814884758704 150.86719751358032" -st 10 -H 0.0.0.0
sqlite
2016-07-26 08:11:53,197 [     models] [   INFO] Connecting to local SQLLite database.
Traceback (most recent call last):
  File "runserver.py", line 54, in <module>
    position = get_pos_by_name(args.location)
  File "C:\Python27\Scripts\PokemonGo-Map-develop\pogom\pgoapi\utilities.py", line 60, in get_pos_by_name
    loc = geolocator.geocode(location_name)
  File "C:\Python27\lib\site-packages\geopy\geocoders\googlev3.py", line 217, in geocode
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "C:\Python27\lib\site-packages\geopy\geocoders\base.py", line 163, in _call_geocoder
    raise GeocoderTimedOut('Service timed out')
geopy.exc.GeocoderTimedOut: Service timed out
```

## Your Environment

* Version used: Tried latest Master and Dev, with two different API keys.
* Operating System and version (desktop or mobile): Windows 10

**Comment by andrewda** [comment]
One of the following:

a.) you supplied an incorrect API key, or
b.) Geocoder API has an issue, or
c.) Your internet is not allowing you to connect for whatever reason

**Comment by blackwat3r** [comment]
the problem is with /pogom/pgoapi/utilities.py not having a default timeout specified in the geolocator.geocode call on line # 60

easily fixed by changing it to
loc = geolocator.geocode(location_name, timeout=10)
