### ISSUE TITLE
New code problem for me

### ISSUE THREAD

**Issue by dosenhosenjoe** [AHAAAAAAA/PokemonGo-Map#21]
It is very slow and retries like 6 times per 1.25%

**Comment by dosenhosenjoe** [comment]
And it now stopped because it couldnt decode json or something

**Comment by DerScreever** [comment]
#20 
think this is duplicated

**Comment by marauder37** [comment]
Meanwhile in Australia I have not been able to get one single RPC request to succeed for about 6 hours.

Are you running the latest code? If you get an error message and a traceback then please be a pal and paste them into the issue

**Comment by DerScreever** [comment]
From Germany we have the same problems. 
No RPC request does success

**Comment by sykhro** [comment]
This is due to the Pokénon Go servers being unstable.
