### ISSUE TITLE
Suggestion: Markers for edges/corners of scans.

### ISSUE THREAD

**Issue by kevvv** [AHAAAAAAA/PokemonGo-Map#211]
Would it be possible to have some points that mark what area on the map is being scanned?

 I'm currently scanning near a huge body of water and don't have a single clue just how much is wasted processing time.

**Comment by Skullmonkey** [comment]
+1 for this. I live in between a river and an ocean with about 1.5 miles in between. All of the Pokemon are expired by the time it searches what I assume is the ocean. I would Like to see where it is searching so that maybe I can modify the center/steps to search (mostly?) only land.

**Comment by JZ6** [comment]
https://i.imgur.com/I1IVitb.png

**Comment by kevvv** [comment]
Umm that doesn't really help me.

**Comment by jangrewe** [comment]
You could just meassure it by using the ruler that Google Maps provides. Go to your location, meassure 250m to the left, right, top, bottom and you know your center cell. Then add 500m up,down,left,right for each additional step.

3 steps = 3x 500m on each side.
