### ISSUE TITLE
Can i make scan areas bigger?

### ISSUE THREAD

**Issue by ZombieMIW** [AHAAAAAAA/PokemonGo-Map#2113]
Is it possible to make it scan larger? Like expand the size of area's it's scanning

**Comment by jskoizumi** [comment]
You can by modifying the -st value (default 10)

**Comment by theblackmarmoset** [comment]
use -st 15.  Seems to be big enough for me.  ( ͡° ͜ʖ ͡°)

**Comment by rayuki** [comment]
does anyone know of a way of making a grid out from a certain set of coords based on our ST size? so we can space our coords correctly when scanning a big area?

**Comment by Sorries** [comment]
well for ST of 10 it is 2.6km side to side on map. right click on google map and use measure distance. I usually do 1.3 km from the ocean/sea and then 2.6km from each point and my polygon will match

**Comment by medghaim** [comment]
https://discord.gg/Kamn6
