### ISSUE TITLE
Unexpected line 12 in config/config.ini

### ISSUE THREAD

**Issue by Ketakku** [AHAAAAAAA/PokemonGo-Map#2118]
I recently did a git pull, after doing this I attempted to run the app with the appropriate syntax
python runserver.py -u USERNAME -p PASSWORD -l "coordinateshere" -st 5 -H 0.0.0.0 however after doing this I receive the below error:
runserver.py: error: Unexpected line 12 in config/config.ini: Database_Name:

I checked the config.ini file and it reads as follows:
[Database]
#Possible values: sqlite, mysql
Type: sqlite
#The following are only required if it's not sqlite
Database_Name:
Database_User:
Database_Pass:
Database_Host:

I attempted to run the install for requirements.txt and everything is up to date, but i still have this issue.

If I understand correctly it shouldn't be asking for a database name since i have the type set to sqlite. Any assistance would be appreciated

**Comment by willgrnr** [comment]
The config structure has changed. See #2021 for changes. 

Edit config.ini.example with your details and then rename to config.ini

**Comment by seraphbreak** [comment]
I renamed my config.ini file and ran runserver again with my flags and it worked without needing a config.ini file.

**Comment by Ketakku** [comment]
Changes to the config.ini file were successful, I'm back up and running. Thanks!
