### ISSUE TITLE
UnboundLocalError: local variable 'poke' referenced before assignment

### ISSUE THREAD

**Issue by gitmon1234** [AHAAAAAAA/PokemonGo-Map#212]
I've been getting this error pretty consistently with recent builds. It'll loop through some steps (the exact number varies) and then get stuck:

```
Completed: 75.0%
[-] looping: step 13 of 16
Exception in thread search_thread:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "example.py", line 575, in main
    pokemonsJSON, ignore, only)
  File "example.py", line 639, in process_step
    disappear_timestamp = time.time() + poke.TimeTillHiddenMs \
UnboundLocalError: local variable 'poke' referenced before assignment
```

**Comment by mroge009** [comment]
Fix indent disappear_timestamp and everything under it to the end of the method once.

**Comment by pdiot** [comment]
Hi.

Indenting didn't fix it for me, as pokemons would stop showing up on the map.
I commentend the whole "Only / ignore" filtering part, and it seems to be working like a charm now.

**Comment by hhu94** [comment]
I can't reproduce this, are you still experiencing the same issue with the latest build?

**Comment by pdiot** [comment]
I can't run the latest version at all :D I got the one from around an hour ago to work without hiccups this way, just thought i'd share how if it can help. 

Keep up the good work for team valor !

**Comment by gitmon1234** [comment]
Seems to come and go. Might have something to do with the server.

**Comment by IPostStupidThings** [comment]
It might be that the error occurs for more than 3 steps, lots of people in the subreddit were reporting this error

**Comment by hhu94** [comment]
I am using 5 steps and can't reproduce the bug with the latest build.

**Comment by IPostStupidThings** [comment]
Just got a response from the user who said >3 steps gives the error, changing their location gives the error after 2 loops. If pdiot's solution doesn't break anything why not try that?

**Comment by pdiot** [comment]
Didn't experiment at all with the filter arguments. 
Just removed it on my fork cause I don't intend to use it for now, and wasn't really fond of how it was handled :)

**Comment by herikwebb** [comment]
+1 I'm seeing this issue as well, filtering using ignore and using 10 step count

**Comment by DerScreever** [comment]
Im sorry, but we dropped the support for the master branch (example.py). 
This branch is deprecated.  
The new branch contains a much cleaner structure so pls report only issues related to the develop branch. 

Your development team
