### ISSUE TITLE
Google API-Key invalid problems [DEV-Version]

### ISSUE THREAD

**Issue by inkkinker** [AHAAAAAAA/PokemonGo-Map#2129]
If I try to open the Website it opens normal but after a second it gets the error that the Google API-Key is invalid.

## Expected Behavior
Map should shown up 

## Current Behavior
Google Maps gets an error

http://prntscr.com/bxiryw

I don't know if this is important but I get this error after the first run 

http://prntscr.com/bxiwqq

## Steps to Reproduce (for bugs)
1. I wrote the API key in the config.ini  
2. I started the program with this command: python runserver.py -a ptc -u *** -p *** -l "*** ***" -st 7 -H *.*.*.* -L de -t 2 -k *************************
3. All starts normal 
4. The website says that the API-Key is invalid (and yes I made a few keys)

## Your Environment
Development-Version (25.07.2016)
Python 2.7.3
Ubuntu 14.04

**Comment by thezomb1e** [comment]
If you use heroku try adding the domain name yourappname.herokuapp.com/* to you API key settings on Google. I had to do this and it worked

**Comment by thezomb1e** [comment]
This would also apply if using a IP.

**Comment by inkkinker** [comment]
Ok I try this

-------------------------------------------------
This is a more detailed picture of the error

http://prntscr.com/bxj33r

**Comment by Germark** [comment]
I'm experiencing the same problem. The same steps, except I'm on windows. I get the same error in dev, 2.0 and 1.0.

**Comment by inkkinker** [comment]
Ok the try with heroku does not work for me
