### ISSUE TITLE
Multi Threaded not working on latest dev branch

### ISSUE THREAD

**Issue by Bakies** [AHAAAAAAA/PokemonGo-Map#2130]
running the scanner with 
$ python runserver.py -t 5
rest of the options are in config/config.ini
looking at the map with "scanned locations" turned on shows only one circle updating at a time, whereas before with multiple threads it updated 5 at a time

commit 775982ea5683ae186124ae96e5561519679ddf1a

**Comment by Bakies** [comment]
![image](https://cloud.githubusercontent.com/assets/1388188/17123408/4d07dd14-52b1-11e6-9392-5e0d372d2832.png)
htop shows that the right amount of threads spawned but I still think only one of them is actually searching

**Comment by ServePeak** [comment]
I believe this was an issue fixed with (#1910)

**Comment by Bakies** [comment]
This appears fixed
