### ISSUE TITLE
OperationalError: database is locked

### ISSUE THREAD

**Issue by bananamanpoke** [AHAAAAAAA/PokemonGo-Map#2138]
I get the following error when my app is running. I'm not sure what its affecting because my map still works (i think) but it pops up every few iterations. It says the database is locked? What does that mean?
![screenshot 2016-07-26 00 00 58](https://cloud.githubusercontent.com/assets/20630843/17125766/69c450f0-52c4-11e6-9e7b-593870bdaf5b.png)

**Comment by bananamanpoke** [comment]
Also, my notifications seem to be broken as well. It keeps notifying me after a pokemon disappears too.

**Comment by avgjoe** [comment]
Are you running two instances of runserver.py on the same database file?

**Comment by bananamanpoke** [comment]
No I'm not but I do keep changing versions from master/develop and older versions of master.
