### ISSUE TITLE
AutoRefresh Icons not clickable

### ISSUE THREAD

**Issue by alexanderrock** [AHAAAAAAA/PokemonGo-Map#214]
When I try to click on a pokemon icon or gym/stop and the "-ar 10" is given as an argument, i'm not getting an popup with the information

**Comment by Lazarix** [comment]
Apologies, I duplicated this in #217 
I'm also getting the issue.

**Comment by h1pp0** [comment]
I tried with -ar 5 and same issue, went to -ar 20 and higher, the issue did not reoccur.

**Comment by Lazarix** [comment]
happens for me on -ar 120

**Comment by h1pp0** [comment]
I just tested it more. After the first auto refresh all the clickable pokemon no longer shows data.

**Comment by foodforarabbit** [comment]
fixed in https://github.com/AHAAAAAAA/PokemonGo-Map/pull/246
