### ISSUE TITLE
Unexpected HTTP server response - needs 200 got 502.  Map Download failed. Trying again.

### ISSUE THREAD

**Issue by GlennHD** [AHAAAAAAA/PokemonGo-Map#2142]
## Behavior
- The app behaved as normally for several hours.  But then it just stopped working and my mobile device could no longer reach my server.  I continuously got the following 2 lines repeatedly until I hit ctrl+c and restarted it.  It, again, got the same error a few minutes after restarting (ctrl+c).  Not sure what a Bad Gateway has to do with this unless it was a problem on the PoGo side (the PoGo app still worked during the errors).  I have it running without a hiccup for the past 5 minutes.
- [WARNING] Unexpected HTTP server response - needs 200 got 502
- [   INFO] Map Download failed. Trying again.

## Environment
 - Windows 10 Pro, Good bandwidth throughput.  Dev Build.
 - Running server (forwarding to ngrok) with the following PS command:  
    - **\python.exe .\runserver.py -u *** -p *** -st 10 -k *** -l "***" -t 10 -H 0.0.0.0

Just giving my input.  I have no problem restarting.

**Comment by LenoxFro** [comment]
http://ispokemongodownornot.com/

**Comment by ZihanTang** [comment]
Same here.
The log said ptc login succeed but there is some error in rpc_api, look forward to a solution.
[    rpc_api] [WARNING] Unexpected HTTP server response - needs 200 got 502
[     search] [   INFO] Map Download failed. Trying again.

**Comment by GlennHD** [comment]
Thanks for that link. I donly login normally with Google but my server uses a PTC login.. didn't know there was such a difference between both. Also didn't know why it would cause a bad gateway error but I can probably guess... thanks

**Comment by GlennHD** [comment]
*** I do login normally **
