### ISSUE TITLE
Issue on mobile

### ISSUE THREAD

**Issue by Lazarix** [AHAAAAAAA/PokemonGo-Map#215]
### Environment info
Operating System: iOS using chrome or safari

Installed version of Python: 2.7

### Steps to reproduce
You get a "sorry! something went wrong." message after 5 seconds of opening the map on a mobile client. It says "This page didn't load Google Maps correctly. See the javascript console for technical details"
The initial render works, and things like resizing and clicking on objects works fine for the first 5 seconds. Then you get the error.

**Comment by sykhro** [comment]
Probably refers to the API key hitting the limit

**Comment by Lazarix** [comment]
Replacing the API key with my own key does seem to solve this problem.
Would highly recommend people get their own key. Perhaps add to README.md as a requirement?

**Comment by hhu94** [comment]
It's annoying because if you're actively developing you don't you want to push your API key when you change example.py. We need to either make it a parameter or put in in a separate config file. What do you guys think?

**Comment by DerScreever** [comment]
@hhu94 
we had some merge for config files i think. there is a field for this so far i know.

**Comment by hhu94** [comment]
@DerScreever Yes, I'm using credentials.json now. Thanks to whoever did it :)

**Comment by JZ6** [comment]
closed
