### ISSUE TITLE
Multi threads fixed? 

### ISSUE THREAD

**Issue by pickett2k** [AHAAAAAAA/PokemonGo-Map#2155]
Just wondering has the Threading issue been fixed where it didn't show all Pokemon? Can't really see a concrete answer in the issues pages... And if so could someone point me to the #? 

Thanks

**Comment by ghormoon** [comment]
there's a hotfix in PR #1910 and real fix in #1913 but none of them is merged so far. #1910 works for me with current develop good

**Comment by ServePeak** [comment]
ghormoon has it switched around. #1910 is the real fix, so if you plan on moving ahead of dev that's the one you should be using.

**Comment by pickett2k** [comment]
Thought so @servepeak when I read them both, 

This should speed up scanning significantly right??

**Comment by ghormoon** [comment]
if you currently use 1 thread, yes :) I usually run around -t 10

**Comment by pickett2k** [comment]
Yea I currently use 5 accounts and 1 thread on each just to cover my town but it takes a while to loop back around on each scan

**Comment by ServePeak** [comment]
What the fix does is that it fixes a threading issue where too many threads would cause parts of the search to be skipped.
