### ISSUE TITLE
Translation on Heroku

### ISSUE THREAD

**Issue by kalimerre** [AHAAAAAAA/PokemonGo-Map#2157]
Hello,

I'd like to know how is that possible to change language on Heroku ? I setup LOCALE variable to "fr" or "FR" but it does not change the language, it just keep English.

Is there any bug with this ? Any way to fix it ? 

Regards,

**Comment by cstewart90** [comment]
heroku config:Set EXTRA_ARGS="-L fr"

**Comment by kalimerre** [comment]
Thanks, but when I deploy using the button and not with command line ? :D 
I can't add this using the Heroku interface ?

**Comment by Toeler** [comment]
Settings -> Reveal Config Vars -> Add it in there

**Comment by kalimerre** [comment]
That's what I did
I add LOCALE as a key and fr as a value but it's still in english :(

**Comment by Toeler** [comment]
No, you add EXTRA_ARGS as the key and -L fr as the value

**Comment by kalimerre** [comment]
Works like a charm! Thanks!! 
If I want to add multiple parameters I need to put all in the EXTRA_ARGS key or I can have multiple EXTRA_ARGS key ?

**Comment by kalimerre** [comment]
Top !
Thanks for the tips :)
