### ISSUE TITLE
Update pokeMarkers on GoogleMap via ajax plus markers API

### ISSUE THREAD

**Issue by loretoparisi** [AHAAAAAAA/PokemonGo-Map#216]
The GoogleMap now let to export the map as global variable - see https://github.com/rochacbruno/Flask-GoogleMaps/issues/29 

This will help to get a context of the `map` object in the window so it's now possible to update the markers via ajax request in the client without having to refresh the page like

```javascript
var marker = new google.maps.Marker({
    position: myLatlng,
    title:"Hello World!"
});
// To add the marker to the map, call setMap();
marker.setMap(window.map);
```

So this could be done like

```javascript
var updateMarkers = function() {
    $.get("/api/v1/markers", function(data) {
        data.forEach((marker, index) => {
            var gm = new google.maps.Marker({
                icon: marker.icon,
                position: new google.maps.LatLng(marker.lat, marker.lng),
                title: marker.infobox
            })
            gm.setMap(window.gmap)
        })
    })
}
setInterval(() => {
    setLabelTime()
    updateMarkers()
}, 3000)
```

and that's it!

![schermata 2016-07-19 alle 02 19 25](https://cloud.githubusercontent.com/assets/163333/16934516/3f15cd38-4d57-11e6-9498-b36f3344ca75.jpg)

where the `/api/v1/markers` will be a new flask endpoint to expose markers like

```python
###
# LP: Markers Endpoint
###
@app.route('/api/v1/markers')
def markers():
    clear_stale_pokemons()
    pokeMarkers = calculate_markers()
    jsonResult = jsonify( pokeMarkers )
    return jsonResult
```

Of course there is something else to do like to remove old markers, etc.

I have pushed the `api` and the javascript changes in my fork here: https://github.com/loretoparisi/PokemonGo-Map

**Comment by volksport** [comment]
@loretoparisi really happy to see you here -- we run into each other on Spotify a lot ... haha!

**Comment by loretoparisi** [comment]
@volksport hahaha! 👍

**Comment by volksport** [comment]
@loretoparisi You should definitely make this a pull request.

contributors: this guy is legit you should take whatever he sends your way! 👍

**Comment by loretoparisi** [comment]
hahaha thank you 💯 
I have fixed the markers info box now and added a trivia `cleanupMarkers` fun :)

**Comment by loretoparisi** [comment]
Ok this is how not it looks like with infobox fixed and markers update and cleanup (to avoid too much objects into the `map` object )

![schermata 2016-07-19 alle 02 42 36](https://cloud.githubusercontent.com/assets/163333/16934845/ad3de9be-4d5a-11e6-99f6-d5d43bdd5e89.jpg)

The json pokemon markers api at `/api/v1/markers` is like

```json
[
{
"icon": "//maps.google.com/mapfiles/ms/icons/red-dot.png",
"infobox": "Start position",
"lat": 44.494887,
"lng": 11.3426163
},
{
"icon": "static/icons/19.png",
"infobox": "<div style='position:float; top:0;left:0;'><small><a href='http://www.pokemon.com/us/pokedex/19' target='_blank' title='View in Pokedex'>#19</a></small> - <b>Rattata</b></div><center>disappears at 02:57:00</center>",
"lat": 44.49707555007651,
"lng": 11.345854693158685
},
{
"icon": "static/icons/42.png",
"infobox": "<div style='position:float; top:0;left:0;'><small><a href='http://www.pokemon.com/us/pokedex/42' target='_blank' title='View in Pokedex'>#42</a></small> - <b>Golbat</b></div><center>disappears at 02:47:24</center>",
"lat": 44.4955452111877,
"lng": 11.342931283437089
},
{
"icon": "static/icons/41.png",
"infobox": "<div style='position:float; top:0;left:0;'><small><a href='http://www.pokemon.com/us/pokedex/41' target='_blank' title='View in Pokedex'>#41</a></small> - <b>Zubat</b></div><center>disappears at 02:51:04</center>",
"lat": 44.494996485158815,
"lng": 11.340402054976378
}
]
```

Sent the PR very funny night!

**Comment by michi0987** [comment]
Add it please, great idea!
