### ISSUE TITLE
How to start with config.ini?

### ISSUE THREAD

**Issue by vellrya** [AHAAAAAAA/PokemonGo-Map#2172]
-se key was removed in last update. How to start with config.ini now? If i using just "python runserver.py", i had arguments -u/--username, -l/--location, -st/--step-limit arу required error
![default](https://cloud.githubusercontent.com/assets/13716114/17135736/e69fb400-5339-11e6-80f8-4b386e54b4b0.JPG)

## Possible Solution

Back -se?

## Your Environment

* Version used: last dev
* Environment name and version (e.g. Python 2.7):Python 2.7.12
* Operating System and version (desktop or mobile):OS Win 7

**Comment by Plop** [comment]
It starts with config.ini by default now. You have to edit it and set the default configuration. You can override the settings by adding them in arguments.

**Comment by vellrya** [comment]
forget location)
