### ISSUE TITLE
Same map differs on different systems / Ubuntu is missing pokemon

### ISSUE THREAD

**Issue by InflamedSebi** [AHAAAAAAA/PokemonGo-Map#2173]
I run the map from heroku.
On my ubuntu Gnome 15.04: Firefox 44.0 and Chrome 51.0.2704.106 show the same Map.
On my Windows seven: Firefox 38.1.0 and Chrome 52.0.2743.82 show the same Map.

BUT the maps between windows and ubuntu differ!
Ubuntu is missing about 1 in 8 Pokemon.
I have no clue why browser are consistent with data, while systems are not.

Tested on my Android 5.1.1 Phone with chrome: same map like windows.
Seems like only ubuntu has this problem.

Can anyone else test this issue?

Not a major issue due to the mobile version is the good one, but maybe someone else is using the map under linux and experienced similar.

**Comment by JasperG** [comment]
Could you check and compare system clocks and timezones on both systems?

**Comment by InflamedSebi** [comment]
wow derp ... should have know that. Completely solved. Thanks.
