### ISSUE TITLE
Pip install requirements error

### ISSUE THREAD

**Issue by illus10nist** [AHAAAAAAA/PokemonGo-Map#2181]
Install requirements using is unsuccessful on ubuntu 12.04

pkg_resources.VersionConflict: (pytz 2011k (/usr/lib/python2.7/dist-packages), Requirement.parse('pytz>=2010'))

----------------------------------------
Command python setup.py egg_info failed with error code 1

**Comment by Chepainais** [comment]
Try 
```
sudo apt-get remove python-pip
wget https://raw.github.com/pypa/pip/master/contrib/get-pip.py
python get-pip.py
sudo pip install --upgrade six
```

Then install requirements again

**Comment by derusc** [comment]
pip install --upgrade pytz

**Comment by wcastello** [comment]
Find usage/installation help on https://discordapp.com/channels/204338767920758785/204339169458126849
and the Wiki https://github.com/AHAAAAAAA/PokemonGo-Map/wiki
