### ISSUE TITLE
Setup HTTPS

### ISSUE THREAD

**Issue by Slivo-fr** [AHAAAAAAA/PokemonGo-Map#2183]
I can't figure out how to setup HTTPS / SSL using let's encrypt.

Any advices ?

What kind of webserver are you using btw ?

**Comment by overload08** [comment]
May be install an Nginx reverse proxy

**Comment by Slivo-fr** [comment]
I'm not really used to nginx, could you give me a start ?

**Comment by overload08** [comment]
You can use this site in french : 
https://homeserver-diy.net/wiki/index.php?title=Utilisation_d%27Nginx_comme_reverse_proxy_avec_un_certificat_auto-sign%C3%A9,_Let%27s_Encrypt_et_un_chiffrement_fort

Replace 
`proxy_pass https://192.168.0.129`
by
`proxy_pass http://127.0.0.1:5000/`
in Nginx config

**Comment by Slivo-fr** [comment]
Is the shipped web server nginx ?

**Comment by overload08** [comment]
What system do you use ? Windows ? Linux ? Other ?

**Comment by Slivo-fr** [comment]
I'm running the runserver.py on a debian dedicated server.

**Comment by overload08** [comment]
Oh ok! You can do a reverse proxy with apache too.
That's the same things than Nginx

https://www.digitalocean.com/community/tutorials/how-to-use-apache-http-server-as-reverse-proxy-using-mod_proxy-extension

Don't edit default sites-available conf, create new conf.

**Comment by Slivo-fr** [comment]
I will dig this way, thanks for your help

**Comment by overload08** [comment]
You're welcome

**Comment by Slivo-fr** [comment]
Got it running with apache reverse proxy, thanks again !

**Comment by overload08** [comment]
;)

**Comment by tarthim** [comment]
Any pointers for windows? As far as I can tell map location through anything not local has to go through HTTPS for the Google Maps API to allow.

**Comment by overload08** [comment]
That's the same config for Windows (with Apache or Nginx)

**Comment by Slivo-fr** [comment]
I saw this page earlier, can we do it on our side, or does the project need to implement it ?

**Comment by tarthim** [comment]
Should be able to do it on our side if we dive into the python I guess.
It would be really neat if they'd include it as a flag option while running, and we could just include our key and certificate, but I guess there's more pressing things at the moment.

(I suck at this stuff, take everything I say with a grain of salt)

**Comment by coolaj86** [comment]
Built-in HTTPS Server
-----

I've got your server with https right here:

* https://github.com/Daplie/node-pokemap

It's a node.js server that uses the same web ui, but is easy to install and none of the problems with installing python, compiling c code, dealing with threads, ports are already open, single-user, setting up https, etc. Super easy and simple.

Pre-Built Packages
------

It even has pre-built downloadable packages:

* https://github.com/Daplie/pokemap-webapp

(though windows is untested, but I'd love to know if the windows-pokemap.bat works)

Disclaimer: I haven't merged in all of the UI updates from this main repo yet, but they're coming.

**Comment by chuyskywalker** [comment]
Feel free to use this thread to discuss if needed, but I'm going to close it as it's not related to direct bugs/etc for the project.
