### ISSUE TITLE
Pokevision map.html

### ISSUE THREAD

**Issue by vinsilsim** [AHAAAAAAA/PokemonGo-Map#2192]
Anyone can do an map.html like pokevision.com?

**Comment by JasperG** [comment]
Shouldn't be hard, at all.

**Comment by philipp-r** [comment]
Do you mean to show remaining time on map? see #1677

**Comment by polyisobutylene** [comment]
If you mean map styling I'm not sure if it's relevant.

You can use this page to help you style the google maps background to make it look more like the ESRI world street map that pokevision is using as its background:
http://googlemaps.github.io/js-samples/styledmaps/wizard/index.html

I did something quickly for comparison:
![screen shot 2016-07-26 at 10 30 41 am](https://cloud.githubusercontent.com/assets/1903878/17141987/60572f58-531c-11e6-884c-6e4fa0c54fcb.png)

If someone did the work to make a proper clone styling maybe they would include it

**Comment by JZ6** [comment]
sounds like someone is trying to make a rip off pokevision server
