### ISSUE TITLE
How to make it visible on iOS

### ISSUE THREAD

**Issue by Silvikk** [AHAAAAAAA/PokemonGo-Map#2193]
Hey, guys! 

After I set up new master version it works good at my laptop but now I can't make it work on iOS using ngrok (old version works fine). I see "Option" button and sign "Pokemon Go Map", the map doesn't work):
http://0ec6f532.ngrok.io - it works only in my laptop web browser

* Version used:
* Python 2.7
* iOS 8.0.2 (iPhone 5)

Any suggestions?

**Comment by 123456abcdef** [comment]
Have you tried refreshing the page a few times?

**Comment by Silvikk** [comment]
@123455abcdef
Hundred times! In different browsers (except Chrome, it requires iOS 9.0+)

**Comment by fankaisong** [comment]
are you saying you can download python 2.7 to your iphone 5 and install that ?

**Comment by 123456abcdef** [comment]
@fankaisong no thats not working. Start your server on your desktop with `-H 0.0.0.0` and you can access the webpage if you enter your_local_desktop_ip:5000

@Silvikk Ah. I have iOS 9 and it works. Sorry have no glue then.

**Comment by Silvikk** [comment]
@123456abcdef 

Okay. It's time to update my software :+1:
