### ISSUE TITLE
Different Behavior of develop/master Map

### ISSUE THREAD

**Issue by Shinitas** [AHAAAAAAA/PokemonGo-Map#2198]
Hi guys, thanks for what you are doing. 

I currently am working with both types of Map: master and develop.
I have seen that Master is getting less and less Pokemon than the develop, one, for no reason whatsoever.
Both my Master and Develop are updated to the last available version.

I like the develop one, but the lack of "scanning X out of 127" is a little frustrating, since I do not know when to stop the scan and being somehow certain about Pokemon in my area.
Could "scanning x out of y" be added to develop, or could the master be as efficient in searching Pokemon as the develop one?

## My Environment
* Version used: both Master and Develop (updated four hours ago)
* Environment name and version (e.g. Python 2.7): Python 2.7.12
* Operating System and version (desktop or mobile): Windows10, Desktop, both using Chrome and Microsoft Edge for cross-testing

**Comment by JasperG** [comment]
If you are running the branches on separate machines, make sure to check and compare time and timezones on both machines first.

Synchronize clocks with ntp.nasa.gov and retry.

**Comment by k33k00** [comment]
Why would you want to stop the scan?

The only option as of right now would be to enable scan areas and just wait until the hexagon stops growing.

**Comment by Shinitas** [comment]
Scanning with master version:
Pokemon acquired: 15
Time: 1 minute, 14' 40" seconds

Scanning with develop version:
Pokemon acquired: 27
Time: 40 seconds and 34"

(Basicially, k33, I was asking for a sort of counter of steps in the develop version, as in the master one)

**Comment by JasperG** [comment]
Again, compare the clocks of your machines.

**Comment by Zach1993** [comment]
They have two different search algorithms. The develop version is much more thorough.

**Comment by Shinitas** [comment]
That is nice.
Thank you, Zach.
But, I'd be clearer:
MAY there be a counter in the develop version, stating at which step we are?
If it does 45 steps, it may say "scanning 12 out of 45 places"

**Comment by wcastello** [comment]
2 days was two years ago, let us know if you still have a problem with the latest develop version.
