### ISSUE TITLE
RuntimeError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by asottile** [AHAAAAAAA/PokemonGo-Map#2208]
Recursing here will eventually (after a long time) lead to a `RuntimeError: maximum recursion depth exceeded`.

I'd suggest moving the try inside the loop and just let the `while True:` loop continue

https://github.com/AHAAAAAAA/PokemonGo-Map/blob/d8cdab2332d8297f20bcc3b56d47d5f03dc24567/pogom/search.py#L196

**Comment by wcastello** [comment]
Changed a while ago.
