### ISSUE TITLE
Browser notification infinite loop

### ISSUE THREAD

**Issue by katanlugi** [AHAAAAAAA/PokemonGo-Map#2212]
When adding a pokemon to the hiding list while at the same time the notify list, an infinite number of notification is generated.

## Expected Behavior

Only one notification should be created and maybe an info message about trying to add a pokemon in both lists.

## Current Behavior

an infinite number of notification is generated and no pokemon is displayed

## Steps to Reproduce (for bugs)

1. Add a pokemon to the notify list
2. Add the same pokemon to the hide list
3. Wait for this pokemon to appear within the scan area
4. Endless notification appear for this pokemon

## Context

It was a mistake from my part and forgot to remove it from the notify list once I added it to the hide list.

## Your Environment

* Version used: latest develop branch of Jul 25, 2016
* Environment name and version (e.g. Python 2.7): Python 2.7.1
* Operating System and version (desktop or mobile): Chrome 51.0.2704.103 (64-bit)

**Comment by kgurnani96** [comment]
going to look for the bug. on a side note, i shouldn't have tried this :(

**Comment by katanlugi** [comment]
I should have mentioned not to try if you can't/don't want to restart chrome...

**Comment by PiaFraus** [comment]
Fixed in #2131

**Comment by medghaim** [comment]
Known issue, fix identified we're just doing some spring cleaning before 2.1
