### ISSUE TITLE
Map flashes, then moves to "Oops! Something went wrong!"

### ISSUE THREAD

**Issue by heartfrappe** [AHAAAAAAA/PokemonGo-Map#2213]
## Expected Behavior
I expect to see the map when I open "localhost:5000" on my local machine.

## Current Behavior
When I open "localhost:5000" on my local machine, the page loads, I can navigate through the filter options, the map loads for half a second, then switches to the "Oops! Something went wrong!" message.

## Possible Solution
Not sure if this is related to my Google maps API key... This is the same behavior I see daily on pokemonradargo.com

## Steps to Reproduce (for bugs)
N/A

## Context
I can't get the map to load at all, even though the thread appears to be running and populating properly.

## Your Environment

* Version used: 0.1.0 (According to package.json)
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): Windows 10 desktop

**Comment by JasperG** [comment]
This is related to your webbrowser, or computer configuration and has no relevance to this project at all.

**Comment by willgrnr** [comment]
It's in the [wiki.](https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Google-Maps-API:-a-brief-guide-to-your-own-key) 

If someone wants to label this "big book of learn how to read", this is pretty fitting.
