### ISSUE TITLE
Uncaught InvalidValueError: initMap is not a function

### ISSUE THREAD

**Issue by 7183847** [AHAAAAAAA/PokemonGo-Map#2228]
![error](https://cloud.githubusercontent.com/assets/20667779/17148841/6664c5c2-5371-11e6-9480-e338db0dd581.png)

Downloaded last scripts version.
Python 2.7, Windows 8.1

please help!

**Comment by willgrnr** [comment]
It seems like you're missing the entire `static/` directory. Can you confirm it is there? For the Google maps error: did you follow the wiki to get your own API key?

**Comment by 7183847** [comment]
> It seems like you're missing the entire static/ directory. Can you confirm it is there?


Thank you! I used a very long way ! Once transferred to the C drive it worked !
