### ISSUE TITLE
[BUG] Not all pokemon are scanned / not all spawnpoints are scanned

### ISSUE THREAD

**Issue by swenne** [AHAAAAAAA/PokemonGo-Map#2232]
When scanning an area for > 1 hour with a map iteration time < 15 minutes, not all spawnpoints show up.

## Expected Behavior
I'm assuming that every spawnpoint spawn a pokemon at an interval of exactly 1 hour. So when scanning an area for > 1 hour, I expect all spawnpoints to shown up. I also assume every "rustling leaves" (ingame) to be a spawn point. and every pokemon (ingame) to be encountered fairly close to their spawn point.

## Current Behavior
Some of the "rustling leaves" show up as spawn points, but not all. I also encounter pokemon ingame that did not register on the map. Changing the location seems to effect which spawnpoints are detected, although I haven't found any way to predict which startinglocation will scan which spawnpoints.

## Possible Solution
?

## Steps to Reproduce (for bugs)
1. Go out with your phone and take note of the spawnpoints and pokemon encountered
2. Simultaniously, scan the area you walk in with the map tool
3. Note that not all spawnpoints/pokemon encountered on your phone are scanned by the map tool

## Your Environment
Running trunk

**Comment by rneu31** [comment]
Are you running this with one thread (-t 1) or multiple threads?

**Comment by Jorgixhallo** [comment]
If you are using more than 1 thread this issue has been identified already and it is going to get fixed on milestone v2.1.0.
Just wait for the Devs to fork and release the new build.

**Comment by swenne** [comment]
I'm not using any -t option, not sure what it defaults too

**Comment by d3st1ny94** [comment]
-t defaults to 5 according to the utils.py . im curious to know what exactly it does. definition says search threads. sooo it runs multiple searches at once per account? im not sure

**Comment by medghaim** [comment]
Help questions aqui, por favor:

https://discord.gg/dfnG2

**Comment by C-5** [comment]
I think simple or I sample
