### ISSUE TITLE
New Config file values broken

### ISSUE THREAD

**Issue by kintera** [AHAAAAAAA/PokemonGo-Map#2234]
when using the new config file layout. If you hard code the values for:

#no-gyms:                 # disables gym scanning (default false)
#no-pokemon:          # disables pokemon scanning (default false)
#no-pokestops:         # disables pokestop scanning (default false)

If these are hard set to false in the config the server will be unable to start stating if sees flag set "value set" and server fails to start even if left open  which should default to false. 

## Expected Behavior
Should except a false hard set or default to false if no value given. 

## Current Behavior
Ignore hard set or no value causing server to not stat with config file.

## Possible Solution
Set code to accept hardset value or default if blank.

## Steps to Reproduce (for bugs)
1. set config value to False, false, 0, or " " 
2. attempt to run "python runserver.py
3. Will throw error and not start server.

## Your Environment

* Version used:   commit 2e6c870 (Latest dev as of 7/26/16 13:00 CST)
* Environment name and version (e.g. Python 2.7): Windows server 2012 r2 python 2.7
* Operating System and version (desktop or mobile): Desktop

**Comment by wcastello** [comment]
Do not use whitespaces or use it with .ini style:
```
no-gyms:true
no-pokemon:true
no-pokestops:true
```

or 

no-gyms = true
no-pokemon = true
no-pokestops = true

**Comment by wcastello** [comment]
Already false by default since... some PR.

**Comment by kintera** [comment]
Still an issue actually just updated the build and get:

runserver.py: error: no-gyms is a flag but is being set to false.  I am running the latest git and have been way past 1372.

This config will cause the issue:

# Authentication settings
auth-service: ptc      # ptc (default) or google
username: "Omitted"
password: "Omitted"

# Database settings
db-type: sqlite         # sqlite (default) or mysql
#db-host:               # required for mysql
#db-name:               # required for mysql
#db-user:               # required for mysql
#db-pass:               # required for mysql

# Search settings
location: "omitted"
no-gyms: false         # disables gym scanning (default false)
#no-pokemon: false      # disables pokemon scanning (default false)
#no-pokestops: false    # disables pokestop scanning (default false)
num-threads: 2         # number of search threads (default 1)
scan-delay: 5          # default 5
step-limit: 12         # default 12

# Misc
gmaps-key: "key omitted"

# Webserver settings
host: 10.0.0.6         # address to listen on (default 127.0.0.1)
port: 5000             # port to listen on (default 5000)
