### ISSUE TITLE
First Scan is fast, second scan crawls

### ISSUE THREAD

**Issue by buddytohelpu** [AHAAAAAAA/PokemonGo-Map#2237]
The first initial scan is fast and scans a wide area, after the first scan completes it runs extremely slow, and does not scan the area (5) before it expires.

**Comment by C-5** [comment]
No not first
Am 26.07.2016 20:47 schrieb "buddytohelpu" <notifications@github.com>:

**Comment by medghaim** [comment]
This is how it works unfortunately, at least for now. If you want to speed things up, go through the source and comment out the pokestop/gym searching - if you have no need for gyms/pokestops. Please go to https://discord.gg/dfnG2 for help and tips!
