### ISSUE TITLE
Second Google map renders over the first

### ISSUE THREAD

**Issue by thefeeltrain** [AHAAAAAAA/PokemonGo-Map#224]
As the title says. A second Google map without the icons is rendered above the first, which hides all useful data. Not sure if Arch/Chrome specific or not.

### Environment info
Operating System: Arch with Linux 4.6.4-1-ARCH

Browser: Google Chrome 52.0.2743.60 beta

Installed version of Python: 2.7.12

### Steps to reproduce
1. Open page
2. Second map renders on top of the first after ~1 second

### What have you tried?
1. Deleting the second .gm-style div in the Chrome inspector shows everything like normal

**Comment by rochacbruno** [comment]
Flask Googlemaps got updated allowing getting the map object in global JS scope.

No need to create second map, just reference the original one!

**Comment by rochacbruno** [comment]
Take a look at examples to get the changes https://github.com/rochacbruno/Flask-GoogleMaps/tree/master/examples

**Comment by aabosh** [comment]
Experiencing the same issue.

**Comment by thefeeltrain** [comment]
Caused by uBlock Origin and/or other ad-blockers. Just disable them.
