### ISSUE TITLE
Only pokemon aren't being displayed on map. Gyms, stops, etc work fine.

### ISSUE THREAD

**Issue by HilkDaddy** [AHAAAAAAA/PokemonGo-Map#2250]
It seems to be the same case with other popular pokemon go maps. I've reset the server, broswers, cleared cache, added -t 1. Wat do?

**Comment by michaelarlt** [comment]
maybe clone of https://github.com/AHAAAAAAA/PokemonGo-Map/issues/2244

**Comment by HilkDaddy** [comment]
No I can see pokemon, stops, gyms being upserted on the cmd prompt

**Comment by HilkDaddy** [comment]
![pokewat](https://cloud.githubusercontent.com/assets/20670429/17156007/87f18476-5355-11e6-9e8b-42be58770f16.jpg)

**Comment by michaelarlt** [comment]
@HilkDaddy those pokemons you can see in the console might be even lured Pokemons generated by the lured pokestops. Just a guess from my side

**Comment by HilkDaddy** [comment]
Possibly. I'll see if I can find an example that disproves that.

**Comment by michaelarlt** [comment]
found another thread which looks similar to this one https://github.com/AHAAAAAAA/PokemonGo-Map/issues/2224

**Comment by elaurendeau** [comment]
I currently have the same issue. Trying to figure out why they are not showing up.

1- It seems like they are unreleated to the pokestop. When i empty my DB, i get multiple pokemons before i get my first pokestop.

2- I checked latitude and longitude from the DB are pointing at the right place.

3- The disappear_time doesn't seem right. According to the DB, they will disappear in 3-4 hours from my PC time. I currently have a time zone issue on my pc where it is always -1 hour from my time. I manually set the time to prevent it. Could it be an desync between the system time so the map never actually display them?

**Comment by elaurendeau** [comment]
Fixed my timezone and pokemons now show up.

GG

**Comment by michaelarlt** [comment]
can you check your timezone @HilkDaddy ? if this is the same case for you, then this issue is not related to the other one.

**Comment by HilkDaddy** [comment]
I have that same issue with my pc, 1 hour behind occasionally have to manually fix it. Let me try.

**Comment by HilkDaddy** [comment]
@elaurendeau What exactly did you adjust? Did you just change to another time zone altogether?

**Comment by elaurendeau** [comment]
1 - Enabled automatic Windows Time in the services.msc

 2- Checked both of Set time automatically and Set time zone automatically in the Time and Language of windows.

**Comment by rakunvar** [comment]
Just thought I'd drop a quick note. This indeed was my issue as well, and indeed windows was doing something weird with my time/timezone. Once I assigned my time zone, then swapped to automatic on both, they show up :) Thanks a ton for this project, especially since I cant exactly walk around much at all..

**Comment by HilkDaddy** [comment]
OMG IT WORKS! Woo! I had to change the 'internet time' option to time.nist.gov

**Comment by michaelarlt** [comment]
haha funny things always happen. so the issue is closed atleast. You might want to change it from open to closed as well

**Comment by HilkDaddy** [comment]
Will do.Thanks for your help everyone!
