### ISSUE TITLE
Map don't dispaly.

### ISSUE THREAD

**Issue by woitekd123** [AHAAAAAAA/PokemonGo-Map#2251]
Hello, i was configure app but and enable on google api js but have error, map doest work:

Oops! Something went wrong.This page didn't load Google Maps correctly. See the JavaScript console for technical details.

**Comment by michaelarlt** [comment]
where did you place your own api key? config and credentials?

**Comment by woitekd123** [comment]
only in credentials.json

**Comment by woitekd123** [comment]
now add to config.ini and to  credentials.json, map still doesn't work :|

**Comment by niklaswa** [comment]
Can you look into the js console and tell us the exact error? (Chrome: F12)

And try to start the server with `-k API_KEY` and look if it works.

**Comment by woitekd123** [comment]
thank you all!! :) i was add to config.ini and credentials.json and start with -k and is working !


thank you :)

**Comment by michaelarlt** [comment]
if you can set the issue to solved, would be fine :)
