### ISSUE TITLE
How can I run multiple instances in MySQL more stable?

### ISSUE THREAD

**Issue by gosp07** [AHAAAAAAA/PokemonGo-Map#2252]
I've been running around 20-23 multiple instances but some of them get the error on screen shot or something similar and stops running.Is there anything I can do to fix or anything I can add to make bot just restart if it runs into an error?I dont have coding experience so I've no idea how to fix it.
![qwer](https://cloud.githubusercontent.com/assets/20618367/17155709/f710043e-538e-11e6-9718-6838a883b1ba.png)

**Comment by hauxir** [comment]
this is a quickfix I made for this error https://github.com/hauxir/PokemonGo-Map/commit/b4fff3733176299b359644e5995d8b0f2c6cc158

**Comment by gosp07** [comment]
I'll check to see if this fixes then close the issue , I'll sleep and usually get the error in like 30-40min so gonna confirm in the morning
