### ISSUE TITLE
[Question] Looking for explanations about the API Key used

### ISSUE THREAD

**Issue by Plop** [AHAAAAAAA/PokemonGo-Map#2253]
Hi,

I'm looking for some explanations about the API Key used. Yesterday, and today, I used 1 000 requests for the Google Places API Web Service. So I want to know what is costing me all these requests.

Also, why the previous API Key was limited to 25k requests, and why does the API type changed ?

Thanks for your help.

**Comment by medghaim** [comment]
Help questions here, please: https://discord.gg/dfnG2
