### ISSUE TITLE
No pokestops at all

### ISSUE THREAD

**Issue by ekep** [AHAAAAAAA/PokemonGo-Map#2257]
Pokestops are not showing at all on map for me. Pokemon and Gyms are showing as expected as far as I know.
Server claims to upsert pokestops just like others but none show on map.
Tried several clean installs and reducing threads and tried to follow execution by inserting some log messages in handling pokestops to no avail. I have no idea why it doesn't work if it works for others. It's like server receives data of pokestops, but map has no idea of what to show and decides to drop it all.

Any ideas how to approach this other than just adding log messages to everything and comparing outputs and trying to figure if it's the data coming from Niantic servers or maybe some environment setting?

I'm using Windows 10 64bit/Python 2.7.12 (tried both 32 and 64 bit). Location is Finland, Haven't tried Linux yet. I have tried both master and development branches and the location I used is 65.010960, 25.469082 if anyone wishes to check if it works for them.

**Comment by Crucial97** [comment]
You did turn on the pokestops to view on the map right?

**Comment by jmccorm** [comment]
I had that problem at first. I did a few browser refreshes and it didn't fix it. I believe when I tried playing around with the icon size multiple times, it finally appeared? You might be able to confirm this by first trying a different browser. This seems like a client-side incompatibility when upgrading from 2.0 to the development branch.

**Comment by Crucial97** [comment]
![capture](https://cloud.githubusercontent.com/assets/11277057/17157481/419fb0a6-5355-11e6-92c5-ff7ba8bbfd08.PNG)

**Comment by jmccorm** [comment]
> Works well enough, try a few refreshes as mentioned above, and maybe different browsers

I believe this is a 2.0 -> development branch upgrade problem. The box for "icon size" was blank for me. From memory, I had to click on it and select a blank entry, and then reload, and then it started working correctly. I don't know if it is a cookie problem, cache problem, or something else. Browser was Firefox on a Windows PC.

**Comment by ekep** [comment]
My usual luck. Now the options work when I tried with Chrome. (I didn't even know scanned locations meant that.) Must've been something fishy with my Firefox that I didn't even suspect or I finally did something right in latest reinstall. Also completely cleared history, cookies etc. at some point, but didn't pay attention to that then.  Thanks for the great help and suggestions.
