### ISSUE TITLE
Confused as to what this file is for/why it keeps disappearing and reappearing.

### ISSUE THREAD

**Issue by theblackmarmoset** [AHAAAAAAA/PokemonGo-Map#2260]
There is this file named pogom.db-journal and I kinda wanna know why it's there in the first place and why the HELL IT KEEPS VANISHING AND COMING BACK!?!?!  But seriously,  I have no clue and it peeks my interest.  Here is a screenshot if you wanna know what im talking about. http://prntscr.com/bxx7fg

**Comment by trol4ever** [comment]
It's a temporary filed used by SQLite.
If you'd like to know more, read up on it here: https://www.sqlite.org/tempfiles.html

**Comment by FrostTheFox** [comment]
trol4ever is correct.
