### ISSUE TITLE
Error while using MariaDB: Specified key was too long

### ISSUE THREAD

**Issue by Zerotask** [AHAAAAAAA/PokemonGo-Map#2262]
When I try using mysql (MariaDB) I got the following error. When I change back to sqlite everything works fine.

![pogomap_mariadb_error](https://cloud.githubusercontent.com/assets/20150243/17157806/3472019e-5392-11e6-8b65-a751a8e478c2.PNG)

**Comment by Zerotask** [comment]
Okay, after I set:
set global innodb_large_prefix = ON;

I get the following error:
Index column size too large. The maximum column size is 767 bytes

source: http://stackoverflow.com/questions/30761867/mysql-error-the-maximum-column-size-is-767-bytes

**Comment by wcastello** [comment]
Can you try going to your models.py and changing all 
`CharField(primary_key=True)`
to 
`CharField(primary_key=True, max_length=255)`
then drop the db, start again and come back here with the result?

**Comment by Zerotask** [comment]
I get the same error:
peewee.InternalError: (1709, u'Index column size too large. The maximum column size is 767 bytes.')

**Comment by wcastello** [comment]
I've just installed MariaDB and tested it, everything works on my side. Are you using the latest develop?

**Comment by wcastello** [comment]
Alright, someone fixed it using max_length=50 because utf8mb4 is the default encoding: https://github.com/AHAAAAAAA/PokemonGo-Map/pull/2256 
Pull the latest develop and it should work for you.

**Comment by Zerotask** [comment]
Thank you very much. It's working now.
