### ISSUE TITLE
[Feature Request] Google offline maps

### ISSUE THREAD

**Issue by Zerotask** [AHAAAAAAA/PokemonGo-Map#2268]
is it possible to integrate google offline maps? I use it only for my city and therefore it could speed up the website if the map is offline / cached on the server who is running it.

**Comment by Megahurtzz** [comment]
I would also love this as it would also reduce mobile data requirements

**Comment by tsvetant** [comment]
It's against Google Maps API ToS

**Comment by Zerotask** [comment]
Oh, right, I also read that.
