### ISSUE TITLE
-fl flag does not work

### ISSUE THREAD

**Issue by Valareos** [AHAAAAAAA/PokemonGo-Map#2279]
Using master with latest commit, the -fl flag is not present as a valid flag, though is in the wiki under usage

**Comment by GreenflyM** [comment]
Also having issues with this. Is the syntax -fl "coordinates" and do you then remove -l when using -fl? I tried running multiple variations and every time it produces an error and won't run.

**Comment by trol4ever** [comment]
@Valareos -fl is present in the develop branch.
@GreenflyM ![after](https://cloud.githubusercontent.com/assets/11703528/17162358/10f1c4d0-53be-11e6-9c29-7e21386839f0.png) 
Look at the way I am using mine at it works fine.

**Comment by Valareos** [comment]
Closing out as FL now present in the master branch
