### ISSUE TITLE
What is the DB used for?

### ISSUE THREAD

**Issue by VergaraF** [AHAAAAAAA/PokemonGo-Map#2280]
Hello,

This is not a bug, but a question... what is the DB used for? I noticed everything gets saved on it (pokestops, pokemons, gyms, etc), but I would like to know the reason why this is done. 

Thank you,

**Comment by callmebackdraft** [comment]
without the DB it wouyld be pretty much impossible to show the gyms pokemon and stops on the map.
when you connect to the webserver it reads the data from the DB

**Comment by medghaim** [comment]
_Not_ a help question. Help questions go here: https://discord.gg/dfnG2
