### ISSUE TITLE
Scanning

### ISSUE THREAD

**Issue by Steev93** [AHAAAAAAA/PokemonGo-Map#2285]
More of a question i am using heroku.com as in the WIKI but the scanning is slow is there anywhere i can turn searching off and select a whole area and increase the scanning speed? for a local area or town ?

If not possible when using heroku is there a way to allow multiple users to search as soon as a new search goes last one disappears 

## Your Environment
* Version used: Todays latest build
* Environment name and version (e.g. Python 2.7): 2.7
* Operating System and version (desktop or mobile): Server

**Comment by medghaim** [comment]
Discussion/help: https://discord.gg/dfnG2
