### ISSUE TITLE
[Suggestion] Show Pokemon IV on hover.

### ISSUE THREAD

**Issue by SubNoizey** [AHAAAAAAA/PokemonGo-Map#2286]
It's pretty annoying to waste time, berries and balls catching a pokemon that turns out to completely suck with IV stats.

If you displayed the IV of the pokemon it'd be more rewarding and be a bigger incentive to go and catch it.

**Comment by BenVlodgi** [comment]
I'm typically looking for pokemon for their candy+dust

**Comment by DeviantEng** [comment]
Don't think it would be possible to calculate the IV of everything scanned.  For starters, IV is calculated based on the CP of the Pokemon, which is dependent on your level.  Too many variables at play here.

**Comment by SubNoizey** [comment]
If the API they use is anything like the other floating around they should be able to grab all that data when it discovers a pokemon and then it's just a matter of running the IV equation to determine its %.

STAMINA = 2 * HP
ATTACK = 2 * ROUND(SQRT(Attack * Special Attack) + SQRT(Speed))
DEFENSE = 2 * ROUND(SQRT(Defense * Special Defense) + SQRT(Speed))

**Comment by prajwalkman** [comment]
Can they even be known without catching it? I don't think so. you'd have to make the bot (or another account) go around catching everything the map sees, which seems like overkill for this project.

**Comment by Nicknack1234** [comment]
This has been requested before (Search) and it was determined not possible.
