### ISSUE TITLE
Change Your location not working under some circumstances (Firefox 47.0 vs 47.0.1)

### ISSUE THREAD

**Issue by adbspurs** [AHAAAAAAA/PokemonGo-Map#2288]
Platform: Windows 10
Browser1: Firefox 47.0.1
Browser2: Firefox 47.0
Python: 2.7

## Expected Behavior
Using Firefox 47.0:
Entering text in "Change your location" does the "usual" google maps thing of popping up addresses.

Using Firefox 47.0.1 entering text has no effect whatsoever, no suggestions, doesn't change "current location in main window, seems to "do nothing".

## Possible Solution
Seems CSS/JS related, somehow related to minor patch update to FF 47.0

## Steps to Reproduce (for bugs)
1. Open "Options" window
2. Enter address in "Change your location" text area
3. FF 47.0 gives suggestions as you type, FF 47.0.1 does nothing

**Comment by zjr8** [comment]
Not sure - as 47 gives nothing for me at the moment but a "You have exceeded your daily request quota for this API.  For more information on usage limits and the Google Maps Javascript API services please see: https://developers.google.com/maps/documentation/javascript/usage" and i have verified that my API key is not over hte limit - I noticed this issue as well last night - it seems that the change location section is not injecting the users JS API key ?

**Comment by MichaelJAndy** [comment]
I can't get this to work regardless of my browser, entering a new spot in "Change Your location" does nothing. On the 2.0 tag

**Comment by Akabane87** [comment]
@MichaelJAndy : you probably need to enable the API Google Maps Geolocation API in the Google APi manager (the one where you got your key).

**Comment by 123456abcdef** [comment]
I'm using OSX and Firefox 47.0.1. Changing the location works with no problem. @adbspurs you could open your browser console und check if some errors are thrown.

**Comment by adbspurs** [comment]
Between @123456abcdef and @Akabane87 got it working... 

* Opened console... error is "This API Project is not authorized to use this API, please ensure this API is activated in the Google Developers Console: <some link> [...]". 
* Clicked link, enabled API
* Address is now working

Will close this but... interesting how different browsers do/don't work without enabling it?

**Comment by MichaelJAndy** [comment]
Confirmed solution. I also inspected element and found that although I'd enabled the Google Maps javascript API, I hadn't enabled the Google Maps location autocompletion API. I think this was missing from the original documentation but it's there now.
