### ISSUE TITLE
Coordinate checking slowly moves towards the right, away from starting point

### ISSUE THREAD

**Issue by skxu** [AHAAAAAAA/PokemonGo-Map#229]
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discordapp.com/invite/qbpVH6b).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System: OSX

Installed version of Python: 2.7

### Steps to reproduce
1. Start the server (any example), step size 3 works well so you can see the movement better
2. Leave the server running for 15-20 min
3. The pokemon that appear on the map are no longer near the original point

### What have you tried?
1. Restarting the server fixes the issue

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by hhu94** [comment]
Experiencing the same issue.

**Comment by XoneFobic** [comment]
I was just going to make the same issue.
To my feeling it seems to move South East from it's original starting point, each cycle.

Original Start point: `52.5195922 5.4806713`
After one cycle (100 steps / `-st 10`): `52.4995922 5.5056713`

**Comment by nborrmann** [comment]
#231

**Comment by h1pp0** [comment]
I noticed this too. Used -st 7 and GPS coords for the start location. I also experienced the "drift" towards the South East direction
