### ISSUE TITLE
Not all Pokemon are shown on the map compared to an older version

### ISSUE THREAD

**Issue by Harachteh** [AHAAAAAAA/PokemonGo-Map#2294]
Using the latest version and one from about two days ago shows that the actual version doesn't display all Pokemon. Both versions had time to complete the scan 100% and were running simultaneously on different ports with different ptc accounts. Exchanging the ptc accounts didn't change the behavior.

Comparison pictures can be found here:
http://imgur.com/a/8iseT

If someone could tell me how to figure out the exact version from the PokemonGo-Map-master.zip I can provide the exact versions too.

**Comment by Crozius** [comment]
Hey mate,

I had the same issue and did some digging into the issues previous to this, found this one: https://github.com/AHAAAAAAA/PokemonGo-Map/issues/2224

use the command -t 1 at the end of the line. Appears that multi-threading is bugged for the time being.

Croz

**Comment by Harachteh** [comment]
Thank you Crozius, using only one thread worked!
Closed because it's a duplicate of https://github.com/AHAAAAAAA/PokemonGo-Map/issues/2224
