### ISSUE TITLE
Steps > Meters conversion ?

### ISSUE THREAD

**Issue by dorian-marchal** [AHAAAAAAA/PokemonGo-Map#2295]
How many meters is a step ?

**Comment by wschoot** [comment]
I believe it's roughly 200 meters right now but that's only a rough measurement. I think the idea behind "steps" in the nearby scanner ingame was 100 meters from where you are right now.

**Comment by hgentry** [comment]
A step (one of the green circles) is 150m. It measures things up to 75m away from you.

**Comment by dorian-marchal** [comment]
Ok, thanks :+1:
