### ISSUE TITLE
[Q] how to make this Online like pokevision.

### ISSUE THREAD

**Issue by jeckoz** [AHAAAAAAA/PokemonGo-Map#2297]
i need help  how to make this Online like pokevision.
and  my friend can scan area based on their own.

please help

**Comment by Dr-Death** [comment]
create DDNS account and setup your router to do a port forward "for port 5000" to your PC

then you can share your DDNS with your friend EX: "ddnsname.no-ip.com:5000"

**Comment by echo000** [comment]
The problem that I face with this, is if they change the location, it also changes the location for anyone else using it

**Comment by jeckoz** [comment]
yeah @echo000 . thats what i mean..
i need more usable website, i have domain and hosting. but i dont know how to set up like pokevision
