### ISSUE TITLE
No module named gpsoauth

### ISSUE THREAD

**Issue by jaimehrubiks** [AHAAAAAAA/PokemonGo-Map#2298]
I wonder if I can setup a map wich will no search for pokemon, and will only look for gyms and pokestops for now. I also want to know if I can limit the area of the map, for example, to only work within an entire country, and if the user selects another country it will not work.

**Comment by Plop** [comment]
Yes you can https://github.com/AHAAAAAAA/PokemonGo-Map/blob/develop/config/config.ini.example

**Comment by jaimehrubiks** [comment]
Thanks, how am I supposed to do it? I tried from command line but it is not working
    unrecognized arguments: -fl -np
Am I supposed to use the config file instead? how do I then launch the app, with no flags?

Thanks

**Comment by Plop** [comment]
Using dev branch ?

Working fine for me.

**Comment by jaimehrubiks** [comment]
Thanks, now I face a new problem
```

Traceback (most recent call last):
  File "runserver.py", line 15, in <module>
    from pogom.search import search_loop, create_search_threads, fake_search_loop
  File "/home/jaime/programs/PoGoMap/pogom/search.py", line 23, in <module>
    from pgoapi import PGoApi
  File "/home/jaime/programs/PoGoMap/pogom/pgoapi/__init__.py", line 1, in <module>
    from pgoapi      import *
  File "/home/jaime/programs/PoGoMap/pogom/pgoapi/pgoapi.py", line 32, in <module>
    from auth_google import AuthGoogle
  File "/home/jaime/programs/PoGoMap/pogom/pgoapi/auth_google.py", line 27, in <module>
    from gpsoauth import perform_master_login, perform_oauth
ImportError: No module named gpsoauth
```

I don't know what to do, already tried:
pip install gpsoauth
pip install -r requeriments.txt
pip install --upgrade -r requeriments.txt

**Comment by wschoot** [comment]
Make sure you type "requirements" correctly ;-)

$ pip install --upgrade -r requirements.txt
...
Requirement already up-to-date: gpsoauth==0.3.0 in /opt/rh/python27/root/usr/lib/python2.7/site-packages (from -r requirements.txt (line 14))
...

**Comment by jaimehrubiks** [comment]
I misstyped it here but of course I did it properly on console.
Anyway, I tried a fresh install, checkout develop branch and 
pip install --upgrade -r requirements.txt
And it fails hard, starting from ImportError: No module named flask_cors
but it is easily installable, all fails but the one about gpsauth

**Comment by jaimehrubiks** [comment]
sudo -H pip install -r requirements.txt
fixed for me, after system reboot.
