### ISSUE TITLE
Config File error when supplying password

### ISSUE THREAD

**Issue by chris-haigh** [AHAAAAAAA/PokemonGo-Map#2308]
## Expected Behavior

Password to be accepted through config file

## Current Behavior

Error message being thrown when password is left uncommented:
runserver.py: error: Unexpected line 3 in /PokemonGo-Map-develop/pogom/../config/config.ini: password: [Password]

## Steps to Reproduce (for bugs)

1. Uncomment auth-service, username and password
2. Enter google, username and password 

## Your Environment

* Version used: Current develop version, just downloaded (previous version from yesterday did the same)
* Environment name and version (e.g. Python 2.7): Python 2.7.12
* Operating System and version (desktop or mobile): Ubuntu 14.04.4

**Comment by chuyskywalker** [comment]
It's a lowercase `password` now: https://github.com/AHAAAAAAA/PokemonGo-Map/blob/develop/config/config.ini.example#L4

Also check the rest of your config file, the structure changed.

**Comment by chris-haigh** [comment]
It is lowercase on mine, and the config file is the same as the current example file, but I still get the error.

**Comment by chuyskywalker** [comment]
Can you post your full config here, but where your password and gmaps key are, enter `XXXXX` instead?

**Comment by chris-haigh** [comment]
# Authentication settings
auth-service: google
username: XXXXXX
password: XXXXXX

# Database settings
#db-type: sqlite        # sqlite (default) or mysql
#db-host:               # required for mysql
#db-name:               # required for mysql
#db-user:               # required for mysql
#db-pass:               # required for mysql

# Search settings
location: XXXXX, YYYYY
#no-gyms:               # disables gym scanning (default false)
#no-pokemon:            # disables pokemon scanning (default false)
#no-pokestops:          # disables pokestop scanning (default false)
num-threads:            4
scan-delay:            1
#step-limit:            # default 10

# Misc
gmaps-key: XXXXX

# Webserver settings
host:                  0.0.0.0
port:                  8000

I currently have the password commented out and then run python runserver.py at which time it asks for the password, I enter it and it works fine.

**Comment by wcastello** [comment]
Your config works just fine for me.

**Comment by wcastello** [comment]
https://github.com/bw2/ConfigArgParse/issues/60
; and # are comment character in the config file, apparently this is an issue

**Comment by chris-haigh** [comment]
Ah, my password has a # in it, that's it then.

I'll just change my password for the time being.

**Comment by chuyskywalker** [comment]
For future reference, I _think_ you could also just have put `"` marks around it.

**Comment by buckycu** [comment]
I have this problem too. My password contains #. I tried "password", 'password' but it didn't work. It's convenient enough not having to put username, API key, location in the command line. But if you have a solution for using the # in the password, do let me know.
