### ISSUE TITLE
QUESTION: Pull develop vesion from git

### ISSUE THREAD

**Issue by neruve** [AHAAAAAAA/PokemonGo-Map#2315]
I'm using git for windows. Can someone tell me the commands to download the develop version and update with the new develop files.

git clone https://github.com/AHAAAAAAA/PokemonGo-Map.git 
and
git pull origin master 

These seem to pull the master build. I tried git pull origin develop with no luck.

**Comment by ewold** [comment]
try  `git checkout origin/develop `

**Comment by k33k00** [comment]
git clone -b develop https://github.com/AHAAAAAAA/PokemonGo-Map.git 

This is what I use to get dev version

**Comment by dtphelan** [comment]
To pull updates (after you've used `git checkout develop`), use `git pull origin develop`.

**Comment by chuyskywalker** [comment]
If you need any more help on this, please try [the discord channel](https://discord.gg/dfnG2), thanks.
