### ISSUE TITLE
Location resetting to 51.4859846,-0.1672702 constantly

### ISSUE THREAD

**Issue by zeroecho** [AHAAAAAAA/PokemonGo-Map#2316]
Updates to the tip of develop and start the server with:

runserver.py -a google -u xxx@gmail.com -p xxx -l "xx,yy" -st 10

Running it now (vs. yesterday) teleports me from my starting location of xx,yy to 51.4859846,-0.1672702 

Looking at the logs it states:

> 2016-07-27 14:14:26,372 [        models] [   INFO] Upserted 0 pokemon, 28 pokest
ops, and 5 gyms
2016-07-27 14:14:30,573 [           app] [   INFO] Changing next location: 51.48
59846,-0.1672702
2016-07-27 14:14:31,707 [        search] [   INFO] Search loop 3 complete.
2016-07-27 14:14:33,878 [        search] [   INFO] Waiting 5 seconds before begi
nning new scan.
2016-07-27 14:14:34,282 [           app] [   INFO] Changing next location: xx,yy
2016-07-27 14:14:38,878 [        search] [   INFO] Search loop 4 starting
2016-07-27 14:14:38,878 [        search] [   INFO] New location set
2016-07-27 14:14:38,880 [        search] [   INFO] Skipping Pokemon Go login pro
cess since already logged in for another 1764.12 seconds
2016-07-27 14:14:39,486 [        models] [   INFO] Upserted 0 pokemon, 28 pokest
ops, and 5 gyms

I wasn't sure what was causing it so I ran grep and found the reference in pogom.db:

> user@machine /cygdrive/c/Users/user/PokemonGo-Map
> $grep -r "51.4859846,-0.1672702" "/cygdrive/c/Users/user/PokemonGo-Map"
> Binary file /cygdrive/c/Users/user/PokemonGo-Map/pogom.db matches

So I deleted pogom.db and ran the server again, and the same thing happens each time even with a clean database.

I'm guessing the database has this record in it but it seems to get generated from code so I'd assume my grep would have found the code that generated it as well as the .db itself. 

Any ideas?

## Your Environment

* Version used: 8fc0a66fbe6c8f16d059db5ccf8763b78b9b6a64
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): Desktop

**Comment by zeroecho** [comment]
Believe this was caused by Geolocation toggle and I am on wifi so for some reason that routes me to somewhere in London (only a few hundred miles away... :dart: )

**Comment by Gillingham** [comment]
@zeroecho I'm encountering the same issue, how did you disable Geolocation? I have a hardcoded location I'm passing, and don't see any geolocation tagged options under --help to disable it.

**Comment by zeroecho** [comment]
I found an option in the UI for the map itself. Click options and it was called Geolocation, now I believe it is called "Follow location". I wonder now if it may be a bug in that if you pass in specific coordinates AND have that option switched on, it tried to render both. I haven't played around since the changes that renamed it from Geolocation to "Follow location" were pushed so it may work properly now. Hope this helps!
