### ISSUE TITLE
Suggestion : Slack integration

### ISSUE THREAD

**Issue by Slivo-fr** [AHAAAAAAA/PokemonGo-Map#2324]
Allow user to post notifications about pokemon using slack webhook

## Expected Behavior
The notification system also post new pokemons on slack using optional configuration values (Hook, Channel, etc)

## Current Behavior
The tool only use native browser notifications

## Context
This would allow some more team work sharing what we can get

**Comment by wschoot** [comment]
As webhooks are integrated into the develop-branch already (https://github.com/AHAAAAAAA/PokemonGo-Map/commit/f6dbab4b2c3564098bca7a7953bd419a82f65fed), adding this is pretty straightforward. The comment from dev suggests that they want to keep their code as clean as possible and are not interested in adding every possible notificationservice right now. Examples will be posted. In the meantime I've build this myself with a little PHP-wrapper which, quickly and dirty, "rewrites" the webhook information to slackformat, and also filters out some pokemons as I don't like to be spammed with pidgets and rattata's ;-)

**Comment by Slivo-fr** [comment]
How cool ! 
Couldn't weebhooks use the listed pokemons for notifications to filter what is sent ?

**Comment by wschoot** [comment]
I *think*, but I'm no dev and haven't looked into the code for this, that it's just a filter in de webbrowser, hiding and showing stuff. In other words, it's not related to the code that fires webhooks. I've tried this and found that, although I'm ignoring a bunch of stuff in the GUI, I get *everything* into the webhook

**Comment by Slivo-fr** [comment]
A bit sad imo, could be neat to apply UI filters to the hooks

**Comment by wschoot** [comment]
True, but, I only want notifications for stuff I don't yet have and I want the map to show me some rare pokes I already have, but still want more of so I'm not really bummed by this.

The gist for "post.php" is here https://gist.github.com/wschoot/01f6d24c83e18ca955d75bcee2633fc4 -- hope this helps anyone

**Comment by Slivo-fr** [comment]
Thanks for sharing

**Comment by reactortrip** [comment]
It's already been done, been running the kavagent fork with it awhile now.

**Comment by andrewda** [comment]
All Pokémon ignoring is done on the front-end, well after the webhook is sent. Also, I think it's better to send all Pokémon data and allow the dev to filter out exactly what they want, even without getting a browser notification.
