### ISSUE TITLE
Server would suddenly go down (it seems)

### ISSUE THREAD

**Issue by rick47** [AHAAAAAAA/PokemonGo-Map#2326]
Well, I have been using iPokeGO for a day or so and it worked smoothly. However, now it just states the following message:

2016-07-27 17:35:36,353 [     search] [   INFO] Map iteration: 0
2016-07-27 17:35:36,353 [     search] [   INFO] Attempting login to Pokemon Go.
2016-07-27 17:35:36,355 [   auth_ptc] [   INFO] PTC login for: *******
2016-07-27 17:36:21,245 [   auth_ptc] [   INFO] PTC Login successful
2016-07-27 17:36:22,989 [     pgoapi] [  ERROR] Login failed - unexpected server response!

And the last iteration just continues. Does that mean that the server is down or I can do something about it?

**Comment by tarthim** [comment]
http://ispokemongodownornot.com/

PTC login servers are down at the moment.

**Comment by fust** [comment]
Maybe the status display from http://ispokemongodownornot.com/ can be shown in the app? That'd be pretty nice!

**Comment by rick47** [comment]
Oh, thanks. Never thought it was such a big problem, but according to that website PTC is down everywhere. 
Am I getting it right that I can fix this issue simply by using my Google account?

**Comment by fust** [comment]
Yup, that simple.

**Comment by hendrysetiadi89** [comment]
just got the same issue here... Did the pokemon go server change the response? I see at http://ispokemongodownornot.com/, it is working now.

**Comment by hendrysetiadi89** [comment]
Oh thanks for the info!

**Comment by rick47** [comment]
I just switched to the google account. It runs fine. If I use the same Google account as I used for the game installation, would it mean that I might get a ban?

**Comment by 123456abcdef** [comment]
@rick47 yes. Don't do that!
