### ISSUE TITLE
[Questions] How does it work ? "Hex Beehive Generator"

### ISSUE THREAD

**Issue by Kylvan** [AHAAAAAAA/PokemonGo-Map#2327]
Hello,

I actually don't know at all how to show the map with the Hex Beehive Generator.

The .bat seems running : https://snag.gy/A9z3hd.jpg

But no map on localhost:5000

What did i forgot ?

Regards

PS : I used this tutorial @ https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/How-to-use-Hex-Beehive-Generator

**Comment by Kylvan** [comment]
This is what i've got with ngrok 

: https://snag.gy/fWjQnF.jpg

**Comment by reyqn** [comment]
There is currently a bug if your latitude / longitude is an integer. Could be that.

**Comment by Kylvan** [comment]
I used the coordinates from the example just to test.

If you can have a look

**Comment by reyqn** [comment]
Yeah I didn't read the wiki for windows. Well you would have to also run `runserver.py -os -l '39.949157, -75.165297'`

**Comment by Mumpitz** [comment]
I got it working perfectly fine. My Coords are in Double-Quotes
`> beehive.sh 3 6 "lat" "lon"`

Now after some time, some hexes don't get refreshed and get blank.
Might be a RAM issue. The Server i am running this got 512MB and this fills up completely when running 6 Steps and 3 Leaps. I've reduced it to 6, 2 and will now monitor it.

Are there known Hardware Recommendations?

**Comment by Kylvan** [comment]
@reyqn 

Can i integrate that in the .bat file ?

**Comment by Hoekynl** [comment]
Try
pip install -U flask-compress==1.3.0

**Comment by Kylvan** [comment]
Will try tommorow thank you, i let you know !

**Comment by Kylvan** [comment]
![administrateur cwindowssystem32cmd exe](https://cloud.githubusercontent.com/assets/20684885/17193807/095f1b22-5455-11e6-95ca-a004e9c349de.jpg)

New error

**Comment by reyqn** [comment]
@Kylvan Try `runserver.py -os -l 'name of a location'`
You should be able to move to the scan location after that

**Comment by Hoekynl** [comment]
@Kylvan 
Remove the , in the location. '39.949157 -7*******'

**Comment by moggd** [comment]
@Klyvan Did you get it working?  I'm having the same problem.  Removing the , didn't work, when I do that I get the error described in #2792 where no python windows will load (COULD NOT GET
a position by name, aborting error when I use it without the comma)

**Comment by smalldragor** [comment]
Hi, i have the same problem...
I got beehive. bat to run and the server seems to be working [http://imgur.com/a/ZVqyx](url), moveables are running [http://imgur.com/a/uGDwG](url), but i do not know how to enter the map. When i type localhost:5000 in my chrome or firefox browser all i see is a beautyful Ooops! message. Can anyone tell me what's going on?

**Comment by Hoekynl** [comment]
@smalldragor 
Go to your Google API page and activate Google Javascript API

**Comment by smalldragor** [comment]
@Hoekynl 
Thanks for the replay but i think JS script API  is running on my account [http://imgur.com/a/L3qf2](url) Guess i still need to wait for a proper tutorial "how to use beehive" because i must have done something wrong.

**Comment by MrKetchumAll** [comment]
![hexbehive](https://cloud.githubusercontent.com/assets/20808879/17382769/69b0d736-5987-11e6-8580-ac19f782d398.png)
Is this how it suppose to look? I got it to here, open the server on another cmd, open localhost and map is there, but there is no scanning. Is there a step I'm missing?

**Comment by MrKetchumAll** [comment]
Problem solve. Gotta open bat file from Tools. Happy hunting!
