### ISSUE TITLE
Cannot Login From Google Account

### ISSUE THREAD

**Issue by 5N0WL30** [AHAAAAAAA/PokemonGo-Map#2332]
PTC works for me (down atm yeah) but can't make it work with google account. I switch infos on config file but nothing changes. Any idea?

2016-07-27 18:39:08,094 [auth_google] [   INFO] Google login for: ********
2016-07-27 18:39:08,520 [auth_google] [   INFO] Google Login failed.
2016-07-27 18:39:08,523 [     search] [   INFO] Failed to login to Pokemon Go. Trying again.

**Comment by AAnkudovich** [comment]
You need to allow access from less secure apps in your google settings

**Comment by 5N0WL30** [comment]
I did it, but still the same error

**Comment by AAnkudovich** [comment]
the following always works for me

python runserver.py -a google -u youremail@gmail.com -p yourpassword -l "dublin,ireland" -st 7 -H 0.0.0.0 -L en

**Comment by 5N0WL30** [comment]
Thanks a lot.

Date: Wed, 27 Jul 2016 08:56:20 -0700
