### ISSUE TITLE
static/dist files

### ISSUE THREAD

**Issue by tkSimon** [AHAAAAAAA/PokemonGo-Map#2333]
This is about the merge mess evolving around the static/dist files. I absolutely understand that it's a requirement to somehow provide them so users can simply download and run any given commit. Personally I don't like this at all because IMHO build artifact files shouldn't be in the source repository. I guess there are many who feel the same way. Though I don't want to start a flame war, so I hope this will be constructive discussion on the topic.

To start the discussion: isn't there a free build service that could be used for this purpose? Much like circle-ci, though storing artifacts not only for tags, but for every commit.
If I have some time later I'll look into OpenShift+Jenkins.

If this isn't in agreement with the core dev team's plans, please close.

**Comment by PiaFraus** [comment]
I don't really understand what I am supposed to do - previously I just edited static/map.js and now my changes are not applied. And I don't even see the file loaded or used by site. Am I supposed to merge all my changes to dist/js/map.js? Should the static one be deleted? What is going on? :)

**Comment by MonkeyLeeT** [comment]
@PiaFraus install node.js or npm, then install Grunt, and run Grunt (which automatically track your changes and install them to static/dist folder).

https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Development

**Comment by PiaFraus** [comment]
@MonkeyLeeT What benefit does it provide? It worked perfectly fine before

**Comment by tkSimon** [comment]
@PiaFraus sass is compiled to css and ecma script 6 code is transpiled to es5
Please don't highjack this thread :(

**Comment by PiaFraus** [comment]
@tkSimon Sorry, I thought it's related, since everything is broken since last pull. And it's related with yout title. I won't comment here anymore.

**Comment by hgentry** [comment]
IMO these files should only be loaded in the official releases. Dev should keep on loading static/map.js. It takes my machine upwards of half an hour to generate the dist files; I can't wait half an hour every code change.

**Comment by chuyskywalker** [comment]
We're not brining `dist` back into the develop branch; see many other posts about this.
