### ISSUE TITLE
Feature request: Make compatible with non-grunt builds

### ISSUE THREAD

**Issue by PiaFraus** [AHAAAAAAA/PokemonGo-Map#2342]
Hi,
Can someone please make a fallback that if there are no files generated by grunt - default map.js will be loaded? 
I kinda understand the reasons, but not everybody needs that. 
I am not as good with webdevelopment, so I don't know if you can dynamically load files and fallback to another files using js. But if we can - can someone implement it please?

## Expected Behavior
If in your build you don't want to use grunt and you don't care about ES compatibility - pull latest changes should still update your website with latest features. And editing static/map.js should take immediate effect.

## Current Behavior
Now we have two map.js and you have to run some third party tools to constantly synchronize them.

## Possible Solution
remove autogenerated file and implement dynamic loading - if no files in dist/js - load the static/js

## Context
Forcing requirements for additional steps in build process, which are not important for a lot of users, makes me sad. I probably would've been able to implement it if we would've used jinja.

**Comment by AHAAAAAAA** [comment]
No. You need to run grunt only once and it will generate those files. This is a very common setup if you're in development. Especially if you're changing things on the front-end, we need grunt to build those files. Release branch will have those files pre-built.

**Comment by PiaFraus** [comment]
@AHAAAAAAA Oh, I thought it will constantly slow down the development process, like in comments for #2333.
