### ISSUE TITLE
With steps=50, Pokemon only appear outside of a certain radius around the central point

### ISSUE THREAD

**Issue by failuretolaunch** [AHAAAAAAA/PokemonGo-Map#2344]
Not sure if anyone has experienced this, but with the default steps=12, at the location specified you see a small hexagon with the "scanned locations" option selected, with 12 radius. This appears to work correctly.

However, with steps=50, I get this instead:

![image](https://cloud.githubusercontent.com/assets/20686514/17185483/3c71a224-53ff-11e6-894b-a82188037e8f.png)

It looks like there's roughly a 12 step thickness of that hexagon, but everything on the inside of that isn't picked up or displayed.

**Comment by AHAAAAAAA** [comment]
yes it searches outwards, so with huge steps the locations in the middle expire well before the initial search is complete so the pokemon in the middle disappear. Reduce your step size drastically or honeycomb it.
