### ISSUE TITLE
[Help] New docker wiki

### ISSUE THREAD

**Issue by Kylvan** [AHAAAAAAA/PokemonGo-Map#2348]
Hello,

The last docker wiki was great and i was able to use docker with chuyskywalker but now i have to build an image :

https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Docker

I don't understand at all how to do it, everytime i got errors, and i've read the dockerfile with notepad but found no clues.

Can you give me a hand ?

Regards

**Comment by Kylvan** [comment]
This is the dock i got when i'm typing  `docker build -t pogomap .` :

`$ docker build -t docker-whale .
An error occurred trying to connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.23/build?buildargs=%7B%7D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&rm=1&shmsize=0&t=docker-whale&ulimits=null: open //./pipe/docker_engine: Le fichier spécifié est introuvable.
`

**Comment by jnovack** [comment]
Are you on the Develop branch?

**Comment by Kylvan** [comment]
I have downloaded the version from the Docker wiki.

So i should reinstall Docker Tools box ?

I'm on W7.

**Comment by jnovack** [comment]
uninstall docker, reinstall docker.

https://docs.docker.com/docker-for-windows/

**Comment by Kylvan** [comment]
The problem is :

The current version of Docker for Windows runs on 64bit Windows 10 Pro, Enterprise and Education (1511 November update, Build 10586 or later). In the future we will support more versions of Windows 10. ( Only)

I can only use this :

https://www.docker.com/products/docker-toolbox

**Comment by jnovack** [comment]
Try restarting the `docker-machine`.

If not, reinstall the toolbox then.  Make sure to do a complete reset and wipe.

Not connecting to `http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.23/build` means it can't connect to the local docker daemon.  Has nothing to do with the build.

**Comment by Kylvan** [comment]
Well, same error, so i supposed this version of the wiki can't work at all on Docker Tools Box in W7 but only on Docker version of W10.

It is possible to have the previous version of this wiki ? '( Who was working on W7)

**Comment by Kylvan** [comment]
https://github.com/docker/docker/issues/22338

Issue solved here.
