### ISSUE TITLE
When a MySQL connection is lost the app doesn't handle it well

### ISSUE THREAD

**Issue by martinsweitzer** [AHAAAAAAA/PokemonGo-Map#2352]
I left the app running over night and walked into two of my instances just spamming this warning message over and over

`models] [WARNING] (2006, "MySQL server has gone away (error(10054, 'An existing connection was forcibly closed by the remote host'))")... Retrying
`
Restarting the app allowed the MySQL connection to connect correctly.

**Comment by marauder37** [comment]
fixed w #2386
