### ISSUE TITLE
Feature Request: Relative pathing 

### ISSUE THREAD

**Issue by ndragon798** [AHAAAAAAA/PokemonGo-Map#2354]
Change all of the absolute pathing to relative pathing to sort out future issues with reverse proxies.

## Expected Behavior
If you change `static/dist/css/app.min.css` to '../static/dist/css/app.min.css' it would stop a lot of problems when hosting the map on a reverse proxy setup with apache.
Without this it has no css, js, or anything else that isn't part of the main page. 
[Picture without relative links](http://i.imgur.com/D4U5RJ9.png)
## Possible Solution
Replace all absolute links with relative ones.

## Steps to Reproduce (for bugs)

[Absolute Links](http://ndragon798.duckdns.org:5000)
[Relative Links](http://ndragon798.duckdns.org/go)

## Context
This affects anyone running pokemon go map through apache2 as a reverse proxy.

**Comment by kyleaa** [comment]
Are you running the develop or master branch? I've had it behind an nginx reverse proxy at /pokemon/ and haven't noticed any issues with anything

**Comment by kyleaa** [comment]
I just noticed your links. Have you tried serving it at /go/ instead of /go? I would expect that would resolve your issue.

**Comment by ndragon798** [comment]
Well you can close this. I feel stupid. The /go/ works.
