### ISSUE TITLE
Question -Config.ini?

### ISSUE THREAD

**Issue by Caspiel86** [AHAAAAAAA/PokemonGo-Map#2359]
## Current Behavior
Running C:\Python27\python runserver.py -se. Gives me an error. I am not sure what i should be placing in the config.ini. I want to be able to search for only Pokemon and turn of the gym and poke-stops
.
Error-
 -error: Unexpected line 14 in D:\Downloads\PokemonGo-Map-develop (1)\PokemonGo-Map-develop\pogom\../config/config.ini: no-gyms:
 
-Config-ini
#Authentication settings
auth-service:ptc
username:******
password:*******

#Database settings
db-type:sqlite        
#db-host:               
#db-name:               
#db-user:              
#db-pass:              

#Search settings
location:*******,*******
no-gyms:
no-pokemon:
no-pokestops:
num-threads:1
scan-delay:1            
step-limit:10

# Misc
gmaps-key:*******

#Webserver settings
host:127.0.0.1                  
port:5000

## Possible Solution
If someone can tell me what i should write after no-gyms: ,no-pokemon: , no-pokestops:.

## Your Environment

* Version used:Dev
* Environment name and version (e.g. Python 2.7): Pything 2.7
* Operating System and version (desktop or mobile):Windows 10 64bit

**Comment by andrewda** [comment]
Looks like there might be an issue with your location. Try changing it to `location: Canada` and see what happens.

**Comment by Caspiel86** [comment]
Tried that. I think its my experience with config.ini. My old laction is set to 41.1727017,-73.19237861. i just put the **** to block it out but i dont live there so there is no reason to.
#Search settings
location:Canada
no-gyms:true
no-pokemon:false
no-pokestops:true
num-threads:1
scan-delay:1            
step-limit:10

I get error-runserver.py: error: no-pokemon is a flag but is being set to 'false'

**Comment by Hoekynl** [comment]
download original config.ini and use command line arguments
-np - Disables Pokemon from the map (including parsing them into local db).
-ng - Disables Gyms from the map (including parsing them into local db).
-nk - Disables PokeStops from the map (including parsing them into local db).

**Comment by Caspiel86** [comment]
I did that as a work around. its working well. Thanks for the info. I am now just trying to speed up the scans if possible.

**Comment by Hoekynl** [comment]
@Caspiel86 
use the -t (number of threads) argument.
It gives more threads to the service allowing faster scanning, but I think it is bugged without using a MySQL server (will not show all pokemons), so use a MySQL server

**Comment by Caspiel86** [comment]
i also found the -t argument . Now to figure out MySQL Server lol. 
Thanks for all the help

**Comment by Hoekynl** [comment]
@Caspiel86 
I found this mini mysql server for windows?
https://sourceforge.net/projects/miniserver/files/MiniServer/MiniServer_%20MySQL%205.0.67%20Portable/mini_server_11.exe/download

**Comment by Caspiel86** [comment]
I checked the wiki and there are no directions for set up. I will figure it out eventually and i hate to ask but any chance you have directions someplace or on another thread.

**Comment by Hoekynl** [comment]
Info : Download it, extract to a folder
Run mysql_start.bat
Login as root : mysql --user=root --password=root
create database pgodb;
grant all on pgodb.* to 'pgouser' identified by 'MAKE OWN PASSWORD';

add this to command line of PokemonGo map starter
--db-type mysql --db-name pgodb --db-user pgouser --db-pass YOURPASSWORD --db-host localhost

**Comment by Caspiel86** [comment]
OperationalError: (2003, "Can't connect to MySQL server on 'localhost' ([Errno 10061] No connection could be made because the target machine actively refused it)")

that is how far i got. SQL is up and running DB is set up and password was set.

I am running this in the CMD-C:\Python27\python runserver.py -a ptc -u *** -p ***** -l 41.1727017,-73.19237861 -st 10 -t 1 -ng -nk --db-type mysql --db-name pgodb --db-user pgouser --db-pass ***** --db-host localhost

**Comment by Hoekynl** [comment]
@Caspiel86 
Let me try myself too with this server.

**Comment by Caspiel86** [comment]
no problem. i appreciate the help . Below is the full CMD error
Traceback (most recent call last):
  File "runserver.py", line 49, in <module>
    create_tables(db)
  File "D:\Downloads\PokemonGo-Map-develop (1)\PokemonGo-Map-develop\pogom\models.py", line 332, in create_tables
    db.connect()
  File "C:\Python27\lib\site-packages\peewee.py", line 3404, in connect
    self.initialize_connection(self.__local.conn)
  File "C:\Python27\lib\site-packages\peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "C:\Python27\lib\site-packages\peewee.py", line 3402, in connect
    **self.connect_kwargs)
  File "C:\Python27\lib\site-packages\peewee.py", line 3929, in _connect
    return mysql.connect(db=database, **conn_kwargs)
  File "C:\Python27\lib\site-packages\pymysql\__init__.py", line 88, in Connect
    return Connection(*args, **kwargs)
  File "C:\Python27\lib\site-packages\pymysql\connections.py", line 690, in __init__
    self.connect()
  File "C:\Python27\lib\site-packages\pymysql\connections.py", line 939, in connect
    raise exc
peewee.OperationalError: (2003, "Can't connect to MySQL server on 'localhost' ([Errno 10061] No connection could be made because the target machine actively refused it)")

**Comment by Hoekynl** [comment]
@Caspiel86 Can you try localhost:3311 ?

**Comment by Caspiel86** [comment]
Tried Cant -

Traceback (most recent call last):
  File "runserver.py", line 49, in <module>
    create_tables(db)
  File "D:\Downloads\PokemonGo-Map-develop (1)\PokemonGo-Map-develop\pogom\models.py", line 332, in create_tables
    db.connect()
  File "C:\Python27\lib\site-packages\peewee.py", line 3404, in connect
    self.initialize_connection(self.__local.conn)
  File "C:\Python27\lib\site-packages\peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "C:\Python27\lib\site-packages\peewee.py", line 3402, in connect
    **self.connect_kwargs)
  File "C:\Python27\lib\site-packages\peewee.py", line 3929, in _connect
    return mysql.connect(db=database, **conn_kwargs)
  File "C:\Python27\lib\site-packages\pymysql\__init__.py", line 88, in Connect
    return Connection(*args, **kwargs)
  File "C:\Python27\lib\site-packages\pymysql\connections.py", line 690, in __init__
    self.connect()
  File "C:\Python27\lib\site-packages\pymysql\connections.py", line 939, in connect
    raise exc
peewee.OperationalError: (2003, "Can't connect to MySQL server on 'localhost:3311' ([Errno 11001] getaddrinfo failed)")

**Comment by Hoekynl** [comment]
@Caspiel86 
run mysql_stop.bat
change that back to localhost and edit the file in mysql server
/udrive/my.cnf
You have 2 lines which are port=3311
Change that to port=3306
and run mysql_start.bat again

**Comment by Caspiel86** [comment]
Just to verify When i installed the SQL . I ran these commands to create the DB. Does that look correct?

mysql> create database pgodb;
Query OK, 1 row affected (0.00 sec)

mysql> grant all on pgodb.* to 'pgouser' identified by '***';
Query OK, 0 rows affected (0.00 sec)

**Comment by Hoekynl** [comment]
@Caspiel86 
Yes that is correct. Could you try what I said above your comment? Hope it fixes it

**Comment by Caspiel86** [comment]
I changed the ports to 3306. verified it saved to the file. When i ran the SQL batch. it still says port 3311.
i tried the CMD with port: 3304 and port:3311. Still getting the same error.

**Comment by Caspiel86** [comment]
this is what i get when i run the sql start batch The MySQL server is working on disk Z:\ [port 3311]

**Comment by Hoekynl** [comment]
@Caspiel86 
Ok let me make config and all files, I will make you a download which should work

**Comment by Caspiel86** [comment]
Wow git hub is awesome.. I dont know how to thank you other than Thank you.

**Comment by Hoekynl** [comment]
@Caspiel86 
Try this : https://drive.google.com/open?id=0B90WlDTwpRLXMy1SY3M4ekgtOFE

**Comment by Caspiel86** [comment]
its working. no clue why they first time it didnt work.

**Comment by Hoekynl** [comment]
@Caspiel86 
Ok nice :D now you should be able to add more threads with -t #
I have -t 8 on my raspberry pi

**Comment by Epion003** [comment]
Sorry to bother @Hoekynl @Caspiel86 I was tryin to follow along with the install but i get this error when i try to run the program

C:\Users\wizdo_000\Desktop\PGo Mapmaster2\PokemonGo-Map-master>C:\Python27\Python.exe runserver.py -a ptc -u LittleFire003 -p Liberty001 -l ", CT 06114, USA" -st 10 -t1 -H 0.0.0.0 -L en --db-type mysql --db-name pgodb --db-user pgouser --db-pass MYPASS --db-host localhost
usage: runserver.py [-h] [-se] [-a AUTH_SERVICE] [-u USERNAME] [-p PASSWORD]
                    [-l LOCATION] [-st STEP_LIMIT] [-sd SCAN_DELAY] [-dc]
                    [-H HOST] [-P PORT] [-L LOCALE] [-c] [-d] [-m] [-ns]
                    [-k GMAPS_KEY] [-C] [-D DB] [-t NUM_THREADS]
runserver.py: error: unrecognized arguments: --db-type mysql --db-name pgodb --db-user pgouser --db-pass MYPASS --db-host localhost

C:\Users\wizdo_000\Desktop\PGo Mapmaster2\PokemonGo-Map-master>

I am new to this and got the mapp working few days ago. trying to set it up to run multiple accts on one window maybe just 8. Sorry for the bother again and thank you
