### ISSUE TITLE
errno 22 while trying to connect to the server

### ISSUE THREAD

**Issue by bgokjh** [AHAAAAAAA/PokemonGo-Map#2360]
this is the code iam running: python example.py -a google -u email -p pass -l "some place" -st 10
and the error i get is this: 
 * Debugger pin code: 426-870-563
Exception in thread search_thread:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "example.py", line 561, in main
    open(path + '/locales/pokemon.' + args.locale + '.json'))
IOError: [Errno 22] invalid mode ('r') or filename: 'C:\\Users\\???\\Desktop\\Po
kemonGo-Map-master/locales/pokemon.en.json'

how do i fix that?

**Comment by Hoekynl** [comment]
Isn't example.py old? Isn't it runserver.py now?

**Comment by talentedmrripley** [comment]
Yes, example,py was removed quite some time ago.  @bgokjh You need to grab the updated code and then read over the setup info in the wiki.

**Comment by wcastello** [comment]
Alright, update and try again.
