### ISSUE TITLE
How to merge Dev PR's? 

### ISSUE THREAD

**Issue by pickett2k** [AHAAAAAAA/PokemonGo-Map#2367]
Ive downloaded the latest development branch and I want to try a few of the PR's people have made, can anyone advise how to merge the files because when I just overwrite the files themselves it always errors out for me or stops the other pr working..

I've got got bash installed but not sure of the commands on windows

If this should be asked on Discord could anyone send me the pin? 

Thanks In advance

**Comment by Bitti09** [comment]
best tool to merge pr's for me: gitkraken.

**Comment by wcastello** [comment]
Assuming the PR is some-pr on https://github.com/someone/PokemonGo-Map.git you can:
git checkout -b pr-test-xyz
git pull https://github.com/someone/PokemonGo-Map.git some-pr

After you're done,
git checkout -b develop
git branch -D pr-test-xyz

**Comment by cstewart90** [comment]
git fetch origin pull/ID/head:BRANCHNAME
git checkout BRANCHNAME

**Comment by pickett2k** [comment]
@wcastello sorry to bring this back up but still having difficulty, 

so if i was to do:

git checkout -b develop
git pull https://github.com/AHAAAAAAA/PokemonGo-Map.git 2319 (is this correct i just put the pull request number in?)

**Comment by cstewart90** [comment]
@pickett2k No. To do it that way you need to do this(Using #2728 as an example).

"blaulan  wants to merge 1 commit into AHAAAAAAA:develop from blaulan:develop" so you would need to `git pull https://github.com/blaulan/PokemonGo-map develop`

best to create a new branch first using `git checkout -b branchname` then git pull

Or you can do it using `git fetch origin pull/ID/head:BRANCHNAME` as I said in previous comment where you only need to know the ID.

**Comment by pickett2k** [comment]
@cstewart90 thanks for all ya help but somehow im sill having trouvle with this:

i type (for example) git fetch origin pull/1992/head:map_synergy

and it says it made a refs in the head folder but then doing a git pull doesnt give me the new PR files inwas trying to get?

thanks again for all your help with this
