### ISSUE TITLE
Question: Setting a webhook URL in config.ini

### ISSUE THREAD

**Issue by Unsworth94** [AHAAAAAAA/PokemonGo-Map#2368]
Is it possible to set a webhook URL inside the config.ini which all the searchers will use? I don't really want to pass the url(s) every time in the runserver.py call!

**Comment by andrewda** [comment]
Each line on the config.ini is equivalent to a command line argument. For example, the `location: <value>` line in the config.ini is the same as `--location <value>`. To specify a webhook, you would use the `--webhook` CLI argument, so just add a `webhook: <url>` parameter to your config.ini.

**Comment by Unsworth94** [comment]
awesome, thanks alot! :smile:
