### ISSUE TITLE
Make it clear if and when this application may violate the ToS

### ISSUE THREAD

**Issue by chalkos** [AHAAAAAAA/PokemonGo-Map#237]
This information is not clear in the README.

**Comment by magnum79** [comment]
it does violates the ToS, is not it obvious?

**Comment by chalkos** [comment]
I don't think it is like that for everyone. I have seen a bat install
script and a reddit post with a detailed guide on getting this to work. It
wouldn't surprise me if someone followed those instructions just to get
banned the following week without realising why.

Something like "using this software is against the ToS and can get you
banned. Use at your own risk" could help.

**Comment by JZ6** [comment]
"using this software is against the ToS and can get you banned. Use at your own risk"

**Comment by Zolomon** [comment]
I think @chalkos has an extremely valid point. Why was this issue closed?

**Comment by ngollan** [comment]
This should *at least* be a prominent part of the README. You are handwaving over a serious issue which is highly disrespectful of your users. (Granted, players should know that since they've read the ToS, but who am I kidding.)

**Comment by DerScreever** [comment]
@ngollan i will add this later.

**Comment by JZ6** [comment]
added to read me, closed
