### ISSUE TITLE
Uploading local PokemonGo-Map to the website

### ISSUE THREAD

**Issue by jtmantis** [AHAAAAAAA/PokemonGo-Map#2373]
Sorry if it has been asked before. But can we upload this map to our ftp server? I'm interested in having all pokestops and gym locations in my local area to be shown for people who visit my site url. And since these are static locations, maybe sript won't have to run all the time and wouldn't cause any problems?

**Comment by Gamewalker** [comment]
How to upload a dynamic map as static? Its changing all day expect pokestops and even they can be lured.

**Comment by Nicknack1234** [comment]
You sure can. The data is all there you just have to modify the code. You just have to ask is what your trying to achieve worth all the effort it would take?

**Comment by chuyskywalker** [comment]
No, neither the map nor the data behind it are static and this is not currently an option. I rather doubt anyone will open a PR to make it an option either. Sorry!
