### ISSUE TITLE
Config file stopping server start if poke: Gyms,Stops or Pokemon are set to false

### ISSUE THREAD

**Issue by kintera** [AHAAAAAAA/PokemonGo-Map#2377]
Config file Still an issue actually just updated the build "Latest commit 026b88e"  

runserver.py: error: no-gyms is a flag but is being set to false. 

I am running the latest git and have been way past issue #1372. been broken since my last report #2234 if you put the #back it will start or if set to true. But if you attempt to set it to false it will not allow the server to start.

This config will cause the issue:

```
Authentication settings

auth-service: ptc # ptc (default) or google
username: "Omitted"
password: "Omitted"

Database settings

db-type: sqlite # sqlite (default) or mysql
#db-host: # required for mysql
#db-name: # required for mysql
#db-user: # required for mysql
#db-pass: # required for mysql

Search settings

location: "omitted"
no-gyms: false # disables gym scanning (default false)
no-pokemon: false # disables pokemon scanning (default false)
no-pokestops: false # disables pokestop scanning (default false)
num-threads: 2 # number of search threads (default 1)
scan-delay: 5 # default 5
step-limit: 12 # default 12

Misc

gmaps-key: "key omitted"

Webserver settings

host: 10.0.0.6 # address to listen on (default 127.0.0.1)
port: 5000 # port to listen on (default 5000)

```

**Comment by wcastello** [comment]
You don't need to set the flags to false, they're false by default, just leave them commented or set them to true if you want.

**Comment by kintera** [comment]
well Aware but the system should allow for these to be set to false... not just un-commented out and set to true... If that is the case why even have a set able flag that looks for true? make it comment out or non to disable or enable it makes no sense as is....
