### ISSUE TITLE
automatic deployment to jelastic in not working. 

### ISSUE THREAD

**Issue by mimentorous** [AHAAAAAAA/PokemonGo-Map#2378]
Hi all. 
I tested jelastic deployment and it works if you don't change anything. 
Dut if you change location, it showing searching circles, in log shows that it sesrching.
But not displaying any pokes, gyms, pokestops... just empty map. 

I know that it can be changedand fixed in configs, but i don't know where to search. 
I know in windows, but not Linux.

**Comment by mimentorous** [comment]
Well as no one replied, i made it by myself.. 

All you need to do, is select your node, go to properties, and you will see a file tree. 

Select file ".jelstart"jelstart
And update all settings that you need. 

After that you need to restart a node. 
And it will work.


This also can be  added to wiki.

**Comment by mimentorous** [comment]
Well as no one replied, i made it by myself.. 

All you need to do, is select your node, go to properties, and you will see a file tree. 

Select file ".jelstart"jelstart
And update all settings that you need. 

After that you need to restart a node. 
And it will work.


This also can be  added to wiki.

**Comment by siruslan** [comment]
Have you changed only location or something else as well?

**Comment by mimentorous** [comment]
I put there my credentials, my API, and also change a range area to scan.

**Comment by mimentorous** [comment]
I know that this project can scan multiple locations, but i have no idea how to setup this in deployed to cloud version. 

If someone can share this info, will be nice!

**Comment by siruslan** [comment]
Have you tried to check Your Google or Your Pkmn Cloud Account radio button and put your credentials? it will save it permanently by default.

**Comment by mimentorous** [comment]
Not really sure what do you mean... 
But anyway, it works. Now i would like to improve it, by lunching multiple scans in different locations, instead of one huge location.
