### ISSUE TITLE
[Bug] Cant read location of device and set location to start scan 

### ISSUE THREAD

**Issue by WhiteO** [AHAAAAAAA/PokemonGo-Map#2385]
Cant read curent location on any browser (click geolocation button) but not set location and not scan to my location

**Comment by Nicknack1234** [comment]
Have you implemented HTTPS ? These features have been in the branch for a while but from what i understand they require a HTTPS connection to work, SSL has been implemented a few times to support these features but SSL keeps getting rolled back because of various implementation issues.

**Comment by chuyskywalker** [comment]
Yup, that'd be it. You can implement [a free ssl tunnel pretty easily with docker+ngrok](https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Docker#start-an-ssl-tunnel-unsupported), but if that's not your bag it's kinda up to you.
