### ISSUE TITLE
2.1.0 can't find "queue" module

### ISSUE THREAD

**Issue by diepflanzen** [AHAAAAAAA/PokemonGo-Map#2387]
Release 2.0.0 worked fine for me. But then release 2.1.0 used some new modules that I don't have. For example, module 'queue' was used in pogom/search.py, but then I can't find the module using pip.

It looks like a new module in python 2.7.12? but even after I updated to 2.7.12 with conda, queue still doesn't come with it. So I thought that looks like a rare package that many distributions and pip don't include.

## Your Environment

* Version used: 2.1.0
* Environment name and version (e.g. Python 2.7): 2.7.10/2.7.12, Conda distribution
* Operating System and version (desktop or mobile): Mac OS X El Capitan

**Comment by wcastello** [comment]
queue is builtin and OS X ships with python 2.7, so you don't need conda, is there any special reason for using it?

**Comment by diepflanzen** [comment]
I guess you're right. I don't really need it. I only used it because it was a convenient distribution for scientific use. Thanks for replying though~:P
