### ISSUE TITLE
Hello NEW to this! Need some noob advice..

### ISSUE THREAD

**Issue by george0wnz** [AHAAAAAAA/PokemonGo-Map#2394]
I just made my own page so i can drive around and scan. I am only having 1 issue and I am probably stupid to figure  out, but i am trying to add a way that i could scan at a drop point instead of having to type location in.  can someone help me do that please? I am using Heroku. Thanks ahead of time!

**Comment by chuyskywalker** [comment]
Please don't drive and Go. In fact, with this app you _do not need_ to be in the car "scanning" around, use it to find things, go directly their paying attention to the road :)

That said now, I believe that the map marker (red drop thing in the middle of the map) can be click-and-dragged to a new location to restart the scan over there.

**Comment by Birkbjo** [comment]
Well, this repo does not seem to have this feature, but I've implemented it in my forked repo.

They way I do it is to have a route that the client post to, and starts a thread that generates the locations given a step count and adds them to the location queue for the search threads to use. 
I'm not up to date on develop yet, but it's working really good for me. 

This way I can just add multiple locations to the queue and the search threads process them.
You can look at it here and try it out. 
https://github.com/Birkbjo/PokeMap
