### ISSUE TITLE
No credentials.json in my config folder, please help

### ISSUE THREAD

**Issue by chopstic** [AHAAAAAAA/PokemonGo-Map#2395]
So I am new to this, but in my config folder there is no "credentials" file to put my google maps api into, there is only a config.ini and that is all. Any advice or help?

**Comment by wcastello** [comment]
No more credentials.json, put your credentials on config.ini.

**Comment by aagulto** [comment]
So how to run config.ini?

**Comment by wcastello** [comment]
Text editor?

**Comment by aagulto** [comment]
Any advice?

![image](https://cloud.githubusercontent.com/assets/20647076/17200040/ddff2cce-544f-11e6-96c6-a7ba21b58aac.png)
