### ISSUE TITLE
ImportError: No module named flask_compress

### ISSUE THREAD

**Issue by TransModeV** [AHAAAAAAA/PokemonGo-Map#2398]
After running $ git pull origin master to updated tonight and updating to the new config.ini format. I started seeing below error.

## Expected Behavior

reach login and run scripts

## Current Behavior

Runs into the following error

$ python runserver.py -se -C
Traceback (most recent call last):
  File "runserver.py", line 13, in <module>
    from pogom.app import Pogom
  File "D:\PokemonGo-Map\pogom\app.py", line 9, in <module>
    from flask_compress import Compress
ImportError: No module named flask_compress

## Steps to Reproduce (for bugs)
I ran the with and with out the call to the config.ini and saw the same issue.

## Your Environment

Version used: Current Master
Environment name and version Python 2.7
Windows 10 Operating System Pro Desktop

**Comment by andrewda** [comment]
Did you `pip install -r requirements.txt`?

**Comment by TransModeV** [comment]
I did when I first installed, everything was working until I updated with git pull origin master.
Should I run the install again?

**Comment by JonahAragon** [comment]
It's best to reinstall requirements.txt every time you update from GitHub.

**Comment by TransModeV** [comment]
Andrewda, thanks I reran the pip install -r requirements.txt and that did the trick.. I will try that if I run into issues after updates going forward.. 

Thanks again!
TMV
