### ISSUE TITLE
Is there a support for dynamic location?

### ISSUE THREAD

**Issue by vminc** [AHAAAAAAA/PokemonGo-Map#2404]
Do we need to start the server with a fixed location or is it possible to support dynamic location based on what the client sends to the server?

**Comment by slashy** [comment]
You can set a new location manually from the maps Options menu, other than that there is (currently) no support for automatically sending the current clients location

**Comment by chuyskywalker** [comment]
The `develop` branch has geolocation support and will have searcher follow you.

**Comment by bergstar** [comment]
It is possible, check out https://github.com/bergstar/pogo-notifier
