### ISSUE TITLE
Disable config.ini when command line prompts being used

### ISSUE THREAD

**Issue by Valareos** [AHAAAAAAA/PokemonGo-Map#2408]
On latest Master build:

The previous build allowed me to use command line arguments to configure what I want done. As of the latest build, it seems to default to loading in the config.ini, even though I have NOT turned that flag on in command line (-se)

Now, obviously the config.ini file is preferred by some, but for me, I need to be able to run SEPERATE instances (using separate usernames/passwords) on same database.  This allows me to have several independent accounts scanning and adding to a single map for people to look at, and they only choose the port to connect to depending on their location.

Please give us an option to DISABLE the config file

**Comment by marauder37** [comment]
They work together, flags overwrite config.ini entries. You are also free to have an empty config file.

**Comment by Valareos** [comment]
Yes but when i tried to run with my old flags, it was demanding i fill in the config.ini file

And configuring the ini file is giving me some really silly error

runserver.py: error: unrecognized arguments: --Service google --Username b**** --Password **** --Steps 5 --Location -27.476490, 153.018340 --
Scan_delay 5 --Host 0.0.0.0 --Port 5001

**Comment by Valareos** [comment]
Ok figured it out, @marauder37 I had to completely empty the config.ini. Not sure why configuring it came up with those errors though

**Comment by marauder37** [comment]
Not sure either, glad it's working for you though!
