### ISSUE TITLE
No "credentials.json" file in config folder, cannot add Google Maps API Key

### ISSUE THREAD

**Issue by cloudsorghosts** [AHAAAAAAA/PokemonGo-Map#2409]
All tutorials I've been reading say to open the "credentials.json" file in the config folder of the PokemonGo-Map zipped documents to enter your Google Maps API Key. There is no "credentials.json" file in the folder, only "config.ini.example." As such Terminal is returning: "runserver.py: error: argument -k/--gmaps-key is required"

Mac OSX 10.9.5
Python 2.7

**Comment by wcastello** [comment]
Copy config.ini.example to config.ini, edit and put your credentials there in the right fields, there's no more credentials.json.

**Comment by cloudsorghosts** [comment]
I don't suppose someone could show me how to enter my credentials? New to this and it's unclear exactly what to enter and how to enter it.

**Comment by wcastello** [comment]
Just edit it with a text editor.

**Comment by ahoernke** [comment]
I as well am unclear on how to edit them
<img width="618" alt="screen shot 2016-07-30 at 2 12 41 pm" src="https://cloud.githubusercontent.com/assets/20744851/17272639/5421bac6-5661-11e6-885e-1e1c879c45ae.png">
