### ISSUE TITLE
Does honeycomb work with OSx

### ISSUE THREAD

**Issue by romero24** [AHAAAAAAA/PokemonGo-Map#2410]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by marauder37** [comment]
Yes

**Comment by romero24** [comment]
are these steps here https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/How-to-use-Hex-Beehive-Generator the same for mac because im pretty new with this. not having luck with creating a .bat file
