### ISSUE TITLE
Heroku Deployed- Multiple users scanning?

### ISSUE THREAD

**Issue by vallmanlgg4** [AHAAAAAAA/PokemonGo-Map#2411]
## Expected Behavior
One instance deployed, allowed multiple users to scan at a time.

## Current Behavior
If one user is scanning, and another starts, the previous users scan stops.

Currently deployed with Heroku, with no modifications made.

**Comment by kwstasna** [comment]
Of course this is the correct behavior cause the script doesnt work (at least as far as i know) for multiple users with one run...
