### ISSUE TITLE
[Request] MySQL Connection Pooling

### ISSUE THREAD

**Issue by kevinpark1217** [AHAAAAAAA/PokemonGo-Map#2412]
It would be great for someone to add MySQL pooling capability when inserting and replacing values in the database, so it would be possible for multiple people to contribute to a single large database. In current configuration, MySQL server would run out of ports to assign to a connection, since each query establishes a new connection.

**Comment by crckdns** [comment]
Same here, running 8 instances...

**Comment by kevinpark1217** [comment]
I might just consider duplicating this project and rework the entire SQL portion of the code. Current PRs and issues handling are so inefficient.

**Comment by marauder37** [comment]
Forks are encouraged! 

You will form a different view of what handling PRs is like after you've processed 700+ of them. I had a look at your earlier PR and it looks like it was merged in about a day, does that not meet your expectations?

**Comment by kevinpark1217** [comment]
@marauder37  My earlier fork was merged in about a day because there were only less than 30 PRs at the time. Now, the number of PRs are slowly increasing, meaning that PRs are no longer processed in timely manners. I like to make a change, test it, and push it to GitHub right away, so I can move onto another problem and repeat the process. But, the ever increasing PR delays are not going to help.

I have made many changes to this project on a local level to fix bugs, but have not PR anything since the first one due to this reason. Unless I become part of collaborators, it is unlikely that I will fork and do a PR.

**Comment by marauder37** [comment]
Sure, and that style of development won't work on a repo this busy. Of the ~70 open PRs, only 5 of them are in shape to be merged. In many cases the developer submitted then moved on, leaving an un-mergeable PR. I can see that your PR required maybe 4 rounds of rework before it was ready for merging. We are only able to accept PRs from developers who will be around for that process. If that doesn't work for you any more then I agree you should maintain your own repo.

**Comment by kevinpark1217** [comment]
@marauder37 Let me do a thing for this project. Let me host a MySQL server and a webserver with high capacity support to create a huge master map. Then, I will authorize preapproved users to be able to connect to the database. And ofc security too. If I do this can we make a deal to put it on a readme.md, so it can become popular.

**Comment by kevinpark1217** [comment]
@marauder37 Also this would help newbie people who don't have experience in Python and webserver, but want to be able to search Pokemons in a large region.

**Comment by marauder37** [comment]
If you set it up we'll certainly check it out

**Comment by crckdns** [comment]
With an option for non public MySQL I hope :D

**Comment by kevinpark1217** [comment]
@crckdns Yup. I already have the most of the part setup. To keep the unauthorized users out of the database, each worker would require a separate login. Also, there will be a secure firewall to deny any connection from an unknown ip address.

**Comment by crckdns** [comment]
In a decade of my IT security life I've seem only few sql servers who had bound external ip instead of localhost only ^^ in most cases it won't be needed as searcher and sqld are on same machine :D
