### ISSUE TITLE
Search thread failed. Response dictionary key error

### ISSUE THREAD

**Issue by MarcelDEV1337** [AHAAAAAAA/PokemonGo-Map#2417]
07-28 11:02:41,808 [        search] [  ERROR] Search thread failed. Response dictionary key error
2016-07-28 11:02:41,812 [        search] [  ERROR] Search thread failed. Response dictionary key error
2016-07-28 11:02:41,818 [        search] [  ERROR] Search thread failed. Response dictionary key error
2016-07-28 11:02:41,976 [        search] [  ERROR] Search thread failed. Response dictionary key error
2016-07-28 11:02:41,976 [        search] [  ERROR] Niantic servers under heavy load. Waiting before trying again

Login with Google Account.. v2.1

**Comment by EnigmaPatrick** [comment]
Seems like Niantic have changed something: https://pgorelease.nianticlabs.com/plfe/rpc

HTTP ERROR: 405

Problem accessing /plfe/rpc. Reason:

    HTTP method GET is not supported by this URL
Powered by Jetty://

**Comment by BlazeMuisNL** [comment]
Seems like they blocked requests outside the Pokemon Go Apps.

**Comment by Worthy7** [comment]
Omggggg

**Comment by LeoPerard** [comment]
Same here, from my logs:

> 2016-07-28 11:07:49,073 [     search] [   INFO] Scanning step 116 of 127 started.
> 2016-07-28 11:07:49,075 [     search] [   INFO] Scanning step 117 of 127 started.
> 2016-07-28 11:07:49,077 [     search] [   INFO] Scanning step 118 of 127 started.
> 2016-07-28 11:07:49,078 [     search] [   INFO] Scanning step 119 of 127 started.
> 2016-07-28 11:07:49,080 [     search] [   INFO] Scanning step 120 of 127 started.
> 2016-07-28 11:07:49,240 [     search] [  ERROR] Scan step 114 failed. Response dictionary key error.
> 2016-07-28 11:07:49,270 [     search] [  ERROR] Scan step 113 failed. Response dictionary key error.
> 2016-07-28 11:07:49,272 [     search] [  ERROR] Scan step 115 failed. Response dictionary key error.
> 2016-07-28 11:07:49,435 [     search] [  ERROR] Scan step 118 failed. Response dictionary key error.
> 2016-07-28 11:07:50,272 [     search] [   INFO] Completed 88.98% of scan.
> 2016-07-28 11:07:50,272 [     search] [   INFO] Completed 89.76% of scan.
> 2016-07-28 11:07:50,273 [     search] [   INFO] Completed 90.55% of scan.
> 2016-07-28 11:08:19,202 [    rpc_api] [WARNING] Unexpected HTTP server response - needs 200 got 502
> 2016-07-28 11:08:19,203 [     search] [   INFO] Map Download failed. Trying again.
> 2016-07-28 11:08:19,204 [    rpc_api] [WARNING] Unexpected HTTP server response - needs 200 got 502
> 2016-07-28 11:08:19,205 [     search] [   INFO] Map Download failed. Trying again.
> 2016-07-28 11:08:19,212 [    rpc_api] [WARNING] Unexpected HTTP server response - needs 200 got 502
> 2016-07-28 11:08:19,213 [     search] [   INFO] Map Download failed. Trying again.
> 2016-07-28 11:08:19,324 [    rpc_api] [WARNING] Unexpected HTTP server response - needs 200 got 502
> 2016-07-28 11:08:19,325 [     search] [   INFO] Map Download failed. Trying again.
> 2016-07-28 11:08:19,361 [     search] [  ERROR] Scan step 116 failed. Response dictionary key error.
> 2016-07-28 11:08:19,371 [     search] [  ERROR] Scan step 117 failed. Response dictionary key error.
> 2016-07-28 11:08:19,474 [     search] [  ERROR] Scan step 119 failed. Response dictionary key error.
> 2016-07-28 11:08:19,827 [     search] [  ERROR] Scan step 120 failed. Response dictionary key error.

**Comment by smeagol91** [comment]
Same here.
`2016-07-28 11:11:38,152 [        search] [  ERROR] Search thread failed. Response dictionary key error
2016-07-28 11:12:08,513 [       rpc_api] [WARNING] Unexpected HTTP server response - needs 200 got 502
2016-07-28 11:12:08,515 [        search] [   INFO] Map download failed, waiting and retrying
2016-07-28 11:12:14,146 [        search] [  ERROR] Search thread failed. Response dictionary key error
2016-07-28 11:12:14,147 [        search] [  ERROR] Niantic servers under heavy load. Waiting before trying again`

**Comment by SOLiNARY** [comment]
Well some of my workers started & work.
But most of them DO NOT.

**Comment by leTokki** [comment]
Servers are unstable perhaps? People are reporting that they can't login on some other websites.

**Comment by MegaJigglypuff714** [comment]
I was about to say that I also have this issue but it seems to be working, just VERY slowly. Probably unstable servers as leTokki said.

**Comment by EnigmaPatrick** [comment]
I'd hope so, blocking 3rd Party completely especially while the 3 step is fucked would just be stupid.

**Comment by nikmess** [comment]
Same for me, every other scan step or so seems to work. Probably just server issues.

**Comment by nbdnbdnbd** [comment]
"Minor text fixes"

**Comment by MarcelDEV1337** [comment]
It works ;) 
2016-07-28 11:42:51,895 [        models] [   INFO] Upserted 1 pokemon, 0 pokestops, and 0 gyms
