### ISSUE TITLE
I can not find the credentials.json file inside the PokemonGo-Map folder

### ISSUE THREAD

**Issue by duanpingbo** [AHAAAAAAA/PokemonGo-Map#2418]
When I reach "Step 4: Get your own Google Maps API Key", I can't find the credentials.json file. Where is it?

**Comment by smeagol91** [comment]
It was moved to `config/config.ini`

**Comment by Silvikk** [comment]
just add a command -k your_api

**Comment by marauder37** [comment]
WHere is this "step 4", I'll go edit it

**Comment by dev-masta** [comment]
I believe it's in "Windows installation" in Wiki:

https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Windows-Installation-and-requirements

**Comment by marauder37** [comment]
ok I've tried to clean it up a bit
