### ISSUE TITLE
Error running command

### ISSUE THREAD

**Issue by MaryGualtieri** [AHAAAAAAA/PokemonGo-Map#242]
When running python example.py ```-u Username -p password -l "Boulder, CO" -st 5```, I get

```
Traceback (most recent call last):
  File "example.py", line 32, in <module>
    from gpsoauth import perform_master_login, perform_oauth
ImportError: No module named gpsoauth
```

Please advise.

**Comment by Trael** [comment]
I got the same - There are new dependencies, should be resolved by running the pip install command again.

**Comment by micksh6** [comment]
I ran pip install 5 times. It always gives the error below. Then python example.py gives the same error as in original post.
Just installed Python 2.7.11 and rebooted. Windows 8.1 x64. pip install error:

Command ""c:\program files\python2.7\python.exe" -c "import setuptools, tokenize
;__file__='g:\\temp\\pip-build-oxlozb\\pycryptodomex\\setup.py';exec(compile(get
attr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, '
exec'))" install --record g:\temp\pip-cwzbvl-record\install-record.txt --single-
version-externally-managed --compile" failed with error code 1 in g:\temp\pip-bu
ild-oxlozb\pycryptodomex

You are using pip version 7.1.2, however version 8.1.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' comm
and.

**Comment by micksh6** [comment]
OK, I upgraded pip as it advised and now it works. Thank you, author!

**Comment by RaamPrashanth** [comment]
Still facing the issue even after upgrading pip and reinstalling gpsoauth

Traceback (most recent call last):
  File "example.py", line 26, in <module>
    from gpsoauth import perform_master_login, perform_oauth
ImportError: No module named gpsoauth

**Comment by MaryGualtieri** [comment]
If you rerun pip install --upgrade -r requirements.txt after you do a git pull, that should fix it.
