### ISSUE TITLE
Blank Page

### ISSUE THREAD

**Issue by darkcloud784** [AHAAAAAAA/PokemonGo-Map#243]
I get a blank page that says "Flask Google Maps Full Map Example". Using Chrome, updated and cache cleared. Console says "[18/Jul/2016 22:18:23] "GET / HTTP/1.1" 200 -
- - [18/Jul/2016 22:18:24] "GET /favicon.ico HTTP/1.1" 404 -
- - [18/Jul/2016 22:18:27] "GET / HTTP/1.1" 200 -"

**Comment by JZ6** [comment]
fixed

**Comment by darkcloud784** [comment]
Issue still present, on newest commit. Same issue.
