### ISSUE TITLE
[Feature Request] Phone notifications

### ISSUE THREAD

**Issue by Zerotask** [AHAAAAAAA/PokemonGo-Map#2432]
It would be awesome to get notifications on your phone when using it as a web app (Mine is installed on an ubuntu server).
Example: https://goroost.com/try-web-push

**Comment by wschoot** [comment]
I'm using the webhook functionality to post to slack and pushover but this sounds nice too!

**Comment by andrewda** [comment]
As @wschoot said, use webhooks.
