### ISSUE TITLE
Slow after new update

### ISSUE THREAD

**Issue by TheMainAttractionHomie** [AHAAAAAAA/PokemonGo-Map#2440]
I have download the new master and am running it and watching the scanned locations go much slower than before. Have I made a mistake somewhere?

**Comment by mackhankins** [comment]
Set your scan delay to 2 I think is the fix. -sd 2

**Comment by TheMainAttractionHomie** [comment]
Thank you so much for such a fast and helpful response, you fixed it.

**Comment by mackhankins** [comment]
Close the issue please and glad I could help.
