### ISSUE TITLE
using config.ini with multiple accounts?

### ISSUE THREAD

**Issue by rayuki** [AHAAAAAAA/PokemonGo-Map#2441]
with the new update there is now the option to use a config.ini

im currently just running a .bat file since im running 40 PTC accounts scanning a big area, however wouldn't mind using the config if this makes things easier (setting mysql database etc)

can we use it with multiple accounts just by adding more accounts to the config? how do we link each account to each location or am i just going to have to keep running my .bat file.

**Comment by SOLiNARY** [comment]
Just put common configuration into config which is shared between ur accounts. and then use arguments when u need to specify differentiations.
example:
mysql connection in config
but user accounts given through argument.

`python runserver.py -ns -u user -p pass -st 3`
it will take arguments u didnt specify from config

**Comment by rayuki** [comment]
ok awesome thanks.
