### ISSUE TITLE
Found Pokes eventually form a ring around searched location and nothing refreshes on actual location searched.

### ISSUE THREAD

**Issue by lighter857** [AHAAAAAAA/PokemonGo-Map#2445]
I leave my browser open on particular location so it keeps scanning the same area.
Eventually the found pokes start create a circle around the area searched and nothing is showed there unless to switch a street over as it restarts the search in the area.

## Expected Behavior
Is it suppose to keep re scanning the same area if left open? 

## Current Behavior
Create a circle of pokes around the original search area and keeps getting farther and farther away

![poke ring](https://cloud.githubusercontent.com/assets/15316855/17216425/9df9fc62-54ae-11e6-809b-ee096035fbe5.png)

This is picture is after approximately 20 - 25 mins the browser is left open on the same area. In the start there were pokes in the initial searched area. I switch over to side street the missing inner circle will start to fill in again.

No particular to a browser as if I open this on my iPhone it will look like this as well. I have attempted to clear cache and history thinking it might be browser related but happens on multiple devices.

**Comment by Forza4Development** [comment]
This is as expected.  When Pokemon expire, they disappear from the map.  A ring just means that it is taking a long time to scan the entire hexagon, so long in fact, that the inner Pokemon start to disappear.  These are removed automatically.  Try  Increasing -t and decreasing -sd.  -t is the number of unique workers that will scan the hexagon.  -sd is the scan delay in between each scanned area.

**Comment by lighter857** [comment]
Forza, I have not set a -sd. I am using whatever the default is. Would you be able to tell me what the default is just so I have baseline as to where to start.

**Comment by stevenpratt** [comment]
The -sd default recently switched from 1 to 5 (second delay).

**Comment by lighter857** [comment]
Thanks fellas... I'll give that a shot and see.
