### ISSUE TITLE
Scanning slow. How to change scan delay on Heroku

### ISSUE THREAD

**Issue by Encouraging** [AHAAAAAAA/PokemonGo-Map#2447]
Hello, I am encountering an issue with 2.1 where the scan speed is so slow. People are saying to change the scan delay back to 1 and change the threads. I need help doing this on Heroku and i currently have no clue how to lmfao. Thanks

**Comment by F10XDE** [comment]
Login to your Heroku dashboard. Go to the "settings" tab > Click "reveal config vars". Add your lines to the "EXTRA_ARGS" field.

**Comment by Encouraging** [comment]
What would the extra lines be? Would it be SCAN_DELAY and the value set to 1?

**Comment by F10XDE** [comment]
-sd 1

**Comment by Seik** [comment]
![4b11b1bc067f06b37669d425910a4215](https://cloud.githubusercontent.com/assets/9640279/17217418/95e3f056-54e4-11e6-9b56-2455cdd59238.png)

**Comment by Encouraging** [comment]
Thank you everyone!
