### ISSUE TITLE
version 2.1.0 slow search, low cpu ussage(multithread??)

### ISSUE THREAD

**Issue by demono01** [AHAAAAAAA/PokemonGo-Map#2459]
## Expected Behavior
so if u added multithreading we expected decent cpu usage not 2% on single core from 4

## Current Behavior
slow search, very slow vs version 2.0.0 but i need to admit its more precise

## Possible Solution
no idea

## Steps to Reproduce (for bugs)
no idea
1.
2.
3.
4.

## Context
faster searching

## Your Environment

* Version used: 2.1.0
* python 2.7
* Operating System and version (desktop or mobile): win 10 pro

**Comment by stevenpratt** [comment]
I'm not sure in what version it changed but the -sd default was recently upped from 1 to 5 (second delay). Try the flag -sd 5 and you can up the threads using -t.

**Comment by stryker007** [comment]
The sweet spot I've found for a 17 step map is -sd 3 -t 7

**Comment by Crazy-Drew** [comment]
If I am running this through Heroku, any quick idea of how to implement this change?

**Comment by demono01** [comment]
stevenpratt thank u very much !!
with options -sd 1 -t 10 it works like a charm

**Comment by M0rr1son** [comment]
@Crazy-Drew How i change it: http://prnt.sc/bypbux and here you can see all flags https://www.jonaharagon.com/PoGoMapWiki/#!Usage.md

**Comment by Crazy-Drew** [comment]
Flawless, I was in the right section but wasn't sure how to write it out correctly. THANK YOU! way faster!

**Comment by noob4real** [comment]
@Crazy-Drew how does it work for you? I'm using heruko too. Can you upload a screenshot of your settings please :) it would be a great help

**Comment by Crazy-Drew** [comment]
@noob4real I am on my phone and can't upload a graphic but in heroku, go to setting for that app, tap config variables and under step count enter this in there.
STEP_COUNT:    8 -t 1 -sd 0.2
