### ISSUE TITLE
Latest update seem to be an older version

### ISSUE THREAD

**Issue by mkorsak** [AHAAAAAAA/PokemonGo-Map#2464]
I deployed a new server today pulling from git, and it seems to be running an older version of the app, where Pokemon take far longer to load, and has the glitch again where pokemon start to disappear in a circle, making a ring outside of them.

**Comment by F10XDE** [comment]
This has been mentioned a few times if you have a look in the closed section of this board. They've introduced threading and increased the step delay to 5 seconds from 1 for the default settings.
You can go back to the old settings by defining: "-sd 1 -t 4"

Theres no issue regarding the pokemons dispearing from the center of the circle, they're just expiring before the search restarts. However at default that shouldn't be happening unless you've been too greedy with your steps, reduce this to max 10-12. or look into using beehive.

**Comment by mkorsak** [comment]
I've been using 15 steps. Just checked again, and now I have a small group in the middle, giant gap, and small outside ring. You're right in that I guess it's just expiring before the next iteration. In past builds eventually it would stop running iterations and leave the map blank, but I guess that hasn't happened yet. What does the 4 mean in in your step delay options there?

**Comment by F10XDE** [comment]
Threads use it, it'll do more blocks per scan

**Comment by wcastello** [comment]
Find usage help here: https://discordapp.com/channels/204338767920758785/204339169458126849
And here: https://github.com/AHAAAAAAA/PokemonGo-Map/wiki
