### ISSUE TITLE
runserver.py: error: no-pokemon is a flag but is being set to 'false'

### ISSUE THREAD

**Issue by aagulto** [AHAAAAAAA/PokemonGo-Map#2467]
Any advice? Thank you!

**Comment by wcastello** [comment]
Do not set it to false. The flag is only meant to be set to true. It's false by default, just leave it with a #. 
Find usage help here: https://discordapp.com/channels/204338767920758785/204339169458126849
And here: https://github.com/AHAAAAAAA/PokemonGo-Map/wiki
