### ISSUE TITLE
Bug: current location not working on iOS Safari

### ISSUE THREAD

**Issue by heldertb** [AHAAAAAAA/PokemonGo-Map#2469]
## Expected Behavior
Track current location when turned on

## Current Behavior
Cannot get current location from iOS device

## Possible Solution
Probably change the code of getting your location to work with iOS

## Steps to Reproduce (for bugs)
Try and get your location on iOS

## Your Environment

* Version used: 2.1
* Environment name and version (e.g. Python 2.7): 2.7
* Operating System and version (desktop or mobile): mobile (iOS 10)

**Comment by HazyArc14** [comment]
Are you using https? I noticed this wasn't working on my iPhone running iOS 10 until I used https.

**Comment by heldertb** [comment]
Yep using no https fixes the problem. Thanx :)

**Comment by commanderjsoc** [comment]
@heldertb please close issue if this fixes your problem

**Comment by heldertb** [comment]
Apparently after some more using, it's still not working. I even tried it on iOS 9 and same issue...

**Comment by commanderjsoc** [comment]
@heldertb make sure that location services are enabled for safari/chrome/firefox. Also make sure that the server is not using a beehive or multiple locations

**Comment by heldertb** [comment]
@commanderjsoc Of course everything is turned on. Beehive/multiple locations not applicable. The problem is that the site does not ask for permission to use your location.

**Comment by heldertb** [comment]
I've found the reason after some digging, you actually need https traffic on iOS 9+.
Is there a guide on how to add a certificate to the web server?
