### ISSUE TITLE
!!!Map Download failed!!!

### ISSUE THREAD

**Issue by Gambode** [AHAAAAAAA/PokemonGo-Map#2476]
Since 2 hours i getting this error

` [    rpc_api] [WARNING] Unexpected HTTP server response - needs 200 got 502
 [     search] [   INFO] Map Download failed. Trying again.`
got this error again and again

The Map apears on the specific adress but it didnt start to scan.

what i tried for now:

->make a new API Key didnt helped
->reinstall the complete map and python didnt helped
->tried a different gmail account didnt helped

anyone can help?

sorry for bad english^^

greetz
Gambo

**Comment by 123456abcdef** [comment]
Niantic servers are overloaded, nothing you can do just wait.

**Comment by commanderjsoc** [comment]
http://ispokemongodownornot.com/

**Comment by Hoekynl** [comment]
@Gambode 
This is a normal error, that means that the Niantic authentication servers are down.
Check their status on ispokemongodownornot.com

**Comment by commanderjsoc** [comment]
@Hoekynl Beat you to it ;)

**Comment by Arderos** [comment]
I can login and play from the smartphone, but still catch the Map download failed error
