### ISSUE TITLE
How to config the new settings

### ISSUE THREAD

**Issue by GodForm** [AHAAAAAAA/PokemonGo-Map#2482]
Guys the scan is going really slow and i dont know how to change the new Config.ini setting, looks like it's not working

**Comment by dudenell** [comment]
Change the number of threads

**Comment by PaleHaunt** [comment]
I can't figure out how to change this either... Can someone please detail this, on how? Sorry... very new to this.

**Comment by Xaldeon** [comment]
The scan delay has been defaulted to 5. Edit your config.ini as followed

scan-delay:             1

**Comment by PaleHaunt** [comment]
The only config.ini I find is config.ini.example. Is this the file?

**Comment by Xaldeon** [comment]
Rename it to config.ini and edit it

**Comment by PaleHaunt** [comment]
OK. One more stupid question. I changed the name, edited the file, and it's running the same speed. Do I leave the file in the config folder, or move it to another directory? And Thank you for the help!

**Comment by Pringles91** [comment]
im having the same issue with VERY slow scans, yesturday it was working fine, today its horrible :(

**Comment by Xaldeon** [comment]
It's working fine for me by just renaming the config.ini and editing the line for scan-delay. Make sure you're running the latest version from the developer branch

**Comment by Pringles91** [comment]
you changed the scan delay to 1 and the threads to what? also, may be a stupid question but how do i know if im running the latest version, and i assume you mean the pokemon go map master winrar?

**Comment by Xaldeon** [comment]
https://github.com/AHAAAAAAA/PokemonGo-Map/archive/develop.zip

**Comment by PaleHaunt** [comment]
I am running the latest version (as of an hour ago) and I must be brain farting. haha OK, changed the name of the config.ini.example file to config.ini. I LEAVE this file in the config folder. I change the #num-threads:           # default 5
#scan-delay:            # default 1

save, run the script in Terminal... Same speed. Slow. :(

**Comment by Xaldeon** [comment]
Make sure to remove the "#". The "#" comments out the lines in the config.

**Comment by mwillems1994** [comment]
You need to remove the # because the # tells the code that that is a comment, so it skips it

**Comment by Pringles91** [comment]
so, when i renamed the config.ini.example to config.ini that made 2 config.ini files in the folder, is this the way its supposed to be?

**Comment by Pringles91** [comment]
after i renamed the file, edited it and close and reopen the program, im getting 1 cell scan every 5 or so seconds.

**Comment by PaleHaunt** [comment]
I feel like an idiot... LOL

OK, so this is how the file reads. What is wrong?

# Authentication settings
#auth-service:          # ptc (default) or google
#username:
#password:

# Database settings
#db-type: sqlite        # sqlite (default) or mysql
#db-host:               # required for mysql
#db-name:               # required for mysql
#db-user:               # required for mysql
#db-pass:               # required for mysql

# Search settings
#location:
#no-gyms:               # disables gym scanning (default false)
#no-pokemon:            # disables pokemon scanning (default false)
#no-pokestops:          # disables pokestop scanning (default false)
num-threads:            default 5
scan-delay:             default 1
#step-limit:            # default 12

# Misc
#gmaps-key:             # your Google Maps API key
#webhook:               # webhook URL (including http://)

# Webserver settings
#host:                  # address to listen on (default 127.0.0.1)
#port:                  # port to listen on (default 5000)

**Comment by Xaldeon** [comment]
Remove the default text -__-

**Comment by marogers** [comment]
Like Xaldeon said.  The relevant lines should be:
num-threads: 5
scan-delay: 1

**Comment by PaleHaunt** [comment]
And... That worked. Thank you guys, very much!

**Comment by Pringles91** [comment]
so is one file supposed to have the default and everything left alone? and the other changed?

**Comment by andrewda** [comment]
@Pringles91 what? The word `default` should never be used as a value in your `config.ini` file, it's just there to tell you what the default value is if the parameter is left unset.

**Comment by Pringles91** [comment]
when i renamed my config.ini.example file, there was already one just called config.ini, and ive never messed with any of this before, i deleted the folder and extracted the winrar file again. and there was only the config.ini.example file, so i renamed it, changed the lines and still running slow. im super sorry if this is getting frustrating, im very new to this stuff. :/

**Comment by andrewda** [comment]
@Pringles91 What does your `config.ini` look like now?

**Comment by Pringles91** [comment]
# Authentication settings
#auth-service:          # ptc (default) or google
#username:
#password:

# Database settings
#db-type: sqlite        # sqlite (default) or mysql
#db-host:               # required for mysql
#db-name:               # required for mysql
#db-user:               # required for mysql
#db-pass:               # required for mysql

# Search settings
#location:
#no-gyms:               # disables gym scanning (default false)
#no-pokemon:            # disables pokemon scanning (default false)
#no-pokestops:          # disables pokestop scanning (default false)
#num-threads:           5
#scan-delay:            1
#step-limit:            # default 12

# Misc
#gmaps-key:             # your Google Maps API key
#webhook:               # webhook URL (including http://)

# Webserver settings
#host:                  # address to listen on (default 127.0.0.1)
#port:                  # port to listen on (default 5000)

**Comment by PaleHaunt** [comment]
Pringles, make your renames config.ini file look like this...

<img width="453" alt="screen shot 2016-07-28 at 1 36 49 pm" src="https://cloud.githubusercontent.com/assets/20708511/17224899/7b018d32-54c8-11e6-8d3b-24018a13a911.png">

**Comment by Pringles91** [comment]
getting errors now....lol ughh

**Comment by Pringles91** [comment]
ok errors are gone, but STILL taking forever to scan. is that an extra space after num-threads: 5 or just one space? or doesnt it matter?

**Comment by marogers** [comment]
Spaces/tabs don't matter.  Are you working with the latest from the develop branch?

**Comment by Pringles91** [comment]
im trying to find the link to it, but no luck, someone above posted the link but its not working for me

**Comment by marogers** [comment]
![2016-07-28_1332](https://cloud.githubusercontent.com/assets/16496896/17228456/e3bb787a-54c7-11e6-9e2f-e50106e18f72.png)

**Comment by Pringles91** [comment]
when i downloaded the v2.1 i edited the config.ini file i run the easy set up and get an error that says "traceback (most recent call last):
 File "<sting>"/ line 1, in <module>
IOError: [Errno 2] No such file or directory: 'config.ini.example'
ALL done!

**Comment by marogers** [comment]
Sorry I'm not familiar with the easy setup method of running the project.  I've been running the server directly through the command line (which seems to pick up the config.ini values that aren't specified in the command line):
`python runserver.py -u xxxxx -p xxxxxxx -l "11.111111 -111.1111111" -st 12`

**Comment by Pringles91** [comment]
i just thought if i deleted the file i would have to run the setup, they may have fixed that in a later version, i deleted the folder, and extracted it again, changed the values, and it runs, no errors, but still VERY slow scanning

**Comment by Pringles91** [comment]
it is also NOT scanning 5 threads at a time, still only 1

**Comment by marogers** [comment]
Hmm I'm not sure what file you're deleting.  When I download the latest from develop I unzip it in to a new folder so I don't have to worry about old files since the project is changing so rapidly.  I rename config.ini.example to config.ini and modify it to the following:

```
# Authentication settings
auth-service:			ptc
username:				xxxxxx
password:				xxxxxx

# Database settings
db-type: sqlite			sqlite
#db-host:               # required for mysql
#db-name:               # required for mysql
#db-user:               # required for mysql
#db-pass:               # required for mysql

# Search settings
location:				"11.111111 -111.1111111"
#no-gyms:               # disables gym scanning (default false)
#no-pokemon:            # disables pokemon scanning (default false)
#no-pokestops:          # disables pokestop scanning (default false)
num-threads:			20
scan-delay:				0
step-limit:				12

# Misc
gmaps-key:				xxxxxxxxxxxxxxxxxxxxxxx
#webhook:               # webhook URL (including http://)

# Webserver settings
#host:                  # address to listen on (default 127.0.0.1)
#port:                  # port to listen on (default 5000)

#Uncomment a line when you want to change its default value (Remove # at the beginning)
#username, password, location and gmaps-key are required
```

Then run the command in my previous comment.  I can see in the command line that it upserts several times a second which I would call fast.

Sorry I can't be of more help.

**Comment by Pringles91** [comment]
you have to add the end there where it starts out #Uncomment a line so on and so forth?

**Comment by marogers** [comment]
No.  Any content after a hashmark until the end of the line are ignored by the program.  I just copied the entire file for clarity.

**Comment by Pringles91** [comment]
kk, i tried the cammand you previously posed and got the error : argument -k/--gmaps-key is required. i noticed the google map key is not in the command. what happen to the old command that was more like this 

python runserver.py -a google -u xxxxxx -p xxxx -st 25 -k xxxxxxx -l "xxxxxxx"

**Comment by marogers** [comment]
Did you add your Google maps API key to the config.ini file as this line shows from the copy of my config.ini?
`gmaps-key:              xxxxxxxxxxxxxxxxxxxxxxx`

**Comment by Pringles91** [comment]
yeah

**Comment by Pringles91** [comment]
it works when i use that command i commented, but its still scanning SOOOOO slow, it upserts about once every 10 seconds on average

**Comment by Pringles91** [comment]
# Authentication settings
auth-service:          ptc
username:               xxxx
password:		xxxxxx

 Database settings
db-type: sqlite         sqlite
#db-host:               # required for mysql
#db-name:               # required for mysql
#db-user:               # required for mysql
#db-pass:               # required for mysql

# Search settings
location:		"xxxxxxxxx"
#no-gyms:               # disables gym scanning (default false)
#no-pokemon:            # disables pokemon scanning (default false)
#no-pokestops:          # disables pokestop scanning (default false)
num-threads:           20
scan-delay:            0
step-limit:            12

# Misc
gmaps-key:             xxxxxxxx
#webhook:               # webhook URL (including http://)

# Webserver settings
#host:                  # address to listen on (default 127.0.0.1)
#port:                  # port to listen on (default 5000)

**Comment by Pringles91** [comment]
the weirdest part about all of this is that it worked GREAT until around 1am est time this morning. since then its just been SLOWWWW

**Comment by Pringles91** [comment]
Made sure i followed your instructions to download latest version, after extracting to a new folder, i opened config folder, and the config.ini file is no longer called config.ini.example it is just called config.ini BUT it is called an "example file under the "type" section

**Comment by marogers** [comment]
Perhaps the slowness you're seeing is due to the server problems today.  If we're in parity in terms of config/run command then I imagine the problem is something external.

**Comment by Pringles91** [comment]
only reason i would say no to that, is that someone was just saying theirs was working great earlier. i feel as if SOMETHING is not right with my file. is the config.ini supposed to be an "example" "type"?

**Comment by marogers** [comment]
No the program will ignore any files that aren't `.ini`.

**Comment by Pringles91** [comment]
right, so im pretty sure that is my new problem at hand, ive downloaded the v2.1 file a couple times now and the only file in the config folder is named config.ini, type: EXAMPLE and 1kb size.

**Comment by marogers** [comment]
You may have to turn on the "File name extensions" checkbox in folder view settings such that you can modify the file extension from `.example` to `.ini`.  If you're on Windows 10 click the View tab in your file explorer and check the "File name extensions" checkbox.

**Comment by Pringles91** [comment]
that worked, now im going to copy your steps from above and see what happens

**Comment by Pringles91** [comment]
i copied everything you stated from above, and its having issues logging in, says there could be problems with the server. it never said that before tho. so i might have it correct now

the error says "no json object could be decoded...."

**Comment by Pringles91** [comment]
also says could not retrieve token and that it disabled my account for 15 min

**Comment by marogers** [comment]
I have also been seeing errors related to pulling data from Niantic servers.

**Comment by Pringles91** [comment]
well hopfully i have everything correct now and its just a server issue! i really appreciate all the help, as soon as something works, or doesnt work i will post and let you know the outcome, youve been a huge help man!

**Comment by Pringles91** [comment]
quick question. even when its niantic servers not working proporly, will it still say that your account has been disabled due to not properly logging in multiple times? i made sure my account and password are correct, and the code seems to be in correlation with the pic you sent above

**Comment by Pringles91** [comment]
it is saying my username or password is incorrect. ive double checked and its not lol

**Comment by Pringles91** [comment]
i tried running with the command as follows
python runserver.py -a google -u xxxxxx -p xxxxxxx -st 25 -k xxxxxxx -l "xxxxxx"

and it logs in but gives me this error

search thread failed. response dictionary key error   -----  is this on my end for sure or no?

it upserts a few times, and then gives the error, then says niantic servers are under heady load, waiting before trying again.

**Comment by marogers** [comment]
That error is not from you. I get that when Niantic's servers are having a hard time.

**Comment by Pringles91** [comment]
its up and running for me! if i set the settings to 20 threads and 0 delay it seems to overload it and not work

**Comment by Pringles91** [comment]
best i can get is 5 threads and 2 delay
