### ISSUE TITLE
Add Support for Multiple Accounts & Scanning Locations

### ISSUE THREAD

**Issue by gnu-user** [AHAAAAAAA/PokemonGo-Map#2483]
Love the PokemonGo-Map project! I have a recommendation for functionality I think would be very useful. Essentially adding support for having each of the scanning threads use a different account and possibly a different starting location, this would make the map populate and stay up to date much faster as you could have multiple accounts scanning different parts of a city, for example in a large city such as NYC.

If no one has time to implement this I may try and submit a pull request, however I'm noticing that the rate of development for this project is very quick, so my pull request may have too many conflicts by the time I have this feature implemented.

If there's anyone with more time on their hands that would like to add this feature, I think it would be very worthwhile.

**Comment by Xaldeon** [comment]
https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/How-to-use-Hex-Beehive-Generator

**Comment by Crazy-Clown** [comment]
What I've done is just wrote a simple batch command to launch several other batch files (in Windows) using start file.bat etc... which  includes the command:
C:\Python27\Python.exe runserver.py -l "LOCATION" -st 7 -ns   (the -ns means it wont launch the web server).  So just run the first batch file with the web server, and running additional location batch scripts will integrate all into the same database.  I have 16 locations going at the same time with no problems.

**Comment by DaVinci0072** [comment]
Several locations with the same account? Isn't that a perfect setup to get a ban?

**Comment by Crazy-Clown** [comment]
> Several locations with the same account? Isn't that a perfect setup to get a ban?

Perhaps.  You could also add in the -a AUTH -u EMAIL@ADDRESS.COM -p PASSWORD inside each batch file to separate the accounts.

I haven't had issues really, but we'll see.

**Comment by gnu-user** [comment]
@Crazy-Clown

**Comment by gnu-user** [comment]
@Crazy-Clown Thanks for that tip, I think that pretty much solves the issue.
