### ISSUE TITLE
runserver.py error: argument -k/--gmaps-key is required

### ISSUE THREAD

**Issue by AllegroStudio** [AHAAAAAAA/PokemonGo-Map#2487]
I did edit the config.ini and have provided a key:

```
[Misc]
#you need a google maps api key to run this!
Google_Maps_API_Key: [key here]
Host: 127.0.0.1
Port: 5000
```

## Your Environment

* Version used: 2.1
* Environment name and version (e.g. Python 2.7): Python 2.7.12
* Operating System and version (desktop or mobile): Windows 10

**Comment by SpeckledTrout** [comment]
Not sure what you're copying your config.ini from but look in the config/config.ini.example 

config.ini doesn't contain subsections like [Misc] so you can safely remove that line entirely.

and it should be
gmaps-key:             # your Google Maps API key

**Comment by wcastello** [comment]
`# Authentication settings
#auth-service:          # ptc (default) or google
#username:
#password:

# Database settings
#db-type: sqlite        # sqlite (default) or mysql
#db-host:               # required for mysql
#db-name:               # required for mysql
#db-user:               # required for mysql
#db-pass:               # required for mysql

# Search settings
#location:
#no-gyms:               # disables gym scanning (default false)
#no-pokemon:            # disables pokemon scanning (default false)
#no-pokestops:          # disables pokestop scanning (default false)
#num-threads:           # number of search threads (default 1)
#scan-delay:            # default 5
#step-limit:            # default 12

# Misc
#gmaps-key:             # your Google Maps API key
#webhook:               # webhook URL (including http://)

# Webserver settings
#host:                  # address to listen on (default 127.0.0.1)
#port:                  # port to listen on (default 5000)

#Uncomment a line when you want to change its default value (Remove # at the beginning)
#username, password, location and gmaps-key are required`

Find usage help here: https://discordapp.com/channels/204338767920758785/204339169458126849
And here: https://github.com/AHAAAAAAA/PokemonGo-Map/wiki
