### ISSUE TITLE
How to find credentials.json in the configuration of API Key

### ISSUE THREAD

**Issue by FerGm28** [AHAAAAAAA/PokemonGo-Map#2488]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: env-7891422.whelastic.net
* Environment name and version (e.g. Python 2.7): Docker 
* Operating System and version (desktop or mobile): Windows 10 & IOS

**Comment by hgentry** [comment]
Best thread

**Comment by medghaim** [comment]
The form is there for a reason. Fill it out.
