### ISSUE TITLE
Steps 15-25 not moving according to logged coordinates

### ISSUE THREAD

**Issue by hhu94** [AHAAAAAAA/PokemonGo-Map#249]
Using -st 5, steps 15 to 25 result in the exact same coordinates being scanned, not movement. Tested in 2 different locations.

### Environment info
Operating System:
Arch Linux

Installed version of Python:
2.7.12

### Steps to reproduce
1. Use the script and check the coordinates logged from steps 15 to 25

### Logs or other output that would be helpful
[log.txt](https://github.com/AHAAAAAAA/PokemonGo-Map/files/370641/log.txt)

**Comment by amal** [comment]
confirmed

**Comment by macgngsta** [comment]
it seems that by step 16 the if loop that increments the movement fails to execute (line 591):

```
if -steplimit / 2 < x <= steplimit / 2 and -steplimit / 2 < y \
            <= steplimit / 2:
```

**Comment by kevvv** [comment]
Been running on 6 and 8 steps recently and have been noticing that it is indeed missing certain spots on the map.  Couldn't really pinpoint what it was though.

**Comment by JZ6** [comment]
fixed
