### ISSUE TITLE
Google Login Failed

### ISSUE THREAD

**Issue by Lorkster** [AHAAAAAAA/PokemonGo-Map#2499]
A few hours ago the google login stopped working for a Heroku dyno I restarted. At the moment I had login issues on my main account too, but those seem to have resolved

## Expected Behavior
Google login should work.

## Current Behavior
Login nor working. Logs show repeated:
```2016-07-28T20:24:00.102723+00:00 app[web.1]: 2016-07-28 20:24:00,102 [   auth_google] [   INFO] Google Login failed.
2016-07-28T20:24:00.102821+00:00 app[web.1]: 2016-07-28 20:24:00,102 [        search] [   INFO] Failed to login to Pokemon Go. Trying again in 5 seconds.
2016-07-28T20:24:05.226643+00:00 app[web.1]: 2016-07-28 20:24:05,226 [        search] [   INFO] Failed to login to Pokemon Go. Trying again in 5 seconds.```

## Possible Solution
At least better debug logs, in the case the login failure can give indications about what's going on.

## Steps to Reproduce (for bugs)
For me just trying to start the Heroku dyno.

## Your Environment
Have both tried with master and develop branches, pushed to Heroku.

**Comment by georgo** [comment]
Yes. Servers are down. You can verify uptime here: http://ispokemongodownornot.com/

**Comment by Lorkster** [comment]
I am managing to login on my phone though. Tried rebooting the phone a couple of time to verify that there wasn't any caching going on.

**Comment by georgo** [comment]
Yeah, it's about luck in that moment. Trust me, Pokemon Go servers are struggling today.

**Comment by Critplank** [comment]
I'm also having this issue. It seems like if it was the servers it'd be working by now.

**Comment by Lorkster** [comment]
It might be that the app is timing out too quickly during the login process. The login servers are definitely stressed, but they are working and I get in every single time on my phone (and another app for that matter).

**Comment by Lorkster** [comment]
What I think happened in my case is that due to the too short wait for a successful login, the repeated tries to login caused my Google account to get locked due to "Suspicious activity". A longer timeout, or a configurable one, would be a nice addition.
