### ISSUE TITLE
Javascript Error

### ISSUE THREAD

**Issue by rlyons20** [AHAAAAAAA/PokemonGo-Map#2504]
I am running the server on Ubuntu.  I just downloaded the new build, and i'm trying to configure it.

I can get the runserver.py to start just fine, but I'm getting a javascript error when I try to connect to the webserver.

I did read the wiki on the google api, and i have triple checked that the java api is enabled.

Please help.

**Comment by DoraKlikOpDora** [comment]
Do you have specified your own API key, the default API-key is probably already used the max amount of times..

**Comment by rlyons20** [comment]
yup.  i specified my key in config/credentials.json, then used the switch -k config/credentials.json

**Comment by rlyons20** [comment]
disregard. i just put the key into the -k switch, and now everything is working.

Thanks!
