### ISSUE TITLE
Nearby pokemon are not being added with higher step counts

### ISSUE THREAD

**Issue by MrThreepwood** [AHAAAAAAA/PokemonGo-Map#2509]
When using a higher step count (like 20), only pokemon along the outer ring are being populated, rather than populating the entire area. This issue also occurs at 10.

## Steps to Reproduce (for bugs)
1. Start the server with a higher number of steps (10 or higher)
2. Wait a while, an hour plus if you like.
Results: Pokemon are populated in the outer ring, but the center is left empty.

## Context
I've set up a server to query multiple PokemonGo-Maps and amalgamate the area, storing the spawn information for future analysis. I was hoping to have servers running at higher step counts to reduce the number of them I would need to Run.

## Your Environment
I'm using Python 2.7 on my Mac with the code base from commit #2275

**Comment by DoraKlikOpDora** [comment]
This can be because of a low thread number. If your steps higher up, you should also higher up your thread count to keep looking for recent pokemons. The higher the steps, the longer it takes before the scanner gets back in the middle of the circle.

**Comment by MonkeyGoneWIld** [comment]
You can turn on scanned locations to better understand the Issue
It might be that the step delay is too long when you have it at higher steps
Try decreasing the step delay down to 1 (or 0) and see if that helps solve the Issue

**Comment by noob4real** [comment]
@MonkeyGoneWIld @DoraKlikOpDora I have a question regarding Heroku deployment. Since the release of 2.1.0 my scanning has been slower and after a while just stops. Some have recommended to higher up my `-t 10` because I have my stepcounts to 10.

Do you guys have any recommendations on what settings are the best to have faster scanning because right now it is slower than 2.0 version. Thank you!

**Comment by plasticlobster** [comment]
I get errors if I go over -t 3. I use -t 3 -sd 2, and I get about 6 "circles" per second to scan and no errors on the backend.

**Comment by MonkeyGoneWIld** [comment]
I use:
scan-delay: 0         
step-limit: 5 
num-threads: 2

and it take 25 sec for each loop

**Comment by DoraKlikOpDora** [comment]
I can not give you a recommendation, since I am running this on am external linux server. I think the recommendation of @MonkeyGoneWIld is the one you need.
