### ISSUE TITLE
Error on starting

### ISSUE THREAD

**Issue by NZJohn** [AHAAAAAAA/PokemonGo-Map#2514]
I get the following error on starting up. Anyone able to resolve this for me?

[Image](http://puu.sh/qhXk4/ce3aebe42c.png)

**Comment by marogers** [comment]
You're missing the module listed in the error.  Try running the below commands while in the base directory:
`pip install -r requirements.txt`
`pip install -r requirements.txt --upgrade`

**Comment by NZJohn** [comment]
Legend! All is working now. Thank you very much!
