### ISSUE TITLE
Can't expose the map to local network/internet.

### ISSUE THREAD

**Issue by padmanek** [AHAAAAAAA/PokemonGo-Map#2516]
I've forwarded the default port (5000) to the PC I'm running the map on but I can't access it all.
The port is forwarded correctly because when I simply do "python -m SimpleHTTPServer 5000" I can easily access the folder from both the internet and the local network.
I'm on W10 Pro. Any ideas?

**Comment by Paralysing** [comment]
Did you add -H 0.0.0.0 and -P PORT? -H 0.0.0.0 accepts connections from anywhere.

**Comment by padmanek** [comment]
damn, -h was set to default , setting it to 0.0.0.0 fixed the issue. Closing.
