### ISSUE TITLE
Config.ini - Have Key - Still have error.

### ISSUE THREAD

**Issue by Invaderofbunnie** [AHAAAAAAA/PokemonGo-Map#2519]
**Completely new to scripts** 

## Expected Behavior
I'm wanting the script to run the map. 

## Current Behavior
When I run python runserver.py -a ptc -u ********* -p **********-l "41.5149054 -90.4618398" -st 10

This is the message received:
 
Usage: runserver.py [-h] [-a AUTH_SERVICE] [-u USERNAME] [-p PASSWORD]
                    [-l LOCATION] [-st STEP_LIMIT] [-sd SCAN_DELAY]
                    [-td THREAD_DELAY] [-ld LOGIN_DELAY] [-dc] [-H HOST]
                    [-P PORT] [-L LOCALE] [-c] [-d] [-m] [-ns] [-os] [-fl] -k
                    GMAPS_KEY [-C] [-D DB] [-t NUM_THREADS] [-np] [-ng] [-nk]
                    [--db-type DB_TYPE] [--db-name DB_NAME]
                    [--db-user DB_USER] [--db-pass DB_PASS]
                    [--db-host DB_HOST] [-wh [WEBHOOKS [WEBHOOKS ...]]]
runserver.py: error: argument -k/--gmaps-key is required

## Possible Solution
From what I understand It has to do with editing the Config.ini file. I only had the Config.Ini.example file and from a previous thread it stated to just rename is Config.ini. 

I edited the gmaps-key:  to the gmaps key I created and attempted to re-run the script and recieved the same error. 

What am I doing wrong? 
The config.ini file has (# -pound sign/ number sign) in front of it.. Do I remove them? 

This is my config.ini file: 

# Authentication settings
#auth-service:          # ptc (default) or google
#username:		
#password:		

# Database settings
#db-type: sqlite        # sqlite (default) or mysql
#db-host:               # required for mysql
#db-name:               # required for mysql
#db-user:               # required for mysql
#db-pass:               # required for mysql

# Search settings
#location:
#no-gyms:               # disables gym scanning (default false)
#no-pokemon:            # disables pokemon scanning (default false)
#no-pokestops:          # disables pokestop scanning (default false)
#num-threads:           # number of search threads (default 1)
#scan-delay:            # default 5
#step-limit:            # default 12

# Misc
#gmaps-key:             # (Im not sure if keys are security info but i have the key in here)
#webhook:               # webhook URL (including http://)

# Webserver settings
#host:                  # address to listen on (default 127.0.0.1)
#port:                  # port to listen on (default 5000)

## Your Environment

* Version used: 2.7.7
Windows 10 - Laptop

**Comment by Dragonprovidence** [comment]
Did you make sure to uncomment the lines? (remove the starting # from the setting lines)

**Comment by HitmanUK1** [comment]
# means ignore line, so just remove it and you should be good to go.

**Comment by Invaderofbunnie** [comment]
Oh my...Am trying now... please hold... :P

**Comment by Invaderofbunnie** [comment]
Do i remove them from every single one?

**Comment by marogers** [comment]
Only the lines you modified with values you want to use.

**Comment by Invaderofbunnie** [comment]
Ok removed the pound sign marks - 

Now getting this error

runserver.py: error: Unexpected line 13 in C:\Python27\PokemonGo-Map-master\pogom\../config/config.ini: location:

**Comment by marogers** [comment]
Did you remove the hashtag from the `location:` line?

**Comment by Invaderofbunnie** [comment]
Yes I did Marogers.. I'm trying to figure out which hashtags to remove and which not to.

**Comment by Invaderofbunnie** [comment]
# Authentication settings
auth-service:          # ptc (default) or google
username:              ***
password:              ****

# Database settings
db-type: sqlite        # sqlite (default) or mysql
db-host:               # required for mysql
db-name:               # required for mysql
db-user:               # required for mysql
db-pass:               # required for mysql

# Search settings
#location:
#no-gyms:               # disables gym scanning (default false)
#no-pokemon:            # disables pokemon scanning (default false)
#no-pokestops:          # disables pokestop scanning (default false)
#num-threads:           # number of search threads (default 1)
#scan-delay:            # default 5
#step-limit:            # default 12

# Misc
gmaps-key:             # (key here]
webhook:               # webhook URL (including http://)

# Webserver settings
host:                  # address to listen on (default 127.0.0.1)
port:                  # port to listen on (default 5000)


^^^^^^^^^^ current config.ini

Error: 
usage: runserver.py [-h] [-a AUTH_SERVICE] [-u USERNAME] [-p PASSWORD]
                    [-l LOCATION] [-st STEP_LIMIT] [-sd SCAN_DELAY]
                    [-td THREAD_DELAY] [-ld LOGIN_DELAY] [-dc] [-H HOST]
                    [-P PORT] [-L LOCALE] [-c] [-d] [-m] [-ns] [-os] [-fl] -k
                    GMAPS_KEY [-C] [-D DB] [-t NUM_THREADS] [-np] [-ng] [-nk]
                    [--db-type DB_TYPE] [--db-name DB_NAME]
                    [--db-user DB_USER] [--db-pass DB_PASS]
                    [--db-host DB_HOST] [-wh [WEBHOOKS [WEBHOOKS ...]]]
runserver.py: error: argument -P/--port: invalid int value: ' '

**Comment by marogers** [comment]
Hashtags make the program ignore all content _after_ the hashtag so you'll want to modify:
`gmaps-key: # (key here]` should be:
`gmaps-key: [key here]`
And you can re-add hashtags before the `db-` lines since you didn't add in values for those lines.

**Comment by reyqn** [comment]
You shouldn't remove the sharp from the host and port line if you want to stay with defaults.

**Comment by robinbastien** [comment]
Remove only the hashtags at the start of the line, and make sure to add the hashtags back to host and port

**Comment by robinbastien** [comment]
Also put quotations around your google API key since it's a string :)

**Comment by Invaderofbunnie** [comment]
You guys are amazing!!!!!!!!!!!
I got it going. Thank you all so much for helping this little newbie out!!!!! Thank you thank you thank you!!!

**Comment by Dragonprovidence** [comment]
Glad to hear you got it working

**Comment by Invaderofbunnie** [comment]
quick question the st-10 at the end of the thread to run the script stands for how many steps per/minute? 
what does this value do if make it higher/lower?

**Comment by Dragonprovidence** [comment]
It affects your search area

**Comment by Invaderofbunnie** [comment]
Is it in terms of feet or inches or...steps? 
I'm sorry forgive my ignorance!!

**Comment by Dragonprovidence** [comment]
I'm unsure the exact measurements, but checking it out yourself like what @robinbastien said will be the quickest way to understand.

**Comment by Invaderofbunnie** [comment]
Thank you all very much for your help!!! and for not eating me alive :)

**Comment by FrostTheFox** [comment]
Issue is solved?

**Comment by Invaderofbunnie** [comment]
Yes thank you very much @FrostTheFox  - I will close the comments. Everyone has been so helpful!
