### ISSUE TITLE
Linux Python

### ISSUE THREAD

**Issue by HitmanUK1** [AHAAAAAAA/PokemonGo-Map#2521]
Hi Guys,

Someone may know this but it is possible to run one screen instance on Linux for multiple places? but with different ptc accounts? 

Hope that makes sense...

Ta

**Comment by Dragonprovidence** [comment]
You can run multiple search servers and have just one server hosting to web, if that is what you mean.

https://www.jonaharagon.com/PoGoMapWiki/#!beehive.md

-ns - No-Server Mode. Starts the searcher but not the Webserver.
https://www.jonaharagon.com/PoGoMapWiki/#!Usage.md

**Comment by HitmanUK1** [comment]
Ill have to give the beehive ago, but with -ns I would need to run multiple screens I believe, thanks anyways :D
