### ISSUE TITLE
web page for the map says google maps did not load correctly. 

### ISSUE THREAD

**Issue by lyon812345** [AHAAAAAAA/PokemonGo-Map#2522]
## Expected Behavior
I want to load up the map. (localhost:5000)

## Current Behavior
I run the the python runserver.py -a ptc -u ********* -p **********-l "41.5149054 -90.4618398" -st 10 with ease but when I try to load the map it shows this. 

https://gyazo.com/8be70199e4b6c94fb4a548554f77577c

## Steps to Reproduce (for bugs)
Here is my config.ini text since that is where the api code is.
 # Authentication settings
#auth-service:          # ptc (default) or google
#username:
#password:

# Database settings
#db-type: sqlite        # sqlite (default) or mysql
#db-host:               # required for mysql
#db-name:               # required for mysql
#db-user:               # required for mysql
#db-pass:               # required for mysql

# Search settings
#location:
#no-gyms:               # disables gym scanning (default false)
#no-pokemon:            # disables pokemon scanning (default false)
#no-pokestops:          # disables pokestop scanning (default false)
#num-threads:           # number of search threads (default 1)
#scan-delay:            # default 5
#step-limit:            # default 12

# Misc
gmaps-key:             
#webhook:               # webhook URL (including http://)

# Webserver settings
#host:                  # address to listen on (default 127.0.0.1)
#port:                  # port to listen on (default 5000)

#Uncomment a line when you want to change its default value (Remove # at the beginning)
#username, password, location and gmaps-key are required

**# I removed my gmaps key for security concerns but other than that everything else is the same.** 

## Your Environment
Version used: 2.7.7  Mac  OS X El Capitan Version 10.11.6

**Comment by noob4real** [comment]
I had a similar issue earlier. Sorry to inform you that my advice is probably the noob advice but what I did was just create a new Google Map API according to the Wiki and it started working for me again. Hope this helps.

**Comment by lisandro52** [comment]
How did you entered your key?
Like this: `"YOUR_GMAPS_KEY"` (notice the double quotes)?

**Comment by lyon812345** [comment]
@lisandro52 nope i just entered the key and removed the # from the line

**Comment by lyon812345** [comment]
@noob4real Still did not work :(

**Comment by lisandro52** [comment]
Can you show us a screenshot from your javascript console? (by pressing F12 on most browsers)

**Comment by lyon812345** [comment]
@lisandro52 
![screen shot 2016-07-28 at 4 25 55 pm](https://cloud.githubusercontent.com/assets/6926388/17235853/03cfe66a-54e0-11e6-8b0a-ef9dca076a5b.png)

**Comment by lisandro52** [comment]
The error says `ApiNotActivatedMapError`. Have you tried enabling the APIs like [this guide says](https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Google-Maps-API-Key) on point **5**?

**Comment by amazedchili** [comment]
Most obvious error is that your Gmaps API has not been activated. Make sure you have the API enabled in the Web console in addition to the key you generated. There's a button you need to press.

**Comment by interbiznw** [comment]
Google Maps Javascript API not activated or your API Key is entered incorrectly

**Comment by lyon812345** [comment]
@interbiznw @lisandro52 @amazedchili Thank you so much! Forgot about that last part for the api key.
