### ISSUE TITLE
Pokemon Go can't open file 

### ISSUE THREAD

**Issue by Shazam2143** [AHAAAAAAA/PokemonGo-Map#2525]
When I try to create the pokemon go app and launch the final command for set up it say that python cant open the file and that the file doesn't exist. 

## Current Behavior
C:\Python27\python.exe: can't open file 'example.py': [Errno 2] No such file or directory
I don't know how to open the file. 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by medghaim** [comment]
oh no

**Comment by invisiblek** [comment]
you should really read the instructions...

**Comment by medghaim** [comment]
@AHAAAAAAA @JZ6 @invisiblek @FrostTheFox WE NEED HELP, STAT.

**Comment by Shazam2143** [comment]
It worked yesterday and I actually had the map but it wouldn't load pokemon now I can't run python and I don't know what I did wrong.
