### ISSUE TITLE
Response Errors

### ISSUE THREAD

**Issue by jasonfoy21** [AHAAAAAAA/PokemonGo-Map#2532]
Python 2.7.12
NPM 3.5.2
node 4.2.6
git branch   6363f6c  
Ubuntu 16

I get these when the thread is higher than 4, if setup to 10 the entire set of requests errors out and runs through a delay prior to a second attempt.

2016-07-28 21:30:29,439 [	Search] Search thread failed. Response dictionary key error.

**Comment by Nicknack1234** [comment]
https://github.com/AHAAAAAAA/PokemonGo-Map/issues/2513

**Comment by Nebulation** [comment]
Been a common problem around here. You need to set your delay to 1 and your thread to 3. That's what I  have and it is effective.

**Comment by MonkeyGoneWIld** [comment]
Thats just because pokemon servers cant respond fast enough, its recommmended to keep Number of threads at 3 or lower unless you increase scan delay

**Comment by jasonfoy21** [comment]
Okay, thanks for the information guys.
