### ISSUE TITLE
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

### ISSUE THREAD

**Issue by xwxv** [AHAAAAAAA/PokemonGo-Map#2539]
keep getting this error
idk what to do about it
I'm running OS X el capitan

tried to re-install and re-run everything
gave me the same result
pls help

**Comment by leonelgalan** [comment]
Do you see the file? It's there (on the repo) https://github.com/AHAAAAAAA/PokemonGo-Map/blob/master/requirements.txt, if you delete it accidentally just download it again.

**Comment by MonkeyGoneWIld** [comment]
did you run this command "pip install -r requirements.txt"?

**Comment by xwxv** [comment]
i have the file and ya i've followed the wiki (and even videos) step by step

**Comment by xwxv** [comment]
![screen shot 2016-07-29 at 12 53 20 am](https://cloud.githubusercontent.com/assets/20717238/17238122/ea52ade8-5526-11e6-899f-82e574ec34f3.png)
this is where i've gotten so far
can't seem to get past this
did i goof somewhere along the line there?

**Comment by j178** [comment]
please change your current directory to which containg the `requirements.txt`

**Comment by xwxv** [comment]
what that mean
how i do that
(im pos rook ik, but I'm trying)

**Comment by andrewda** [comment]
`cd PokemonGo-Map` or wherever your PokemonGo-Map directory is downloaded to.

**Comment by xwxv** [comment]
wow
im an idiot, thank you guys
