### ISSUE TITLE
got that error after leaving the thing run for a bit

### ISSUE THREAD

**Issue by thu2468** [AHAAAAAAA/PokemonGo-Map#254]
https://smallpaste.in/view/578db01fa46da104178b4567

**Comment by Octylpy** [comment]
Are you still able to access the web page after it shows that error?

**Comment by HenrySia** [comment]
@thu2468 what version of python are you using?

**Comment by macrojames** [comment]
Page should still load. I am using Flask a lot and this happens on double refreshes or some GoogleChrome prefetching.

**Comment by JZ6** [comment]
fixed
