### ISSUE TITLE
AttributeError AttributeError: lat and lng required

### ISSUE THREAD

**Issue by arturoaviles** [AHAAAAAAA/PokemonGo-Map#255]
### Environment info
Operating System: Mac OS 10.11.4

Installed version of Python: 2.7.11

### Steps to reproduce
1. git clone https://github.com/AHAAAAAAA/PokemonGo-Map.git
2. cd PokemonGo-Map/
3. pip install -r requirements.txt
4. python example.py -a authService -u myUsername -p myPassword -l "lat, lon" -st 5

myUsername and myPassword where my Google Username

**Comment by Octylpy** [comment]
That happens when you try to load the webpage before it is able to retrieve  data on any Pokemon. Try giving it a minute a try again.

**Comment by abdilahrf** [comment]
same with me 
i have wait 15 min and still same @Octylpy

**Comment by Octylpy** [comment]
@abdilahrf Are you using a street address or lat/lng coordinates?

**Comment by abdilahrf** [comment]
i just forget to set  -a to ptc now it's working

**Comment by Scyntrus** [comment]
Should have been fixed by https://github.com/AHAAAAAAA/PokemonGo-Map/pull/241

**Comment by JZ6** [comment]
fixed

**Comment by arturoaviles** [comment]
@abdilahrf what's ptc? Thanks
