### ISSUE TITLE
Broken Commit! (Removed dist files from Git)

### ISSUE THREAD

**Issue by kevinpark1217** [AHAAAAAAA/PokemonGo-Map#2550]
Please revert this commit since it breaks basically all of the functionality on the website.
 ["Removed dist files from Git" #2384](https://github.com/AHAAAAAAA/PokemonGo-Map/pull/2384)

This commit results in this.
![Problem](https://i.gyazo.com/107fca36108bba44625e72f075507875.png)

**Comment by numb401** [comment]
https://github.com/AHAAAAAAA/PokemonGo-Map/issues/2544
got to run 3 lines of code and it'll work again

**Comment by adbspurs** [comment]
@numb401 Care to provide Windows instructions? Ta!

**Comment by numb401** [comment]
@adbspurs Those are windows instructions. First install node.js, then run those 3 commands in the root pogomap directory. If that fails, install the master branch.

**Comment by marauder37** [comment]
Windows people might need to get Node.js from https://nodejs.org/en/ first

**Comment by matpag** [comment]
This commit blocked everybody who didn't use Node.js to compile files... (50% of people using this project probably)

**Comment by Mr-Protocol** [comment]
I had an error with npm install grunt-cli and had to apply this fix.

> digitalmediums commented on Sep 27, 2012
I've found this is often a misnaming error, if you install from a package manager you bin may be called nodejs so you just need to symlink it like so "ln -s /usr/bin/nodejs /usr/bin/node"

I get an error with the ./node_modules/.bin/grunt build command.

Loading "sass.js" tasks...ERROR
Error: ENOENT: no such file or directory, scandir '/PokemonGo-Map/node_modules/node-sass/vendor'

Help?
