### ISSUE TITLE
How to stop the recurring loop?

### ISSUE THREAD

**Issue by mahavidhan** [AHAAAAAAA/PokemonGo-Map#2561]
Finally I got this to work and it looks wonderful. Thanks for this awesome map. I wish to know how to stop the recurring loop of scanning locations. I setup the command line to scan 3 steps and once 3 steps are over it come back to the mid point and starts scanning again. How to stop the command line command after completing 3 steps? Thanks

EDIT : I actually want to monitor 14 pokestops in different locations (3 steps for each pokestop). Is there a way to create a batch file where I can enter coordinates of those 14 pokestops and run the batch file so that it scans 3 steps for each pokestops and do this for all 14 pokestops and stop it there.

**Comment by mortasgus** [comment]
Hello @mahavidhan 

Could you tell us a little more about your operating system.

by default, i will say ...
CTRL + C 
 :-)

**Comment by mahavidhan** [comment]
Thank you for your reply. I am using Windows 7 and I know CTRL+C is to manually stop the process. I want to stop it automatically after 3 steps scanning is over. Moreover, I am also looking for a batch file as explained in my first post that I edited later.

**Comment by Dragonprovidence** [comment]
Not sure if any of the releases have this option. Once the server starts, the search threads just go on and on. I would guess you'll have to modify search loop in search py, or control the thread somehow.

**Comment by mahavidhan** [comment]
omg! modify search.py. I dont have the expertise to control the thread if that is what it means technically :) There has to be some way and someone may have discovered something like what I am expecting. I will have to wait patiently I guess for a solution or may be for the next release.

**Comment by mahavidhan** [comment]
I didnt undestand the reason for four downvotes. Its a valid question I guess. Having a batch file that scans 3 steps for every pokestop one after the other using its coordinates will be easier to monitor for nearby pokemons, gym details and lured pokestops.

**Comment by SOLiNARY** [comment]
open `search.py`

find this patch of code:

```
def search_loop(args):
    i = 0
    try:
        while True:
            log.info("Map iteration: {}".format(i))
            search(args, i)
            log.info("Scanning complete.")
            if args.scan_delay > 1:
                log.info('Waiting {:d} seconds before beginning new scan.'.format(args.scan_delay))
                time.sleep(args.scan_delay)
            i += 1

    # This seems appropriate
    except Exception as e:
        log.info('{0.__class__.__name__}: {0} - waiting {1} sec(s) before restarting'.format(e, args.scan_delay))
        time.sleep(args.scan_delay)
        search_loop(args)
```

change it to:

```
def search_loop(args):
    i = 0
    try:
		log.info("Map iteration: {}".format(i))
		search(args, i)
		log.info("Scanning complete.")
		if args.scan_delay > 1:
			log.info('Waiting {:d} seconds before beginning new scan.'.format(args.scan_delay))
			time.sleep(args.scan_delay)
		i += 1

    # This seems appropriate
    except Exception as e:
        log.info('{0.__class__.__name__}: {0} - waiting {1} sec(s) before restarting'.format(e, args.scan_delay))
        time.sleep(args.scan_delay)
        search_loop(args)
```

**Comment by mahavidhan** [comment]
Thank you for your reply.
1. The patch of code you sent was little different in my search.py file. (see below)
2. I still replaced the patch of code that i had in my file to the one you sent. Result - It does stop scanning but it does not exit out to the command prompt. I still have to manually stop it using CTRL+C.
```
#
# Search Overseer
#
def search_loop(args):
    i = 0
    while True:
        log.info("Search loop {} starting".format(i))
        try:
            search(args, i)
            log.info("Search loop {} complete.".format(i))
            i += 1
        except Exception as e:
            log.error('Scanning error @ {0.__class__.__name__}: {0}'.format(e))
        finally:
            if args.thread_delay > 0:
                log.info('Waiting {:g} seconds before beginning new scan.'.format(args.thread_delay))
                time.sleep(args.thread_delay)
```

**Comment by SOLiNARY** [comment]
add

`quit()`

to interrupt execution

def search_loop(args):
    i = 0
        log.info("Search loop {} starting".format(i))
        try:
            search(args, i)
            log.info("Search loop {} complete.".format(i))
            i += 1
        except Exception as e:
            log.error('Scanning error @ {0.__class__.__name__}: {0}'.format(e))
        finally:
            quit()

**Comment by mahavidhan** [comment]
After making the changes, first it gave me an error on line `log.info("Search loop {} complete.".format(i))`
IndentationError: unexpected indent
Then I tried adding `while True:` above the line `log.info("Search loop {} starting".format(i))` and it worked but did not come out to the command prompt even after entering quit().
It halted at line Search loop 0 complete
Then i copy-pasted the above changes you gave without any indentation but i got an error on line `i = 0`
IndentationError: expected an indented block

??? :(

**Comment by mahavidhan** [comment]
i played with indentation a bit and got it working with this piece of code but again, it does not terminate with quit(). The cursor keeps blinking after saying Search loop 0 complete. It does quit/terminate and does not come to command prompt 
```
def search_loop(args):
    i = 0
    log.info("Search loop {} starting".format(i))
    try:
        search(args, i)
        log.info("Search loop {} complete.".format(i))
        i += 1
    except Exception as e:
        log.error('Scanning error @ {0.__class__.__name__}: {0}'.format(e))
    finally:
        quit()
```
