### ISSUE TITLE
[FEATURE REQUEST]Mail notification as option

### ISSUE THREAD

**Issue by sharklab** [AHAAAAAAA/PokemonGo-Map#2570]
As title, and can someone help me to find the notification part in the code?

Thanks and great job!

**Comment by wschoot** [comment]
You can use webhooks to call to some URL which mails you about pokemon on the map. Webhooks we're added a few days back in commit https://github.com/AHAAAAAAA/PokemonGo-Map/commit/f6dbab4b2c3564098bca7a7953bd419a82f65fed
