### ISSUE TITLE
Is it possible to run runserver.py more than once at the same time using different google accounts.

### ISSUE THREAD

**Issue by photex12** [AHAAAAAAA/PokemonGo-Map#2571]
What I would like to do is run the server (for example 4 times) on the same location but with different google accounts.
This to make all pokemon load faster.
Course running the server multiple times means there will be 4 servers writng to the database.
Also should I use 4 different ports than?

Or am I going about this all wrong and is there another way?

**Comment by mortasgus** [comment]
yes you can
#2546
