### ISSUE TITLE
Is it possible set different locations for different threads?

### ISSUE THREAD

**Issue by Pereck** [AHAAAAAAA/PokemonGo-Map#2575]
For now, i can't set different locations for different threads. Is it possible? Because i need to share my machine with my friends.

Thank you

**Comment by hd1080** [comment]
Yes this is possible, just start another process in no-server mode (-ns) and with different location.
For me it looks like this: `python runserver.py -ns -l "23.133926, 8.577753"`
You can also add different thread value, username, password, ... than in your config file.

**Comment by Pereck** [comment]
Ok, thank you. But after i start the no-server, is there a way to change its location from the map? Or must i restart it?

**Comment by commanderjsoc** [comment]
@Pereck I'm pretty sure you just have to restart it... sorry
