### ISSUE TITLE
Search thread failed. Response dictionary key error

### ISSUE THREAD

**Issue by shpapy** [AHAAAAAAA/PokemonGo-Map#2579]
getting the error above plus this msg "search] [ ERROR] Niantic servers under heavy load. Waiting before trying again"
whilst the servers are up and running and i didnt hit the API cap.

Steps to Reproduce

python runserver.py

OS: Elementary OS

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

to map t

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):
desktop - Elementary os Python 2.7

**Comment by reactortrip** [comment]
I get that when I up the threads. If I lower the threads, it works.

**Comment by MarcelDEV1337** [comment]
3 Threads max.

**Comment by Schwaitz** [comment]
@MarcelDEV1337 I used to run about 9 servers with 5-10 threads each, and it would work fine. Why am I now running into this problem?

**Comment by TJohnson93** [comment]
@Schwaitz Seems that Niantic has throttled the amount of connections at a time (possibly by IP?)

**Comment by Schwaitz** [comment]
@TJohnson93 Confirmed. Also confirming that it is by account, not IP.

**Comment by TJohnson93** [comment]
@Schwaitz ahh cool... thanks, that's helpful to know!!

**Comment by xomikronx** [comment]
@Schwaitz I think they are throttling now.  I can run 3 threads just fine, anything over and I get `Niantic servers under heavy load. Waiting before trying again`

**Comment by reactortrip** [comment]
They have done something else as well to mask some spawns.  I'm not getting half the spawns I use to and I haven't seen a rare in awhile.  I use to see rares quite frequently.

**Comment by TJohnson93** [comment]
@reactortrip Yeah I found the same...
