### ISSUE TITLE
there is no credentials.json in my config

### ISSUE THREAD

**Issue by Antonijow** [AHAAAAAAA/PokemonGo-Map#2586]
i tried using the homebrow wiki and got the map to my documents but then it says to put my API Key in the credentials.json in config, however there is no credentials.json at all in my PokemonGo Map. what am i  doing wrong?

**Comment by willgrnr** [comment]
I guess the documentation needs to be updated. Modify config.ini.example with your info and rename to config.ini

**Comment by Antonijow** [comment]
thank you, i got it to work

**Comment by ahoernke** [comment]
When I open that file, I have tried many ways to putting in my info and my code, and cannot get it to work. am I typing it in the wrong area of the document? How does this have to be formatted for it to run correctly. Any help would be awesome. 
<img width="618" alt="screen shot 2016-07-30 at 2 12 41 pm" src="https://cloud.githubusercontent.com/assets/20744851/17272584/c81d6cba-565f-11e6-8c5f-4a0b69b220a3.png">

**Comment by willgrnr** [comment]
Update to the newest version, and at the bottom of that file it'll explain what to do.
