### ISSUE TITLE
Response dictionary key error.

### ISSUE THREAD

**Issue by HurfeyDurfey** [AHAAAAAAA/PokemonGo-Map#2588]
Any ideas?
<img width="353" alt="screen shot 2016-07-29 at 9 02 54 am" src="https://cloud.githubusercontent.com/assets/20724952/17249113/67851f18-556c-11e6-80aa-91a3a2c70c71.png">

**Comment by reactortrip** [comment]
Too many threads, go down to 2

**Comment by HurfeyDurfey** [comment]
Still getting the error, but less frequently. I'll try 1.

**Comment by wcastello** [comment]
https://github.com/AHAAAAAAA/PokemonGo-Map/issues/2513
https://discord.gg/sSYhW for usage help.
