### ISSUE TITLE
Running pokemongo-map on a shared hosting

### ISSUE THREAD

**Issue by mahavidhan** [AHAAAAAAA/PokemonGo-Map#2589]
Wondering if it is possible to run pokemongo-map on shared hosting. If yes, are there any step-by-step instructions given somewhere? while i was looking info on this during my google search, somehere I found http://104.46.62.52/ that shows nearby pokemons. Is is possible to do something like this LIVE? If it is possible, it would be easier for all friends who live close by to find pokemons by visiting the map located on a shared hosting server. My question may be stupid but i am curious to know.

**Comment by reactortrip** [comment]
Yes, you can run this on a shared vps running Linux.

**Comment by chuyskywalker** [comment]
Please take some time to browse the wiki which has many examples and instructions, thanks!
