### ISSUE TITLE
Response dictionary key error

### ISSUE THREAD

**Issue by 2Awesome2** [AHAAAAAAA/PokemonGo-Map#2592]
2016-07-29 09:31:45,293 [     search] [  ERROR] Scan step 796 failed. Response dictionary key error.

I keep getting this, any one know what this is?

**Comment by TFD777** [comment]
Everyone is getting this, threads no longer work, so the map will load slower as well.

**Comment by ylehir** [comment]
Reduce the number of thread to 3 max.
#2588, #2579, #2513

**Comment by 2Awesome2** [comment]
ty =)

**Comment by bogo307** [comment]
How do you reduce the max amount of threads?

**Comment by wcastello** [comment]
https://github.com/AHAAAAAAA/PokemonGo-Map/issues/2513
https://discord.gg/sSYhW for usage help.
