### ISSUE TITLE
Change the timezone in the database and prevent record entries with a criteria

### ISSUE THREAD

**Issue by mahavidhan** [AHAAAAAAA/PokemonGo-Map#2606]
1. Where and how can I change the timezone to local time. All times in the db are UTC.
2. Hide pokemon feature only hides them in the map but the entries still goes into the database. How can I prevent specific pokemons to get entered in the db?
3. Is there a way to delete all records in the pokemon table when the execution starts with a condition where the time is 15 minutes older than current time?

**Comment by Znuff** [comment]
1. You don't
2. You don't
3. No

**Comment by wcastello** [comment]
https://discord.gg/sSYhW for help.
