### ISSUE TITLE
MariaDB Max_Connections

### ISSUE THREAD

**Issue by sagot3n** [AHAAAAAAA/PokemonGo-Map#2607]
So im on the latest dev and its working great! I have about 30 PTC accounts im using to scan my local area and they are all -t 1 and it works like a charm. However im running into errors on the DB side where im running out of connection to the sql server (mariadb). Anyone know how to update it to allow more connections?

**Comment by Znuff** [comment]
http://lmgtfy.com/?q=mariadb+max+connections+&l=1

Honestly...

**Comment by sagot3n** [comment]
Totally did that and cant find aything for windows out there. I checked ini files and cant find anything that has max_connections listed as a variable.

**Comment by DomGrieco** [comment]
set global max_connections := XXX;

**Comment by Znuff** [comment]
If it doesn't exist, just fucking add it. Geez.
