### ISSUE TITLE
[Help/Instructions for Wiki] Loading the app onto python hosting site

### ISSUE THREAD

**Issue by Zareaus** [AHAAAAAAA/PokemonGo-Map#2611]
## Expected Behavior

I have tried to load the app onto [https://www.pythonanywhere.com](https://www.pythonanywhere.com) but my skills are beginner at best.

Instructions on loading the app into one of the many free hosting sites would help use the maps while on the go away from the computer.

## Current Behavior

To see the app in the outside world requires port forwarding, which I can't do due to local network settings.

## Possible Solution

You can clone from GitHub and the setup seems straightforward.... if you know what you're, which I don't.

## Context

I figured this was a good way to run the app without having to use port forwarding. (which I can't do due to network settings)

There are several similar sites and I can see them being easily used to run maps.

**Comment by AHAAAAAAA** [comment]
There's 3 easy deployment options in the README page of develop. Heroku, Jelastic, and Scalingo. Use one of those if possible. Otherwise, you can also do -H 0.0.0.0 and -P 5000 with a DDNS service to access your computer's Flask server when you're out.
