### ISSUE TITLE
[Request] Pushbullet compatibility

### ISSUE THREAD

**Issue by wowfood** [AHAAAAAAA/PokemonGo-Map#2624]
## Expected Behavior

Integrate PoGo notifications such that they are forwarded by Pushbullet (or a similar service)

## Current Behavior

Currently notifications only get displayed on the webpage, and requires the webpage to be in active focus to work.

## Context

Missed a few rare pokemon because I've not flicked to check the map until there's only a minute or so left before said rare disappears.  Having pushbullet notifications sent out would mean I could leave the app running, and only need to look at the map when notified that a rare is near.

## Your Environment
Currently running PoGo map on home computer, with info forwarded to the outside world via ngrok.  (need to switch over so it's running on my pi at some point)...  Anyone want to make a pi image with this preinstalled for me?)

**Comment by wowfood** [comment]
I realise it might already be possible to do this through pushbullet, but bugger me if I can figure out how.

**Comment by reactortrip** [comment]
Kvangent fork has this already with slack and a few others as well.  Pretty easy to adapt to the newer versions.

**Comment by Dagothur** [comment]
@reactortrip how do you merge Kvangent's changes when downloading a new build? I've been doing them manually in NP++ but am unsure if there's an easier way built into the Github site to do this?

**Comment by Cliffield** [comment]
Kvangent wrote a third party extension for PokemonGo-Map's webhook.
https://github.com/kvangent/PokeAlarm

**Comment by wowfood** [comment]
Excellent, just what I was looking for.  Shame it says he'll probably be stopping pushbullet integration after august, guessing it costs to use the API or something.

**Comment by ShutUpPetey** [comment]
I wrote something on my local branch that works well, but I have never pushed anything to github share repo in my life. So I would be too terrified to ruin everything! lol

**Comment by andrewda** [comment]
Use webhooks. We have no plans of implementing any third party apps because webhooks are already available. As @Cliffield said, checkout @kvangent fantastic PokeAlarm.

**Comment by kvangent** [comment]
@Dagothur new version doesn't need to be integrated, check out my PokeAlarm repo.
