### ISSUE TITLE
Gmaps-key is required (runserver.py: error: argument -k/--gmaps-key is required)...How to fix this issue?

### ISSUE THREAD

**Issue by apalmerston** [AHAAAAAAA/PokemonGo-Map#2626]
## Environment info
Windows 10
Python 2.7

## I'm getting this error
usage: runserver.py [-h] [-a AUTH_SERVICE] [-u USERNAME] [-p PASSWORD]
                    [-l LOCATION] [-st STEP_LIMIT] [-sd SCAN_DELAY]
                    [-td THREAD_DELAY] [-ld LOGIN_DELAY] [-dc] [-H HOST]
                    [-P PORT] [-L LOCALE] [-c] [-d] [-m] [-ns] [-os] [-fl] -k
                    GMAPS_KEY [-C] [-D DB] [-t NUM_THREADS] [-np] [-ng] [-nk]
                    [--db-type DB_TYPE] [--db-name DB_NAME]
                    [--db-user DB_USER] [--db-pass DB_PASS]
                    [--db-host DB_HOST] [-wh [WEBHOOKS [WEBHOOKS ...]]]
runserver.py: error: argument -k/--gmaps-key is required

## This is what I've tried
C:\Users\Onshore\Desktop\PokemonGo-Map-master>C:\Python27\python runserver.py -a ptc -u myUsername -p myPassword -l "Central Park, New York" -st 10

when it was example.py it was working for me...but when I changed to this version I can't get past this error.

**Comment by cytec** [comment]
just add -k and put your gmaps key in there

**Comment by Dagothur** [comment]
If you don't have one yet follow this: https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Google-Maps-API-Key
