### ISSUE TITLE
PHP for webhooks

### ISSUE THREAD

**Issue by shiznewski** [AHAAAAAAA/PokemonGo-Map#2627]
I have tried everything to output the data sent by the webhook

print_r($_POST);
print_r($_GET); 
along with many others. I can't seem to get any data. 

Can someone help with this? I want to be able to break it into a array, then i will scan the aray for the pokemon i want etc then send message with twiolo, however i can't get any of the data, and its not standard json

**Comment by MRokas** [comment]
Have you tried using `file_get_contents("php://input")` to access received data?

**Comment by shiznewski** [comment]
Nope. I didn't even know about that. Sorry. Thanks for the help. I'm an idiot

**Comment by andrewda** [comment]
Pretty sure an alternative to `file_get_contents("php://input")` is `$HTTP_RAW_POST_DATA` if you were looking to go the easy-variable route, though [the PHP documentation](http://php.net/manual/en/wrappers.php.php) says the former is preferred.
