### ISSUE TITLE
[Request] Modify map.js to load current user location instead of mapped location

### ISSUE THREAD

**Issue by pir2** [AHAAAAAAA/PokemonGo-Map#2628]
## Expected Behavior
Not expected behaviour, but potential enhancement.  Have the option to start the default view at the user's current location

## Current Behavior
The map currently loads at whatever the starting location of the search bot is set at

## Possible Solution
Modify `initMap` in `maps. js` with the following:

```
function initMap() {
  map = new google.maps.Map(document.getElementById('map'), {
    center: {
      lat: center_lat,
      lng: center_lng
    },
    zoom: 16,
    fullscreenControl: true,
    streetViewControl: false,
    mapTypeControl: true,
    mapTypeControlOptions: {
      style: google.maps.MapTypeControlStyle.DROPDOWN_MENU,
      position: google.maps.ControlPosition.RIGHT_TOP,
      mapTypeIds: [
        google.maps.MapTypeId.ROADMAP,
        google.maps.MapTypeId.SATELLITE,
        'nolabels_style',
        'dark_style',
        'style_light2',
        'style_pgo',
        'dark_style_nl',
        'style_light2_nl',
        'style_pgo_nl'
      ]
    },
  });

// Additional Code for current location stolen from map.js
 if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(function(position) {
        var latlng = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);
        locationMarker.setVisible(true);
        locationMarker.setOptions({
          'opacity': 1
        });
        locationMarker.setPosition(latlng);
        map.setCenter(latlng);
      });
    } 
```

## Context
Currently running a server for multiple users and most searchers are run in `-ns` mode.  The searchers currently map the whole city, but some of the designated locations are actually the user's marker so that they can map their own/current location in case it's not mapped already, or one of the searchers is down.

Users are clicking the `follow location` button to get to their current location.  If the map started at their current location instead, there would be less user interaction required.

(yes, the user could just press the little circle in the bottom right, but if it just loaded in the current location, most end users would be happy!)

**Comment by invisiblek** [comment]
i'm not even sure we'd add something like this as an option. if it can detect a user's whereabouts, it should go there in my opinion

**Comment by jangrewe** [comment]
I'm running a public map and have 7 areas with 11 steps each (covering the city center and surrounding districts), and i've (of course) also disabled the geolocation feature - but i'd love for the map to center on a users location, because otherwise you have to first scroll a lot to get to it on the map.
Maybe add an option toggle "always center map on my location", without updating the mapping location of the searcher.

**Comment by invisiblek** [comment]
https://github.com/AHAAAAAAA/PokemonGo-Map/pull/2668

**Comment by jangrewe** [comment]
From a quick glance i gathered that the map now gets centered for every user, always? That would put the map ~500km east of where i actually live... this should be a toggle, disabled by default.

**Comment by invisiblek** [comment]
yea, probably best to make it a toggle. now we need to decide if the feature is good enough to warrant yet another toggle

**Comment by pir2** [comment]
Would it make more sense if this was a startup option? - UL UserLocation
python runserver.py -UL 

Seems like something that only the person running the server would care about and something the user should have less control over

**Comment by invisiblek** [comment]
No, this is definitely a UI feature. One user may want this where another may not. It changes nothing about what, or how much,  data is collected.

**Comment by CtrlAltDefeat94** [comment]
I would definitely like such a feature, I am mapping a few city centers that are a bit spread throughout the country(running for friends etc), and currently most of them need to get to their location first before they can actually use it.
