### ISSUE TITLE
Unexpected line 5 error randomly appearing 

### ISSUE THREAD

**Issue by taxon221** [AHAAAAAAA/PokemonGo-Map#2629]
Unexpected line 5 error randomly appearing 
Visual of my problem:
(https://cloud.githubusercontent.com/assets/20709657/17256669/87939080-558c-11e6-9322-825193e56290.png)

## Current Behavior
The program started acting up lately (It still worked but it wouldn't show all pokemon) so i downloaded the new version 2.1.0 but after putting the google api and i tried to run the commands in cdm and after the install requirements command it worked fine and gave me the usual feed but after adding the -a google, -u, -p, -l and -st and entering all that it gives me this error:

usage: runserver.py [-h] [-a AUTH_SERVICE] [-u USERNAME] [-p PASSWORD]
                    [-l LOCATION] [-st STEP_LIMIT] [-sd SCAN_DELAY]
                    [-td THREAD_DELAY] [-ld LOGIN_DELAY] [-dc] [-H HOST]
                    [-P PORT] [-L LOCALE] [-c] [-d] [-m] [-ns] [-os] [-fl] -k
                    GMAPS_KEY [-C] [-D DB] [-t NUM_THREADS] [-np] [-ng] [-nk]
                    [--db-type DB_TYPE] [--db-name DB_NAME]
                    [--db-user DB_USER] [--db-pass DB_PASS]
                    [--db-host DB_HOST] [-wh [WEBHOOKS [WEBHOOKS ...]]]
runserver.py: error: Unexpected line 5 in C:\Users\Jeremy\Desktop\PoGo map\PokemonGo-Map-master\pogom\../config/config.ini: Username:

## Possible Solution
I'm in no way an expert or even a novice coder but this could be prevented with a single program where you only enter your username and password and coordinates this is of course not as easy as it sounds but i think that would really prevent a bunch of simple problems with people like me  

## Steps to Reproduce (for bugs)

1.C:\Users\Jeremy\Desktop\PoGo map\PokemonGo-Map-master>pip install -r requirements.txt

2.Requirement already satisfied (use --upgrade to upgrade): Flask==0.11.1 in c:\python27\lib\site-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): Jinja2==2.8 in c:\python27\lib\site-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe==0.23 in c:\python27\lib\site-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): Werkzeug==0.11.10 in c:\python27\lib\site-packages (from -r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): configargparse==0.10.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): click==6.6 in c:\python27\lib\site-packages (from -r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): itsdangerous==0.24 in c:\python27\lib\site-packages (from -r requirements.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): peewee==2.8.1 in c:\python27\lib\site-packages (from -r requirements.txt (line 8))
Requirement already satisfied (use --upgrade to upgrade): wsgiref==0.1.2 in c:\python27\lib\site-packages (from -r requirements.txt (line 9))
Requirement already satisfied (use --upgrade to upgrade): geopy==1.11.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 10))
Requirement already satisfied (use --upgrade to upgrade): protobuf==2.6.1 in c:\python27\lib\site-packages (from -r requirements.txt (line 11))
Requirement already satisfied (use --upgrade to upgrade): requests==2.10.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 12))
Requirement already satisfied (use --upgrade to upgrade): s2sphere==0.2.4 in c:\python27\lib\site-packages (from -r requirements.txt (line 13))
Requirement already satisfied (use --upgrade to upgrade): gpsoauth==0.3.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 14))
Requirement already satisfied (use --upgrade to upgrade): protobuf-to-dict==0.1.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 15))
Requirement already satisfied (use --upgrade to upgrade): PyMySQL==0.7.5 in c:\python27\lib\site-packages (from -r requirements.txt (line 16))
Requirement already satisfied (use --upgrade to upgrade): flask-cors==2.1.2 in c:\python27\lib\site-packages (from -r requirements.txt (line 17))
Requirement already satisfied (use --upgrade to upgrade): flask-compress==1.3.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 18))
Requirement already satisfied (use --upgrade to upgrade): setuptools in c:\python27\lib\site-packages (from protobuf==2.6.1->-r requirements.txt (line 11))
Requirement already satisfied (use --upgrade to upgrade): future in c:\python27\lib\site-packages (from s2sphere==0.2.4->-r requirements.txt (line 13))
Requirement already satisfied (use --upgrade to upgrade): pycryptodomex>=3.0 in c:\python27\lib\site-packages (from gpsoauth==0.3.0->-r requirements.txt (line 14))
Requirement already satisfied (use --upgrade to upgrade): Six in c:\python27\lib\site-packages (from flask-cors==2.1.2->-r requirements.txt (line 17))

3.C:\Users\Jeremy\Desktop\PoGo map\PokemonGo-Map-master>python runserver.py -a google -u myemail@gmail.com -p password -l "00.000000 -00.000000" -st 10

4.usage: runserver.py [-h] [-a AUTH_SERVICE] [-u USERNAME] [-p PASSWORD]
                    [-l LOCATION] [-st STEP_LIMIT] [-sd SCAN_DELAY]
                    [-td THREAD_DELAY] [-ld LOGIN_DELAY] [-dc] [-H HOST]
                    [-P PORT] [-L LOCALE] [-c] [-d] [-m] [-ns] [-os] [-fl] -k
                    GMAPS_KEY [-C] [-D DB] [-t NUM_THREADS] [-np] [-ng] [-nk]
                    [--db-type DB_TYPE] [--db-name DB_NAME]
                    [--db-user DB_USER] [--db-pass DB_PASS]
                    [--db-host DB_HOST] [-wh [WEBHOOKS [WEBHOOKS ...]]]
runserver.py: error: Unexpected line 5 in C:\Users\Jeremy\Desktop\PoGo map\PokemonGo-Map-master\pogom\../config/config.ini: Username:

## Context
Not a huge problem but i'm organizing a big walk with a few big companies (Big for our small island Curacao) and i'm using this to show the companies where all the pokestops and gyms are and how the pokemon and lures behave but i already have the pokestops scanned in the area we are using but it would be helpful to be able to update it and show off the pokemon and the lures effect too

## My Environment
* Version used: 1.0.3
* Environment name and version Using Python 2.7.12
* Operating System and version : Windows 10 64 bit and running ios version 8.4 

## Thank everybody
Just wanted to thank everybody that actually looked at my post and deals with my bad grammar and all that hopefully you guys can help me find a solution and i'm not 100% on this all the time but i work monday to friday from 8 till 4/5 so i should be on here at those times but ill also try to check in while at home but if i dont respond you can add me on discord: Taxon #2554 or skype: Jeremyvrolijk i have 2 so add them both (I'm the ones in curacao or netherlands antilles)

**Comment by marogers** [comment]
The error indicates that you have uncommented the Username line in config.ini without supplying a value.  Did you remove the hashtags and not add your username?

**Comment by invisiblek** [comment]
Username is not valid, username is. (case-sensitive)

model your config.ini after config.ini.example

**Comment by taxon221** [comment]
Probably forgot to change all that when switching from 2.0.0 to 2.1.0 thanks for the help gonna change that now
