### ISSUE TITLE
Converting Disappear time to local time

### ISSUE THREAD

**Issue by shiznewski** [AHAAAAAAA/PokemonGo-Map#2630]
Disappear is epoch. One i just got a second ago is 1469827558.0

I am in EST (America/New York).

In php how do i convert that to my time zone? 

I have tried:
date_default_timezone_set('America/New York');
$dt = date("1469827558.0:"); and it still comes out 4 hours ahead of where i am

**Comment by remcotroost** [comment]
No offense, but "Issues" is with regard to bugs of the source code and should not be used as a StackOverflow discussion forum.

This may help you: [link](http://us.php.net/manual/en/function.gmstrftime.php)
