### ISSUE TITLE
Niantic Servers Under Heavy Load

### ISSUE THREAD

**Issue by Tman1677** [AHAAAAAAA/PokemonGo-Map#2634]
After about an hour of work it stops collecting pokemon data in the area.
## Expected Behavior

It will continue scanning for pokemon (adding them into the pokelyzer database) indefinitely.
## Current Behavior

After about an hour of work, stops scanning and starts reporting that Niantic servers are under heavy load, requiring a restart.
## Possible Solution

No Idea
## Steps to Reproduce (for bugs)

1. Setup PokemonGo-Map
2. Use Google Log-In account.
3. Install Pokelyzer to the database [Here](http://www.whackdata.com/2016/07/26/instructions-analyzing-pokemon-go-data/)

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):
Ubuntu 16, controlled via screen sharing and ssh from a Mac.

**Comment by MRokas** [comment]
Are you serious?

**Comment by deada92** [comment]
same here

**Comment by mkorsak** [comment]
Same

**Comment by MRokas** [comment]
There's nothing todo if Niantic servers are under heavy load. All you can do is set scan-delay to help a bit.

**Comment by crckdns** [comment]
I guess, your scan is way too fast or too many threads at same time (same effect)

**Comment by iDervy** [comment]
Add the comment -t 3

It slows down the scanner, but it's the only way currently to by pass it.

**Comment by vinsilsim** [comment]
Niantic servers accept only -t 3 per google account or ptc account! you need use multiples accounts now to scan large area!

my beehive_builder.sh to build locations with multiple accounts

http://pastebin.com/K2Nz3wF5

Usage Example: ./beehive_builder.sh 8 2 -33.868196 151.212564 1

First: create file with name accounts.txt and put you google or ptc account with:
user,password,ptc
or
user,password,google
One account per line. You can use multiples auth types at same time Example:

accounts.txt

ptcuser1,password,ptc
ptcuser2,password,ptc
ptcuser3,password,ptc
user1@gmail.com,password,google
user2@gmail.com,password,google
ptcuser4,password,ptc

**Comment by d3unan** [comment]
@vinsilsim 
Can you explain how to use the beehive_builder.sh?  I'm new to coding.
I downloaded "beehive_builder.sh.txt" and inserted it into my PokemonGo-Map folder.  Also, in the folder I created "accounts.txt" with all my account info.  What are the next steps?

**Comment by vinsilsim** [comment]
Operational System? Windows Linux or Mac OS?

**Comment by d3unan** [comment]
Windows

**Comment by d3unan** [comment]
@vinsilsim 
Windows.  I followed this setup: 
https://www.jonaharagon.com/PoGoMapWiki/#!Windows-Installation-and-requirements.md

**Comment by MRokas** [comment]
On windows you should use .bat file.
