### ISSUE TITLE
[Improvement/Bug?] Start to the coordinates provided

### ISSUE THREAD

**Issue by ser86** [AHAAAAAAA/PokemonGo-Map#2639]
## Expected Behavior
When you insert coordinates the scanner will begin from this point 

## Current Behavior
When you insert coordinates the scanner will begin from the nearest point that have an address

## Steps to Reproduce (for bugs)
If you search coordinates in Google Maps
![schermata del 2016-07-29 20-11-03](https://cloud.githubusercontent.com/assets/1152900/17259137/6490edc4-55ca-11e6-93ce-dbee6b563687.png)
The same coordinates on Pokemap
![schermata del 2016-07-29 20-10-50](https://cloud.githubusercontent.com/assets/1152900/17259203/b75bf31e-55ca-11e6-9872-d84d36c89732.png)
If on Google Maps you try to get directions appear an address
![schermata del 2016-07-29 20-27-25](https://cloud.githubusercontent.com/assets/1152900/17259389/88e2d362-55cb-11e6-9c88-bc00f5e29578.png)
That address is the one Pokemap uses to get the start position

## Context
Is quite insignificant if you run single scan at a time but it can be a PITA if you try to map an entire city or area with multiple scan because the points can be transfer far away leaving area not mapped.

## Your Environment

* Version used: v2.1.0
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): Ubuntu 16.04

**Comment by Lexazan** [comment]
Please try with comma between cords, like 45.470311**,** 8.746936

**Comment by ser86** [comment]
Yes with comma it work as expected, thanks a lot!
