### ISSUE TITLE
I'm getting a flask error.

### ISSUE THREAD

**Issue by Weezky** [AHAAAAAAA/PokemonGo-Map#2641]
C:\Users\Mauricio\Downloads\PokemonGo-Map-develop>python ./runserver.py --help
Traceback (most recent call last):
  File "./runserver.py", line 17, in <module>
    from pogom.app import Pogom
  File "C:\Users\Mauricio\Downloads\PokemonGo-Map-develop\pogom\app.py", line 9, in <module>
    from flask_compress import Compress
ImportError: No module named flask_compress

I'm getting that, prior to this I've been able to run every branch before, ( master and develop) I just downloaded a new develop one today and after setting everything up I'm getting that. I already uninstalled flask and reinstalled it with no avail.

**Comment by miaojs** [comment]
did you do a pip install -r requirements.txt ?

**Comment by Weezky** [comment]
Yea. I did at the very beggining.

**Comment by miaojs** [comment]
You need to do it again.

**Comment by Weezky** [comment]
No I mean I do it every time I download a new branch. I did with this one as well.

**Comment by Paralysing** [comment]
Try pip install flask_compress?

**Comment by Weezky** [comment]
Solved it. Thanks for the help.
