### ISSUE TITLE
Question/issue? : Grunt Build

### ISSUE THREAD

**Issue by Varatnar** [AHAAAAAAA/PokemonGo-Map#2645]
I updated to the latest build a few minutes ago and whenever i try to run the server, it returns an error, something about neeeding to run "grunt build" before.

I do not know how to start that, but by removing the check it all works properly, see code below.

`    # Let's not forget to run Grunt / Only needed when running with webserver`
`    #if not args.no_server:`
`    #    if not os.path.exists(os.path.join(os.path.dirname(__file__), 'static/dist')):`
`    #        log.critical('Please run "grunt build" before starting the server.');`
`    #        sys.exit();`

After commenting the check, the server seems to run like normal, i still would like to know what the intended behavior should be.

All his is running on windows, the code is launched through a cygwine command line.
Furthermore, no actual sql database is running with it and every parameters are fed through the command lines (no config files).

Thank you

**Comment by MRokas** [comment]
Grunt is required to build front-end files.

Either use https://github.com/AHAAAAAAA/PokemonGo-Map/releases - which is intended for regular users, or follow these steps:

Install node.js + npm
Run: `npm install --global grunt-cli && npm install && grunt build` in map directory

**Comment by leonelgalan** [comment]
Your app works because because you have older versions of the _dist_ files that are no longer in the repo. Build new _dist_ files every time you pull so you get the latest improvements on the front end.

**Comment by Varatnar** [comment]
Thank you for you answers !
