### ISSUE TITLE
Problem with GoogleMaps API Key

### ISSUE THREAD

**Issue by adamalston** [AHAAAAAAA/PokemonGo-Map#2653]
I updated the program last night and it quit working. Also I cannot find the correct location to insert my GoogleMaps API key. 

![](https://cloud.githubusercontent.com/assets/18297826/17261568/73545f4c-55a4-11e6-95bb-95e444774d97.png)

## Context
 
The program is not working anymore.

## Your Environment

* Version used: Latest
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): OS X 10.11.6

**Comment by andrewda** [comment]
Just enter your Google Maps API Key using the `-k` parameter. The error tells you exactly what to do...

**Comment by adamalston** [comment]
I have tried this before and I just tried it again and it is registering the same error. I inserted the -k parameter and this is what I got
<img width="563" alt="screen shot 2016-07-29 at 4 08 39 pm" src="https://cloud.githubusercontent.com/assets/18297826/17262003/e55c4198-55a6-11e6-99f0-b5f7fc573530.png">
