### ISSUE TITLE
AttributeError: 'module' object has no attribute 'total_ordering'

### ISSUE THREAD

**Issue by cpabell** [AHAAAAAAA/PokemonGo-Map#2654]
I followed all steps for installing and running but the terminal returns this when trying to run:

[~/Desktop/PoGo/PokemonGo-Map-2.1.0]# python runserver.py -u [username] -p [password] -st 10 -k [mykey] -l "[mylocation]"
Traceback (most recent call last):
  File "runserver.py", line 13, in <module>
    from pogom.app import Pogom
  File "/root/Desktop/PoGo/PokemonGo-Map-2.1.0/pogom/app.py", line 11, in <module>
    from s2sphere import *
  File "/usr/lib/python2.6/site-packages/s2sphere/__init__.py", line 5, in <module>
    from .sphere import *
  File "/usr/lib/python2.6/site-packages/s2sphere/sphere.py", line 12, in <module>
    @functools.total_ordering
AttributeError: 'module' object has no attribute 'total_ordering'

I'm running Centos 6 on a VPS with Python 2.7 if that helps at all.

**Comment by wcastello** [comment]
> I'm running Centos 6 on a VPS with Python 2.7 if that helps at all.
No you're not:

> File "/usr/lib/python2.6/site-packages/s2sphere/sphere.py", line 12, in

**Comment by AHAAAAAAA** [comment]
Wcastello for github president

**Comment by upperdecker954** [comment]
im getting the same error. any help would be great. im trying to install this on my dedicated server, which is running python2.6. I also cannot change the version of python for some reason...been struggling with this for half a day now. any help would be great.
