### ISSUE TITLE
white, empty screen upon entry

### ISSUE THREAD

**Issue by bone4lyf** [AHAAAAAAA/PokemonGo-Map#2657]
## Expected Behavior

Map should load in central area.

## Current Behavior

The maps does not load. Instead, the screen is filled with white space. The title bar and options to the left are displayed.

## Steps to Reproduce (for bugs)

1. When I engage runserver.py, it successfully logs in and begins scanning (apparently). The text indicates that it is scanning anyway.
2. When I access the localhost by browser, the screen is blank/white.
3.
4.

## Context

cannot use program

## Your Environment

* Version used: developer - downloaded 7-29-16
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile):10 64-bit

**Comment by tr1p0z** [comment]
Same problem!

**Comment by Paralysing** [comment]
Try installing and running grunt? There's a [wiki post](https://www.jonaharagon.com/PoGoMapWiki/#!Development.md) about it.

**Comment by bone4lyf** [comment]
Well, that didn't seem to the fix the issue.

...But I am not getting this bug in the latest stable, which is 2.1.0.

**Comment by DoraKlikOpDora** [comment]
Try installing the requirements again.

pip install -r requirements.txt

**Comment by ecrouch** [comment]
I had to do the following:

clone repo
open command prompt in directory
npm install -g grunt
let it work for a few minutes
npm install
wait another few minutes
I opened a new command prompt, ran grunt by simply typing 'grunt'
kept the watcher running in background
commented out my entire config file and load all variables via cmd 
no more white screen, map loads just fine.

**Comment by freakjam** [comment]
Run "grunt" again to update some stuff, map loaded fine for me after that.

` sudo grunt
Running "jshint:files" (jshint) task

✔ No problems


Running "clean:build" (clean) task
>> 1 path cleaned.

Running "babel:dist" (babel) task

Running "uglify:build" (uglify) task
>> 4 sourcemaps created.
>> 4 files created.

Running "sass:dist" (sass) task

Running "cssmin:build" (cssmin) task
>> 2 files created. 49.3 kB → 35.95 kB`

**Comment by Epion003** [comment]
following the wiki install got the first 2 parts to run fine but when i type grunt is says not recognized... should i try A clean download again and try again. I had just gotten my hive working with small number and now this blank map today...

**Comment by freakjam** [comment]
install grunt-cli

**Comment by SAnthonyH** [comment]
Having the same problem. Script loads but map doesn't show. 

I'm getting a lot of warning errors running npm install, is this normal?

**Comment by Paralysing** [comment]
If you're on linux, try apt-get install nodejs-legacy, on windows, try using [this](https://nodejs.org/en/blog/release/v0.8.23/), it got rid of all the errors for me.

**Comment by SAnthonyH** [comment]
It might be because I'm trying to run it on a Raspberry Pi, but I get the following after running Sudo Grunt. 

Loading "sass.js" tasks...ERROR
>> Error: Node Sass does not yet support your current environment: Linux Unsupported architecture (arm) with Node 0.10.x
>> For more information on which environments are supported please see:
>> https://github.com/sass/node-sass/releases/tag/v3.8.0
Loading "babel.js" tasks...ERROR
>> Error: Cannot find module 'core-js/library/fn/symbol/iterator'
Warning: Task "sass" not found. Use --force to continue.

Aborted due to warnings.

**Comment by Epion003** [comment]
First thank you for the comments i managed to get the map back up following u guys. singkle target map works but my beehive one ins still blank ;-(

**Comment by freakjam** [comment]
Unexpected HTTP server response - needs 200 got 502 means Niantic servers are overloaded.

**Comment by Epion003** [comment]
@freakjam is it randomly generated cause if i try hive gives me that but when i just do single works fine?

**Comment by chuyskywalker** [comment]
Seems to be sorted, feel free to use thread for follow up though.
