### ISSUE TITLE
Not All Pokemon Appear on Map

### ISSUE THREAD

**Issue by justanironic** [AHAAAAAAA/PokemonGo-Map#2658]
## Current Behavior
The scan seems to be missing a lot of Pokemon it normally wouldn't. At first I thought it might be from the new version or some different parameter settings, but it was working fine in the beginning. I even tried to use the older version of the map again that I knew worked and it showed the same Pokemon or, rather, lack thereof.

## Steps to Reproduce (for bugs)
1. Run the latest version of the map on port 5000
2. Run an older version that I can 100% confirm used to work perfectly on port 8000
3. Compare results between maps (they are the same)
4. Compare maps to the game itself, confirm that the maps are missing Pokemon

## Your Environment
* Version used: [The latest commit](https://github.com/AHAAAAAAA/PokemonGo-Map/commit/6363f6c37c4336189e4839830ff6f2cf791049ad) (as of writing this) as well as an older commit of which I'm not exactly sure what it is.
* Environment name and version: Python 2.7
* Operating System: Windows 10

**Comment by andrewda** [comment]
Already reported numerous times. Please use the search feature on GitHub before reporting an issue.
