### ISSUE TITLE
New to Heroku and Python

### ISSUE THREAD

**Issue by RealestRealist** [AHAAAAAAA/PokemonGo-Map#2661]
Is there any way to run multiple accounts on 1 heroku project
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by andrewda** [comment]
Please use the discord #help channel. https://discord.gg/sSYhW
