### ISSUE TITLE
error since update 

### ISSUE THREAD

**Issue by Ananda93** [AHAAAAAAA/PokemonGo-Map#2664]
Hello,

Ever since there was a update in PokemonGomaps, i havent been able to install it anymore.
Before the update there was in config the map credentials and that isn't there anymore

And now i have this error on my computer, does anybody now how to install it with the new config.ini.examples?

usage: runserver.py [-h] [-a AUTH_SERVICE] [-u USERNAME] [-p PASSWORD]
[-l LOCATION] [-st STEP_LIMIT] [-sd SCAN_DELAY]
[-td THREAD_DELAY] [-ld LOGIN_DELAY] [-dc] [-H HOST]
[-P PORT] [-L LOCALE] [-c] [-d] [-m] [-ns] [-os] [-fl] -k
GMAPS_KEY [-C] [-D DB] [-t NUM_THREADS] [-np] [-ng] [-nk]
[--db-type DB_TYPE] [--db-name DB_NAME]
[--db-user DB_USER] [--db-pass DB_PASS]
[--db-host DB_HOST] [-wh [WEBHOOKS [WEBHOOKS ...]]]

**Comment by andrewda** [comment]
You should move `config.ini.example` to `config.ini`. If you need more help, please use the discord #help channel or read the documentation.
