### ISSUE TITLE
runserver.py line 10

### ISSUE THREAD

**Issue by pierreguerin0341** [AHAAAAAAA/PokemonGo-Map#2666]
When I try to launch the runserver.py it returns me an error with:
Traceback (most recent call last):
  File "runserver.py", line 10, in <module>
    from flask_cors import CORS
ImportError: No module named flask_cors

I have followed the installation on my Debian OS, and for some reason it won't work.

## Your Environment

* Version used: Debian 
* Environment name and version (e.g. Python 2.7): Python 2.7

**Comment by Gamewalker** [comment]
did u test pip install -r requirements.txt ?

**Comment by Paralysing** [comment]
If pip install -r requirements.txt doesn't work, try pip install flask_cors

**Comment by pierreguerin0341** [comment]
Thanks, worked for me!
