### ISSUE TITLE
[Error] Could not get a position by name, aborting.

### ISSUE THREAD

**Issue by ovoxorobert** [AHAAAAAAA/PokemonGo-Map#2669]
upon inserting: 
python runserver.py -a ptc -u ********* -p ********* -l “LOCATION” -st 10 -k [API KEY] 

I am getting the error listed above I am running v2.1.0 i was having no issues with v2.0.0 but i wanted the newest version so I updated and am having this problem

Side Note:
At first i was getting the -k-- api key error but fixed it by putting it in the runserver.py then continued to get the" could not get position by name error"
Also my config.ini is filled out 

Any help would be great thanks!

**Comment by ChopSu3y** [comment]
what are you putting inside your location field?

**Comment by ovoxorobert** [comment]
the city i want to find pokemon in. i am using my geo location for positioning.

**Comment by ChopSu3y** [comment]
are you putting location as: -l "latitude longitude" ?

Mine bugs out sometimes when I do something like: -l "chicago illinois"

**Comment by ovoxorobert** [comment]
yes i am doing the longitude and latitude way i am currently trying the city and state way but still nothing.

**Comment by andrewda** [comment]
Try `-l "latitude,longitude"` – just a comma instead of a space. Seems to work for me without issue.

**Comment by ovoxorobert** [comment]
Wow youre a life saver logged me in good but of course if its not one thing its another, the page will load really quickly and the Oops! Something went wrong happens.

**Comment by ovoxorobert** [comment]
Thanks for all the help guys i figured it out, just needed a new key :p
