### ISSUE TITLE
run Grunt Build...

### ISSUE THREAD

**Issue by A5LAN** [AHAAAAAAA/PokemonGo-Map#2676]
I was following this tutorial but it did not mention a thing about grunt build, I know grunt is a JS file as I was I running it this following error came up below;

![image](https://cloud.githubusercontent.com/assets/8560891/17266468/b9f12864-55c6-11e6-8b86-a93520323237.png)

Due to this I cant run the localhost server

Using Python 2.7 on Windown 10 Asus laptop

**Comment by Slam2** [comment]
Install : npm 4.x

In your git folder, use : npm install.

After install it. Run : grunt build.

You can run your webserver ;)
