### ISSUE TITLE
Not loading any map data

### ISSUE THREAD

**Issue by theebanka** [AHAAAAAAA/PokemonGo-Map#2679]
## Expected Behavior
Expected to load poke stops, Pokemon, and gyms

## Current Behavior
Not loading any information on the map

Heroku Logs show this:
` [    rpc_api] [WARNING] Unexpected HTTP server response - needs 200 got 502`

`[     search] [   INFO] Map Download failed. Trying again.`

**Comment by jnwarner** [comment]
I am also having a similar issue, deployed on local server computer Ubuntu 16.04 LTS Server running on latest commit. The log shows the login was successful but does not load the map in the browser. Neither the `master` branch or the `develop` branch seems to work.

**Comment by theebanka** [comment]
It's looking as though ptc and google servers could Ben struggling... this may be related..

**Comment by jnwarner** [comment]
It's strange, I am able to log in and catch Pokemon though? Maybe you're right though, A couple of friends of mine have been reporting that the servers are down for them, maybe just patchy server uptime right now?

**Comment by Paralysing** [comment]
May be related to #2513 , try running the server with -t 3, -sd 1.

**Comment by jnwarner** [comment]
Wow, could they finally be catching on to our shenanigans? Haha.

**Comment by Paralysing** [comment]
They started throttling requests to their api to 3 a second yesterday.

**Comment by jnwarner** [comment]
I wondered why they appeared to be slowing down. That's saddening.

**Comment by Paralysing** [comment]
Check out #2546 and #2568 for more info.

**Comment by theebanka** [comment]
@Paralysing so is there a way to limit the requests for a heroku app? Is this output that I am currently getting still related to that issue? It is repeating this over and over again 

`[     models] [   INFO] Upserted 0 pokemon, 0 pokestops, and 0 gyms`

**Comment by Paralysing** [comment]
I haven't worked with heroku much, but someone said there was something about extra-args, the output you're getting didn't seem to be related to the request limits, but I could be wrong. Look at the [wiki](https://www.jonaharagon.com/PoGoMapWiki/#!heroku.md) for more info.
