### ISSUE TITLE
"Get directions" link not localized

### ISSUE THREAD

**Issue by drallieiv** [AHAAAAAAA/PokemonGo-Map#2681]
## Expected Behavior
"get directions" link should trigger a nav route with directions.

## Current Behavior
When using the "get directions" link we have a redirection to 
https://www.google.com/maps/dir/Current+Location/<gps location>

Maps direction search is localized, and "Current Location" will not be matched to the current location if the account is not in english. In french, it requires "ma position"

## Possible Solution
Translate "Current Location" to each language, and have it use the same param then pokemon names.

**Comment by andrewda** [comment]
Ouch, this seems like an issue with google redirecting users in other countries from `google.com` to `google.fr` or something similar, but not translating the parameters for whatever reason. I feel like there has to be a way around this without making the code messy with a translate function, and requiring people to get a Google Translate API key.

**Comment by drallieiv** [comment]
I did not found it in search but duplicates : 2414

**Comment by andrewda** [comment]
Okay, direct all conversations to #2414.
