### ISSUE TITLE
Is multithread still blocked?

### ISSUE THREAD

**Issue by craywong** [AHAAAAAAA/PokemonGo-Map#2683]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by antiremy** [comment]
Using any account with more that 3 threads with a step delay of 1 will be blocked/throw tons of errors

**Comment by charredchar** [comment]
What scan delay would you recommend? If this is still such an issue maybe an option to log into multiple accounts to split the threads up across?

**Comment by someonefromcanada38** [comment]
The map is moving very slowly now. Even at 10 steps it is unlikely to find anything in the outer rings with enough time to reach it. Multiple accounts to split threads would be very useful in countering the throttling put in place, and also make larger maps more functional, as more accounts can be added to deal with additional size.

**Comment by antiremy** [comment]
I believe the fastest scan possible of one location is using -t 3 -sd 1 (3 threads, step delay 1)

**Comment by chuyskywalker** [comment]
As noted, server throttling limits how fast the scan can go now with a single account. There are a few in-the-works PRs to support multiple accounts for higher scanning thresholds, so take a look around for those.
