### ISSUE TITLE
ImportError: No module named flask_cors

### ISSUE THREAD

**Issue by jihaoran0509** [AHAAAAAAA/PokemonGo-Map#2684]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by catherinesjy** [comment]
I am a user not a developer, but here I found some information that may help: https://github.com/AHAAAAAAA/PokemonGo-Map/issues/1411.
