### ISSUE TITLE
MySQL transaction error perma-crashes scanner

### ISSUE THREAD

**Issue by parrots** [AHAAAAAAA/PokemonGo-Map#2686]
When running 7 scanners using `-sd 0.75 -st 8 -t 2` into a MySQL database, occasionally there will be a race condition in which there is an error obtaining a lock on the DB. When this happens the instance that experiences the exception stops scanning.

This is using the current development branch.

## Expected Behavior
The instance should either retry the database update, or drop the update and just move on to the next location. Either way, it should not prevent the next step in the scan hex.

## Current Behavior
An exception happens, killing future scans for that instance.

## Possible Solution
#2616 is close. Replacing that line with `except Exception as e:` fixes it.

## Steps to Reproduce (for bugs)
1. Set up multiple workers (~7) using a shared MySQL database
2. Not sure what exact timing profile is required, but launching them all at once using `-sd 0.75 -st 8 -t 2` options triggers it reliably for me within 10 min
3. Start the worker instances and let them run
4. Watch as eventually a worker instance hits the transaction error and eventually stops updating the DB

## Context
Trying to scan a region using multiple worker threads

## Your Environment
* Version used: Dev c5fe7d6fc0e0e4c5015b29d9d0006a47ab3d57db
* Environment name and version (e.g. Python 2.7): Python 2.7.11, Ubuntu instance on DigitalOean
* Operating System and version (desktop or mobile): Desktop

**Comment by DomGrieco** [comment]
testing this, seems great so far :+1:
