### ISSUE TITLE
Lured pokestops disappear after the first update tick

### ISSUE THREAD

**Issue by ayalfishey** [AHAAAAAAA/PokemonGo-Map#269]
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discordapp.com/invite/qbpVH6b).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.

Not much to say after the first -ar lured pokestops disappear 

### Environment info
Operating System:
Windows 7

Installed version of Python:
2.7.12

### Steps to reproduce
1. start it with a value for -ar, after that many seconds the pokestops will vannish
2.
3.

### What have you tried?
1.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by ryantheleach** [comment]
Are these actual lured pokestops? or some sort of bug?

**Comment by ayalfishey** [comment]
im not at a location that's lured right now but based on central park its actually lured locations

**Comment by Plop** [comment]
Got the same bug. Lured Pokestops disappears after the first auto-refresh.
