### ISSUE TITLE
Webhook timestamps are locale dependent

### ISSUE THREAD

**Issue by mataamad** [AHAAAAAAA/PokemonGo-Map#2694]
Webhook timestamps are locale dependent - this makes them hard to use when making calculations on servers in different timezones.

the webhook 'disappear_time' should use calendar.timegm(d_t.timetuple()) instead.

That way it's easy to consume the webhook data - e.g. I added an add_pokemon method to app.py:
`
        self.route("/add_pokemon", methods=['POST'])(self.add_pokemon)

...

    def add_pokemon(self):
        p = request.json["message"]
        data = {};
        data[b64decode(p['encounter_id'])] = {
            'encounter_id': p['encounter_id'],
            'spawnpoint_id': p['spawnpoint_id'],
            'pokemon_id': p['pokemon_id'],
            'latitude': p['latitude'],
            'longitude': p['longitude'],
            'disappear_time': datetime.utcfromtimestamp(p['disappear_time'])
        }
        
        InsertQuery(Pokemon, rows=data.values()).upsert().execute()
        print("added pokemon " + str(p['pokemon_id']))
        return "ok"
`
Without the locale fix, datetime.fromtimestamp gives incorrect results.

**Comment by andrewda** [comment]
I believe there is currently a PR that fixes this.

**Comment by mataamad** [comment]
Ah right, #2637.  Sorry, I searched issues but not PR's.
Looks like they're also trying to make some unnecessary changes in it though.
