### ISSUE TITLE
(Question) New beehive setup

### ISSUE THREAD

**Issue by Epion003** [AHAAAAAAA/PokemonGo-Map#2695]
After spending few hrs reading finally got the the new dev 2.1 working but have not had similar success with beehive. I made csv file that has 9 accts in it. Im only trying to make a 2 leap file but i keep getting this error
Reading usernames/passwords from C:\apps\accounts.csv
Traceback (most recent call last):
  File "location_generator.py", line 53, in <module>
    accounts = [auth_template.format(args.auth, line[0].strip(), line[1].strip()) for line in account_fields]
IndexError: list index out of range

my cmd looks like this
c:\python27\python.exe location_generator.py -lat 41.739153 -lon -72.695964 -st 7 -lp 2 --accounts C:\apps\accounts.csv --windows

Not sure what im doing wrong help setting up or please point me in right redirection thank you

**Comment by le3bl** [comment]
Not familiar with the beehive code, but the index out of range means it is having trouble splitting up the values in your csv.  If the assumed delimiter for the file is a comma and for some reason your csv is saving with tabs, spaces, or pipes then it wouldn't be able to split up the row columns properly.  If you open the file in a text editor, how are the columns being separated?

**Comment by Epion003** [comment]
@le3bl  one min will check now thank you

**Comment by Epion003** [comment]
opened in notepad++ the file opened with user:pass How do i change this so has the correct format

**Comment by Epion003** [comment]
@le3bl Ok i edited the file and got to were it says generating .bat but have not seen a file created yet?

**Comment by le3bl** [comment]
@Epion003 The file it generated for me was called beehive.sh in the root directory.

**Comment by stanleykylee** [comment]
The example for this for windows is:
python location_generator.py -lat -33.9 -lon 151.1 -st 5 -lp 3 --accounts C:\Documents\accounts.csv --windows --installdir="C:\Downloads\PokemonGo-Map"

You're missing the --installdir

**Comment by Epion003** [comment]
@le3bl @stanleykylee thank you very
 trying this out now

**Comment by Epion003** [comment]
ok I see it cycling now in the command window but now the localhost wond open web page
says site cant be reach... So im guessing i missed something

**Comment by rayuki** [comment]
localhost not being reached is same problem as i and many others in discord having with it running on this version of dev. i dont think its something we have done. i got it all working also but could not check my outputs unless i ran the generated beehive.bat on the 2.0 dev build.

**Comment by Epion003** [comment]
@rayuki so what mods do i have to make to the other beehive bat i had so it works with what i got going on now? Im not gonna try running them both at the same time am I

**Comment by Epion003** [comment]
@le3bl @stanleykylee thank you very for all your help. Also @rayuki i redid the grun install stuff and its finally connecting. finally after hours of messing with this starting to see progress not i just have to make changes to the 70 meter files but i will tackle that after some sleep.... Thank you again everyone
