### ISSUE TITLE
Question: pogon.db does not seems to have pokemon names (in .fullschema). Where app gets them? I want to query database and get names too. Thank you.

### ISSUE THREAD

**Issue by AlexM202020** [AHAAAAAAA/PokemonGo-Map#2696]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by Paralysing** [comment]
pogom.db doesn't have pokemon names, only the pokemon_id which relates to the pokedex. You would have to query the db to get an id and then query a site that matches the id with the actual name.

**Comment by wcastello** [comment]
Look at the locales/pokemon.en.json file then map id's to names using it.
