### ISSUE TITLE
Question on gym table. guard_pokemon_id - what it is some long number? Is it difficult to get lists of all defenders' pokemon ids from pokedex of all gyms? Thank you.

### ISSUE THREAD

**Issue by AlexM202020** [AHAAAAAAA/PokemonGo-Map#2697]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by andrewda** [comment]
Please direct questions to the discord channel. I'm guessing `guard_pokemon_id` is the id of the largest Pokemon in the gym, but I'm not sure.
