### ISSUE TITLE
speed up scans?

### ISSUE THREAD

**Issue by cwarkentin** [AHAAAAAAA/PokemonGo-Map#2698]
How would I go about speeding up the scan speed? does it start messing with the threading? it seems super slow right now

**Comment by Paralysing** [comment]
Currently, since Niantic is throttling requests down to 3 requests per second, the highest speed you could go at would be to use -t 3 -sd 1.

**Comment by chuyskywalker** [comment]
What he said. There are some PR's in the works to support multiple account/threads, but they're a bit up in the air right now.

**Comment by cwarkentin** [comment]
thanks guys
