### ISSUE TITLE
Can you please add option to pause servers/internet quering w/out closing the map? Or how help to block it in win 7 (in firewall I could not revoke access to internet for Electron while running). Thank you.

### ISSUE THREAD

**Issue by AlexM202020** [AHAAAAAAA/PokemonGo-Map#2699]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by itsZea** [comment]
ctrl+c in your terminal to stop server then (y/n) to start again or stop

Can we also stop asking questions like this?

Its unnecessary to create multiple issues to ask multiple questions. Create one issue ask your questions in the space provided and be done....

**Comment by chuyskywalker** [comment]
There's an open PR around here for this as a toggle button in the UI. I can't find it off hand, but take a look around for it.

**Comment by AlexM202020** [comment]
Where is that terminal? I run app for Win 7, it's just map, ctrl-c does not work on that map. Clicking button 'operational' does not seem to do anything.
