### ISSUE TITLE
Allow specifying Flask options on the command line

### ISSUE THREAD

**Issue by Slashbunny** [AHAAAAAAA/PokemonGo-Map#27]
It would be nice if we could specify a different bind address, port, and disable the built-in debugging for the Flask server. Something like this:

http://flask.pocoo.org/snippets/133/

It looks like the argument parsing and the flask server startup might need to be re-arranged in the file.

**Comment by DerScreever** [comment]
would be really great

**Comment by marauder37** [comment]
Working on this

**Comment by marauder37** [comment]
@Slashbunny @DerScreever test the PR please, if you can

**Comment by DerScreever** [comment]
I will do this later.
Now i need to work ^^

**Comment by DerScreever** [comment]
done
