### ISSUE TITLE
 missing file static/dist/css/app.min.css

### ISSUE THREAD

**Issue by venticello** [AHAAAAAAA/PokemonGo-Map#2704]
Last version missing file static/dist/css/app.min.css, but it is used in the file templates/map.html

**Comment by invisiblek** [comment]
use grunt to generate these files

**Comment by rayuki** [comment]
how do we do that with grunt? what command please

**Comment by aboldin** [comment]
How to generate js ana css??

**Comment by andrewda** [comment]
`grunt build`
