### ISSUE TITLE
 Scanning with multiple users

### ISSUE THREAD

**Issue by Giopi** [AHAAAAAAA/PokemonGo-Map#2705]
Scanning with multiple users

## Expected Behavior
How do I ensure the scanning approximately 1,000 people?

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by andrewda** [comment]
What exactly are you asking? If you need help, please use the discord. This issues tracker should be for issues only.
