### ISSUE TITLE
Nginx Reverse Proxy domain.com/go

### ISSUE THREAD

**Issue by daneren2005** [AHAAAAAAA/PokemonGo-Map#2706]
## Current Behavior
Setting up a reverse proxy to domain.com/go does not work because all of the assets are still hosted under /.  The initial page load but everything beyond that (ie: css) fails because it loads from domain.com/css instead of domain.com/go/css

## Possible Solution
Need a param in addition to host and port (extension?) which allows the use with reverse proxies

## Your Environment
* Version used: commit 6363f6c37c4336189e4839830ff6f2cf791049ad
* Operating System and version (desktop or mobile): Ubuntu 14.04 with Nginx

**Comment by tkSimon** [comment]
The commit you mentioned works fine for me, using:
````
location /go/ {
        proxy_pass http://127.0.0.1:5000/;
}
````
If you were running a different version of this application before, try CTRL+F5 to reload the page from network. (telling the browser not to use its cache)

**Comment by W1ndst0rm** [comment]
@tkSimon nailed it. I had the same problem. When I added the trailing slash to my location everything worked fine. Just make sure you're navigating to domain.com/go/

**Comment by tkSimon** [comment]
I added a note to the nginx wiki page:

    If you want to access your maps at www.YourDomain.com/go/: (note the trailing slash!)

@daneren2005 If this resolves your issue, please close.

**Comment by daneren2005** [comment]
For the life of me I couldn't get it to work last night.  I'm wondering if the old response was being cached or something, since now it works fine.  Sorry for wasting everyone's time.

**Comment by tkSimon** [comment]
Happens often; when you change versions make sure to reload-from-network: CTRL+F5 ;)
