### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by into** [AHAAAAAAA/PokemonGo-Map#271]
Could you add removing a pokemon from the map, maybe a check mark you can click on after clicking on the pokemon to remove it? Just so when I catch it, I can remove it from the map. Would be useful but not all that important. Thanks.

**Comment by JZ6** [comment]
great idea

**Comment by meersjo** [comment]
Given that the game knows which spawns you caught/have fled, perhaps this information could be grabbed from the account data and applied?

Of course, that would not work if you use this with a burner account...

**Comment by into** [comment]
@meersjo Which I do, so that wouldn't help in the slightest. :d

**Comment by MonkeyLeeT** [comment]
Since we have ignore option for pokemons, front-end developers will make use of it and allow you to ignore list of pokemons once they're done with front end interaction.
