### ISSUE TITLE
Webhook problems

### ISSUE THREAD

**Issue by RealestRealist** [AHAAAAAAA/PokemonGo-Map#2711]
## Expected Behavior

The webhook does not send the name of pokemon that spawned and sends despawn time as a long number that is not helpful.  It also sends notifications for ALL pokemon and I really dont want 100 pidgey and rattata texts.
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by andrewda** [comment]
We're not sent the names of the Pokemon from the Niantic servers. The webhook is basically a relay, so if you want to get the Pokemon name, use the `pokemon.en.json` file.

Also, if you're going to only want to use some of the Pokemon webhooks, then all you have to do is add filter out those that don't meet the requirements, right? All that's needed is a simple if statement...
