### ISSUE TITLE
Please remove grunt, it doesnt work on a Pi

### ISSUE THREAD

**Issue by Hoekynl** [AHAAAAAAA/PokemonGo-Map#2718]
## Expected Behavior
I would love to run the server agian, but on the latest version i need to install grunt and do a grunt build. Well installing grunt is not the problem, but executing grunt build is because grunt-sass is not compatible with ARM

## Current Behavior
It doesnt work

## Possible Solution
Removing grunt, or pre-executing grunt build before the upload

## Steps to Reproduce (for bugs)
1. Get a Pi
2. Install PokemonGoMap
3. Execute grunt build in the folder
4. watch the error "grunt-sass is not compatible with ARM"

## Context
I can not use this anymore, which sucks.

## Your Environment
RPI 3b
Python 2.7
NPM
Grunt v6
Raspbian

**Comment by Hoekynl** [comment]
Ok so I think I got things working a bit, don't ask me how because I really don't know.
I get this error
`pi@pgo:/srv/pgomap$ sudo grunt build -f
Running "clean:build" (clean) task
>> 0 paths cleaned.

Running "babel:dist" (babel) task
Warning: Couldn't find preset "es2015" relative to directory "static/js" Used --force, continuing.

Running "uglify:build" (uglify) task
>> Destination static/dist/js/app.min.js not written because src files were empty.
>> Destination static/dist/js/map.min.js not written because src files were empty.
>> Destination static/dist/js/mobile.min.js not written because src files were empty.
>> Destination static/dist/js/stats.min.js not written because src files were empty.
>> No files created.
`

**Comment by Dutzen** [comment]
How exactly did install npm (version?) and grunt?  i fail :D

**Comment by b3rguinho** [comment]
@Dutzen if Pi try:
wget https://nodejs.org/dist/v4.4.7/node-v4.4.7-linux-armv7l.tar.xz
tar -xvf node-v4.4.7-linux-armv7l.tar.xz
cd node-v4.4.7-linux-armv7l.tar.xz
sudo cp -R * /usr/local/
