### ISSUE TITLE
locale setting is not applied to the options menu

### ISSUE THREAD

**Issue by Lops88** [AHAAAAAAA/PokemonGo-Map#2730]
## Expected Behavior
language specific pokemon-names should be used in the exclude/notify section

## Current Behavior
the english names are being used, regardless of user selected locale

using latest develop build: #2667

**Comment by tschroeder-zendesk** [comment]
Somebody appears to have messed up the language selection in the browser afaict. It was working when my translation branch was merged. I will look into this and try to submit a fix. But currently the browser thinks it's set to en when I run the server with locale ru. However this is all translation in the ui that is failing not just the exclude/notify. (some of the translation is done in the backend like pokemon)

**Comment by tim95030** [comment]
This should be fixed now.
