### ISSUE TITLE
Remove the red marker? Keeps moving startpoint. 

### ISSUE THREAD

**Issue by ewigg** [AHAAAAAAA/PokemonGo-Map#2732]
Can I remove or diable the redmarker in any way?

I have set false on draggable marker but I share the server with more people and I think that someone can move the marker and the startpoint, scan moves.

See my Image, its have moved. I havent touched it :)

<img width="400" alt="moves" src="https://cloud.githubusercontent.com/assets/6955113/17271326/a21c7632-5678-11e6-8470-9c2a7dea3807.PNG">

**Comment by Gonoshift** [comment]
You can avoid it's generation on the client by commenting out this line in **map.js**
`var marker = createSearchMarker();`

**Comment by SOLiNARY** [comment]
if you want to disable it on server, open `pogom/app.py` then change the:
```
 def next_loc(self):
        args = get_args()
        if args.fixed_location:
            blabla code
```
with this:
```
 def next_loc(self):
        return 'Location searching is turned off', 403
        args = get_args()
        if args.fixed_location:
            blabla stuff
```

**Comment by Gamewalker** [comment]
I start my server with -os and only location parameter and then all other worker with real accounts and so u cant move the first one, or if u do, without any effect.

**Comment by joveice** [comment]
-fl "Fixed location" pretty self explanatory.
