### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by jfilice** [AHAAAAAAA/PokemonGo-Map#2734]
![screenshot 7](https://cloud.githubusercontent.com/assets/20742405/17271560/5137bf0e-564d-11e6-97f5-11df60638f8f.png)

Keep running into this error message, I'm not sure what to do.

**Comment by H3npi** [comment]
replace example.py with runserver.py

**Comment by jfilice** [comment]
Thank you! I'm not very computer savvy so I appreciate it. I had to remove the -ar command but it is working now.

**Comment by leTokki** [comment]
Always hide your username and password
