### ISSUE TITLE
Looking for private template for PokemonGo-Map

### ISSUE THREAD

**Issue by vinsilsim** [AHAAAAAAA/PokemonGo-Map#2735]
Looking for someone to make a private template, I paid for bitcoin or paypal.

Skype: psx.athbr

**Comment by Paralysing** [comment]
Github is a code discussion site, not a shop, looks like someone's copying PokeVision.

**Comment by vinsilsim** [comment]
@Paralysing ok bro how delete?

**Comment by Paralysing** [comment]
You could close the issue, don't think you could delete it.
