### ISSUE TITLE
Question: Is there any way to customize scan range?

### ISSUE THREAD

**Issue by abradu** [AHAAAAAAA/PokemonGo-Map#2739]
For example using the -st line you set it to a number of scans in every direction.
Is there any way to customize it so it only scans for example 7 north and east of your point, but only 4 south and west?

**Comment by invisiblek** [comment]
No, there is not

I doubt such a feature would be considered either. It would add a ton of extra complexity to the code

**Comment by jimdrie** [comment]
You can add extra scanner processes on the same database already to accomplish this.

**Comment by chuyskywalker** [comment]
Yup, set up several smaller scan regions
