### ISSUE TITLE
Maps opening in St. Paul MN -_- 

### ISSUE THREAD

**Issue by Invaderofbunnie** [AHAAAAAAA/PokemonGo-Map#2744]
Does not matter what Coordinate I enter into the CMD, I continue to get St. Paul MN as the location...

## Expected Behavior
Based on GPS coordinates, should be opening where i tell it to.

## Current Behavior
Current script: 
`python runserver.py -a ptc -u ***** -p ******* -l "41.515060 -90.456192 -st 5`

## Possible Solution
I've attempted to change to another nearby location, didn't matter. 

## Context
Now I wish I lived in St. Paul -_-

* Version used:
Python 2.7.7
Windows 10 (*shakes fist*) 
Dell Latitude 35500

**Comment by tim95030** [comment]
you are missing closing double brackets on your location

**Comment by andrewda** [comment]
What @tim95030., My guess is that the geocoder sees `-st` and thinks you're talking about St. Paul.

**Comment by Invaderofbunnie** [comment]
Oh Geez!!! Thank you guys so much... could I be anymore of a noob >_<
