### ISSUE TITLE
[Security] Password and API key visible to other users

### ISSUE THREAD

**Issue by ikegami** [AHAAAAAAA/PokemonGo-Map#2747]
To launch runserver, one needs to provide one's username and password on the command line, as well as one's Google API key.

On unix systems, the parameters passed to executing programs are visible to everyone on the machine (regardless of permissions), so everyone else on the machine has to access one's credentials when one run this program.

Please provide a means of passing the parameters using a config file instead. Standard filesystem permissions can then be used to prevent others from accessing one's credentials.

**Comment by CtrlAltDefeat94** [comment]
https://github.com/AHAAAAAAA/PokemonGo-Map/blob/master/config/config.ini.example
