### ISSUE TITLE
Cant start

### ISSUE THREAD

**Issue by denniskai1234** [AHAAAAAAA/PokemonGo-Map#275]
When i try to start the map i get this error:

Traceback (most recent call last):
  File "example.py", line 28, in <module>
    from requests.packages.urllib3.exceptions import InsecureRequestWarning
ImportError: cannot import name InsecureRequestWarning

Makes no different if i add options or just execute the example.py

**Comment by denniskai1234** [comment]
Is it possible to download a old version? Current version dosent work.

**Comment by betrisey** [comment]
You should try this
`sudo easy_install --upgrade pip`
Then download the requirements again
`pip install -r requirements.txt`

http://stackoverflow.com/questions/28987891/patch-pyopenssl-for-sslv3-issue

**Comment by FlyVik** [comment]
Hello! I'm from Ukraine. interested in playing Pokemon go read this article https://github.com/AHAAAAAAA/PokemonGo-Map, and I can not ask, I do not understand, could not you help me?
