### ISSUE TITLE
ImportError: No module named LatLon

### ISSUE THREAD

**Issue by FrenzyDemon** [AHAAAAAAA/PokemonGo-Map#2753]
## Expected Behavior
Use the Hex-Beehive-Generator to obtain coordinates.

## Current Behavior

Instead of coordinates I receive an error stating:

Traceback (most recent call last):
  File "C:...\location_generator.py", line 3, in <module>
    import LatLon
ImportError: No module named LatLon

## Context

I am trying to get the Coordinates so that I can insert them into my Spreadsheet, then into the beehive.bat file as described in the Wiki Instructions.

I successfully did this on one computer yesterday, following the same steps, but now I cannot reproduce it on another computer.
## Your Environment

Python 2.7.12 / Windows 10 Laptop

**Comment by 123456abcdef** [comment]
Execute `pip install -r requirements.txt` again and check the ouput, the dependency LatLon is not installed and should be installed with the command mentioned before.

**Comment by FrenzyDemon** [comment]
When I execute that command, I get another error: 
![error code](https://cloud.githubusercontent.com/assets/20687581/17273016/01b57cbe-5675-11e6-9b52-0cfa87bfc23e.png)

**Comment by Zingkitty** [comment]
In the exact same boat.

**Comment by rhinogator** [comment]
same error here

**Comment by elvador** [comment]
Just do what the error message tells you: Get vcpython27. (See the line above the red error message)

**Comment by manzarek123** [comment]
For debian:
apt-get install python-dev

**Comment by FrenzyDemon** [comment]
Okay, I went and installed VCPython and I was able to input my coordinates, but it does not behave in the same manner it did previously.

Instead of being returned coordinates, it says "Generating beehive script to ../../beehive.sh"
I am not sure what I am supposed to do with "beehive.sh"
Previously, I would just copy and paste coordinates into a Spreadsheet, then use that to create "beehive.bat" (as per the Wiki instructions)

**Comment by brandonshults** [comment]
Since you are on Windows you need to pass the --windows flag.  This will generate beehive.bat instead of beehive.sh. There is no longer a need for the spreadsheet.

**Comment by FrenzyDemon** [comment]
I'm sorry, but I am very inexperienced and have been struggling and trying my best to get this far.

Can you please tell me exactly when and where I'm adding the "-- windows flag"

**Comment by brandonshults** [comment]
When you run location_generator.py add --windows it's all in the instructions: https://github.com/AHAAAAAAA/PokemonGo-Map/blob/develop/Tools/Hex-Beehive-Generator/Instructions%20for%20location_generator.txt

**Comment by Zingkitty** [comment]
I'm trying to use this:
 python location_generator.py -lat 53.548207 -lon -113.496720 -st 5 -lp 3 --accounts C:\Users\MOVIES\Desktop\POGODEV\PokemonGo-Map-develop\Tools\Hex-Beehive-Generator\Accounts.csv --windows --installdir=C:\Users\MOVIES\Desktop\POGODEV\PokemonGo-Map-develop

but nothing is generated (no sh or .bat file)

**Comment by Zingkitty** [comment]
I'm trying to use this line:

python location_generator.py -lat 53.548207 -lon -113.496720 -st 5 -lp 3 --accounts C:\Users\MOVIES\Desktop\POGODEV\PokemonGo-Map-develop\Tools\Hex-Beehive-Generator\Accounts.csv --windows --installdir=C:\Users\MOVIES\Desktop\POGODEV\PokemonGo-Map-develop

but no files are generated.

**Comment by brandonshults** [comment]
Maybe add quotes around your paths?  Also by default the beehive.bat will be up two directories so for you that would be: C:\Users\MOVIES\Desktop\POGODEV\PokemonGo-Map-develop

**Comment by Zingkitty** [comment]
Yea i've tried with and without quotes, no file is generated in that directory.

**Comment by FrenzyDemon** [comment]
Okay, now that I have the beehive.bat file that is automatically generated. When I run it, it says that "The process "python.exe" not found."

I'm sorry for so many questions, but the instructions are not clear on what do about this.

**Comment by brandonshults** [comment]
Probably this line in location_generator.py: pythonpath = "C:\\Python27\\Python.exe"

**Comment by joelverhagen** [comment]
Try install this:
https://www.microsoft.com/en-us/download/details.aspx?id=44266

Then run `pip install -r requirement.txt` again in the root PokemonGo-Map server.

**Comment by FrenzyDemon** [comment]
The path in location_generator.py is already correct.

I reinstalled VCPython, and the requirements.txt and I am still getting the same error. Am I supposed to be in a particular directory when I open beehive.bat?

**Comment by Zingkitty** [comment]
SIDENOTE: my own issue was fixed! for some reason location_generator was completely empty (0kbs)
