### ISSUE TITLE
Long scan time

### ISSUE THREAD

**Issue by george0wnz** [AHAAAAAAA/PokemonGo-Map#2755]
I have an issue with it taking a long time to scan 2 minutes to do step count 5. 5 -7 sec a scan. How can I change that in hiroku.

**Comment by Paralysing** [comment]
I believe there is a setting called EXTRA_ARGS, haven't worked with heroku much, check the [wiki](https://www.jonaharagon.com/PoGoMapWiki/#!heroku.md) for more info. The highest you can go tight now is -t 3 -sd 1.

**Comment by george0wnz** [comment]
Thank you I got it working!
