### ISSUE TITLE
ImportError: No module named flask_compress

### ISSUE THREAD

**Issue by prinzpi** [AHAAAAAAA/PokemonGo-Map#2757]
Hi,

if I trying to use the newest version of the map, I will receive the following error message, after trying to start the python script.

```
python runserver.py
Traceback (most recent call last):
  File "runserver.py", line 13, in <module>
    from pogom.app import Pogom
  File "/home/xxx/pokemon/pogom/app.py", line 9, in <module>
    from flask_compress import Compress
ImportError: No module named flask_compress
```

With the last version everything was working fine.
Can somebody explain me which could be the root of the issue?

I'm using "screen" to run the script several times, the locations are always different, also another PTC account is in use.

Thanks for help.

**Comment by Paralysing** [comment]
Try pip install flask_compress

**Comment by prinzpi** [comment]
Thanks, have also to update / install some other packages.
Now it's working fine again.
