### ISSUE TITLE
Blurry Icons

### ISSUE THREAD

**Issue by JZ6** [AHAAAAAAA/PokemonGo-Map#276]
New icons are blurry, but they are the right size.
Solutions:
go back to 65x icons instead of the 30x now, and figure out a fix for the icon size issue
go back to old pixelated icons.

**Comment by Rominiust** [comment]
If you head into /static/icons from the main folder, that's where the icons are stored.  You can go into the /static/icons/old folder, and copy & replace them to the /icons folder, and it'll replace the newer icons with the old, pixelated icons.

In my opinion it's easier to tell which the old ones are quicker, but that's just personal preference.

**Comment by haagiboy88** [comment]
Don't we have a merged 2x icons already somewhere? The old pixelated ones. Someone with skills in photoshop can easily batch resize them all to the specified size.

**Comment by haagiboy88** [comment]
See pr#98

**Comment by quagliero** [comment]
I have a 5 line fix/update for this if people are still interested? Reverting back to the pixelated images and using the Google Map Icon Object, with the scaledSize property:

![retina-icons-iphone5](https://cloud.githubusercontent.com/assets/4254570/17019015/4ee5373a-4f32-11e6-8f58-1333a8bc69a5.PNG)
