### ISSUE TITLE
Correct scan radius 70 or 100 m?

### ISSUE THREAD

**Issue by Imoq** [AHAAAAAAA/PokemonGo-Map#2768]
I was watching https://github.com/AHAAAAAAA/PokemonGo-Map/pull/2610 and changed my scan radius from 100 m to 70 m, but now I see the issue closed and change not applied to main branch. What is the right value then? Should I revert back to 100 m?

Thanks!

**Comment by chimpy** [comment]
It's still in develop.

**Comment by Imoq** [comment]
Great, sorry, you are right. I'll now be quiet and go sit in a corner :) Thanks!
