### ISSUE TITLE
Unclear what the actual scanning radius of the tool is

### ISSUE THREAD

**Issue by SeraphC** [AHAAAAAAA/PokemonGo-Map#2775]
## Expected Behavior
We should be able to pass scanning radius should be in km rather than 'steps' and if possible scanning radius should be indicated on the map.

## Current Behavior
The algorithm is scanning an area, the size of which I can roughly make out from the algorithm. However it is still very much unclear where the edge is. This may be important when you want to be sure certain spawn locations at the edge of your target area are included without making the number of scanned steps unnecessary large.

## Possible Solution
-Allow scanning radius to be provided in km rather than steps.
-Indicate scanned area on map.
-Document scanning algorithm.

**Comment by medghaim** [comment]
Help/discussion here: https://discord.gg/tw6fj
