### ISSUE TITLE
Placing on hosting

### ISSUE THREAD

**Issue by vtboren56** [AHAAAAAAA/PokemonGo-Map#278]
Can I put your application hosting, to have access to it from the domain?

**Comment by DerScreever** [comment]
feel free to do it :D

**Comment by vtboren56** [comment]
I have posted applications on a domain, installed all the dependencies, ran everything, but when I go to a domain that does not work, what am I doing wrong?

**Comment by vtboren56** [comment]
Who can write a little different than the instructions to start the computer from running on a hosting with reference to the domain? I think it will be interesting to many.

**Comment by betrisey** [comment]
Have you specified the public IP of the server with the -H or --host parameter?

**Comment by iRodri** [comment]
Are you using the host 0.0.0.0?

**Comment by FlyVik** [comment]
Hello! I'm from Ukraine. interested in playing Pokemon go read this article https://github.com/AHAAAAAAA/PokemonGo-Map, and I can not ask, I do not understand, could not you help me?

**Comment by oceanor** [comment]
It gives error when using -H 0.0.0.0, I'll posy a screen of it from pc

**Comment by vtboren56** [comment]
If I use the host 0.0.0.0 then get an error socket.error: [Errno 13] Permission denied

**Comment by JZ6** [comment]
that's a problem with your server

**Comment by vtboren56** [comment]
I correctly understand that I need to have a dedicated ip?

**Comment by iRodri** [comment]
It doesn't matter, right now I have it running in a LAN server, you just need to configure it correctly.

**Comment by oceanor** [comment]
even having a dedicated ip, using port 80 and keeping it to localhost with port forwarding correctly configured, when you access the server from outside it will show a blank page

**Comment by vtboren56** [comment]
When I put port 80, I get the same error
socket.error: [Errno 13] Permission denied

**Comment by vtboren56** [comment]
When I go to the domain I see 403 error

**Comment by iRodri** [comment]
Is the server located in your lan or is it outside of your network?

**Comment by oceanor** [comment]
starting using -H 0.0.0.0 -P 80, getting this error:

**Comment by vtboren56** [comment]
Thats not my hosting - jino.ru

**Comment by iRodri** [comment]
Oh, so you are asking if you can use a web hosting to run this program. Unless you redirect all traffic into a VPN, no.

**Comment by Temetz** [comment]
Ports <1024 are privileged and require special permissions (administrator) to be used on unix / windows systems.

**Comment by vtboren56** [comment]
> Oh, so you are asking if you can use a web hosting to run this program. Unless you redirect all traffic into a VPN, no.

It is very sad

**Comment by nekitk** [comment]
to run server on 80 port and 0.0.0.0 host you should run it with root permissions
just put `sudo` in the command's beginning
also you don't need static ip — you can use special DNS server like no-ip.com

**Comment by chuparCh0pper** [comment]
See [README.md](https://github.com/AHAAAAAAA/PokemonGo-Map/blob/master/README.md)

### make server externally visible
#### IPv4
`python example.py -a PTC -u myUsername -p myPassword -l "Central Park, New York, NY" -st 5 -H 0.0.0.0 -P 5000`
#### IPv6
`python example.py -a PTC -u myUsername -p myPassword -l "Central Park, New York, NY" -st 5 -H :: -P 5000`

**Comment by crckdns** [comment]
It's pretty simple and who can't adjust it to run externally, they don't need it.. sorry, but that's getting more and more kiddie-like "I want it, do it for me, I get all the credits for the work you did" :/

**Comment by chuparCh0pper** [comment]
[I'm such a leet hacker](http://i.imgur.com/fndsHh8.jpg)
