### ISSUE TITLE
No Exclusions and Drop Down Menus Don't work

### ISSUE THREAD

**Issue by brando56894** [AHAAAAAAA/PokemonGo-Map#2780]
I just pulled down the latest commits (most current: c10f9a187d2e626a382eff4a3bebe496fa80963c) and the exclusion feature no longer works, also the drop down menus for Exlusions and Notifications don't have any content and aren't clickable. Map Style also doesn't contain anything either.

http://www.imagebam.com/image/cfa181497647348

**Comment by aaiezza** [comment]
Might be because of this: #2777

Actually probably definitely

**Comment by danielbennifer** [comment]
I'm having a similar problem. And, in addition to this, I'm unable to change the location of the marker through the options menu. As I type, it starts to bring up suggested locations, but won't allow one to be clicked.

**Comment by daaaaa** [comment]
I had the same issue using chrome. I pressed ctrl + f5 to clean the cache and it works now.

**Comment by danielbennifer** [comment]
@daaaaa With the exclusions and drop down menu, or the change location functionality?

**Comment by brando56894** [comment]
Didn't fix anything for me either.

**Comment by brando56894** [comment]
Issues are fixed in the latest commits.
