### ISSUE TITLE
Temporary fix to rate limiting/no pokemon being found

### ISSUE THREAD

**Issue by skeldoor** [AHAAAAAAA/PokemonGo-Map#2784]
## Expected Behavior
Should be able to scan with -sd 1 without issues.

## Current Behavior
Scanning with low -sd numbers causes the server to reject the request and return zero pokemon, pokestops, or gyms.

## Possible Solution
Run scanners with at least -sd 5 in towns, possible to get away with -sd 3 in cities.

## Context
[Reddit thread](https://www.reddit.com/r/pokemongodev/comments/4vev3u/psa_get_map_objects_min_refresh_seconds_5/) - Rate limiting has been implemented and seems to have a 5 second delay between map object requests.

**Comment by chuyskywalker** [comment]
There are several other issues open about this at right now. Such as #2777
