### ISSUE TITLE
Deploying to Heroku does not work as intended

### ISSUE THREAD

**Issue by alanyee** [AHAAAAAAA/PokemonGo-Map#2786]
## Expected Behavior
The webapp should show me green circles with there the pokemon, pokestops, and gyms are.         

## Current Behavior
The webapp just shows me the map with the correct location, but I do not seen any circles. So I do not any pokemon, pokestops, and gyms. But if I clone the repository, I see the webapp works as expected.

# Steps to Reproduce (for bugs)
1. Go to https://github.com/AHAAAAAAA/PokemonGo-Map
2. Click on Deploy to Heroku
3. Follow the prompted steps to deploy to Heroku
4. View the app

## Context
I want it to work on a site that I can access from my phone. 

## Your Environment
Heroku is Heroku. Locally, 
* Version used: Latest one - #1299 
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): macOS Sierra

**Comment by stevenpratt** [comment]
I think heroku server IPs are blocked now so your account doesn't get logged in and never begins scanning.

**Comment by chrismapes** [comment]
Niantic banned heroku and Amazon AWS.

**Comment by FrostTheFox** [comment]
Heroku is blocked, see the reference above.
