### ISSUE TITLE
ImportError: No module named Flask_cors?

### ISSUE THREAD

**Issue by KSUWildcatFan** [AHAAAAAAA/PokemonGo-Map#2789]
Getting this when I try to type python ./runserver.py --help

Supposed to display the help list with the current release. I was using an old build that was just fine prior to the most recent patch. I had made some modifications for email notifications (within the PY code itself) and didn't really want to upgrade in the first place. Is there any easy change I could make to the original PY code to implement the -sd functionality? I'd really rather that than even bother trying to use the new version. Otherwise, I need help making this one work. I can't get it going for some reason.

**Comment by medghaim** [comment]
Help questions here: https://discord.gg/tw6fj
