### ISSUE TITLE
Addition of email notification within the script?

### ISSUE THREAD

**Issue by KSUWildcatFan** [AHAAAAAAA/PokemonGo-Map#2798]
I had this working in one of the original releases but I haven't been able to figure out just where the searching is happening in the current version (just started looking)..Figured I'd throw it out there.

I had mine notifying me of the pokemon name, #, GPS coordinates, and how long until despawn. This way I could start my server at home, get in my car, and drive around to pick up everything I was notified about. I think it'd be a great enhancement if someone wanted to put the time into adding it.

**Comment by TJohnson93** [comment]
@KSUWildcatFan Not a bad idea... Perhaps better through Pushbullet, Slack etc... ??

**Comment by chuyskywalker** [comment]
Try the `/mobile` page with phone tracking. Light weight and easy. Email notification will not be added.

**Comment by codyma94** [comment]
@chuyskywalker sorry, this sounds like exactly what I need, but what do you mean by the `/mobile` page? Thank you!

**Comment by KSUWildcatFan** [comment]
I'd much prefer phone notifications, but I'm with cody..what do you mean /mobile?

**Comment by chuyskywalker** [comment]
If you're running the application somewhere like `http://yourpokesite.com' or `http://10.12.21.51` just add `/mobile` to the url
