### ISSUE TITLE
Please run grunt build

### ISSUE THREAD

**Issue by talentedmrripley** [AHAAAAAAA/PokemonGo-Map#2799]
## Expected Behavior

Start runserver.py

## Current Behavior

When I try to run it I get this message:
[    MainThread][     runserver] [CRITICAL] Please run "grunt build" before starting the server.

## Steps to Reproduce (for bugs)

1. Clone the develop branch
2. python runserver.py

I've had it up and running for several days.  Decided to clone the develop branch to grab recent changes and now I can't get it to start up.

**Comment by chuyskywalker** [comment]
https://github.com/AHAAAAAAA/PokemonGo-Map/wiki#how-to-get-it-up--running-grunt-included-on-a-fresh-ubuntu-1604-vpsvm-root-is-implied
