### ISSUE TITLE
Error running from heroku

### ISSUE THREAD

**Issue by grantleehoffman** [AHAAAAAAA/PokemonGo-Map#2800]
## Expected Behavior
Getting proper data back from niantic for pokemon locations

## Current Behavior
No pokemon can be found on the map. Receiving the following errors in the heroku logs:

```
[   auth_google] [   INFO] Google Login successful
[   auth_google] [  DEBUG] Google Session Token: xxxxxxxxxxx
[connectionpool] [   INFO] Starting new HTTPS connection (1): pgorelease.nianticlabs.com
[connectionpool] [  DEBUG] "POST /plfe/rpc HTTP/1.1" 403 None
[       rpc_api] [WARNING] Unexpected HTTP server response - needs 200 got 403
```

## Possible Solution
Not sure, can run from local machine with no issues

## Steps to Reproduce (for bugs)

1. execution from local machine
2. run same execution from heroku

## Context
Am unable to run server on heroku

## Your Environment
python 2.7
ran locally with same command line options using google auth

**Comment by Paralysing** [comment]
Not sure if related, but check issue #2774 , niantic is now throttling requests even harder to about 1 request per 5 seconds, they also started blocking ips.

**Comment by Paralysing** [comment]
I'm pretty sure heroku runs off Amazon AWS, and Niantic has definately blocked AWS instance ips.
