### ISSUE TITLE
Niantic problem, or Code problem? [search_thread][rpc_api] [WARNING] Unexpected HTTP server response - needs 200 got 403

### ISSUE THREAD

**Issue by Schwaitz** [AHAAAAAAA/PokemonGo-Map#2802]
Hey guys,

I'm currently getting this error:

`[search_thread][rpc_api] [WARNING] Unexpected HTTP server response - needs 200 got 403`

Is it an API overloaded error, or something in the code? I am getting a successful login.

**Comment by PaleHaunt** [comment]
Heroku was banned tonight it seems along with several cloud based servers.

**Comment by Schwaitz** [comment]
@PaleHaunt I am not running off of Heroku. Would they really ban all of AWS?

**Comment by Paralysing** [comment]
I think they did ban all of AWS, look at issue #2774 , lots of AWS users are reporting they were blocked.

**Comment by chrismapes** [comment]
@Schwaitz Yeah, my guess is that they are whitelisting their own servers Google App Engine and banning the rest of AWS, Google, Rackspace, and anything else fir which they can get IP ranges.

**Comment by Schwaitz** [comment]
@chrismapes @Paralysing, Would running all external calls through a proxy be possible? I've done it with python before using a large list and cycling through ones that work. I could probably jerry-rig it into this code as well.

**Comment by Paralysing** [comment]
@Schwaitz It probably would work, as long as Niantic doesn't ban other hosts, so far, my OVH servers still work, but you also might be able to use google app engine to host the proxy server.
