### ISSUE TITLE
How do I add scan delay to the bat file template found at https://www.jonaharagon.com/PoGoMapWiki/#!beehive.md

### ISSUE THREAD

**Issue by dilroopgill** [AHAAAAAAA/PokemonGo-Map#2808]

**Comment by brandonshults** [comment]
Just add it to PokemonGo-Map's config.ini in the config folder.

**Comment by dilroopgill** [comment]
Does that affect the bat file running the server? The bat has its own thread limit, so I thought it was seperate?

**Comment by dilroopgill** [comment]
SET thread=-t 1
is in the bat

**Comment by medghaim** [comment]
Help/discussion here: https://discord.gg/tw6fj
