### ISSUE TITLE
and I can not ask, I do not understand, could not you help me?

### ISSUE THREAD

**Issue by FlyVik** [AHAAAAAAA/PokemonGo-Map#281]
Hello! I'm from Ukraine. interested in playing Pokemon first read this article https://github.com/AHAAAAAAA/PokemonGo-Map, and I can not ask, I do not understand, could not you help me?

**Comment by FlyVik** [comment]
Where to set and use this program? how to open Google Maps?

**Comment by Temetz** [comment]
If you are running on linux machine:

git pull https://github.com/AHAAAAAAA/PokemonGo-Map
cd PokemonGo-Map
pip install -r requirements.txt
python example.py -a authService -u myUsername -p myPassword -l "Boulder, CO" -st 5

After a while you can navigate to http://127.0.0.1:5000 and you should see the map populated.

See the README.md (https://github.com/AHAAAAAAA/PokemonGo-Map/blob/master/README.md)
for all the switches and options.

**Comment by Johanneshn** [comment]
[This might get you on the right track](https://www.reddit.com/r/pokemongodev/comments/4t80df/wip_pokemon_go_map_visualization_google_maps_view/d5feu2f)

**Comment by FlyVik** [comment]
I open and write python example.py -a authService -u myUsername -p myPassword -l "Boulder, CO" -st 5, and it is a mistake I wrote, but as I write the data and map coordinates

**Comment by FlyVik** [comment]
I open and write python example.py -a authService -u myUsername -p myPassword -l "Boulder, CO" -st 5, and it is a mistake I wrote, but as I write the data and map coordinates

**Comment by FlyVik** [comment]
I'm done there and says nothing

**Comment by JZ6** [comment]
FlyVik  stop spamming

**Comment by FlyVik** [comment]
sorry, I accidentally

**Comment by FlyVik** [comment]
No one will help me

**Comment by nakami** [comment]
@FlyVik, please don't open up project issues for such matters.
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discordapp.com/invite/qbpVH6b).
