### ISSUE TITLE
Hex Builder location broken 

### ISSUE THREAD

**Issue by Quiv** [AHAAAAAAA/PokemonGo-Map#2810]
Hello, i'm trying to set multi thread but it seems i have a problem with hex builder ...
Using the up to date dev branch.
All center of each scan are not at the correct place.
I test all my location with google map and http://www.hamstermap.com/quickmap.php and nothing showing at the correct place.

hex generator : 

python location_generator.py -lat 18.024281 -lon -63.047378 -st 5 -lp 2 --account accounts.csv --auth google

What it is suppose to look like with coords : 

![2](https://cloud.githubusercontent.com/assets/6039307/17275199/cbe6da86-56d5-11e6-858a-dc9dc9f4925a.jpg)

What it does : 

![1](https://cloud.githubusercontent.com/assets/6039307/17275201/d0c83ac2-56d5-11e6-88fb-aeb3ca28aa28.jpg)

## Steps to Reproduce (for bugs)
1. clean install w/ dev branch
2. locationgenerator.py

## Your Environment

* Version used:
Dev Branch 
Ubuntu server 16.04

Please can anyone help me to understand.
Thanks in advance

**Comment by fourmansyah** [comment]
can some one help me with this problem ?
<div class="separator" style="clear: both; text-align: center;">
<a href="https://2.bp.blogspot.com/-eS6n-0OEL0c/V52odIf46ZI/AAAAAAAAKx4/UvuMdrVigVsSIlUnsWuRgXx43vJvFzkUgCLcB/s1600/1.jpg" imageanchor="1" style="margin-left: 1em; margin-right: 1em;"><img border="0" height="316" src="https://2.bp.blogspot.com/-eS6n-0OEL0c/V52odIf46ZI/AAAAAAAAKx4/UvuMdrVigVsSIlUnsWuRgXx43vJvFzkUgCLcB/s640/1.jpg" width="640" /></a></div>

**Comment by Quiv** [comment]
your answer has nothing to do in this issue .... thanks

**Comment by NoMotion** [comment]
I think this is a duplicate issue people have been posting. Take a search on the dev branch for this issue
