### ISSUE TITLE
Scanning outside of specified radius?

### ISSUE THREAD

**Issue by NickyNice** [AHAAAAAAA/PokemonGo-Map#2813]
Here is an image showing what I am talking about. http://imgur.com/a/3wLDs

It seems like the scanner is just randomly going to places it shouldn't be. Has anybody seen this or know what might be going on here? Everything seems to work fine when I first move to a location but shortly after I start seeing less and less Pokemon. I'm now thinking its because its not even scanning where I want it to. Any ideas? Using v 2.1.0

**Comment by miaojs** [comment]
I've noticed this.

**Comment by hhu94** [comment]
Those are lured pokemon. The scanned area represents the area scanned for non-lured pokemon.
