### ISSUE TITLE
Heroku version doesn't scan anymore

### ISSUE THREAD

**Issue by OlloApocalypso** [AHAAAAAAA/PokemonGo-Map#2816]
Hi guys,

Scanning in the Heroku version doesn't work for me anymore. No scan activities are shown with "Scanned Locations" enabled. 

I did deploy a new version to Heroku, but the problem remains.

The local version on my windows PC is still doing fine. Any idea how to fix this or what caused the problem? Is it related to the latest patch?

Cheers,

**Comment by miaojs** [comment]
#2777 

Probably being blocked.

**Comment by medghaim** [comment]
https://discord.gg/tw6fj
