### ISSUE TITLE
Update Usage example

### ISSUE THREAD

**Issue by KevakaBuel** [AHAAAAAAA/PokemonGo-Map#282]
Could you update the Usage example for more parameters. I cant seem go get -dp to work for me.

**Comment by DerScreever** [comment]
python example.py -u user -p passoword -l "location" -st 5 **-dp -dg** -H "Host" -P 80

just pass them alone without true of false behind

**Comment by KevakaBuel** [comment]
Ok i thought so, but it does not show any pokestops (there are definitely a few in the search radius) so i thought i missed an argument.

**Comment by chuparCh0pper** [comment]
Please see Pull request https://github.com/AHAAAAAAA/PokemonGo-Map/pull/283

**Comment by DerScreever** [comment]
done
