### ISSUE TITLE
[Possible Issue] Less pokemon detected than before?

### ISSUE THREAD

**Issue by danielzt12** [AHAAAAAAA/PokemonGo-Map#2827]
I have been running this for a few days now. 
And yesterday around midnight I began to feel that less pokemons were upserted each time ? Being a noob I am wondering if this is somehow related to the latest update. They updated the client version maybe they also changed something on the server side?
P.S. I have tried different -t and -td combination and it doesn't seem to help the situation.

Environment: OSX 10.10 Chrome 51

**Comment by oleerik** [comment]
-sd 5 :)

**Comment by freakjam** [comment]
#2824 
#2774

**Comment by danielzt12** [comment]
Hello guys thanks for the reply
but are you sure this is the issue?
On reddit someone claims that it was like this long before that
https://www.reddit.com/r/pokemongodev/comments/4vev3u/psa_get_map_objects_min_refresh_seconds_5/d5y3jtt

**Comment by MRokas** [comment]
Not an issue.
