### ISSUE TITLE
Click on the map to search

### ISSUE THREAD

**Issue by deada92** [AHAAAAAAA/PokemonGo-Map#2840]
I would like to be able to click on a place on the map to start searching. I would think its pretty easy because the most functionality are already there. Can you u guys hint me to the right place where I can implement this?

**Comment by heldertb** [comment]
Probably in map.js (: (under static/js/map.js)

**Comment by deada92** [comment]
I have added this to map.js


```
  //Add listener
  google.maps.event.addListener(map, "click", function (event) {
      var latitude = event.latLng.lat();
      var longitude = event.latLng.lng();
      console.log( latitude + ', ' + longitude );
  }); //end addListener
```

but nothing is printed on the console. Any idea why?

**Comment by deada92** [comment]
Solution pasted in static/dist/js/map.js:

``

  //Add listener
  google.maps.event.addListener(map, "click", function (event) {
      var latitude = event.latLng.lat();
      var longitude = event.latLng.lng();
      changeLocation(latitude, longitude);
  }); //end addListener
``
