### ISSUE TITLE
No Information about the --accounts option in location_generator.py (beehive)

### ISSUE THREAD

**Issue by Somnium42** [AHAAAAAAA/PokemonGo-Map#2846]
There is absolutely no information in the wikis about the usage of the --accounts option in beehive.
I tried multiple schemes for my file "accounts.txt"  but none worked since i don't know what is used to seperate each argument like -p, -a, -u.
Example accounts.txt
-a ptc -u asdf -p asdfsdfsad,
-a ptc -u fdas -p fasfdsfad,
......
This puts everything in the "-u collum" in beehive.sh
or 
asdf -p asdfa,
....
or asdf asdf
....

All these don't work since i don't know how ot separate each input field

## Possible Solution
Adding example accounts.txt into the /Tools/Hex-beehive folder.
Update Wiki.

## Your Environment

* Version used: dev
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): Ubuntu server 16.04

**Comment by littlebigcat** [comment]
The clue is in the instructions with the accounts.csv name. You need to feed it comma separated values

"name1,pass1
name2,pass2
name3,pass3"

Without quotations obviously

**Comment by Somnium42** [comment]
Thank you for the answer. :+1:  This should get added to the wiki.
Best Regards
