### ISSUE TITLE
Support multiple accounts

### ISSUE THREAD

**Issue by lucastockmann** [AHAAAAAAA/PokemonGo-Map#285]
What do you think about supporting multiple accounts? - The benefits are that we can have more accurate data and scale larger.

My target would be to have a map of the whole city I live in.

**Comment by MikeDX** [comment]
Once the persistent data pull request is merged, this is trivial as you can run multiple instances and they will share a database

**Comment by JZ6** [comment]
multiple accounts are already supported, just run each in a different port, I have 3 bots going all the time
