### ISSUE TITLE
Best way to Update to new Version?

### ISSUE THREAD

**Issue by FrenzyDemon** [AHAAAAAAA/PokemonGo-Map#2850]
## Context

How can I update to the latest version without messing up any files that I need. Do I just simply Install the Develop branch again and overwrite the entire Pokemon Go Map folder? Do I only update the specific files that were updated? Do I have to start over like I'm setting it up for the first time?

I'm sorry if this seems like a stupid question, but I struggled very much just for the initial installation and I don't want to burn everything down when I update to the new version
## Your Environment

* Version used: 
* Environment name and version (e.g. Python 2.7): Python 2.7.12
* Operating System and version (desktop or mobile): Windows 10 Desktop

**Comment by freakjam** [comment]
Use msysgit and do a git pull to only download/pull the latest changes.

**Comment by PaleHaunt** [comment]
What is the best way to update to the new version using a Mac?

**Comment by lighter857** [comment]
@freakjam can you please elaborate on how to do that.. apologies i'm fairly new at this stuff.. I am using the dev version.

**Comment by freakjam** [comment]
Linux even easier.

**Install git:**
sudo apt-get install git

**Clone repo:**
git clone -b develop https://github.com/AHAAAAAAA/PokemonGo-Map

**Download updates:**
cwd into PokemonGo-Map and do a "git pull"
