### ISSUE TITLE
Modify map.html

### ISSUE THREAD

**Issue by deada92** [AHAAAAAAA/PokemonGo-Map#2856]
I'm trying to remove/add some custom stuff to the left bar.. maybe let it appear on desktop from beginning. I'm editing the map.html in `templates/map.html` but the changes dont appear... Wheres the right location of that file?

**Comment by Gonoshift** [comment]
Changes aren't live cause the python script loads the html resource and if you change it while is loaded you won't see any change, you have to kill and restart the server.

**Comment by deada92** [comment]
awesome ty
