### ISSUE TITLE
Push notifications

### ISSUE THREAD

**Issue by KassiusKlay** [AHAAAAAAA/PokemonGo-Map#2859]
Hello, 

Im sorry if this has been asked before.

I have been running PogoMap with 8 accounts. I can get the native notifications (blinking sound) on the PC but if im checking the map on Chrome mobile app it doesnt work. 

I know some scanners have integrated Push notifications and also know about the PokemonGo-Finder project but it seems outdated.

Any way to make Push notifications natively here?

Thanks and sorry if this has been answered before.

**Comment by Maxsky5** [comment]
Yes you can thanks to webhooks. More informations here : https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Using-Webhooks
I'm using IFTTT + PushBullet, and it's working fine :)

**Comment by KassiusKlay** [comment]
Ill give it a try and report back. 

Thank you for your answer.

**Comment by KassiusKlay** [comment]
hmmm even after reading through the wiki Im not able to do this by my own. 

Would you be so kind to share the code so I can just edit the pokemon id and put my pushbullet api key? 

Thank you so much

**Comment by chromer90** [comment]
Install this extension and then add the argument to the config of main map or in your command. Works pretty well for me. https://github.com/kvangent/PokeAlarm

**Comment by KassiusKlay** [comment]
Wow thank you so much chromer90.

Works wonderfully!

Cheers
