### ISSUE TITLE
Auto update map data

### ISSUE THREAD

**Issue by rockneurotiko** [AHAAAAAAA/PokemonGo-Map#286]
Hi!

First of all, this is a really great project, as soon as I have some time I'll check the source and issues and see if I can help with something :smile: 

While I'm using it I'm thinking that a good idea to avoid redraw the google map (the API limits sucks), if the auto-refresh is enabled, the server can open a websocket and the client connect to it to receive new pokemons in the area (or an API call from the client every "x" seconds to get updates).

I don't know if this has been suggested before, I've searched but I can't find it :)

Thanks and really awesome work guys!

**Comment by DerScreever** [comment]
already working on a solution

**Comment by nborrmann** [comment]
I don't get the question. Auto-refresh doesn't redraw the map, it just adds and removes markers. 
How would websockets of all things help?
