### ISSUE TITLE
Map Does Not Display Any Pokemon

### ISSUE THREAD

**Issue by dkhodaba** [AHAAAAAAA/PokemonGo-Map#2862]
## Expected Behavior
Pokemon that are upserted display on the map when the Pokemon slider is toggled on.

## Current Behavior
Pokemon are being upserted and written to the database but even with all display options toggled on only gyms and pokestops will display on the map.

## Possible Solution
Not sure, but I suspect maybe the web server is failing to create objects for the pokemon on the map. No errors are showing in the console. It could be that the database is recording time to disappear in GMT/UTC but this could also be standard behavior. Since it is detecting lure status correctly, I am doubtful this is the cause.

## Steps to Reproduce (for bugs)

Running runserver.py with the normal procedure.
http://imgur.com/a/qDmyW for images of console, db table, and map

## Environment
* Version used: Current dev and current master using sqlite db
* Environment name and version (e.g. Python 2.7): Python 2.7.12
* Operating System and version (desktop or mobile): Windows 7 x64

**Comment by Ayysir** [comment]
Niantic changed the api and reduced some calls and radius

**Comment by dkhodaba** [comment]
Yeah. Not sure. I expect it's environmental, but everything else seems fine. I don't think it's Niantic related because the db is still getting pokemon written to it. Even if I delete the db file and run the server again it's still getting populated, but _nothing_ shows on the map.

**Comment by MajorT1990** [comment]
Had the same issue on my server. Syncing system time resolved it for me. My system clock was 7 minutes ahead.

**Comment by pattyjogal** [comment]
+1 To MajorT1990. My system time goofs when I switch from Windows to Linux, and setting it correctly brought back the pokemon. I guess they disappear because they have expired, as far as the program can tell, if the system time is x minutes/hours ahead.

**Comment by dkhodaba** [comment]
Another +1 to MajortT1990. I can't believe I didn't notice that my computer was an entire day off track. Everything is working now.
