### ISSUE TITLE
Any documentation on how to use webhooks with twitter?

### ISSUE THREAD

**Issue by DomGrieco** [AHAAAAAAA/PokemonGo-Map#2866]
Does anyone have any documentation or examples on how to use webhooks to post to twitter? Thank you!

**Comment by MRokas** [comment]
You've to write some server-side code which upon receiving webhook's json will use Twitter's API to post a tweet.

You should just google about using Twitter API.

**Comment by DomGrieco** [comment]
@MRokas Gotcha, thanks.

**Comment by Maxsky5** [comment]
You could also use IFTTT with Maker and Twitter. Maker as trigger (receiving POST requests) and Twitter as action.
