### ISSUE TITLE
Visualization user-dependent

### ISSUE THREAD

**Issue by MarcoAbejorro** [AHAAAAAAA/PokemonGo-Map#287]
Hi everyone,
i have a question about the visualization.
Is the result user-dependent?

I use the scanner with my PTC-Account and at the same time i play with my google account.
But the pokemon is not there when i go to that locations on the map.

So have every user his own "map" of pokemons?
Do i have to use the same account for the scanner and game?
THX
Have a nice day

**Comment by Octylpy** [comment]
Pokemons are shared among all users. You should be able to see them on another account.

**Comment by JZ6** [comment]
pokemon that comes from lures or incense do not show up currently
