### ISSUE TITLE
Easier way to change locations

### ISSUE THREAD

**Issue by Draco18s** [AHAAAAAAA/PokemonGo-Map#2871]
Any possibility of getting some kind of "move pin here" by clicking on the map?  I was using PokeVision to get GPS coordinates to plug into the change location text field, but with that one down (likely for good) there isn't an easy way to relocate the scan area.

I can still use Google Maps, but it's less precise (I have to roughly center the desired location on screen, then grab the current URL).

**Comment by Paralysing** [comment]
Not sure if the feature was in the master or develop branch, but there was a double click to add point.

**Comment by slashy** [comment]
You can use an address aswell. You don't have to get GPS coordianates.

Also when you use Google Maps you can rightclick on the desired location and select "what's here" and a window will open that contains the coordinates that you can copy. Though just using addresses or even places is much easier.

**Comment by SethG911** [comment]
Currently you can just drag the red pin to another location.

**Comment by juliusrucker25** [comment]
can confirm, you can drag the pin around to another location

**Comment by Draco18s** [comment]
Ah ha, so you can. Thanks fellas.  I'd tried double clicks and right-clicking with no success.

(Address is only marginally helpful, as I don't always know the address of the place I want to look at, for instance yesterday I was doing scouting to find a place with several gyms in close proximity, as the two super-close ones I did know about were occupied by cp2200 dragonites and I did not have the resources necessary to take them both down).
