### ISSUE TITLE
Google Maps api is required error

### ISSUE THREAD

**Issue by Shervin415** [AHAAAAAAA/PokemonGo-Map#2873]
I tried looking at the tutorial on YouTube but in that config folder it had different files so I looked on the wiki and followed it but it seems outdated. When I go to config and change the config in notepad and put my info and then do python runserver.py in the cmd of that folder where I saved it says "runserver.py: error: argument -k/--gmaps-key is required"
Any help is appreciated.

**Comment by SpechtXXO** [comment]
You need an own google maps key, try this wiki 
https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Google-Maps-API-Key

**Comment by medghaim** [comment]
Help here please: https://discord.gg/tw6fj
