### ISSUE TITLE
Bug. Beehive generates an really uneven searcher distribution

### ISSUE THREAD

**Issue by Somnium42** [AHAAAAAAA/PokemonGo-Map#2879]
I launched beehive with the command "python /usr/local/pokmap/PokemonGo-Map-develop/Tools/Hex-Beehive-Generator/location_generator.py -st 6 -lp 5 -lat 123 -lon 123 --accounts /usr/local/pokmap/PokemonGo-Map-develop/accounts.txt" and it generated an uneven pattern. 
![Uploading Screenshot_2016-07-31_20-54-22.png…] see picture for details.
![screenshot_2016-07-31_20-54-22](https://cloud.githubusercontent.com/assets/15572960/17278628/b180ea06-5761-11e6-8aa3-0105edb8c352.png)

## Steps to Reproduce (for bugs)

1. Download latest dev build 
2. Install it on Ubuntu server 16.04 (following the instructions of the wiki)
3. Generate an beehive.sh with st 6 lp 5 and an account list
4. ----

## Context
[http://188.68.32.25:4777 live example ]

## Your Environment

* Version used: newest dev
* Environment name and version (e.g. Python 2.7): py 2.7
* Operating System and version (desktop or mobile): Ubuntu 16.04

**Comment by jimdrie** [comment]
The coordinates in the beehive.sh file should have a comma, that's why it goes wrong. See #2815.

**Comment by Somnium42** [comment]
Thank you for the answer. I will close this now since there is already a pull request for the fix.
