### ISSUE TITLE
Keep getting "runserver.py: error: unrecognized arguments: of Georgia, Athens, Georgia"

### ISSUE THREAD

**Issue by fireplaceweird** [AHAAAAAAA/PokemonGo-Map#2882]
Trying to get this code working, it worked the first time with these inputs but now every time I try, the location seems to not be recognized.
I inputted this exactly (except the username and password):
python example.py -a ptc -u **** -p ***** -l “University of Georgia, Athens, Georgia” -st 30

It just keeps giving me "runserver.py: error: unrecognized arguments: of Georgia, Athens, Georgia"
I'm not sure if it just isn't recognizing the beginning of it "University" or if it is purposely excluded.
I have tried: 
Geocoordinates with a space between
Geocoordinates with a comma between
No comma between words in the address
Exact address of a specific place in the university with commas
Exact address of a specific place with no commas (spaces)

Anyone help would be greatly appreciated. Thanks.

**Comment by fireplaceweird** [comment]
I have also tried adding the gmaps key and have tried getting a new key and trying again but to no avail

**Comment by fireplaceweird** [comment]
Now it just says [runserver][ERROR] Could not get a position by name, aborting. Any other ideas? @Somnium42

**Comment by Inrego** [comment]
I emptied the file and provided the info through run parameters. That worked for me.

**Comment by medghaim** [comment]
Help questions here, please: https://discord.gg/tw6fj
