### ISSUE TITLE
Git Pull'd, and scan location changed???

### ISSUE THREAD

**Issue by DeviantEng** [AHAAAAAAA/PokemonGo-Map#2887]
Have a simple setup; 2 accounts with `-st 6 -sd 5`, one running 90 seconds after the other.  Not sure what commit I was previously running, but I did a git pull a could hours ago, and then my scan area changed (cells got closer together?).  Did a git pull just a few minutes ago, and still having the same thing.  What's up?

http://imgur.com/a/MWyu9

I wish I knew what commit I was on that was working, else I'd just roll back.

**Comment by WtfJoke** [comment]
Im running c360bec8fd607de5cc0cc388e9723631136c8e52, no problems so far

**Comment by DeviantEng** [comment]
Running `a83ce5c` on both my web server and my scan sever (2 separate boxes).  

How can I rollback to a certain commit with git?

**Comment by WtfJoke** [comment]
I think git checkout c360bec8fd607de5cc0cc388e9723631136c8e52 should do the job

**Comment by DeviantEng** [comment]
Turns out `npm install` was not running `grunt install` (was erroring on that), so I had to do so manually with `node_module/.bin/grunt install` and it seems to be working now.

If I understand correctly, the scan area was changed from 100m down to 70m, so I pulled that new code but didn't let the frontend rebuild so it was using the 70m logic, with 100m visuals (or something like that).
