### ISSUE TITLE
Nothing found at all with dev branch

### ISSUE THREAD

**Issue by Scalpweb** [AHAAAAAAA/PokemonGo-Map#2889]
No pokemon found with the dev branch. I have an older version working fine, but the freshly downloaded dev branch gives me nothing.

## Expected Behavior

It should find some pokemon...

## Current Behavior

Nothing found at all

## Steps to Reproduce (for bugs)

1. Download the dev branch
2. Install it by following the wiki
3. Run the command:
python /home/pokemap-dev/PokemonGo-Map/runserver.py -u ### -a google -p ### -k ### -st 1 -l "Paris, France" -ns -dc -t 1 -sd 5

## Your Environment

* Version used: Dev branch
* Environment name and version (e.g. Python 2.7): Pything 2.7
* Operating System and version (desktop or mobile): CentOs 6

**Comment by iOS4ever** [comment]
I see nothing with the master branch either. Which master build are you running?

**Comment by crckdns** [comment]
with one step? I doubt you are lucky enough to find a pokemon exactly there where the scan starts..  it is possible for sure, but with luck.  why not scanning more area?

**Comment by excitedbox** [comment]
@crckdns That is like using google's I'm feeling lucky button.

**Comment by Scalpweb** [comment]
Yep, that was stupid. Sorry.
