### ISSUE TITLE
Slow refreshing / pokemon disappear

### ISSUE THREAD

**Issue by denniskai1234** [AHAAAAAAA/PokemonGo-Map#289]
After running the map for some time it shows less and less pokemon it, looks like its very slow reloading the area?

After restaring the script it shows up all pokemon again.

OS Debian 8 amd 64
python --version
Python 2.7.9

python example.py -u nope-p nope -l "51.9606649, 7.626134699999966" -st 10 -a ptc -H 127.0.0.1 -P 5000 -L de -ar 15

**Comment by JZ6** [comment]
stale / expired pokemon gets removed

**Comment by denniskai1234** [comment]
I know that they get removed, but it shows in the town after some time like 3-4 pokemons after a restart its back to 50+.

**Comment by Plop** [comment]
Got the same problem. After a few minutes, less and less pokemon, until there is not a single pokemon left. I have to restart manually to get the pokemon back

**Comment by denniskai1234** [comment]
Before i open another issue, does anyone know if there is any kind of rate limiting on the pokemon servers side? Im running the map for multiply persons on one of my servers but im not sure if it could create any issues since it requests so much from one ip.

**Comment by KingsDevelopment** [comment]
Your server is the only one pinging, your friends are getting it from your server. @denniskai1234

**Comment by denniskai1234** [comment]
My english sucks thats why you didnt understood what im trying to say. Ofc i know that they dont get any data from the pokemon go servers, but my server does and when i run 4-5 different maps maybe they see too many request from one ip and block my server.

**Comment by DerScreever** [comment]
same as #325
