### ISSUE TITLE
Change algorithm

### ISSUE THREAD

**Issue by grinsekatze003** [AHAAAAAAA/PokemonGo-Map#29]
Any plans on changing the current algorithm? It shows only pokemon that are north of the given location.

**Comment by sykhro** [comment]
GitHub issues are for bug reporting.  
For general support, and feature request, join [our discord server](https://discord.gg/kwAcr7e).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.
