### ISSUE TITLE
Clear up the example.py mess

### ISSUE THREAD

**Issue by nborrmann** [AHAAAAAAA/PokemonGo-Map#290]
We need to split up the example.py file asap.

I suggest something along the lines of:
- `runserver.py` starts the server and background thread, reads flags and settings
- `background_thread.py` The, uh, background thread
- `controller.py` Our API endpoints
- `pokemongo-api.py` functions that interact with the gameservers, retries, etc.
- `models.py` as introduced by #264.

This breaks all other PRs, before working on this we should discuss in discord and stop all other dev.

**Comment by JZ6** [comment]
+1 from me, commit all major pulls then go full steam ahead

**Comment by medghaim** [comment]
Yarr, I'd like to help!

**Comment by Octylpy** [comment]
Should we put everything into a `src/` folder?

**Comment by tejado** [comment]
I suggest to replace my (!) old codebase with the new structure which is rewritten from scratch and more future compatible:
https://github.com/tejado/pgoapi

**Comment by DerScreever** [comment]
@sykhro is already ready to do this :P

**Comment by nborrmann** [comment]
very nice @tejado.

**Comment by medghaim** [comment]
Marking as closed, this is done thanks to @nborrmann  and @favil
