### ISSUE TITLE
So Finally, here comes to the end. If developers being more 'silent' what's going on here, I bet I could use this for months longer

### ISSUE THREAD

**Issue by actondong** [AHAAAAAAA/PokemonGo-Map#2904]
I anticipated this  end week ago by how eye-catching this project is trying to be. Hackers do things in shade, especially when they hack something.  :) GG

**Comment by andrewda** [comment]
I don't think you can blame this on the developers...

**Comment by chuyskywalker** [comment]
Oh man! We hackers have totally screwed up. I guess I'll have to throw away my sweet outfit:

![hacker](https://cloud.githubusercontent.com/assets/131800/17280533/9b20ac8a-5746-11e6-906d-affb8cf79454.jpg)
