### ISSUE TITLE
Can't seem to login with multiple accounts

### ISSUE THREAD

**Issue by NunoPontes** [AHAAAAAAA/PokemonGo-Map#2906]
So I've read tons of stuff on how I can get multiple account to scan 1 area to work, but I can't seem to find a way. 

 Problem: It will only login with user2

Command:
python runserver.py -a "ptc" -u user1 -u user2 -p password12 -st 5 -k key -l "Coimbra" -t 6 -sd 1 -td 1 -ld 1

**Comment by Gamewalker** [comment]
part of my ubuntu server script:

```
params="-st 10 -sd 6 -t 1 -ns"
nohup python runserver.py -l "50.732380,7.101401" -st 10 -H 0.0.0.0 -L de -fl -m -os >/dev/null 2>&1&
nohup python runserver.py -a ptc -u XXX125 -p XXX125 -l "50.748843,7.052284" $params >/dev/null 2>&1&
nohup python runserver.py -a ptc -u XXX126 -p XXX126 -l "50.732380,7.101401" $params >/dev/null 2>&1&
nohup python runserver.py -a ptc -u XXX127 -p XXX127 -l "50.684906,7.156043" $params >/dev/null 2>&1&
nohup python runserver.py -a ptc -u XXX128 -p XXX128 -l "50.687268,7.189910" $params >/dev/null 2>&1&
nohup python runserver.py -a ptc -u XXX123 -p XXX123 -l "50.633188,7.152835" $params >/dev/null 2>&1&
nohup python runserver.py -a ptc -u XXX -p XXXX -l "50.713727,7.061035" $params >/dev/null 2>&1&
nohup python runserver.py -a ptc -u XXX129 -p XXX129 -l "50.708126,7.142189" $params >/dev/null 2>&1&
nohup python runserver.py -a ptc -u XXX -p XXX -l "50.715204, 7.108148" $params >/dev/null 2>&1&
```

**Comment by NunoPontes** [comment]
but in your case you run multiple instances, right?

i want to in 1 console have 2 or more accounts on the same location.

This is my .bat file:

START runserver.py -a ptc -u user1 -p pass1 -u user2 -p pass12 -st 5 -k key -l "Coimbra" -t 2 -sd 1 -td 1 -ld 1

When i run it only the user2 gets the login

**Comment by NunoPontes** [comment]
Managed to fix it not sure how, but it started working after grunt install, i dont know if it's related, but still.

Command:  START runserver.py -a "ptc" -u user1 -u user2 -p pass12 -st 10 -k key -l "location" -t 6 -sd 0.2 -td 1 -ld 1
