### ISSUE TITLE
Parallel logins for Multiple accounts

### ISSUE THREAD

**Issue by Frozen-byte** [AHAAAAAAA/PokemonGo-Map#2908]
This feature request was inspired by testing the feature given by #2568 

## Expected Behavior
Start search immediately after login for one account passes.

## Current Behavior
All accounts are logged in, then the searchers are started.

## Possible Solution
merge the loops :loop: 

## Steps to Reproduce (for bugs)

1. Make 4500 Accounts
2. Paste them into the config.ini
3. start the runserver.py
4. watch the output.

## Context
Beehive generator takes a bunch of resources currently and is not that easy to use/configure. 
It's way easier to have a single high stepcount of 120 or so doing the same job.

## Your Environment

* Version used: develop a83ce5c0e6bfa4a97df485498e27fe3a0181ef7a
* Environment name and version (e.g. Python 2.7): python2.7
* Operating System and version (desktop or mobile): debian 12.04

**Comment by DomGrieco** [comment]
Even with 20+ accounts takes awhile to authenticate. It would be nice if the searcher started as each account logged in.

**Comment by DomGrieco** [comment]
Also, if 1 account get's, let's say, unexpected server response, it will stop the searcher from moving forward.

**Comment by DomGrieco** [comment]
`2016-07-31 20:45:25,118 [ search_thread][      auth_ptc] [   INFO] PTC login for: ###
2016-07-31 20:45:25,563 [ search_thread][      auth_ptc] [   INFO] PTC Login successful
2016-07-31 20:45:26,646 [ search_thread][        pgoapi] [  ERROR] Login failed - unexpected server response!
2016-07-31 20:45:26,646 [ search_thread][        search] [   INFO] Failed to login to Pokemon Go. Trying again in 5 seconds.`

When this happens, it will stop the searcher until the error goes away. In some cases I haven't seen it go away in over 30 minutes.

**Comment by Epion003** [comment]
@DomGrieco yea i have that happen once in awhile also. would be nice if we had a way to restart the worker that stopped...

**Comment by DomGrieco** [comment]
I also noticed when you run a lot of accounts in 1 searcher (tested with 40) you will get a lot of ` [  ERROR] Search thread failed. Response dictionary key error`. So would that mean they also have some type of soft throttle for multiple request by IP within X amount of time? I'm not sure, just speculating.

Although, if I run 40 accounts in using a searcher for each account and set a 5-second delay between when each one launches I don't normally see these errors.

Also, using 1 thread per account with a scan delay of 5.2.

**Comment by Epion003** [comment]
@DomGrieco what do you mean 40 accts with a searcher for each? How would u set that up. I only scan for myself so i spent this whole wknd reading the diff post till i was finally able to get a nice small beehive for myself going only 3leaps at 5 steps with -sd 5ram think today was longest it ran before i had my 1st worker stop then 2nd hour or 2 later.  I also have a 2nd file that i run on a seperate port so i can use the geotrack feature on moblie while walking which i luv. wast testing it today for 6-7 hrs with no prob so far. but always looking to learn new methods....

**Comment by kipperjx2** [comment]
how do u list multiple accounts in the line say that are all ptc

**Comment by DomGrieco** [comment]
> The following parameters should be ok:
> 
> Using single account should be just as it was earlier:
> ./runserver.py -a ptc -u user -p pass -st 3 -t 3 ...
> 
> This will use ptc for all accounts and ask interactively
> for one password to use for all accounts:
> ./runserver.py -u user1 -u user2 -u user3 -st 3 -t 3 ...
> 
> This will use password 'pass' for all accounts and use ptc:
> ./runserver.py -u user1 -u user2 -u user3 -p pass -st 3 -t 3 ...
> 
> This will use google for all accounts and unique passwords
> for each account:
> ./runserver.py -a google -u user1 -u user2 -p pass1 -p pass2 ...
> 
> This will log one in ptc and one in google with respective un/pw:
> ./runserver.py -a ptc -a google -u user1 -u user2 -p pass1 -p pass2 ...
> 
> In config.ini these can be given as lists or single values:
> auth-service: [google, ptc]
> username: [user1, user2]
> password: onepasswordforbothaccounts
> 
From the commit 8c9a64dca5e73147e569b4ce9f0ac0a4f3fda078

**Comment by Frozen-byte** [comment]
Resolved by PR #2956
