### ISSUE TITLE
Example.py is not a good main file name.

### ISSUE THREAD

**Issue by KnightHawk3** [AHAAAAAAA/PokemonGo-Map#291]
As far as I can tell this is a holdover from the example this project was based on, I propose that sooner rather than later we rename it to something more indicative of what it is, like `PokemonGoMap.py` or `PoGOMap.py`

Obviously this is a semi breaking change but in an early stage of development it won't be as bad.

**Comment by JZ6** [comment]
in goal list

**Comment by KnightHawk3** [comment]
Sorry, didn't see it there (I did search open issues though!)
