### ISSUE TITLE
error  [CRITICAL] Please run "grunt build" before starting the server.

### ISSUE THREAD

**Issue by shiznewski** [AHAAAAAAA/PokemonGo-Map#2910]
I downloaded the latest development branch. And when i try to start it gives me this error

2016-07-31 18:57:36,671 [    MainThread][     runserver] [CRITICAL] Please run "grunt build" before starting the server.

I have ran pip install to make sure everything is updated

python runserver.py -a google -u ###@gmail.com -u ###@gmail.com -p #### -p #### -t 2 -sd 5 -st 10 -k AIzaSyA9##### -l "###" -H 0.0.0.0 -P 5011 -wh http://####.com/pokemon/alarms.php

**Comment by numb401** [comment]
https://www.jonaharagon.com/PoGoMapWiki/#!Development.md

**Comment by shiznewski** [comment]
I installed grunt and tried the command now i get this.

root@PokemonGoMap1:/_pkmgo/1# grunt build
/usr/bin/env: ‘node’: No such file or directory

**Comment by BillyWM** [comment]
Develop is for developers only. If you're just trying to run the map, download a release:

https://github.com/AHAAAAAAA/PokemonGo-Map/releases

**Comment by shiznewski** [comment]
I've had the map working for a while. and installed the webhooks version wrote my custom webhooks and all that. Now i'm interested in the multi account since the scannign speed has gotten slow. I know lots of languages but they are the more higher level easier langauges.. Your right i probably should just wait for it all to be merged in.

Sorry

**Comment by Pymous** [comment]
The error you have is related to your installation of Node, you should check it :) 

What is "node -v" and "npm -v" returns ?

**Comment by soptikopava** [comment]
node -v  returned "v4.4.7"
npm -v returned "2.15.8"

**Comment by BillyWM** [comment]
@soptikopava: You have to run "npm install" after you install Grunt (This is different from running "npm install -g grunt")

running "npm install" will look inside package.json and install everything that's listed as a dependency in that file.

**Comment by abighairyspider** [comment]
Thanks numb401! Not sure why all the elitist tools couldn't have just provided that info days ago instead of just spamming the same canned response over and over in the 50 or so threads that spawned... You'd have thought those instructions were the freaking formula for cold fusion from the obtuse responses...

**Comment by BillyWM** [comment]
>Thanks numb401! Not sure why all the elitist tools couldn't have just provided that info days ago 

@abighairyspider: I'm the "elitist tool" that wrote the page @numb401 linked to.
