### ISSUE TITLE
Google Login doesn't work work with Google 2-Step Verification

### ISSUE THREAD

**Issue by pixocode** [AHAAAAAAA/PokemonGo-Map#292]
### Environment info
Operating System: Cubuntu 16.04  
Installed version of Python: 2.7  

### Steps to reproduce
1. `python example.py -a goo monadresse@gmail.com -l "Lyon, France" -st 5 -H 0.0.0.0 -L fr`  
2. insert my google password  
3. "Wrong username/password"  

### Logs or other output that would be helpful
```
Exception in thread search_thread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "example.py", line 581, in main
    api_endpoint, access_token, profile_response = login(args)
  File "example.py", line 92, in memoizer
    cache[key] = obj(*args, **kwargs)
  File "example.py", line 516, in login
    raise Exception('[-] Wrong username/password')
```

**Comment by HanSolo80** [comment]
You can create application specific passwords that work when you have 2-step validation active. So in my opinion this is enough.
See [Google Answer](https://support.google.com/accounts/answer/185833?hl=en)

**Comment by pixocode** [comment]
I had not thought of, thank you ^^ "
