### ISSUE TITLE
localhost:5000 Map Won't Load

### ISSUE THREAD

**Issue by Deathscythe193** [AHAAAAAAA/PokemonGo-Map#2921]
## Expected Behavior

Map should load to see streets etc at location.

## Current Behavior

Map does not load when going to "localhost:5000", it is just a blank white screen where the map should be with Pokémon Go Map in the top left with the "Options" menu (that works).

## Possible Solution

Possibly software is out of date like java? I am not sure, looking for suggestions. I have tried restarting my computer, updating java and using a new google api.

## Steps to Reproduce (for bugs)

1. I use the runserver.py with the correct command lines, it launches and login successfully then starts to scan for pokemons/gyms/pokestops.
2. Go to localhost:5000 and the map fails to load. 
3.
4.

## Your Environment

* Version used: latest developer version from this morning
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): Windows 7 64 Bit

**Comment by excitedbox** [comment]
check that your api key has javascript api enabled/ create a java script api key.

**Comment by Deathscythe193** [comment]
According to the google maps api manager my api has access to javascript and google places API web services which are the two you are supposed to use.

**Comment by Enterodactyl** [comment]
This happened to me earlier today too. Try disabling the API for javascript and google places API web services. Then re-enable it.

**Comment by Deathscythe193** [comment]
How long should it take to disable one of them? I hit disable and it just sits spinning saying "DISABLING" for a while.

**Comment by Buddhaman42** [comment]
I am hoping someone can help solve this. I am having exact same issues. My API also has Javascript and Google places enabled. I have the correct API key in command line and everything is updated. I tried disabling and re-enabling and that did not help. Same as OP, I have the top bar fully functioning, but only a white screen where map should be. Any help?? (experience level: extremely novice)

**Comment by Deathscythe193** [comment]
Found the issue....use google Chrome as the web browser.

**Comment by Buddhaman42** [comment]
I am using Chrome and still having the issue. Anyone else have an idea what it could be?

**Comment by foodforarabbit** [comment]
Did you try putting the api key in config.ini? 

Try this if you haven't already:
1) make a copy of config.ini.example and rename it config.ini. Place it in the same folder (config).
2) uncomment the gmaps-key: line (remove the # from the front)
3) add your key after the colon, then save the file and restart your script.

**Comment by Buddhaman42** [comment]
Yeah. I tried that and no luck. By the way I am using -st 7 -sd 5 -t 1. Not
sure if the issues are related, but the returned searches in command window
are showing up with 179 pokestops, 6 gyms, and only 1 or 2 pokemon. Seems
odd as well. May be two unrelated issues, but thought I would mention it
just in case.
