### ISSUE TITLE
(Question) Database info

### ISSUE THREAD

**Issue by Epion003** [AHAAAAAAA/PokemonGo-Map#2926]
Sorry been trying to find but cant find info on how to access the database so i can understand the info in it not just times and lat lon directions. is there a script or something so if i access the DB i could find the spawn time for dratini or charmander for example.
Thank you for any help

**Comment by Paralysing** [comment]
pgogm.db is the sqlite database, I just use sqlitebrowser to see the "pokemon" table.

**Comment by Epion003** [comment]
@Paralysing I used the one from the wiki Mariadb i set it up just as the wiki said would you know how to use that?

**Comment by Paralysing** [comment]
Haven't used mariadb, only sqlite and mysql, sorry.

**Comment by Epion003** [comment]
mariadb is mysql that the wiki has but its ok thank you

**Comment by Epion003** [comment]
@Paralysing thx for your info kinda helped me find wat i was looking for after few google searches thank you
