### ISSUE TITLE
Allow parsing file with -i and -o flags

### ISSUE THREAD

**Issue by IsBoris** [AHAAAAAAA/PokemonGo-Map#293]
It would be nice to be able to use `-o rare.txt` and `-i common.txt` to shorten the command-line input and use same pokemon presets in other bash scripts.

**Comment by Sejadis** [comment]
I think it would actually be nice to be able to give all args trough a text file - would make it much easier  
something like example.py -args args.txt
with args.txt arguments seperated by ; or whatever

**Comment by KevakaBuel** [comment]
you know that you can create a simple .bat file to run example.py with all arguments? Just write the same you would actually write in the console in to a txt, name it run.bat (or whatever you like) and just open run.bat in the console.

Still agree with IsBoris that it would be nice to separate all arugments into separate txts.
