### ISSUE TITLE
Pokemon Notification does not appear to be working correctly

### ISSUE THREAD

**Issue by datbomb** [AHAAAAAAA/PokemonGo-Map#2932]
I'm not sure if this is a bug but the Pokemon notification seems to be acting up. Within the notification area I've added a few rare Pokemon such as Dratini and Dragonite. For obvious reasons I don't receive any notifications for these. 

However, I also added more common ones such as Eevee and Rattatta. When adding these Pokemons to the notification list the pop ups are constant. I can't hit the X fast enough. This doesn't reconcile with what I see (or lack of what I see) within maps. I'll receive about 20 Eevee notifications in a span of 30 seconds but the maps may show 1 or 2.

I'm not sure if it's a problem with the notification itself or whether it's actually seeing more than what can be displayed within the map.

Does anyone have any insight?

Not sure if this matters but here's my command line. It works well for the most part. Let me know if there are recommendations on improving my command line.
c:\python27\python.exe runserver.py -a ptc -u *** -p *** -l "***" -st 7 -sd 1 -t 2 -H 0.0.0.0 -L en -k ***

**Comment by thisisntmyrealname** [comment]
Check area pokestops with lures. When this happens, is the notification for the last lured pokemon?

**Comment by datbomb** [comment]
I filtered the maps to lured pokestops and I see a ton of lured Pokestops outside the range of my scanning. However, I only see a couple Eevee's near a couple Pokestops within my scanning range. Again, the amount of notifications I'm receiving doesn't reconcile with what I see on the maps.

Another interesting thing I'm seeing is that although I've shut down the command prompt _and_ maps I'm still receiving notifications. Not sure if this is related.

**Comment by Matsu16** [comment]
@datbomb #2930

**Comment by datbomb** [comment]
Thanks @Matsu16

I did a thread search earlier but must have missed that one.

**Comment by thisisntmyrealname** [comment]
We were probably writing ours up at the same time.

**Comment by datbomb** [comment]
I'll close this issue to reduce clutter but will keep it linked to yours @thisisntmyrealname
