### ISSUE TITLE
Failed to login

### ISSUE THREAD

**Issue by dogelord** [AHAAAAAAA/PokemonGo-Map#2934]
## Expected Behavior

running _python runserver.py -u [user] -p [pass] -st 10 -k [API key] -l "location" -H 0.0.0.0 -P 80_
I should get a succesful login.
## Current Behavior

When I run the command, it says that it could not retreive token: Username or Pass is incorrect.
I have verified my username and password, and they are correct. 
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

Unable to succesfully run python script / view map
## Your Environment

* Version used: Latest
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile):
Ubuntu Server 16.04 Droplet

**Comment by Paralysing** [comment]
Check #2774 , Niantic has started banning ip ranges of a few hosts.

**Comment by dogelord** [comment]
Well that's unfortunate. I'm on NYC2, others show blocked as well so I'm guessing that's it. Thanks for letting me know.
