### ISSUE TITLE
Auth issue?  Maps no longer updating - Unexpected HTTP server response 

### ISSUE THREAD

**Issue by stlalpha** [AHAAAAAAA/PokemonGo-Map#2935]
I am getting the following in my logs - and the maps are no longer updating:

 2016-08-01 02:14:17,730 [   auth_google] [   INFO] Google Login successful.
 2016-08-01 02:14:17,960 [       rpc_api] [WARNING] Unexpected HTTP server response - needs 200 got 403

Any ideas?  I am running latest.

**Comment by Paralysing** [comment]
Check out #2774 , Niantic banned ip ranges for a few hosts, if you're on AWS or DigitalOcean, that's probably the issue, 403 means forbidden.

**Comment by stlalpha** [comment]
Right on - thanks for the response.  I was on Heroku - moved hosts - working fine now.  Thanks!
