### ISSUE TITLE
Multiple users / threads?

### ISSUE THREAD

**Issue by gsabran** [AHAAAAAAA/PokemonGo-Map#2936]
There seems to be recent support for multiple users/threads (I don't get exactly if the two are related) but not a lot of documentation around it? Is it possible to have a single server behave similarly to several servers with independent logins / search characteristics?

From here https://github.com/AHAAAAAAA/PokemonGo-Map/blob/develop/pogom/search.py#L223-L225 it seems that only one position is taken into account

**Comment by rickymm3** [comment]
+ 1

**Comment by Paralysing** [comment]
Currently, only 1 position is used, multiple accounts was made to bypass Niantic's throttling.

**Comment by swemoney** [comment]
I don't think this is possible right now. The best you can do to duplicate this functionality is to run multiple instances of the web server with different ports and let each user use a different port. If all the servers are using the same mysql server, they should share all of their data but each webserver should be able to move the location themselves.

**Comment by gsabran** [comment]
Are you interested in a PR to have that functionality?

**Comment by coolaj86** [comment]
This (my) fork supports multiple users and uses node.js' native threads:

https://github.com/Daplie/node-pokemap

The server is completely stateless and allows the companion web client to operate just like its official counterpart (as to be less likely to get blocked):

* only updates when you're actually using the client
* doesn't require manual location setting
* server has very low memory and cpu requirements

**Comment by chuyskywalker** [comment]
It is not, and the feature has been rejected a few times because it's not in-line with the projects goals. (There really should be a wiki page about this...)

You can run the application multiple times against the same database to scan multiple areas, though.
