### ISSUE TITLE
Map Server crashes after 30 min - 1 hr

### ISSUE THREAD

**Issue by Valareos** [AHAAAAAAA/PokemonGo-Map#294]
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discordapp.com/invite/qbpVH6b).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System: Windows 7

Installed version of Python: 2.7.10

### Steps to reproduce
1.Run Program
2.Wait for 30 min - 1 hr
3. Problem appears

### What have you tried?
1.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

Error tossed is: 

Traceback (most recent call last):
  File "c:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "c:\Python27\lib\threading.py", line 1073, in run
    self.function(*self.args, **self.kwargs)
  File "example.py", line 592, in main
    pokemonsJSON, ignore, only)
  File "example.py", line 628, in process_step
    profile_response))
  File "example.py", line 409, in get_heartbeat
    payload = response.payload[0]
  File "c:\Python27\lib\site-packages\google\protobuf\internal\containers.py", l
ine 64, in __getitem__
    return self._values[key]
IndexError: list index out of range

**Comment by DerScreever** [comment]
should be already fixed

**Comment by Valareos** [comment]
I will download latest and see if issue still exists.

**Comment by Romancha** [comment]
"IndexError: list index out of range" - this error disappeared, but after 30 min - 1h on map no new Pokémon until reboot the server

**Comment by nakami** [comment]
i also have this issue. seems that after a single iteration, new iterations won't add pokemon to the map anymore...

**Comment by Valareos** [comment]
since downloading latest, issue hasn't reappeared.  Will run it overnight and report.

**Comment by Valareos** [comment]
Ok, Error is not there, but new pokemon stopped spawning. Resetting server fixes it.

**Comment by crckdns** [comment]
Can confirm that, new pokemon stop spawning after some longer runtime.
Dedicated Debian machine.

**Comment by Plop** [comment]
Confirm this too

**Comment by nborrmann** [comment]
Can confirm, but we'll be refactoring this in #264 which will most likely fix it. I will have another look after that got merged.

**Comment by sandsaber** [comment]
+ as in #325

**Comment by DerScreever** [comment]
Im sorry, but we dropped the support for the master branch (example.py). 
This branch is deprecated.  
The new branch contains a much cleaner structure so pls report only issues related to the develop branch. 

Your development team
