### ISSUE TITLE
osx install issue with requirements.txt

### ISSUE THREAD

**Issue by hannahbanana** [AHAAAAAAA/PokemonGo-Map#2943]
## Expected Behaviour
installation :-) have been chugging along nicely for a few weeks until I tried a fresh install today

## Current Behaviour
When I install python reqs: 

 curl https://bootstrap.pypa.io/get-pip.py > get-pip.py && sudo python ./get-pip.py && sudo -H easy_install --upgrade six && sudo -H easy_install --upgrade setuptools && sudo -H pip install requirements.txt

I get

Could not find a version that satisfies the requirement requirements.txt (from versions: )
No matching distribution found for requirements.txt

## Possible Solution
Only way I've deviated from the instructions is I installed to User/PoGo rather than to /Documents, because I've already got a bunch of stuff in there & I'm weird about my folders

## Your Environment
Mac OSX 10.11.6

**Comment by FrostTheFox** [comment]
it's pip install -r requirements.txt not pip install requirements.txt.

**Comment by PieterxJan** [comment]
I encountered the same issue and fixed it with the following command:

`pip install --upgrade six`

**Comment by hannahbanana** [comment]
Great, thank you - should I update the wiki?

**Comment by PieterxJan** [comment]
@hannahbanana As I also encountered the problem on my homestead vagrantbox, linode server and DO droplet, I think it's best to add it, yes.

**Comment by hannahbanana** [comment]
I've fixed in the wiki :-) thank you!
