### ISSUE TITLE
login credential

### ISSUE THREAD

**Issue by rooster415** [AHAAAAAAA/PokemonGo-Map#2945]
after i input 

python runserver.py -u [USERNAME] -p [PASSWORD] -st 10 -k [Google Maps API key] -l "[LOCATION]"

im getting a login verification fail but logged in at ptc

**Comment by medghaim** [comment]
Please go here for help/discussion: https://discord.gg/kjrcd

Closing, as this is not an issue.

**Comment by Cammo009** [comment]
Try 
For PTC: 
`python runserver.py -a ptc -u [USERNAME] -p [PASSWORD] -st 10 -k [Google Maps API key] -l "[LOCATION]"`

For Google: 
`python runserver.py -a google -u [USERNAME] -p [PASSWORD] -st 10 -k [Google Maps API key] -l "[LOCATION]"`
