### ISSUE TITLE
Unable to connect localhost:5000 after MariaDB MySQLLite setup.

### ISSUE THREAD

**Issue by shermsaludez** [AHAAAAAAA/PokemonGo-Map#2948]
## Expected Behavior

Loading into localhost:5000 is suppose to work

## Current Behavior

Running beehive.bat works
After editing the config.ini, i removed the # to uncomment and replaced it with the suggested on the wiki 

https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/How-to-start-using-a-MySQL-Server

## Possible Solution
Screwed up something in the config.
Run a command to fix it?

```
# Authentication settings
#auth-service:          # ptc (default) or google
#username:
#password:

# Database settings
db-type:mysql        
# sqlite (default) or mysql
db-host:127.0.0.1               
# required for mysql
db-name:pokemongomapdb               
# required for mysql
db-user:root              
# required for mysql
db-pass:               
# required for mysql

# Search settings
#location:
#no-gyms:               # disables gym scanning (default false)
#no-pokemon:            # disables pokemon scanning (default false)
#no-pokestops:          # disables pokestop scanning (default false)
#num-threads:           # number of search threads (default 1)
#scan-delay:            # default 5
#step-limit:            # default 12

# Misc
gmaps-key:AIzaSyB_AB63TRQEFF21CzDSZE1WhLsqKY0viVP0zWI8           
# your Google Maps API key
#webhook:               # webhook URL (including http://)

# Webserver settings
#host:                  # address to listen on (default 127.0.0.1)
#port:                  # port to listen on (default 5000)

#Uncomment a line when you want to change its default value (Remove # at the beginning)
#username, password, location and gmaps-key are required
```

## Your Environment

Python 2.7
Windows 10

**Comment by pyr0ball** [comment]
you're missing your db password

**Comment by pyr0ball** [comment]
Please try a fresh pull and refer to the wiki for installation instructions. Each new iteration has new requirements so be mindful of that. If you have issues with setup and configuration they should be directed to the help channel on discord.

https://github.com/AHAAAAAAA/PokemonGo-Map/wiki

https://discord.gg/HZqaX

**Comment by FrostTheFox** [comment]
Closed by moderator request.
