### ISSUE TITLE
mysql worse performance than sqlite 100% cpu use

### ISSUE THREAD

**Issue by Archalias** [AHAAAAAAA/PokemonGo-Map#2953]
When using mysql directly from the wiki tutorial my cpu use deadlocks my computer at 100%.
I can barely see my windows (I have 232 scanners atm) but it appears they are being flooded with a too many requests error. Due to how many scanners I use I have both gyms and pokestops completely disabled which makes sqlite perform just fine with no locked issues.

## Expected Behavior
Better performance than sqlite.

## Current Behavior
mysql uses 100% cpu when sqlite uses 20%-40%

## Possible Solution
possibly just throttle the requests as it seemed to be happening repeatedly at <100ms

## Steps to Reproduce (for bugs)
1. setup the latest build with mysql following the wiki tutorial
2. run a large amount of instances

## Context
I'm trying to get better performance because I'm attempting to make an accurate near live map of the places my friends and I go. With sqlite I have to turn gyms and pokestops off.

**Comment by Spurlex** [comment]
You can fix this by using MySQL "Points" which need to be added into this project.

https://dev.mysql.com/doc/refman/5.7/en/spatial-datatypes.html

These are designed for MySQL Geo lookups and are much faster. Would be great if someone good at Python implemented them.

**Comment by Archalias** [comment]
With the latest dev and #2956 this is no longer a problem.
When it first starts it goes crazy and kills my cpu but after a short time it's incredibly better.
