### ISSUE TITLE
Request: Option to set additional delays

### ISSUE THREAD

**Issue by DomGrieco** [AHAAAAAAA/PokemonGo-Map#2957]
## Current Behavior
With multiple accounts running in one searcher I find when you have a large number of accounts request get throttled.

There currently isn't any option to change the delay between each search_thread; instead, you can only change the delay between each scan thread loop.

Also, it would be nice to have the option to add a delay between each account log in.

## Possible Solution
For testing purposes I've added `time.sleep(random.uniform(0.2,1.5))`  in search.py below `log.info('Login to Pokemon Go successful.')`. I need more time to effecitvly test delays between account logins.

I don't have a possible solution yet for delays between each search_thread.

## Steps to Reproduce (for bugs)
1. Add 20+ accounts to one searcher
2. Wait
3. Monitor Account log failures and search thread failures.

## Context
Have more options to add delays in between all the requested information from the API will allow us to test our limits with the API. I think it would be ignorant of us only to assume the `--scan-delay` is the only contributing factor in how Niantic is or plans to throttle request in the coming future.

## Your Environment

* Version used: a83ce5c0e6bfa4a97df485498e27fe3a0181ef7a
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): Ubuntu 16.04.1 x64

**Comment by chuyskywalker** [comment]
Already exists:

```
    parser.add_argument('-sd', '--scan-delay',
                          help='Time delay between requests in scan threads',
                          type=float, default=5)
    parser.add_argument('-td', '--thread-delay',
                        help='Time delay between each scan thread loop',
                        type=float, default=5)
```

**Comment by DomGrieco** [comment]
This is wrong. Thread delay works just like scan delay except it only adds the delay between each finished scan.

**Comment by chuyskywalker** [comment]
There's only two places you can set delays and both already exist. There the primary loop which has `-td` delay at the end of it, and (once that loop starts over) you have a cluster of `search_threads` which all have an internal delay between requests of `-sd`. There's no other delay that could be set, as far as I know.

**Comment by DomGrieco** [comment]
This was requesting delays in general, not just a thread delay for each search_thread. This would be optional delays with defaults of 0 so it wouldn't change the current state.

I added my own delay after each search_thread and I have yet to see any errors with 25 accounts running on one scanner. Although, before the additional delays I would always get at least one `Search thread failed. Response dictionary key error` for one of the search threads. Testing with 1 thread per account and a scan delay of 5.2 seconds.

> There currently isn't any option to change the delay between each search_thread; instead, you can only change the delay between each scan thread loop.
>  
> Also, it would be nice to have the option to add a delay between each account log in.

**Comment by DomGrieco** [comment]
Maybe I'm just not making sense its 4:30 am for me. I'll do a PR tomorrow to show you what I'm talking about.

**Comment by chuyskywalker** [comment]
Go check out #2956 where i've made it a thread-per-user; the `-sd` delay over there would definitely apply to logins as well.

**Comment by DomGrieco** [comment]
@chuyskywalker Yea I took a quick look at it last night before I got off. It runs really well! I still think it would be nice to have an option to add a user set delay between each successful login.  I can PR it once #2956 get's merged.

**Comment by chuyskywalker** [comment]
I can see what you mean. Funny enough, people complained that prior to that branch logins would take TOO long since they seemed to run sequentially. Now they all happen at once and we need a delay :D 

It'll be a bit of pokey-jiggery to get a thread safe delay in place to block logins across threads with delays. Sure it's possible, but it'll be a bit cumbersome.
