### ISSUE TITLE
How do you Stop server

### ISSUE THREAD

**Issue by Cammo009** [AHAAAAAAA/PokemonGo-Map#2958]
How do i stop the runserver.py when running? I would like to make some changes to the config.ini

**Comment by BaIthamel** [comment]
ctrl+C is the usual method

**Comment by chuyskywalker** [comment]
^

**Comment by Cammo009** [comment]
Will try it that. I am using linux ubuntu with putty connection. Will that still work doing Ctrl+C

**Comment by Nodebuck** [comment]
Ctrl+C doesn't work for me if it ran for a longer amount of time.

**Comment by Cammo009** [comment]
It worked for putty. But how will i be able to stop it if i closed putty? Is there a command i can use? @BaIthamel

**Comment by THEdavidharris** [comment]
If you want to kill all Python processes running in the background:

`pkill -9 python`

To kill individual background processes, `ps` shows all processes from the current user and `ps aux` will show all process on the machine, you can find the PID and then do `kill 12345` if the PID is 12345

**Comment by Nodebuck** [comment]
I stop it using `fuser -k 5000/tcp` if Ctrl+C doesn't work. (The command
stops the process using port 5000).

**Comment by Nodebuck** [comment]
I stop it using `fuser -k 5000/tcp` if Ctrl+C doesn't work.

 (The command stops the process which uses port 5000).

**Comment by Cammo009** [comment]
Thanks that should help. At the moment i have to find how to keep the runserver going. As soon as Putty closes or becomes inactive it stops the runserver meaning i have to login and tun the start command again.

**Comment by Nodebuck** [comment]
You have to run it in a screen. Type `screen -S pokego` and then start the server. You can leave with Ctrl+A then D and go back into the screen using `screen -r pokego`. You can terminate the screen using `screen -X -S pokego quit`.
