### ISSUE TITLE
Contribruting to the same db

### ISSUE THREAD

**Issue by simoher** [AHAAAAAAA/PokemonGo-Map#2961]
How much would ti requier if we ran a db, fx. for each cuntry / state? 

The thing cursing the biggest load on servers must be the scanning. If we could spread that out on our users, by making them scan theier own locations. Then we may be running our own scanners on the biggest cities to asure fress data on them.

**Comment by FrostTheFox** [comment]
Issues are for bug code. You are free to discuss with members on our Discord.
