### ISSUE TITLE
Beehive Generator - How to view the output

### ISSUE THREAD

**Issue by maccaman8** [AHAAAAAAA/PokemonGo-Map#2962]
<Hi everyone,
I've been using the normal version of the map for a while now ("C:\Python27\python.exe" runserver.py -a -u -p -l "lat, long" -st -sd 5 -L en -k API and was great until the change which Niantic implemented.

I've been trying to use this Hex Beehive Generator, but am getting stuck on a few things.

I have been trying to follow the instructions but appear to be stuck at a few things:

I've created a .bat file, and the file is running 

saying C:\Desktop\PokemonGo-Map>ping 127.0.0.1 -n 6  1>nul

All the movables are now going, however I am unable to view the API on localhost:5000.

Any help would be greatly appreciated

**Comment by BaIthamel** [comment]
this is for code issues, for technical support go to the discord.

**Comment by FrostTheFox** [comment]
Closed by moderator request. Please use discord for technical support.
