### ISSUE TITLE
[Feature Request]: P2P / destribrution of DB data.

### ISSUE THREAD

**Issue by simoher** [AHAAAAAAA/PokemonGo-Map#2967]
## Expected Behavior

Pokemon data could(?) get distributed between a few DB's and or users, to make it possible for all the different Go-Map scanners to contribute to a common pokemon world map DB. 

For data do be valid, one pokemon should fx be inserted twice, in populated areas, but only once in remote areas. 

Android- and browser version could contribute to these DB's too.

Many different entry points could still be used, fx DK.SomePokemonMapApp.com, to spread load for different religions. (No idea if that is necessary) .

## Current Behavior
People are running their own small individual maps, covering small areas.  

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by invisiblek** [comment]
The problem with this is that we can't verify the integrity of the data. There'd be no way to prevent people from putting false data into such a database.

A good idea at heart, but not a direction this project is going to go. Feel free to set up your own mysql instance and have people point to it though!
