### ISSUE TITLE
Jelastic extra args

### ISSUE THREAD

**Issue by Silvikk** [AHAAAAAAA/PokemonGo-Map#2968]
Hey, guys!

Could you help me to find out how to add EXTRA_ARGS into Jelastic deployment?

Thanks!

**Comment by kalimerre** [comment]
Hey,

In your environement in "sych74/pokemongo-map" you got a wheel, click on it and choose "Run config"  and you got the "run command" where you can add EXTRA_ARGS parameters :)

**Comment by Silvikk** [comment]
Thank you! @kalimerre
