### ISSUE TITLE
Notification bug?

### ISSUE THREAD

**Issue by jorenmartijn** [AHAAAAAAA/PokemonGo-Map#2972]
## Expected Behavior
Normally you'd only get a notification when a new Pokemon appears.

## Current Behavior
I get these notifications constantly, if you close them a new notification immediately appears. 
Eevee is not visible on the map at all.
<img width="369" alt="screen shot 2016-08-01 at 10 59 43" src="https://cloud.githubusercontent.com/assets/2348805/17288831/3612f910-57d7-11e6-9b46-bfc7314e2380.png">

## Steps to Reproduce (for bugs)
I don't know how to reproduce it but I have Eevee in my notification list. It does happen regularly.

## Your Environment
* Latest version of the code (did a git pull this morning).
* Python 2.7 
* OSX El Capitain 10.11.5

**Comment by cbourgui** [comment]
I think it happens after lured pokemon disappearance

**Comment by Shuyinsama** [comment]
I just had the same issue also with Eevee. It kept pointing me to the same locations even though the Eevee is already despawned.

**Comment by MrChick** [comment]
I'm having the same issue, but with Jigglypuffs instead of Eevees

**Comment by invisiblek** [comment]
https://github.com/AHAAAAAAA/PokemonGo-Map/issues/2478
