### ISSUE TITLE
IOError: No such file or directory: '....\\static/dist/data\\pokemon.min.json'

### ISSUE THREAD

**Issue by ekbfh** [AHAAAAAAA/PokemonGo-Map#2979]
Exception in thread search_thread-0:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Python27\PokemonGo-Map-master\pogom\search.py", line 174, in search_thread
    parse_map(response_dict, i, step, step_location)
  File "C:\Python27\PokemonGo-Map-master\pogom\models.py", line 257, in parse_map
    p['longitude'], d_t)
  File "C:\Python27\PokemonGo-Map-master\pogom\customLog.py", line 17, in printPokemon
    pokemon_name = get_pokemon_name(id).lower()
  File "C:\Python27\PokemonGo-Map-master\pogom\utils.py", line 248, in get_pokemon_name
    return i8ln(get_pokemon_data(pokemon_id)['name'])
  File "C:\Python27\PokemonGo-Map-master\pogom\utils.py", line 243, in get_pokemon_data
    with open(file_path, 'r') as f:
IOError: [Errno 2] No such file or directory: 'C:\\Python27\\PokemonGo-Map-master\\static/dist/data\\pokemon.min.json'

Latest build. any ideas?

**Comment by michaelluk** [comment]
Have you `grunt build` before runserver.py?

**Comment by tarthim** [comment]
Grunt build has not run properly. Run npm install. Do NOT cancel it, it takes a long while. (Might want to nuke current install and start over)

**Comment by ekbfh** [comment]
Ok, what is the 'npm install'? i haven't this command in system. 
i run python runserver.py. Pip installed all the requirements.
Please, explain why i need this grunt. All was fine on previous builds without it.

**Comment by tarthim** [comment]
For the newest dev builds there's been a switch to grunt (part of node.js) to generate graphical assets. Install node.js to be able to use npm. Interesting that you're not getting the standard grunt install error though. Assuming Windows here.

See the wiki: https://github.com/AHAAAAAAA/PokemonGo-Map/wiki for other OS, or more help.

**Comment by ekbfh** [comment]
Oh, i see. Win10, yes.
In fact i'm wondering why it's doesn't say anything about it.
installed npm, all is great. 
But latest release is great too, i think i will use it.

Thank you all.

**Comment by jonathan-dejong** [comment]
Just want to throw this in here for anyone else. 

I had the same issue (been running develop branch all along). 
I fixed it by first running `npm install` (important that this is run from the right location, for me it's where I installed pokemongo-map). 
Then I ran `grunt build`. 
Done! This is probably obvious for most but I'll leave it here for others that might find this issue.  

On a sidenote it might also be worth rerunning `pip install -r requirements.txt` from time to time. I just switched to mariadb and had some issue which was related to missing mysql software. It was solved by doing this.

**Comment by tarthim** [comment]
@jonathan-dejong Running npm install automagiccally runs a grunt build at the end, so running it twice, while it does no harm, shouldn't be necessary. :-)

**Comment by jonathan-dejong** [comment]
@tarthim 

Yeah that happened in my case as well but one of the files ran into some trouble so I had to do a `grunt build --force` afterwards.

**Comment by tarthim** [comment]
@jonathan-dejong Definitely not bad practice to run it to make sure, either way. :-)
