### ISSUE TITLE
Launch error 

### ISSUE THREAD

**Issue by Iljalala** [AHAAAAAAA/PokemonGo-Map#298]
I'm launching from console like this:
`D:\PokemonGo-Map-master>C:\Python27\python.exe example.py -a PTC -u ***** -p ****** -l "Central Park, New York, NY" -st 5 -i Pidgey,Weedle,Zubat`

And I have this error:
```
[-] register_background_thread called
Traceback (most recent call last):
  File "example.py", line 907, in <module>
    register_background_thread(initial_registration=True)
  File "example.py", line 733, in register_background_thread
    if not werkzeug.serving.is_running_from_reloader():
AttributeError: 'module' object has no attribute 'is_running_from_reloader'
```

I have installed python2.7 and have used setup.bat from EasySetup folder, it has not showed any error.

**Comment by nborrmann** [comment]
install dependencies #RTFM
