### ISSUE TITLE
Error when running "pip install -r requirements.txt"

### ISSUE THREAD

**Issue by id4h0** [AHAAAAAAA/PokemonGo-Map#2982]
Hello,

I can't install the requirements.txt neither of the newest master nor of the dev branch. I am getting this report:

## Current Behavior
s5470@s5470:~/Downloads/DPokemonGo-Map-develop$ pip install -r requirements.txt
Requirement already satisfied (use --upgrade to upgrade): Flask==0.11.1 in /home/s5470/.local/lib/python2.7/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): Jinja2==2.8 in /home/s5470/.local/lib/python2.7/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe==0.23 in /home/s5470/.local/lib/python2.7/site-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): Werkzeug==0.11.10 in /home/s5470/.local/lib/python2.7/site-packages (from -r requirements.txt (line 4))
Collecting configargparse==0.10.0 (from -r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): click==6.6 in /home/s5470/.local/lib/python2.7/site-packages (from -r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): itsdangerous==0.24 in /home/s5470/.local/lib/python2.7/site-packages (from -r requirements.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): peewee==2.8.1 in /home/s5470/.local/lib/python2.7/site-packages (from -r requirements.txt (line 8))
Requirement already satisfied (use --upgrade to upgrade): wsgiref==0.1.2 in /usr/lib/python2.7 (from -r requirements.txt (line 9))
Requirement already satisfied (use --upgrade to upgrade): geopy==1.11.0 in /home/s5470/.local/lib/python2.7/site-packages (from -r requirements.txt (line 10))
Requirement already satisfied (use --upgrade to upgrade): protobuf==2.6.1 in /home/s5470/.local/lib/python2.7/site-packages (from -r requirements.txt (line 11))
Requirement already satisfied (use --upgrade to upgrade): requests==2.10.0 in /home/s5470/.local/lib/python2.7/site-packages (from -r requirements.txt (line 12))
Requirement already satisfied (use --upgrade to upgrade): s2sphere==0.2.4 in /home/s5470/.local/lib/python2.7/site-packages (from -r requirements.txt (line 13))
Requirement already satisfied (use --upgrade to upgrade): gpsoauth==0.3.0 in /home/s5470/.local/lib/python2.7/site-packages (from -r requirements.txt (line 14))
Requirement already satisfied (use --upgrade to upgrade): protobuf-to-dict==0.1.0 in /home/s5470/.local/lib/python2.7/site-packages (from -r requirements.txt (line 15))
Collecting PyMySQL==0.7.5 (from -r requirements.txt (line 16))
  Using cached PyMySQL-0.7.5-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): flask-cors==2.1.2 in /home/s5470/.local/lib/python2.7/site-packages (from -r requirements.txt (line 17))
Collecting flask-compress==1.3.0 (from -r requirements.txt (line 18))
Collecting LatLon==1.0.1 (from -r requirements.txt (line 19))
  Using cached LatLon-1.0.1-py2-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): setuptools in /home/s5470/.local/lib/python2.7/site-packages (from protobuf==2.6.1->-r requirements.txt (line 11))
Requirement already satisfied (use --upgrade to upgrade): future in /home/s5470/.local/lib/python2.7/site-packages (from s2sphere==0.2.4->-r requirements.txt (line 13))
Requirement already satisfied (use --upgrade to upgrade): pycryptodomex>=3.0 in /home/s5470/.local/lib/python2.7/site-packages (from gpsoauth==0.3.0->-r requirements.txt (line 14))
Requirement already satisfied (use --upgrade to upgrade): Six in /home/s5470/.local/lib/python2.7/site-packages (from flask-cors==2.1.2->-r requirements.txt (line 17))
Collecting pyproj (from LatLon==1.0.1->-r requirements.txt (line 19))
Installing collected packages: configargparse, PyMySQL, flask-compress, pyproj, LatLon
Exception:
Traceback (most recent call last):
  File "/home/s5470/.local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/s5470/.local/lib/python2.7/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/home/s5470/.local/lib/python2.7/site-packages/pip/req/req_set.py", line 742, in install
    **kwargs
  File "/home/s5470/.local/lib/python2.7/site-packages/pip/req/req_install.py", line 831, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/home/s5470/.local/lib/python2.7/site-packages/pip/req/req_install.py", line 1032, in move_wheel_files
    isolated=self.isolated,
  File "/home/s5470/.local/lib/python2.7/site-packages/pip/wheel.py", line 346, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/home/s5470/.local/lib/python2.7/site-packages/pip/wheel.py", line 324, in clobber
    shutil.copyfile(srcfile, destfile)
  File "/usr/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Keine Berechtigung: '/usr/local/lib/python2.7/dist-packages/configargparse.pyc'

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
Ubuntu 16.04.1 LTS 64-Bit

**Comment by freakjam** [comment]
https://github.com/AHAAAAAAA/PokemonGo-Map/issues/2838#issuecomment-236435066

**Comment by id4h0** [comment]
Thanks! And for me SHAME *** SHAME *** SHAME *** ...
