### ISSUE TITLE
[Feature Request] Add Google Maps Pointer Flag

### ISSUE THREAD

**Issue by licklake** [AHAAAAAAA/PokemonGo-Map#2984]
Using the map with multiple users can be a problem, because everyone can move the "map pointer" to another location and cause the scanner to change its search area. There should be a flag that can disable this "function".

## Current Behavior

Using the map with multiple users (that don't know eachother) isn't possible, because everyone will move the marker to its own location.

## Possible Solution

Add a flag that looks something like this:
#multiusermode:                            #(default: false) this disables the real time location mover

**Comment by SOLiNARY** [comment]
there is a flag. use -fl when running your server.  (fixed location)
