### ISSUE TITLE
Launch Error

### ISSUE THREAD

**Issue by lywrekz** [AHAAAAAAA/PokemonGo-Map#299]
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discordapp.com/invite/qbpVH6b).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System: Win10 64

Installed version of Python: 2.7

### Steps to reproduce
1. Running the following: python example.py -u *** -p *** -l *** -st 5
2.
3.

### What have you tried?
1. If I comment out line 26 it runs fine

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

Traceback (most recent call last):
  File "example.py", line 26, in <module>
    from gpsoauth import perform_master_login, perform_oauth
ImportError: No module named gpsoauth

**Comment by Johanneshn** [comment]
You are missing gpsoauth, run:
`pip install -r requirements.txt`

**Comment by lywrekz** [comment]
Thanks!
