### ISSUE TITLE
Docker repository on https://hub.docker.com

### ISSUE THREAD

**Issue by mattekure** [AHAAAAAAA/PokemonGo-Map#2994]
Is there an official docker repository for this on https://hub.docker.com?  There are a number of repositories there that seem to pull from this project, but its impossible to say how they are updated or if they will just stop supporting.

**Comment by Ashex** [comment]
There are instructions in the wiki on how to build a docker image but there isn't an official repository up there. 

The majority of them look to be forks of the project pulling in changes and are hooked into docker hub for continuous builds. I think I'm the only person who is maintaining an actual repository with tested images.

**Comment by chuyskywalker** [comment]
No official one right now; I rebuild nightly though: https://hub.docker.com/r/chuyskywalker/pokemongo-map/
