### ISSUE TITLE
Pokemon only spawning North/Northeast of location

### ISSUE THREAD

**Issue by haagiboy88** [AHAAAAAAA/PokemonGo-Map#30]
### Environment info
Operating System: Windows 10 64-bit

Installed version of Python: 2.7.12

### Steps to reproduce
1. Run the program as you normally would

### What have you tried?
1. Waiting and refreshing.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by AHAAAAAAA** [comment]
Fixed!
