### ISSUE TITLE
Parallel requests

### ISSUE THREAD

**Issue by JanWerder** [AHAAAAAAA/PokemonGo-Map#300]
It would be great if you could send multiple request to the niantic servers at once. With that kind of batching it would drastically faster to cover the map.

**Comment by swablueme** [comment]
And get you banned.

**Comment by JanWerder** [comment]
Well, that depends. I don't think there is an automatic banning system in place right now and if there was you would get banned anyway for "gps spoofing"

**Comment by Temetz** [comment]
Niantic will most likely implement a Ingress style anti spoofing system really soon as one of the top priority things. The system already exist in Ingress, so most likely it will be a very fast process to turn it on for Pokemon also.

They usually gather some baseline data before turning the system on and then swinging the ban hammer producing a massive ban wave.

Changing your location location too often, too fast will be easy to detect. Its also something to keep in mind when doing the scans. Toggling between your work and home areas, will cause you a lot of trouble really fast.

**Comment by JanWerder** [comment]
"most likely" & "usually" are interesting word choices. Several things:
1. All of the points being made by you and me are essentially assumptions
2. I can follow your example in the last paragraph, but scanning an area is very similar to driving while having the app open. I don't think that this would result in a ban. Covering huge distances in mere seconds is something a ban system will most likely punish.
3. I don't see your point why a parallel requests will incease the likelyhood of you getting banned. (Are you even making that point?)

**Comment by Temetz** [comment]
Mostly just random thoughts and things learned from Ingress.

By monitoring the network traffic between my phone and the pokemon player frontend it seems that there is a request made to `/plfe/:id/rpc` only every 30 seconds. Im only concerned as it seems that this would generate more traffic than the real phone application is generating.

I could be wrong also. :)

**Comment by KingsDevelopment** [comment]
If the banning system is going to be used, isn't this app going to be wortheless anyways?
Because I can scan my hometown in 10 minutes now, I will never reach that with a car.

**Comment by swablueme** [comment]
I think most people are using this as a replacement for the three step radar.
And I hope everyone is using this with a burner account.

**Comment by Temetz** [comment]
@KingsDevelopment Making only 1 request every 30 seconds to simulate the pokemon app behaviour should be still fine. It still displays you more than visible on your phone.

@swablueme I would call it natural selection in case someone isnt using a burner account.

**Comment by sdwvit** [comment]
What if add multiple accounts? That should grant almost linear increase in scanning speed
