### ISSUE TITLE
ImportError, no flask_cors

### ISSUE THREAD

**Issue by Hatrix5555** [AHAAAAAAA/PokemonGo-Map#3004]
Hi. When I try to run server, I have an error:

> $ python runserver.py -a ptc -u Dupa5555 -p dupa1234 -l "4A Macquarie St, Sydney NSW 2000, Australia" -st 5 -ar 10
Traceback (most recent call last):
  File "runserver.py", line 10, in <module>
    from flask_cors import CORS
ImportError: No module named flask_cors

What should I do?

**Comment by CtrlAltDefeat94** [comment]
pip install -r requirements
and change your password probably

**Comment by Hatrix5555** [comment]
Ok, I had outdated pip, thx
