### ISSUE TITLE
NPM Error and Grunt Build

### ISSUE THREAD

**Issue by FrenzyDemon** [AHAAAAAAA/PokemonGo-Map#3008]
## Expected Behavior

Trying to use "npm install"
## Current Behavior

> pogomap@0.1.0 postinstall C:\Users\Tarek\Downloads\PokemonGo-Map-develop
> grunt build

'grunt' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE
npm ERR! pogomap@0.1.0 postinstall: `grunt build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pogomap@0.1.0 postinstall script 'grunt build'.
npm ERR! This is most likely a problem with the pogomap package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     grunt build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pogomap
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls pogomap
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Tarek\Downloads\PokemonGo-Map-develop\npm-debug.log

## Your Environment

* Version used: Dev
* Environment name and version (e.g. Python 2.7): 2.7.12
* Operating System and version (desktop or mobile): Windows 10 Desktop

**Comment by BaIthamel** [comment]
This isn't really an "issue" although i sympathise. if you want help you might be able to get it on the discord.

**Comment by FrenzyDemon** [comment]
I don't understand what the error is even saying. Can you please explain?

Why is this so hard to freaking install now? 3 days ago I did this stuff in like 15 mins, and now there are SOOO many extra steps involved and the instructions have not been updated to reflect this. I'm having a very rough time and it's very frustrating.

**Comment by FrenzyDemon** [comment]
I don't even know wtf I'm doing with this Npm install, nodejs, and grunt stuff man. Last time all I had to do was copy paste some freaking coordinates into a Spreadsheet and then run beehive.bat

**Comment by BaIthamel** [comment]
Even half the devs making the code don't know how to set up grunt. I hate it.

**Comment by FrenzyDemon** [comment]
I was able to use the Location Generator to create a beehive.bat file but this is what happens when I try to run it.
![untitled](https://cloud.githubusercontent.com/assets/20687581/17298426/06fa42e0-57d8-11e6-87e3-687dc9e75842.png)
Is this related to my issue or is this something I can fix easily?

**Comment by BaIthamel** [comment]
you really really want to join a help chat, this is not for user support it's for clear bugs.

**Comment by FrenzyDemon** [comment]
I see many people posting here for user support.

**Comment by BaIthamel** [comment]
They shouldn't be. And when people with mod powers can be bothered the close them with directions to ask for help in the help chats.

**Comment by FrenzyDemon** [comment]
Jesus man, I'm just a guy trying to get some help. Why you gotta come in here and do this on my thread? Now you've discouraged anyone who might have thought of helping me.

Thanks for offering absolutely 0 assistance

**Comment by BaIthamel** [comment]
Then follow my first piece of help! Go get help in a dedicated help location!

**Comment by FrenzyDemon** [comment]
Why do you have to come in here and tell me to find help somewhere else? I've been helped here before, and so have many other people.

Please, if you do not want to help just leave people alone. Your comments are not productive in anyway

**Comment by shutz-c0de** [comment]
Alright, I had the same problem, here is what you need to do : 
   npm install grunt --save-dev
   npm install jshint-stylish
   npm install grunt-contrib-uglify
   npm install grunt-contrib-jshint 
   npm install grunt-contrib-watch
   npm install grunt-sass
   npm install grunt-contrib-copy
   npm install grunt-contrib-clean
   npm install grunt-contrib-cssmin
   npm install grunt-usemin
   npm install grunt-contrib-concat
   npm install grunt-html-validation
   npm install grunt-babel
   npm install grunt-minjson

Then you should do : 
   grunt build

If the grunt build stop with a warning, just do : 
   grunt build --force

You'll pass on that warning, should still work.
Tell me if this work out for you.

**Comment by FrenzyDemon** [comment]
When trying to run "npm install grunt --save-dev", I receive this error:
![untitled](https://cloud.githubusercontent.com/assets/20687581/17299226/6e5bb8c6-57db-11e6-930d-dcf5deb2a7b5.png)
What is Minimatch3.0.2?

**Comment by shutz-c0de** [comment]
It's not an error, it's a Warning, and this warning tell you that the minimatch package is deprecated (not maintained anymore) and it also tell you that you may be vulnerable to RegExp Dos attack (because of this deprecated package).
If you don't plan on making your website widely available, you don't really care.
If you do, you can try to upgrade to a superior version of minimatch.

**Comment by FrenzyDemon** [comment]
Oh wow, thank you for not making me feel stupid about that. So that worked properly? I just need to enter the rest of the commands now?

**Comment by shutz-c0de** [comment]
Yes, everything is good, you can go ahead.
Basically, if you receive a Warning, or a Notice, it will not impact the execution of the code.
It's only the error that are critical :) !

**Comment by FrenzyDemon** [comment]
Thank you so much! I completed the instructions and I got this: 
![untitled](https://cloud.githubusercontent.com/assets/20687581/17299753/9ce148d0-57dd-11e6-965c-f65c3423f1b3.png)

So what do I do now that npm and grunt are done? I really don't know what I needed them for in the first place, I was just following directions. My beehive.bat file is still giving the same error message I posted above "Python not found".

**Comment by shutz-c0de** [comment]
So now you are done with the grunt file, everything is ok.
Your next problem seem's to be your python environment path.

Do you know where your python is installed ?

When you type `python` in your windows console, does it open the python terminal ?

**Comment by FrenzyDemon** [comment]
Yes, my Python is located in the default folder. So how can it not find it?

**Comment by itztq** [comment]
Hi im following this issue and im finally have running the server. but if i enter the web the page turns white with only the filter

**Comment by shutz-c0de** [comment]
@FrenzyDemon 
Then you need to define the environment path for python, follow this guideline to do so :
http://superuser.com/a/143121

@itztq
It seem's like you wrongly pulled the auto thread fork, you need to first clone the develop branch of PokemonGo-Map, then do execute the auto thread command 

(I'm on my phone atm, will get this comment clearer on a computer soon)

**Comment by FrenzyDemon** [comment]
Shutz-Code, thank you so much for bringing me this far. I tried to correct the Path Variable via your instructions, but it still is not working. I created a new Issue for this topic, since it is different from my original problem.

**Comment by itztq** [comment]
@shutz-c0de  i downloaded the dev branch map and run the server thats good right?

and the auto run command can if configure it in the config.ini or diffrent? and how?

**Comment by itztq** [comment]
@shutz-c0de  fixed it ! 

Grunt build must not contain any errors/warnings in my case i had to run:

npm install babel-preset-es2015 --save
npm install babel-preset-react --save

**Comment by shutz-c0de** [comment]
@itztq : Thank's mate! I didn't knew about those :) !

**Comment by Buddhaman42** [comment]
Thank you for the help already posted! Can anyone help me out further? After inputting all the commands by @shutz-c0de, I get the following failure:

![image](https://cloud.githubusercontent.com/assets/20763688/17338644/30db2d2a-58b6-11e6-8500-8ccf47d53b4a.png)

Says it cannot find module 'lru-cache'. Am I missing something from my files?

**Comment by anavkx** [comment]
Created an account just to thank @shutz-c0de for the grunt/babel info. Had the same initial problem as @FrenzyDemon, was driving me nuts, now working perfectly. Thank you!

**Comment by Buddhaman42** [comment]
Nevermind.....not even sure how I fixed it, but I fixed it. Haha, thanks again for the solid info!

**Comment by shutz-c0de** [comment]
@anavkx 
You are welcome my friend ! It's a pleasure to help !

@Buddhaman42
Haha, glad sorted this out by yourself :+1: !
