### ISSUE TITLE
[Request] Automatic account creation

### ISSUE THREAD

**Issue by Frildoren** [AHAAAAAAA/PokemonGo-Map#3012]
I was wondering if there is any way of creating accounts automatically? I can't find anything (much to my surprise) to achieve this online, like a simple script, even though the Pokemon Trainer Club registration has no captcha.

Specially now that the requests are throttled and using several workers with different accounts is almost mandatory to get a decent speed I think this is very needed.

**Comment by BaIthamel** [comment]
Not an issue.

**Comment by freakjam** [comment]
Google PTC account creator.

**Comment by licklake** [comment]
works for me:

http://www.ownedcore.com/forums/pokemon-go/pokemon-go-hacks-cheats/566151-ptc-account-creator.html

**Comment by Frildoren** [comment]
Okay thank you everyone!
