### ISSUE TITLE
UPDATE TO MINIMATCH 3.0.2

### ISSUE THREAD

**Issue by Akshat1295** [AHAAAAAAA/PokemonGo-Map#3017]
Am I supposed to ignore the warnings during npm installation...

**Comment by hack3rjack** [comment]
Wondered the same thing, works fine but didn't know if update was beneficial.

**Comment by pankk** [comment]
As long as you are not publishing/sharing your map you should be fine. There are some vulnerabilities (regex attack) in the deprecated version.

**Comment by andrewda** [comment]
#3074
