### ISSUE TITLE
--num-threads 5 unrecognized after new clone

### ISSUE THREAD

**Issue by scarecr0w12** [AHAAAAAAA/PokemonGo-Map#3020]
## Expected Behavior
At run, should initialize search and run

## Current Behavior
Gives error of:
runserver.py: error: unrecognized arguments: --num-threads 5

## Steps to Reproduce (for bugs)
1. Running initial search using command line values(Not config-ini file)
2.
3.
4.

## Your Environment
Window sServer 2012 R2 standard
Python27
New Clone of Git develop repository as of 8/1/16 9:32am GMT-7
(Brand new install just for this)

**Comment by Jagerblue** [comment]
I believe the new dev just threads based on how many accounts you give it, instead of letting you specify.(As it's only able to support 1 per person anyways due to niantics throttling)

**Comment by scarecr0w12** [comment]
Is there a way around it? I'm not adding any thread value in the CLI line i put in:

python runserver.py -a ptc -u ****** -p ******* -l "33.456232, -112.075322" -st 200 -sd 1 -ld 2 -dc -H 192.99.***.*** -P 5000 -k ******** --db-type=mysql --db-host=***.***.***.*** --db-name=*** --db-user=*** --db-pass=***

**Comment by freakjam** [comment]
Adjust the config.ini (put # in front of num threads setting)

**Comment by scarecr0w12** [comment]
heh, yeah just realized that i had that in the config.ini file. This can close
