### ISSUE TITLE
Create a easy set up pls 

### ISSUE THREAD

**Issue by magicnld** [AHAAAAAAA/PokemonGo-Map#3032]
Create a easy set up pls 

looks as 
press pokemongo.exe 
account name and password 
location and api key 
press search and go.

**Comment by skeldoor** [comment]
Fantastic

**Comment by JackDoan** [comment]
Perhaps [PokemonGo-DesktopMap](https://github.com/mchristopher/PokemonGo-DesktopMap) would help you

**Comment by 0x8** [comment]
pokemon go desktop would help. I have a script that works on *nix systems (linux, OS X) but it won't be a whole lot of help on windows
