### ISSUE TITLE
No Pokemon show up on Windows 8.1 Pro

### ISSUE THREAD

**Issue by rriixx** [AHAAAAAAA/PokemonGo-Map#3034]
No Pokemon are showing up on the map, only Pokestops and Gyms.

## Expected Behavior
I'm running Pokemap on my Mac with Mac OS X El Captian and everthing is working fine. Now i wanted to run it on Windows 8.1 Pro, but no pokemon are shown on the map, only Pokestops and Gyms.
The console says "Upserted 3 Pokemon", so i think everything is working correct, but stil no Pokemon are shown at the map.

## Your Environment
* Version used: v2.1.0
* Python 2.7
* Windows 8.1 Pro

**Comment by lmjustic** [comment]
How many threads are you using? Niantic has begun limiting request rates to 3 requests per second.  So, if you are using more than 2 threads with a 1 second delay, you many of your requests will be rejected by Niantic servers and not actually find Pokémon.  The map will still appear like it's updating fine, but there will be numerous empty locations.

**Comment by MRokas** [comment]
did you check the menu?

**Comment by MRokas** [comment]
@lmjustic  _"Upserted 3 Pokemon"_ suggests his scanner find pokemons

**Comment by rriixx** [comment]
@MRokas yes Pokemon is checked in the menu

here is my command:
python runserver.py -u XXX-p XXX -st 20 -k XXX -l "Berlin" -td 1 -sd 1

Still showing no pokemon, but "Upserted X pokemon" counts some.

any tips?

**Comment by pokegothrow** [comment]
Check your computer's clock! I had the same problem, because of a time-zone issue when I dual boot Windows.

If your time is wrong, the pokemons will be considered "outdated" and will simply not be drawn by the javascript code in the browser.

Hope that helps!

**Comment by MRokas** [comment]
Open up Developer Console, re-load page, and copy paste whole text from there

**Comment by rriixx** [comment]
@pokegothrow you are my hero, that did the trick!!

the computer's clock was 2 hours ahead.

thanks guy's for helping!

Happy pokemon farming
