### ISSUE TITLE
Issue with Version 1.1.0

### ISSUE THREAD

**Issue by sheikhsabayyal** [AHAAAAAAA/PokemonGo-Map#3035]
2nd version works perfectly, but I get this error whenever I try the 1.1.0.. any solution? 

Traceback (most recent call last):
  File "runserver.py", line 13, in <module>
    from pogom.app import Pogom
  File "/Users/xxxxx/Desktop/PokemonGo-Map-master/pogom/app.py", line 9, in <module>
    from flask_compress import Compress
ImportError: No module named flask_compress

**Comment by MRokas** [comment]
`pip install -r requirements.txt`

**Comment by sheikhsabayyal** [comment]
Thanks! Didn't know the requirements.txt of 1.1.0 is different from previous version
