### ISSUE TITLE
Pokemon don't appear on map

### ISSUE THREAD

**Issue by AppleTechy** [AHAAAAAAA/PokemonGo-Map#3052]
I just ran the Heroku deployment button with no problems. When I open the app the map loads just fine but no Pokemon, Pokestops, or Gyms can be seen. I tried with different Pokemon go account and still saw no Pokemon. What did I do wrong? Any help would be much appreciated!

**Comment by Paralysing** [comment]
Niantic banned a few host ips, including heroku, check #2774

**Comment by AppleTechy** [comment]
@Paralysing Thanks for info. I am sad to hear that considering I couldn't get it to run locally on my Mac or on my RPI 2. If I do manage to get it to run locally is there a way to force it to only update the locations every 5 seconds?

**Comment by Paralysing** [comment]
-t 1 -sd 5 works fine for me, it limits to 1 scan every 5 seconds.

**Comment by AppleTechy** [comment]
@Paralysing I keep on getting this error `The directory '/Users/appletechy/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/Appletechy/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.` It continues installing but it ends the process with this message "Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'"

**Comment by Paralysing** [comment]
I don't have a mac, normally run with linux, but the [wiki](https://jonaharagon.github.io/PoGoMapWiki/#!Macintosh-Installation-and-requirements.md) might be able to help.
