### ISSUE TITLE
How do I set up?

### ISSUE THREAD

**Issue by Alexander3500** [AHAAAAAAA/PokemonGo-Map#3053]
How do I set up the pokemon go map? Im watching the video but like after 6 minutes in the video, it get lost because hes explaining the older version? I dont know how to set up after I download the zip :\

**Comment by DoraKlikOpDora** [comment]
Extract the zip.

Open the directory you've installed PokemonGo-Map-master in, and open also this directory.
Run `pip install -r requirements`
Run `python runservery.py` and add the flags, which can be found after running this command, you wish to use. You can also change the config.ini in the /config directory.

**Comment by Alexander3500** [comment]
Wheres pip install -r requirements located ? sryy

**Comment by DoraKlikOpDora** [comment]
pip install -r requirements is a command.

For windows: Open cmd and run that command in the right directory (PokemonGo-Map-master) and it should install.

For linux the same, open the directory and run the command

**Comment by VelocityRa** [comment]
@DoraKlikOpDora I doubt he's running Linux

**Comment by chuyskywalker** [comment]
There are several wikis on the subject here, please refer to those.
