### ISSUE TITLE
^ SyntaxError: Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by AppleTechy** [AHAAAAAAA/PokemonGo-Map#3059]
I received this error when trying to run "Curl https:bootstrap...." The final output before it ends is `ollecting wsgiref==0.1.2 (from -r requirements.txt (line 9))
  Using cached wsgiref-0.1.2.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-z5ooh6c7/wsgiref/setup.py", line 5, in <module>
        import ez_setup
      File "/private/tmp/pip-build-z5ooh6c7/wsgiref/ez_setup/__init__.py", line 170
        print "Setuptools version",version,"or greater has been installed."
                                 ^
    SyntaxError: Missing parentheses in call to 'print'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-z5ooh6c7/wsgiref/`
Any help would be much  appreciated.
## Your Environment
* Version used: newest
* Environment name and version (e.g. Python 2.7):Python 3.4 and 3.5. Home-brew 
* Operating System and version (desktop or mobile):Desktop,OS X 10.11.5

**Comment by MRokas** [comment]
Use python2.7

**Comment by AppleTechy** [comment]
@MRokas Is there way to get around that? I have installed python 2.7.11 but still am receiving the error. Is there an easy way to force it to run in Python2 as I need Python 3.4 /5 for another project I am working on.

**Comment by MRokas** [comment]
python2.7 command should work

**Comment by Ashex** [comment]
Use virtualenv

**Comment by AppleTechy** [comment]
@ashx Thanks for that. I went ahead and installed it but I don't really understand how to use it. Is there a good write up somewhere for me to read?

**Comment by chuyskywalker** [comment]
As this isn't an issue with PokemonGo-Map itself, I'm going to close it.
