### ISSUE TITLE
Question: How can I prevent the script from deleting expired pokemon?

### ISSUE THREAD

**Issue by KevakaBuel** [AHAAAAAAA/PokemonGo-Map#306]
Another version of this code i got about 15 hours ago did not delete expired pokemon. At first it was a bit of annoying, but after a while i say the potential of using this to create heat maps, which are pretty interesting. Is there are way where i can easily disable the deleting of expired pokemon?

**Comment by denniskai1234** [comment]
Someone requested to save all pokemons into a database exactly for this reason, not sure where it went. Its a good idea, im watching the spawns in my city and they are mostly the same so you can generate a offline version too where which pokemon should spawn due the history.

**Comment by Johanneshn** [comment]
Change line 789 and 583 in example.py to `#clear_stale_pokemons()`

**Comment by KevakaBuel** [comment]
Thank you very much =)
