### ISSUE TITLE
Cmd Window closes after beehive.bat

### ISSUE THREAD

**Issue by FrenzyDemon** [AHAAAAAAA/PokemonGo-Map#3063]
## Expected Behavior

Use beehive.bat to start my PokeMap.
## Current Behavior

Everytime "Moveable" comes up on the screen, it opens a secondary window and then immediately closes out of it. After going through all "Moveables", the original command window closes as well.
![untitled](https://cloud.githubusercontent.com/assets/20687581/17310321/a01fe2ca-5811-11e6-869d-418daed753f8.png)

## Steps to Reproduce
This is the command I typed into the Location Generator to create "beehive.bat":

python location_generator.py -lat 35.921919 -lon -84.0467687 -st 3 -lp 3 --windows --installdir="C:\Users\Tarek\Downloads\PokemonGo-Map-develop\PokemonGo-Map-develop"

## Your Environment

* Version used: Developer
* Environment name and version (e.g. Python 2.7): 2.7.1
* Operating System and version (desktop or mobile): Windows 10 Desktop

**Comment by kinderoth** [comment]
I'm having the same issue, I'm not sure what the cause is though. I'm on windows 7 desktop.

**Comment by FrenzyDemon** [comment]
I don't know if this will solve your issue, but for some reason I had to re run the 'Easy Setup' in the Tools Folder, and entered my Gmaps key at the end. I did this several times, but it finally started working the last time.
