### ISSUE TITLE
ImportError: No module named flask_cors

### ISSUE THREAD

**Issue by maddock34** [AHAAAAAAA/PokemonGo-Map#3064]
After running the easy setup setup.bat (after installing python 2.7) and entering all the -u -p  etc. it says this 
"Traceback (most recent call last): 
           File "runserver.py", line 14, in (module) 
                from flask_cors import CORS
ImportError: No module named flask_cors"

No idea what any of it means

**Comment by delvier** [comment]
Did you follow the install guide and use "pip install -r requirments" it seems like you update your git repository without recalling the 'pip'

**Comment by miaojs** [comment]
Did you try searching? #3004, #2939, #2789, #2666, #2111, #1578

**Comment by maddock34** [comment]
Did pip install and this is what I get 
![a](https://cloud.githubusercontent.com/assets/20781807/17312904/b4db6594-584e-11e6-9787-55842365dd66.PNG)

**Comment by miaojs** [comment]
#2951

**Comment by maddock34** [comment]
Alright, it seems all good. Another request, can I create a .bat to run that will launch it without having to type all the commands in again?

**Comment by miaojs** [comment]
Yes. Or use the config file without command args

**Comment by maddock34** [comment]
Let me be more specific, would you mind instructing me on creating a .bat to run it please. Use the config file without the commands?

**Comment by miaojs** [comment]
Have you gotten the server running yet? Just copy and paste the command into a text file and rename it to end in .bat. make sure you have show file extensions on in Windows. 

The config file can contain the various command arguments so you can just run runserver.py and it'll use the config file for  what you wouldve put in the command arguments.

**Comment by maddock34** [comment]
Just to check this is okay the .bat will contain this "python runserver.py -u user -p pass -st 10 -k APIKey -l "Location" -H 0.0.0.0" and I'll save that into the Pokemon Go map directory and it'll launch fine?

**Comment by maddock34** [comment]
Alright, it's all working. Thanks for the help
