### ISSUE TITLE
Localhost Something went wrong

### ISSUE THREAD

**Issue by Scarletterr** [AHAAAAAAA/PokemonGo-Map#3069]
I've put in my Google Api key, in both my code and my config but localhost/google maps still won't load. Everything is running on the command prompt, but I'm unable to see the map.

**Comment by Shadowgar** [comment]
Add -H 0.0.0.0 in the command line or I comment the host section in your config

**Comment by Scarletterr** [comment]
That didn't work either, host section:
#host:                  # address to listen on (default 127.0.0.1)

**Comment by Deathscythe193** [comment]
Make sure that you have JavaScript api and Google place web services api enabled on your google api key. Also, use Chrome web browser to view the map (I had to do this to make it work).

**Comment by Scarletterr** [comment]
I've got it enabled and am using chrome lol this is why i got frustrated. I was pretty sure I'd done everything right.

**Comment by hagehg** [comment]
@Scarletterr if it says something like "Check your Javascript console for infos" then it may be that you need to add your server's IP as a referrer for your API key at the site where you created the key

**Comment by Scarletterr** [comment]
I entered the IP address into Google API console where I created my API key. I waited 5 minutes (the website said it could take that long to register) and I'm still getting the same message.

**Comment by Scarletterr** [comment]
Turns out I put an O where I needed a 0 in my API code. --Problem solved
