### ISSUE TITLE
register_background_thread: not runing inside Flask

### ISSUE THREAD

**Issue by ph1l74** [AHAAAAAAA/PokemonGo-Map#307]
### Environment info
Operating System:
Win7
Installed version of Python:
Py2.7

### Steps to reproduce
1. Python 2.7, pip was installed.
2. -a, -u, -p, -l and -st atrributes was set up.
3. retrying_set_location_: geocoder exception «urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590»), retrying...

### What have you tried?
1. Disable all atrributes.
2. Reinstall pip and all requiries.
3. Changin' username/pass

### Logs or other output that would be helpful
![image](https://cloud.githubusercontent.com/assets/10608735/16945842/41ea88fa-4dc0-11e6-84d0-2ed9b9bb6aba.png)
and:
![image](https://cloud.githubusercontent.com/assets/10608735/16945878/69e968c6-4dc0-11e6-8af7-cf3274b63fdc.png)

**Comment by princeomlet** [comment]
I have the same problem, it seems to me

https://github.com/AHAAAAAAA/PokemonGo-Map/issues/305

**Comment by DerScreever** [comment]
i just tested with the latest version. all work great.

**Comment by ph1l74** [comment]
Still not working after downloading [this ver.](https://github.com/AHAAAAAAA/PokemonGo-Map/commit/d0a98a9a57ae8c2f1e6edac6a114ff00e73b6666)

**Comment by AIphatierchen** [comment]
I have the same Problem, but i solved it. If you typ in: "python example.py -a authService -u myUsername -p myPassword -l "Boulder, CO" -st 5"

delet the "-a authService"  Only use:
"python example.py  -u myUsername -p myPassword -l "Boulder, CO" -st 5"

**Comment by DerScreever** [comment]
Im sorry, but we dropped the support for the master branch (example.py). 
This branch is deprecated.  
The new branch contains a much cleaner structure so pls report only issues related to the develop branch. 

Your development team
