### ISSUE TITLE
Request feature: Can't hide "Search" switch (on frontend)

### ISSUE THREAD

**Issue by Becold** [AHAAAAAAA/PokemonGo-Map#3075]
## Expected Behavior
Having an argument/flag to disable this switch : http://puu.sh/qmvRn/1fa98fe1a1.png

## Possible Solution
Add an argument/flag (like -fl does for the Location changer).

## Context
I want to setup my own semi-public "pokevision". But I dont want my friends to pause the search-threads.
This feature should hide this switch.

## Your Environment
* Version used: develop

**Comment by jfla15** [comment]
I'm pretty sure I saw a PR adding flags to disable any switch.
For now you can instead delete the following HTML:
`        <div class="form-control switch-container" style="display:{{search_control}}">
          <h3>Scan</h3>
          <div class="onoffswitch">
            <input id="search-switch" type="checkbox" name="search-switch" class="onoffswitch-checkbox" checked/>
            <label class="onoffswitch-label" for="search-switch">
              <span class="switch-label" data-on="On" data-off="Off"></span>
              <span class="switch-handle"></span>
            </label>
          </div>
        </div>`
from templates/map.html to at least get rid of the switch.

**Comment by willgunty-okta** [comment]
You can also run a -os and -ns instance.  The -os instance is just the front end.  No control over search.  -ns is no frontend, and only does scanning.

**Comment by Becold** [comment]
Thanks jfla15 . I confirm : The flag is **-nsc**.
But someone should add it to [the wiki](https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Command-Line-Arguments).

**Comment by 1111121RicardoBrandao** [comment]
You have it on the wiki, here is the copy-paste from there: 

> -nsc, --no-search-control
>                         Disables search control
>   -fl, --fixed-location
>                         Hides the search bar for use in shared maps.
