### ISSUE TITLE
Database Issue

### ISSUE THREAD

**Issue by rlyons20** [AHAAAAAAA/PokemonGo-Map#3082]
I just updated to the latest code, and now I'm getting DB errors on start up, like:

File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3404, in connect
    self.initialize_connection(self.__local.conn)

I realize that I'm probably supposed to get rid of the old database, but I don't know how to do that. 

Please help.

**Comment by jfla15** [comment]
Getting rid of an old database shouldn't be necessary, but you can go ahead and delete the database file called 'pogom.db' that's located in the folder with your runserver.py and see if it helps.

**Comment by rlyons20** [comment]
it was a permissions issue on the folder.  

i got it.
