### ISSUE TITLE
How many Accounts do you use?

### ISSUE THREAD

**Issue by FrenzyDemon** [AHAAAAAAA/PokemonGo-Map#3083]
Can someone please explain to me how many accounts I need in order to run the Beehive.bat at maximum efficiency?

If my .bat opens up 20 different Command Windows, does that mean I need 20 different accounts? Would it increase speed if I made 40/60/80? Can I lower the Scan Delay below 5 if I get more accounts, or will it skip Pokemon?
## Your Environment

* Version used: Developer
* Environment name and version (e.g. Python 2.7): Python 2.7.12
* Operating System and version (desktop or mobile): Windows 10 Desktop

**Comment by NoMotion** [comment]
If you are using the latest version you do no longer have to create more than one instance. You can configure one instance to use multiple accounts for scanning, which will increase effectiveness.

The number of accounts is a matter of preference. I use 10 accounts to scan 25 step and it's more than sufficient.

**Comment by FrenzyDemon** [comment]
Thank you very much man!

**Comment by FrenzyDemon** [comment]
One last question, can you please tell me about the suggest Scan Delay? Does it have anything to do with the number of accounts? I remember hearing something about a 5 second rule.

**Comment by NoMotion** [comment]
Uh I don't know for sure. I set mine to 2 and its fast enough. You can definitely drop below 5 if you are using more than one account. Just play with it till you notice its going quick and not getting dictionary key errors
