### ISSUE TITLE
Any place to determine our non-overlapping agent starting locations?

### ISSUE THREAD

**Issue by MonsterMMORPG** [AHAAAAAAA/PokemonGo-Map#3085]
So i can set each agent without overlapping locations

I mean lets say i want to cover 20 km radius so how should distribute multiple agents at different locations

**Comment by Harachteh** [comment]
Check the Hex-Beehive-Generator in the Tools Folder.
https://jonaharagon.github.io/PoGoMapWiki/#!beehive.md

**Comment by MonsterMMORPG** [comment]
@Harachteh too much work. i hope they implement multi agent crawling feature asap
