### ISSUE TITLE
Noob here, what is Beehive? How do you set it up?

### ISSUE THREAD

**Issue by Enterodactyl** [AHAAAAAAA/PokemonGo-Map#3087]
From my understanding, it's a way to run multiple accounts at once?

Currently I am running like 15 accounts but I have to manually enter them into terminal one by one with the -ns function. Which is annoying because I have to stagger running them so that the scans overlap.

 Is beehive a more efficient way of doing this? How do I do it?

**Comment by curt2008** [comment]
Just edit your config.ini file in the following format :

`username:[username1,username2,username3]
password:[password1,password2,password3]`

And then run `python runserver.py` with your normal arguments not including user & pass

**Comment by Enterodactyl** [comment]
I see, so wouldn't all of the accounts be scanning the exact same place at the exact same time? Or am I missing something?

**Comment by VergaraF** [comment]
I had that question. How do you make X account scan X location?

**Comment by SiTe417** [comment]
Likewise, I am not sure how to put multiple accounts into Beehive, it all works just under the same account and password.. we all know how that turns out.

**Comment by NoMotion** [comment]
The beehive was a solution to getting a wider radius with a few more accounts. Nowadays we have threaded scanning based on accounts added to the map. So effectively if you want to cover more you can just increase the step and the number of accounts you are scanning with. This solves most of the use cases for the beehive grid and I don't think many use it as much since it wasn't simple to use.

If you add your accounts like @curt2008 states it will use all your accounts and rotate scanning with them

**Comment by Enterodactyl** [comment]
Ahhh I see, so by rotating accoutns it actually scans as if the step counts were less?

**Comment by NoMotion** [comment]
You effectively circumvent the rate limit since it thinks you are a different person scanning, so we can once again scan very quickly. Step counts are still the same

**Comment by bndggl** [comment]
I tried to edit the config.ini as suggested above, but now get the error "username can't be set to list unless its action type is set to 'append'"

I assume there's a simple way to do this and it's obvious I don't have a clue what I'm doing?

**Comment by NoMotion** [comment]
Are you running dev build?

**Comment by KJThaDon** [comment]
Getting same error

**Comment by bndggl** [comment]
Ah, switched to dev branch and now it works

**Comment by c133** [comment]
I'm still using beehive.sh is this not a thing anymore?

**Comment by SiTe417** [comment]
Opening the dev branch to people seems to have exacerbated issues..
