### ISSUE TITLE
Map doesn't appear anymore [old version]

### ISSUE THREAD

**Issue by exeioklm** [AHAAAAAAA/PokemonGo-Map#3088]
Note : I'm on a late version, not the recent one. And since I can't make the new version work, I would prefer to continue with the old one, which was perfectly working until yesterday.

The map on localhost:5000 used to work perfectly. For some reason the map doesn't appear anymore. I've tried on Firefox, on Chrome and with my smartphone, same issue. Here is a screenshot of what I get.

![bug](https://cloud.githubusercontent.com/assets/20784124/17314062/a7354fbe-5861-11e6-8024-d1c5dd282fae.png)

Thank you for your time.

**Comment by wobblybobz** [comment]
@exeioklm : I presume you are using a newer version from the Develop branch. To fix this you need have NodeJS and npm Installed and then run "npm install -g grunt" and then "npm install" this should then run the grunt tasks to convert the sass (Stylesheets) to css and run the JS Minifications tasks which will create a dist inside the static folder containing the files needed to render the page properly. See here for more details... https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Development

**Comment by exeioklm** [comment]
I didn't manage to do what you told me, but I've downloaded the latest version from the link you gave me and replaced the entire folder "static" : It worked. Thanks.
