### ISSUE TITLE
Multiple Accounts

### ISSUE THREAD

**Issue by rlyons20** [AHAAAAAAA/PokemonGo-Map#3090]
I'm trying to run 10 accounts, and here is the command I'm running:

python /opt/bin/PokemonGo-Map/runserver.py -a google -u 1 -u 2 -u 3 -u 4 -u 5 -u 6 -u 7 -u 8 -u 9 -u 10 -p 1 -p 2 -p 3 -p 4 -p 5 -p 6 -p 7 -p 8 -p 9 -p 10 -l "LONG LAT" -H 192.168.1.1 -P #### -st 10 -sd 5 -k googl_API

It only logs in the last account.  I definitely just upgraded to the latest code.

Please help!

**Comment by rlyons20** [comment]
bambusbo just told me... use dev version.

**Comment by rjwestman** [comment]
is it possible to set different locations and step ranges for multiple accounts?
