### ISSUE TITLE
credentials.json does not exist

### ISSUE THREAD

**Issue by R--Perez** [AHAAAAAAA/PokemonGo-Map#3092]
When navigating to my pokemon map directory, and inside the config folder i cant find credentials.json.

**Comment by mgoodsell91** [comment]
I dont think that is needed anymore to run it. If you are on Mac you have to add -k "Gmapskey" when running to get it working. and im pretty sure on windows it asks for it when you click on easysetup.bat, but i could be wrong.

**Comment by invisiblek** [comment]
use command line parameters or config.ini
