### ISSUE TITLE
Error with loading the map

### ISSUE THREAD

**Issue by lordhelixc** [AHAAAAAAA/PokemonGo-Map#3093]
I have been trying to load the map for a while, but I get this when I try:
```
Traceback (most recent call last):
  File "runserver.py", line 18, in <module>
    from pogom.app import Pogom
  File "C:\Users\Austin\Desktop\PokemonGo-Map-develop\pogom\app.py", line 12, in <module>
    from pogom.utils import get_args
  File "C:\Users\Austin\Desktop\PokemonGo-Map-develop\pogom\utils.py", line 117
    print sys.argv[0] + ': error: arguments -l/--location is required'
            ^
SyntaxError: Missing parentheses in call to 'print'
```
The parameters I am using look like this:
```
python runserver.py -u ******** -p ******** -st 10 -k *************************************** -l "26.******** -80.*********"
```

**Comment by NoMotion** [comment]
`arguments -l/--location is required'` You must specify a location with the `-l` option

**Comment by lordhelixc** [comment]
I just tried using a location instead of coordinates and ended up getting the same error. Thanks for trying though.

**Comment by NoMotion** [comment]
Well it definitely is an issue with your location parameter. This is the code segment 
`if args.location is None:
            parser.print_usage()
            print sys.argv[0] + ': error: arguments -l/--location is required'`
It will only execute that line that threw the exception if your location format is wrong. Try moving the location argument to the front of the list

**Comment by Kasmodan1** [comment]
python runserver.py -a ptc -u ********** -p ******** -l "40.755591, -111.873144" -st 5 -sd 1 -t 1 -H 0.0.0.0

Here is my exact command with loc and it works just fine for me. try using this one and see if that works. then you know it was your -l command

**Comment by andrewda** [comment]
The issue is that you're using Python 3. You need to be using Python 2.7.

**Comment by lordhelixc** [comment]
Turns out I had both Python 3 and Python 2.7 installed, and it was defaulting to 3 instead of 2. Thanks!
