### ISSUE TITLE
-t is no longer working

### ISSUE THREAD

**Issue by sabernar** [AHAAAAAAA/PokemonGo-Map#3096]
-t used to allow you to use more than one thread at a time, but now it fails

## Expected Behavior

multiple threads should be initiated

## Current Behavior

the server fails to start
`runserver.py: error: unrecognized arguments: -t 4`

## Steps to Reproduce (for bugs)

1.  python runserver.py -a ptc -u myname -p mypassword -l "45,-122" -st 6 -k  GOOGLEAPIKEY -t 4
2.
3.
4.

## Context

it's much slower to query myarea

## Your Environment

* Version used: 

/projects/PokemonGo-Map (develop) $ git pull origin develop
remote: Counting objects: 44, done.
remote: Total 44 (delta 23), reused 23 (delta 23), pack-reused 21
Unpacking objects: 100% (44/44), done.
From https://github.com/AHAAAAAAA/PokemonGo-Map
 * branch            develop    -> FETCH_HEAD
   a83ce5c..4dba6e6  develop    -> origin/develop

* Environment name and version (e.g. Python 2.7):  Python 2.7 
* Operating System and version (desktop or mobile):  Mac, Chrome

**Comment by Paralysing** [comment]
If you're running the latest develop, check #2956 , they took away -t.

**Comment by NoMotion** [comment]
the number of threads is now directly proportional to the number of accounts you are scanning with

**Comment by FrenzyDemon** [comment]
> the number of threads is now directly proportional to the number of accounts you are scanning
Does this also apply If I'm using the Location Generator to make the beehive.bat, and I use "--Accounts C:\Documents\Accounts.csv"?

Does it automagically know to up the Threads according to how many accounts I listed or do I need to tell it to up the threads somehow?

**Comment by sabernar** [comment]
Well, that sucks.

**Comment by NoMotion** [comment]
@FrenzyDemon I have not used the Location Generator, I think it is being deprecated since you can easily cover 50+ steps with a dozen accounts. 

The application knows how many threads to spin since it will count the number of accounts you wish to login with. Specify the accounts as such `-u user1 -u user2 ... -p pass1 -p pass2 ...`

**Comment by FrenzyDemon** [comment]
Thank you very much!

**Comment by FrenzyDemon** [comment]
One last question, can you please tell me about the suggest Scan Delay? Does it have anything to do with the number of accounts? I remember hearing something about a 5 second rule.

**Comment by chuyskywalker** [comment]
Other's have already noted what's going on. In reality, adding multiple threads (for a single account) no longer does anything other than kick in a throttle from the Niantic servers so the option was removed.
