### ISSUE TITLE
Using Multiple accounts with Hex Beehive

### ISSUE THREAD

**Issue by SiTe417** [AHAAAAAAA/PokemonGo-Map#3097]
Basically, got Hex Beehive working.. but it only uses one account, instead of the multiple I have.

This obviously leads to a lot of issues with Pokemon not scanning.. any simple thing I'm doing wrong or information that may be needed to help figure it out?

**Comment by andrewda** [comment]
Already answered. Use the search.

**Comment by SiTe417** [comment]
Used it, didn't find anything other than people using the Dev build.

Thanks.
