### ISSUE TITLE
Only Pokemon with <3 mins show up on the map!!

### ISSUE THREAD

**Issue by OmarMustafa** [AHAAAAAAA/PokemonGo-Map#3098]
I tried running the latest version, as well as the master one from the wiki and I can never see Pokemon that will disappear in more than 3 mins like other similar projects. Any idea?

**Comment by Kasmodan1** [comment]
1. shorten your scan radius. -st 5
2. use -t 1
3. I use -sd 1
 I find pokies just fine and 13 min timers and under. I figure a smaller scan radii will refresh faster and will catch when a poke is placed sooner.

**Comment by OmarMustafa** [comment]
Hi,
Thanks a lot. Unfortunately, it still doesn't work. I even tried -st 5 but no luck! It's always like 2:50 or less. I'm running the following command, I tried Chrome/Firefox but same thing :(

python runserver.py -a google -u ...@gmail.com  -p ... -k "..." -l "Central Park, NYC, USA" -np -t 1 -st 1 -sd 1

**Comment by petteri72** [comment]
Change sd to 11 and you will also find rare ones.

**Comment by leTokki** [comment]
All pokemon less than 3 mins are most likely lure spawned pokemons, have you tried `-sd 5 -t 1`?

**Comment by OmarMustafa** [comment]
@leTokki I tried that, and also -sd 1 and 12 but didn't work!
@petteri72 wow, same command with level 20 account does show more pokemon (although 90% are still <3 but I guess that's due to the lure modules everywhere)! Why would -sd 11 btw? That's just the scan delay.
