### ISSUE TITLE
Pokemon does not despawn after the amount of time specified (possible server issue)

### ISSUE THREAD

**Issue by haagiboy88** [AHAAAAAAA/PokemonGo-Map#31]
### Environment info
Operating System: Windows 10 64-bit

Installed version of Python: 2.7.12

### Steps to reproduce
1. Run program as normal and wait til you find a pokemon. The timer does not decrease when program is updating.

### What have you tried?
1. Waiting for 10 minutes while server was up (ish) to see if the timer on a 4 min 41 sec pokemon would despawn on the map.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by sykhro** [comment]
See #61
