### ISSUE TITLE
How can i have my google username ?

### ISSUE THREAD

**Issue by Lesspion** [AHAAAAAAA/PokemonGo-Map#310]
Hi everyone,

I've try all possibility for my google account, and the same error appear ..

-u test.t@gmail.com or -u test.t

(sorry for my bad english ..)
Thanks if you can help me

**Comment by DerScreever** [comment]
you need to set the auth service
example: python example.py **-a google** -u test.t@gmail.com -p password

**Comment by Lesspion** [comment]
I set it : python example.py -a google -u test.t@gmail.com -p "just*a*password"
But I have the same error ...

**Comment by DerScreever** [comment]
for me this work o.O

**Comment by MikeDX** [comment]
Do you have two step auth enabled? There seems to be a problem with that. Google auth definitely works as I've used both auth methods fine.

**Comment by Answeroid** [comment]
I have 2 step auth and my google account doesnt work, but pts test acc just worked fine. Trying to find the solution for that on my side

**Comment by Lesspion** [comment]
Yes I have the 2 step auth and if i disable it, it works fine !

**Comment by meersjo** [comment]
In your google account settings, under security, you can create application-specific passwords. Those work even while 2FA is enabled.
