### ISSUE TITLE
Can't npm install

### ISSUE THREAD

**Issue by Riffles** [AHAAAAAAA/PokemonGo-Map#3101]
Hello, any help would greatly be appreciated. I'm trying to do npm install after downloading the nodejs and installing it, it is coming back with warnings as depicted in the image attached. What do I need to do to get this working properly so I can run the grunt build command?
![npminstall](https://cloud.githubusercontent.com/assets/20785901/17316378/3628d54a-5828-11e6-9d6e-7b1072da393b.png)

**Comment by hfknight** [comment]
you should run npm install in PokemonGo-Map folder
