### ISSUE TITLE
running beehive.bat seems to work no output localhost:5000

### ISSUE THREAD

**Issue by watwatwat1** [AHAAAAAAA/PokemonGo-Map#3103]
hi guys,
I have got the development beehive program making a batchfile using the .csv (in the main folder)
it says python.exe can not be found.  However in the folder i can run scan as normal.  is there something i need to do to the batch file to make it recognize python

**Comment by andrewda** [comment]
You need to make sure Python 2.7 is properly installed. There are numerous Windows tutorials online.
