### ISSUE TITLE
Please run "grunt build" before starting the server

### ISSUE THREAD

**Issue by Ayysir** [AHAAAAAAA/PokemonGo-Map#3107]
based on latest changes to develop branches i'm receiving `Please run "grunt build" before starting the server` on heroku. Any tips?

**Comment by andrewda** [comment]
This has been answered numerous times. Please use the search.

**Comment by Ayysir** [comment]
...uh didn't show but OK. Thanks for lack of help or direction a issue
ticket

**Comment by andrewda** [comment]
#2740 - just takes one [search](https://github.com/AHAAAAAAA/PokemonGo-Map/search?utf8=%E2%9C%93&q=grunt+build+heroku&type=Issues)

We expect people reporting issues to not report an already-submitted issue which they can refer to. It just clutters up the issues and is completely unnecessary.
