### ISSUE TITLE
Can't start on Windows

### ISSUE THREAD

**Issue by NickRimmer** [AHAAAAAAA/PokemonGo-Map#311]
### Environment info
Operating System: Windows 10

Installed version of Python:
Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)] on win3

### Steps to reproduce
1. git clone https://github.com/AHAAAAAAA/PokemonGo-Map
2. cd PokemonGo-Map
3. pip install -r requirements.txt
4. python example.py -a ptc -u myUsername -p myPassword -l "NY" -st 5

### What have you tried?
1. reinstall requirements
2. start on linux (working fine)

### Logs or other output that would be helpful

>Traceback (most recent call last):
  File "example.py", line 26, in <module>
    from gpsoauth import perform_master_login, perform_oauth
  File "C:\Python27\lib\site-packages\gpsoauth\__init__.py", line 4, in <module>
    from . import google
  File "C:\Python27\lib\site-packages\gpsoauth\google.py", line 4, in <module>
    from Cryptodome.PublicKey import RSA
  File "C:\Python27\lib\site-packages\Cryptodome\PublicKey\RSA.py", line 83, in <module>
    from Cryptodome.Math.Numbers import Integer
  File "C:\Python27\lib\site-packages\Cryptodome\Math\Numbers.py", line 42, in <module>
    from Cryptodome.Math._Numbers_gmp import Integer
  File "C:\Python27\lib\site-packages\Cryptodome\Math\_Numbers_gmp.py", line 155, in <module>
    _gmp.mpz_init = lib.__gmpz_init
  File "C:\Python27\lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "C:\Python27\lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function '__gmpz_init' not found

**Comment by nborrmann** [comment]
Most likely dependencies didn't install cleanly.

**Comment by NickRimmer** [comment]
When I trying "pip install -r requirements.txt"

>Requirement already satisfied (use --upgrade to upgrade): geopy==1.11.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): protobuf==2.6.1 in c:\python27\lib\site-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): requests==2.10.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): flask-googlemaps==0.2.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): s2sphere==0.2.4 in c:\python27\lib\site-packages (from -r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): flask==0.11.1 in c:\python27\lib\site-packages (from -r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): gpsoauth==0.3.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): coveralls==1.1 in c:\python27\lib\site-packages (from -r requirements.txt (line 8))
Requirement already satisfied (use --upgrade to upgrade): werkzeug==0.11.10 in c:\python27\lib\site-packages (from -r requirements.txt (line 9))
Requirement already satisfied (use --upgrade to upgrade): setuptools in c:\python27\lib\site-packages (from protobuf==2.6.1->-r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): future in c:\python27\lib\site-packages (from s2sphere==0.2.4->-r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): click>=2.0 in c:\python27\lib\site-packages (from flask==0.11.1->-r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): Jinja2>=2.4 in c:\python27\lib\site-packages (from flask==0.11.1->-r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): itsdangerous>=0.21 in c:\python27\lib\site-packages (from flask==0.11.1->-r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): pycryptodomex>=3.0 in c:\python27\lib\site-packages (from gpsoauth==0.3.0->-r requirements.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): docopt>=0.6.1 in c:\python27\lib\site-packages (from coveralls==1.1->-r requirements.txt (line 8))
Requirement already satisfied (use --upgrade to upgrade): coverage>=3.6 in c:\python27\lib\site-packages (from coveralls==1.1->-r requirements.txt (line 8))
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe in c:\python27\lib\site-packages (from Jinja2>=2.4->flask==0.11.1->-r requirements.txt (line 6))

**Comment by DerScreever** [comment]
on windows i had some problems, when i run the pip installation without admin rights.

**Comment by NickRimmer** [comment]
I tried with admin rights:
1. pip uninstall -r requirements.txt 
2. pip install -r requirements.txt

no changes )=

**Comment by NickRimmer** [comment]
"pip list" command result:

>click (6.6)
coverage (4.1)
coveralls (1.1)
docopt (0.6.2)
Flask (0.11.1)
Flask-GoogleMaps (0.2.0)
future (0.15.2)
geopy (1.11.0)
gpsoauth (0.3.0)
itsdangerous (0.24)
Jinja2 (2.8)
MarkupSafe (0.23)
pip (8.1.2)
protobuf (2.6.1)
pycryptodomex (3.4.2)
requests (2.10.0)
s2sphere (0.2.4)
setuptools (24.0.3)
Werkzeug (0.11.10)
wheel (0.29.0)

**Comment by Vnr** [comment]
It's pycryptodome issue. I solved that by copying "c:\Python27\Lib\site-packages\Cryptodome\Math\mpir.dll" to "c:\Python27\" folder.

**Comment by DerScreever** [comment]
Im sorry, but we dropped the support for the master branch (example.py). 
This branch is deprecated.  
The new branch contains a much cleaner structure so pls report only issues related to the develop branch. 

Your development team
