### ISSUE TITLE
Changing map default options

### ISSUE THREAD

**Issue by blindreaper** [AHAAAAAAA/PokemonGo-Map#3113]
How can i set Pokestops to unticked by default? I removed checked from map.html but it it still set to on as default.

**Comment by ELusiveLPFAN** [comment]
Edit static/js/map.js, than rebuild it with "grunt build". Profit!

**Comment by blindreaper** [comment]
Cheers, any idea how to hide pidgey by default?

**Comment by ELusiveLPFAN** [comment]
Not sure, but maybe like this?
Edit map js:
  remember_select_exclude: {
    default: [pidgey, rattata],
    type: StoreTypes.JSON

Run grunt build

**Comment by duncanmcdowell** [comment]
I just manually store them in the load pokemon function.

You have to identify them by id. Example:

`Store.set('remember_select_exclude', [19]);`

**Comment by blindreaper** [comment]
Cheers, set me on the right path.
