### ISSUE TITLE
config.ini

### ISSUE THREAD

**Issue by hoidaan** [AHAAAAAAA/PokemonGo-Map#3120]
Running on OSX.

Maybe this is not the right place to ask but I hope someone can help me with this. I'm a basic user and I'm trying to configure the config.ini file. When I don't use the config.ini and just run it with all options it does work, but I'd like to do it with the config.ini file :)  When I use python run server.py it says: 

sage: runserver.py [-h] [-a AUTH_SERVICE] [-u USERNAME] [-p PASSWORD]
                    [-l LOCATION] [-st STEP_LIMIT] [-sd SCAN_DELAY]
                    [-td THREAD_DELAY] [-ld LOGIN_DELAY] [-dc] [-H HOST]
                    [-P PORT] [-L LOCALE] [-c] [-d] [-m] [-ns] [-os] [-fl] -k
                    GMAPS_KEY [-C] [-D DB] [-t NUM_THREADS] [-np] [-ng] [-nk]
                    [--db-type DB_TYPE] [--db-name DB_NAME]
                    [--db-user DB_USER] [--db-pass DB_PASS]
                    [--db-host DB_HOST] [-wh [WEBHOOKS [WEBHOOKS ...]]]
runserver.py: error: unrecognized arguments: --Authentication settings --Search settings --Misc --Webserver settings

I've already renamed the config.example to config.ini in the config map and my setting looks like this:

Authentication settings
auth-service: ptc
username: ******
password: *****

# Database settings
#db-type: sqlite        # sqlite (default) or mysql
#db-host:               # required for mysql
#db-name:               # required for mysql
#db-user:               # required for mysql
#db-pass:               # required for mysql

Search settings
location: Nederland
#no-gyms:               # disables gym scanning (default false)
#no-pokemon:            # disables pokemon scanning (default false)
#no-pokestops:          # disables pokestop scanning (default false)
#num-threads:           # number of search threads (default 1)
#scan-delay:            # default 5
step-limit: 6

Misc
gmaps-key: AIzaSyBth4jwTiWcx***************
#webhook:               # webhook URL (including http://)

Webserver settings
host: 192.168.178.24
port: 5000

Thanks!

**Comment by Ashex** [comment]
`Authentication settings` should have a # in front.

**Comment by hoidaan** [comment]
Wow.. Thanks man.. I thought I had to remove them! It's working now! :D
