### ISSUE TITLE
Nginx config issue.

### ISSUE THREAD

**Issue by Shadowgar** [AHAAAAAAA/PokemonGo-Map#3128]
So I'm running Nginx inside Xampp at the moment and everything works fine except I can't get Pogo map to display. I thought I had the Nginx config down but I guess not. Anyone help tweak my config? 

`server {
        listen       80;
        server_name  localhost;
 
        location ~* ^.+\.(jpg|jpeg|gif|png|ico|css|zip|tgz|gz|rar|bz2|pdf|txt|tar|wav|bmp|rtf|js|flv|swf|html|htm)$
        {
            #root   html;
            root   F:/xampp/htdocs;
            expires max;
        }
        #set default location
        location / {
            proxy_pass         http://127.0.0.1:8080/;
        }
        #Adding location for phpmyadmin
        location /phpmyadmin {
            proxy_pass         http://127.0.0.1:8080/phpmyadmin;
            allow 127.0.0.1;
            deny all;
        }
        #adding pokemon go
        location /pogo/ {
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   Host      $http_host;
            proxy_pass         http://127.0.0.1:5000;
         }`

**Comment by Shadowgar** [comment]
If I change the default location of /'s port from 8080 to 5000 it works but I'm needing to point this to a domain/pogo and not domain.

**Comment by shiona** [comment]
I believe I ran across the same problem as you: proxy_pass does not alter the path.

I assume you want this to be set up so that http://yourhost/ gets proxyed to 127.0.0.1:8080 and http://yourhost/pogo gets proxyed to 127.0.0.1:5000. If this is correct, here's (part of) my config:

>         location /pokemon/ {
                rewrite ^/pokemon(/.*)$ $1 break;
                proxy_pass http://[internal_ip]:5000/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto https;
                proxy_redirect off;
        }

Without the rewrite line a request for `http://myhost/pokemon/` gets forwarded to `http://[internal_ip]:5000/pokemon/`. The rewrite drops the `pokemon` from the path.

I'm not expert on http nor nginx, so I can't say I completely understand the X-fields, but I hope you'll manage to get forward with this.

And if you manage to solve this, please close the issue.

**Comment by Ashex** [comment]
Does the example in the [wiki](https://jonaharagon.github.io/PoGoMapWiki/#!nginx.md) not work for you?

**Comment by shiona** [comment]
I stand corrected. The wiki version works.

I must have messed up something when I first tried setting that up.

**Comment by Shadowgar** [comment]
the wiki only works if I point the 5000 port to /

If I point it to /go/ it does not work. I'll deleted everything and try again.

**Comment by Shadowgar** [comment]
This is my config using the exact wiki
`
#user  nobody;
worker_processes  1;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    #gzip  on;

server {
        listen       80;
        server_name  localhost;
 
        location ~* ^.+\.(jpg|jpeg|gif|png|ico|css|zip|tgz|gz|rar|bz2|pdf|txt|tar|wav|bmp|rtf|js|flv|swf|html|htm)$
        {
            #root   html;
            root   C:/xampp/htdocs;
            expires max;
        }
        #set default location
        location / {
            proxy_pass         http://127.0.0.1:8080/;
        }
        #Adding location for phpmyadmin
        location /phpmyadmin {
            proxy_pass         http://127.0.0.1:8080/phpmyadmin;
            allow 127.0.0.1;
            deny all;
        }
		location /go/ {
           proxy_pass http://127.0.0.1:5000/;
        }
    

        #error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }

        # proxy the PHP scripts to Apache listening on 127.0.0.1:80
        #
        #location ~ \.php$ {
        #    proxy_pass   http://127.0.0.1;
        #}

        # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
        #
        #location ~ \.php$ {
        #    root           html;
        #    fastcgi_pass   127.0.0.1:9000;
        #    fastcgi_index  index.php;
        #    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
        #    include        fastcgi_params;
        #}

        # deny access to .htaccess files, if Apache's document root
        # concurs with nginx's one
        #
        #location ~ /\.ht {
        #    deny  all;
        #}
    }


    # another virtual host using mix of IP-, name-, and port-based configuration
    #
    #server {
    #    listen       8000;
    #    listen       somename:8080;
    #    server_name  somename  alias  another.alias;

    #    location / {
    #        root   html;
    #        index  index.html index.htm;
    #    }
    #}


    # HTTPS server
    #
    #server {
    #    listen       443 ssl;
    #    server_name  localhost;

    #    ssl_certificate      cert.pem;
    #    ssl_certificate_key  cert.key;

    #    ssl_session_cache    shared:SSL:1m;
    #    ssl_session_timeout  5m;

    #    ssl_ciphers  HIGH:!aNULL:!MD5;
    #    ssl_prefer_server_ciphers  on;

    #    location / {
    #        root   html;
    #        index  index.html index.htm;
    #    }
    #}

}
`

This now only leaves me with text only on the map.

**Comment by Shadowgar** [comment]
After deleting everything an re installing it started working. So it must have been a syntax error on my part. Thank you all for your help.
