### ISSUE TITLE
Does not the map

### ISSUE THREAD

**Issue by NoiseControllers** [AHAAAAAAA/PokemonGo-Map#313]
http://i.imgur.com/CnDPiL5.png

**Comment by chuparCh0pper** [comment]
more info on what you have tried please

**Comment by DerScreever** [comment]
more infos or i close this.

**Comment by m0rtem** [comment]
Mine is doing this also, tested and works on windows 8 but windows 10 has this issue.

Something to do with markupsafe?

If its of any help I did not have pip setup on this win10 machine so I installed manually first, then tried pip with no results.

> SyntaxError: missing } after property list
> http://127.0.0.1:5000/
> Line 51

**Comment by NoiseControllers** [comment]
Thanks @m0rtem for complete information, sorry for my english i am spanish.

**Comment by m0rtem** [comment]
@NoiseControllers that is alright, your English is not too bad! Maybe just change the title if you can too something more relevant => "Uncaught SyntaxError: Unexpected string"

**Comment by m0rtem** [comment]
UPDATE

I managed to fix this by changing the key from unicode string to a regular string.

In example.py on line 829 I have added:

`        pokemon_key = str(pokemon_key)`

**Comment by dnsBlah** [comment]
There is still the issue, on line 839, the 'key' value contains u' <<< an pokemonkey here >>> '
And will crash the jquery.
I just removed it. and the map is working, together with the change on line 831 from above

**Comment by DerScreever** [comment]
@dnsBlah 
then please create a pull request with the changes ^^

**Comment by m0rtem** [comment]
@dnsBlah I did not need to make the change on line 839 in order to get it to work, will try it though.

**Comment by akam-it** [comment]
i just added pokemon_key = str(pokemon_key) on line 829.

with line 830 changed to LABEL_TMPL = ''' map doesn't work

**Comment by m0rtem** [comment]
@akam-it what error did you receive?

**Comment by akam-it** [comment]
SyntaxError: missing } after property list

**Comment by m0rtem** [comment]
that is exactly the error I had before I made the changes... did you make the change @dnsBlah suggested aswell?

**Comment by dnsBlah** [comment]
thats because of the unicode 
I'm not sure how/why there is unicode in: the pokemon_key
```
pokeMarkers.append({
            'type': 'pokemon',
            'key': pokemon_key,

```

So i just removed the whole key: pokemon_key

It's not a fix, but a workaround, so there is no pull requests, sorry

**Comment by m0rtem** [comment]
I too don't feel comfortable doing a pull request as I only removed functionality and added 1 line. Seeing as it worked for me on windows8 I am reluctant to change this without solving the original problem.

**Comment by dnsBlah** [comment]
exactly, it's just a workaround, not a fix.
For me the key was also bugging around. And after a while I'm getting other errors

**Comment by akam-it** [comment]
actualy it doesn't help me.
the map is shown now, but it is empty

**Comment by m0rtem** [comment]
The map loads initially for me but does not show anything until I wait 5/10 seconds and refresh the map. Does this do anything for you?

**Comment by blakebjorn** [comment]
I had to whitelist the page in my ad blocker (Opera built-in one) in addition to making the 

line 831: LABEL_TMPL = u'''   -> LABEL_TMPL = '''
and 
line 842: 'key': pokemon_key -> 'key': str(pokemon_key)

changes

**Comment by NoiseControllers** [comment]
after making changes @blakebjorn 
http://i.imgur.com/Q5Fkw9r.png

**Comment by blakebjorn** [comment]
@NoiseControllers 

Add 

pokemon['name'] = pokemon['name'].replace(u'\N{MALE SIGN}','(M)').replace(u'\N{FEMALE SIGN}','(F)')

right under pokemon = pokemon[pokemon_key] on line ~823

it should work now when there are nidorans in range

**Comment by NoiseControllers** [comment]
it does not work @blakebjorn 
```
for pokemon_key in pokemons:
        pokemon = pokemons[pokemon_key]
		pokemon['name'] = pokemon['name'].replace(u'\N{MALE SIGN}','(M)').replace(u'\N{FEMALE SIGN}','(F)')
```
https://gyazo.com/ef99af2fcae7f442f5a500c72e16a65a

**Comment by blakebjorn** [comment]
@NoiseControllers 

if you are using notepad or notepad++ or some other editor (other than an actual python IDE) you will have to use 4 spaces instead of TAB or you will get indentation errors when you run the program
