### ISSUE TITLE
What command do i need to start single console which will scan entire city with given multiple accounts

### ISSUE THREAD

**Issue by MonsterMMORPG** [AHAAAAAAA/PokemonGo-Map#3133]
Ok i have installed ptc account creator and generated sufficient accounts

I want to start a scan with certain radius of kilometers and provide multiple accounts

So these multiple accounts can be shared to scan entire area with a good speed

What command do i need? i dont want to certainly start different console for each account manually with providing manual information

That is not doable

I can use development branch as well just tell me the command ty :D

**Comment by danielhampton** [comment]
Try using --read-the-wiki

**Comment by Harachteh** [comment]
either use the Hex-Beehive-Generator in the tools folder or use the develop branch and just add multiple users and passwords (... -u user1 -u user2 ... -p pass1 -p pass2 ...)

**Comment by Harachteh** [comment]
https://jonaharagon.github.io/PoGoMapWiki/#!beehive.md

**Comment by MonsterMMORPG** [comment]
@Harachteh ty let me try that. if you type a full command lets say for 3 accounts that would help me very much though. for development branch

**Comment by Harachteh** [comment]
runserver.py -a ptc -u user1 -u user2 -u user3 -p pass1 -p pass2 -p pass3 -l "lat, long" -st 6
keep in mind develop no longer uses -t

**Comment by 1111121RicardoBrandao** [comment]
This should be closed since this is not a issue but a lack of reading the wiki, is everything explained there
