### ISSUE TITLE
Map not automatically showing scanned pokemon

### ISSUE THREAD

**Issue by silentclown** [AHAAAAAAA/PokemonGo-Map#3134]
Not sure if I done something wrong but scanning is working fine but I have to either manually refresh the page or just click and drag the map a little for newly scanned pokemon and new step circles to appear on the map.

**Comment by danielhampton** [comment]
Look in your console for a javascript error, or try rebuilding the js files with grunt build.

**Comment by silentclown** [comment]
I fixed the issue by running Chrome we browser instead of Microsoft Edge / IE . Rookie mistake
