### ISSUE TITLE
[ERROR] Please run "grunt build" before starting server

### ISSUE THREAD

**Issue by MonsterMMORPG** [AHAAAAAAA/PokemonGo-Map#3136]
Here my command on latest development branch https://github.com/AHAAAAAAA/PokemonGo-Map/tree/develop

downloaded entire folder and double clicked easy install on windows 8.1 with administrator rights

It was working with master branch

**2016-08-02 14:19:43,737 [      MainThread][     runserver][CRITICAL] Please run "grunt build" before starting the server**

I have installed all these commands already
```

npm install grunt --save-dev

npm install jshint-stylish
npm install grunt-contrib-uglify
npm install grunt-contrib-jshint 
npm install grunt-contrib-watch
npm install grunt-sass
npm install grunt-contrib-copy
npm install grunt-contrib-clean
npm install grunt-contrib-cssmin
npm install grunt-usemin
npm install grunt-contrib-concat
npm install grunt-html-validation
npm install grunt-babel
npm install grunt-minjson

npm install babel-preset-es2015 --save
npm install babel-preset-react --save

npm install grunt build --save
```

**Comment by hallengreenn** [comment]
cd into the folder, then;

npm install
grunt build

This works for me.

**Comment by MonsterMMORPG** [comment]
seems like working now ty @hallengreenn

**Comment by licklake** [comment]
got the same problem on a linux machine
