### ISSUE TITLE
/next_loc does not work for me

### ISSUE THREAD

**Issue by chuparCh0pper** [AHAAAAAAA/PokemonGo-Map#314]
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discordapp.com/invite/qbpVH6b).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System: Ubuntu 64bit

Installed version of Python: 2.7

### Steps to reproduce
1. Call localhost:5000/next_loc?lat=38.897660&lon=-77.036551
2. Wait for current scan to finish

### What have you tried?
1.

### Logs or other output that would be helpful
127.0.0.1 - - [19/Jul/2016 12:14:55] "GET /next_loc?lat=38.897660&lon=-77.036551 HTTP/1.1" 200 -
....
Completed: 100.0%
Update to next location 38.897660, -77.036551
[-] register_background_thread called
[-] register_background_thread: queueing
[!] DEBUG mode on
[-] looping: step 1 of 4
[+] Searching pokemons for location 29.0 18.0

**Comment by marazmatik** [comment]
same problem

**Comment by TiesdeKok** [comment]
I suspect the problem is in line 609.  
`set_location_coords(x * 0.0025 + origin_lat, y * 0.0025 + origin_lon, 0)`  

The coordinates are set using increments relative to the original_lat/lon not the newly updated FLOAT_LAT and FLOAT_LON.

**Comment by chuparCh0pper** [comment]
fixed it https://github.com/AHAAAAAAA/PokemonGo-Map/pull/303/commits/288e8875a20b762d85b9d2225ecc0bc3a2109a16

**Comment by DerScreever** [comment]
Im sorry, but we dropped the support for the master branch (example.py). 
This branch is deprecated.  
The new branch contains a much cleaner structure so pls report only issues related to the develop branch. 

Your development team
