### ISSUE TITLE
[QUESTION] Don't know which branch/version to use anymore

### ISSUE THREAD

**Issue by remie2000** [AHAAAAAAA/PokemonGo-Map#3144]
A few days ago Shiona started a pull request to let the pokemon map use multiple accounts.
Are multiple accounts already supported yet in one of the branches?

If yes:

- Which branch should I download and deploy on my Ubuntu Server 14.04 VPS?

I am using 27 accounts at this moment

**Comment by Ashex** [comment]
All PRs are made against develop. When a release is made the commit is tagged then merged into master.

bleeding edge: develop
Stable: tagged releases or master

**Comment by remie2000** [comment]
So...? Which version is supporting multiple (27) accounts

**Comment by Ashex** [comment]
`All PRs are made against develop. `

**Comment by cirespieler** [comment]
develop is the answer

**Comment by remie2000** [comment]
Thx @cirespieler

**Comment by remie2000** [comment]
#3155
