### ISSUE TITLE
So many database is locked error even with as low as 20 accounts

### ISSUE THREAD

**Issue by MonsterMMORPG** [AHAAAAAAA/PokemonGo-Map#3145]
I am using latest development thread

My computer is very strong

Is this expected when using as low as 20 miner agents?

Here the command i use

`d: & cd "D:\74 pokemon go\PokemonGo-Map-master" & python runserver.py  -a ptc -u ac -p pw  -a ptc -u ac -p pw  -a ptc -u ac -p pw  -a ptc -u ac -p pw  -a ptc -u ac -p pw  -a ptc -u ac -p pw  -a ptc -u ac -p pw  -a ptc -u ac -p pw  -a ptc -u ac -p pw  -a ptc -u ac -p pw  -a ptc -u ac -p pw  -a ptc -u ac -p pw  -a ptc -u ac -p pw  -a ptc -u ac -p pw  -a ptc -u ac -p pw  -a ptc -u ac -p pw  -a ptc -u ac -p pw  -a ptc -u ac -p pw  -a ptc -u ac -p pw  -a ptc -u ac -p pw  -st 15 -k asdas-asdsa-l "36.80204, 34.63328" -sd 7`

Here the error message

![error message](https://cloud.githubusercontent.com/assets/4149474/17328134/975f8934-58c4-11e6-9521-4a32d78a4b14.png)

**Comment by MonsterMMORPG** [comment]
moved folder to SSD and disabled pokestop and gym

now no errors :D

**Comment by justsomedudeonthenet** [comment]
When using sqlite database, yes, this happens.
Switch to using mySQL if you want to reliably handle that many searchers.
