### ISSUE TITLE
[ERROR] ImportError: No module named packages.urllib3

### ISSUE THREAD

**Issue by inkkinker** [AHAAAAAAA/PokemonGo-Map#3146]
If I try to run the runserver.py I get the error "ImportError: No module named packages.urllib3". I don't know whats missing because if I try to install urllib3 it says its already installed

## Your Environment
pgoapi-purge
Python 2.7
Ubuntu 14.04 LTS

**Comment by Arthok** [comment]
I have the same error but only on my Server. I still don't understand where it come from because I purge everything ...
That's a mystery ...

**Comment by inkkinker** [comment]
@Arthok try the execute "sudo pip install --upgrade requests" for me it worked
