### ISSUE TITLE
Pushbullet support?

### ISSUE THREAD

**Issue by waltwhitman6969** [AHAAAAAAA/PokemonGo-Map#3149]
Been trying to bring in Pushbullet support for this so I can get the notifications to my phone, with the lat/long of the pokemon but I can't seem to figure it out. Anyone know how to implement this? I know there was a project on /r/pokemongodev that did this but the guy that made it doesn't seem to be updating it anymore.

**Comment by gine78** [comment]
https://github.com/AHAAAAAAA/PokemonGo-Map/issues/2988

**Comment by waltwhitman6969** [comment]
Exactly what I was looking for. Thank you my friend
