### ISSUE TITLE
Your location blinking constantly in mobile Android Google Chrome and not changing location

### ISSUE THREAD

**Issue by Gol-D-Ace** [AHAAAAAAA/PokemonGo-Map#3154]
Clicking the Your location button should get the current location of the phone and then set it for the search.

Instead the button is just constantly blinking for me and not getting a location at all

1. Start the server like you always do.
2. Open the Webpage in the Android Google Chrome Browser
3. Press the Your location button in the bottom right corner
4. Button will blink forever and will not change your location

The button is working fine in Firefox 47.0.1 running on Windows 7 x64 SP1 Ultimate.
The button is also working fine in the Android Firefox App Version 47.0

Server is running on Ubuntu MATE 16.04
Using develop branch on commit c8b145e
Android Version 5.1.1 and the Google Chrome App Version is 51.0.2704.81

**Comment by tarthim** [comment]
You need to serve HTTPS for the Google Maps API to work properly with location. Your PC is working because this restriction isn't build into localhost.

**Comment by Gol-D-Ace** [comment]
I guess this is currently not possible or?

So I will have to stick to the Firefox Android App (which is working fine instead of Google Chrome).

**Comment by tarthim** [comment]
Either that, or you setup a https reverse proxy, but that could take more effort depending on your situation.

**Comment by Gol-D-Ace** [comment]
I guess sticking to the Firefox App is enough for me for now ;)

Thank you very much for answering.
