### ISSUE TITLE
[GUIDE] How to use multiple accounts (multiple threads) on DEV build

### ISSUE THREAD

**Issue by wardude202** [AHAAAAAAA/PokemonGo-Map#3155]
**GUIDE FOR CONFIG.INI**

HOW TO USE MULTIPLE ACCOUNT IN CONFIG.INI IN THE DEVELOP BUILD TREE

righto here is the syntax
note with auth-service each account must use its corresponding auth server(ptc / google), for me i use 2x ptc accounts and 1x google account thus my [ptc, ptc, google] auth-service setup

auth-service: [ptc, ptc, google]
username: [USER1, USER2, USER3@gmail.com]
password: [PASS1, PASS2, PASS3]

OR

(if everything has the same password)

auth-service: [ptc, ptc, google]
username: [USER1, USER2, USER3@gmail.com]
password: PASS1

EXAMPLE
auth-service: [ptc, ptc, google]
username: [Poophead, Thisusauser, Realgmail@gmail.com]
password: [PoopConfirmed, Totallythepass, Gmailpass]

**Comment by Gol-D-Ace** [comment]
Your instructions are for the config.ini *hint*

For users that want to use the command line instead do this:

./runserver.py -a ptc -a ptc -a google -u user1ptc -u user2ptc -u user3google -p pwuser1ptc -p pwuser2ptc -p pwuser3google

**Comment by HardTacos** [comment]
Great guide. This should be added to the documentation in the dev build

**Comment by 1111121RicardoBrandao** [comment]
If the accounts use all the same service or password you dont need to repeat them

auth-service: ptc
username: [USER1, USER2, USER3]
password: pass

Same for users that want to use command line

**Comment by brianhrowe** [comment]
So after setting up my config file I run

`python runserver.py`

without any arguments because they're all set in the config (including my google Key, and yes the line it's on is uncommented). However when I run this it returns

> usage: runserver.py [-h] [-a AUTH_SERVICE] [-u USERNAME] [-p PASSWORD]
                    [-l LOCATION] [-st STEP_LIMIT] [-sd SCAN_DELAY]
                    [-ld LOGIN_DELAY] [-dc] [-H HOST] [-P PORT] [-L LOCALE]
                    [-c] [-d] [-m] [-ns] [-os] [-nsc] [-fl] -k GMAPS_KEY [-C]
                    [-D DB] [-cd] [-np] [-ng] [-nk] [--db-type DB_TYPE]
                    [--db-name DB_NAME] [--db-user DB_USER]
                    [--db-pass DB_PASS] [--db-host DB_HOST]
                    [--db-max_connections DB_MAX_CONNECTIONS]
                    [-wh [WEBHOOKS [WEBHOOKS ...]]]
runserver.py: error: argument -k/--gmaps-key is required

As far as I can tell there's no switch for telling it to run the config file. It's supposed to be CLI > Config > Defaults right?

Thnx

**Comment by wardude202** [comment]
@brianhrowe  says that you need your google maps key recheck your config,ini file buddy it seems like its either #ed out or not there

**Comment by brianhrowe** [comment]
@wardude202 I've attached a snap of my config file. I believe it's correctly set up. I have auth-service, usernames, passwords, location and google maps key uncommented with appropriate values (redacted).

Not sure what else I'd need to do.

Thanks
![config](https://cloud.githubusercontent.com/assets/2099182/17332610/5a28d628-589d-11e6-9ff7-379965900947.jpg)

**Comment by bbbenji** [comment]
Is it possible to define 2 locations with this method? For example 2 different cities.

**Comment by alexanderhektor** [comment]
How does the app behave / use the multiple accounts?
Is it using the beehive route, but faster and in an intelligent way? will it create multiple beehives by itself?

**Comment by brianhrowe** [comment]
@alexpantyukhin it will still only scan on the set scan delay (5seconds by default). But scans however many locations in the pattern as you have accounts. 

Then delay and scan said number of locations again until it reaches the step limit and moves back to the origin.

**Comment by sirdumpty** [comment]
is there a way to scan multiple locations/coordinates?

**Comment by bbbenji** [comment]
@sirdumpty I already asked this question up above. From looking through the code (lightly) it appears that it is not possible and would require semi-major changes to implement. 

I think it would be a good idea to be able to define the config via argument. This way it would be possible to split multiple accounts to multiple locations and run concurrent instances and only 1 as a host.

**Comment by Evuse** [comment]
I can run multiple scanners, i can see em on the webpanel, but i can only set 1 location even for multiple accounts. Please how should i configure config.ini?

**Comment by bbbenji** [comment]
@Evuse You can't do that.

**Comment by Evuse** [comment]
So how should i do?

**Comment by bbbenji** [comment]
@Evuse You can't...

**Comment by sirdumpty** [comment]
@bbbenji you're right, it seems like i had to use multiple cmd prompts using different accounts to scan other locations.

**Comment by Evuse** [comment]
@sirdumpty this is ok, but how to launch 10 scanners and see results just on a single webpage?

**Comment by ramirex5** [comment]
@Evuse I don't think you can. Try launching few scanners on different ports and open multiple browser windows.

**Comment by Evuse** [comment]
@ramirex5 this is not a solution. multiple scan in a single web view is possible, i'm sure, but i don't know how :(

**Comment by bbbenji** [comment]
@Evuse The solution has been posted multiple times. Please search or at least ask in a relevant issue. This is not the place.

**Comment by Evuse** [comment]
There's not a full complete solution. Please can you help me to find it out? Thanks

**Comment by hoidaan** [comment]
@brianhrowe I don't know if this answers you question, but I can login with two accounts using this:

# Authentication settings
auth-service: ptc
username: *****
password: ****

auth-service: google
username: *********
password: ********

**Comment by Evuse** [comment]
I can login with multiple accounts, but i'd like to scan different locations in a single web view. Can someone help me please?

**Comment by fuglesang** [comment]
@Evuse The general gist of it is found here: https://jonaharagon.github.io/PoGoMapWiki/#!mysql.md

You need to make them "talk" together, meaning a central database all servers can look up. After you've followed the guide you can start one web server followed by more servers run with the -ns command (meaning they only scan for pokemon and update the database with that info).

**Comment by Bizadon** [comment]
Tried to run, had an error:

username cant't be set to a list '[user1, user2, etc.]' unless its action type is changed to 'append'

what to do with it? I edited a config file as in example.

**Comment by wardude202** [comment]
That's because you are using the master build not the dev one

**Comment by Bizadon** [comment]
@wardude202 yep, thx, I'm dummy

**Comment by xioxxio** [comment]
If you use 3 logins, how do you specify the 3 different locations?

Thanks

**Comment by Bizadon** [comment]
@xioxxio by using 3 threads
