### ISSUE TITLE
Google two factor authentication (and some more questions)

### ISSUE THREAD

**Issue by arieljannai** [AHAAAAAAA/PokemonGo-Map#316]
- [x] ~~Is google two factor authentication supported? If so, how to use it with the script?~~ - [Solved](https://github.com/AHAAAAAAA/PokemonGo-Map/issues/316#issuecomment-233595364)
- [ ] I think it's better to allow prompting for password instead of typing it visibly on the command line (saved history etc.).
- [ ] Is it possible to make the program an app that will ask for google basic permissions through google services?
- [ ] Couldn't join the discordapp with the link from the *new issue* template (Error: `The instant invite is invalid or has expired.`)

**Comment by DerScreever** [comment]
like i know two factor is not supported.

**Comment by meersjo** [comment]
In your google account settings, under security, you can create application-specific passwords, so at least you don't have to stick your main password on the commandline. It's a very convenient feature :-)

**Comment by arieljannai** [comment]
@meersjo Thanks!

Here's the link to those settings, if someone else is also interested: https://security.google.com/settings/security/apppasswords

**Comment by Answeroid** [comment]
prompting for password is there actually. If you use something like code below - it will ask you for one:
`python example.py -a ptc -u username -l "Address" -st 5`
