### ISSUE TITLE
Getting Error on Startup

### ISSUE THREAD

**Issue by MinziMinzz** [AHAAAAAAA/PokemonGo-Map#3161]
Everytime I try to start my Map, I get this Error.
The File "pokemon.min.json" does not exists, I tried to rename the File to "pokemon.json", but that does not work.

![startup](https://cloud.githubusercontent.com/assets/1565795/17331900/2e2b1358-58cd-11e6-8805-412694f94588.png)

**Comment by shiona** [comment]
Duplicate of #2979

**Comment by MinziMinzz** [comment]
Thanks mate
