### ISSUE TITLE
OOOPS Something went wrong - java script console error - Do I need new API key?

### ISSUE THREAD

**Issue by LotusLenex** [AHAAAAAAA/PokemonGo-Map#3166]
Sorry..feel like this is an easy fix I'm missing somewhere...

**Comment by peteyb1313** [comment]
Open up the javascript console, what's the error?

**Comment by LotusLenex** [comment]
I switched out my API...pretty sure that was it. Sorry for uneeded issue post here.

If anyone else sees that error on map, check your API..make sure you've got it correct.
