### ISSUE TITLE
External web server

### ISSUE THREAD

**Issue by devian223** [AHAAAAAAA/PokemonGo-Map#318]
Can you elaborate on how to use the  -H parameter for use with an external web server? I have a website with a fixed IP, is it possible to generate the output on there?

**Comment by DerScreever** [comment]
python example.py -u user -p password -l "location" -st 5 -H serverip -P 80 
just insert the ip of your server and it work ^^

**Comment by meersjo** [comment]
-H will have the flask listen on the given IP, so it *is* the webserver. What I do, is to have it listen on localhost, and then use mod_rewrite to proxy the requests in the appropriate vhost:

  RewriteEngine on
  RewriteRule ^/pokemap/(.*) http://localhost:5001/$1 [proxy]
  RewriteRule ^/pokemap      http://localhost:5001    [proxy]

It seems, however, that Flask converts the image urls to absolute paths (although the code seems to request relative ones), so i also need this inconvenient line:

  Alias /static /home/meersjo/git/PokemonGo-Map/static

**Comment by devian223** [comment]
Thanks, will need some adjusting since it is running on Windows Server

**Comment by mel15** [comment]
I tried to access with my phone (android) to my local server and I could do it for a second but then it says an error like this one http://i.stack.imgur.com/bWmy6.png but no idea how to access to my console from the mobile

**Comment by SanderLedegen** [comment]
@mel15 I got the exact same issue when connecting to the server externally. In the console, however, I can read something about exceeding the usage quota. You also get linked to [this page](https://developers.google.com/maps/faq#usage_exceed). Perhaps you need to request an API token yourself? (Just a first guess, haven't worked with Google Maps before..)

**Comment by mel15** [comment]
@SanderLedegen thanks for the answer! knowing that I'm not the only one makes me think that I didn't mess it doing the forward rules...
I don't know really, could be that the app needs some configuration to be able to send information by forwarding, could be that right now blocks that connection.
Because if I'm connected at the same network and I put my computer local ip, I can see it without any error, but no idea :S

**Comment by SanderLedegen** [comment]
@mel15 It seems that API key was indeed the issue :) I requested an API key myself, replaced it with the one already specified in the *credentials.json* file, restarted my server and I'm good to go! I suggest you to do the same thing and if you would need extra help, just check the last link in my last comment. Good luck! ;-)

**Comment by mel15** [comment]
@SanderLedegen thanks a lot!! When I get home, I'll try lo do that :D

**Comment by Vzhik** [comment]
Hi, friend. How can I start it with external ip?
When I wrote my ip address on host I have got exception: The requested adderess is not valid in its context. How can I fix it?

http://grab.by/RB9Q

**Comment by SanderLedegen** [comment]
@Vzhik You should use 0.0.0.0 for the -H argument ;-)
