### ISSUE TITLE
Pokemon clear out when hosting to multiple peers

### ISSUE THREAD

**Issue by Powerfists** [AHAAAAAAA/PokemonGo-Map#3180]
After going live on my site which is only hosted to about 5 friends the radar stops working. I currently have 24 accounts scanning a decent sized area. This worked great for about 3 hours with me accessing it from an external source. As soon as I shared it to a few friends it stops working.

## Expected Behavior
Sharing my radar should not completely remove all pokemon from showing.

## Current Behavior
The parser continues to run but no pokemon are showing on the map

## Possible Solution
no idea.

**Comment by lighter857** [comment]
is this external host or on a local machine?
What if you restart your server on a different port where no one has access... can you see everything again?

**Comment by Powerfists** [comment]
port forwarding to a local machine. 
mysql

and yes, if no one else is loading it, then it works fine.

**Comment by INGY23** [comment]
Are you sure one of your friends isn't setting a different scan area as this will move all the worker processes for that port to the new search area

**Comment by lighter857** [comment]
@Powerfists ... @INGY23  is right... are you sure one of your friends isn't changing the search location?
Run the server disabling the search and see if it still works... if not setup a second worker on a different port and have them connect there and see what happens ....

**Comment by Powerfists** [comment]
how can i disable search changing the search location?

**Comment by Powerfists** [comment]
I have my scanners set up using the -ns command so that they update on the main map. Maybe I should try starting the server with a dummy single scanner, then have all of the others set up to -ns. BRB will try and advise.

**Comment by Powerfists** [comment]
That fixed it. I basically blocked changing location using the command. maps are working perfectly now, no matter how many users. Well at least they were before that big niantic nerf bat hit at 4:30pm est
