### ISSUE TITLE
 runserver.py: error: unrecognized arguments: -1 [location]

### ISSUE THREAD

**Issue by kharmaDawg** [AHAAAAAAA/PokemonGo-Map#3182]
any clue on correcting this?

**Comment by CaitlynMainer** [comment]
It's not a 1 (one) it's an l (lowercase L)

**Comment by JZ6** [comment]
lmao dem memes

**Comment by kharmaDawg** [comment]
and this is where i smack my forehead with my free hand.  Now I will  retire my keyboard and join the crew of Captain Obvious.   Thanks Caitlyn.
