### ISSUE TITLE
Pokemon not showing up in map? (JELASTIC)

### ISSUE THREAD

**Issue by aliamid93** [AHAAAAAAA/PokemonGo-Map#3184]
I have deployed to JELASTIC, but I can't see any pokemons or anything else. Locally, it works just fine.

Is Jelastic banned from using the Niantic API just as AWS ?

**Comment by felixvd** [comment]
Does the console say that any elements have been upserved?

**Comment by aliamid93** [comment]
@felixvd I solved it, it was some ptc account error. Thanks!

**Comment by mrAlexZT** [comment]
@aliamid93 could you please explain in details how did you fix this issue? Thanks!

**Comment by aliamid93** [comment]
@mrAlexZT I had to go to pokemon trainer club website, and log onto my accounts once and log out, and it seems to fixed my problem. But it was still wierd that it worked locally when it wasnt working on Jelastic even thought I used the same ptc accounts
