### ISSUE TITLE
how to use config in latest version?

### ISSUE THREAD

**Issue by atribushny** [AHAAAAAAA/PokemonGo-Map#3186]
does anyone know how to do the simple run  from cmd?

I saved my config, and try to
C:\Pogo>python runserver.py
but it returns:
usage: runserver.py [-h] [-a AUTH_SERVICE] [-u USERNAME] [-p PASSWORD]
                    [-l LOCATION] [-st STEP_LIMIT] [-sd SCAN_DELAY]
                    [-td THREAD_DELAY] [-ld LOGIN_DELAY] [-dc] [-H HOST]
                    [-P PORT] [-L LOCALE] [-c] [-d] [-m] [-ns] [-os] [-fl] -k
                    GMAPS_KEY [-C] [-D DB] [-t NUM_THREADS] [-np] [-ng] [-nk]
                    [--db-type DB_TYPE] [--db-name DB_NAME]
                    [--db-user DB_USER] [--db-pass DB_PASS]
                    [--db-host DB_HOST] [-wh [WEBHOOKS [WEBHOOKS ...]]]
runserver.py: error: arguments -u/--username, -l/--location, -st/--step-limit are required

thanks

**Comment by timlinde** [comment]
Can you post your config?

**Comment by morderous97** [comment]
you are missing the parameters, this is what it should look like 
python runserver.py -a "put the autentication type ptc or google" -u "Put the username" -p "Put the password" -l "coordinates or the address" -st 10 -H 0.0.0.0 -L en -k "Google api key" -t 1

**Comment by snagaduck** [comment]
I've been having the same issues. The old config formatting is different than the new. So far I have not been able to have runserver.py see my variables from my config.ini file.

I even tried statically setting my config file location in pogom/utils.py

I also tried commenting out the CMD in Dockerfile to prevent it from defaulting to help with no variables.

**Comment by timlinde** [comment]
@morderous97 @snagaduck  It seems like you don't understand OP's question. He has saved a config file, so there should be no need for config parameters when running python runserver.py.

**Comment by snagaduck** [comment]
@timlinde It seems you didn't read my comment, because that's exactly what I was also referring to.

**Comment by snagaduck** [comment]
The old config files had formatting like this:
[Authentication]
# ptc or google
Service: google
Username: 
Password: 

[Database]
# Possible values: sqlite, mysql
Type: mysql
# The following are only required if it's not sqlite
Database_Name: pokemongomapdb
Database_User: 
Database_Pass: 
Database_Host:

The new example looks like this:

# Authentication settings
auth-service: google          # ptc (default) or google
username: 
password: 

# Database settings
db-type: mysql
db-host: 127.0.0.1
db-name: pokemongomapdb
db-user: 
db-pass:

**Comment by snagaduck** [comment]
I transcribed all of my data into the new format, and still ran into the same issue. Not sure if the server is even looking in the right location for it's variables. It's error is too generic, just saying it's missing an argument, which is defined in the config.ini. So it either can't see the file, or doesn't understand what it's looking for. I've tried inserting my variables in both formats old and new, still no luck, still digging though.

```
# python runserver.py
usage: runserver.py [-h] [-a AUTH_SERVICE] [-u USERNAME] [-p PASSWORD]
                    [-l LOCATION] [-st STEP_LIMIT] [-sd SCAN_DELAY]
                    [-ld LOGIN_DELAY] [-dc] [-H HOST] [-P PORT] [-L LOCALE]
                    [-c] [-d] [-m] [-ns] [-os] [-nsc] [-fl] -k GMAPS_KEY [-C]
                    [-D DB] [-cd] [-np] [-ng] [-nk] [--db-type DB_TYPE]
                    [--db-name DB_NAME] [--db-user DB_USER]
                    [--db-pass DB_PASS] [--db-host DB_HOST]
                    [--db-max_connections DB_MAX_CONNECTIONS]
                    [-wh [WEBHOOKS [WEBHOOKS ...]]]
runserver.py: error: argument -k/--gmaps-key is required
```

**Comment by morderous97** [comment]
ok my bad, so the config file is saved as "config.ini.EXAMPLE" just remove the ".EXAMPLE" extension and edit it, all lines are commented just remove the "#" and put your data in (i'll put an example)

# Authentication settings
auth-service:ptc       
username: "user"
password: "mypass"

# Database settings
#db-type: sqlite        
#db-host:               
#db-name:               
#db-user:               
#db-pass:               

# Search settings
location: "my location"
#no-gyms:               
#no-pokemon:            
#no-pokestops:          
#num-threads:           
#scan-delay:            
#step-limit:            

# Misc
gmaps-key: my gmaps-key           
#webhook:               

# Webserver settings
#host:                 
#port:

**Comment by timlinde** [comment]
@snagaduck like @morderous97 showed. You are missing this in your config file:
`gmaps-key:` my gmaps-key`

**Comment by morderous97** [comment]
@snagaduck  you can get the gmas api key here https://developers.google.com/maps/documentation/javascript/.
you have to be patience the site got lots of errors

**Comment by snagaduck** [comment]
@timlinde I have all of my variables defined:
```
#Provide Pokemon Go Credentials here. This section must be filled out!

# Authentication settings
auth-service: "google"          # ptc (default) or google
username: 
password: 

# Database settings
db-type: "mysql"
db-host: "127.0.0.1"
db-name: "pokemongomapdb"
db-user: 
db-pass: 

# Search settings
#location:
#no-gyms:               # disables gym scanning (default false)
#no-pokemon:            # disables pokemon scanning (default false)
#no-pokestops:          # disables pokestop scanning (default false)
#num-threads:           # number of search threads (default 1)
#scan-delay:            # default 5
step-limit: "30"           # default 12

# Misc
gmaps-key: "my key"
#webhook:               # webhook URL (including http://)

# Webserver settings
host: "0.0.0.0"
port: "5001"
```

**Comment by morderous97** [comment]
the key is active?

**Comment by snagaduck** [comment]
@morderous97  mine was not a new setup, I had a working install up until I updated this morning. So all of my variables have been verified working.

**Comment by morderous97** [comment]
still not working?

**Comment by snagaduck** [comment]
I actually just figured mine out :( my git clone downloaded master instead of devel. I guess if you download the right thing, you get a working server. Sorry for the hijack. Hope OP figures his out!

**Comment by morderous97** [comment]
no problem mate :)

**Comment by atribushny** [comment]
so my conf is next:
# Authentication settings
#auth-service: ptc         # ptc (default) or google
#username: usernameACC
#password: usernamePWD

# Database settings
#db-type: sqlite        # sqlite (default) or mysql
#db-host:               # required for mysql
#db-name:               # required for mysql
#db-user:               # required for mysql
#db-pass:               # required for mysql

# Search settings
#location: "00.00000, 00.00000"
#no-gyms:               # disables gym scanning (default false)
#no-pokemon:            # disables pokemon scanning (default false)
#no-pokestops:          # disables pokestop scanning (default false)
#num-threads:           # number of search threads (default 1)
#scan-delay:            # default 5
#step-limit: 7           # default 12

# Misc
gmaps-key: AbraKadavra           # your Google Maps API key
#webhook:               # webhook URL (including http://)

# Webserver settings
#host: 88.121.0.01                 # address to listen on (default 127.0.0.1)
#port:                  # port to listen on (default 5000)

**Comment by morderous97** [comment]
@atribushny 

- Authentication settings

**#**auth-service: ptc # ptc (default) or google
**#**username: usernameACC
**#**password: usernamePWD

Database settings

#db-type: sqlite # sqlite (default) or mysql
#db-host: # required for mysql
#db-name: # required for mysql
#db-user: # required for mysql
#db-pass: # required for mysql

Search settings

**#**location: "00.00000, 00.00000"
#no-gyms: # disables gym scanning (default false)
#no-pokemon: # disables pokemon scanning (default false)
#no-pokestops: # disables pokestop scanning (default false)
#num-threads: # number of search threads (default 1)
#scan-delay: # default 5
**#**step-limit: 7 # default 12

Misc

gmaps-key: AbraKadavra # your Google Maps API key
#webhook: # webhook URL (including http://)

Webserver settings

**#**host: 88.121.0.01 # address to listen on (default 127.0.0.1)
**#**port: # port to listen on (default 5000)

the # in bold must be deleted

**Comment by atribushny** [comment]
@morderous97 You're right, I'd found this before your post :) thanks

**Comment by morderous97** [comment]
no probelm :D

**Comment by atribushny** [comment]
@morderous97 
so what's next?
C:\Pogo>python runserver.py
2016-08-03 00:11:40,821 [     runserver] [  ERROR] Could not get a position by name, aborting.
:(

**Comment by snagaduck** [comment]
@atribushny you have no location defined. If you don't want it in your config file, you'll have to specify it on the command line

either python runserver.oy -l "Location, Name"

or add it to the location line, and remove the #

**Comment by atribushny** [comment]
@snagaduck but, it's defined in conf:
location: "46.621834, 32.579131"
I used it in old versions

**Comment by morderous97** [comment]
i had problems whit cordinates, try whit the name like "Somewhere, State"

**Comment by snagaduck** [comment]
@atribushny  try removing the space

**Comment by atribushny** [comment]
@morderous97 I guess , I've found the mistake. we must avoid ", only the digits should be entered like:
location: 46.621834, 32.579131

**Comment by mrwbsn** [comment]
how if the coordinates contains "-" in front of them? -6.3024459,106.8929672 for example

**Comment by rooster** [comment]
So, weirdly - it seems that quotes are not allowed. The parser seems to assume every value is a string already, so I guess it parses the quotes as literal quotes...

Just updated my config file and removed all the quotes and now it is working. Location can be coordinates, and the space after the comma is ok

I didn't find anything about that in the ConfigArgParse docs - I assumed the basic YAML formatting rules at least would apply.
