### ISSUE TITLE
Blank Page #243

### ISSUE THREAD

**Issue by darkcloud784** [AHAAAAAAA/PokemonGo-Map#319]
Reference to Blank Page #243 which was closed.... same issue, updated to newest commit. Not sure why someone closed the issue without referencing what "fixed" it. I see a commit by the person that closed it but the commit didn't actually edit anything other than moving a line of code down one.

**Comment by DerScreever** [comment]
console log or something?

**Comment by darkcloud784** [comment]
Check my previous bug report.... everything is there...

**Comment by mkody** [comment]
Looks working for me. Except there isn't any Pokémons or other markers there. (Maybe related to #325 and other linked issues)

**Comment by NitriKx** [comment]
Same here. Pokémons disapear after ~1h (but all the other markers stay).
[logs.txt](https://github.com/AHAAAAAAA/PokemonGo-Map/files/371451/logs.txt)

**Comment by DerScreever** [comment]
Im sorry, but we dropped the support for the master branch (example.py). 
This branch is deprecated.  
The new branch contains a much cleaner structure so pls report only issues related to the develop branch. 

Your development team
