### ISSUE TITLE
best command for 4 accounts

### ISSUE THREAD

**Issue by amoghh** [AHAAAAAAA/PokemonGo-Map#3193]
Kudos to the developers this works flawlessly. i just had one query. since niantic blocked the no. of requests per second i started using the dev branch with 4 accounts. what is the best command for me to scan in minimum possible time and what is the minimum step delay that i can use. thanks in advance for the replys.

p.s i m working on windows 10 64 bit

**Comment by Paralysing** [comment]
The minimum scan delay is -sd 5, I would suggest using -sd 5.1 for stability.

**Comment by Oricul** [comment]
So, curious... I'm currently running 7 sharing a MySQL database. If you're using -sd 5.1, what are you using for -st?
Currently, I'm using -st 6 -sd 10, but this causes scans to be dated.
I'm looking for the "green zone" for quick scanning over the biggest radius without being immediately detected.

**Comment by Paralysing** [comment]
I use 30 accounts, implemented in the lastes develop -sd 5.1 -st 30

**Comment by Oricul** [comment]
And you get 100% green scans?

**Comment by Paralysing** [comment]
Not 100%, about 75% for me

**Comment by Paralysing** [comment]
But no red scanned areas

**Comment by Oricul** [comment]
Great. Thanks for the information.

**Comment by Oricul** [comment]
Unfortunately, I have the middle areas timing out (going red and disappearing) with those settings. :(

**Comment by Oricul** [comment]
Paralysing, do you have another way I can contact you?

**Comment by Paralysing** [comment]
Sorry, I'm really busy right now, I would suggest using a ptc account generator to generate more accounts, the more accounts and threads, the faster it will be.

**Comment by ChipWolf** [comment]
![](http://i.imgur.com/akflOyf.png)

90 workers (-st 5 -t 1 -sd 5), each with their own account. I'm going to be tweaking the -sd to 10, let's see if there's fewer dead areas

**Comment by amoghh** [comment]
thanks for all the help guys i"l close this issue now
