### ISSUE TITLE
Trouble with updated version

### ISSUE THREAD

**Issue by Maz1n** [AHAAAAAAA/PokemonGo-Map#3194]
Issues after updating older version
## Current Behavior
When I run setup in Easy-Setup folder I get this message Command "python setup.py egg_info" failed with error code 1 in c:\users\kj\appdata\local\temp\pip-build-n5twx2\pyproj\ I have no idea how to fix this issue as I am very new to python. Had no issues installing a previous older version

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used- Python 2.7.12
* Operating System- Win10

**Comment by meliorit** [comment]
I needed Microsoft Visual C++ Compiler for Python 2.7 ( [http://aka.ms/vcpython27](url) ) to resolve this error.

**Comment by Maz1n** [comment]
Thank you very much that has fixed my issue aswell

**Comment by dev-masta** [comment]
This is closed but it's maybe important to someone.
It solved my issue with `Command "python setup.py egg_info" failed with error code 1` too.
The file is 83.8Mb big
