### ISSUE TITLE
Pokestops spawns in a area from South/Southwest to North/Northeast

### ISSUE THREAD

**Issue by haagiboy88** [AHAAAAAAA/PokemonGo-Map#32]
### Environment info
Operating System: Windows 10 64-bit

Installed version of Python: 2.7.12

### Steps to reproduce
1. Run program as normally. You can see the effect easily when having a stepsize of 5

### What have you tried?
1. Changing stepsize, but server was down so I couldn't test the influence on stepsize in terms of west-east size of the mapped area.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by JZ6** [comment]
More samples:
http://imgur.com/0WiLM5B
http://imgur.com/zAVT6um

**Comment by yigitserin** [comment]
Possible solution using this 2d spiral algorithm:

https://gist.github.com/yigitserin/0fdaea1a6c6b5412f87781950ab164e1
