### ISSUE TITLE
config.ini doesn't work

### ISSUE THREAD

**Issue by tonygils** [AHAAAAAAA/PokemonGo-Map#3201]
can someone help me to check my config.ini file?
i got some errors on the file:
runserver.py: error: unrecognized arguments: --Authentication settings --Search settings --Misc

[config.ini.txt](https://github.com/AHAAAAAAA/PokemonGo-Map/files/397967/config.ini.txt)

**Comment by timlinde** [comment]
This:
`username: tonygils,tonygils02,tonygils03,tonygils04`
Should be
`username: [tonygils,tonygils02,tonygils03,tonygils04]`

**Comment by timlinde** [comment]
Did you pull the code from the develop branch?

**Comment by tonygils** [comment]
no the master

**Comment by timlinde** [comment]
Oh.. Then i am not so sure. I don't think the master branch supports multiple accounts but i might be wrong.

**Comment by tonygils** [comment]
i also tried dev, same issue

**Comment by tonygils** [comment]
first: is this right?because this is the first fail.

-Authentication settings
auth-service: [ptc]
username: [tonygils,tonygils02,tonygils03,tonygils04]
password: [xxxx]

**Comment by timlinde** [comment]
No its wrong should be this: 
auth-service: ptc
username: [tonygils,tonygils02,tonygils03,tonygils04]
password: xxxx

**Comment by timlinde** [comment]
You should only use brackets (array) if there are different passwords on each account.

**Comment by Peter22483** [comment]
same prob here, 
username can't be set to a list '[xxx1, xxx2]' unless its action type is changed to 'append'.
running master

**Comment by tonygils** [comment]
Authentication settings
auth-service: ptc
username: [tonygils,tonygils02,tonygils03,tonygils04]
password: xxxxxx

this error:
runserver.py: error: unrecognized arguments: --Authentication settings --Search settings --Misc

so still same error.

in terminal i only say: 
python runserver.py

right?

**Comment by jbouaziz** [comment]
I'm having the same issue as @Peter22483.

**Comment by timlinde** [comment]
Can someone try downloading the develop version and retry? I really don't think master version works with multiple accounts.. I had to swap master to develop myself to get it to work.

**Comment by itapir** [comment]
'Authentication settings' is not an argument but a comment. You should keep the '#' as
#Authetication settings
auth-service: ptc
username: [tonygils,tonygils02,tonygils03,tonygils04]
password: xxxxxx

**Comment by Powerfists** [comment]
remove .txt in your config.ini filename.

**Comment by andrewda** [comment]
@itapir is correct.

**Comment by jbouaziz** [comment]
I'm on the latest version of develop and this is what my config.ini looks like:
```
# Authentication settings
auth-service:ptc
username:[someusername1,someusername2,someusername3,someusername4,someusername5]
password:somepassword
```

Is there anything wrong? it works when I'm only using one user and no brackets.

**Comment by itapir** [comment]
@jbouaziz 
Have you mixed ptc accounts with google accounts in the brackets? what kind of error message did u get?

**Comment by jbouaziz** [comment]
@itapir I'm only using ptc accounts. The error message is:
``` username can't be set to a list '[xxx1, xxx2]' unless its action type is changed to 'append'. ```

**Comment by tonygils** [comment]
works for me!

i remove the # at this line:
# Authentication settings

**Comment by itapir** [comment]
@jbouaziz check your PokemonGo-Map-master\pogom\utils.py.
Do you have 
"parser.add_argument('-u', '--username', help='Username')"
or
"parser.add_argument('-u', '--username', action='append',
                        help='Usernames, one per account.')"

**Comment by Peter22483** [comment]
i got
 parser.add_argument('-u', '--username', help='Username')"
should i change it?

**Comment by itapir** [comment]
@Peter22483 No. It means you are not using the latest develop branch so that you can't use the multi account feature. You should clone the develop branch :
github.com/AHAAAAAAA/PokemonGo-Map/tree/develop

**Comment by jbouaziz** [comment]
@itapir I've updated it to the latest develop and it's working. Thanks!
