### ISSUE TITLE
Question -Beehive Preview?

### ISSUE THREAD

**Issue by Caspiel86** [AHAAAAAAA/PokemonGo-Map#3204]
## Possible Solution
I am trying to maximize my beehive scans. I keep getting a few scan in the water. Instated of me trying different location. Is there a preview site some one has built or any information on a possible beehive preview something. obviously this is just to cut down some time while waiting for the full scan to run and its not important at all

**Comment by ChipWolf** [comment]
Use the mock mode flag on runserver.py, it should fill the map with test data without actually scanning
