### ISSUE TITLE
[Change Request] Remove "Search" in multiusermode

### ISSUE THREAD

**Issue by licklake** [AHAAAAAAA/PokemonGo-Map#3207]
Remove "Search" from the frontend when -fl is set. The -fl flag is mostly used when multiple users are supposed to use the map. 

## Expected Behavior

If -fl is set, nobody should be able to stop the searching.

## Current Behavior

Every user can start/stop the searching
## Possible Solution

Remove "Search" button when -fl is set.

## Your Environment

* Version used: dev build
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): Linux, desktop

**Comment by jfla15** [comment]
There already exists the command -nsc to disable the front-end "search" switch
