### ISSUE TITLE
Probably wrong pokemons appearing

### ISSUE THREAD

**Issue by qbrist** [AHAAAAAAA/PokemonGo-Map#321]
http://i.imgur.com/msYdznG.png

Every time since morning, those pokemons appearing on the map. Always with the same time.
I can't find what's wrong.

**Comment by DerScreever** [comment]
tryed with the latest changes?

**Comment by qbrist** [comment]
pulled 2 commits ago

**Comment by DerScreever** [comment]
retry pls
for me all work. if it not work pls post a log and the command you run.

**Comment by qbrist** [comment]
Ok, I just tested, those pokemons are real, but something wrong with time.
Also they are dissapearing after page reload.

My command: "python example.py -a google -u username -p password -l "Сокол-1, Московская область" -st 5 -dp -dg -ar 5"

**Comment by olipayne** [comment]
They are supposed to disappear when they have expired, pokemon don't stay on the map forever.

**Comment by nborrmann** [comment]
I noticed this too. Sometimes there are pokemon with really odd times. Maybe there is a bug when we calculate the timeOfDespawn.

**Comment by DerScreever** [comment]
Im sorry, but we dropped the support for the master branch (example.py). 
This branch is deprecated.  
The new branch contains a much cleaner structure so pls report only issues related to the develop branch. 

Your development team
