### ISSUE TITLE
No module named Queue

### ISSUE THREAD

**Issue by DJGHOSTS3V3N** [AHAAAAAAA/PokemonGo-Map#3219]
Already checked another issue, (#3086), and have done anything on it and I still encounter problems starting up the server. Here is the problem itself; 

> root@Volvagia:~/PokemonGo-Map# /usr/bin/python ./runserver.py --help
> Traceback (most recent call last):
>   File "./runserver.py", line 14, in <module>
>     from queue import Queue
> ImportError: No module named queue
> 

I'm really fresh out of ideas and don't know what to do. I followed all the instructions regarding the DigitalOcean Deployment and still no success. Help!

**Comment by DJGHOSTS3V3N** [comment]
Nevermind, I ran 

> pip install -r requirements.txt

and I managed to run it.

**Comment by Nokoa** [comment]
when I run that it says: "'pip' is not recognized as an internal or external command,"
