### ISSUE TITLE
Scanner is showing some red, anyway to fix this?

### ISSUE THREAD

**Issue by ryanzab** [AHAAAAAAA/PokemonGo-Map#3225]
Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): Windows 7
 

 -st 7  -t 1 -sd 5 
whats wrong with these settings? It seem to be scanning super far out but not quick enough to refresh the inside. Thanks in advance for any help
![lmdkasm](https://cloud.githubusercontent.com/assets/20804331/17348388/e03bdd96-58e3-11e6-880b-09d32bb25259.jpg)

**Comment by freakjam** [comment]
Scan delay was changed to 10 sec by Niantic. Use -sd 10 for now.

**Comment by Oricul** [comment]
From what I understand, you either need to increase threads, or decrease scan delay. Though, if what freakjam said is true, then there's no point to decreasing scan delay. So I'd just increase threads and decrease step limit.
Maybe try something like... -st 6 -t 2 -sd 10

**Comment by ryanzab** [comment]
Awesome thanks, also I haven't set up multiple account but instead i have been using the same account at multiple locations.. is there a downside to this?

**Comment by Oricul** [comment]
Again, I'm a novice in this area, but if you're referring to PTC or Google Logins for Pokemon GO, then potentially you could be detected more quickly and banned (if not even IP banned for this kind of scanning). That's why people tend to recommend a PTC account creator. 

Though, I'm unsure about using the API multiple times - I would love an answer to that.

**Comment by ryanzab** [comment]
Thats what i'm thinking could happen but it seems to be working pretty solidly. Also for using multiple account do you need a new API key each time? Or is the only thing that changes is the account

**Comment by SOLiNARY** [comment]
u can use the same api key
