### ISSUE TITLE
Documenting effective settings

### ISSUE THREAD

**Issue by 7ESL4** [AHAAAAAAA/PokemonGo-Map#3228]
Can we add a line to the Wiki that shows the most effective settings?  This would avoid issues about -t being too high, -sd being too low, etc.  Thanks!

**Comment by frazahod** [comment]
amen to that

**Comment by 7ESL4** [comment]
So... I added one...  but I don't know if my settings are any good.  Feel free to edit... please?

**Comment by chuyskywalker** [comment]
There are defaults for a reason.

**Comment by 7ESL4** [comment]
I also closed the issue for a reason... if we're being passive aggressive about it.

They code isn't updated when the only switch needed is a change in scan delay.
