### ISSUE TITLE
Unable to install requirements.txt on ubuntu

### ISSUE THREAD

**Issue by Mokhan94** [AHAAAAAAA/PokemonGo-Map#3235]
Running the requirements.txt file on ubuntu and it is not getting past the screenshot below.
![screenshot from 2016-08-02 19-16-51](https://cloud.githubusercontent.com/assets/16256821/17349746/ee780fe0-58e5-11e6-8136-238d4b51f833.png)
![screenshot from 2016-08-02 19-18-30](https://cloud.githubusercontent.com/assets/16256821/17349745/ee77f32a-58e5-11e6-86a2-d6b45f334b7b.png)

Please help.

**Comment by frazahod** [comment]
Did you try sudo -H?

**Comment by Mokhan94** [comment]
I get command not found message.

**Comment by frazahod** [comment]
copy paste terminal output plz

**Comment by Mokhan94** [comment]
muhammad@muhammad-p6-2103w:~/PokemonGo-Map$ sudo -H pip install -r requirements.txt
[sudo] password for muhammad: 
Collecting six==1.10.0 (from -r requirements.txt (line 1))
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting Flask==0.11.1 (from -r requirements.txt (line 2))
  Using cached Flask-0.11.1-py2.py3-none-any.whl
Collecting Jinja2==2.8 (from -r requirements.txt (line 3))
  Using cached Jinja2-2.8-py2.py3-none-any.whl
Collecting MarkupSafe==0.23 (from -r requirements.txt (line 4))
  Using cached MarkupSafe-0.23.tar.gz
Collecting Werkzeug==0.11.10 (from -r requirements.txt (line 5))
  Using cached Werkzeug-0.11.10-py2.py3-none-any.whl
Collecting configargparse==0.10.0 (from -r requirements.txt (line 6))
  Using cached ConfigArgParse-0.10.0.tar.gz
Collecting click==6.6 (from -r requirements.txt (line 7))
  Using cached click-6.6.tar.gz
Collecting itsdangerous==0.24 (from -r requirements.txt (line 8))
  Using cached itsdangerous-0.24.tar.gz
Collecting peewee==2.8.1 (from -r requirements.txt (line 9))
  Using cached peewee-2.8.1.tar.gz
Requirement already satisfied (use --upgrade to upgrade): wsgiref==0.1.2 in /usr/lib/python2.7 (from -r requirements.txt (line 10))
Collecting geopy==1.11.0 (from -r requirements.txt (line 11))
  Using cached geopy-1.11.0-py2.py3-none-any.whl
Collecting protobuf==2.6.1 (from -r requirements.txt (line 12))
  Using cached protobuf-2.6.1.tar.gz

**Comment by Mokhan94** [comment]
Thats what I get up to after I reran it.

**Comment by Mokhan94** [comment]
muhammad@muhammad-p6-2103w:~$ sudo apt-get update
[sudo] password for muhammad: 
Hit:1 http://us.archive.ubuntu.com/ubuntu xenial InRelease
Get:2 http://us.archive.ubuntu.com/ubuntu xenial-updates InRelease [95.7 kB]
Get:3 http://security.ubuntu.com/ubuntu xenial-security InRelease [94.5 kB]    
Hit:4 http://us.archive.ubuntu.com/ubuntu xenial-backports InRelease           
Fetched 190 kB in 0s (361 kB/s)                                                
Reading package lists... Done
muhammad@muhammad-p6-2103w:~$

**Comment by frazahod** [comment]
any progress

**Comment by Mokhan94** [comment]
no. I am just stuck at this position.

**Comment by frazahod** [comment]
So it still stalls at 
"Collecting protobuf==2.6.1 (from -r requirements.txt (line 12))
Using cached protobuf-2.6.1.tar.gz"

**Comment by Mokhan94** [comment]
Yup. I also re downloaded the package but same issue. How can I remove python, pip, and everything else so I can restart this process?

**Comment by danielhampton** [comment]
`python -m pip uninstall pip setuptools` or `pip uninstall pip`

**Comment by frazahod** [comment]
try pip uninstall -r requirements.txt before you do the above

**Comment by Mokhan94** [comment]
muhammad@muhammad-p6-2103w:~$ sudo pip uninstall pip
[sudo] password for muhammad: 
The directory '/home/muhammad/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Not uninstalling pip at /usr/lib/python2.7/dist-packages, outside environment /usr
The directory '/home/muhammad/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
muhammad@muhammad-p6-2103w:~$

**Comment by Mokhan94** [comment]
and it is not letting me uninstall requirements.txt

**Comment by frazahod** [comment]
are you in a VM?

**Comment by Mokhan94** [comment]
no. This is a Ubuntu OS machine.

**Comment by frazahod** [comment]
try a `sudo apt-get upgrade`

**Comment by Mokhan94** [comment]
muhammad@muhammad-p6-2103w:~/PokemonGo-Map$ sudo apt-get upgrade
[sudo] password for muhammad: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  fuse libfuse2 libllvm3.8
3 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/10.4 MB of archives.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
(Reading database ... 180451 files and directories currently installed.)
Preparing to unpack .../fuse_2.9.4-1ubuntu3.1_amd64.deb ...
Unpacking fuse (2.9.4-1ubuntu3.1) over (2.9.4-1ubuntu3) ...
Preparing to unpack .../libfuse2_2.9.4-1ubuntu3.1_amd64.deb ...
Unpacking libfuse2:amd64 (2.9.4-1ubuntu3.1) over (2.9.4-1ubuntu3) ...
Preparing to unpack .../libllvm3.8_1%3a3.8-2ubuntu4_amd64.deb ...
Unpacking libllvm3.8:amd64 (1:3.8-2ubuntu4) over (1:3.8-2ubuntu3) ...
Processing triggers for man-db (2.7.5-1) ...
Processing triggers for libc-bin (2.23-0ubuntu3) ...
Setting up libfuse2:amd64 (2.9.4-1ubuntu3.1) ...
Setting up fuse (2.9.4-1ubuntu3.1) ...
update-initramfs: deferring update (trigger activated)
Setting up libllvm3.8:amd64 (1:3.8-2ubuntu4) ...
Processing triggers for libc-bin (2.23-0ubuntu3) ...
Processing triggers for initramfs-tools (0.122ubuntu8.1) ...
update-initramfs: Generating /boot/initrd.img-4.4.0-31-generic

**Comment by frazahod** [comment]
also do `echo $PATH` and let me see the output

**Comment by frazahod** [comment]
that is all normal for upgrade.

**Comment by Mokhan94** [comment]
/home/muhammad/bin:/home/muhammad/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

**Comment by frazahod** [comment]
how about `pip -V`

**Comment by Mokhan94** [comment]
pip 8.1.2 from /home/muhammad/.local/lib/python2.7/site-packages (python 2.7)

**Comment by frazahod** [comment]
Is it installed there on purpose?

**Comment by Mokhan94** [comment]
I just ran terminal and installed it.

**Comment by frazahod** [comment]
do the thing above then

**Comment by Mokhan94** [comment]
Which are you referring to?

**Comment by frazahod** [comment]
PATH=$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games

**Comment by Mokhan94** [comment]
I just get this. 
muhammad@muhammad-p6-2103w:~$ PATH=$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
muhammad@muhammad-p6-2103w:~$

**Comment by frazahod** [comment]
echo $PATH

**Comment by Mokhan94** [comment]
muhammad@muhammad-p6-2103w:~$ echo $PATH
/home/muhammad/bin:/home/muhammad/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
muhammad@muhammad-p6-2103w:~$

**Comment by frazahod** [comment]
try `PATH=$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games`
and then 
`echo $PATH`

**Comment by Mokhan94** [comment]
muhammad@muhammad-p6-2103w:~$ PATH=$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
muhammad@muhammad-p6-2103w:~$ echo $PATH
/home/muhammad/bin:/home/muhammad/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
muhammad@muhammad-p6-2103w:~$

**Comment by frazahod** [comment]
sorry export is on same line as PATH=$PATH, formatting is messin up

**Comment by Mokhan94** [comment]
So anything I can do? Or do I have to go to win10? lol

**Comment by frazahod** [comment]
did you try with export in front?

**Comment by Mokhan94** [comment]
muhammad@muhammad-p6-2103w:~$ PATH=$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games export
declare -x CLUTTER_IM_MODULE="xim"
declare -x COMPIZ_CONFIG_PROFILE="ubuntu"
declare -x DBUS_SESSION_BUS_ADDRESS="unix:abstract=/tmp/dbus-IFD6YAIHE3"
declare -x DEFAULTS_PATH="/usr/share/gconf/ubuntu.default.path"
declare -x DESKTOP_SESSION="ubuntu"
declare -x DISPLAY=":0"
declare -x GDMSESSION="ubuntu"
declare -x GDM_LANG="en_US"
declare -x GNOME_DESKTOP_SESSION_ID="this-is-deprecated"
declare -x GNOME_KEYRING_CONTROL=""
declare -x GNOME_KEYRING_PID=""
declare -x GPG_AGENT_INFO="/home/muhammad/.gnupg/S.gpg-agent:0:1"
declare -x GTK2_MODULES="overlay-scrollbar"
declare -x GTK_IM_MODULE="ibus"
declare -x GTK_MODULES="gail:atk-bridge:unity-gtk-module"
declare -x HOME="/home/muhammad"
declare -x IM_CONFIG_PHASE="1"
declare -x INSTANCE=""
declare -x JOB="dbus"
declare -x LANG="en_US.UTF-8"
declare -x LANGUAGE="en_US"
declare -x LESSCLOSE="/usr/bin/lesspipe %s %s"
declare -x LESSOPEN="| /usr/bin/lesspipe %s"
declare -x LOGNAME="muhammad"
declare -x LS_COLORS="rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:"
declare -x MANDATORY_PATH="/usr/share/gconf/ubuntu.mandatory.path"
declare -x OLDPWD
declare -x PATH="/home/muhammad/bin:/home/muhammad/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
declare -x PWD="/home/muhammad"
declare -x QT4_IM_MODULE="xim"
declare -x QT_ACCESSIBILITY="1"
declare -x QT_IM_MODULE="ibus"
declare -x QT_LINUX_ACCESSIBILITY_ALWAYS_ON="1"
declare -x QT_QPA_PLATFORMTHEME="appmenu-qt5"
declare -x SESSION="ubuntu"
declare -x SESSIONTYPE="gnome-session"
declare -x SESSION_MANAGER="local/muhammad-p6-2103w:@/tmp/.ICE-unix/2918,unix/muhammad-p6-2103w:/tmp/.ICE-unix/2918"
declare -x SHELL="/bin/bash"
declare -x SHLVL="1"
declare -x SSH_AUTH_SOCK="/run/user/1000/keyring/ssh"
declare -x TERM="xterm-256color"
declare -x UPSTART_SESSION="unix:abstract=/com/ubuntu/upstart-session/1000/2695"
declare -x USER="muhammad"
declare -x VTE_VERSION="4205"
declare -x WINDOWID="54525962"
declare -x XAUTHORITY="/home/muhammad/.Xauthority"
declare -x XDG_CONFIG_DIRS="/etc/xdg/xdg-ubuntu:/usr/share/upstart/xdg:/etc/xdg"
declare -x XDG_CURRENT_DESKTOP="Unity"
declare -x XDG_DATA_DIRS="/usr/share/ubuntu:/usr/share/gnome:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop"
declare -x XDG_GREETER_DATA_DIR="/var/lib/lightdm-data/muhammad"
declare -x XDG_MENU_PREFIX="gnome-"
declare -x XDG_RUNTIME_DIR="/run/user/1000"
declare -x XDG_SEAT="seat0"
declare -x XDG_SEAT_PATH="/org/freedesktop/DisplayManager/Seat0"
declare -x XDG_SESSION_DESKTOP="ubuntu"
declare -x XDG_SESSION_ID="c2"
declare -x XDG_SESSION_PATH="/org/freedesktop/DisplayManager/Session0"
declare -x XDG_SESSION_TYPE="x11"
declare -x XDG_VTNR="7"
declare -x XMODIFIERS="@im=ibus"
muhammad@muhammad-p6-2103w:~$

**Comment by frazahod** [comment]
do this ` export PATH=$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games`

**Comment by Mokhan94** [comment]
muhammad@muhammad-p6-2103w:~$ export PATH=$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games
muhammad@muhammad-p6-2103w:~$ 
Nothing still

**Comment by Mokhan94** [comment]
muhammad@muhammad-p6-2103w:~$ echo $PATH
/home/muhammad/bin:/home/muhammad/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games

**Comment by frazahod** [comment]
this is weird. try `export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games`
then `echo $PATH`

**Comment by frazahod** [comment]
that should do it I think. I forgot that the previous command appends the new stuff rather than replacing it.

**Comment by Mokhan94** [comment]
muhammad@muhammad-p6-2103w:~$ export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games
muhammad@muhammad-p6-2103w:~$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games

**Comment by frazahod** [comment]
fantastic now try `python -V`

**Comment by Mokhan94** [comment]
muhammad@muhammad-p6-2103w:~$ python -V
Python 2.7.12

**Comment by frazahod** [comment]
and `pip-V`

**Comment by Mokhan94** [comment]
muhammad@muhammad-p6-2103w:~$ pip -V
pip 8.1.1 from /usr/lib/python2.7/dist-packages (python 2.7)

**Comment by frazahod** [comment]
perfect now try the install from requirements.txt again

**Comment by frazahod** [comment]
lemme know what happens

**Comment by Mokhan94** [comment]
Bad new. Same thing.....

**Comment by frazahod** [comment]
can I see output?

**Comment by Mokhan94** [comment]
muhammad@muhammad-p6-2103w:~/Downloads/PokemonGo-Map-master$ sudo -H pip install -r requirements.txt
[sudo] password for muhammad: 
Collecting Flask==0.11.1 (from -r requirements.txt (line 1))
  Using cached Flask-0.11.1-py2.py3-none-any.whl
Collecting Jinja2==2.8 (from -r requirements.txt (line 2))
  Using cached Jinja2-2.8-py2.py3-none-any.whl
Collecting MarkupSafe==0.23 (from -r requirements.txt (line 3))
  Using cached MarkupSafe-0.23.tar.gz
Collecting Werkzeug==0.11.10 (from -r requirements.txt (line 4))
  Using cached Werkzeug-0.11.10-py2.py3-none-any.whl
Collecting configargparse==0.10.0 (from -r requirements.txt (line 5))
  Using cached ConfigArgParse-0.10.0.tar.gz
Collecting click==6.6 (from -r requirements.txt (line 6))
  Using cached click-6.6.tar.gz
Collecting itsdangerous==0.24 (from -r requirements.txt (line 7))
  Using cached itsdangerous-0.24.tar.gz
Collecting peewee==2.8.1 (from -r requirements.txt (line 8))
  Using cached peewee-2.8.1.tar.gz
Requirement already satisfied (use --upgrade to upgrade): wsgiref==0.1.2 in /usr/lib/python2.7 (from -r requirements.txt (line 9))
Collecting geopy==1.11.0 (from -r requirements.txt (line 10))
  Using cached geopy-1.11.0-py2.py3-none-any.whl
Collecting protobuf==2.6.1 (from -r requirements.txt (line 11))
  Using cached protobuf-2.6.1.tar.gz

**Comment by Mokhan94** [comment]
I think I should try reinstalling Python and Pip. Not sure which command I should use though?

**Comment by frazahod** [comment]
python and pip are fine I suspect. let me see the contents of `/usr/lib/python2.7` ( just use `ls /usr/lib/python2.7`)

**Comment by Mokhan94** [comment]
muhammad@muhammad-p6-2103w:~$ ls /usr/lib/python2.7
_abcoll.py               htmllib.py             shelve.py
_abcoll.pyc              HTMLParser.py          shlex.py
abc.py                   HTMLParser.pyc         shlex.pyc
abc.pyc                  httplib.py             shutil.py
aifc.py                  httplib.pyc            shutil.pyc
antigravity.py           ihooks.py              SimpleHTTPServer.py
anydbm.py                imaplib.py             SimpleXMLRPCServer.py
argparse.egg-info        imghdr.py              sitecustomize.py
argparse.py              importlib              sitecustomize.pyc
ast.py                   imputil.py             site.py
ast.pyc                  inspect.py             site.pyc
asynchat.py              inspect.pyc            smtpd.py
asyncore.py              io.py                  smtplib.py
atexit.py                io.pyc                 sndhdr.py
atexit.pyc               json                   socket.py
audiodev.py              keyword.py             socket.pyc
base64.py                keyword.pyc            SocketServer.py
base64.pyc               lib2to3                SocketServer.pyc
BaseHTTPServer.py        lib-dynload            sqlite3
Bastion.py               lib-tk                 sre_compile.py
bdb.py                   LICENSE.txt            sre_compile.pyc
binhex.py                linecache.py           sre_constants.py
bisect.py                linecache.pyc          sre_constants.pyc
bisect.pyc               locale.py              sre_parse.py
bsddb                    locale.pyc             sre_parse.pyc
calendar.py              logging                sre.py
calendar.pyc             _LWPCookieJar.py       ssl.py
CGIHTTPServer.py         _LWPCookieJar.pyc      ssl.pyc
cgi.py                   macpath.py             stat.py
cgi.pyc                  macurl2path.py         stat.pyc
cgitb.py                 mailbox.py             statvfs.py
chunk.py                 mailcap.py             StringIO.py
cmd.py                   markupbase.py          StringIO.pyc
codecs.py                markupbase.pyc         stringold.py
codecs.pyc               md5.py                 stringprep.py
codeop.py                mhlib.py               stringprep.pyc
code.py                  mimetools.py           string.py
collections.py           mimetools.pyc          string.pyc
collections.pyc          mimetypes.py           _strptime.py
colorsys.py              mimetypes.pyc          _strptime.pyc
commands.py              MimeWriter.py          struct.py
compileall.py            mimify.py              struct.pyc
compileall.pyc           modulefinder.py        subprocess.py
compiler                 _MozillaCookieJar.py   subprocess.pyc
ConfigParser.py          _MozillaCookieJar.pyc  sunaudio.py
ConfigParser.pyc         multifile.py           sunau.py
config-x86_64-linux-gnu  multiprocessing        symbol.py
contextlib.py            mutex.py               symtable.py
contextlib.pyc           netrc.py               _sysconfigdata.py
cookielib.py             new.py                 _sysconfigdata.pyc
cookielib.pyc            nntplib.py             sysconfig.py
Cookie.py                ntpath.py              sysconfig.pyc
Cookie.pyc               nturl2path.py          tabnanny.py
copy.py                  numbers.py             tarfile.py
copy.pyc                 numbers.pyc            tarfile.pyc
copy_reg.py              opcode.py              telnetlib.py
copy_reg.pyc             opcode.pyc             tempfile.py
cProfile.py              optparse.py            tempfile.pyc
csv.py                   optparse.pyc           test
csv.pyc                  os2emxpath.py          textwrap.py
ctypes                   os.py                  textwrap.pyc
curses                   os.pyc                 this.py
dbhash.py                _osx_support.py        _threading_local.py
decimal.py               pdb.doc                threading.py
decimal.pyc              pdb.py                 threading.pyc
difflib.py               __phello__.foo.py      timeit.py
difflib.pyc              pickle.py              toaiff.py
dircache.py              pickle.pyc             tokenize.py
dis.py                   pickletools.py         tokenize.pyc
dis.pyc                  pipes.py               token.py
dist-packages            pkgutil.py             token.pyc
distutils                pkgutil.pyc            traceback.py
doctest.py               platform.py            traceback.pyc
DocXMLRPCServer.py       platform.pyc           trace.py
dumbdbm.py               plat-x86_64-linux-gnu  tty.py
dummy_threading.py       plistlib.py            types.py
dummy_thread.py          plistlib.pyc           types.pyc
email                    popen2.py              unittest
encodings                poplib.py              urllib2.py
ensurepip                posixfile.py           urllib2.pyc
filecmp.py               posixpath.py           urllib.py
fileinput.py             posixpath.pyc          urllib.pyc
fnmatch.py               pprint.py              urlparse.py
fnmatch.pyc              pprint.pyc             urlparse.pyc
formatter.py             profile.py             UserDict.py
fpformat.py              pstats.py              UserDict.pyc
fractions.py             pty.py                 UserList.py
ftplib.py                pyclbr.py              user.py
functools.py             py_compile.py          UserString.py
functools.pyc            py_compile.pyc         uuid.py
__future__.py            pydoc_data             uuid.pyc
__future__.pyc           pydoc.py               uu.py
genericpath.py           _pyio.py               uu.pyc
genericpath.pyc          Queue.py               warnings.py
getopt.py                Queue.pyc              warnings.pyc
getopt.pyc               quopri.py              wave.py
getpass.py               quopri.pyc             weakref.py
getpass.pyc              random.py              weakref.pyc
gettext.py               random.pyc             _weakrefset.py
gettext.pyc              repr.py                _weakrefset.pyc
glob.py                  re.py                  webbrowser.py
glob.pyc                 re.pyc                 whichdb.py
gzip.py                  rexec.py               wsgiref
gzip.pyc                 rfc822.py              wsgiref.egg-info
hashlib.py               rfc822.pyc             xdrlib.py
hashlib.pyc              rlcompleter.py         xml
heapq.py                 robotparser.py         xmllib.py
heapq.pyc                runpy.py               xmlrpclib.py
hmac.py                  runpy.pyc              xmlrpclib.pyc
hmac.pyc                 sched.py               zipfile.py
hotshot                  sets.py                zipfile.pyc
htmlentitydefs.py        sgmllib.py
htmlentitydefs.pyc       sha.py
muhammad@muhammad-p6-2103w:~$

**Comment by frazahod** [comment]
try `sudo apt-get install --reinstall python`

**Comment by Mokhan94** [comment]
Done
muhammad@muhammad-p6-2103w:~$ sudo apt-get install --reinstall python
[sudo] password for muhammad: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 0 not upgraded.
Need to get 137 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 python amd64 2.7.11-1 [137 kB]
Fetched 137 kB in 0s (711 kB/s)
(Reading database ... 180451 files and directories currently installed.)
Preparing to unpack .../python_2.7.11-1_amd64.deb ...
Unpacking python (2.7.11-1) over (2.7.11-1) ...
Processing triggers for doc-base (0.10.7) ...
Processing 1 changed doc-base file...
Processing triggers for man-db (2.7.5-1) ...
Setting up python (2.7.11-1) ...
muhammad@muhammad-p6-2103w:~$

**Comment by frazahod** [comment]
now `sudo reboot` and when it boots back in try to install from requirements.txt again. that may work, but if not you may need to do a clean install of Ubuntu

**Comment by Mokhan94** [comment]
Not working. I will do a clean install now. Thanks alot for you help man, do you have some more proper steps on how I should install this for next time. The ones on the Wiki are not detailed. 

Thanks,

**Comment by frazahod** [comment]
On my ubuntu server I literally did this
`apt install git nodejs npm python-pip nodejs-legacy python-dev
git clone -b develop https://github.com/AHAAAAAAA/PokemonGo-Map.git
cd PokemonGo-Map/
pip install -r requirements.txt
npm install
npm install -g grunt-cli
npm install node-sass
grunt build`

so clean install maybe and give that a try? Or for about 5 bucks a month you can get a Digital Ocean server that is really quick and easy to get this running on and lets you view the map from where ever you wan.t

**Comment by Mokhan94** [comment]
Did you run those code one at a time? Also did you run the terminal from the desktop? And nah, I'm creating an app and wanted to host my own radar. I already did it successfully on win 10, I'm just new to Ubuntu so having some trouble that's all. Wish me luck.

**Comment by Mokhan94** [comment]
thanks man. Having the same issue. Just going to go with windows 10 on this one.
