### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by Herwi** [AHAAAAAAA/PokemonGo-Map#324]
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discordapp.com/invite/qbpVH6b).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System: Ubuntu

Installed version of Python: 2.7

### Steps to reproduce
1. python example.py -a ptc -u ******* -p ******* -l "Mogilno" -st 8 -H 91.189.36.16 -P 1234 -dp -dg

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

Exception in thread search_thread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 505, in run
    self.__target(*self.__args, **self.__kwargs)
  File "example.py", line 613, in main
    pokemonsJSON, ignore, only)
  File "example.py", line 633, in process_step
    print('[+] Searching for Pok'+u'\xe9'+'mon at location {} {}'.format(FLOAT_LAT, FLOAT_LONG))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 21: ordinal not in range(128)

**Comment by TrickTrick** [comment]
i have too this bug

**Comment by DerScreever** [comment]
fixed already. 
try the latest version pls

**Comment by Herwi** [comment]
works
