### ISSUE TITLE
Noob question here - how do I get developer working? I have master working already.

### ISSUE THREAD

**Issue by Riffles** [AHAAAAAAA/PokemonGo-Map#3240]
Sorry for the extremely noob question, I'm just learning all this stuff, but, I'm a little confused as to how to use the develop build i cloned. I try "python runserver.py --help" on the  master build and I get a return, but, when I do the same on developer I get an [Errno 2] No such file or directory for runserver.py. Can someone tell me what I have to do to get this up and running?

Another question, how should it look when I put multiple runserver.py lines down to create multiple points on my map? Can someone put and example of maybe 3 lines worth for 3 fake accounts so I know how it should be copy pasted into the command prompt?

Thanks in advance!

**Comment by cdhowie** [comment]
Both branches seem to accept the same options, or darn near the same.  Please post the exact error message you get when running the develop branch.  It's likely that you forgot a step when deploying it.

**Comment by Riffles** [comment]
![pogo error2](https://cloud.githubusercontent.com/assets/20785901/17350668/7e6dbcfc-58dd-11e6-8e28-5ce6242907fb.png)

Maybe I did forget a step. I feel like I'm doing the exact same thing as I was attempting with the master to get that one working though :(

**Comment by Riffles** [comment]
![pogo error2](https://cloud.githubusercontent.com/assets/20785901/17350694/b01b07a0-58dd-11e6-845d-e2fb30475a78.png)

Maybe I did miss a step, but I feel like I've done the exact same things to get master working. Developer is just giving me problems though :(

**Comment by cdhowie** [comment]
Looks like the script just plain isn't there, which would indicate that Git didn't correctly check out the develop branch.  Does `ls` show other files?  Have you tried `grunt build`?

If all else fails, `git reset --hard && grunt build` and try again.  Pay particular attention to errors from Git.

**Comment by Riffles** [comment]
Wow, Howie.

So basically I'm retarded and I was GitBashing the pokemongo-dev folder not realizing there was another pokemongo-dev folder that had all the contents inside it. Thank you so much, you made me realize that I didn't check out the branch properly. 

Much obliged, sir! :+1:

**Comment by GenuineSounds** [comment]
@Riffles Close your issue if you figured it out.
