### ISSUE TITLE
How does one start a no server scan with multiple accounts?

### ISSUE THREAD

**Issue by skeldoor** [AHAAAAAAA/PokemonGo-Map#3243]
I have everything set up fine. I can access my map fine. 

`runserver.py -a ptc -u user1 -p pass -st .... etc`

On the new develop build, how do I go about starting a scan with multiple users instead of just user1?

I wanna do this from the terminal so no config editing because that's too static

Thanks for any help

**Comment by timlinde** [comment]
`runserver.py -a ptc -u user1 -p pass -u user2 -p pass2 -st .... etc`

**Comment by skeldoor** [comment]
Is that really it? What if they all have the same pass? Seems strange

**Comment by timlinde** [comment]
`runserver.py -a ptc -u user1 -u user2 -p samepassword -st .... etc`
Yep thats it.

**Comment by piplar** [comment]
Hey, 
I have some other questions, I know i should start my own issue and wait for responses but I'm looking for some people who dont mind answering some questions.

**Comment by skeldoor** [comment]
Go go go

**Comment by piplar** [comment]
Ok thank you. 

Im going to start off by saying im a noob lol i have ios dev background and swift but this is my first time working on stuff like this. 

I am using python 27 and at first played around with maps version 1,0, then decided to get the API key needed and this is the code im writing. 

`runserver.py -a Google -u USER -p PASS -l LOCATION -st STEPS -k API `KEY`

I am running my local host and the page opens, i see the options board on the left but the map wont load and im getting an error saying oops something went wrong, google maps did not load correctly, see javascript console for technical details. 

I should also add, I am using my command prompt inside the poke map 2.1 folder to do this. 

Let me know if I've explained this properly. 

Thanks in advance for the much needed help.

**Comment by piplar** [comment]
Basically I want to make a poke tracking website for myself and my brother to simultaneously use, where the location scans where we drop the location marker. So I'm just having some trouble figuring out some stuff..... lol

**Comment by skeldoor** [comment]
Assuming you're on chrome, if you right click the map area and click inspect and then go to console, what are the errors?

**Comment by piplar** [comment]
![image](https://cloud.githubusercontent.com/assets/20805289/17351424/558457be-58fc-11e6-89e7-f52bee689a8a.png)

It says my API key is wrong, I was reading through another github page on google maps services and was directed to obtain a server key. is this correct?

**Comment by piplar** [comment]
Thanks for the hint on the java console by the way

**Comment by piplar** [comment]
![image](https://cloud.githubusercontent.com/assets/20805289/17351544/a112db50-58fd-11e6-9b42-9eef289b8a7e.png)

I just tried a browser API key from google and this is the error im now getting.

**Comment by piplar** [comment]
New error saying the server API key is not activated either

**Comment by piplar** [comment]
Sorry for the bombardment of msgs

**Comment by skeldoor** [comment]
Go in to google api console

go to library 

click and enable:

Google Maps Geocoding API
Google Maps Geolocation API
Google Maps JavaScript API
Google Places API Web Service

Should work then

**Comment by piplar** [comment]
wow youre amazing man! thanks so much! 

haha youre my first and so far only friend on github lmao!!

**Comment by piplar** [comment]
can i bother you with a few more questions?

**Comment by skeldoor** [comment]
Ok but we should really be closing this thread soon haha

**Comment by piplar** [comment]
Haha ok if we close it now, is there another way we can communicate? 

Regards, 
Nicholas Paldino 
647-296-5390

**Comment by piplar** [comment]
ok we can close the thread, but can we communicate any other way? 

I just have some more "advanced" questions for me but "basic" questions for you lol..

**Comment by skeldoor** [comment]
Email me at contact@pokesear.ch
