### ISSUE TITLE
Long Run Issue

### ISSUE THREAD

**Issue by sandsaber** [AHAAAAAAA/PokemonGo-Map#325]
Hi,

I noticed, that after long time, like 30min-1h of running, everything disappear from map and no new pokemon appear, there are will be just empty map. Maybe I missed some kind of settings?
using:
python example.py -a PTC -u **** -p ***** -l "59.435544, 24.746575" -st 5 -ol -ar 10 -dg

**Comment by benemorius** [comment]
any console output?

**Comment by XoneFobic** [comment]
Same issue, both terminal and browser console say nothing out of the ordinary.

**Comment by sandsaber** [comment]
Yup, but, I have feel, that it's does not running steps anymore. So main loop stopped, but I could not find anything good in console :(

**Comment by DerScreever** [comment]
now i can reproduce.
but when i lock into the console log there is nothing unnormal :/

**Comment by nborrmann** [comment]
This has also been disussed in #294.

**Comment by nborrmann** [comment]
It's weird. It does add new pokemon occasionally, but after an hour nothing is there anymore. I suspect it is because of the client side js detection of duplicates using only the SpawnId.

**Comment by nikos90** [comment]
@nborrmann no that's not the case.
`for hh in hs:
        try:
            for cell in hh.cells:
                for wild in cell.WildPokemon:`

the problem is there, the hh.cells are empty. 
checking the heartbeat response now..

**Comment by DerScreever** [comment]
Im sorry, but we dropped the support for the master branch (example.py). 
This branch is deprecated.  
The new branch contains a much cleaner structure so pls report only issues related to the develop branch. 

Your development team
