### ISSUE TITLE
Docker setup - Running ngrok issue

### ISSUE THREAD

**Issue by ladymPokeD** [AHAAAAAAA/PokemonGo-Map#3252]
Hello all,

I follow the wiki but unable to setup ngrok to docker.

Please advise?

I follow the instruction:

docker run -d -p 4040 \
   --link pogomap-timessquare \
   --name ngrok-timessquare wernight/ngrok \
    ngrok http pogomap-timessquare:5000

The docker terminal gives me unknown number:

d741127b6ffefc677eb7281bef4af00957740aa32869c7659c4735c10aeb3971

**Comment by chuyskywalker** [comment]
That's letting you know the container started. Read the rest of [said wiki page](https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Docker).
