### ISSUE TITLE
Map not loading corectly

### ISSUE THREAD

**Issue by cheezitupp** [AHAAAAAAA/PokemonGo-Map#3253]
Instead of the map loading, I get a simpler HTML version, without a map.

A screenshot of localhost:5000 is [here](http://prnt.sc/c0xf3w)

I've tried loading the page with Microsoft edge and chrome on windows.

Each time I have gotten the same problem

If anyone has a fix for this, your help is appreciated. Thanks in advance.

**Comment by c133** [comment]
Try adding -H 0.0.0.0 -P 80 at the end of all of your commands

**Comment by spidervalve100** [comment]
Im in the same boat. My guess is it is something to do with grunt-sass not loading correctly. Tried what c133 suggested and still no dice.

**Comment by andrewda** [comment]
Looks like you didn't generate the CSS and JS using grunt. Try typing `grunt buiold in console. If that still has no effect, take a screenshot of your developer console.

**Comment by MrKetchumAll** [comment]
Try a different pokemon go map. The one with "stat" on the right didn't work for me. Good luck.

**Comment by koruitch** [comment]
Similar problem in windows 10 64bits.

**Comment by cheezitupp** [comment]
Going to the pokemon go map version 2.1.0 fixed it, but I can only use threads and not multiple accounts on that so I'll try c133's suggestion on the developer version

**Comment by cheezitupp** [comment]
Now, when I run the developer version, it says please run grunt build before starting the server, so the developer version no longer works for me, but the other one does. It may be painfully slow, but it works.
