### ISSUE TITLE
I really need some guidence setting up sqlite3 for the first time  

### ISSUE THREAD

**Issue by dadime69** [AHAAAAAAA/PokemonGo-Map#3256]
I don't know how to build the sqlite3db can you help???
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment sqlite3/Macbookpro iOS 10.12 Sierra 

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by JZ6** [comment]
Please read the wiki
