### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by akkatracker** [AHAAAAAAA/PokemonGo-Map#326]
A python 3 version would be nice 😄

**Comment by chuparCh0pper** [comment]
Do you have problems running the script?
You can install python3 and python2 parallel and run this script using pyhton2
`py -2 example.py ...`

**Comment by marauder37** [comment]
I tried to do a Python 3-compat version, it got stuck on the protobufs bit. There is currently a lot of magic numbers and bit-packing and other nonsense that makes it work. I'll take another look after the next big refactorings land.
