### ISSUE TITLE
Change scan area on running server

### ISSUE THREAD

**Issue by sgsayson** [AHAAAAAAA/PokemonGo-Map#3261]
I used to be able to change the scan area on a running server by searching or dragging the dropped pin. Currently, I am able to change the scan area temporarily; however, next time I reopen the browser/webapp, it reverts back to the original location set within the config.ini.

## Expected Behavior

Permanent scan location change.

## Current Behavior

Temporary location scan change. Location scan reverts back to defined location in config.ini after reopening browser/webapp.

## Steps to Reproduce (for bugs)

1. Change location.
2. Close webapp (iOS)
3. Reopen webapp.
4.

## Your Environment

* Version used: develop #3173 
* Environment name and version (e.g. Python 2.7): 
* Operating System and version (desktop or mobile): Mobile webapp iOS

**Comment by g5bEM6RpSbQF** [comment]
Duplicate of https://github.com/AHAAAAAAA/PokemonGo-Map/issues/3212

**Comment by sgsayson** [comment]
closing. duplicate of #3212.
