### ISSUE TITLE
Hexagon step coordinates design

### ISSUE THREAD

**Issue by sirdumpty** [AHAAAAAAA/PokemonGo-Map#3266]
I've been doing trial and error with my coordinates selection, currently i'm scanning 3 different locations with some overlap.

I was wondering if there was a site that can help me sign a better scan map by showing me what my scan hexagon will look like and how much overlap there will be?

**Comment by andikatanpah** [comment]
hi, i was created simulation.. but it's manual hexagon (no overlap). You can change step limit and radius..
https://jsfiddle.net/Kr3Mb1Z/Lqo303w9/
just click the cordinat, and if done click get maker

**Comment by Harachteh** [comment]
you can use the Hex-Beehive-Generator to get exact locations for your scans with minimal overlap. It's in the Tools folder. For more info check the wiki https://jonaharagon.github.io/PoGoMapWiki/#!beehive.md
