### ISSUE TITLE
Anyone using Google Cloud? (not a issue)

### ISSUE THREAD

**Issue by DomGrieco** [AHAAAAAAA/PokemonGo-Map#3268]
As the title says. I'm with Digital Ocean but I'm preparing ahead of time to move host. I believe the Pokemon Go servers are hosted on google cloud in Cali. I'm wondering if they blocked out Google Cloud.

**Comment by zumbrunnen** [comment]
I've got an instance up and running on GCC in a EU data center. Works perfectly. :+1:

**Comment by DomGrieco** [comment]
Awesome, good to know. Thanks!

**Comment by blackhattristar** [comment]
Are there any tutorials on how to set this up in Google Cloud? That would be great for the Wiki.

**Comment by Silvikk** [comment]
@zumbrunnen hey, man! could help us to deploy it into the google cloud?

**Comment by zumbrunnen** [comment]
In general, it's the same as described here: https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/DigitalOcean-Deployment

- create a VM (from Ubuntu 16.04 image)
- open Firewall ports (e.g. 50000 or 80 or whatever you use)
- clone, install and configure app (see also [here](https://github.com/AHAAAAAAA/PokemonGo-Map/wiki#how-to-get-it-up--running-grunt-included-on-a-fresh-ubuntu-1604-vpsvm-root-is-implied))
- start it

Further, I've set up an Apache web server as a reverse proxy.

**Comment by Silvikk** [comment]
@zumbrunnen Thanks!
