### ISSUE TITLE
Am i getting a IP ban?

### ISSUE THREAD

**Issue by MrARM** [AHAAAAAAA/PokemonGo-Map#3276]
## Expected Behavior

The map will login correctly, both on PTC and google
## Current Behavior

[      auth_ptc] [   INFO] PTC login for: **********
[      auth_ptc] [   INFO] PTC Login successful
[       rpc_api] [WARNING] Unexpected HTTP server response - needs 200 got 403
## Possible Solution

Proxies or more debugging. like a verbose option
## Steps to Reproduce (for bugs)

Run the map on one account for a few days, eventually it will stop working and not login. 
Tested on 3 accounts, git pulled for each new account.

## Context

I cannot use the map on the server i have.
## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):
I tried first with a python2.7 ubuntu 14.04 VPS on 1.0.0, Heroku on 2.0.0 and 2.1.0 using the deploy to heroku button on the first one and then forking and deploying later. The new PTC account has just been setup.

**Comment by Marve1337** [comment]
Yes AWS/Azure/DO and others are IP banned on their major blocks.

**Comment by MrARM** [comment]
Ok, i was just making sure.
Since i have considered hosting from my home network if all else fails.
