### ISSUE TITLE
ImportError: No module named LatLon

### ISSUE THREAD

**Issue by juliusrucker25** [AHAAAAAAA/PokemonGo-Map#3277]
## Expected Behavior
Terminal should output a list of coordinates according to this https://jonaharagon.github.io/PoGoMapWiki/#!beehive.md

## Current Behavior
 python location_generator.py -st 5 -lp 4 -lat "36.329360" -lon "-119.646816"
Traceback (most recent call last):
  File "location_generator.py", line 3, in <module>
    import LatLon
ImportError: No module named LatLon

## Possible Solution
No Idea. Noobie. Tried searching for help but couldn't find anything relevant .

## Steps to Reproduce (for bugs)
N/A

## Context
Trying to use the guide provided for Beehive

## Your Environment

Latest dev branch
Windows 10

**Comment by Paralysing** [comment]
pip install LatLon

**Comment by juliusrucker25** [comment]
Got it but now i'm struggling on what to do next:

https://github.com/AHAAAAAAA/PokemonGo-Map/blob/develop/Tools/Hex-Beehive-Generator/Instructions%20for%20location_generator.txt

Line 16 & 19 show [-o OUTPUT] [--accounts ACCOUNTS] [--auth AUTH] but on the updated guide here https://jonaharagon.github.io/PoGoMapWiki/#!beehive.md there's none of that. What is the next step?

**Comment by Steelerbacks** [comment]
When I run my python location_generator.py -st 5 -lp 4 -lat XXXXXXX -lon -XXXXXX, git says that it's 'Generating beehive script to ../../beehive.sh but when I open that file in the Hex-Beehive-Generator, this is all that it contains: "nohup python ../../runserver.py -os -l ', ' &"
