### ISSUE TITLE
Trying to Auto Run my cmd's 

### ISSUE THREAD

**Issue by ryanzab** [AHAAAAAAA/PokemonGo-Map#3284]
## Current Behavior
I created a .bat file to try and  run all of my locations so I don't have to do it manually but when I try this it doesn't work. It say its not recognized as an internal or external command. But if I type them in one by one then it's fine.
## Your Environment
Python 2.7
Windows 7

**Comment by InflamedSebi** [comment]
please close #3281 #3282 #3283 and just update on this one.

**Comment by ryanzab** [comment]
Sorry accidentally hit enter as I was typing the title not sure why it made a bunch of them.

**Comment by ryanzab** [comment]
C:\Users\ZAB>\PokemonGo-Map-master>C:\Python27\python.exe runserver.py -a ptc -u
 sername -p asswordi -l  loaction -st
6 -H 0.0.0.0 -L en -t 2 -sd 5.1 -k  -P72
'\PokemonGo-Map-master' is not recognized as an internal or external command,
operable program or batch file.

**Comment by Gammoria** [comment]
I have multiple batch files for running maps and killing all maps. This is a general example of one that I use. This is by no means the best way or the cleanest / most efficient code. It works for me without errors. This runs 1 web server and 3 scanners. I use this for 3 different locations that are near one another. 

Change the PythonInit variable to include your path for your python installation if you don't have it in your PATH environment variable already. [Here is a link on how to do that](http://pythoncentral.io/add-python-to-path-python-is-not-recognized-as-an-internal-or-external-command/). 

The "Title" after START changes the title bar of the spawned python instances so that I get a clear view of which one is which. If you're only running one, It's not really necessary to title it.



```
@echo off

: Server and User Settings
REM Initializating the servers
SET PythonInit="python runserver.py"

REM Users and Passwords
SET User1="XXXXXX@gmail.com"
SET Pass1="********"
SET User2="XXXXXX@gmail.com"
SET Pass2="********"
SET User3="XXXXXX@gmail.com"
SET Pass3="********"


REM Locations for the maps
SET Loc1="Location"
SET Loc2="Location2"
SET Loc3="Location3"

REM Server Settings
SET NumSteps="4"
SET ScanDelay="5"
SET Threads="1"

:-----------------------------

REM Change directory to where the map is
cd "C:\Users\Charles\Desktop\PokeMap\PokemonGo-Map"

REM WebServer
START "Title1" %PythonInit% -a google -u %User1% -p %Pass1% -l %Loc1% -os -H 0.0.0.0 -P 5000

REM Scanner1
START "Title1" %PythonInit% -a google -u %User1% -p %Pass1% -l %Loc1% -ns -st %NumSteps% -sd %ScanDelay% -t %Threads%

REM Scanner2
START "Title2" %PythonInit% -a google -u %User2% -p %Pass2% -l %Loc2% -ns -st %NumSteps% -sd %ScanDelay% -t %Threads%

REM Scanner3 
START "Title3" %PythonInit% -a google -u %User3% -p %Pass3% -l %Loc3% -ns -st %NumSteps% -sd %ScanDelay% -t %Threads%

exit
```

**Comment by ryanzab** [comment]
So right now i'm manually opening the command from the master folder and dragging python 27 into it, then pasting into it and it runs
` runserver.py -a ptc -u username-p psswd -l "location" -st 6 -H 0.0.0.0 -L en -t 2 -sd 5.1 -k api -P84
`
but then i have 50 friggin cmd windows open. is there anyway to make it so it'll just run them all at once?

**Comment by Gammoria** [comment]
Do you mean can you run all 50 from one batch file? Or run all 50 in a single cmd window?

**Comment by ryanzab** [comment]
id prefer both but at this point i just want to be able to run 50 from one batch

**Comment by InflamedSebi** [comment]
For now, each location needs his own cmd window (i suggested a change here #3160)
**How many locations do you want to scan?**

First of all, running with higher than -t 1 will cause some pokemon to not show up. Same with lower than -sd 5. So theese are the recommended values. Also each scanner must use his own account or some pokemon will be missing again.

The latest develop branch supportes multiple accounts per scanner, to speed it up.
if you use less then 50 locations it might be worth switching to the develop branch.

**Comment by ryanzab** [comment]
so basically I have to open up each one individually?

**Comment by itapir** [comment]
For the first question, the batch can work like this:
C:\Python27\python.exe C:\Users\ZAB\PokemonGo-Map-master\runserver.py -a ptc -u
sername........

**Comment by Gammoria** [comment]
Running 50 from one batch is very possible. You can run all of them using something similar to what I linked earlier. You'd just have to make a variable for each user, pass, and location. Then you'd have to copy and paste the line to run the scanners 50 times.

I'm sure there's a way to do this with a FOR loop so you don't have to copy and paste and edit 50 times, but from my 20 minutes of research and attempts I don't know enough to do it.

**Comment by InflamedSebi** [comment]
updated https://github.com/AHAAAAAAA/PokemonGo-Map/issues/3284#issuecomment-237178376
there are many ways to do it, but it depends on:
- the amount of accounts you have ?
- the amount of locations you want to scan ?

**Comment by ryanzab** [comment]
itapir it says runserver.py is not recognized and inflamed sebi around 50 is what im gunna be aiming for.3

**Comment by InflamedSebi** [comment]
50 accounts and 3 locations ?
then you should use the development branch anyway
and the use (@Gammoria 's script with some minor changes): (dev branch only)

```
@echo off

REM Initializating the servers
SET PythonInit="python runserver.py"

REM Users and Passwords
SET User1="-a ptc -u user1 -p pass1"
SET User2="-a ptc -u user2 -p pass2"
SET User3="-a ptc -u user3 -p pass3"

REM Locations for the maps
SET Loc1="Location1"
SET Loc2="Location2"

REM Server Settings
SET Settings1="-st 4 -sd 5"
SET Settings2="-st 5 -sd 5"

REM Change directory to where the map is
cd "C:\Users\Charles\Desktop\PokeMap\PokemonGo-Map"

REM WebServer
START "Webserver" %PythonInit% %User1% -l %Loc1% -os -H 0.0.0.0 -P 5000

REM Scanner
START "Scanner1" %PythonInit% %User1% -l %Loc1% -ns %Settings1%
START "Scanner2" %PythonInit% %User2% %User3% -l %Loc2% -ns %Settings2%

exit
```

at the scanner line, you cann add as many users as you want.

**Comment by ryanzab** [comment]
So now im getting an error when running the easy setup for dev branch

**Comment by ryanzab** [comment]
SO i set up this file after figuring out how to switch to dev branch now when i set all this code up, i get cannot runserver.py

**Comment by ryanzab** [comment]
Now i dont get that error but nothing happens at all now anothwr cmd pops open for a second then both close.

**Comment by InflamedSebi** [comment]
open command line.
use `cd` to navigate into your pokemon map folder
then run `python runserver.py -h`

**Comment by ryanzab** [comment]
so why does python runserver.py -h work but when I try to click my .bat file it says python runserver.py cant be found.

**Comment by InflamedSebi** [comment]
did you adjust the path inside the bat file?

´´´Batch
REM Change directory to where the map is
cd "C:\Users\Charles\Desktop\PokeMap\PokemonGo-Map"
´´´

**Comment by ryanzab** [comment]
`REM Change directory to where the map is
cd "C:\Users\ZAB\Desktop\PokemonGo-Map-develop"
 is this correct?`

**Comment by InflamedSebi** [comment]
seems to be ok ...
change the exit in the bat file to a 'pause'
and tell the error please

**Comment by ryanzab** [comment]
``REM Initializing Servers
SET PythonInit="python runserver.py"

REM Users and Passwords
Set User1="-a ptc -u sername user1 -p assword"

REM Locations for the maps
SET Loc1="location"
SET Loc2="Location2"

REM Server Settings
SET Settings1="-st 6 -sd 5.1 "
SET Settings2="-st 6 -sd 5.1 -ns"

REM Change directory to where the map is
cd "C:\Users\ZAB\Desktop\PokemonGo-Map-develop"

REM Webserver
Start "Webserver" %PythonInit% %User1 -l %Loc1% -os -H 0.0.0.0 -P 5000

REM Scanner
START "Scanner1" %PythonInit% %Settings1% -l %Loc1% %User1%
pause

```

Thats my code and it says the systhem cannot find file python runserver.py

**Comment by InflamedSebi** [comment]
than the path is not ok.
the map is inside a folder called 'PokemonGo-Map-develop' on your desktop?

**Comment by ryanzab** [comment]
by map what do you mean?

**Comment by InflamedSebi** [comment]
runserver.py

**Comment by ryanzab** [comment]
Yes its inside the developer branch i just extracted that folder to my desktop

**Comment by InflamedSebi** [comment]
thats strange ... do you use teamviever or join.me, so i can have a look ?

**Comment by ryanzab** [comment]
will download one second

**Comment by ryanzab** [comment]
teamviewer id 949914975

**Comment by ryanzab** [comment]
hey

**Comment by InflamedSebi** [comment]
oh -sd changed ... its now 10, not 5 ...
so map is much slower now ...
