### ISSUE TITLE
Add a public changelog

### ISSUE THREAD

**Issue by DevAndArtist** [AHAAAAAAA/PokemonGo-Map#3289]
## Current Behavior

People that do not work with git are just downloading the whole repository and try to run the server like it's described in wiki. They have no clue what has been changed after they come back here after a week. There is no hint what has been improved in general. 

## Possible Solution

Add a public changelog with all the improvements and changes made on the master branch.

**Comment by freakjam** [comment]
https://jonaharagon.github.io/PoGoMapWiki/#!index.md

**Comment by JZ6** [comment]
Master changes are documented, dev you need to read commits

**Comment by DevAndArtist** [comment]
@freakjam @JZ6 Great, I missed that one! Thanks.
