### ISSUE TITLE
Hide caught pokemon

### ISSUE THREAD

**Issue by itztq** [AHAAAAAAA/PokemonGo-Map#3296]
Whenever we caught a pokemon, a new thing we can introduce is: to (temp) hide the pokemons  after catching it. 

## Expected Behavior
1. Spot pokemon
2. Catching the pokemon
3.Click caught pokemon
4. Pokemon hide

## Current Behavior
If a Pokemon is caught  it still will be on the rader and this can sometimes be confusing.

## Possible Solution
Option to hide or click caught Pokemon.

## Your Environment
Im not a dev. this is just a option and im thinking how can we improve the map options.

**Comment by hack3rjack** [comment]
There is already an option when clicking the pokemon to remove them from the map (without excluding them from future searches). Just click that and it will remove them from the map...I use this all the time. 

![remove](https://cloud.githubusercontent.com/assets/20573875/17365514/5e258138-593b-11e6-84a9-f13dd5ee2f21.JPG)

**Comment by itztq** [comment]
@hack3rjack really! I thought that removing was the same thing as hiding! thanks..
