### ISSUE TITLE
Best Alternative to heroku

### ISSUE THREAD

**Issue by Faskill** [AHAAAAAAA/PokemonGo-Map#3306]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by aliamid93** [comment]
I am using Jelastic and it's working fine. I've also heard some people recommend Digital Ocean.

**Comment by patrocle** [comment]
Scaleway ;-)
