### ISSUE TITLE
Best Alternatives to Heroku

### ISSUE THREAD

**Issue by Faskill** [AHAAAAAAA/PokemonGo-Map#3307]
What would you advice as an easy to setup alternative to Heroku?
I've seen on another thread that people advice localtunnel and ngrok, is that still working since the update?

As I am a novice user, I would also appreciate it if you could quickly describe how to install what you advice

Thanks in advance !

Edit : please delete the other issue

**Comment by HanSolo80** [comment]
You can use IBM Bluemix modifying the manifest.yml file. See here: https://jonaharagon.github.io/PoGoMapWiki/#!bluemix.md

**Comment by cirespieler** [comment]
ngrok is pretty easy if you are somewhat familiar with terminal, it's one simple command to get it going.
If you're using the master branch, Scalingo works pretty well. You get a month for free and it's pretty much exactly the same as Heroku.

**Comment by cirespieler** [comment]
Or you could use the desktop version which has ngrok built in, the electron wrapper makes it pretty easy.

**Comment by Faskill** [comment]
Thanks a lot for your answers !

I'm currently using the master branch, but I was wondering if I should install the dev branch, as updates are more frequent, would that be better for me?

I was under the assumption that I was already using the desktop version, unless it is separate from the zip I downloaded in the master branch

I am not familiar with terminal, but if it's only for one command I should be able to handle it, I'm a fast learner

Does ngrok support several instances being used at once? I saw a post here indicating otherwise

I will look into it and Scalingo and keep you posted
