### ISSUE TITLE
eslint SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by blindreaper** [AHAAAAAAA/PokemonGo-Map#3309]
Currently on the develop branch

> $grunt build
> 
> /home/user/PokemonGo-Map/node_modules/grunt-eslint/tasks/eslint.js:2
> const chalk = require('chalk');
> ^^^^^
> Loading "eslint.js" tasks...ERROR
> >> SyntaxError: Use of const in strict mode.

**Comment by jbouaziz** [comment]
Me too, it was working yesterday.

**Comment by vaurdan** [comment]
I had the same problem. You need to update your nodejs version to at least v4.4.7. This version was introduced in #2748.

**Comment by invisiblek** [comment]
grunt build works

running grunt alone fails

**Comment by invisiblek** [comment]
https://github.com/AHAAAAAAA/PokemonGo-Map/pull/3351
