### ISSUE TITLE
print '[-] {}'.format(message) SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by ZombiePm** [AHAAAAAAA/PokemonGo-Map#331]
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discordapp.com/invite/qbpVH6b).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System: Windows 8.1

Installed version of Python: 3.5.2

### Steps to reproduce
run python example.py -a ptc -u ****** -p ****** -l "Some Location" -st 10

### What have you tried?
  File "example.py", line 103
    print '[-] {}'.format(message)
                 ^
SyntaxError: invalid syntax

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by gkarlos** [comment]
You are using the wrong python version (3.5.2). You need 2.7.x

**Comment by ZombiePm** [comment]
thanks for help
