### ISSUE TITLE
grunt build not work

### ISSUE THREAD

**Issue by BoGnY** [AHAAAAAAA/PokemonGo-Map#3310]
I`ve just install latest nodejs and npm version.. but not work.. 
Anyone have some idea??

> $ npm install
> 
> > pogomap@0.1.0 postinstall C:\Luca\PokemonGO\map
> > grunt build
> 
> Loading "eslint.js" tasks...ERROR
> >> Error: Cannot find module './scope-manager'
> Loading "babel.js" tasks...ERROR
> >> Error: Cannot find module 'core-js/library/fn/symbol/iterator'
> 
> Running "clean:build" (clean) task
> >> 0 paths cleaned.
> Warning: Task "babel" not found. Use --force to continue.
> 
> Aborted due to warnings.
> 
> npm ERR! Windows_NT 10.0.10586
> npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
> npm ERR! node v6.3.1
> npm ERR! npm  v3.10.3
> npm ERR! code ELIFECYCLE
> npm ERR! pogomap@0.1.0 postinstall: `grunt build`
> npm ERR! Exit status 3
> npm ERR!
> npm ERR! Failed at the pogomap@0.1.0 postinstall script 'grunt build'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the pogomap package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     grunt build
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs pogomap
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls pogomap
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     C:\Luca\PokemonGO\map\npm-debug.log

## Your Environment

* Version used: latest develop branch 5e1bec1724efb9e5b1486346e5a1dc1dd6b0907f
* Environment name and version (e.g. Python 2.7): Python 2.7.12 NodeJS 6.3.1 npm 3.10.3
* Operating System and version (desktop or mobile): Windows 10 64bit

[npm-debug.txt](https://github.com/AHAAAAAAA/PokemonGo-Map/files/399300/npm-debug.txt)

**Comment by ELusiveLPFAN** [comment]
[RTFM](https://github.com/AHAAAAAAA/PokemonGo-Map/wiki)

**Comment by MrKetchumAll** [comment]
Look through the "issues" or google it. There were quite a bit of people who had the same problem, including myself. I actually just got done fixing it. I did a lot of things, so I don't know even know what really fixed the problem lol.

**Comment by cirespieler** [comment]
Try deleting node-modules folder and building grunt again.

**Comment by BoGnY** [comment]
Thanks, I've tried to delete node_modules folder a few hours ago and worked..
Problem was a previously wrong installation of `npm install` command!

;)
