### ISSUE TITLE
How to find more pokemons

### ISSUE THREAD

**Issue by GreeZlyZavr** [AHAAAAAAA/PokemonGo-Map#3312]
Hello, I have some questions about pokemap. Does anyone know how to improve researching of pokemons? I ask because on my map always about 15 pokemons but I use string with -st 10 and I suppouse that 10 is very much. What is more, in the centre of my city there are a lot of people but there are also few pokemons I can see...
All string : runserver.py -a ptc -u *** -p *** -l "***" -st 10 -H 0.0.0.0 -L en -sd 5 -t 3 -k "***"
If I don't use -t 3 it will become laggy and I use -k with the same reasone. Does this program have any flags which help me to find ONLY pokemons and to improve perfomance? 
Sorry for my English)))

**Comment by Bizadon** [comment]
I if rightly understood about usung multithread function - 1 account for 3 threads is not enoung, try to use -t 1 and -st 4, for your local area it is enough, I just dont understand how to use multiple accounts too

**Comment by GreeZlyZavr** [comment]
Oh, is -t multiple accounts? Really? I thought it is just how mach the program check each circle on the map... I little bit stupid in this XD

**Comment by GreeZlyZavr** [comment]
Ok, I tried to look how much pokemons in Santa Monika so there are as much as on the video but they appeared realy slow. Maybe the reason is that I use laptop and it's weak??? What can I do???

**Comment by InflamedSebi** [comment]
`-sd` is the delay between scans. everything lower than 5 will cause some pokemon to not show up.
`-t` is the number of threads. -t 2 would send 2 requests per scan. but everything higher than 1 will also cause some pokemon to not show up. thats why it got removed in the develop branch.
I would recommend switching to the develop branch (neccesary for multiple accounts)
and then use:
`python runserver.py -a ptc -u user1 -p pass1 -a ptc -u user2 -p pass2 -l location -st 10 -H 0.0.0.0 -L en -sd 5  -k blabalakeylblalala`
as you see, you can use multiple accounts by just adding `-a ptc -u user -p pass` over and over again.
but you could also use the config file #3155

**Comment by daaaaa** [comment]
Is is faster to provide multiple account on a single location or using Hex-Beehive and provides one account for each script generated (assuming to cover a similar area with both methods)?

**Comment by GreeZlyZavr** [comment]
ok, thank you gays, I think the problem is that I don't live in Santa Monica ))))

**Comment by BenVlodgi** [comment]
@GreeZlyZavr your real life proximity to the city will not affect the scanning speed. All this data is stored on Niantic's servers, each request being made (no matter where for) is only communicating with Niantic's Servers.

**Comment by InflamedSebi** [comment]
@daaaaa every account can scan 1 circle every 5 seconds. So it doesn't matter if your area is one giant hex or a few smaller ones. It just depends on the total amount of circles to scan.
As a formula:
t = time in seconds needed to scan your area
a = amount of accounts
c = amount of circles
```
       c * 5 
t  =   ----- 
         a   
```
