### ISSUE TITLE
change from master to develop

### ISSUE THREAD

**Issue by dirkpoetter** [AHAAAAAAA/PokemonGo-Map#3320]
So i just tried to figure out how things work. I just installed the master 2 days ago without any problems.
Today i did some research and saw that some of my issues could be solved with dev brand.

So i downloaded the dev zip. extracted it, opened folder, opend command and wanted to install. but when i hit install  following error occurs: (i didn't changed anything in the config, because i didn't had to with master)

**d (Unable to find vcvarsall.bat). Get it from http://aka.ms/vcpython27

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\****\ap
pdata\local\temp\pip-build-tl3uzr\pyproj\

C:\Users\****\Desktop\PokemonGo-Map-develop>**

Might be a newbie mistake, but couldnt find help in researching other issues.

**Comment by forsakenzombi** [comment]
same issue

**Comment by Grifan** [comment]
try method from Syndiction [3141](https://github.com/AHAAAAAAA/PokemonGo-Map/issues/3141)

**Comment by forsakenzombi** [comment]
Grifan that looks entirely unrelated however Dirkpoetter I think I figured it out. 

Go here and download Visual C++ Compiler For Python 2.7 https://www.microsoft.com/en-us/download/details.aspx?id=44266

After I installed that i ran "C:\Python27\Scripts\pip2.7.exe" install -r requirements.txt in development folder again and got more errors but it popped up something i needed to install so i hit yes then on the next try after that i successfully had everything installed.

**Comment by dirkpoetter** [comment]
Thank you, Ok so far so good. It worked. But when i try to start the server now it shows: 

2016-08-03 15:14:51,898 [      MainThread][     runserver][CRITICAL] Please run
"grunt build" before starting the server

i am completly new to this, so dont blame me. I walked through the video tutorial when i startetd with master and all was fine, i didnt had to do something with grunt. Can someone pls tell me how to install grunt build?

**Comment by WtfJoke** [comment]
Download this: https://nodejs.org/en/download/
then open a cmd
write:

1. npm install -g grunt-cli
2. npm install
3. grunt build

If you have any errors write here agian.

**Comment by forsakenzombi** [comment]
Where do we open cmd from? Am I in the right directory? 

C:\PokemonGo-Map-develop>npm install -g grunt -cli
'npm' is not recognized as an internal or external command,
operable program or batch file.

**Comment by forsakenzombi** [comment]
nevermind i figured out system32 worked but I got this error 

C:\WINDOWS\system32>npm install -g grunt-cli
C:\Users\admin\AppData\Roaming\npm\grunt -> C:\Users\admin\AppData\Roaming\npm\node_modules\grunt-cli\bin\grunt
grunt-cli@1.2.0 C:\Users\admin\AppData\Roaming\npm\node_modules\grunt-cli
├── grunt-known-options@1.1.0
├── nopt@3.0.6 (abbrev@1.0.9)
├── resolve@1.1.7
└── findup-sync@0.3.0 (glob@5.0.15)

C:\WINDOWS\system32>npm install
npm ERR! install Couldn't read dependencies
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! path C:\WINDOWS\system32\package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! package.json ENOENT: no such file or directory, open 'C:\WINDOWS\system32\package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\WINDOWS\system32\npm-debug.log

C:\WINDOWS\system32>

**Comment by dirkpoetter** [comment]
Step 1. npm install -g grunt -cli was succesfull (opened in generall windows command)
Step 2:

C:\Users\Andre>npm install
npm ERR! install Couldn't read dependencies
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! path C:\Users\Andre\package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! package.json ENOENT: no such file or directory, open 'C:\Users\Andre\pa
ckage.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directo
ry.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Andre\npm-debug.log

**Comment by Grifan** [comment]
> If you have any errors write here agian.
I downloaded  [nodeJS v4.4.7 LTS](https://nodejs.org/en/). Istalled it and reinstalled requirements.txt. Thenin the same cmd run command: npm install. 
Now all work fine. Thanks a lot.
P.S. Sorry for my English. I'm not native speaker
![hhhh](https://cloud.githubusercontent.com/assets/9806610/17368665/b4250c9a-599d-11e6-978a-cf8a739e2765.png)

**Comment by forsakenzombi** [comment]
C:\PokemonGo-Map-develop>npm install
'npm' is not recognized as an internal or external command,
operable program or batch file.

npm commands do not seem to work..... so confused

**Comment by dirkpoetter** [comment]
try to install "install -r requirements.txt" in your folder again, and when finished just type "npm install" in that same command window. Worked for me

**Comment by forsakenzombi** [comment]
i tried that already I jsut get a error that npm is not a recognized command in that folder


C:\PokemonGo-Map-develop>"C:\Python27\Scripts\pip2.7.exe" install -r requirements.txt
Requirement already satisfied (use --upgrade to upgrade): six==1.10.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): Flask==0.11.1 in c:\python27\lib\site-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): Jinja2==2.8 in c:\python27\lib\site-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe==0.23 in c:\python27\lib\site-packages (from -r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): Werkzeug==0.11.10 in c:\python27\lib\site-packages (from -r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): configargparse==0.10.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): click==6.6 in c:\python27\lib\site-packages (from -r requirements.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): itsdangerous==0.24 in c:\python27\lib\site-packages (from -r requirements.txt (line 8))
Requirement already satisfied (use --upgrade to upgrade): peewee==2.8.1 in c:\python27\lib\site-packages (from -r requirements.txt (line 9))
Requirement already satisfied (use --upgrade to upgrade): wsgiref==0.1.2 in c:\python27\lib\site-packages (from -r requirements.txt (line 10))
Requirement already satisfied (use --upgrade to upgrade): geopy==1.11.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 11))
Requirement already satisfied (use --upgrade to upgrade): protobuf==2.6.1 in c:\python27\lib\site-packages (from -r requirements.txt (line 12))
Requirement already satisfied (use --upgrade to upgrade): requests==2.10.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 13))
Requirement already satisfied (use --upgrade to upgrade): s2sphere==0.2.4 in c:\python27\lib\site-packages (from -r requirements.txt (line 14))
Requirement already satisfied (use --upgrade to upgrade): gpsoauth==0.3.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 15))
Requirement already satisfied (use --upgrade to upgrade): protobuf-to-dict==0.1.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 16))
Requirement already satisfied (use --upgrade to upgrade): PyMySQL==0.7.5 in c:\python27\lib\site-packages (from -r requirements.txt (line 17))
Requirement already satisfied (use --upgrade to upgrade): flask-cors==2.1.2 in c:\python27\lib\site-packages (from -r requirements.txt (line 18))
Requirement already satisfied (use --upgrade to upgrade): flask-compress==1.3.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 19))
Requirement already satisfied (use --upgrade to upgrade): LatLon==1.0.1 in c:\python27\lib\site-packages (from -r requirements.txt (line 20))
Requirement already satisfied (use --upgrade to upgrade): setuptools in c:\python27\lib\site-packages (from protobuf==2.6.1->-r requirements.txt (line 12))
Requirement already satisfied (use --upgrade to upgrade): future in c:\python27\lib\site-packages (from s2sphere==0.2.4->-r requirements.txt (line 14))
Requirement already satisfied (use --upgrade to upgrade): pycryptodomex>=3.0 in c:\python27\lib\site-packages (from gpsoauth==0.3.0->-r requirements.txt (line 15))
Requirement already satisfied (use --upgrade to upgrade): pyproj in c:\python27\lib\site-packages (from LatLon==1.0.1->-r requirements.txt (line 20))

C:\PokemonGo-Map-develop>npm install
'npm' is not recognized as an internal or external command,
operable program or batch file.

C:\PokemonGo-Map-develop>

**Comment by forsakenzombi** [comment]
nevermind. I didnt know I had to restart my cmd window to get the command npm to be recognized.

**Comment by dirkpoetter** [comment]
how do you know if "npm install" is ready?

**Comment by forsakenzombi** [comment]
what do you mean? Before I was getting 

C:\PokemonGo-Map-develop>npm install
'npm' is not recognized as an internal or external command,
operable program or batch file.

I closed the cmd window and reopened it and tried the command again and got this

C:\PokemonGo-Map-develop>npm install
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
-
> node-sass@3.8.0 install C:\PokemonGo-Map-develop\node_modules\grunt-sass\node_modules\node-sass
> node scripts/install.js

Binary downloaded and installed at C:\PokemonGo-Map-develop\node_modules\grunt-sass\node_modules\node-sass\vendor\win32-x64-46\binding.node

> node-sass@3.8.0 postinstall C:\PokemonGo-Map-develop\node_modules\grunt-sass\node_modules\node-sass
> node scripts/build.js

"C:\PokemonGo-Map-develop\node_modules\grunt-sass\node_modules\node-sass\vendor\win32-x64-46\binding.node" exists.
 testing binary.
Binary is fine; exiting.

> pogomap@0.1.0 postinstall C:\PokemonGo-Map-develop
> grunt build

Running "clean:build" (clean) task
>> 0 paths cleaned.

Running "babel:dist" (babel) task

Running "uglify:build" (uglify) task
>> 5 sourcemaps created.
>> 5 files created.

Running "minjson:build" (minjson) task
File "static\dist\data\pokemon.min.json" created: 85.94 kB → 55.45 kB
File "static\dist\data\mapstyle.min.json" created: 293 B → 255 B
File "static\dist\locales\de.min.json" created: 18.81 kB → 15.79 kB
File "static\dist\locales\fr.min.json" created: 19.13 kB → 16.12 kB
File "static\dist\locales\pt_br.min.json" created: 17.3 kB → 14.49 kB
File "static\dist\locales\ru.min.json" created: 18.21 kB → 15.23 kB
File "static\dist\locales\zh_cn.min.json" created: 15.29 kB → 12.32 kB
File "static\dist\locales\zh_hk.min.json" created: 17.96 kB → 14.35 kB

Running "sass:dist" (sass) task

Running "cssmin:build" (cssmin) task
>> 3 files created. 52.13 kB → 37.93 kB

Done, without errors.
eslint-config-standard@5.3.5 node_modules\eslint-config-standard

eslint-plugin-standard@2.0.0 node_modules\eslint-plugin-standard

eslint-plugin-promise@2.0.0 node_modules\eslint-plugin-promise

grunt-include-file@0.1.1 node_modules\grunt-include-file

grunt-contrib-copy@1.0.0 node_modules\grunt-contrib-copy
├── file-sync-cmp@0.1.1
└── chalk@1.1.3 (escape-string-regexp@1.0.5, ansi-styles@2.2.1, supports-color@2.0.0, strip-ansi@3.0.1, has-ansi@2.0.0)

grunt-eslint@19.0.0 node_modules\grunt-eslint
└── chalk@1.1.3 (escape-string-regexp@1.0.5, ansi-styles@2.2.1, supports-color@2.0.0, strip-ansi@3.0.1, has-ansi@2.0.0)

grunt-contrib-concat@1.0.1 node_modules\grunt-contrib-concat
├── source-map@0.5.6
└── chalk@1.1.3 (ansi-styles@2.2.1, escape-string-regexp@1.0.5, supports-color@2.0.0, strip-ansi@3.0.1, has-ansi@2.0.0)

grunt-minjson@0.4.0 node_modules\grunt-minjson
└── maxmin@2.1.0 (figures@1.7.0, pretty-bytes@3.0.1, gzip-size@3.0.0, chalk@1.1.3)

grunt-cli@1.2.0 node_modules\grunt-cli
├── grunt-known-options@1.1.0
├── nopt@3.0.6 (abbrev@1.0.9)
├── findup-sync@0.3.0 (glob@5.0.15)
└── resolve@1.1.7

grunt-contrib-clean@1.0.0 node_modules\grunt-contrib-clean
├── async@1.5.2
└── rimraf@2.5.4 (glob@7.0.5)

grunt-legacssy@0.4.0 node_modules\grunt-legacssy
├── chalk@0.4.0 (ansi-styles@1.0.0, has-color@0.1.7, strip-ansi@0.1.1)
├── css@1.6.0 (css-parse@1.7.0, css-stringify@1.4.1)
└── maxmin@0.1.0 (pretty-bytes@0.1.2, gzip-size@0.1.1)

grunt-html-validation@0.1.18 node_modules\grunt-html-validation
├── colors@0.6.2
├── request@2.34.0 (forever-agent@0.5.2, aws-sign2@0.5.0, tunnel-agent@0.3.0, oauth-sign@0.3.0, qs@0.6.6, mime@1.2.11, json-stringify-safe@5.0.1, tough-cookie@2.3.1, node-uuid@1.4.7, http-signature@0.10.1, form-data@0.1.4, hawk@1.0.0)
└── w3cjs@0.1.25 (commander@2.0.0, superagent@0.15.7, superagent-proxy@0.2.0)

grunt@0.4.5 node_modules\grunt
├── eventemitter2@0.4.14
├── dateformat@1.0.2-1.2.3
├── getobject@0.1.0
├── colors@0.6.2
├── which@1.0.9
├── async@0.1.22
├── lodash@0.9.2
├── rimraf@2.2.8
├── hooker@0.2.3
├── grunt-legacy-util@0.2.0
├── exit@0.1.2
├── nopt@1.0.10 (abbrev@1.0.9)
├── coffee-script@1.3.3
├── iconv-lite@0.2.11
├── underscore.string@2.2.1
├── minimatch@0.2.14 (sigmund@1.0.1, lru-cache@2.7.3)
├── glob@3.1.21 (inherits@1.0.2, graceful-fs@1.2.3)
├── grunt-legacy-log@0.1.3 (grunt-legacy-log-utils@0.1.1, lodash@2.4.2, underscore.string@2.3.3)
├── findup-sync@0.1.3 (lodash@2.4.2, glob@3.2.11)
└── js-yaml@2.0.5 (esprima@1.0.4, argparse@0.1.16)

grunt-contrib-connect@1.0.2 node_modules\grunt-contrib-connect
├── connect-livereload@0.5.4
├── async@1.5.2
├── portscanner@1.0.0 (async@0.1.15)
├── http2@3.3.4
├── opn@4.0.2 (object-assign@4.1.0, pinkie-promise@2.0.1)
├── morgan@1.7.0 (on-headers@1.0.1, basic-auth@1.0.4, depd@1.1.0, on-finished@2.3.0, debug@2.2.0)
├── connect@3.4.1 (utils-merge@1.0.0, parseurl@1.3.1, debug@2.2.0, finalhandler@0.4.1)
├── serve-static@1.11.1 (escape-html@1.0.3, encodeurl@1.0.1, parseurl@1.3.1, send@0.14.1)
└── serve-index@1.8.0 (escape-html@1.0.3, parseurl@1.3.1, batch@0.5.3, http-errors@1.5.0, mime-types@2.1.11, debug@2.2.0, accepts@1.3.3)

grunt-contrib-cssmin@1.0.1 node_modules\grunt-contrib-cssmin
├── chalk@1.1.3 (escape-string-regexp@1.0.5, supports-color@2.0.0, ansi-styles@2.2.1, has-ansi@2.0.0, strip-ansi@3.0.1)
├── clean-css@3.4.19 (commander@2.8.1, source-map@0.4.4)
└── maxmin@1.1.0 (figures@1.7.0, gzip-size@1.0.0, pretty-bytes@1.0.4)

grunt-contrib-uglify@2.0.0 node_modules\grunt-contrib-uglify
├── lodash.assign@4.1.0
├── uri-path@1.0.0
├── chalk@1.1.3 (ansi-styles@2.2.1, escape-string-regexp@1.0.5, supports-color@2.0.0, strip-ansi@3.0.1, has-ansi@2.0.0)
├── uglify-js@2.7.0 (async@0.2.10, uglify-to-browserify@1.0.2, source-map@0.5.6, yargs@3.10.0)
└── maxmin@1.1.0 (figures@1.7.0, gzip-size@1.0.0, pretty-bytes@1.0.4)

grunt-usemin@3.1.1 node_modules\grunt-usemin
├── path-exists@1.0.0
├── debug@2.2.0 (ms@0.7.1)
├── chalk@1.1.3 (escape-string-regexp@1.0.5, ansi-styles@2.2.1, supports-color@2.0.0, has-ansi@2.0.0, strip-ansi@3.0.1)
└── lodash@3.10.1

grunt-contrib-watch@1.0.0 node_modules\grunt-contrib-watch
├── async@1.5.2
├── tiny-lr@0.2.1 (parseurl@1.3.1, livereload-js@2.2.2, qs@5.1.0, debug@2.2.0, body-parser@1.14.2, faye-websocket@0.10.0)
├── lodash@3.10.1
└── gaze@1.1.0 (globule@1.0.0)

grunt-unused@0.2.3 node_modules\grunt-unused
├── moment@2.14.1
└── lodash@4.14.1

eslint@3.2.2 node_modules\eslint
├── ignore@3.1.3
├── imurmurhash@0.1.4
├── estraverse@4.2.0
├── strip-bom@3.0.0
├── pluralize@1.2.1
├── path-is-inside@1.0.1
├── globals@9.9.0
├── esutils@2.0.2
├── strip-json-comments@1.0.4
├── progress@1.1.8
├── text-table@0.2.0
├── user-home@2.0.0 (os-homedir@1.0.1)
├── is-resolvable@1.0.0 (tryit@1.0.2)
├── debug@2.2.0 (ms@0.7.1)
├── doctrine@1.2.2 (isarray@1.0.0, esutils@1.1.6)
├── chalk@1.1.3 (supports-color@2.0.0, ansi-styles@2.2.1, escape-string-regexp@1.0.5, has-ansi@2.0.0, strip-ansi@3.0.1)
├── json-stable-stringify@1.0.1 (jsonify@0.0.0)
├── levn@0.3.0 (type-check@0.3.2, prelude-ls@1.1.2)
├── optionator@0.8.1 (fast-levenshtein@1.1.4, type-check@0.3.2, wordwrap@1.0.0, deep-is@0.1.3, prelude-ls@1.1.2)
├── require-uncached@1.0.2 (resolve-from@1.0.1, caller-path@0.1.0)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── concat-stream@1.5.1 (inherits@2.0.1, typedarray@0.0.6, readable-stream@2.0.6)
├── shelljs@0.6.0
├── glob@7.0.5 (path-is-absolute@1.0.0, fs.realpath@1.0.0, inherits@2.0.1, inflight@1.0.5, once@1.3.3, minimatch@3.0.2)
├── inquirer@0.12.0 (strip-ansi@3.0.1, ansi-regex@2.0.0, ansi-escapes@1.4.0, through@2.3.8, rx-lite@3.1.2, cli-width@2.1.0, figures@1.7.0, string-width@1.0.1, readline2@1.0.1, run-async@0.1.0, cli-cursor@1.0.2)
├── espree@3.1.7 (acorn-jsx@3.0.1, acorn@3.3.0)
├── is-my-json-valid@2.13.1 (jsonpointer@2.0.0, generate-function@2.0.0, xtend@4.0.1, generate-object-property@1.2.0)
├── file-entry-cache@1.3.1 (object-assign@4.1.0, flat-cache@1.2.1)
├── js-yaml@3.6.1 (esprima@2.7.2, argparse@1.0.7)
├── table@3.7.8 (slice-ansi@0.0.4, tv4@1.2.7, xregexp@3.1.1, strip-ansi@3.0.1, string-width@1.0.1, bluebird@3.4.1)
├── escope@3.6.0 (esrecurse@4.1.0, es6-map@0.1.4, es6-weak-map@2.0.1)
└── lodash@4.14.1

grunt-sass@1.2.0 node_modules\grunt-sass
├── object-assign@4.1.0
├── each-async@1.1.1 (set-immediate-shim@1.0.1, onetime@1.1.0)
└── node-sass@3.8.0 (get-stdin@4.0.1, lodash.clonedeep@4.4.1, async-foreach@0.1.3, in-publish@2.0.0, chalk@1.1.3, nan@2.4.0, mkdirp@0.5.1, glob@7.0.5, cross-spawn@3.0.1, meow@3.7.0, request@2.74.0, gaze@1.1.0, node-gyp@3.4.0, sass-graph@2.1.2)

babel-preset-es2015@6.9.0 node_modules\babel-preset-es2015
├── babel-plugin-transform-es2015-duplicate-keys@6.8.0 (babel-types@6.11.1, babel-runtime@6.11.6)
├── babel-plugin-transform-es2015-modules-commonjs@6.11.5 (babel-plugin-transform-strict-mode@6.11.3, babel-template@6.9.0, babel-types@6.11.1, babel-runtime@6.11.6)
├── babel-plugin-check-es2015-constants@6.8.0 (babel-runtime@6.11.6)
├── babel-plugin-transform-es2015-shorthand-properties@6.8.0 (babel-types@6.11.1, babel-runtime@6.11.6)
├── babel-plugin-transform-es2015-classes@6.9.0 (babel-messages@6.8.0, babel-helper-replace-supers@6.8.0, babel-helper-optimise-call-expression@6.8.0, babel-helper-function-name@6.8.0, babel-helper-define-map@6.9.0, babel-template@6.9.0, babel-types@6.11.1, babel-traverse@6.12.0, babel-runtime@6.11.6)
├── babel-plugin-transform-es2015-block-scoped-functions@6.8.0 (babel-runtime@6.11.6)
├── babel-plugin-transform-es2015-computed-properties@6.8.0 (babel-helper-define-map@6.9.0, babel-template@6.9.0, babel-runtime@6.11.6)
├── babel-plugin-transform-es2015-for-of@6.8.0 (babel-runtime@6.11.6)
├── babel-plugin-transform-es2015-function-name@6.9.0 (babel-types@6.11.1, babel-helper-function-name@6.8.0, babel-runtime@6.11.6)
├── babel-plugin-transform-es2015-literals@6.8.0 (babel-runtime@6.11.6)
├── babel-plugin-transform-es2015-arrow-functions@6.8.0 (babel-runtime@6.11.6)
├── babel-plugin-transform-es2015-destructuring@6.9.0 (babel-runtime@6.11.6)
├── babel-plugin-transform-es2015-parameters@6.11.4 (babel-helper-get-function-arity@6.8.0, babel-helper-call-delegate@6.8.0, babel-template@6.9.0, babel-types@6.11.1, babel-traverse@6.12.0, babel-runtime@6.11.6)
├── babel-plugin-transform-es2015-object-super@6.8.0 (babel-helper-replace-supers@6.8.0, babel-runtime@6.11.6)
├── babel-plugin-transform-es2015-sticky-regex@6.8.0 (babel-helper-regex@6.9.0, babel-types@6.11.1, babel-runtime@6.11.6)
├── babel-plugin-transform-es2015-block-scoping@6.10.1 (babel-types@6.11.1, babel-template@6.9.0, babel-traverse@6.12.0, lodash@4.14.1, babel-runtime@6.11.6)
├── babel-plugin-transform-es2015-unicode-regex@6.11.0 (regexpu-core@2.0.0, babel-helper-regex@6.9.0, babel-runtime@6.11.6)
├── babel-plugin-transform-es2015-typeof-symbol@6.8.0 (babel-runtime@6.11.6)
├── babel-plugin-transform-es2015-template-literals@6.8.0 (babel-runtime@6.11.6)
├── babel-plugin-transform-es2015-spread@6.8.0 (babel-runtime@6.11.6)
└── babel-plugin-transform-regenerator@6.11.4 (babel-plugin-syntax-async-functions@6.8.0, private@0.1.6, babylon@6.8.4, babel-types@6.11.1, babel-traverse@6.12.0, babel-core@6.11.4, babel-runtime@6.11.6)

grunt-babel@6.0.0 node_modules\grunt-babel
└── babel-core@6.11.4 (babel-messages@6.8.0, babel-template@6.9.0, path-exists@1.0.0, path-is-absolute@1.0.0, slash@1.0.0, shebang-regex@1.0.0, private@0.1.6, babel-helpers@6.8.0, convert-source-map@1.3.0, debug@2.2.0, source-map@0.5.6, babylon@6.8.4, minimatch@3.0.2, babel-types@6.11.1, babel-code-frame@6.11.0, babel-traverse@6.12.0, babel-generator@6.11.4, json5@0.4.0, lodash@4.14.1, babel-register@6.11.6, babel-runtime@6.11.6)

C:\PokemonGo-Map-develop>grunt build
Running "clean:build" (clean) task
>> 1 path cleaned.

Running "babel:dist" (babel) task

Running "uglify:build" (uglify) task
>> 5 sourcemaps created.
>> 5 files created.

Running "minjson:build" (minjson) task
File "static\dist\data\pokemon.min.json" created: 85.94 kB → 55.45 kB
File "static\dist\data\mapstyle.min.json" created: 293 B → 255 B
File "static\dist\locales\de.min.json" created: 18.81 kB → 15.79 kB
File "static\dist\locales\fr.min.json" created: 19.13 kB → 16.12 kB
File "static\dist\locales\pt_br.min.json" created: 17.3 kB → 14.49 kB
File "static\dist\locales\ru.min.json" created: 18.21 kB → 15.23 kB
File "static\dist\locales\zh_cn.min.json" created: 15.29 kB → 12.32 kB
File "static\dist\locales\zh_hk.min.json" created: 17.96 kB → 14.35 kB

Running "sass:dist" (sass) task

Running "cssmin:build" (cssmin) task
>> 3 files created. 52.13 kB → 37.93 kB

Done, without errors.

C:\PokemonGo-Map-develop>

**Comment by dirkpoetter** [comment]
ye i got it but it takes forever to install npm, still not finished. Is that correct?

**Comment by forsakenzombi** [comment]
shoulda been finished by now based on my timeline. It took a good few minutes but nothing crazy. Whole thing was less than 5 minutes.

**Comment by dirkpoetter** [comment]
Yeah don problem solved :D 

Ty veryone!
