### ISSUE TITLE
Pokemon disappear if several people are connected

### ISSUE THREAD

**Issue by rclavel** [AHAAAAAAA/PokemonGo-Map#333]
If there are several people connected on the same web instance, all the pokemons disappear and never come back.

**Comment by hyperknot** [comment]
I can confirm that pokemons disappear after a while, no idea if this is because of other people or because of some other reason.

**Comment by DerScreever** [comment]
some other reason i think #325

**Comment by Answeroid** [comment]
pokemons actually dissapear after several minutes when they were spawned. So if you started pokemon-go-map example.py file and saw there few pokemons on the map - they will dissapear in few minutes. Thats why no need to setup too big steps flag for that

**Comment by rclavel** [comment]
@Answeroid They actually disappear but new pokemons should appear later, and it's not the case. It is a map problem, it's not possible to do not have any pokemons in a large area of a big city.

**Comment by DerScreever** [comment]
Im sorry, but we dropped the support for the master branch (example.py). 
This branch is deprecated.  
The new branch contains a much cleaner structure so pls report only issues related to the develop branch. 

Your development team
