### ISSUE TITLE
grunt: command not found

### ISSUE THREAD

**Issue by raulgbcr** [AHAAAAAAA/PokemonGo-Map#3330]
Im just getting this error and cant install the map.

`raul@raulgbcr:~/PokemonGo-Map$ sudo npm install
sudo: unable to resolve host raulgbcr
npm http GET https://registry.npmjs.org/babel-preset-es2015
npm http GET https://registry.npmjs.org/eslint
npm http GET https://registry.npmjs.org/eslint-config-standard
npm http GET https://registry.npmjs.org/eslint-plugin-promise
npm http GET https://registry.npmjs.org/eslint-plugin-standard
npm http GET https://registry.npmjs.org/grunt
npm http GET https://registry.npmjs.org/grunt-babel
npm http GET https://registry.npmjs.org/grunt-cli
npm http GET https://registry.npmjs.org/grunt-contrib-clean
npm http GET https://registry.npmjs.org/grunt-contrib-concat
npm http GET https://registry.npmjs.org/grunt-contrib-connect
npm http GET https://registry.npmjs.org/grunt-contrib-copy
npm http GET https://registry.npmjs.org/grunt-contrib-cssmin
npm http GET https://registry.npmjs.org/grunt-contrib-uglify
npm http GET https://registry.npmjs.org/grunt-contrib-watch
npm http GET https://registry.npmjs.org/grunt-eslint
npm http GET https://registry.npmjs.org/grunt-html-validation
npm http GET https://registry.npmjs.org/grunt-include-file
npm http GET https://registry.npmjs.org/grunt-legacssy
npm http GET https://registry.npmjs.org/grunt-minjson
npm http GET https://registry.npmjs.org/grunt-sass
npm http GET https://registry.npmjs.org/grunt-unused
npm http GET https://registry.npmjs.org/grunt-usemin

raul@raulgbcr:~/PokemonGo-Map$ sudo npm install -g grunt-cli
sudo: unable to resolve host raulgbcr
npm http GET https://registry.npmjs.org/grunt-cli

raul@raulgbcr:~/PokemonGo-Map$ sudo npm install node-sass
sudo: unable to resolve host raulgbcr
npm http GET https://registry.npmjs.org/node-sass

raul@raulgbcr:~/PokemonGo-Map$ sudo grunt build
sudo: unable to resolve host raulgbcr
sudo: grunt: command not found
raul@raulgbcr:~/PokemonGo-Map$`

**Comment by Becold** [comment]
Try that : sudo npm install -g grunt 
Then : sudo grnt build

**Comment by raulgbcr** [comment]
Same problem, command not found. :(

**Comment by suhdude19** [comment]
getting aswell

**Comment by le3bl** [comment]
@Becold you need to add this line to your hosts files (/etc/hosts & /etc/hostname) for NPM to work.
127.0.0.1 raulgbcr

**Comment by raulgbcr** [comment]
@le3bl Thats not the problem. Despite to it, I have done it and still getting the same problem. 

> raul@raulgbcr:~/PokemonGo-Map$ sudo npm install
[sudo] password for raul:
npm http GET https://registry.npmjs.org/babel-preset-es2015
npm http GET https://registry.npmjs.org/eslint
npm http GET https://registry.npmjs.org/eslint-config-standard
npm http GET https://registry.npmjs.org/eslint-plugin-promise
npm http GET https://registry.npmjs.org/eslint-plugin-standard
npm http GET https://registry.npmjs.org/grunt
npm http GET https://registry.npmjs.org/grunt-babel
npm http GET https://registry.npmjs.org/grunt-cli
npm http GET https://registry.npmjs.org/grunt-contrib-clean
npm http GET https://registry.npmjs.org/grunt-contrib-concat
npm http GET https://registry.npmjs.org/grunt-contrib-connect
npm http GET https://registry.npmjs.org/grunt-contrib-copy
npm http GET https://registry.npmjs.org/grunt-contrib-cssmin
npm http GET https://registry.npmjs.org/grunt-contrib-uglify
npm http GET https://registry.npmjs.org/grunt-contrib-watch
npm http GET https://registry.npmjs.org/grunt-eslint
npm http GET https://registry.npmjs.org/grunt-html-validation
npm http GET https://registry.npmjs.org/grunt-include-file
npm http GET https://registry.npmjs.org/grunt-legacssy
npm http GET https://registry.npmjs.org/grunt-minjson
npm http GET https://registry.npmjs.org/grunt-sass
npm http GET https://registry.npmjs.org/grunt-unused
npm http GET https://registry.npmjs.org/grunt-usemin

You have new mail in /var/mail/raul
raul@raulgbcr:~/PokemonGo-Map$ sudo npm install -g grunt-cli
npm http GET https://registry.npmjs.org/grunt-cli

raul@raulgbcr:~/PokemonGo-Map$ sudo npm install node-sass
npm http GET https://registry.npmjs.org/node-sass

raul@raulgbcr:~/PokemonGo-Map$ sudo grunt build
sudo: grunt: command not found
raul@raulgbcr:~/PokemonGo-Map$ grunt
-bash: grunt: command not found
raul@raulgbcr:~/PokemonGo-Map$

**Comment by MrStu82** [comment]
delete your node modules folder, and run these again
sudo npm install
sudo npm install -g grunt-cli
sudo npm install node-sass
sudo grunt build
