### ISSUE TITLE
Cleanup menu and Full stats not functional

### ISSUE THREAD

**Issue by Plop** [AHAAAAAAA/PokemonGo-Map#3339]
Downloaded latest develop. Menu is not clean and the full stats page is empty and indefinitely loading

## Expected Behavior

Menu like this https://github.com/AHAAAAAAA/PokemonGo-Map/pull/3195
Full stats page like this https://github.com/AHAAAAAAA/PokemonGo-Map/pull/2159

## Current Behavior

Menu like this 
![image](https://cloud.githubusercontent.com/assets/876470/17369161/7869509a-5997-11e6-9685-c4f3582c35dd.png)

Full stats page like this ![image](https://cloud.githubusercontent.com/assets/876470/17369155/6f9debc4-5997-11e6-80ea-b84937ad3baf.png)

**Comment by blindreaper** [comment]
try CTRL-F5 for a full refresh, seems like you are loading cache.

**Comment by Plop** [comment]
Already try this, tried on Firefox, Chrome, IE (yeah...), on my computer and on a mobile phone... People I'm giving the map seems to have the same issues.

**Comment by Plop** [comment]
Seems like a `grunt build` fixed this. Everything is working fine now :)
