### ISSUE TITLE
[Question] Multiple locations

### ISSUE THREAD

**Issue by robbertstevens** [AHAAAAAAA/PokemonGo-Map#334]
Is it possible to search on multiple locations?

**Comment by DerScreever** [comment]
no at the moment we does not provide this feature. maybe later.

**Comment by psam25** [comment]
Is it possible to run 2 times the same instance or with a other new account?

**Comment by talentedmrripley** [comment]
Yes you can run more than one instance at the same time.  Just make sure to specify different port numbers for each one.  I've done two, both in my local area, with the same account.  It worked as expected.

**Comment by robbertstevens** [comment]
@talentedmrripley I meant having them on the same map

**Comment by akatimka** [comment]
yes i want this to )
