### ISSUE TITLE
Error when trying to connect to database on dev

### ISSUE THREAD

**Issue by Extrememist** [AHAAAAAAA/PokemonGo-Map#3345]
peewee.OperationalError: (2003, "Can't connect to MySQL server on 'XX.XXX.XX.XX:23845' ([Errno -2] Name or service not known)")
I have confirmed the database is working with multiple different softwares, its just seems to be,
that my map wont connect to the database. no matter how many different ways i try.

Anyone able to help ?

**Comment by hack3rjack** [comment]
Did you follow the wiki step by step for dev branch requirements and initial setup and the mySQL [wiki](https://jonaharagon.github.io/PoGoMapWiki/#!mysql.md)?

**Comment by Extrememist** [comment]
It was setup by my friend who is hosting a 50 map bots @hack3rjack and he's connected to the exact database im trying to connect to :|

**Comment by hack3rjack** [comment]
He's connected currently? Can you ping that IP from your terminal? Can you have him check to see if the server is started (e.g. service mysql status)? Might be a permission or routing issue if the DB is running.

**Comment by Extrememist** [comment]
its started i've connected to the database via 3rd party tools myself @hack3rjack i dont know what the issue is, but its really screwing me over. he's also connected to it currently, i dont have any access to the server directly and he's currently asleep

**Comment by Extrememist** [comment]
Holy **** i got stuff to work i shall close this now...
