### ISSUE TITLE
best way for multiple ptc accounts?

### ISSUE THREAD

**Issue by dirkpoetter** [AHAAAAAAA/PokemonGo-Map#3347]
quick question, since i try to go with a few accounts. Which is the best way to create multiple accounts? Do u have to create a new email for every account? Some tricks and tipps?

**Comment by le3bl** [comment]
https://github.com/ocjd/ptc-account-creator

**Comment by designateddesigner** [comment]
Well that's great, I was looking for something similar, but this repo doesn't seem to have any documentation along with it and I'm not familiar with ruby. Would you be so kind as to create a short guide?

**Comment by ELusiveLPFAN** [comment]
@designateddesigner , you can use this 
https://github.com/sebastienvercammen/nintendo-ptc-account-generator
