### ISSUE TITLE
Developer cant connect to map via IP address but could with master

### ISSUE THREAD

**Issue by forsakenzombi** [AHAAAAAAA/PokemonGo-Map#3350]
Guys yesterday I setup the master branch and was able to assign it a public ip address and stuff and was able to connect to it yesterday from anywhere.

Today I setup the developer branch and I cant even connect to it on its internal IP address at all. I can only connect to the localhost:5000 but internalip:5000 and externalip:5000 will not work but they worked yesterday with the master branch. I have unlbocked them from the firewall and all that. I am a network admin. I dont think the issue is a network setting. Is there something different about the dev branch vs the master branch when it comes to connecting to it this way?

**Comment by forsakenzombi** [comment]
infact I just confirmed it. If I run the master branch I can connect to localhost:5000 internal-ip-address:5000 and external-ip-address:5000

but if I am running the developer branch I can only connect to localhost:5000 I cannot connect to internal-ip-address:5000 or external-ip-address:5000

**Comment by AmauryVela** [comment]
Adding the host 0.0.0.0 worked for me -H 0.0.0.0, Hope it helps

**Comment by forsakenzombi** [comment]
thats exactly what I was missing. Thank you kind sir
