### ISSUE TITLE
Prevent location change from options within the map

### ISSUE THREAD

**Issue by loki17** [AHAAAAAAA/PokemonGo-Map#3352]
Please help me with disabling all location features (change scan location, scan follows location, start at users location) in the options section of the map. This is to prevent other users from changing scan location which I set through the command window. I am using developers branch.

**Comment by gatomiaurex** [comment]
Did you try using -fl ?

**Comment by loki17** [comment]
-fl did the job. Thanks a lot @gatomiaurex
