### ISSUE TITLE
Please run "grunt build"

### ISSUE THREAD

**Issue by AndreasEnemyr** [AHAAAAAAA/PokemonGo-Map#3357]
[      MainThread][     runserver][CRITICAL] Please run "grunt build" before starting the server

Anyone know?

**Comment by sn0opy** [comment]
Well, just run `grunt build`. If grunt is not yet installed, you have to install it. It's required to build frontend stuff like CSS and Javascript.

**Comment by AndreasEnemyr** [comment]
Thanks! :)
