### ISSUE TITLE
Adding 2 accounts

### ISSUE THREAD

**Issue by michi0987** [AHAAAAAAA/PokemonGo-Map#336]
I would like to be able to use 2 accounts at the same time so map is filling up faster and the whole process is faster cuz of 2x more requests to server.

**Comment by aboldin** [comment]
You can use 2 ports on different maps

**Comment by D3nn3** [comment]
I think his point is to use multiple accounts to populate **one** map and not having one map for each account.
@michi0987 The second option I mentioned is already implemented as aboldin said.

**Comment by michi0987** [comment]
@D3nn3 yes thats what i meant, to use it on one map

**Comment by akatimka** [comment]
i think that good idea.  put 2 or 10 scan in the one location.
Any info how its possible?

**Comment by akatimka** [comment]
now i have 3 pages in screen.
and must swich all time.
Any idea how i can see all objects in one map\page?
START C:\Python27\python.exe example.py -a google -u *@gmail.com -p pass -l "*" -st 5 -ar 5 -P 5000
START C:\Python27\python.exe example.py -a google -u *@gmail.com -p pass -l "*" -st 5 -ar 5 -P 5001
START C:\Python27\python.exe example.py -a google -u *@gmail.com -p pass -l "*" -st 5 -ar 5 -P 5002

**Comment by D3nn3** [comment]
Don't think it's possible yet.
