### ISSUE TITLE
Can Pokesniper2 url be added to monster popup

### ISSUE THREAD

**Issue by billbo99** [AHAAAAAAA/PokemonGo-Map#3368]
Can Pokesniper2 url be added to pokemon detail popup ?

## Expected Behavior
Add an option to enable pokesniper2:// url to the pokemon pop-up

I hacked map.min.js to get this to work for me.  If someone could do this properly I am sure it would be appreciated.

![image](https://cloud.githubusercontent.com/assets/17733206/17375303/45c47438-59a8-11e6-92e4-efa9a5fe65c5.png)

**Comment by andrewda** [comment]
This project is not about cheating/sniping Pokémon. It's about finding the Pokémon around you so you can go out and catch them properly. I'm not in favor if this change. :-1:

**Comment by JZ6** [comment]
If you could 'hack' a pr I can close it.
