### ISSUE TITLE
No Module Named "pgoapi"

### ISSUE THREAD

**Issue by Natglobe** [AHAAAAAAA/PokemonGo-Map#3371]
I'm trying to run the develop branch of the Map Master, and have followed the guidelines on installing everything. But what makes me thing different is when I run the necessary commands I receive the following error message: "ImportError: No module named pgoapi"

## Expected Behavior
 Everything would run smoothly.

## Current Behavior
 I receive the error message: "ImportError: No module named pgoapi"

## Your Environment

* Environment name and version: Python 2.7
* Operating System and version: Mac OS X

**Comment by aldarund** [comment]
you didnt run pip install -r requiremenents.txt

**Comment by skeldoor** [comment]
I am also getting this error. I have run pip install -r requirements.txt

**Comment by Natglobe** [comment]
@aldarund I've run "pip install -r requiremenents.txt" and I'm now recieving this error message:
"ImportError: No module named protobuf.internal"

**Comment by aldarund** [comment]
@Natglobe protobuf not installed for you for some reason. there should be errors when u run pip install -r ..

**Comment by Natglobe** [comment]
@aldarund Do you know how I can install protobuf?

**Comment by aldarund** [comment]
pip install protobuf>=3.0.0a3

**Comment by Natglobe** [comment]
@aldarund I receive this message "Requirement already satisfied (use --upgrade to upgrade): setuptools in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from protobuf)"

**Comment by Natglobe** [comment]
@aldarund  I put in "sudo pip install protobuf --upgrade pip" and it worked. Thank you for the help!
