### ISSUE TITLE
Error while installing requirements.

### ISSUE THREAD

**Issue by TheMaze36904** [AHAAAAAAA/PokemonGo-Map#3373]
When running the command "C:\Python27\Scripts\pip install -r requirements.txt" there is an error while installing pgoapi

## Expected Behavior
Normally it will install all the requirements without errors

## Steps to Reproduce (for bugs)

1. Run "C:\Python27\Scripts\pip install -r requirements.txt"
2. Wait till the end
3. Get an error that says "   Error [Error 2] The system cannot find the specified file while executing command git clone -q git://github.com/tejado/pgoapi.git C:\Users\****\Desktop\PokemonGo-Map-develop\src\pgoapi     Cannot find command 'git'"

## Your Environment

* Version used: latest develop version as of 8/3/2016 1:47 PM Eastern Time (US and Canada)
* Environment name and version (e.g. Python 2.7): Python 2.7.12
* Operating System and version (desktop or mobile): Windows 10, Laptop

**Comment by aldarund** [comment]
you need to have git installed on your machine
