### ISSUE TITLE
ImportError: No Module Named "pgoapi"

### ISSUE THREAD

**Issue by skeldoor** [AHAAAAAAA/PokemonGo-Map#3376]
## Steps to Reproduce

`sudo apt-get install python python-pip python-dev nodejs nodejs-legacy npm`

```
apt install git nodejs npm python-pip nodejs-legacy python-dev
git clone -b develop https://github.com/AHAAAAAAA/PokemonGo-Map.git
cd PokemonGo-Map/
pip install --upgrade pip
pip install -r requirements.txt
npm install
npm install -g grunt-cli
npm install node-sass
grunt build
```
`
python runserver.py -a ptc -u user -p pass -l location -st 5 -H "0.0.0.0" -P "8080" -k key -sd 8 -fl`

Gives this error:

```
Traceback  (most recent call last):
  File "runserver.py", line 37, in <module>
    from pogom.search import search_overseer_thread, fake_search_loop
  File "/var/www/pogom/search.py", line 28, in <module>
    from pgoapi import PGoApi
ImportError: No module named pgoapi
```

## Your Environment

* Version used: develop

**Comment by numb401** [comment]
`pip install -e git://github.com/tejado/pgoapi.git@dffe1490065cd3f24762cc3a1f16316ba0ce7a9c#egg=pgoapi`

**Comment by skeldoor** [comment]
Ran that, still getting exact same error

**Comment by JZ6** [comment]
removed the old pgoapi and reinstall with pip, all else fails download a fresh copy
