### ISSUE TITLE
How to use more than 1 account at the same time?

### ISSUE THREAD

**Issue by GamerBene19** [AHAAAAAAA/PokemonGo-Map#3378]
As I read much about this multiple acc using I just wanted to ask:
**How to use more than 1 account?**
And how do I use it in the webinterface. (Do you have to log in?)

A little step by step guide would be great.

I´m using Raspbian (Jessie Lite) (Yes, it works on RaspberryPi) with Python V. 2.7 on a RaspberryPi
I use the **master** branch.

Thanks for all answers and sorry if I posted this wrong. (Just registered 5 minutes ago)

**Comment by JZ6** [comment]
https://github.com/AHAAAAAAA/PokemonGo-Map/pull/2568

**Comment by JZ6** [comment]
-a/--auth-service, -u/--user and -p/--password can now be defined multiple times.
This is also possible for config file.

**Comment by GamerBene19** [comment]
@JZ6 And how do I decide witch account I want to use? So in my case my server is accesed by two pepole (me and a friend). My Problem now is, if I set my location to my home it scans and everything is ok, but if my friend sets the center of the scanned area to his house it won´t scan mine (and the same for him if it´s set to my house). So is there a way, that I and my friend can use it at the same time, without changing each others points? Or am I missunderstanding sth with this multiple account thing? Sorry for bad English (is it bad?) 
Have a nice day, thanks for your answer, GamerBene.

**Comment by Oricul** [comment]
If it were me, I'd be running 2 different threads, not from the same thread. Share a database file so you can see eachothers results.

**Comment by GamerBene19** [comment]
> If it were me, I'd be running 2 different threads, not from the same thread. Share a database file so you can see eachothers results.

Yeah, but how to do that, I don´t know anything about that.

But lets wait until the Scans (hopefully) work again.

**Comment by chuyskywalker** [comment]
The 'issues' area is for bug reports, it is not a support forum, please use the discord chat.

**Comment by GamerBene19** [comment]
@chuyskywalker What is the "discord chat" and how do I use it?

**Comment by Kruemmelmonster** [comment]
m8 https://jz6.github.io/PoGoMap/ just look at the top...
