### ISSUE TITLE
auto-refresh does not work in Safari

### ISSUE THREAD

**Issue by kingeddard** [AHAAAAAAA/PokemonGo-Map#338]
### Environment info
Operating System: OS X El Capitan 10.11.6 (15G31)

Installed version of Python: 2.7.12

### Steps to reproduce
1. Run in Terminal: python example.py -a ptc -u InstinctForce -p Pokemon150 -l "lat, lng" -st 10 -ar 15
2. Open localhost:5000 in Safari

### What have you tried?
1. Tried changing autorefresh into different parameters
2. Opened localhost:5000 in Google Chrome; worked perfectly

Is this the intended purpose or a bug in how it deals with Safari or how Safari communicates with the info?

**Comment by kingeddard** [comment]
yes, i was using a real GPS coordinate, just decided to leave that out (hope thats okay)

**Comment by alistairmackenzie** [comment]
@kingeddard Please edit your post and remove the PTC credentials.

**Comment by DerScreever** [comment]
Im sorry, but we dropped the support for the master branch (example.py). 
This branch is deprecated.  
The new branch contains a much cleaner structure so pls report only issues related to the develop branch. 

Your development team
