### ISSUE TITLE
Seems like -t arg was removed. Does it have a replacement?

### ISSUE THREAD

**Issue by adrianocr** [AHAAAAAAA/PokemonGo-Map#3380]
The -t (threads) argument was removed. `2016-08-03T14:04:57.79-0400 [App/0]      ERR runserver.py: error: unrecognized arguments: -t 2`. Does it have a replacement? Or does the app now multithread itself?

**Comment by ShadowthePast** [comment]
-t is no longer necessary, it automatically makes a thread for each account from what I understand.
