### ISSUE TITLE
Ngrok Issues

### ISSUE THREAD

**Issue by gatomiaurex** [AHAAAAAAA/PokemonGo-Map#3384]
can't connect with ngrok

## should connect with ngrok
after installing the developer branch and installing the requirements i can't connect with ngrok from another pc, tried with different maps as well but it wont work anymore

## wont connect
after running the workers and ngrok i get a tunnel not found error

## Your Environment
I am using Windows 7 x64 and python 2.7.1

**Comment by SimonTellsAll** [comment]
Also experienced this issue. I have changed to using pagekite although that has bandwidth limits but on the upside handles traffic a lot better.

**Comment by chuyskywalker** [comment]
`ngrok` is not officially something supported here. You can seek community help in the discourse.
