### ISSUE TITLE
http://localhost:5000/raw_data don't list all

### ISSUE THREAD

**Issue by JohanJu** [AHAAAAAAA/PokemonGo-Map#3385]
## Expected Behavior
All of the Pokemon is shown in
http://localhost:5000/raw_data?gyms=false

## Current Behavior
Not all of the Pokemon is shown
(May be intermittent)

## Context
trying to get data to a bot

## Your Environment
Linux
a83ce5c0e6bfa4a97df485498e27fe3a0181ef7a

**Comment by Nexus37** [comment]
Hi !

I noticed the raw_data don't show pokemons on lured pokestop.
I'm not sure but if someone could confirm me ?

**Comment by chuyskywalker** [comment]
This end point is not designed to be consumed outside the application, so this is not a bug.
