### ISSUE TITLE
[Feature Request] config.ini as a runtime argument

### ISSUE THREAD

**Issue by pir2** [AHAAAAAAA/PokemonGo-Map#3386]
## Current Behavior
User can only have one config.ini to start their searchers

## Possible Solution
Add --config as a runtime argument for running server

e.g. `python runserver.py --config myconfig.ini` 

## Context
It would be easier to manage a bunch of `config*.ini` files rather than a bunch of separate commands

**Comment by invisiblek** [comment]
https://github.com/AHAAAAAAA/PokemonGo-Map/pull/3390
