### ISSUE TITLE
OpenSSL problem

### ISSUE THREAD

**Issue by masiarb** [AHAAAAAAA/PokemonGo-Map#339]
Hi guys,

Hate to post this here, since it is not directly related to the map thingy, but mostly something wrong with my system. Anyways, I get the following when running `pip install -r requirements.txt`.

`RuntimeError: You are linking against OpenSSL 0.9.8, which is no longer support by the OpenSSL project. You need to upgrade to a newer version of OpenSSL.`

By doing `openssl version` I see `OpenSSL 1.0.1e 11 Feb 2013` which seems to be fine for the `pip` installation to work. Unfortunately by doing `python -c "import ssl; print ssl.OPENSSL_VERSION"` I see `OpenSSL 0.9.8zg 14 July 2015` which of course is not the correct version. 

Now, I'm running on OSX 10.10.5 with Python 2.7.12. I also opened a SO question with no replies up until now: http://stackoverflow.com/questions/38455688/python-referencing-old-openssl .

Can anybody help me? I tried everything (all the solutions I found on SO were not working for me). I am no Python expert, but would it be possible to change the method calls in order to make it work with the OpenSSL version that my Python installation is able to access?

Thanks

**Comment by mkody** [comment]
Quick question, are you using MacPorts or Homebrew on your Mac?

**Comment by masiarb** [comment]
Sorry for not specifying, I'm using `Homebrew`.

**Comment by mkody** [comment]
Apple has his own OpenSSL "fork", but you might as well have installed an another OpenSSL version through Homebrew.
On my side, with macOS Sierra (beta 10.12), I get `OpenSSL 0.9.8zh 14 Jan 2016` with `openssl version`, while python is using `OpenSSL 1.0.2h   3 May 2016`.

Running `brew info openssl` reported me that I'm using the `1.0.2h` version from it.
Try to run `homebrew update ; homebrew upgade`, this might work.
I don't remember if macOS comes with Python2 pre-installed, but I'm running Hombrew's build on my side.

**Comment by masiarb** [comment]
I did `brew update ; brew upgrade` already, so now I receive `Already up-to-date` response.

Running `brew info openssl` reported me `openssl: stable 1.0.2h (bottled) [keg-only]`, which looks like yours. I installed both Python and OpenSSL through `brew` so running `brew install python` lead to `Warning: python-2.7.12 already installed`.

**Comment by mkody** [comment]
Can you retry with `brew reinstall python --with-brewed-openssl` instead?

**Comment by masiarb** [comment]
Tried that already, here you go the terminal output:

```
$ brew reinstall python --with-brewed-openssl
==> Reinstalling python
==> Downloading https://homebrew.bintray.com/bottles/python-2.7.12.yosemite.bottle.tar.gz
Already downloaded: /Users/masiar/Library/Caches/Homebrew/python-2.7.12.yosemite.bottle.tar.gz
==> Pouring python-2.7.12.yosemite.bottle.tar.gz
==> /usr/local/Cellar/python/2.7.12/bin/python -s setup.py --no-user-cfg install --force --verbose --single-version-extern
==> /usr/local/Cellar/python/2.7.12/bin/python -s setup.py --no-user-cfg install --force --verbose --single-version-extern
==> /usr/local/Cellar/python/2.7.12/bin/python -s setup.py --no-user-cfg install --force --verbose --single-version-extern
==> Caveats
Pip and setuptools have been installed. To update them
  pip install --upgrade pip setuptools

You can install Python packages with
  pip install <package>

They will install into the site-package directory
  /usr/local/lib/python2.7/site-packages

See: https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Homebrew-and-Python.md

.app bundles were installed.
Run `brew linkapps python` to symlink these to /Applications.
==> Summary
🍺  /usr/local/Cellar/python/2.7.12: 3,476 files, 46.7M
$ python -c "import ssl; print ssl.OPENSSL_VERSION"
OpenSSL 0.9.8zg 14 July 2015
```

**Comment by mkody** [comment]
Well, I'm clueless now. That's how I fixed my installation the last time I've been through this.
