### ISSUE TITLE
Poor synergy between Map bot and Bot

### ISSUE THREAD

**Issue by noncicredo** [AHAAAAAAA/PokemonGo-Map#3391]
## Expected Behavior
Catching the pokemon pinned via the map (or the closest one)

## Current Behavior
The Map Bot updates the location, the Bot sometimes forgets it and when it does it takes too much. Anyway, even the Bot updates the location, it **never** catches the pokemon i pin (literally, the pin is on its head), but catches a pokemon aroud it (imo, too far, even if i set "max_distance": 250)
N.B. it looks like the Bot gives priority to real location pokemons  e.g. 80% catches real location pokemons 20% teletrasporting (seems like we need to increase the frequency of location update)

## Steps to Reproduce (for bugs)
1. Pin a pokemon on the Map
2. Update the location on Map bot and Bot as fastest as possibile
3. Catch the pokemon pinned
4. Catch the closest pokemons around the pin 

## Possibile Solution
Increase the Update-Location frequency from the Map Bot to the Bot

## Context
Trying to catch specific pokemons

## Your Environment

* Version used: latest commit
* Environment name and version Python 2.7)
* Operating System and version OSX

**Comment by anqixu** [comment]
Get out of this repo, you ignorant low-life cheater.
