### ISSUE TITLE
share map with friends

### ISSUE THREAD

**Issue by pashjkaaaa** [AHAAAAAAA/PokemonGo-Map#3392]
my friends can come on my map? what should I do for this?

OS Windows 7

my english rly very bad :/

**Comment by gine78** [comment]
you can run more than one instances on your server.  You cannot Share one map with more users. 
One Users location changes the other users location. You need serverinstance for any of your friends.

**Comment by realbunny** [comment]
@gine78 I think he wants to just share the map, not just localhost.
@pashjkaaaa, download https://ngrok.com/, run it and write `ngrok http 5000` (if you are using port 500, wich is standard) in the command line

**Comment by freakjam** [comment]
Please check the Wiki: [Making your map available outside your WiFi](https://jonaharagon.github.io/PoGoMapWiki/#!external.md)
