### ISSUE TITLE
Scanner is very slow, keep getting map parsing failed error and exception while downloading map error (needs 200 got 502)

### ISSUE THREAD

**Issue by nern9** [AHAAAAAAA/PokemonGo-Map#3393]
Im using many accounts to scan, but after i updated to the latest version of the develop branch, i keep getting those two errors. Anyone else having this problem?

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by Jojo1910** [comment]
Same here

**Comment by Crazy-Drew** [comment]
I had it about 5 minutes, ago I shut down the command window,  run the script again and it has been running beautifully since.

**Comment by freakjam** [comment]
Use the [search](https://github.com/AHAAAAAAA/PokemonGo-Map/search?q=needs+200+got+502&type=Issues&utf8=%E2%9C%93) function before posting an issue.
