### ISSUE TITLE
Error When run requirement.txt

### ISSUE THREAD

**Issue by romainhe** [AHAAAAAAA/PokemonGo-Map#3394]
Hi, 
I have an error when i run the command 
"pip install -r requirements.txt"

I get the following error : Command python setup.py egg_info failed with error code 1

Somebody have an idea for fix ?

Thx

**Comment by genito66666** [comment]
https://www.microsoft.com/en-us/download/details.aspx?id=44266 Install this. Works for me.

**Comment by romainhe** [comment]
Sorry... i Forget to specify my env. 

Its a webserver running on debian jessie

**Comment by romainhe** [comment]
For info, the complete error is :  
```
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-TG5LDa/protobuf-to-dict
Storing debug log for failure in /root/.pip/pip.log
```

**Comment by romainhe** [comment]
This command solve the error for me..;
`sudo pip install --upgrade six`
