### ISSUE TITLE
api call from outside

### ISSUE THREAD

**Issue by gine78** [AHAAAAAAA/PokemonGo-Map#3396]
Hey,
my Idea: I get my iphone coordinates directly from icloud (https://github.com/picklepete/pyicloud)
and i want to use these for pokemap.

So i have the lat and lon in variables.  Is there a way to push the coords trough the runserver, so that the pokemap coordinates change if i move? 

I get pushmessages via pushbullet if a wild pokemon appears. So can i get notifications without opening PokemonMap.

**Comment by andrewda** [comment]
Make a POST request to `/next_loc`. You can see how this is done [here](https://github.com/AHAAAAAAA/PokemonGo-Map/blob/2c88f6c0a172f254128de68eb0c5fd7a53ae121a/static/map.js#L1073-L1075).
