### ISSUE TITLE
Digital Ocean 

### ISSUE THREAD

**Issue by blackhattristar** [AHAAAAAAA/PokemonGo-Map#3400]
I just created a DO droplet and I have the IP address but when I enter it into my browser, it doesn't go anywhere except for dnsrsearch.com 

Any help would be greatly appreciated!

**Comment by freakjam** [comment]
Contact DO support.

**Comment by blackhattristar** [comment]
I've tried my IP with :80 and :5000 and I can't seem to get my IP to load in my browser after just setting up a droplet. Any help would be greatly appreciated. This is what I've set in my user data:

#!/bin/bash

apt-get -y update
apt-get -y install git nodejs npm python-pip nodejs-legacy python-dev
git clone -b develop https://github.com/AHAAAAAAA/PokemonGo-Map.git
cd PokemonGo-Map/
pip install -r requirements.txt
npm install
npm install -g grunt-cli
npm install node-sass
grunt build
python ./runserver.py -u myemail@gmail.com -p my password -st 10 -k mykey -l "lat, long” -H 0.0.0.0 -P 80 &

**Comment by GreenflyM** [comment]
-H needs to specify your server IP

**Comment by blackhattristar** [comment]
How can I specify the server IP when the server hasn't been created yet? I'm following the Wiki steps for setting this up on Digital Ocean.

**Comment by andrewda** [comment]
@blackhattristar well you'll need to run the command on a droplet, right? When you run the command, just use the droplet's IP. Why would you need the IP before the droplet is created?

**Comment by blackhattristar** [comment]
Because I thought I was suppose to copy and past 

#!/bin/bash

apt-get -y update
apt-get -y install git nodejs npm python-pip nodejs-legacy python-dev
git clone -b develop https://github.com/AHAAAAAAA/PokemonGo-Map.git
cd PokemonGo-Map/
pip install -r requirements.txt
npm install
npm install -g grunt-cli
npm install node-sass
grunt build
python ./runserver.py -u [USERNAME] -p [PASSWORD] -st 10 -k "[GMAPS API KEY]" -l "[LOCATION]" -H 0.0.0.0 -P 80

into User Data when creating the droplet and you're saying -H is suppose to be the droplets IP address. Right?

**Comment by GreenflyM** [comment]
Just change 0.0.0.0 to the public ip of your droplet

**Comment by blackhattristar** [comment]
Can someone create a video tutorial on how to do this? It's like a couple steps and for some reason I'm finding it very difficult. I tried to make a video to show you all what I'm doing but to cover up all my passwords and information is to time consuming. I'm going to post pics of the steps I'm doing and maybe someone will see where I'm going wrong. I appreciate all of your help!

![screen shot 2016-08-03 at 4 28 12 pm](https://cloud.githubusercontent.com/assets/13209070/17385404/55b2c018-5997-11e6-8d10-1904cf617e7e.png)
![screen shot 2016-08-03 at 4 25 46 pm](https://cloud.githubusercontent.com/assets/13209070/17385408/55d4e51c-5997-11e6-904f-34cec796cddb.png)
![screen shot 2016-08-03 at 4 25 14 pm](https://cloud.githubusercontent.com/assets/13209070/17385407/55cc4a9c-5997-11e6-96a6-b16183bd901a.png)
![screen shot 2016-08-03 at 4 25 09 pm](https://cloud.githubusercontent.com/assets/13209070/17385406/55cab2ea-5997-11e6-917c-ea23a776f936.png)
![screen shot 2016-08-03 at 4 24 46 pm](https://cloud.githubusercontent.com/assets/13209070/17385405/55c7e092-5997-11e6-8922-e7f2f559824f.png)
![screen shot 2016-08-03 at 4 28 45 pm](https://cloud.githubusercontent.com/assets/13209070/17385417/677ea3b6-5997-11e6-972f-7728d44220d3.png)
![screen shot 2016-08-03 at 4 29 17 pm](https://cloud.githubusercontent.com/assets/13209070/17385431/81495160-5997-11e6-9710-a3954585f798.png)
![screen shot 2016-08-03 at 4 29 26 pm](https://cloud.githubusercontent.com/assets/13209070/17385432/82831494-5997-11e6-95ac-2755b7a5aa12.png)

**Comment by blackhattristar** [comment]
I finally got it to work thanks to your help. This is now what I'm seeing when I load the IP address. 

![screen shot 2016-08-03 at 5 09 22 pm](https://cloud.githubusercontent.com/assets/13209070/17386196/1c13d922-599d-11e6-8b28-3717e6c5f570.png)

Any ideas?

**Comment by andrewda** [comment]
TWC sucks. Clear your cache and DNS cache, and if neither of those work, wait for TWC to clear their cache. Should be fine within at most six hours.

**Comment by Zenebatos** [comment]
Is your web browser somehow translating the IP to 'www.$IP' ? That's what it looks like anyways. 

Also even though you hid your IP, its still clearly there in the last screenshot in the search bar...

**Comment by blackhattristar** [comment]
@adrianocr @Zenebatos I finally got it all to work! I wish I could edit the Digital Ocean instructions. It doesn't quit get the point across of what to do if you've never done that sort of thing before. Now that I've done it and gotten it to work, it's like a cake walk. Maybe they'll let me contribute to the instructions for a n00b section. :D

**Comment by andrewda** [comment]
@blackhattristar please also post your solution here so that people who are searching for this issue can find a way to resolve it.

**Comment by blackhattristar** [comment]
My resolve was to create a droplet and copy and paste this in the User Data section:

```
#!/bin/bash

apt-get -y update
apt-get -y install git nodejs npm python-pip nodejs-legacy python-dev
git clone -b develop https://github.com/AHAAAAAAA/PokemonGo-Map.git
cd PokemonGo-Map/
pip install -r requirements.txt
nam install
npm install -g grunt-cli
npm install node-sass
grunt build
```

Notice how I left out `python runserver.py -u [USERNAME] -p [PASSWORD] -st 10 -k [Google Maps API key] -l "[LOCATION]" -H 0.0.0.0 -P 80`

Once I did that, I waited until the droplet was successfully created. Once the droplet was created and it had an IP address, I opened the Access Console and proceeded to login. It was my first Droplet I've ever created so at first it asked me to enter the username (root) and the password (they send you a temp password via email) and once you enter the temp password, they ask you to create a new password. Once I did that I was logged into my Droplet. I wanted to run the code from my mac terminal via SSH because you can't copy and paste in the Digital Ocean Access Console. So I went ahead and opened my mac terminal and to access your DO Droplet you have to type the command `ssh root@the.ip.address.digitalocean.gave.you`

Once you've done that, proceed to login using your DO Droplet credentials (root) and the new password you created and you should be logged in. 

Once you're logged in enter the first command `cd /PokemonGo-Map/`

Now enter the second command `python runserver.py -u [USERNAME] -p [PASSWORD] -st 10 -k [Google Maps API key] -l "[LOCATION]" -H 0.0.0.0 -P 80`

IMPORTANT: Make sure you replace USERNAME, PASSWORD, Google Maps API Key and Location. Remove 0.0.0.0 and replace it with your Droplets IP Address

That's it! If you have any questions, let me know!
