### ISSUE TITLE
Export Pokestops, Gym and Pokemon coordinates to excel spreadsheet

### ISSUE THREAD

**Issue by jonnyjules** [AHAAAAAAA/PokemonGo-Map#3401]
Is there a simple way to export all the coordinates to a spreadsheet?

**Comment by peacefulreason** [comment]
Download a sqlite browser such as http://sqlitebrowser.org/ and open the DB file. Under the file menu, export to csv and select the tables you want to dump.

**Comment by jonnyjules** [comment]
Thanks!
