### ISSUE TITLE
Develop build pogoapi not installed, can't import

### ISSUE THREAD

**Issue by skeldoor** [AHAAAAAAA/PokemonGo-Map#3404]
## Steps to Reproduce

`sudo apt-get install python python-pip python-dev nodejs nodejs-legacy npm`

```
apt install git nodejs npm python-pip nodejs-legacy python-dev
git clone -b develop https://github.com/AHAAAAAAA/PokemonGo-Map.git
cd PokemonGo-Map/
pip install --upgrade pip
pip install -r requirements.txt
npm install
npm install -g grunt-cli
npm install node-sass
grunt build
```

`python runserver.py -a ptc -u user -p pass -l location -st 5 -H "0.0.0.0" -P "8080" -k key -sd 8 `

Gives this error:

It seems 'pogoapi' is not installed. You must run pip install... etc

Running it again doesn't fix

**Comment by Crazy-Drew** [comment]
I entered this line, and it installed the new api right away., I was up and running in a minute.
sudo -H pip install -r requirements.txt

Right now: google and ptc login servers appear to be offline for the time being.

**Comment by Boehmi42** [comment]
I have the same problem. The weird thing is that pgoapi gets installed into src/pgoapi no problem and you can call it from there, but it still isn't getting imported. My Raspberry Pi managed to update to the newest version just fine, but my Debian Wheezy server gets this error.

My exact error message:

[      MainThread][     runserver][CRITICAL] Was not able to import pgoapi. Try running pip install -r requirements.txt

**Comment by skeldoor** [comment]
I have the same issue Boehmi. I'll try what Crazy-Drew said but I have no idea what's wrong, been running the master build for ages now with no issues like this

**Comment by MysticalOS** [comment]
I had to switch off master because it STILL doesn't have the 70m change in it. it's not as well maintained. 100m scans miss a lot of pokemon.

but yes develop can be more buggy sometimes.

**Comment by medghaim** [comment]
https://discord.gg/FbyK5
