### ISSUE TITLE
Pip Install Error for Developer Branch

### ISSUE THREAD

**Issue by captainkirk98** [AHAAAAAAA/PokemonGo-Map#3414]
Operating System: Windows 8

Python 2.7.12

I was using the master branch but decided to try the developer branch to speed up the process of scanning by using multiple accounts. I tried to install pip but this was the error I got:

C:\Users\Kirk\Desktop\Runserver Pokemon Go Map - Developer>pip install --upgrade pip
Requirement already up-to-date: pip in c:\python27\lib\site-packages

C:\Users\Kirk\Desktop\Runserver Pokemon Go Map - Developer>pip install -r requirements.txt
Requirement already satisfied (use --upgrade to upgrade): six==1.10.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): Flask==0.11.1 in c:\python27\lib\site-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): Jinja2==2.8 in c:\python27\lib\site-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe==0.23 in c:\python27\lib\site-packages (from -r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): Werkzeug==0.11.10 in c:\python27\lib\site-packages (from -r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): configargparse==0.10.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): click==6.6 in c:\python27\lib\site-packages (from -r requirements.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): itsdangerous==0.24 in c:\python27\lib\site-packages (from -r requirements.txt (line 8))
Requirement already satisfied (use --upgrade to upgrade): peewee==2.8.1 in c:\python27\lib\site-packages (from -r requirements.txt (line 9))
Requirement already satisfied (use --upgrade to upgrade): wsgiref==0.1.2 in c:\python27\lib\site-packages (from -r requirements.txt (line 10))
Requirement already satisfied (use --upgrade to upgrade): geopy==1.11.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 11))
Requirement already satisfied (use --upgrade to upgrade): s2sphere==0.2.4 in c:\python27\lib\site-packages (from -r requirements.txt (line 12))
Requirement already satisfied (use --upgrade to upgrade): gpsoauth==0.3.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 13))
Requirement already satisfied (use --upgrade to upgrade): PyMySQL==0.7.5 in c:\python27\lib\site-packages (from -r requirements.txt (line 14))
Requirement already satisfied (use --upgrade to upgrade): flask-cors==2.1.2 in c:\python27\lib\site-packages (from -r requirements.txt (line 15))
Requirement already satisfied (use --upgrade to upgrade): flask-compress==1.3.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 16))
Collecting LatLon==1.0.1 (from -r requirements.txt (line 17))
  Using cached LatLon-1.0.1-py2-none-any.whl
Obtaining pgoapi from git+git://github.com/tejado/pgoapi.git@dffe1490065cd3f24762cc3a1f16316ba0ce7a9c#egg=pgoapi (from -r requirements.txt (line 18))
  Cloning git://github.com/tejado/pgoapi.git (to dffe1490065cd3f24762cc3a1f16316ba0ce7a9c) to c:\users\kirk\desktop\runserver pokemon go map - developer\src\pgoapi
  Error [Error 2] The system cannot find the file specified while executing command git clone -q git://github.com/tejado/pgoapi.git "C:\Users\Kirk\Desktop\Runserver Pokemon Go Map - Developer\src\pgoapi"
Cannot find command 'git'

Any ideas how to fix this?

**Comment by andrewda** [comment]
Install git.
