### ISSUE TITLE
Can't install develop version

### ISSUE THREAD

**Issue by iruleuall4** [AHAAAAAAA/PokemonGo-Map#3417]
I am trying to install the developer version in order to run multiple accounts at once. If this is possible with the master version, please let me know before trying to solve this problem and I will simply do that instead.

When I follow the steps listed here: https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Development to install the development version, I run into issues. I have downloaded Node 4.4.7 and when I run "npm install -g grunt" in the appropriate directory, all is well (although I originally had to update minimatch to version 3.0.2 to get it to work). When I try to run "npm install" to install package.json, I get a lot of errors:

http://prnt.sc/c1aipw

http://prnt.sc/c1aixi

It seems as though the root cause is that I'm missing the file ~PokemonGo-Map-develop\node_modules\grunt-sass\node_modules\node-sass\vendor and core.js/library/fn/symbol/iterator

Any help with this matter is greatly appreciated.

**Comment by GamerBene19** [comment]
As far as I know. The master version should suppourt multiple threas.

**Comment by Oricul** [comment]
https://github.com/AHAAAAAAA/PokemonGo-Map/issues/3310#issuecomment-237243134

**Comment by jhonatansm** [comment]
use requirements of master version ;)

**Comment by medghaim** [comment]
https://discord.gg/FbyK5 <--- help
