### ISSUE TITLE
[FIX] Just found this right now, hope it helps devs

### ISSUE THREAD

**Issue by sharklab** [AHAAAAAAA/PokemonGo-Map#3419]
https://github.com/NECROBOTIO/NecroBot/issues/2700

*EDIT:*
NecroBot has removed all issues. The issue linked above contained this:

> I got the request!!!

> [->] Response for DownloadSettings { "hash": "54b359c97e46900f87211ef6e6dd0b7f2a3ea1f5" }
> https://gist.github.com/ruffnecktsk/c36e7ffd8d90ccf07abfab575f4cc511

> decoded. Need responses too

> i see get_player request changed, now app sending version 4 { 1: 2 2 { 1: "0.31.0" } }

> I have caught the RPC requests, but I have no idea what to do next. Here is the raw request of /plfe/rpc : http://cdn.auroraen.com/2U2k0f412L24/1254_Request.txt

> here is one of /plfe/380/rpc: http://cdn.auroraen.com/130s1L3V2l2h/1683_Request.txt

**Comment by Keyvandabar** [comment]
Link doesn't work :(

**Comment by andrewda** [comment]
@Keyvandabar issues were removed from the NecroBot repository literally 25 seconds ago... Not sure why, but the post linked to this: https://gist.github.com/ruffnecktsk/c36e7ffd8d90ccf07abfab575f4cc511

**Comment by sharklab** [comment]
got it all:

I got the request!!!

[->] Response for DownloadSettings { "hash": "54b359c97e46900f87211ef6e6dd0b7f2a3ea1f5" }
https://gist.github.com/ruffnecktsk/c36e7ffd8d90ccf07abfab575f4cc511

decoded. Need responses too

i see get_player request changed, now app sending version 4 { 1: 2 2 { 1: "0.31.0" } }

I have caught the RPC requests, but I have no idea what to do next. Here is the raw request of /plfe/rpc : http://cdn.auroraen.com/2U2k0f412L24/1254_Request.txt

here is one of /plfe/380/rpc: http://cdn.auroraen.com/130s1L3V2l2h/1683_Request.txt

**Comment by ChipWolf** [comment]
Some interesting resources:

https://github.com/PocketMobsters/PokeMobBot/commit/eb1c6abff719db20d652e32f781931c7a6b0f544

https://www.reddit.com/r/pokemongodev/comments/4w0jum/all_ptcgoogle_logins_failing_from_api/?st=irffvv62&sh=5ff0d2f8

**Comment by DeviantEng** [comment]
Guess NecroBot doesn't want to share their work?

**Comment by anonymouz** [comment]
Maybe this?

https://github.com/PocketMobsters/PokeMobBot/commit/52e7c7b6ba398eb9c96fd007be168513f9bed44a

**Comment by Keyvandabar** [comment]
So how does one implement this into the code to fix the issue?

**Comment by le3bl** [comment]
The devs are working on it.  Just wait.

**Comment by ChipWolf** [comment]
@Keyvandabar there's a bunch of us stumbling around trying to figure out what's going on and patch the PoGOAPIs, I'd wait it out if you haven't got much experience

**Comment by FlarumHostingCo** [comment]
You be patient

**Comment by Keyvandabar** [comment]
Thank you! <3

**Comment by g2384** [comment]
@DeviantEng NecroBot did not actually fixed this issue. Their lastest code cannot handle this API change.

**Comment by ChipWolf** [comment]
They've completely changed the protobuf, fun, sleepless night ahead :cold_sweat:

https://www.reddit.com/r/pokemongodev/comments/4w124h/pokemon_go_antibots_reverse_engineering/

**Comment by novikk** [comment]
@ChipWolf the protobuf posted in EDIT2 is actually pretty similar, isn't it?

**Comment by ChipWolf** [comment]
@g2384 I'd be surprised if they managed to reverse engineer and de-obfuscate the new protobuf that quickly

**Comment by ChipWolf** [comment]
@novikk there's lots of uncertain findings popping up right now, Niantic are clearly trying to make breaking changes to kill third-party apps, so if there's some dynamic structure happening I wouldn't be the least bit surprised

**Comment by ChipWolf** [comment]
@novikk turned out to be a bad request

**Comment by NecronomiconCoding** [comment]
@DeviantEng we are sharing the work, we reached 200+ issues filled with the same spam. so we gotta turn dat thing off. 

NecroBot creator -

**Comment by RKT77** [comment]
Agreed, people are freaking out instead of letting the devs solve the issues one by one. We better stop this madness.

**Comment by JZ6** [comment]
false information @sharklab 
@ChipWolf thanks for clearing things up:)

**Comment by DeviantEng** [comment]
@NecronomiconCoding
No doubt. Seeing the same spam around here and /r/pokemongodev. Getting out
of hand. :)

**Comment by Sharke** [comment]
It has nothing to do with sharing their work. The guy who posted that issue just ripped it off reddit / is the same person anyways 

https://www.reddit.com/r/pokemongodev/comments/4w0jum/all_ptcgoogle_logins_failing_from_api/?st=irffvv62&sh=5ff0d2f8
