### ISSUE TITLE
setup.bat issue with cahed pyproj

### ISSUE THREAD

**Issue by anakaine** [AHAAAAAAA/PokemonGo-Map#3420]
An error is generated when using setup.bat, as below. 

I've refreshed the python27 install, pip as well, and have installed the latest version of git. Not sure how to fix this one. Any tips?

Python 2.7.12

## Current Behavior
```
Collecting pyproj (from LatLon==1.0.1->-r requirements.txt (line 17))
  Using cached pyproj-1.9.5.1.tar.gz
    Complete output from command python setup.py egg_info:
    using bundled proj4..
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\teamaw~1\appdata\local\temp\pip-build-q8ui7_\pyproj\setup.py", line 72, in <module>
        objects = cc.compile(['nad2bin.c', 'src/pj_malloc.c'])
      File "c:\python27\lib\distutils\msvc9compiler.py", line 473, in compile
        self.initialize()
      File "c:\python27\lib\distutils\msvc9compiler.py", line 383, in initialize
        vc_env = query_vcvarsall(VERSION, plat_spec)
      File "c:\python27\lib\site-packages\setuptools\msvc.py", line 173, in msvc9_query_vcvarsall
        return EnvironmentInfo(arch, ver).return_env()
      File "c:\python27\lib\site-packages\setuptools\msvc.py", line 1103, in return_env
        [self.VCIncludes,
      File "c:\python27\lib\site-packages\setuptools\msvc.py", line 811, in VCIncludes
        return [os.path.join(self.si.VCInstallDir, 'Include'),
      File "c:\python27\lib\site-packages\setuptools\msvc.py", line 541, in VCInstallDir
        python_vc = self.ri.lookup(reg_path, 'installdir')
      File "c:\python27\lib\site-packages\setuptools\msvc.py", line 451, in lookup
        bkey = winreg.OpenKey(hkey, key, 0, winreg.KEY_READ)
    WindowsError: [Error 2] The system cannot find the file specified

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\teamaw~1\appdata\local\temp\pip-build-q8ui7_\pyproj\

```

**Comment by nijave** [comment]
Looks like it's trying to compile something and you don't have visual studio installed or configured correctly. Easiest solution would be to download the module already compiled as a .whl and install with pip

http://www.lfd.uci.edu/~gohlke/pythonlibs/#pyproj

Then pip install filename.whl

**Comment by anakaine** [comment]
No love there using pip and the wheel files you linked, or by downloading from PyPi and attempting a manual install. In fact the manual install generated the same error as above. 

IF you know, is it possible to use community edition of visual studio to get this to compile?

**Comment by Ajp121** [comment]
I'm having the same issues, I have the latest Visual Studio 2015 installed, python2.7 and latest git.

**Comment by nijave** [comment]
https://www.microsoft.com/en-us/download/details.aspx?id=44266

per https://m.reddit.com/r/pokemongodev/comments/4ubwh0/open_source_pokemon_go_bot_very_fast120_in_56_hrs/d5owsz6

Looks like it was crashing trying to find the location of visual studio or crashing because it could find source files it was looking for in the visual studio files

**Comment by Ajp121** [comment]
Yep, just discovered the same thing. That fixed it for me, thanks!

**Comment by anakaine** [comment]
Also fixed. Thanks
