### ISSUE TITLE
No Pokémon Showing Up

### ISSUE THREAD

**Issue by blackhattristar** [AHAAAAAAA/PokemonGo-Map#3421]
All of a sudden the API has not upserted Pokémon, Gyms or PokéStops. Anyone else having this issue?

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by cesarbecerra** [comment]
Repeated issue, please check the other threads before post it, thank

**Comment by anakaine** [comment]
This has been well noted in previous issues and is due to the latest update. Some new dev info coming through from necrobot may help solve the issue

**Comment by jonathanwcrane** [comment]
Yes this is a known issue.  Niantic changed their API.  see https://github.com/AHAAAAAAA/PokemonGo-Map/issues/3403?issuecomment=237372013#issuecomment-237372013

Contributors, please close this issue.  :)

**Comment by blackhattristar** [comment]
Are we just waiting for a fix or does someone have one already? I couldn't find any answers because there were so many people talking about it.
