### ISSUE TITLE
-nsc -fl not working

### ISSUE THREAD

**Issue by ryanzab** [AHAAAAAAA/PokemonGo-Map#3423]
`SET Settings1=-st 8 -sd 5.1 -ns -ng -fl -nsc`
I had it working yesterday on the Master Branch, but since i switched over to developer I cant get these to work.
Python2.7
Windows 7

**Comment by Kirkerino** [comment]
Well, nothing really works right now. Not for me at least. They changed something.

**Comment by ryanzab** [comment]
Yeah that's true im just checking my scan area's right now.

**Comment by Becold** [comment]
Well, these flags are working on my side. Are you sure you are running on the develop branch ?

Btw, Niantic broke our API. We need an update to fix it.

**Comment by cheevs** [comment]
Did Niantic turn it off on their side?

**Comment by ryanzab** [comment]
@becold ```
REM path
cd C:\Users\ZAB\Desktop\PokemonGo-Map-develop
```
Yeah I am.

**Comment by andrewda** [comment]
#3406
