### ISSUE TITLE
not finding pokemon anymore

### ISSUE THREAD

**Issue by cmills47** [AHAAAAAAA/PokemonGo-Map#3426]
I just got this up and running last night.  I have four accounts being used to scan different areas.  For the last 3.5 hours, all of them are finding 0 pokemon each.  It's logging in successfully, scanning the areas successfully, but always finding nothing.

## Expected Behavior
finding lots of pokemon

## Current Behavior
not finding any pokemon

## Possible Solution
Has anyone else experienced issues like this?  I am not sure if it is something wrong with the tool, Niantec soft-blocking my IP or account(s) [just returning nothing instead of hard blocking me], or if there's something else going on.

## Steps to Reproduce (for bugs)
[unclear -- use 4 accounts running continually for 12 hours on the same computer with default config for 5s delay, and this might repro it]

## Context
Hoping to make a notification system using webhooks

## Your Environment
* Version used: public release (not dev)
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): Win10 desktop

**Comment by PanamaPaul** [comment]
cmon bro....gotta read down a little...lots of posts here...

Niantic changed the API about 5 hrs ago and devs are currently working on a fix. :)

**Comment by itztq** [comment]
don't be lazy and do some research 
-->>
Pokemons won't appear since last login server downtime #3406

**Comment by Kirkerino** [comment]
Yeah, something is wrong atm. The scrips were working as usual last night but now they're not working. Not sure what is wrong, but something is. Read the other comments.

**Comment by PanamaPaul** [comment]
???....Really???.....*facepalm*

**Comment by itztq** [comment]
@cmills47  Delete or close your issue please

**Comment by thappy** [comment]
Please search first

https://github.com/AHAAAAAAA/PokemonGo-Map/issues?q=is%3Aissue+is%3Aclosed

https://www.reddit.com/r/pokemongodev/comments/4w0mtr/getting_0_pokemon_upserted_in_last_few_minutes/

**Comment by xcheneric** [comment]
There should be an issue left open so that people can actually see that
it's being handled.

**Comment by itztq** [comment]
@xcheneric there is --> Pokemons won't appear since last login server downtime #3406

**Comment by cmills47** [comment]
iztq - FWIW I looked through the first 4 pages of open issues and saw none related to this before opening this.  I would recommend making it more obvious this is a known issue rather than hiding the evidence and then telling people reporting the issue to get off your lawn.

**Comment by Sharke** [comment]
@cmills47  Really?
Because this is on the first page https://github.com/AHAAAAAAA/PokemonGo-Map/issues/3406

**Comment by andrewda** [comment]
Closing - #3406
