### ISSUE TITLE
Digital Ocean Droplet and No Google Map

### ISSUE THREAD

**Issue by blackhattristar** [AHAAAAAAA/PokemonGo-Map#3429]
I finally got my Droplet to work thanks to a few of you. This is now what I'm seeing when I load the IP address. 

![screen shot 2016-08-03 at 5 09 22 pm](https://cloud.githubusercontent.com/assets/13209070/17386196/1c13d922-599d-11e6-8b28-3717e6c5f570.png)

Any ideas?

**Comment by Sharke** [comment]
Are you using a valid Maps API Key? Is there any output in the console?

**Comment by andrewda** [comment]
Already asked several times. Please use the search and stick to one issue thread.

**Comment by blackhattristar** [comment]
Do you think that it could be that I entered the Maps API Key wrong?

**Comment by andrewda** [comment]
@blackhattristar could be that. Look in the developer console for more information and post a SS of it here.

**Comment by blackhattristar** [comment]
@andrewda That's what it was! Thank you team!
