### ISSUE TITLE
Help with .bat file

### ISSUE THREAD

**Issue by TheMaze36904** [AHAAAAAAA/PokemonGo-Map#3432]
I am trying to figure out how to make a batch file that does all of these:
- runs the requirements
- runs grunt build
- clones latest dev build
- npm install
- upgrades pip
- npm install -g grunt-cli
- npm install node-sass
- starts the server (runserver.py)
- reloads server every 30 mins 
- and kills all instances

Currently I have a few of them in one batch, but I don't know the others
`start git clone -b develop https://github.com/AHAAAAAAA/PokemonGo-Map.git
cd C:\Users\Liam\Desktop\PokemonGo-Map\
pip install --upgrade pip
pip install -r requirements.txt
npm install
npm install -g grunt-cli
npm install node-sass
npm run-script build
`

**Comment by le3bl** [comment]
Why?

**Comment by TheMaze36904** [comment]
@le3bl so i dont have to enter in all the commands

**Comment by peshetoman** [comment]
there is already a simple install bat in the wiki for windows. check it out if you have missed it. if it doesnt work for you you might at least take ideas from it.
