### ISSUE TITLE
No credentials.json

### ISSUE THREAD

**Issue by sprinke** [AHAAAAAAA/PokemonGo-Map#3434]
Attempting to follow directions on this page: https://jonaharagon.github.io/PoGoMapWiki/#!Macintosh-Installation-and-requirements.md
but there is no credentials.json in the config folder under ~/Documents/PokemonGo-Map.

I'm not very knowledgable about this, so any assistance would be appreciated. Thanks!

**Comment by Devastatin** [comment]
they changed the API, you won't be able to get this to work until they figure out how to deal with the update.

**Comment by pogack** [comment]
Once things are working again, you can place your Google API Key on the command line with -k

**Comment by AndrewYoungs** [comment]
There should be a credentials.json.example, copy that in to that same folder and rename it credentials.json and then uncomment out the lines you need to configure and fill in the areas after the = as needed.

Right now though Niantic borked the API so we're looking for a workaround.

**Comment by ryan7185** [comment]
no, credentials.json is removed, its just config.ini now

**Comment by ajz0691** [comment]
I had to copy credentials.json from the original example.py code. Should I remove ".example" from the config.ini.example file and use that?

**Comment by le3bl** [comment]
@ajz0691 yes. Uncment lines by removing the # symbol

**Comment by MrKetchumAll** [comment]
The whole system is down. Wait until collaborators fix it.
