### ISSUE TITLE
If/when it does start working again, how do I do the map overlay?

### ISSUE THREAD

**Issue by Scharfestahl** [AHAAAAAAA/PokemonGo-Map#3435]
Forgive me for what might be a silly question, but when I set this up yesterday I seemed to have it working in the command prompt. It would say X gyms, X pokestops, X pokemon and X remaining or something to that effect and keep counting down. But how do I have the information show up on google maps? When I run the script, do I need to have my browser open on Google Maps or something? Because I tried doing that yesterday and was not able to have it display Pokemon. What am I missing?

Let me know if I can provide any information that might help.

Thanks!

**Comment by clasherpekka** [comment]
http://localhost:5000/

**Comment by drewreece** [comment]
Have you read the wiki?
For example the Windows installation help… 
https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Windows-Installation-and-requirements
… lists this line 

> Hit enter and view your map in all it's glory at http://127.0.0.1:5000/. Done!

Open that & view it in your browser on the server running PokémonGo-Map.

**Comment by Scharfestahl** [comment]
Thanks for the replies. I did read the wiki to set it up, but it seems like I was looking at a different page perhaps. I followed everything on here:

https://github.com/AHAAAAAAA/PokemonGo-Map/wiki

Maybe it's on there too and I just missed it. But thanks for pointing me in the right direction!
