### ISSUE TITLE
No Pokemon showing in latest develop build 

### ISSUE THREAD

**Issue by Nickg1995** [AHAAAAAAA/PokemonGo-Map#3436]
Just downloaded the latest dev branch and yea it runs but no Pokemon are loading. Also the old threading does not work for me, how do you multi thread now? This is what I was putting in Terminal

python runserver.py -a ptc -u *** -p *** -a ptc -u *** -p *** -a ptc -u *** -p *** -a ptc -u *** -p *** -a ptc -u *** -p *** -a ptc -u *** -p *** -a ptc -u *** -p *** -l “Location” -st 20 -L en -k *** -P 5000 -sd 5 

I used to have -t 20 before for threading which worked well the multiple accounts but yea now there is nothing :/ 

Any help would much appreciated

**Comment by DarkAssassin011** [comment]
Come on man..
[https://www.reddit.com/r/pokemongodev/comments/4w1cvr/pokemongo_current_api_status/](url)

**Comment by ryan7185** [comment]
do ppl ever read previous posts before asking stupid questions.?

**Comment by Nickg1995** [comment]
@DarkAssassin011 Appreciate the heads up. @ryan7185 I did look for a resolution to my issue before posting, clearly I missed the current status of the API.
