### ISSUE TITLE
Error while installing pip - Can't run server "ImportError: No module named queue"

### ISSUE THREAD

**Issue by Nokoa** [AHAAAAAAA/PokemonGo-Map#3439]
I installed the Poekmon GO map couple days ago all worked, now I tried to install it on another computer and there appears to be an error while installing pip in the command line. 
https://i.gyazo.com/1c12b9c68407ee8a40b658f3eba79aca.png

Then when I try to run the server I also get an error probably because of pip. 
https://i.gyazo.com/db73f7767f69a33bcd91529d167b0761.png

I am using the latest Dev branch, with Python 2.7.12 Node, and Grunt.

**Comment by chuyskywalker** [comment]
Please use the search before posting: https://github.com/AHAAAAAAA/PokemonGo-Map/search?q=No+module+named+queue&type=Issues&utf8=%E2%9C%93

**Comment by Nokoa** [comment]
None seem to solve my problem. It says that "'pip' is not recognized as an internal or external command,
operable program or batch file."
