### ISSUE TITLE
zero pokemon found on map 

### ISSUE THREAD

**Issue by piplar** [AHAAAAAAA/PokemonGo-Map#3440]
I know that there are pokemon nearby, but i cant seem to find via localhost. None are being found and I'm assuming thats impossible with a 50 step count. Yesterday i was able to see locations. 

successful complete login using python 27  and the server says im looping but none are being found. 

can someone help?

**Comment by Barabicus** [comment]
Have you not read any of the other many issues posted on this?

**Comment by piplar** [comment]
No i havent, im not getting any errors. program is running exactly like it was yesterday. except its just not finding any pokemon and i did a quick look through issues before posting this and couldnt find an issue exactly like mine. so theres no need for attitude. 

if you dont have something productive to input, than dont say anything at all. 

thanks

**Comment by piplar** [comment]
Im still new to github so some patience would be greatly appreciated

**Comment by piplar** [comment]
can someone add something productive?

**Comment by ericmacfa** [comment]
FYI you'll want to look through the closed issues, there's plenty of duplicate issues on this. The devs are working on this, Niantic changed their API, going to have to wait for a fix.

**Comment by jaller200** [comment]
Niantic updated their API #3406

**Comment by piplar** [comment]
ohhh didnt even realize i could look at closed issues. sorry guys! 

api update makes sense. thanks

**Comment by tungnt244** [comment]
i have the same problem.

**Comment by piplar** [comment]
how long does it usually take to get up and running again?

**Comment by Cammo009** [comment]
Thanks for the update. I have noticed this a possible api change may be causing this issue as the servers was showing pokemon yesturday and now they are not on all 3 of my servers. 

how this can be resolved without to much hassel for developers.

**Comment by Barabicus** [comment]
As long as it takes. Every problem has its own challenges and its hard to say when it'll be back. I can't imagine it taking a huge amount of time but then again its impossible to say. I get you're new to github but there was literally another post about this on the front page. If you go there you can find links that will point you to a reddit section detailing a bit more what is happening.

**Comment by piplar** [comment]
Thanks so much for the info! Really appreciate it.

**Comment by Cammo009** [comment]
Im now to this. Will we need to re-install a new version for the update or will the fix be update automatically?

**Comment by Barabicus** [comment]
You'll have to update it yourself. It could be on the develop branch awhile before it gets pushed to the master branch so when its released look into that. If you're not familiar with branches I suggest googling a quick tutorial on how to setup and use them.
