### ISSUE TITLE
the map don't show the pokemon location.. HELP

### ISSUE THREAD

**Issue by jgvj11** [AHAAAAAAA/PokemonGo-Map#3441]
sorry i dont understad very well the others issues post, but in my case i'm using the map in LINUX, and yesterday was working great, but today after very attempts to try run the program because the niantic servers was heavyload or something like that, the map start woking again but now don't show the pokemons around my location, so whats happening? what can i do to fix the problem? or how can you help me?.
thanks for your services and atention.

**Comment by rain3k** [comment]
i have same problem.

**Comment by xioxxio** [comment]
Seriously?

**Comment by mturfe** [comment]
Same problem as well. Was working yesterday and partially into today.

**Comment by jgvj11** [comment]
what? xioxxio

**Comment by le3bl** [comment]
This issue has been repeatedly raised for the past 6 hours. Do some research before you raise it again.

**Comment by ericmacfa** [comment]
Please look at the closed issues section. There was an Niantic API update, the devs are working on it.

**Comment by xioxxio** [comment]
Exactly, read the other post, its been offline for 6 hours

**Comment by AlejandroBlackburn** [comment]
I have the same problem, In the console I get this error: 2016-08-03 22:31:37,085 [        search] [  ERROR] Search thread failed. Response dictionary key error

**Comment by jgvj11** [comment]
ok ericmacfa, i don't see that section thanks for the advice, i will check, but  you said that the devs are working on it so i will wait for the soon fix... thanks

**Comment by ericmacfa** [comment]
Click the issues tab, then click "closed" with a checkmark and 1500 somthing next to it, or type "is:issue is:closed" in the search box, thanks for being patient

**Comment by IAmPanda1** [comment]
Thanks ericmacfa I tried looking but I wasn't able to find it

**Comment by jgvj11** [comment]
thanks i will close this issue, is my first time and i dont now where is that section but ericmacfa knows where hehehehe.... thanks

**Comment by jlozanomaltos** [comment]
The API is broken, all maps are failing, devs are working on fix...
