### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in c:\users\JoeBlogs\appdata\local\temp\pip-build-auyvyq\pyproj\

### ISSUE THREAD

**Issue by superdonkeyr** [AHAAAAAAA/PokemonGo-Map#3442]
When I run the command line to begin the scan (which begins the scan in the master build, though that build isn't obtaining any results atm) the dev build returns an error telling me to run pip install -r requirements.txt.

I do this and that lists the error in the title a few times. This is only on the dev build that this happens.

## Context
Because of this I cannot use the dev build of this amazing project.

I followed the tutorial exactly to get the master build working --it works
I followed the tutorial again with the dev build --it doesn't work (though ofc this is a dev build and so is by it's very nature, unstable.

**Comment by AI-B0t** [comment]
You need to install Microsoft Visual C++ 9.0, if you run 'pip install -r requirements.txt' you get a better message (highlighted below) with an actionable suggestion: distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 9.0 is required. Get it from **[http://aka.ms/vcpython27](http://aka.ms/vcpython27)**

Collecting pyproj (from LatLon==1.0.1->-r requirements.txt (line 17))
  Using cached pyproj-1.9.5.1.tar.gz
    Complete output from command python setup.py egg_info:
    using bundled proj4..
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\user\appdata\local\temp\pip-build-mrmqhk\pyproj\setup.py", line 72, in <module>
        objects = cc.compile(['nad2bin.c', 'src/pj_malloc.c'])
      File "c:\python27\lib\distutils\msvc9compiler.py", line 473, in compile
        self.initialize()
      File "c:\python27\lib\distutils\msvc9compiler.py", line 383, in initialize
        vc_env = query_vcvarsall(VERSION, plat_spec)
      File "c:\python27\lib\site-packages\setuptools\msvc.py", line 173, in msvc9_query_vcvarsall
        return EnvironmentInfo(arch, ver).return_env()
      File "c:\python27\lib\site-packages\setuptools\msvc.py", line 1107, in return_env
        [self.VCIncludes,
      File "c:\python27\lib\site-packages\setuptools\msvc.py", line 815, in VCIncludes
        return [os.path.join(self.si.VCInstallDir, 'Include'),
      File "c:\python27\lib\site-packages\setuptools\msvc.py", line 553, in VCInstallDir
        raise distutils.errors.DistutilsPlatformError(msg)
    **distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 9.0 is required. Get it from http://aka.ms/vcpython27**

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\user\appdata\local\temp\pip-build-mrmqhk\pyproj\

**Comment by jasonfoy21** [comment]
pip install --upgrade six

OR if that fails

pip uninstall six

**Comment by anakaine** [comment]
install this

https://www.microsoft.com/en-us/download/confirmation.aspx?id=44266

**Comment by Okloks** [comment]
Same problem.
Microsoft Visual C++ 9.0 is installed.

```
  Skipping because already up-to-date.
Requirement already satisfied (use --upgrade to upgrade): future in c:\python27\lib\site-packages (from s2sphere==0.2.4->-r requirements.txt (line 12))
Requirement already satisfied (use --upgrade to upgrade): requests in c:\python27\lib\site-packages (from gpsoauth==0.3.0->-r requirements.txt (line 13))
Requirement already satisfied (use --upgrade to upgrade): pycryptodomex>=3.0 in c:\python27\lib\site-packages (from gpsoauth==0.3.0->-r requirements.txt (line 13))
Collecting pyproj (from LatLon==1.0.1->-r requirements.txt (line 17))
  Using cached pyproj-1.9.5.1.tar.gz
    Complete output from command python setup.py egg_info:
    using bundled proj4..
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "d:\temp\pip-build-cdroli\pyproj\setup.py", line 72, in <module>
        objects = cc.compile(['nad2bin.c', 'src/pj_malloc.c'])
      File "c:\python27\lib\distutils\msvc9compiler.py", line 473, in compile
        self.initialize()
      File "c:\python27\lib\distutils\msvc9compiler.py", line 383, in initialize
        vc_env = query_vcvarsall(VERSION, plat_spec)
      File "c:\python27\lib\site-packages\setuptools\msvc.py", line 173, in msvc9_query_vcvarsall
        return EnvironmentInfo(arch, ver).return_env()
      File "c:\python27\lib\site-packages\setuptools\msvc.py", line 1135, in return_env
        exists),
      File "c:\python27\lib\site-packages\setuptools\msvc.py", line 1158, in _build_paths
        return os.pathsep.join(unique_paths)
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xcc in position 9: ordinal not in range(128)
```

**Comment by Asakurex** [comment]
That's probably because you installed Visual Redistrubtion C++ 9.0 instead of 
https://www.microsoft.com/en-us/download/confirmation.aspx?id=44266
which is Microsoft Visual C++ Compiler for Python 2.7

**Comment by Okloks** [comment]
@Asakurex, no, I installed Microsoft Visual C++ Compiler for Python 2.7

**Comment by Asakurex** [comment]
Here is a whole topic on how to resolve but it's tricky if you're just here to enjoy the map and have no experiance:

http://stackoverflow.com/questions/21129020/how-to-fix-unicodedecodeerror-ascii-codec-cant-decode-byte

**Comment by superdonkeyr** [comment]
Works because of the missing VCPython.msi. Thank you
