### ISSUE TITLE
Upserted 0 pokemon, 0 pokestops, and 0 gyms

### ISSUE THREAD

**Issue by robiningelbrecht** [AHAAAAAAA/PokemonGo-Map#3443]
Since today the my map won't update anymore. When I change the location, the python server reacts accordingly and sets new coordinates. Ajax calls and responses are susscesfull, but I keep getting
_**Upserted 0 pokemon, 0 pokestops, and 0 gyms**_

So I'm left with an empty map

**Comment by ryanzab** [comment]
#3406

**Comment by austexcn** [comment]
this is a known issue and they're working on it, check out #3406

**Comment by MrKetchumAll** [comment]
You noobs need to learn to use the search function or look into issues before spamming issues for help. Getting really annoying guys. I don't mean to be rude, but I feel I'm openly speaking for the majority here.

**Comment by dkweva01007** [comment]
This is the Niantic update, They don't let data out.
