### ISSUE TITLE
Since tonight, fetches no data

### ISSUE THREAD

**Issue by WhizzardBlizzard** [AHAAAAAAA/PokemonGo-Map#3445]
## Current Behavior
Logins are fine (+- 20 ptc accounts, tried a few googles as well), as well as API calls, but returns 0 pokemon,stops and gyms. Got my first 200 HTTP reponse yesterday, but none since. Changing VPS gave the same result

## Steps to Reproduce (for bugs)
threads: 1
delay: 10
step: 12
location: Santa Monica Pier

## Your Environment
- dev branch
- Ubuntu server 16.04
- python 2.7.x

**Comment by chuyskywalker** [comment]
#3406

**Comment by WhizzardBlizzard** [comment]
@chuyskywalker 

Jup, just saw it. Like an idiot I just openend a issue before searching. Flag me as a dumbass
