### ISSUE TITLE
Doesn't find Pokemons

### ISSUE THREAD

**Issue by shaf12** [AHAAAAAAA/PokemonGo-Map#3449]
http://prntscr.com/c1f00l
And there r pokemons in my nearby....
Help pls... :(

**Comment by HinoReo** [comment]
#3403
Learn to use search -_-

**Comment by shaf12** [comment]
Its not the same problem -_-

**Comment by cmoodyEIT** [comment]
Yes it is

**Comment by NoMotion** [comment]
Map doesn't work. This has been an issue for ~10 hours. Please close this

**Comment by cesarbecerra** [comment]
Like everyone said, API CHANGE its the same problem, use search, thats a repeat thread

**Comment by HoDaDor** [comment]
Shhhh, just accept it

**Comment by HinoReo** [comment]
@HoDaDor IMO that's the best reply ever. You made my day
