### ISSUE TITLE
[-] retrying_api_req: request error (Unexpected end-group tag.), retrying

### ISSUE THREAD

**Issue by havenofear** [AHAAAAAAA/PokemonGo-Map#345]
[-] retrying_api_req: request error (Unexpected end-group tag.), retrying
[-] retrying_api_req: request error (Unexpected end-group tag.), retrying
[-] retrying_api_req: request error (Unexpected end-group tag.), retrying
[-] retrying_api_req: request error (Unexpected end-group tag.), retrying

**Comment by sykhro** [comment]
See #342
