### ISSUE TITLE
Error when starting server. (Pokelyzer integrated)

### ISSUE THREAD

**Issue by BallTongue0** [AHAAAAAAA/PokemonGo-Map#3460]
So I'm running the map with pokelyzer feeding data into tableau. And when patching pokelyzer and reinstalling the map I'm having some trouble figuring this out. I'm really new to coding and i hope this will be an easy fix for some of you more experienced programmers! 

## Expected Behaviour
Map server should start

## Current Behaviour
After running: python runserver.py......... i get this:

Traceback (most recent call last):
File "runserver.py", line 18, in 
from pogom.app import Pogom
File "/Users/USER/Documents/pokelyzer/PokemonGo-Map-develop/pogom/app.py", line 17, in 
from .models import Pokemon, Gym, Pokestop, ScannedLocation
File "/Users/USER/Documents/pokelyzer/PokemonGo-Map-develop/pogom/models.py", line 19, in 
from .customLog import printPokemon
File "/Users/USER/Documents/pokelyzer/PokemonGo-Map-develop/pogom/customLog.py", line 16, in 
conn = psycopg2.connect(dbname="pokemon_go", user="pokemon_go_role", password=args.pokel_pass, host="127.0.0.1")
AttributeError: 'Namespace' object has no attribute 'pokel_pass'

## Your Environment
* Version used: Dev branch 
* Environment name and version : Python 2.7, Postgres.app 
* Operating System and version : Mac OSX (10.11)

**Comment by fankaisong** [comment]
that is because you dont have all these package installed. I had the same issue. remember that requirements.txt ? somehow python did not install everything in that list. what I did was making each name a new line. 
![image](https://cloud.githubusercontent.com/assets/16741236/17402950/44ce0012-5a1b-11e6-9b44-e8e4d77a34ce.png)

**Comment by freakjam** [comment]
Arg --pokel-pass is no longer needed. Everything is [done](http://www.whackdata.com/2016/07/31/pokelyzer-webhook-integration-pokemongo-map/) now by using the -wh parameter (webhooks).
