### ISSUE TITLE
Wont't show any pokemon

### ISSUE THREAD

**Issue by Koen-K** [AHAAAAAAA/PokemonGo-Map#3463]
Is does scan and the pokestops and gyms are showing, but no pokemon. Anyone else with the same problem? I tried making new PTC accounts.

**Comment by Reubenwelsh** [comment]
do a search next time

**Comment by Koen-K** [comment]
What do you mean, I got the 16 searchers

**Comment by DANDWYERIRL** [comment]
It is due to an API change. There is a notice in the wiki posted today

**Comment by cdhowie** [comment]
Duplicate of #3406

**Comment by aldarund** [comment]
Use  a f**g search before posting another duplicate. And read at least main of repo and open your eyes

**Comment by licklake** [comment]
#closerequest

**Comment by reikix** [comment]
Seriously, f***ing read before whining here.
