### ISSUE TITLE
No stops, gyms or pokemons found

### ISSUE THREAD

**Issue by Big-al** [AHAAAAAAA/PokemonGo-Map#3464]
Yesterday the pokemon server worked fine, today there are no Stops, Gyms or Pokemons found. 
I tested:
- Both public and private.
- Combinations of notifications and filters
- Both dev and master build
- Both home network, mobile connection, public wifi 
- 3 different public IP's from 2 different distributors 
- 3 different google accounts 

No connection on either. 

Here's the dump from central park:
![udklip](https://cloud.githubusercontent.com/assets/7080878/17405100/7ba20212-5a5e-11e6-84ba-70f02e068880.PNG)

Has the Niantic API been taken down? as far as i understand that would require a new app though, right?(I am new to programming, bare with me.)

**Comment by ankerbachryhl** [comment]
The Api is down right now, they are trying to find a solution :)

**Comment by DANDWYERIRL** [comment]
It is due to an API change. There is a notice in the wiki posted today
