### ISSUE TITLE
How to use multiple accounts?

### ISSUE THREAD

**Issue by Rolloski** [AHAAAAAAA/PokemonGo-Map#3467]
I am trying to set up multiple accounts, they are all PTC accounts and using the same password. I am using the develop branch.. my config below:

```
# Authentication settings
auth-service: ptc
username:[**********,*******,******]
password:****************
```

I have censored out the usernames and password for the purpose of this issue ticket.

The error i get when running the server is :

`runserver.py: error: username can't be set to a list '[*********,*********,************]' unless its action type is changed to 'append'`

**Comment by mrkfishy** [comment]
Issue #3177

**Comment by 1111121RicardoBrandao** [comment]
Only by error description i can say you that you are not using develop branch

Still at the moment the API methods are down so you dont have how to test it when you have the accounts
