### ISSUE TITLE
Search is unable to find any pokemon

### ISSUE THREAD

**Issue by kongshem** [AHAAAAAAA/PokemonGo-Map#3468]
## Expected Behavior
Starting a scan reveals pokemon nearby

## Current Behavior
A scan does not show any pokemon, just pokestops and gyms.

## Steps to Reproduce (for bugs)
1. Start the python program, for example python runserver.py -a ptc -u ******** -p ****** -l "59.9226610, 10.6215490" -st 100
2. Open the map
3.
4.

## Your Environment

* Version used: Latest version
* Environment name and version (e.g. Python 2.7): Python 2.7, cmder
* Operating System and version (desktop or mobile): Windows 10

**Comment by Syndiction** [comment]
The API for everything is down read the front page and please close this issue, they are looking into a solution as of right now
