### ISSUE TITLE
Document Google API key in credentials.json

### ISSUE THREAD

**Issue by marauder37** [AHAAAAAAA/PokemonGo-Map#347]
Sorry, time doesn't allow me to PR this myself. Please add to README.md:

If you see in your browser:

> Oops! Something went wrong. This page didn't load Google Maps correctly. See the JavaScript console for technical details."

or in the console:

> This site has exceeded its daily quota for maps.

then go here: https://developers.google.com/maps/documentation/javascript/get-api-key

and get a key, and change the value of `gmaps_key` in your `credentials.js` to your new key.

**Comment by DerScreever** [comment]
better is to remove the default key. so everyone must generate his own key. so no issues are reported because api key limit is reached.

**Comment by XoneFobic** [comment]
It's not that hard to make/get one, with a 2500 daily quota. Which should be enough for most small projects.

https://console.developers.google.com/apis/credentials

**Comment by Scildrei** [comment]
I attached my own key, but somehow I still get this in the **console**:
> This site has exceeded its daily quota for maps.
And this error on the **page**:
> This page didn't load Google Maps correctly. See the JavaScript console for technical details.

Any input on this?

**Comment by XoneFobic** [comment]
@Scildrei, the error should hold a link to tell you what the problem is.
It can take a few minutes for Google to actually figure out the key is active. It might not be enabled. The website wildcard (`Accept requests from these HTTP referrers`) might be wrong/not accepting your current referrer.

**Comment by DerScreever** [comment]
https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Google-Maps-API:-a-brief-guide-to-your-own-key

**Comment by Scildrei** [comment]
@XoneFobic Yeah, I'm on it. I think I figured it out. Thanks!
