### ISSUE TITLE
-pm

### ISSUE THREAD

**Issue by BlayzerQ** [AHAAAAAAA/PokemonGo-Map#349]
How use -pm?

**Comment by DerScreever** [comment]
we have no -pm? :D

**Comment by mkody** [comment]
@DerScreever Actually, yes [example.py#L495](https://github.com/AHAAAAAAA/PokemonGo-Map/blob/63e0432f65feb667a1d04b014d62f20bcc3ea857/example.py#L495)

**Comment by DerScreever** [comment]
@mkody so only missing in readme. 

@BlayzerQ just write -pm without true or false behind
