### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 'pokemon.json'

### ISSUE THREAD

**Issue by mcmaxl** [AHAAAAAAA/PokemonGo-Map#35]
### Environment info
Operating System: chrooted debian on synology dsm 5

Installed version of Python: 2.7.9

### Logs or other output that would be helpful

```
python /opt/pokemon-go-map/example.py -u ******* -p ******** -l "48.161614, 11.568200" -st 1
[-] register_background_thread called
[-] register_background_thread: not running inside Flask so not starting thread
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
[-] register_background_thread called
[-] register_background_thread: initial registration
[-] main
 * Debugger is active!
Exception in thread search_thread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/pokemon-go-map/example.py", line 315, in main
    pokemonsJSON = json.load(open('pokemon.json'))
IOError: [Errno 2] No such file or directory: 'pokemon.json'

```

**Comment by sykhro** [comment]
Going with the simple stuff first:
is pokemon.json in the same dir as example.py?

**Comment by mcmaxl** [comment]
yes

**Comment by sykhro** [comment]
Probably an issue of relative paths. Will look into it

**Comment by mcmaxl** [comment]
thx. appreciate it!

**Comment by sykhro** [comment]
Can you try again?  b3013cd could have fixed the issue

**Comment by mcmaxl** [comment]
```
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
[-] register_background_thread called
[-] register_background_thread: initial registration
[-] main
 * Debugger is active!
Exception in thread search_thread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/pokemon-go-map/example.py", line 316, in main
    pokemonsJSON = json.load(open(os.getcwd() + '/pokemon.json'))
IOError: [Errno 2] No such file or directory: '/opt/pokemon.json'
```

it should be /opt/pokemon-go-map/pokemon.json in my case

**Comment by dianasalsa** [comment]
I have the same issue running the script on QPython on Android 5.1

The latest update changed the path to //pokemon.json, before it was only "pokemon.json"

![screenshot_2016-07-17-23-40-09](https://cloud.githubusercontent.com/assets/15210597/16903221/27d009ac-4c78-11e6-8ca7-75f9f2f1b6a0.png)

**Comment by sykhro** [comment]
Try out this version http://pastebin.com/H7LmGNb0

**Comment by mcmaxl** [comment]
fixed. thanks

**Comment by sykhro** [comment]
Are the icons displaying correctly?

**Comment by mcmaxl** [comment]
```
('Completed:', 75.0, '%')
[-] register_background_thread called
[-] register_background_thread: queueing
[-] looping: step 0 of 1
[-] retrying_api_req: request error (('Connection aborted.', BadStatusLine("''",))), retrying
[-] retrying_api_req: request error (('Connection aborted.', BadStatusLine("''",))), retrying
[-] retrying_api_req: request error (('Connection aborted.', BadStatusLine("''",))), retrying
[-] main
```

doing this sorta stuff. However, I can't access the webserver. As I said, it's running on a synology box but trying to access serverip:5000 gives me nothing

**Comment by sykhro** [comment]
The pokemon go servers are almost dead, hence the errors. try to access localhost:5000

**Comment by mcmaxl** [comment]
sorry, i was unclear. it's running on the synology server, but i want to access it over the local network from another machine

**Comment by nakami** [comment]
if your synology server is running a linux, try `lsof -i :5000` to see the ports being listened to. i've got the project running on a linux and instead of remapping the local port to a network-accessible one, i just run `curl 127.0.0.1:5000 > index.html` to get a file i can access on my network (e.g. some other webserver...)

**Comment by mcmaxl** [comment]
thank you, i will try that tomorrow!

**Comment by ththompson** [comment]
@mcmaxl  5000 is the default port for the synology web interface. Probably best to use a different one.

**Comment by sykhro** [comment]
As of now, port 5000 is hard coded due to Flask. Custom parameters for this will be added soon

**Comment by Lazarix** [comment]
FYI, the workaround for the port issue is setting app,run in example.py to:
app.run(debug=True, host='0.0.0.0')
If you want a custom port other than 5000, do 
app.run(host='0.0.0.0', port=int('5001'), debug=True)

**Comment by nakami** [comment]
this doesn't help resolving this ticket, however i'd like to help @mcmaxl further.
to correct myself from earlier, creating a local copy is stupid as you also need the icons and need a cronjob or something to create such a copy over and over again.

my instance i've the script running is http://nakami.crux.uberspace.de/pokemongo/

i rerouted the port in my apache webserver via a .htaccess file (in web folder of the apache server)
i could not use 5000 and i had only access to that specific apache server so, i had to take the port  63436
```
RewriteEngine On
RewriteRule (.*) http://localhost:63436/$1 [P]
```
(63436 is the port i got unlocked for myself and quite a weird, because my webserver provider has many users on their server nodes)

in the last line of the `example.py` i've added the port i'm able to use locally:
`app.run(debug=True,port=63436)`

**Comment by marauder37** [comment]
Command line parameters for flask are in PR #54, if someone tests it we can merge it

**Comment by mcmaxl** [comment]
(vielen Dank ;) @nakami, @Lazarix 
solved it via `app.run(host='serverip')`

**Comment by sykhro** [comment]
Seems like everything is sorted out. Closing.
