### ISSUE TITLE
Suggestion: Interacting with script on the map

### ISSUE THREAD

**Issue by Sejadis** [AHAAAAAAA/PokemonGo-Map#350]
in another thread someone asked for the possibility to set new coordinates while on the map.

I think it would be nice if we could further interact with the script - some things i have in mind:
- restarting the script (i.e. to restart it on errors when not at home)
   -> for that it would probably be needed to have the map running independent from the script
- setting new coordinates or basically setting all arguments
- setting local or user based -i / -o lists
   -> i would like to have it running for me and my friends while we are all able to set the list as we want and not server wide

without having an always existing UI i think the start position marker tooltip would be a good place to start

**Comment by foodforarabbit** [comment]
The map is pretty much running separately from the server so you can restart the server and the map will still update properly. I think theres a UI somewhere in progress... as soon as someone adds in a place to put buttons and stuff I'll take a look at building in all the controls.

**Comment by jay8ee** [comment]
Really interested in this too.
