### ISSUE TITLE
Google maps error "daily limit"

### ISSUE THREAD

**Issue by psam25** [AHAAAAAAA/PokemonGo-Map#351]
After run this script today I got a Google maps error:

> This Site Has exceeded the daily limit for tickets. If you created this site, see </a> <a href="https://developers.google.com/maps/faq#usagelimits?utm_referrer=v3" target="_blank"> documentation for more information .

How can we avoid this error?

**Comment by DerScreever** [comment]
You need to generate your own google api key. we create at the moment an instruction, how to generate your own key.
