### ISSUE TITLE
Restart app by rest

### ISSUE THREAD

**Issue by Fiofant** [AHAAAAAAA/PokemonGo-Map#352]
Sometimes the program hangs and does not do the following steps.
It would be nice to add restart applications by  REST API.
Like this: 

> 127.0.0.1:5000/restart?pass=qwerty1

UPD: @mkody rights, need to use your password

**Comment by mkody** [comment]
But what if you're hosting this on a server (because you want to use it on your phone) and that someone finds your instance and type himself `/restart` to annoy you?
Maybe with a password-thing, like `127.0.0.1:5000/restart?key=password`.

**Comment by SilverC** [comment]
@Fiofant I agree with @mkody. I think we should get a separate PR on the backlog to implement a password feature. My PR needs the feature as well #651
