### ISSUE TITLE
API ERROR?

### ISSUE THREAD

**Issue by nullrndtx** [AHAAAAAAA/PokemonGo-Map#353]
[-] retrying_api_req: request error (Unexpected end-group tag.), retrying
[-] retrying_api_req: request error (Unexpected end-group tag.), retrying
[-] retrying_api_req: request error (Unexpected end-group tag.), retrying
[-] retrying_api_req: request error (Unexpected end-group tag.), retrying
[-] retrying_api_req: request error (Unexpected end-group tag.), retrying
[-] retrying_api_req: request error (Unexpected end-group tag.), retrying
[-] retrying_api_req: request error (Unexpected end-group tag.), retrying
[-] retrying_api_req: request error (Unexpected end-group tag.), retrying
[-] retrying_api_req: request error (Unexpected end-group tag.), retrying

**Comment by Plop** [comment]
Niantic servers are just dying, as always. Same issues than #344  and #345

**Comment by marauder37** [comment]
It's because we ask for JSON, the server is dying, it gives us a 503 page in HTML

**Comment by Herwi** [comment]
Same here.
[-] retrying_api_req: request error (Unexpected end-group tag.), retrying

**Comment by fuzha** [comment]
i think this will helping you...
[Google Maps Api](https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Google-Maps-API:-a-brief-guide-to-your-own-key)

**Comment by mkody** [comment]
@fuzha This isn't gmap's related (since it's only a client-side problem, not something you see on the server console), see what @Plop copy-pasted :p

**Comment by Plop** [comment]
@mkody it was faster that way :D
