### ISSUE TITLE
object has no attribute 'latitude'

### ISSUE THREAD

**Issue by fuzha** [AHAAAAAAA/PokemonGo-Map#354]
i get error like this, what must i do? 
thank you...

[-] register_background_thread called
[-] register_background_thread: not running inside Flask so not starting thread
 * Restarting with stat
[-] register_background_thread called
[-] register_background_thread: initial registration
 * Debugger is active!
[+] Locale is en
[+] Getting initial location
 * Debugger pin code: 124-471-736
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
Exception in thread search_thread:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "example.py", line 571, in main
    retrying_set_location(args.location)
  File "example.py", line 157, in retrying_set_location
    set_location(location_name)
  File "example.py", line 177, in set_location
    origin_lat, origin_lon = local_lat, local_lng = loc.latitude, loc.longitude
AttributeError: 'NoneType' object has no attribute 'latitude'

**Comment by Answeroid** [comment]
hey, what you have started? plz list command here also

**Comment by fuzha** [comment]
i just type and enter

> python example.py -a google -u mail -p pass -l "location" -st 5

**Comment by Answeroid** [comment]
python example.py -a google -u your_google@mail.com -l "Location" -st 5 should work if you have no 2 step verification on google account. This time it will ask you to type your password during execution

**Comment by fuzha** [comment]
i have correct data to log in, i have use this pokemon go map normal before this error appear...

**Comment by fuzha** [comment]
still cannot use this map :( 

> [-] register_background_thread called
[-] register_background_thread: not running inside Flask so not starting thread
 * Restarting with stat
[-] register_background_thread called
[-] register_background_thread: initial registration
 * Debugger is active!
[+] Locale is en
[+] Getting initial location
 * Debugger pin code: 302-416-371
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
Exception in thread search_thread:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "example.py", line 554, in main
    retrying_set_location(args.location)
  File "example.py", line 155, in retrying_set_location
    set_location(location_name)
  File "example.py", line 175, in set_location
    origin_lat, origin_lon = local_lat, local_lng = loc.latitude, loc.longitude
AttributeError: 'NoneType' object has no attribute 'latitude'


c:\PokemonGo-Map-master>

**Comment by fuzha** [comment]
still can't use this map :'(
[this is error screenshot](https://www.dropbox.com/s/o514wv9b8z3ktbc/3.PNG?dl=0)

**Comment by Answeroid** [comment]
try to download the latest version of this map and try again
