### ISSUE TITLE
Fork for each steps to parallel API calls

### ISSUE THREAD

**Issue by slbug** [AHAAAAAAA/PokemonGo-Map#357]
It will be useful to have parameter to make parallel requests.
Fork can be done near - ```for step in range(steplimit2):```

**Comment by irrenhaus** [comment]
I think this will only add to the chance that your account gets banned since this would locate you in multiple locations at the same time.

**Comment by slbug** [comment]
Multiple accounts?

**Comment by cprogrammer1994** [comment]
Personally I have to wait 15 seconds to get my map full of pokemons... This is bearable.

**Comment by slbug** [comment]
With 5 steps I have to wait about 10 minutes for full refresh

**Comment by hgentry** [comment]
I can implement this tonight with a -parallel flag to turn it on
