### ISSUE TITLE
Feature request: Display only gyms

### ISSUE THREAD

**Issue by Alexkurd** [AHAAAAAAA/PokemonGo-Map#358]
It would be great to check only gym statuses of the area.
-og --only-gyms Display only gyms

All pokemons are ignored and we can check using bigger steps to cover larger areas.
After #122 we could check only cached gyms status.

**Comment by mkody** [comment]
Maybe more a `-np` `--no-pokemons`?
This allow ua to disable showing Pokémons but with can either show Pokéstops, gyms, or both with `-dp -dg -np`.

**Comment by talentedmrripley** [comment]
For the time being you should be able to accomplish this with -o "Charizard" -dg.  Not the most elegant but at least functional.  Feel free to substitute any other rare Pokemon for Charizard if you want.

**Comment by mkody** [comment]
@talentedmrripley well, `-o "Ditto"` should be the most reliable option ;)

**Comment by MikeDX** [comment]
You can just use -o 0

**Comment by Alexkurd** [comment]
I've used it, but it takes several hours to get full area and gym statuses are incorrect by that time.

**Comment by talentedmrripley** [comment]
@Alexkurd The way I understand the search function it won't matter if they implement a flag for just gyms, it'll still be slow.  You might want to run multiple instances with smaller areas to break up the search into faster chunks.
