### ISSUE TITLE
Lured Pokéstops do not disappear once finished 

### ISSUE THREAD

**Issue by NitriKx** [AHAAAAAAA/PokemonGo-Map#359]
### Environment info
Operating System: Centos7 

Installed version of Python: py27

### Steps to reproduce
1. Run the server with PokéStop + Only Lured PokéStop
2. Find a Lured POkéStop
3. Wait until it ends, the icon does not disappear

**Comment by Temetz** [comment]
Can confirm.

**Comment by mkody** [comment]
Confirming too.

**Comment by AHAAAAAAA** [comment]
shouldn't be a terribly hard thing to fix since we've already done this with pokemon.

**Comment by IMNoob1** [comment]
you have it refreshed ? (haven't noticed if gone with refreshed but can someone confirm?)

**Comment by DerScreever** [comment]
Im sorry, but we dropped the support for the master branch (example.py). 
This branch is deprecated.  
The new branch contains a much cleaner structure so pls report only issues related to the develop branch. 

Your development team
