### ISSUE TITLE
Suggestion: add flag for custom Google Maps Javascript API

### ISSUE THREAD

**Issue by Valareos** [AHAAAAAAA/PokemonGo-Map#361]
At the moment, using my own Javascript API key requires editing the file, which has to be done every time the example.py file is changed.

Adding a flag to declare a API key would mean less reliance on the default API key.

**Comment by mkody** [comment]
Are you editing the `example.py` file to add you key? It should go to `credentials.json`, which you can edit and still pull new version (until there's an edit for it, at least).

**Comment by Swatto** [comment]
I think also it's a good idea since you can provide your own map key with different hosting/running platform without the need of modifying source code since the credentials file is in the git.

**Comment by Temetz** [comment]
This feature already exists?
https://github.com/AHAAAAAAA/PokemonGo-Map/pull/184

**Comment by Temetz** [comment]
Oh... nevermind. My bad. You are looking for a command line flag.

**Comment by mkody** [comment]
So yeah, @Swatto is right. +1 for this.

**Comment by Valareos** [comment]
Closing this issue out as it was on the Master branch and was addressed in the Develop Branch
