### ISSUE TITLE
Using `next_loc` not changing location

### ISSUE THREAD

**Issue by TiesdeKok** [AHAAAAAAA/PokemonGo-Map#362]
When I use, for example, `http://localhost:5000/next_loc?lat=10.5625879&lon=-71.6392861` the following happens:

1) I see the call in the terminal 
2) After the searching is 100% I see the message that the location is updated
3) When the new round of searching begins it, however, still uses the old location

Any idea what might be causing this?

**Comment by chuparCh0pper** [comment]
Please see https://github.com/AHAAAAAAA/PokemonGo-Map/issues/314

**Comment by TiesdeKok** [comment]
My bad, I will close this one.
