### ISSUE TITLE
app.route('/next_loc') not working

### ISSUE THREAD

**Issue by Rohmin** [AHAAAAAAA/PokemonGo-Map#366]
### Environment info
Operating System:

Installed version of Python:
2.7

### Steps to reproduce
1. Set a location and scan, works
2. trough url set new lat/lon parameters , works, gives ok message
3. after current scan/loop is finished, doesn't update to new lat/lon parameters

**Comment by senjougahara** [comment]
Its only map location than doesn't update. Pokemon searching lat/lon updates.

**Comment by JKapitein** [comment]
Duplicate of #314
