### ISSUE TITLE
Cant find module flask.

### ISSUE THREAD

**Issue by wizardsambolton** [AHAAAAAAA/PokemonGo-Map#367]
I have used pip to install requirements.txt, I am using python 2.7 but yet when I run the script I still get the following error:

    Traceback (most recent call last):
            File "example.py", line 4, in <module>
                  import flask
     ImportError: No module named flask

**Comment by Bitti09** [comment]
did 

> pip install --upgrade -r requirements.txt
run without errors?

**Comment by wizardsambolton** [comment]
@Bitti09 Tried that, still get the same error.

**Comment by Baha** [comment]
I'm having the same problem, but in my case `pip install --upgrade -r requirements.txt` is throwing some errors.

**Comment by wizardsambolton** [comment]
I should add I am on OSX El Capitan

**Comment by mkody** [comment]
Try using `pip2 install -r requirements.txt` and `python2 example.py [...]`.
It might happen you have Python 3 installed too.

**Comment by wizardsambolton** [comment]
@mkody Whilst I do have python3 installed, I am sure I am using 2.7.

**Comment by mkody** [comment]
Strange, did you at least try? I did run `pip` the first time and it didn't work. Tried again but with `pip2` and it went well

**Comment by Baha** [comment]
@mkody I've just tried, but I get the same result.

I'm using OSX El Capitan as well...

**Comment by wizardsambolton** [comment]
@mkody Same results as @Baha, tried it, and it still does not work.

**Comment by jonathanselea** [comment]
Please ensure yourself that you are running Python2.7x and NOT Python3x.

Just run:
sudo pip install flask flask-googlemaps

**Comment by wizardsambolton** [comment]
Just done that, still getting the same results. @jonathanselea

**Comment by Baha** [comment]
I think I've fixed it on my machine.

I did it by using `easy_install flask` instead of using pip.

**Comment by wizardsambolton** [comment]
@Baha That does not seem to work for me :/

**Comment by Hambert** [comment]
I use the pip parameter `--ignore-installed` while installing.

`sudo pip2 install --upgrade -r requirements.txt --ignore-installed`

worked on my Mac with Pyton 3 und 2.7 installed.

**Comment by JohnnyDeuss** [comment]
I fixed it by manually seting the setuptools version to an older version:
```
pip install setuptools==21.2.1
pip install flask
```

**Comment by wkernan** [comment]
> I use the pip parameter `--ignore-installed while installing`.
> `sudo pip2 install --upgrade -r requirements.txt --ignore-installed`
> worked on my Mac with Pyton 3 und 2.7 installed.

This worked for me

**Comment by rochacbruno** [comment]
You should start using `virtualenv`

**Comment by wizardsambolton** [comment]
Thanks to @Hambert 's suggestion it works fine! But now when visit the webpage, the map does not display.

**Comment by wizardsambolton** [comment]
Ok so I started using my own google map api key, with that the maps displays, but then I get the following error and no pokemon load.

    retrying_api_req: request error (Unexpected end-group tag.), retrying

**Comment by DerScreever** [comment]
Im sorry, but we dropped the support for the master branch (example.py). 
This branch is deprecated.  
The new branch contains a much cleaner structure so pls report only issues related to the develop branch. 

Your development team
