### ISSUE TITLE
Lure Module Timer Wrong

### ISSUE THREAD

**Issue by SeeingBlue** [AHAAAAAAA/PokemonGo-Map#368]
It appears that lure module expiration timers are wrong. I dropped a lure and the map said it would expire in 2 minutes.

**Comment by Scyntrus** [comment]
My guess is that the expiration time doesn't say when the lure will expire but when the next pokemon will spawn. Anyone verify?

**Comment by DerScreever** [comment]
Im sorry, but we dropped the support for the master branch (example.py). 
This branch is deprecated.  
The new branch contains a much cleaner structure so pls report only issues related to the develop branch. 

Your development team
