### ISSUE TITLE
No pokemons

### ISSUE THREAD

**Issue by Herwi** [AHAAAAAAA/PokemonGo-Map#371]
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discordapp.com/invite/qbpVH6b).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System: Ubuntu

Installed version of Python: 2.7

### Steps to reproduce
1. python example.py -a ptc -u ****** -p ****** -l "Park Cytadela, Poznan" -st 10 -H ****** -P ****** -dp -dg

### What have you tried?
1. Freshly clone git

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).
Loop is working, pokestops and gyms are visible, but pokemons dont show anymore after 30mins.
![poks](https://cloud.githubusercontent.com/assets/20536322/16953857/f4047cfe-4dce-11e6-84a9-84644dbe3e3d.png)

**Comment by CarlSchou** [comment]
Happens for me as well, isn't a server issue cause happened way before servers started going down.

**Comment by DerScreever** [comment]
we already know this.

**Comment by JKapitein** [comment]
Fixed in https://github.com/AHAAAAAAA/PokemonGo-Map/pull/264 btw
