### ISSUE TITLE
I see only 5-6 type of pokemons

### ISSUE THREAD

**Issue by Discepless** [AHAAAAAAA/PokemonGo-Map#373]
### Environment info
Operating System: Windows 10

Installed version of Python: 2.7

### What have you tried?
1. Downloaded other (old) builds.
2. Tried out the version w/o GUI (works fine)
3. Reinstalled

Aloha, Comrades.

Since this morning i've got a trouble - i see only the common pokemons on the map. I've tried different builds, different locations - still the same.
Yesterday worked fine, w/o any troubles

There is a screenshot what i see
http://prntscr.com/butpwu

My launch command example.py -a ptc -u Kalio1993 -p 92300 -l "52.5243700, 13.4105300" -st 20

**Comment by JKapitein** [comment]
Maybe there are only common Pokemon in your area?

**Comment by Discepless** [comment]
Nope, we've tested with my friend. He sees rare pokemons on the same spot =)

**Comment by chuparCh0pper** [comment]
Please remove your username and your password

**Comment by Discepless** [comment]
It's the fake one :)   Well, anyway. Any ideas how to solve this?

**Comment by chuparCh0pper** [comment]
You did not set the `--only` flag did you.

Just tried it on windows 10 & same location it worked for me without problems.

Try to delete and repull the project, also please set the `-dp -dg -d` flags for debugging reasons

**Comment by Alexkurd** [comment]
Pokemon list depends on your trainer level. I've checked the same area with 2lvl and 16lvl and they are different. The higher level the rare pokemons you'll see.

**Comment by Discepless** [comment]
Well, tried agan the full reinstall.. Now between the loop steps i am getting a error 

```
127.0.0.1 - - [19/Jul/2016 17:20:27] "GET /static/forts/PstopLured.png HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "C:\Python27\lib\site-packages\flask\app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Python27\lib\site-packages\flask\helpers.py", line 892, in send_static_file
    cache_timeout=cache_timeout)
  File "C:\Python27\lib\site-packages\flask\helpers.py", line 633, in send_from_directory
    filename = safe_join(directory, filename)
  File "C:\Python27\lib\site-packages\flask\helpers.py", line 603, in safe_join
    return os.path.join(directory, filename)
  File "C:\Python27\lib\ntpath.py", line 85, in join
    result_path = result_path + p_path
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 7: ordinal not in range(128)
[-] retrying_api_req: request error (Unexpected end-group tag.), retrying
```
But than the steps continue and i see the same type of pokemons =) 
http://prntscr.com/buudfy



> Pokemon list depends on your trainer level. I've checked the same area with 2lvl and 16lvl and they are different. The higher level the rare pokemons you'll see.

Nah, by my friend it works fine

**Comment by chuparCh0pper** [comment]
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 7: ordinal not in range(128)

The given value 0xc4 cannot be decoded as it is not ASCII (7bit only). Maybe it has something to do with your Cyrillic letters.
Does your firend use Cyrillic aswell?

**Comment by chuparCh0pper** [comment]
https://discord.gg/KXVkj

**Comment by Discepless** [comment]
The problem was on Cyillic letters ^^
