### ISSUE TITLE
ImportError: No module named flask_googlemaps

### ISSUE THREAD

**Issue by callenshaw** [AHAAAAAAA/PokemonGo-Map#374]
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discordapp.com/invite/qbpVH6b).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:
Windows 10
Installed version of Python:
Python 2.7

### What have you tried?
1. Downloaded full repo and installed with easy setup batch script

### Logs or other output that would be helpful
When trying to run example.py, this is my output:
Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from flask_googlemaps import GoogleMaps
ImportError: No module named flask_googlemaps

I saw no error messages during install - everything says "successfully installed". The final line of output from the install is:
Successfully installed Jinja2-2.8 MarkupSafe-0.23 Werkzeug-0.11.10 click-6.6 coverage-4.1 coveralls-1.1 docopt-0.6.2 flask-0.11.1 flask-googlemaps-0.2.0 future-0.15.2 geopy-1.11.0 gpsoauth-0.3.0 itsdangerous-0.24 protobuf-2.6.1 pycryptodomex-3.4.2 requests-2.10.0 s2sphere-0.2.4

(PS: Also the discord link is broken, or I may have asked there...)

**Comment by callenshaw** [comment]
Ugh this is my fault I wasn't using the absolute path to python so I was running the script with a different version!

**Comment by shahjenil93** [comment]
how did you solve this issue?

**Comment by M4CC** [comment]
I have the same issue, how did you fix it?

**Comment by callenshaw** [comment]
Read the comments ppl... I wasn't using the correct python version when running the script.

Also thanks to everyone who worked on this!!!
