### ISSUE TITLE
Wiki says --auto-refresh, code says --auto_refresh

### ISSUE THREAD

**Issue by asottile** [AHAAAAAAA/PokemonGo-Map#377]
Personally I'd prefer `--auto-refresh`, not sure which is the intended behaviour

**Comment by DerScreever** [comment]
well in this case the code win but should look like the wiki :D

**Comment by mroge009** [comment]
Question, were you able to get the auto refresh to work?

**Comment by asottile** [comment]
Yes, it does appear to work for me

**Comment by alexpantyukhin** [comment]
I have made a pull request for fixing it in the code: https://github.com/AHAAAAAAA/PokemonGo-Map/pull/416

**Comment by DerScreever** [comment]
Im sorry, but we dropped the support for the master branch (example.py). 
This branch is deprecated.  
The new branch contains a much cleaner structure so pls report only issues related to the develop branch. 

Your development team
