### ISSUE TITLE
Discord server link is expired.

### ISSUE THREAD

**Issue by vbogach** [AHAAAAAAA/PokemonGo-Map#379]
GitHub issues are for bug reporting and feature requests.  
For general support, join [**our discord server**](https://discordapp.com/invite/qbpVH6b).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

The discord link in bold is expired.

**Comment by chuparCh0pper** [comment]
The invite expired

**Comment by rezz3x** [comment]
The Link is expired, i have some Questions.

**Comment by chuparCh0pper** [comment]
Please use this one for small questions https://discord.gg/DRHMY
