### ISSUE TITLE
Restarting the app

### ISSUE THREAD

**Issue by hugoerg56** [AHAAAAAAA/PokemonGo-Map#380]
thanks! now working perfect on my iphone
https://dl.dropboxusercontent.com/u/29635564/IMG_0560.jpg

There is a way maybe a route to restart the app?
When I get the "Unexpected end-group tag." need to restart.

**Comment by DilanFX** [comment]
How do you get it working on an iphone? Kinda confused with all this

**Comment by hugoerg56** [comment]
I just mount the app on a webserver from my computer and create an app for IOS with a webview and send the GPS location with the route /next_loc?lat=0000000&long=000000

**Comment by DilanFX** [comment]
Could you explain in basic terms, i'm completely new to all this. Thanks man

**Comment by Hardell** [comment]
That's probably as basic as it gets. 

As for the issue, it comes from the pogo API not handling server overload properly - https://github.com/Mila432/Pokemon_Go_API/issues/79

**Comment by CarlTaylor1989** [comment]
Closing this.

**Comment by hugoerg56** [comment]
Yep no problem, I just get connected via ssh to reset the app in case crash... thanks!
