### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by rezz3x** [AHAAAAAAA/PokemonGo-Map#385]
1. Does the Map automatically show the new Pokemons without refreshing?
2. Can you get banned for using this on your main Account?
3. Are Pokemons from Account to Account different?
4. Could you add the CP of the Pokemon?

**Comment by volksport** [comment]
Yes
Yes
No
No
(from my understanding...)

**Comment by rezz3x** [comment]
Just tried to my first Question, and no you have to refresh the Map to see the Changes.

**Comment by CarlTaylor1989** [comment]
To elaborate a bit more:

1. Yes it does.
2. Of course, be sure to use a dummy account.
3. No, pokemon do not differ and level of account makes no difference.
4. This cannot be added as this is based on account level, a bit of RNG and some maths involved.

**Comment by knilob** [comment]
Good to know about question #2. Got it working initially, and then I was thinking, "Wonder if they'll ban people for using this."

**Comment by Strela666** [comment]
why pokemon may not appear on the map? in the console says that the pokemon is in the coordinate, but on the map it is not
