### ISSUE TITLE
why pokemon may not appear on the map? 

### ISSUE THREAD

**Issue by Strela666** [AHAAAAAAA/PokemonGo-Map#395]
in the console says that the pokemon is in the coordinate, but on the map it is not

**Comment by cprogrammer1994** [comment]
problem persists even if you reload the page?

**Comment by Strela666** [comment]
yes

**Comment by cprogrammer1994** [comment]
can you see those pokemons in the list of `localhost:8000/raw_data`

**Comment by Strela666** [comment]
see in the list of localhost:5000/raw_data

**Comment by cprogrammer1994** [comment]
I will check if I am able to reproduce.

**Comment by Arioh002** [comment]
Same as for Strela666, I can see pokemons list on `localhost:5000/raw_data`, but map is empty.

**Comment by saif88** [comment]
localhost:5000/raw_data is empty and map is empty but i am over a pokestop

**Comment by CTpeMHbly** [comment]
Check your console when you are checking the map. It was the same for me. I had some unicode errors there. 
Just move files to another folder and now it's ok.

**Comment by DerScreever** [comment]
Im sorry, but we dropped the support for the master branch (example.py). 
This branch is deprecated.  
The new branch contains a much cleaner structure so pls report only issues related to the develop branch. 

Your development team
