### ISSUE TITLE
Decouple  Flask-GoogleMaps

### ISSUE THREAD

**Issue by macgngsta** [AHAAAAAAA/PokemonGo-Map#396]
As awesome as Flask-GoogleMaps is in creating a quick google map, there is no support for other google apis, such as places API

[https://developers.google.com/maps/documentation/javascript/examples/places-searchbox](url)

i actually tried to get a search box in, but it requires loading the places library after the google key, and i think that without some significant effort on adding to the flask-googlemaps project or making a short term hack would be the only way

there also could be a possibility of going openstreet maps instead of google maps.

**Comment by AHAAAAAAA** [comment]
There's been a lot of talk about this as people run into roadblocks designing and adding to the maps. IMO, I think the best choice is to contribute to the Flask-GoogleMaps project right now. @rochacbruno has been pretty responsive and it would be amazing if we can make this project as full-featured as possible. It's one of the better Flask solutions I've used and is a nice chance to give back!

However, I haven't been that involved on the front-end so far and I defer to those who are!

**Comment by rochacbruno** [comment]
If something need to be add/changed in Flask-GoogleMaps I can help.

**Comment by rochacbruno** [comment]
BTW: @macgngsta to add new JS library you can just do in template after {{fullmap.js}} which problem did you find?

**Comment by rochacbruno** [comment]
@macgngsta I just tested places-searchbox and works well.

put the library after {{fullmap.js}}

then refer to existing `map` object in JS.

**Comment by macgngsta** [comment]
@rochacbruno  - i saw an issue where they mentioned map scope was not available, but i was looking at the 2 versions behind on the Flask-GoogleMaps, ill have to revisit.

**Comment by rochacbruno** [comment]
They should merge this https://github.com/AHAAAAAAA/PokemonGo-Map/pull/386

**Comment by macgngsta** [comment]
I'm also waiting for the rewrite before I do any significant changes as it will probably require some additional endpoints and control logic
