### ISSUE TITLE
FIX AttributeError FIX

### ISSUE THREAD

**Issue by Pypsen1337** [AHAAAAAAA/PokemonGo-Map#397]
Hello! I did this . The screenshot below . (Perhaps a mess , throw an example of the resulting line ), press enter in the console ( the result of the screenshot below ) , turn on http: // localhost: 5000 , and the site appears AttributeError ( screenshot below)
Please, help! What is wrong and what to do next ?
ATTENTION! FIX !
REPLACE "Google" on the "ptc" and 
Remove the space in your location after the comma
ATTENTION! FIX !
![ea](https://cloud.githubusercontent.com/assets/20542481/16958700/123cff26-4dfb-11e6-8d19-735725b7c04e.png)
![a6e0ca2c-4dfb-11e6-9899-6227719df693](https://cloud.githubusercontent.com/assets/20542481/16973809/4b09d57c-4e50-11e6-8eba-88d79e1ca975.png)

![ae](https://cloud.githubusercontent.com/assets/20542481/16958681/f61e0e7a-4dfa-11e6-8b75-5475558c6cf6.png)

**Comment by jreese802** [comment]
You need a closing quote for your location.

**Comment by Pypsen1337** [comment]
what?  - "my location" "" quotes have

**Comment by JoshuaGarrison27** [comment]
Remove your comma from the location coordinates. I believe this is a previous bug but some could argue it isn't a bug. But I feel the comma should there.

**Comment by Pypsen1337** [comment]
Delete comma.
![wert](https://cloud.githubusercontent.com/assets/20542481/16959638/7f6fc872-4dff-11e6-83a4-087bd50b4cc0.png)

**Comment by Pypsen1337** [comment]
They say there is a solution in the https://github.com/AHAAAAAAA/PokemonGo-Map/issues/284 , but I do not understand how to apply it . Explain please !

**Comment by Scyntrus** [comment]
Remove the space in your location after the comma

**Comment by Pypsen1337** [comment]
Thank You, @Scyntrus  
A new trouble . Do you know how to help me ?
![aea](https://cloud.githubusercontent.com/assets/20542481/16972774/a54f01c8-4e47-11e6-858b-f15266c2f557.png)

**Comment by DerScreever** [comment]
Im sorry, but we dropped the support for the master branch (example.py). 
This branch is deprecated.  
The new branch contains a much cleaner structure so pls report only issues related to the develop branch. 

Your development team
