### ISSUE TITLE
ProtoBuffer Parsor Error

### ISSUE THREAD

**Issue by rushingfitness** [AHAAAAAAA/PokemonGo-Map#398]
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discordapp.com/invite/qbpVH6b).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:
Mac OS 10.11.5
Installed version of Python:
2.7

### Steps to reproduce
1. Turn on the server
2. Let it try and get pokemon
3. Sometimes it errors, sometimes it doesn't

### What have you tried?
1. I added in a second catch to line 214:
    
        except:
            print "Unexpected error:", sys.exc_info()[0]

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).
<img width="888" alt="screenshot 2016-07-19 13 03 32" src="https://cloud.githubusercontent.com/assets/3672033/16959056/3772057e-4db1-11e6-8282-94765c5bb015.png">

**Comment by DerScreever** [comment]
Im sorry, but we dropped the support for the master branch (example.py). 
This branch is deprecated.  
The new branch contains a much cleaner structure so pls report only issues related to the develop branch. 

Your development team
