### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 'credentials.json'

### ISSUE THREAD

**Issue by mcmaxl** [AHAAAAAAA/PokemonGo-Map#399]
```
root@BlackBox:/# python /opt/pokemongo/example.py -u ***** -p ******** -l "*******" -st 10 -H 192.168.100.10 -P 5010
Traceback (most recent call last):
  File "/opt/pokemongo/example.py", line 41, in <module>
    with open('credentials.json') as file:
IOError: [Errno 2] No such file or directory: 'credentials.json'
```

newest version, file is definitely in there. What am I doing wrong?

**Comment by cprogrammer1994** [comment]
run in the PokemonGo-Map where the `credentials.json` is.

**Comment by mcmaxl** [comment]
how do you mean?

**Comment by Cat-Ion** [comment]
cd /opt/pokemongo/
    python /opt/pokemongo/example.py -u ***** -p ******** -l "*******" -st 10 -H 192.168.100.10 -P 5010

**Comment by mcmaxl** [comment]
ok that works. Why? Known bug?

**Comment by cprogrammer1994** [comment]
maybe the file should be loaded with:
```
os.path.join(os.path.dirname(os.path.realpath(__file__)), 'credentials.json')
```

**Comment by cprogrammer1994** [comment]
i have an active *Pull Request*, i don't know if I can raise another.

**Comment by mkody** [comment]
@cprogrammer1994 You can create a new branch based on the current master and open a new Pull Request. ;)

**Comment by DerScreever** [comment]
Im sorry, but we dropped the support for the master branch (example.py). 
This branch is deprecated.  
The new branch contains a much cleaner structure so pls report only issues related to the develop branch. 

Your development team
