### ISSUE TITLE
Gets stuck after RPC server 

### ISSUE THREAD

**Issue by Idhanta** [AHAAAAAAA/PokemonGo-Map#4]
I entered the command, it started the flask maps on localhost, I went to localhost:5000 on my browser, could see the map but then when I went to check the terminal, it showed this and got stuck at this point. 
I'm using my club trainer account. 

![screen shot 2016-07-17 at 4 45 10 pm](https://cloud.githubusercontent.com/assets/2195375/16900290/560e7c34-4c3e-11e6-891a-5f8577e2df85.png)

After trying to reload the page, I get a ValueError: No JSON object could be decoded.
https://gist.github.com/anonymous/a4ea9dc6d12a1b8f793208b3fc265518

**Comment by marzika** [comment]
The terminal shows the exact error, the RPC server is down, try again later. The reload-ValueError is normal.
