### ISSUE TITLE
Run project help

### ISSUE THREAD

**Issue by immorro** [AHAAAAAAA/PokemonGo-Map#400]
Can anyone tell me - how to run python project? What i need to get page like on screenshot? Newer work with py..(

**Comment by sashgorokhov** [comment]
apt-get install python python-dev python-pip
pip install -r requirements.txt
python example.py <options>

**Comment by riley-usagi** [comment]
`Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'`

**Comment by ryanhmaas** [comment]
As an example: `python example.py -a authService -u myUsername -p myPassword -l "Boulder, CO" -st 5`

So substitute authService with either google or PTC, myUsername with your username, and myPassword with your password. Make sure the location in quotes is one Google Maps can locate.

More info here: https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Usage

**Comment by vladimirtsyupko** [comment]
@ryanhmaas which username/password from google account?

**Comment by Rhynocerous** [comment]
@vladimirtsyupko Whichever username/password you use for your secondary Pokemon Go account. I recommend not using your primary account.

**Comment by immorro** [comment]
`>>> python example.py -a google -u xxx@xxx.xxx -p qwerty -l "Central Park, New York, NY" -st 5 -H 0.0.0.0 -P 5000
SyntaxError: invalid syntax`
whats wrong

**Comment by vintagesucks** [comment]
google username without the @gmail.com part

**Comment by immorro** [comment]
@vintagesucks, same error

**Comment by vintagesucks** [comment]
@immorro your command runs fine for me, do you have any double spaces or did you actually include >>> in your command?

**Comment by sashgorokhov** [comment]
@immorro if `python - - version` says 3.* version (not 2.7) then you using the wrong python version. You should install python 2.7

**Comment by immorro** [comment]
![image](https://cloud.githubusercontent.com/assets/13468709/16963501/69baf402-4dff-11e6-8541-d9f80be011d6.png)

**Comment by Vivicus** [comment]
This shouldn't be an issue for the team to look at.

This isn't a bug, this is a user issue.  Assuming you have python installed correctly you can run the python script from the folder as such (Using powershell as an example):

.\example.py -a [ptc or google authN] -u [Actual username] -p [Actual password] -l "[Actual address]" -st 10

Trying to have developers take time out of their lives to help you learn not only the absolute basics of how to execute their code takes time away from them developing the code, which they are doing for free, on top of what they are already doing for jobs.  Please be more considerate in the future.

**Comment by sashgorokhov** [comment]
@immorro looks like you're completely unfamiliar with the magic we are doing here.

**Comment by ARentz07** [comment]
Can you guys document that you need python 2.7 and not 3.x? I'm a software developer and just managed to run through the whole process without realizing I had the wrong version of python installed. @immorro Don't worry about it. :smile:

**Comment by immorro** [comment]
yeap, coding in console in 2k16 its not wor me... so I asked for help.

This giude realy helps - seems like problem was in path var
https://github.com/vintagesucks/PokemonGo-Map-Install-Guides

![image](https://cloud.githubusercontent.com/assets/13468709/16974617/4851eef4-4e47-11e6-86db-c69d1ace6794.png)

thx all.

**Comment by lookforwardto** [comment]
well done

**Comment by lakhhan** [comment]
Ohhh fuck..I dnt knw anything bt i want the map for pokemon go..any could me out.!??
