### ISSUE TITLE
Login and password?

### ISSUE THREAD

**Issue by riley-usagi** [AHAAAAAAA/PokemonGo-Map#404]
What? How to use normal google account? What key need to use?

**Comment by Naramsim** [comment]
`python example.py -a google -u mail@gmail.com -p myPassword -l "Firenze Italy" -st 5 -i Pidgey,Weedle,Zubat`

**Comment by TheWebSmith** [comment]
As the username you use the google username without the @gmail.com. The password is the same as the one you use when you log into your google account.

**Comment by wkernan** [comment]
I used quotes to fill in username and password -u "@gmail.com" -p "password"

**Comment by JZ6** [comment]
fixed
