### ISSUE TITLE
Map not appearing

### ISSUE THREAD

**Issue by lverdi** [AHAAAAAAA/PokemonGo-Map#405]
Operating System: Mac OS 10.11.5
Installed version of Python: 2.7

I've done all the installation steps but when I run the program, no map is appearing. I can see the search being done but there is no visualization.

**Comment by ryanhmaas** [comment]
After you run, go to the url provided in the console.  It'll say something like 

> running on http://127.0.0.1:5000/

Navigate to that.

**Comment by tylerjosephrose** [comment]
Still doesn't exactly work. The page does not have a map on it. Here's what loads on mine.
<img width="597" alt="screen shot 2016-07-19 at 1 48 02 pm" src="https://cloud.githubusercontent.com/assets/11827207/16960423/805ff7ea-4db7-11e6-8efa-4a8e1bd39b12.png">

**Comment by Twista** [comment]
check the browser console

**Comment by JZ6** [comment]
need more info

**Comment by tylerjosephrose** [comment]
Here is the full screen with the browser console pulled up if that helps.
<img width="1280" alt="screen shot 2016-07-19 at 1 50 20 pm" src="https://cloud.githubusercontent.com/assets/11827207/16960496/ce6a881a-4db7-11e6-9e52-ffc433b02492.png">

**Comment by tylerjosephrose** [comment]
Hm. Under console it says Failed to load resource: the server responded with status 404

**Comment by tylerjosephrose** [comment]
I reloaded everything and it is working now.

**Comment by Naramsim** [comment]
Go for #406.
Read this: https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Google-Maps-API:-a-brief-guide-to-your-own-key

**Comment by tylerjosephrose** [comment]
Using my own key does not work either. It seems to load the map fine until it begins searching for Pokemon. After that it gives the same error as earlier

**Comment by blakebjorn** [comment]
**FIX**
in example.py, change:

line 823: pokemon['name'] = pokemon['name'].replace(u'\N{MALE SIGN}','(M)').replace(u'\N{FEMALE SIGN}','(F)')
line 831: LABEL_TMPL = u''' -> LABEL_TMPL = ''' 
line 842: 'key': pokemon_key -> 'key': str(pokemon_key) 

This forces all the unicode values to str, and makes nidoran be represented as (M)/(F) in the browser

**Comment by tylerjosephrose** [comment]
That did it! Thanks!

**Comment by DerScreever** [comment]
Im sorry, but we dropped the support for the master branch (example.py). 
This branch is deprecated.  
The new branch contains a much cleaner structure so pls report only issues related to the develop branch. 

Your development team
