### ISSUE TITLE
This site has exceeded its daily quota for maps.

### ISSUE THREAD

**Issue by SeeingBlue** [AHAAAAAAA/PokemonGo-Map#406]
### Environment info
Operating System: Win10x64

Installed version of Python: 2.7

### Steps to reproduce
1.Launch maps with 'C:\Python27\python.exe example.py -a ptc -u **** -p **** -l "Morristown, TN" -st 3 -H 0.0.0.0 -P 5000 -i Caterpie,Rattata,Zubat,Pidgey,Weedle -dp -ol -dg -ar 10'. Load Localhost:5000 in Chrome
2. Sometimes(not everytime) it crashes and says: 'Oops! Something went wrong.
This page didn't load Google Maps correctly. See the JavaScript console for technical details.'
3. Javascript console reports: This site has exceeded its daily quota for maps. If you are the creator of this site, please visit the <a href="https://developers.google.com/maps/faq#usagelimits?utm_referrer=v3" target="_blank">documentation</a> to learn more.'

### What have you tried?
1. Nothing

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).
*.170.110.16 - - [19/Jul/2016 13:41:52] "GET /data HTTP/1.1" 200 -
*.170.110.16 - - [19/Jul/2016 13:42:02] "GET /data HTTP/1.1" 200 -
[-] retrying_api_req: request error (Unexpected end-group tag.), retrying
*.170.110.16 - - [19/Jul/2016 13:42:08] "GET / HTTP/1.1" 200 -
*.170.110.16 - - [19/Jul/2016 13:42:09] "GET /config HTTP/1.1" 200 -
Completed: 100.0%
[-] register_background_thread called
[-] register_background_thread: queueing
*.170.110.16 - - [19/Jul/2016 13:42:10] "GET /data HTTP/1.1" 200 -
*.170.110.16 - - [19/Jul/2016 13:42:10] "GET /static/forts/Instinct_large.png HTTP/1.1" 200 -
*.170.110.16 - - [19/Jul/2016 13:42:10] "GET /static/forts/Valor_large.png HTTP/1.1" 200 -
*.170.110.16 - - [19/Jul/2016 13:42:10] "GET /favicon.ico HTTP/1.1" 404 -
#Crash happened here. Maybe related to auto-refresh?
*.170.110.16 - - [19/Jul/2016 13:42:19] "GET /data HTTP/1.1" 200 -

**Comment by talentedmrripley** [comment]
Go here: 

https://developers.google.com/maps/documentation/javascript/get-api-key

and get a key, and change the value of gmaps_key in your credentials.js to your new key.

**Comment by Naramsim** [comment]
Steps to read:
https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Google-Maps-API:-a-brief-guide-to-your-own-key

**Comment by JZ6** [comment]
fixed

**Comment by SeeingBlue** [comment]
Thanks guys. I figured that's what'd I have to do.
