### ISSUE TITLE
Module google.protobuf is missing

### ISSUE THREAD

**Issue by Truesh00ter** [AHAAAAAAA/PokemonGo-Map#407]
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discordapp.com/invite/qbpVH6b).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

This issue probably falls under the scope of Discord, sadly the link has expired and I can't join through the link.

### Environment info
Operating System:
Ubuntu 15.04
Installed version of Python:
2.7

### Steps to reproduce
1. python example.py -u USERNAME -p PASSWORD -l "LOCATION" -st 3 -H 0.0.0.0 -P 5000
2. pip install google.protobuf

### What have you tried?
	   84  wget https://github.com/AHAAAAAAA/PokemonGo-Map/archive/master.zip
	   87  unzip master.zip -d pokemonMap
	   89  cd pokemonMap/
	   91  cd PokemonGo-Map-master/
	   97  wget https://bootstrap.pypa.io/get-pip.py
	   99  python get-pip.py
	  101  pip install --upgrade -r requirements.txt
	  103  nano credentials.json
	  104  python example.py -u USERNAME -p PASSWORD -l "LOCATION" -st 3 -H 0.0.0.0 -P 5000
	  105  pip install flask
	  106  python example.py -u USERNAME -p PASSWORD -l "LOCATION" -st 3 -H 0.0.0.0 -P 5000
	  107  pip install flask_googlemaps
	  108  python example.py -u USERNAME -p PASSWORD -l "LOCATION" -st 3 -H 0.0.0.0 -P 5000
	  109  pip install requests
	  110  python example.py -u USERNAME -p PASSWORD -l "LOCATION" -st 3 -H 0.0.0.0 -P 5000
	  111  pip install google.protobuf

### Logs or other output that would be helpful
	Traceback (most recent call last):
	  File "example.py", line 19, in <module>
		import pokemon_pb2
	  File "/root/pokemonMap/PokemonGo-Map-master/pokemon_pb2.py", line 6, in <module>
		from google.protobuf import descriptor as _descriptor
	ImportError: No module named google.protobuf

### Other
I also had the same issue for:
- flask
- flask_googlemaps
- requests

But I've solved those by:
pip install flask
pip install flask_googlemaps
pip install requests

pip install google.protobuf comes back with:
pip install google.protobuf         
	Collecting google.protobuf
	Could not find a version that satisfies the requirement google.protobuf (from versions: )
	No matching distribution found for google.protobuf

Strange thing is I've got it working on a VM since Day 0 but that is running Xubuntu 16.04 LTS which was freshly installed especially for this PokemonGo-Map to test with. But I'm now trying to get it working on my VPS for webservice purposes.

**Comment by Truesh00ter** [comment]
https://github.com/AHAAAAAAA/PokemonGo-Map/blob/master/requirements.txt
Already has protobuf 2.6.1 in the default pull.
I'm using it but it doesn't change anything.

**Comment by Truesh00ter** [comment]
I'm now getting this far, error with installing gpsoauth:
	Failed building wheel for pycryptodomex
	Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-_4213X/pycryptodomex/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-6lqEL0-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-_4213X/pycryptodomex/

**Comment by TheRealGitCub** [comment]
I am getting the `Failed building wheel` error as well. 

Running Python 2.7.6 and pip 8.1.2 on Ubuntu 14.04.4 LTS.

**Comment by TheRealGitCub** [comment]
**Update**: Issue solved! I looked a little closer at the error and noticed errors relating to `gcc` missing. I fixed this by running `apt-get install python2.7-dev`

**Comment by Truesh00ter** [comment]
Cheers!
Works now, I needed `build-essentials` to make it work, though the servers are down now but `example.py` runs just fine now.

**Comment by TanishaWij** [comment]
I am still having this issue! how do i fix it?

**Comment by zjaved** [comment]
How did you install build-essentials. I'm having the same problem Trush00ter had in installing  gpsoauth

**Comment by Truesh00ter** [comment]
Sigh.
http://lmgtfy.com/?q=how+to+install+build-essentials

**Comment by zjaved** [comment]
I should have been more clear...

When I do 

sudo apt-get update
sudo apt-get install build-essential

I get apt-get not found. Tried installing various libraries they suggested, but it didn't seem to work. If you don't know that's alright...thanks for the snarky answer to my probably naive question.

**Comment by mkody** [comment]
@zjaved `apt` is a package manager for Debian and Debian-based GNU/Linux distributions. It's like homebrew, for short.
On OSX, you need to have XCode and the command line tools from XCode installed, it installs the majority of tools we get from Debian's (and Ubuntu's) `build-essential`.

**Comment by zjaved** [comment]
@mkody got it. thanks. I got it to work on my windows machine at least.

**Comment by julianghionoiu** [comment]
On RHEL 7.2 (aws.micro) you need the following:
```
yum group install "Development Tools"
yum install python-devel.x86_64
```
