### ISSUE TITLE
Wrong username/password

### ISSUE THREAD

**Issue by Plop** [AHAAAAAAA/PokemonGo-Map#408]
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discordapp.com/invite/qbpVH6b).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System: Debian 8

Installed version of Python: 2.7.9

**Username/Password tested on the Trainer Club and successfully connected.**

### Steps to reproduce
1.  python example.py -a ptc -u MY_username -p MY_password -l "Location" -st 8 -L fr -dg -ar 5 -dp -p 5000
2. ???
3. Wrong username/Password

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

```
[!] PTC login for: username
127.0.0.1 - - [19/Jul/2016 19:50:25] "GET /data HTTP/1.1" 200 -
Your username or password is incorrect. You have 2 attempts left before you will be locked out of your account for 15 minutes.
Exception in thread search_thread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "example.py", line 581, in main
    api_endpoint, access_token, profile_response = login(args)
  File "example.py", line 92, in memoizer
    cache[key] = obj(*args, **kwargs)
  File "example.py", line 516, in login
    raise Exception('[-] Wrong username/password')
Exception: [-] Wrong username/password
```

**Comment by Naramsim** [comment]
Obviously you have to set YOUR username and YOUR password...

**Comment by Plop** [comment]
Obviously I have set MY username and MY password, and tested it manually on the Trainer Club, and it doesn't work.

**Comment by Naramsim** [comment]
It doesn't seem to the report you have attached.
Are you using google or PoGo auth? (in the app?)

**Comment by Plop** [comment]
I just wanted it to be anonymized.

Here is a full log with just the password removed : 

`root@autrui-web:/var/www/PokemonGo/PokemonGo-Acigne# python example.py -a ptc -u plopdsrepu -p MY_PASSWORD -l "Acigné, France" -st 8 -L fr -dg -ar 5 -dp -p 5000
[-] register_background_thread called
[-] register_background_thread: not running inside Flask so not starting thread
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
[-] register_background_thread called
[-] register_background_thread: initial registration
 * Debugger is active!
[+] Locale is fr
 * Debugger pin code: 488-866-251
[+] Getting initial location
[!] Your given location: Acigné, France
[!] lat/long/alt: 48.1336749 -1.533848 0.0
[!] PTC login for: plopdsrepu
Your username or password is incorrect. You have 4 attempts left before you will be locked out of your account for 15 minutes.
Exception in thread search_thread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "example.py", line 581, in main
    api_endpoint, access_token, profile_response = login(args)
  File "example.py", line 92, in memoizer
    cache[key] = obj(*args, **kwargs)
  File "example.py", line 516, in login
    raise Exception('[-] Wrong username/password')
Exception: [-] Wrong username/password
`

I'm using PoGo auth.

**Comment by talentedmrripley** [comment]
Does your password contain anything other than alphanumeric characters?  If so try changing to just alphanumeric and try it again.

**Comment by Plop** [comment]
Nope, it's only alphanumerical characters.

**Comment by Powback** [comment]
It's because of the port. 

python example.py -a ptc -u ploprepu -p MY_PASSWORD -p 5000

Notice the double p parameter. Port should be uppercase.

**Comment by Plop** [comment]
Godamn fu... It is. Sorry for bothering you, thanks for your help.

**Comment by ZombiePm** [comment]
-p "password" solved this error
