### ISSUE TITLE
small monsterr on map

### ISSUE THREAD

**Issue by kas212** [AHAAAAAAA/PokemonGo-Map#409]
http://prntscr.com/buwaus

**Comment by Temetz** [comment]
Update your version.
`git pull`

or re-clone the repository fully.

If that doesnt help, disable your cache or force reload `CTRL+F5`

**Comment by Sejadis** [comment]
yeah clearing the cache should fix that

**Comment by kas212** [comment]
already reclone and clearc cache http://prntscr.com/buwu8k

**Comment by kas212** [comment]
i lost lapras coz cant see on map :(

**Comment by talentedmrripley** [comment]
There were larger icons in an earlier version.  I've uploaded them here:
https://mega.nz/#!gBoFRQLD!SAemy-GuAtF6XMSGcjLolG-2uQQwRURZaigVQYNb-A0
You can copy them over the icons in the newer version if you want.
