### ISSUE TITLE
Pokestops still showing.

### ISSUE THREAD

**Issue by Majamulli** [AHAAAAAAA/PokemonGo-Map#41]
Just wanted to leave a quick feedback that the Pokestops are still showing, even with the new version that was uploaded about an hour ago. At least for me.

**Comment by AHAAAAAAA** [comment]
Clear your cache, that's probably causing the issue.

**Comment by Majamulli** [comment]
You were right indeed. Sorry for that, should've thought of that myself.. Thanks for the fast reply.
