### ISSUE TITLE
Retrying_api_req: request error (Unexpected end-group tag.)

### ISSUE THREAD

**Issue by Linear-M** [AHAAAAAAA/PokemonGo-Map#412]
Occuring 2-5 times per loop - this may also be the error which is causing (picture):
![image](https://cloud.githubusercontent.com/assets/2018383/16961243/8a304ae0-4de4-11e6-996d-64f3bfc966f4.png)

Picture of log (picture): 
![image](https://cloud.githubusercontent.com/assets/2018383/16961275/a5f8b7f8-4de4-11e6-9cf1-5f34b1a234b9.png)

**Comment by Sejadis** [comment]
its 'cause of niantics servers

**Comment by HenrySia** [comment]
It appears this issue came from tejado's PoGo API and tejado has recently fixed it. [https://github.com/tejado/pgoapi/issues/31](url)

I'm not familiar with PokemonGo-Map codebase, but perhaps we can pull the fix?

**Comment by oceanor** [comment]
server issues, tejado pushed a commit but it's not fixing it (of course lol), just showing a friendly message instead of an error :D

**Comment by Linear-M** [comment]
Yeah - seems the fix wa sjust to show a more appropriate error. Any idea if this is causing the unexpected error on the map?

**Comment by HenrySia** [comment]
Problem that I have is PokemonGo-Map doesn't recover from it even after the server is back up. It won't show any pokemon on the map.

**Comment by Linear-M** [comment]
Just doing some testing - looks like a malformed call to google maps API on each Pokemon API req failure causing issue.

**Comment by activars** [comment]
seems like niantics servers changes

**Comment by Linear-M** [comment]
Google Map error occuring <5s after load regardless of changes from the script

**Comment by TheWebSmith** [comment]
Why don't you read the message. It clearly says that you should look into the JavaScript console for more details. When I got this error the JavaScript console showed that the quota of the google maps api key was reached.

I guess the Unexpected end-group tag is unrelated to the map not showing up, because I get this message often, when the servers are a little unstable, but the map is still kind of working.

**Comment by Linear-M** [comment]
Forgot to add a new gmap key to the site..closing...

**Comment by Linear-M** [comment]
@websmith I have been using this on a couple vps' hard to keep track of which have keys :-)
