### ISSUE TITLE
Cant get Server to work outside Network

### ISSUE THREAD

**Issue by Maxxxel** [AHAAAAAAA/PokemonGo-Map#414]
### Environment info
Operating System: Windows 10 64Bit

Installed version of Python: 2.7

### Steps to reproduce
1. i set -H 192.168.178.31 -P 5000

2. i went to my FritzBox and added a PortForward at my internal IP 192.168.178 at source 5000 and  range 5000 - 500 UDP and TCP ( i also tried setting my source to 80 and range 5000 - 5000 UDP and TCP and source 5000 and range 80 - 80 TCP and UDP).

3. i can open the Map in the Network via 192.168.178.31:5000 but not from external: myExternalIP:5000

4. if i use as port a port opened by an UPNP Device it works, but now not anymore (i guess the device stopped sending)

i would talk to you via Discord but your invitation is outdated.

**Comment by RedFalconv2** [comment]
Cannot reproduce on Windows 10 & Windows 7.

**Comment by talentedmrripley** [comment]
Works for me forwarding ports from pfsense to the Windows box running it.  You only need TCP.  Try setting -H to 0.0.0.0 also make sure that the IP of your Windows box hasn't changed.  Might want to make it static.

I am not familiar with FritzBox but here's their documentation.  Check it to make sure you didn't miss something.

https://en.avm.de/service/fritzbox/fritzbox-7390/knowledge-base/publication/show/893_Configuring-static-port-sharing/

**Comment by Maxxxel** [comment]
0.0.0.0 is the answer!!!! thank you

**Comment by nkolosov** [comment]
I start example.py with params "-H 0.0.0.0 -P 9999" at my VPS and when I try "wget http://mydomain:9999" from VPS console it working, but when I try do it from my home desktop, I get "Connection refused". What I need to do?

**Comment by mkody** [comment]
@nkolosov Dot you have iptables or any other firewall software installed on your VPS? Or maybe something to control firewall rules trough your hosting company's webpanel?
