### ISSUE TITLE
Change 'print' call on the logger.

### ISSUE THREAD

**Issue by alexpantyukhin** [AHAAAAAAA/PokemonGo-Map#417]
Hi. It looks not good to have `print` . What if change that calls with logger.info?

**Comment by bengalaviz** [comment]
I just send a push #429 to implement this.

**Comment by DerScreever** [comment]
Im sorry, but we dropped the support for the master branch (example.py). 
This branch is deprecated.  
The new branch contains a much cleaner structure so pls report only issues related to the develop branch. 

Your development team
