### ISSUE TITLE
[Problem] Can't start application on my VPS

### ISSUE THREAD

**Issue by nkolosov** [AHAAAAAAA/PokemonGo-Map#422]
I'd started application with params"-H 0.0.0.0 -P 9999" at my VPS.

When I try execute "wget http://mydomain:9999" from VPS console it working.
But when I try do it from my home desktop, I get "Connection refused". 

What I need to do?

At VPS:
```

$ netstat -an | grep '9999'
tcp        0      0 0.0.0.0:9999            0.0.0.0:*               LISTEN  
```

At home desktop:
```
nkolosov@nkolosov-laptop:~$ sudo tcpdump -n host mydomain and port 9999 
listening on eth0, link-type EN10MB (Ethernet), capture size 262144 bytes
01:08:58.796798 IP *.*.*.*.57678 > *.*.*.*.9999: Flags [S], seq 3809825663, win 29200, options [mss 1460,sackOK,TS val 2732318 ecr 0,nop,wscale 7], length 0
01:08:58.798620 IP *.*.*.*.9999 > *.*.*.*..57678: Flags [R.], seq 0, ack 3809825664, win 0, length 0
```

**Comment by Znuff** [comment]
Are you sure "mydomain.com" doesnt' also resolve to IPv6, and you are accessing it on IPv6, but not actually listening to IPv6? For IPv6 you need to do `-H ::`

**Comment by nkolosov** [comment]
I tried use -H ::, but it not working too

**Comment by talentedmrripley** [comment]
Is there a firewall on your VPS?  Have you allowed port 9999 through it?

**Comment by nkolosov** [comment]
I'm enable outgoing connections from iptables, ufw is disabled (Ubuntu 14.04)

```
$ sudo iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:9999

```

**Comment by macgngsta** [comment]
most likely your VPS does not allow external connections by default. you can hit it from your VPS console because your are on that private network. 

highly likely that you will need to either punch a hole through the firewall, turn off something like selinux or properly point your domain back to your VPS

**Comment by nkolosov** [comment]
But connections to port 80 (Apache2 with my web-page) is working without any problems

**Comment by Jared87** [comment]
If nothing works you yould try to map a path on your Apache2 to the port of the script.
https://www.digitalocean.com/community/tutorials/how-to-use-apache-http-server-as-reverse-proxy-using-mod_proxy-extension

**Comment by nkolosov** [comment]
Thank you, it working!

**Comment by Jerome-lara** [comment]
@nkolosov Can you tell me the URL? I get the map loaded up. But no pokemon displayed :(

**Comment by nkolosov** [comment]
@Jerome-lara what displaying on console log? Are you see errors at browser developer console ('F12' in Chrome)

**Comment by Jerome-lara** [comment]
Nope, just like #428

**Comment by Jerome-lara** [comment]
@nkolosov Nope, just like #428
