### ISSUE TITLE
it is possible to save the pokemon data?

### ISSUE THREAD

**Issue by isnuryusuf** [AHAAAAAAA/PokemonGo-Map#425]
Save data to csv or json or another text file

**Comment by cprogrammer1994** [comment]
you can see: `localhost:5000/raw_data`

**Comment by isnuryusuf** [comment]
thnks for your reply, but when i stop the service, the data become unavailable, can we keep the data to fix location and continue load the data every time start the service

**Comment by bmanturner** [comment]
Go for it. Python supports a wide variety of databases.

**Comment by jangrewe** [comment]
Just a thought, but: is it really necessary? The data expires so quickly and gets updated so fast...

**Comment by bmanturner** [comment]
You could look for trends/spawns.
