### ISSUE TITLE
retrying_get_profile: get_profile returned no-len payload, retrying_api_req: request error (unexpected end-group tag.)

### ISSUE THREAD

**Issue by Coraz97** [AHAAAAAAA/PokemonGo-Map#427]
I'm constantly getting errors when I run the script described in the reddit post, like `"retrying_get_profile: get_profile returned no-len payload, retrying"` constantly, and sometimes in between I get `"retrying_api_req: request error (unexpected end-group tag.), retrying"`.
Both username and password are correct, and there are no misspellings.

### Environment info
Operating System: Windows 10 64 bit

Installed version of Python: 2.7.12

I just tried, and on mobile I can play the game, so most likely it's not a server issue.
If it helps, I'm running a version of the code downloaded approx. 5 hours ago.

**Comment by VetLee** [comment]
Not an issue: servers are down

**Comment by foodforarabbit** [comment]
also if you're getting that with ptc, try logging in with google.

add `-a "google"` and use your gmail username / password

**Comment by abderrahmane-tj** [comment]
@Coraz97 probably because servers are down http://www.mmoserverstatus.com/pokemon_go

**Comment by Coraz97** [comment]
I can swear they were up when I tried. Oh, well, 'tis better like this.

**Comment by zaphim12** [comment]
I'm getting this same issue after retrying multiple times after checking that the server is up.

**Comment by Fakerthantrump** [comment]
server down again

**Comment by zaphim12** [comment]
It wasn't down when I tried.  I could log on to the actual game with my phone at the same time I ran the program (using a different account)

**Comment by Fakerthantrump** [comment]
well try again 1st when the server is fully up and stable for at least 30~minute

**Comment by medghaim** [comment]
Closing. Feel free to reopen if this issue persists.

**Comment by malosaa** [comment]
server is up and i getting that error

**Comment by willouuu** [comment]
Error again, but I can play to game

**Comment by Ryaaaan** [comment]
The error also occurs when the Pokemon Trainer Club (if you're using `-a ptc`) is experiencing issue - NOT JUST NIANTIC. If you use `-a google` rather than `-a ptc` the script will run (assuming Niantic's Servers are up) but you now have to use your google credentials...

**Comment by Ryaaaan** [comment]
For example... if you can log onto the game and everything seems fine - but you still get this error... try running the following:

`python example.py -a google -u GOOGLEUSERNAME -p GOOGLEPASSWORD -l "Lancaster, PA" -st 10`

GOOGLEUSERNAME = gmail account
GOOGLEPASSWORD = your gmail password
