### ISSUE TITLE
I get the map loaded up. But no pokemon displayed

### ISSUE THREAD

**Issue by SomebodyEpic** [AHAAAAAAA/PokemonGo-Map#428]
I get the map loaded up. But no pokemon displayed. 
![31fadcc2c00c4117aa1efe9ce30f92dc](https://cloud.githubusercontent.com/assets/20545086/16964524/d8182fe8-4e0c-11e6-92ba-b4be8d7ed11a.png)

![25c2481aecf543d489621e7323f0f372](https://cloud.githubusercontent.com/assets/20545086/16964541/fb4e22e2-4e0c-11e6-8c9f-7a04c886fcec.png)

**Comment by CarlSchou** [comment]
Servers are down

**Comment by Lazarix** [comment]
servers are busy at the moment.

**Comment by SomebodyEpic** [comment]
Ok,ty very much for answer
