### ISSUE TITLE
Getting a Google API fails

### ISSUE THREAD

**Issue by del6597** [AHAAAAAAA/PokemonGo-Map#433]
The directions for getting a Google Maps API are vague.  Following the instructions did not yield an API key as expected.  Turns out there are extra steps to take such as enabling the APIs in the Google API dashboard.

After creating a new project in the API dashboard, create an API Key and select Browser when prompted for the type.  Use this new key in the config file.  Running it right off the bat does not work and you need to enable some APIs on the dashboard overview menu.
The following APIs need to be enabled:
- Google Maps Directions API 	
- Google Maps Distance Matrix API 	
- Google Maps Elevation API 	
- Google Maps Geocoding API 	
- Google Maps JavaScript API 	
- Google Places API Web Service 

Without having these enabled your map will show up for a split second and then grey out.

**Comment by stormageddon** [comment]
Hmm you must have had a strange flow. According to the Google API docs, just clicking "continue" should have enabled the API's. I know when I did it, that's what happened - no extra steps were necessary.

https://developers.google.com/maps/documentation/javascript/get-api-key#key

**Comment by del6597** [comment]
"Works for me" does not mean additional clarification shouldn't be added for those users experiencing the same issue as me.

**Comment by CSCG** [comment]
Weird. I know as a fact, under this project's umbrella on my API Console I've *only* got Google Maps Javascript API (Browser) enabled. But  -  I will note, the API key I first used got taken down almost immediately for rate-limiting.

The second one, I've been using on a public radar for the last 40 hours no issue. I think @stormageddon is right in the sense that some of those random 'continue' or 'continue with my project' buttons are key. What was the console error response from Gmaps, in your case, @del6597 ?

**Comment by del6597** [comment]
https://developers.google.com/maps/documentation/javascript/error-messages#api-not-activated-map-error

**Comment by CSCG** [comment]
Yep. That's usually a sign that the JS API key needs to be regenerated *or* you need to wait five minutes. I know, it doesn't make much sense, but I dealt with that one myself and it cleared itself up with no extra API auth's within a couple minutes. Regardless, this would be good for the readme. My experience shows the Google Console is kinda rough to work with...

"**The Google Maps JavaScript API** is not activated on your API project. You may need to enable the Google Maps JavaScript API under APIs in the Google API Console.

See Obtaining an API key."

**Comment by del6597** [comment]
Waiting five minutes did not work in my case.  Regenerating a new key did not work either.  I had to manually enable APIs for this to work.  I hope to save others the two hour long headache of debugging I had to go through to actually figure out the root cause.  I've never used Google APIs before so it was not immediately obvious.

**Comment by del6597** [comment]
This wasn't a question. This was a request for improving the documentation on how to get a Google API key because in some instances there are additional steps to take.
