### ISSUE TITLE
retrying_api_req: request error (Unexpected end-group tag.), retrying

### ISSUE THREAD

**Issue by lex095** [AHAAAAAAA/PokemonGo-Map#435]
Console write:
retrying_api_req: request error (Unexpected end-group tag.), retrying

The map is not Pokemon....

**Comment by Architektor** [comment]
Niantic servers unstable. Stop duping issues

**Comment by lex095** [comment]
I'm sorry , okay, I'm waiting for

**Comment by linuxboytoo** [comment]
Are people sure this is not a temp ban issue?  Niantic has been getting smart about banning stuff like this in Ingress, I suspect they will/are doing the same with PGO

**Comment by Dayjo** [comment]
@linuxboytoo I agree, this could potentially be some form of banning. I can access the servers fine on the game, but with my API account I get this error (when 30 minutes ago it worked ok). It also could be just some form of rate limiting?
