### ISSUE TITLE
Uncaught SyntaxError: Unexpected string

### ISSUE THREAD

**Issue by CezaryRynkowski** [AHAAAAAAA/PokemonGo-Map#436]
### Environment info
Operating System: Windows 10

Installed version of Python: 2.7.3

### Steps to reproduce
1.Pull git repo
2.Run example.py
3.Go to localhost:5000

Im geeting js error : (index):51 Uncaught SyntaxError: Unexpected string

line51 - > `        var raw_markers = [{'disappear_time': -1, 'infobox': 'Start position', 'key': 'start-position', 'lat': 52.182614, 'lng': 21.0267889, 'type': 'custom', 'icon': '//maps.google.com/mapfiles/ms/icons/red-dot.png'}, {'disappear_time': 1468962362.388, 'infobox': u"<div><b>Weedle</b><span> - </span><small><a href='http://www.pokemon.com/us/pokedex/13' target='_blank' title='View in Pokedex'>#13</a></small></div><div>Disappears at - 23:06:02 <span class='label-countdown' disappears-at='1468962362.39'></span></div><div><a href='https://www.google.com/maps/dir/Current+Location/52.1824559855,21.0236226372' target='_blank' title='View in Maps'>Get Directions</a></div>", 'key': u'471932cfcd3', 'lat': 52.18245598550861, 'lng': 21.023622637157956, 'type': 'pokemon', 'icon': 'static/icons/13.png'}, {'disappear_time': 1468962272.541, 'infobox': u"<div><b>Weedle</b><span> - </span><small><a href='http://www.pokemon.com/us/pokedex/13' target='_blank' title='View in Pokedex'>#13</a></small></div><div>Disappears at - 23:04:32 <span class='label-countdown' disappears-at='1468962272.54'></span></div><div><a href='https://www.google.com/maps/dir/Current+Location/52.1810812258,21.0263462573' target='_blank' title='View in Maps'>Get Directions</a></div>", 'key': u'471932cf0ef', 'lat': 52.18108122578826, 'lng': 21.026346257332126, 'type': 'pokemon', 'icon': 'static/icons/13.png'}, {'disappear_time': 1468962481.369, 'infobox': u"<div><b>Pidgey</b><span> - </span><small><a href='http://www.pokemon.com/us/pokedex/16' target='_blank' title='View in Pokedex'>#16</a></small></div><div>Disappears at - 23:08:01 <span class='label-countdown' disappears-at='1468962481.37'></span></div><div><a href='https://www.google.com/maps/dir/Current+Location/52.1826467008,21.0277248871' target='_blank' title='View in Maps'>Get Directions</a></div>", 'key': u'471932cef1b', 'lat': 52.18264670081894, 'lng': 21.027724887108608, 'type': 'pokemon', 'icon': 'static/icons/16.png'}, {'disappear_time': 1468962569.541, 'infobox': u"<div><b>Rattata</b><span> - </span><small><a href='http://www.pokemon.com/us/pokedex/19' target='_blank' title='View in Pokedex'>#19</a></small></div><div>Disappears at - 23:09:29 <span class='label-countdown' disappears-at='1468962569.54'></span></div><div><a href='https://www.google.com/maps/dir/Current+Location/52.1812917032,21.0280118969' target='_blank' title='View in Maps'>Get Directions</a></div>", 'key': u'471932cf221', 'lat': 52.181291703199065, 'lng': 21.028011896932405, 'type': 'pokemon', 'icon': 'static/icons/19.png'}, {'disappear_time': 1468962300.935, 'infobox': u"<div><b>Zubat</b><span> - </span><small><a href='http://www.pokemon.com/us/pokedex/41' target='_blank' title='View in Pokedex'>#41</a></small></div><div>Disappears at - 23:05:00 <span class='label-countdown' disappears-at='1468962300.93'></span></div><div><a href='https://www.google.com/maps/dir/Current+Location/52.1825582907,21.0281996937' target='_blank' title='View in Maps'>Get Directions</a></div>", 'key': u'471932ceeef', 'lat': 52.18255829072503, 'lng': 21.028199693667837, 'type': 'pokemon', 'icon': 'static/icons/41.png'}, {'disappear_time': 1468962829.388, 'infobox': u"<div><b>Weedle</b><span> - </span><small><a href='http://www.pokemon.com/us/pokedex/13' target='_blank' title='View in Pokedex'>#13</a></small></div><div>Disappears at - 23:13:49 <span class='label-countdown' disappears-at='1468962829.39'></span></div><div><a href='https://www.google.com/maps/dir/Current+Location/52.1839145275,21.0246437659' target='_blank' title='View in Maps'>Get Directions</a></div>", 'key': u'471932ce177', 'lat': 52.18391452748632, 'lng': 21.02464376585349, 'type': 'pokemon', 'icon': 'static/icons/13.png'}, {'disappear_time': 1468962838.725, 'infobox': u"<div><b>Spearow</b><span> - </span><small><a href='http://www.pokemon.com/us/pokedex/21' target='_blank' title='View in Pokedex'>#21</a></small></div><div>Disappears at - 23:13:58 <span class='label-countdown' disappears-at='1468962838.72'></span></div><div><a href='https://www.google.com/maps/dir/Current+Location/52.180007723,21.0237234268' target='_blank' title='View in Maps'>Get Directions</a></div>", 'key': u'471932cf861', 'lat': 52.180007722998056, 'lng': 21.023723426836465, 'type': 'pokemon', 'icon': 'static/icons/21.png'}, {'disappear_time': 1468962838.914, 'infobox': u"<div><b>Pidgey</b><span> - </span><small><a href='http://www.pokemon.com/us/pokedex/16' target='_blank' title='View in Pokedex'>#16</a></small></div><div>Disappears at - 23:13:58 <span class='label-countdown' disappears-at='1468962838.91'></span></div><div><a href='https://www.google.com/maps/dir/Current+Location/52.1865862582,21.0256739826' target='_blank' title='View in Maps'>Get Directions</a></div>", 'key': u'471932cd8a1', 'lat': 52.18658625815031, 'lng': 21.025673982617615, 'type': 'pokemon', 'icon': 'static/icons/16.png'}, {'disappear_time': 1468962829.725, 'infobox': u"<div><b>Squirtle</b><span> - </span><small><a href='http://www.pokemon.com/us/pokedex/7' target='_blank' title='View in Pokedex'>#7</a></small></div><div>Disappears at - 23:13:49 <span class='label-countdown' disappears-at='1468962829.72'></span></div><div><a href='https://www.google.com/maps/dir/Current+Location/52.1796925413,21.024018233' target='_blank' title='View in Maps'>Get Directions</a></div>", 'key': u'471932cf80b', 'lat': 52.179692541349844, 'lng': 21.024018232984975, 'type': 'pokemon', 'icon': 'static/icons/7.png'}, {'disappear_time': 1468962803.388, 'infobox': u"<div><b>Rattata</b><span> - </span><small><a href='http://www.pokemon.com/us/pokedex/19' target='_blank' title='View in Pokedex'>#19</a></small></div><div>Disappears at - 23:13:23 <span class='label-countdown' disappears-at='1468962803.39'></span></div><div><a href='https://www.google.com/maps/dir/Current+Location/52.1838610235,21.0244650683' target='_blank' title='View in Maps'>Get Directions</a></div>", 'key': u'471932ce183', 'lat': 52.18386102353962, 'lng': 21.02446506826066, 'type': 'pokemon', 'icon': 'static/icons/19.png'}];
`
Its probably problem with u in  `'key': u'471932cf80b'` and ` 'infobox': u"<div>` etc

**Comment by NgJason** [comment]
I had issues until I upgraded to 2.7.12. Try upgrading your python.

**Comment by nkolosov** [comment]
I have same problem. In developer console "Uncaught SyntaxError: Unexpected token ="
This line:
`function addMarker(options = {}) {`

Python 2.7.12.

By this reason as I understand, not working autorefresh map =(

**Comment by slbug** [comment]
@nkolosov will work only in chrome (49+) or firefox

**Comment by CezaryRynkowski** [comment]
Chrome 51 here
I trying to update python to 2.7.4 but still...

**Comment by nkolosov** [comment]
I'm just removed default values for js function and it working at other browsers :)

**Comment by braingineer** [comment]
@nkolosov what do you mean by that

@DerScreever how is this a server issue? I get the other one (end-group deal), but this?   I just want to get this working =)

**Comment by Kudusch** [comment]
\+ 1

Experiencing this also. Problem occurs on Chrome (51) and Safari (9.1).
The script runs without errors.

<img width="1280" alt="bildschirmfoto 2016-07-20 um 02 19 46" src="https://cloud.githubusercontent.com/assets/1136612/16971042/94f6bb12-4e20-11e6-907c-ee76c228d46f.png">

**Comment by braingineer** [comment]
Ya, I'm able to run the /data route just fine.

**Comment by SAudelOG** [comment]
I'm having the same issue on chrome and safari, it just render the map at the first time, right before beginning searching pokemons

**Comment by ztschir** [comment]
I seem to have fixed this issue by changing the the following:

line 836
OLD:        label = LABEL_TMPL.format(**pokemon)
NEW:       label = str(LABEL_TMPL.format(**pokemon))


line 842:
OLD:             'key': pokemon_key,
NEW:            'key': str(pokemon_key),

I know the person in charge of the repo doesn't want any pull requests atm, so idk when this will be fixed.

**Comment by SAudelOG** [comment]
I fixed it encoding the strings that comes in "label" and "key" that has the same effect of @ztschir solution
````
        label = label.replace('\n', '').encode('utf-8')

        pokeMarkers.append({
            'type': 'pokemon',
            'key': pokemon_key.encode('utf-8'),
            'disappear_time': pokemon['disappear_time'],
            'icon': 'static/icons/%d.png' % pokemon["id"],
            'lat': pokemon["lat"],
            'lng': pokemon["lng"],
            'infobox': label
        })

**Comment by CezaryRynkowski** [comment]
@ztschir changing this lines resolved my problem

**Comment by xaho** [comment]
@ztschir these changes resolved this problem for a friend of mine as well 
(He has OSX El Capitan, issue was on Safari, Chrome and Firefox)
