### ISSUE TITLE
Issue by trying tu run

### ISSUE THREAD

**Issue by 4BHIFGartner** [AHAAAAAAA/PokemonGo-Map#438]
![unbenannt](https://cloud.githubusercontent.com/assets/17762260/16967738/f103c96a-4e0a-11e6-9f54-51e17a352293.PNG)

i tryed it like its explained but it fails,
i got a email by google witch said me that they ragistered a new login mybe a problem with that

**Comment by jangrewe** [comment]
servers down? if you can't run the game, the script most likely won't work either.

**Comment by madjapahit** [comment]
i have same problem, rpc session token was okay, but pokemon server api have same strange output and script cant hold on.

maybe pokemon server is down?
