### ISSUE TITLE
After every step a new background thread is created that runs main and tries to login again and again

### ISSUE THREAD

**Issue by JZ6** [AHAAAAAAA/PokemonGo-Map#44]
http://pastebin.com/W4pP3Xeq

I am working on  a fix rn

**Comment by marauder37** [comment]
If you have any questions while you're fixing I'll try to help. Remember that the thread runs main() once and finishes, so a new thread must be created each time.  Certainly if we could avoid signing in every time the thread runs that would be great.

**Comment by JZ6** [comment]
Ya i agree with you here,
and i ve being informed that the threading implementation was your idea, so what would be the best option do you think?

**Comment by favll** [comment]
Ohhh that makes so much sense. So simply the indentation is faulty. Currently the background thread is created if the while loop stepping through the steps.

**Comment by JZ6** [comment]
perhaps have a check for the access token to request a login if only required

**Comment by JZ6** [comment]
@favll so we unindent register_background_thread() to fix it?

**Comment by favll** [comment]
Yes, but the code will still try to login and retrieve an access token again. There seems to be an issue with that.

**Comment by JZ6** [comment]
I ve decided to move accestoken requests outside of the main thread, lets go from there

**Comment by JZ6** [comment]
yes @favll because it requests a new token for every main thread

**Comment by JZ6** [comment]
I think ive fixed it goin for  a test rn

**Comment by JZ6** [comment]
ok its good submitting a pull request now

**Comment by favll** [comment]
Issue #20 is related to this.

**Comment by marauder37** [comment]
I'll have a look at the PR when it comes in. Unindenting register_background_thread() so it's run once as the very last statement in main() will be a huge benefit. 

For the access tokens, things would be improved by 
1. requesting them in a separate function
2. in that function, checking whether we already have them and if so not logging in again
3. still calling login from main() each time, it's probably still the best place for it. You don't want to delay Flask startup and reduce responsiveness on the main thread while a bunch of login stuff happens

**Comment by marauder37** [comment]
If I may, I'm going to keep this open until the PR is in

**Comment by AHAAAAAAA** [comment]
PR posted [here](https://github.com/AHAAAAAAA/PokemonGo-Map/pull/45). Let's see if it fixes these issues!

**Comment by JZ6** [comment]
@marauder37 I ve fulfilled all 3 requirements, @AHAAAAAAA merge when you are ready

**Comment by JZ6** [comment]
closed
