### ISSUE TITLE
[FR] Separate Storage, Worker and Frontend

### ISSUE THREAD

**Issue by jangrewe** [AHAAAAAAA/PokemonGo-Map#440]
(This should probably be flagged as a Feature Request)

Would it be possible to have one "Storage" (or: data source for the frontend) and multiple "Workers" (which use the Storage as their data sink), so that multiple locations could be updated?

That way you could have multiple locations with smaller step counts, instead of doing just one update with a very high (and slow) step count.

Reason: We're organizing the people in our city in multiple districts with multiple hotspots, and updating the whole city, or even just a whole district, wouldn't finish before everything's expired again ;-)

**Comment by Plop** [comment]
Would totally love this. Would be really cool, I also have to separate the city in multiple districts, and it's bothering...
