### ISSUE TITLE
RFC: Status lines always show the same lat/long

### ISSUE THREAD

**Issue by MikeDX** [AHAAAAAAA/PokemonGo-Map#446]
Given any console log, when searching for pokemon within the loop (lets say 1 - 25 for a 5 step pass)

Every line output is always the same

[-] looping: step n of 25
[+] Searching for Pokemon at location X.XXXXXX -Y.YYYYYY

Would it / should it be the actual lat / long of the point in which the actual search is taking place rather than the origin?

**Comment by Sejadis** [comment]
it does change for me


[-] looping: step 8 of 100
[+] Searching for Pokemon at location 52.41187 12.547851
Completed: 8.0%
[-] looping: step 9 of 100
[+] Searching for Pokemon at location 52.41437 12.547851
Completed: 9.0%
[-] looping: step 10 of 100
[+] Searching for Pokemon at location 52.41687 12.547851

**Comment by MikeDX** [comment]
DOH! It does for me too, I just wasnt paying enough attention to the correct part!
