### ISSUE TITLE
gmaps_key is hardcoded - usage limited to 25k requests /24h

### ISSUE THREAD

**Issue by alskgj** [AHAAAAAAA/PokemonGo-Map#447]
Currently a google map api key is hardcoded in credentials.json.

If the usage limit (25k requests / 24h) is exceeded, the application will stop working: https://developers.google.com/maps/documentation/javascript/usage.

This is fixed by replacing the hardcoded api key with another key, which are obtainable here:
https://developers.google.com/maps/documentation/javascript/get-api-key.

### Proposed fix
No hardcoded google maps key and allowing (forcing) user to supply own key.

**Comment by talentedmrripley** [comment]
This is mentioned on the Wiki here:

https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Google-Maps-API:-a-brief-guide-to-your-own-key

But I agree that it should be changed to force people to get their own.

**Comment by pskitz** [comment]
I'm constantly getting an error that says I've exceeded my daily quota despite having changed the api key for my own. I only get this when accessing it from the external IP as well, not LAN/localhost

**Comment by UCFCyborg** [comment]
@pskitz, I got around the error by using a VPN to run it along with changing the key.  My guess is Google blacklists the IP if you try to run the application without changing the key first.  Without a VPN I still get the error, maybe in 24 hours they will release it.  The other part of why I think it's a blacklisted IP is if you run the program with the maps key as an empty string you get the same error, meaning it's checking something else before it checks the key.  Searched for hours in here trying to find a workaround before I figure this out, I was afraid to post an issue as it was telling me I was using the old key, I thought I was skipping a step or something and didn't want to look like a fool!  Find a way to alter your external ip and it should and it should work!

**Comment by rohith94** [comment]
yes google blacklists that IP until  u opt for paid version if limit is exceeded

**Comment by UCFCyborg** [comment]
@rohith94 Does the blacklist expire at the end of the 24 hour period or is it permanent?
