### ISSUE TITLE
How secure is using Google credentials to log in?

### ISSUE THREAD

**Issue by stanparker** [AHAAAAAAA/PokemonGo-Map#450]
What happens with my Google password when I use it to log in using this script?

I changed my password before I ran it as a precaution, but I'm curious if that was necessary.

**Comment by macgngsta** [comment]
Unfortunately it is stored in memory for the duration of the execution on line 54 of example.py,
but for the most part, there doesn't seem to be anything shady going on.

On line 319, it is passed to the gpsoauth module:
https://github.com/simon-weber/gpsoauth

**Comment by mkody** [comment]
Probably as secure as login in to your Google account on your browser. 
@macgngsta linked to gpsoauth, which (by checking the code) only communicates with Google Servers.

**Comment by talentedmrripley** [comment]
@stanparker If you haven't already you should create a Pokemon Training Center account or a different Google account.  Don't use the one associated with your "main" account in case they start banning for this.

**Comment by stanparker** [comment]
Thanks for the responses, everyone.
