### ISSUE TITLE
ImportError: No module named gpsoauth

### ISSUE THREAD

**Issue by gitmon1234** [AHAAAAAAA/PokemonGo-Map#451]
Getting the following error from the current build:

Traceback (most recent call last):
  File "example.py", line 26, in <module>
    from gpsoauth import perform_master_login, perform_oauth
ImportError: No module named gpsoauth

**Comment by gitmon1234** [comment]
Nevermind, forgot to update my script with the new flags.

**Comment by Sejadis** [comment]
the requirements.txt changed a couple builds ago
just install the gpsoautch module

**Comment by zjaved** [comment]
Hi there, I'm doing 
 sudo pip install gpsoauth

and receiving 

Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-YQN0lX/pycryptodomex/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-cL55mR-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-YQN0lX/pycryptodomex/

Not sure what to do. 

When I run the gps command I get 
ImportError: No module named gpsoauth

**Comment by Memodellocos** [comment]
Can you paste more of the message above that? I think I had something similar but the message indicated I was missing another tool.

**Comment by jrami** [comment]
I'm getting a pretty similar error on debian 8.
`Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-xeRYqr/pycryptodomex/setup.py';exec(compile(getattr(tokenize, 'open', open)
(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-K_sBYQ-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-xeRYqr/pycryptodomex/`
