### ISSUE TITLE
Suggestion: Show current cell location on Map

### ISSUE THREAD

**Issue by vDrag0n** [AHAAAAAAA/PokemonGo-Map#454]
Is there a way to enable the current cell being looked at on the Map?

**Comment by Lunat1q** [comment]
if under cell you mean your phone, then yes, it's possible, but you need some software what will toss gps location from your phone to this app, like phone deamon which can send data via post to website.
If you ask about is it implemented now - then no, it's not.

**Comment by Trael** [comment]
@Lunat1q I think they mean what cell is being scanned by the scanner as it's stepping through - some sort of marker to indicate the path that the stepping is occuring would be useful if you're using this as a poke radar to determine whether the area you're searching in has been scanned recently.
