### ISSUE TITLE
Can WE??? Can we run more then one location at a time on one Map.

### ISSUE THREAD

**Issue by DumbDumb0509** [AHAAAAAAA/PokemonGo-Map#455]
Due to the Slow Update time for -st 5 or 10, can we run more then 1 location on a map so it updates 4 or 5 locations at the same time to get more up to date pokemon

**Comment by michi0987** [comment]
No you cant. In case to do that you would need more accounts. Single account can get data of one location at the time, that's how it works.

**Comment by DumbDumb0509** [comment]
is there any ways to speed the process of the search up?

**Comment by prikaz** [comment]
@michi0987: What? It's totally doable -- you can already just spawn another thread of the app and they will run in parallel. Just need to restructure the code a bit since the coordinates are currently globals..

**Comment by talentedmrripley** [comment]
@prikaz But that's not possible right now is it?  It only spawns a singe process.  
@DumbDumb0509 You could run multiple searches with smaller areas but I'm not aware of a way to combine those into a single map.  Just specify a port for each one.

**Comment by michi0987** [comment]
@prikaz it is but not right now
