### ISSUE TITLE
Store map info in database instead of program memory

### ISSUE THREAD

**Issue by hgentry** [AHAAAAAAA/PokemonGo-Map#458]
The more I work on this, the more it seems that keeping map info in ram is a bottleneck for the future success of the project. Moving it to a concurrency-friendly database that multiple server threads can access is the first step to making the map serve multiple users at once.

**Comment by docrockulus** [comment]
You can access a JSON formatted list of pokemon/stops/gyms by going to <mapaddress:mapport>/raw_data. Collecting and storin this information for use should be trivial.

**Comment by JawnZ** [comment]
seems like it would be trivial to store it in sqlite. the benefit just being so it lasts between sessions?

**Comment by hgentry** [comment]
The benefit mostly being that we can more easily deal with having hundreds of concurrent users in different locations (once we get per-user threads).

**Comment by DerScreever** [comment]
we are working on this.

**Comment by medghaim** [comment]
Check out this feature in the `develop` branch :)
