### ISSUE TITLE
Script silently fails (stops displaying new pokemon data)

### ISSUE THREAD

**Issue by Megahurtzz** [AHAAAAAAA/PokemonGo-Map#459]
Hello,

I used to have an issue where after running the script for about 30 mins it would halt with some index error.

With the latest version that error message seems to have gone away and the script continues processing through steps but looks like it has silently failed instead.  After about 30 mins it stops recording new pokemon until it is restarted.

Does anyone know what I could do to have this continuously run?

Thanks

**Comment by hgentry** [comment]
duplicate #547

**Comment by ericpadilla** [comment]
what does duplicate #547 means?

**Comment by ericpadilla** [comment]
ok thanks, which is me lol.

**Comment by foodforarabbit** [comment]
hey guys this should fix it: https://github.com/AHAAAAAAA/PokemonGo-Map/pull/465

I've been running it for 30 minutes and it seems to be fine so far
