### ISSUE TITLE
This site has exceeded its daily quota for maps.

### ISSUE THREAD

**Issue by JawnZ** [AHAAAAAAA/PokemonGo-Map#460]
Just started running this, and I get an error that tells me to look at the javascript console. this is what shows up there.

This site has exceeded its daily quota for maps. If you are the creator of this site, please visit the <a href="https://developers.google.com/maps/faq#usagelimits?utm_referrer=v3" target="_blank">documentation</a> to learn more.

Not certain where/why it thinks I'm over quota, I just started using this a few minutes ago.

**Comment by JawnZ** [comment]
I should've looked in the wiki and not just issues first. Appears addressed here.

https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Google-Maps-API:-a-brief-guide-to-your-own-key

**Comment by medghaim** [comment]
Please close this :)
