### ISSUE TITLE
Maps API quota exceeded, on different api key

### ISSUE THREAD

**Issue by pskitz** [AHAAAAAAA/PokemonGo-Map#461]
I'm constantly getting an error that says I've exceeded my daily quota despite having changed the api key for my own. I only get this when accessing it from the external IP as well, not LAN/localhost. To be a bit more specific, the map loads for a couple seconds, then I get the error.

**Comment by JawnZ** [comment]
you changed your api key in the credientials.json file?

**Comment by Skullmonkey** [comment]
https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Google-Maps-API:-a-brief-guide-to-your-own-key

**Comment by olsenej** [comment]
Having the same problem after following the wiki guide and using my own Google Maps API key

**Comment by medghaim** [comment]
There was a brief moment in time where the credentials.json file existed, but the code that read from the file was overwritten, resulting in the API_KEY being hardcoded into the example.py file.

Check `example.py`, near the top, if you see anything regarding a GOOGLE KEY or whatever, then you have that older version and you should update your local copy of the repo again.

**Comment by pskitz** [comment]
Disregard, I'm an idiot. I changed the key in the older version I had installed, but not the new one.

**Comment by medghaim** [comment]
Glad you got it fixed! Please close :)

**Comment by JawnZ** [comment]
@medghaim Mine still shows up in credentials.json and I first downloaded this like 2 hours ago...did I miss some kind of update?

**Comment by pskitz** [comment]
@JawnZ The (current?) branch still uses the credentials.json what he is referring to is [this](https://github.com/AHAAAAAAA/PokemonGo-Map/tree/py-rewrite) branch where it looks like most of the code is being rewritten.
