### ISSUE TITLE
 FIX ! AttributeError: "NoneType" object has no attribute "latitude" FIX!

### ISSUE THREAD

**Issue by Pypsen1337** [AHAAAAAAA/PokemonGo-Map#464]
I was able to solve its problems of the past , https://github.com/AHAAAAAAA/PokemonGo-Map/issues/397 but a new . 
FIX TROUBLE!
Try use langitude like this on your location
42.861449, -104.487674
Or find your latitude and longitude and fits on the principle of " Latitude , Longitude "

**Comment by fuzha** [comment]
i have same problem with that, then that error appear because location you put is not available if use name, try use langitude like this on your location

> 42.861449, -104.487674

**Comment by Pypsen1337** [comment]
Wow ! Thank you so much! Now I can look for Pokemon ! : D Fix in the hat !

**Comment by Pypsen1337** [comment]
Now it was a normal map on the website , there is a search of Pokemon up to 100 , and then again. But the map is not visible Pokemon . What to do?
![default](https://cloud.githubusercontent.com/assets/20542481/16973729/8ad6c9cc-4e4f-11e6-85b8-5cda15d8d16c.png)

**Comment by Pypsen1337** [comment]
Now it was a normal map on the website , there is a search of Pokemon up to 100 , and then again. But the map is not visible Pokemon . What to do?

**Comment by fuzha** [comment]
nice, happy hunting :dancer:

**Comment by alexpantyukhin** [comment]
I believe it possible to catch such situation and if the it was not possible to find location by name stop the application with specific message like 'Can not find location.' and print some advises how to fix that (use long and lat or change location name)

**Comment by Lunat1q** [comment]
1. Try to write  location in transliteration, if it's Cyrilic.
2. Most important, there should be NO CYRILIC LETTERS in the path to PY stript, just move it to drive root.

**Comment by DerScreever** [comment]
Im sorry, but we dropped the support for the master branch (example.py). 
This branch is deprecated.  
The new branch contains a much cleaner structure so pls report only issues related to the develop branch. 

Your development team

**Comment by jamesunderwood** [comment]
after entering example user and pass and location im getting a syntec error

file "c:\pokemongo\example.py", line 103
   print '[-] {}'.format<message>
syntaxError: invalid sytax

can anyone help me why this is happening, im entering location in numbers lat and long tried several coordinates, pass and user name verified to be active through the website this is the last step, also tried to access the 5000 server wont come up on my browser, (was it because of the last step not going through?)
