### ISSUE TITLE
Error while doing pip install

### ISSUE THREAD

**Issue by da1z** [AHAAAAAAA/PokemonGo-Map#466]
Hello
I am getting folowing error whole doing pip install --upgrade -r requirements.txt. Please help
I am on Win10 and py2.7

Collecting MarkupSafe (from Jinja2>=2.4->flask==0.11.1->-r requirements.txt (line 6))
  Using cached MarkupSafe-0.23.tar.gz
Installing collected packages: MarkupSafe, Jinja2, itsdangerous, flask, flask-googlemaps, future, s2sphere, pycryptodomex, gpsoauth, docopt, coverage, coveralls
  Running setup.py install for MarkupSafe ... error
    Complete output from command c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\kirylch\\appdata\\local\\temp\\pip-build-wuwih1\\MarkupSafe\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\kirylch\appdata\local\temp\pip-fkarpy-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-2.7
    creating build\lib.win32-2.7\markupsafe
    copying markupsafe\tests.py -> build\lib.win32-2.7\markupsafe
    copying markupsafe\_compat.py -> build\lib.win32-2.7\markupsafe
    copying markupsafe\_constants.py -> build\lib.win32-2.7\markupsafe
    copying markupsafe\_native.py -> build\lib.win32-2.7\markupsafe
    copying markupsafe\__init__.py -> build\lib.win32-2.7\markupsafe
    running egg_info
    writing MarkupSafe.egg-info\PKG-INFO
    writing top-level names to MarkupSafe.egg-info\top_level.txt
    writing dependency_links to MarkupSafe.egg-info\dependency_links.txt
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'MarkupSafe.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'MarkupSafe.egg-info\SOURCES.txt'
    copying markupsafe\_speedups.c -> build\lib.win32-2.7\markupsafe
    running build_ext
    building 'markupsafe._speedups' extension
    error: [Error 2] The system cannot find the file specified

    ----------------------------------------
Command "c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\username\\appdata\\local\\temp\\pip-build-wuwih1\\MarkupSafe\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\username\appdata\local\temp\pip-fkarpy-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\username\appdata\local\temp\pip-build-wuwih1\MarkupSafe\

**Comment by vintagesucks** [comment]
do `pip install setuptools==21.2.1` and try again

**Comment by medghaim** [comment]
Marking as closed. Feel free to reopen if you are still having trouble after trying @vintagesucks suggestion.
