### ISSUE TITLE
Making a map Externally visable 

### ISSUE THREAD

**Issue by DumbDumb0509** [AHAAAAAAA/PokemonGo-Map#467]
Im trying to make the map externally visable so i can load it on my ipad when im out searching

what do i need to put in for the IP4 or IP6

**Comment by ZeldoKavira** [comment]
This is in the docs... 0.0.0.0 for ipv4 or :: for ipv6

**Comment by DumbDumb0509** [comment]
yep.. done that but i cannot get it to load up on another device

**Comment by ericpadilla** [comment]
i use ngrok. easy setup

**Comment by diit** [comment]
I have this running on a digital ocean server, just rolled up ubuntu server, added all dependencies and ran the included external example, works great.

**Comment by Bitti09** [comment]
or  just use nginx or caddy as a reverse  proxy.

**Comment by a9595** [comment]
ngrok works for me like a charm:
http://ae65d294.ngrok.io

**Comment by craigbaines** [comment]
Iv'e set mine up as -H 0.0.0.0 -P 5000. 127.0.0.1:5000 loads fine but if i try connecting via my ip i get a connection timed out. Iv'e tried port forwarding and firewall rules, is there something obvious im missing? Trying to make it so my friends can view the map too.

**Comment by louispires** [comment]
I keep on getting issues due to the API key being over used I think.

This explains my problem quite well: https://www.latecnosfera.com/2016/06/google-maps-api-error-missing-keymap-error-solved.html

Can anyone help me change the API key myself?

**Comment by craigbaines** [comment]
@a9595 i just set it up on that grok, its working but i keep getting an error
"Too many connections! The tunnel session 'xxxxx' has violated the rate-limit policy of 40 connections per minute. Please decrease your inbound connection volume or upgrade to a paid plan for additional capacity. ERR_NGROK_702"

Any solutions? 

Thanks

**Comment by louispires** [comment]
I also used ngrok but the limit of 40 connections for the free plan is way too little for this.

But I found inside the credentials.json the gmaps_key variable which I updated to my own. Now I only add the -H 0.0.0.0 and it works as expected.

**Comment by craigbaines** [comment]
yep, im with you on that, i dont understand why i cant just connect with my ip

**Comment by AndrewYoungs** [comment]
Forward incoming port 5000 using TCP and make sure you set the -H 0.0.0.0 flag when you run the script.

**Comment by craigbaines** [comment]
Yep i had done, turns out my sky router is just a twat, i reset it back to factory settings, re-did the forwarding an now it works lol
