### ISSUE TITLE
How to download this map?? 

### ISSUE THREAD

**Issue by majjinnbuuu** [AHAAAAAAA/PokemonGo-Map#468]
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discordapp.com/invite/qbpVH6b).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:

Installed version of Python:

### Steps to reproduce
1.
2.
3.

### What have you tried?
1.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by ericpadilla** [comment]
https://github.com/AHAAAAAAA/PokemonGo-Map/wiki

**Comment by eggins** [comment]
Please refrain from asking questions before visiting the [wiki](https://github.com/AHAAAAAAA/PokemonGo-Map/wiki)
