### ISSUE TITLE
can it shows more currectly on map?

### ISSUE THREAD

**Issue by Luc4z** [AHAAAAAAA/PokemonGo-Map#469]
eveything works fine but it happens like i saw dragonite/pikachu in game but when i check my it didn't show on map , seems like it cant deteced all pokemon when they're close

**Comment by crckdns** [comment]
Works fine for me. Maybe they just spawned after you've scanned the area?

**Comment by ericpadilla** [comment]
keep on refreshing your browser for latest scan

**Comment by Lunat1q** [comment]
Area being scanned by squares, if u say there gonna be 7 steps, then i  will be 49 squares. So u check them 1 by 1, but after you checked it, UNTILL you will check it agains, some pokemons can spawn there, and they will not be displayed on the map, untill you recheck that square again.
