### ISSUE TITLE
Maps Key dosen't work

### ISSUE THREAD

**Issue by andrenagusch** [AHAAAAAAA/PokemonGo-Map#471]
It seems I can't change the maps key. After changing to a NEW api key I got this error:

`[-] retrying_set_location: geocoder exception (The given key has gone over the requests limit in the 24 hour period or has submitted too many requests in too short a period of time.), retrying`

**Comment by pavel-trubitsyn-clearscale** [comment]
Confirm this, got this message too. Could you describe how to get own GAPI credentials for this, please?

**Comment by DerScreever** [comment]
you need to look into our wiki for an instruction.

**Comment by andrenagusch** [comment]
I did it exactly like the instruction in the wiki! And it's not my first time creating an google API Key

**Comment by andrenagusch** [comment]
After about 2 hours the new key works for me!
