### ISSUE TITLE
Automatically get location.

### ISSUE THREAD

**Issue by alexpantyukhin** [AHAAAAAAA/PokemonGo-Map#473]
What if browser will pass location to the server? Sometimes it's annying to populate location in command string. I think it would be useful if user allows browser to get location and pass it on server.
I could implement this feature if it would be needed.

**Comment by crckdns** [comment]
Have you checked the previous questions? It was already asked as feature request

**Comment by alexpantyukhin** [comment]
Sorry. Could you refer this issue as duplicate?
