### ISSUE TITLE
Attribute error('lat and lng required')

### ISSUE THREAD

**Issue by lamoed** [AHAAAAAAA/PokemonGo-Map#475]
I have the same problem as there https://github.com/AHAAAAAAA/PokemonGo-Map/issues/210
but author closed issue without explanations

Created new google maps api key and replace in credentials.json
Authorize with google python example.py -a google -u mymail@gmail.com -p password -l "Moscow, Russia" -st 5

From console:
`[-] register_background_thread called
[-] register_background_thread: not running inside Flask so not starting thread
 * Restarting with stat
[-] register_background_thread called
[-] register_background_thread: initial registration
 * Debugger is active!
[+] Locale is en
[+] Getting initial location
 * Debugger pin code: 101-986-906
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[-] retrying_set_location: geocoder exception (<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>), retrying`

When open browser 127.0.0.1:5000
[http://dl2.joxi.net/drive/2016/07/20/0004/0547/324131/31/4236e59353.jpg](url)

What i am doing wrong? Help please

**Comment by DerScreever** [comment]
remove the "," on your location.

**Comment by lamoed** [comment]
this doesn't help

**Comment by Zergus** [comment]
Same issue

**Comment by karthikhiccup** [comment]
its working :100:  
the latitude and longitude gives attribute error where as the actual address from the google maps starts the localhost and displays all the pokemon in near by area
