### ISSUE TITLE
Web site.

### ISSUE THREAD

**Issue by Lunat1q** [AHAAAAAAA/PokemonGo-Map#476]
Hello, i'm C# coder (you can start throwing some poo in me).
As far as i saw the code for this Scanning Map, i noticed what this can be done in asp.net MVC. And portal can be made, i mean, there can be WebSite, where everyone can login with their accounts (google,ptc... or whatever is possible), and set location to start detecting. 
Are there any plans to do so? And if not, may be there is some idealogists like me, who want to start webPortal branch with me?

**Comment by alexpantyukhin** [comment]
I also thought about that feature.  It would be interesting to participate.

**Comment by DerScreever** [comment]
we already working on this.
a website for everyone to set location and start detecting is on progress, also filter for show gyms, pokestops and pokemons will be added.

**Comment by Lunat1q** [comment]
Sure, i can help if needed, have some knowledge of Jquery Ajax, and Javascript coding for "dynamic" content. If required ofc.

**Comment by medghaim** [comment]
All help is appreciated! Rewrite is almost done, keep an eye out for the `develop` branch :)
