### ISSUE TITLE
Pushover Support

### ISSUE THREAD

**Issue by mikeporterdev** [AHAAAAAAA/PokemonGo-Map#483]
Feature request: Add support for notification services such as Pushover and Pushbullet when certain Pokemon spawn in the scanned area.

**Comment by KevakaBuel** [comment]
I second this, would be a very nice feature for background scans.

**Comment by mikeporterdev** [comment]
As an addition to this, notifications when a nearby gym has been taken would be useful too, especially if it has been taken from your team
