### ISSUE TITLE
Question about the codes

### ISSUE THREAD

**Issue by ronayumik** [AHAAAAAAA/PokemonGo-Map#484]
I just want to ask, how do the scripts get the pokemons's location? Did the pokemon go servers provide some API that serve the locations?

If there is any, may I know the link/documentations? Or is there any _magic trick_ in your code?

Anyway, thanks a million as this script is heaven-like cheats for pogo players.

**Comment by DerScreever** [comment]
we do some magic fancy stuff :-) the server official provide not api access. we send some request like the api do. then we parse the response.

**Comment by ronayumik** [comment]
So, Is it like the script sends locations that still in range with the submitted location continuously?

**Comment by MonkeyLeeT** [comment]
It's simulating a player walking and sending his new location to server, which would respond with information about map, and thus pokemons/gyms/stops.

**Comment by medghaim** [comment]
@MonkeyLeeT summed it up perfectly.

https://www.reddit.com/r/pokemongodev/comments/4svl1o/guide_to_pokemon_go_server_responses/
Here's a guide discussing the server communication more indepth - there's a lot of other very useful info on that subreddit that'll be of help.

**Comment by ronayumik** [comment]
Right then, thank you for your kind replies :bow: :bow:
