### ISSUE TITLE
Error in Wiki: Usage (--auth-service should be --auth_service)

### ISSUE THREAD

**Issue by Alexandre-Nourissier** [AHAAAAAAA/PokemonGo-Map#489]
From the source code analysis, the wiki page ["Usage"](https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Usage) have 1 error : 
the attribute for the auth service is: 
>  -a   --auth-service  |  Auth service (PTC or google) 

and should be 
>  -a   --auth_service   | Auth service (PTC or google) 

Thanks for you hard work !

**Comment by medghaim** [comment]
`parser.add_argument('-a', '--auth-service', ... )`

**Comment by Alexandre-Nourissier** [comment]
ha, yep my bad. Thanks for the quick response !
