### ISSUE TITLE
Lure (Timing Bug?)

### ISSUE THREAD

**Issue by IMNoob1** [AHAAAAAAA/PokemonGo-Map#495]
Not sure maybe it still isn't perfect but I run:
python example.py -dp -ol -a ptc -st 10 -ar 60

1) Around the location of the lure, once a hard refresh intrigues (It increases its time, before a hard refresh it says 12:33:33 after a hard refresh it says 12:39:13) is the real time for lure isn't accurate? 

**2) No pokemon spawns around the lure, is it sort of a bug or because server can't handle all the requests or the randomness of the lure (thous we can't track it?)** // Not A Bug, its just how the game works.

Update:
3) Lure not disappearing after it finishes (atm shows me exp at 12:54:33 which is 8 minutes ago) hard refresh didn't helped, -ar didn't help either only a new session fixed the issue.

**Comment by IMNoob1** [comment]
Read more about Lure (& Incense) learned that they are "Personal (Lure is global) loot", meaning that they wont show on the pogo map.

so as far as i can see it, only the timing is a problem atm.

**Comment by DerScreever** [comment]
Im sorry, but we dropped the support for the master branch (example.py). 
This branch is deprecated.

The new branch contains a much cleaner structure so pls report only issues related to the develop branch.

Your development team
