### ISSUE TITLE
Can't load map

### ISSUE THREAD

**Issue by g3r4n** [AHAAAAAAA/PokemonGo-Map#496]
Got the following error in the console :
![image](https://cloud.githubusercontent.com/assets/10941033/16982195/dabc61bc-4e6e-11e6-8a93-dbb280472618.png)

my command line :
python runserver.py -H 0.0.0.0 -a ptc -u nope -p nope -l "Mail pablo picasso, Nantes, France" -st 6 -P 2000 -L fr

**Comment by frdmn** [comment]
Which branch did you use?

**Comment by g3r4n** [comment]
I'm using chrome 47.

**Comment by g3r4n** [comment]
working with hrome 51.

**Comment by Midako** [comment]
@g3r4n 
Well the error message tells you 
"Block-scoped declarations (let, const, function, class) is not supported outside of strict mode."
so either you write on line 1 
"use strict" with " or you write it at line 3 in front of the parameter disappear_date.

didn't test it myself.
