### ISSUE TITLE
python example.py -a google -u **** -p '****' -l "Boulder, CO" -st 5 exception

### ISSUE THREAD

**Issue by xvm03** [AHAAAAAAA/PokemonGo-Map#500]
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discordapp.com/invite/qbpVH6b).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:

Installed version of Python:
/usr/local/Cellar/python/2.7.9

### Steps to reproduce
1.install
2. python example.py -a google -u **** -p '****' -l "Boulder, CO" -st 5 exception
3.exception

### What have you tried?
1.

### Logs or other output that would be helpful

[-] register_background_thread called
[-] register_background_thread: not running inside Flask so not starting thread
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
[-] register_background_thread called
[-] register_background_thread: initial registration
[+] Locale is en
[+] Getting initial location
 * Debugger is active!
 * Debugger pin code: 678-420-456
[-] retrying_set_location: geocoder exception (Service timed out), retrying
[-] retrying_set_location: geocoder exception (Service timed out), retrying
[-] retrying_set_location: geocoder exception (Service timed out), retrying
[-] retrying_set_location: geocoder exception (Service timed out), retrying
[-] retrying_set_location: geocoder exception (Service timed out), retrying
[-] retrying_set_location: geocoder exception (Service timed out), retrying
[-] retrying_set_location: geocoder exception (Service timed out), retrying
[-] retrying_set_location: geocoder exception (Service timed out), retrying
[-] retrying_set_location: geocoder exception (Service timed out), retrying
[-] retrying_set_location: geocoder exception (Service timed out), retrying
[-] retrying_set_location: geocoder exception (Service timed out), retrying
[-] retrying_set_location: geocoder exception (Service timed out), retrying
[-] retrying_set_location: geocoder exception (Service timed out), retrying
[-] retrying_set_location: geocoder exception (Service timed out), retrying
[-] retrying_set_location: geocoder exception (Service timed out), retrying

**Comment by DerScreever** [comment]
try to remove the "," on your location

**Comment by Bitti09** [comment]
try 
` python example.py -a google -u **** -p '****' -l "Boulder,  Colorado, US" -st 5 exception`

**Comment by DerScreever** [comment]
Im sorry, but we dropped the support for the master branch (example.py). 
This branch is deprecated.  
The new branch contains a much cleaner structure so pls report only issues related to the develop branch. 

Your development team
