### ISSUE TITLE
Question: Multiple Pokéwanderers?

### ISSUE THREAD

**Issue by darcycartwright** [AHAAAAAAA/PokemonGo-Map#502]
I was just wondering - is it possible to have multiple PokémonGO accounts logged in and sending data to the API?

Ideally I would have 5-10 in key areas of my city.

**Comment by IMNoob1** [comment]
you don't even need multiple accounts, one account few sessions opened.

**Comment by PhyberApex** [comment]
For future reference it would be nice to have multiple paths like /home /city for different locations so we would not need to run on multiple ports :)

**Comment by FlorianChedemail** [comment]
The go-to answer seems to be "wait for the refactor to happen" so we should wait for that then see where to go from there.

**Comment by SanderLedegen** [comment]
Yeah, or a `/data?longitude=x&latitude=y&altitude=z` type of URL which returns some JSON containing all available Pokémon in the area with their respective GPS coordinates. Now that would come in handy, meaning that I just have to run the Python script once while being able to serve multiple users a dynamic location.

**Comment by FlorianChedemail** [comment]
@SanderLedegen That would be the elegant way to handle it, great idea!
