### ISSUE TITLE
Ignore is not working, timers all say 00:00, time is set to New Zealand time

### ISSUE THREAD

**Issue by mellor21** [AHAAAAAAA/PokemonGo-Map#504]
### Environment info
Operating System:
Linux Mint

Installed version of Python:
2.7

### Steps to reproduce
1. Set it to ignore common pokemon; drowzee, pidgey, rattata and they'll still show up
2. Click on any pokemon and look at the timer and time

### What have you tried?
1. Nothing, someone asked me to test it so I did

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by FlorianChedemail** [comment]
Ignore depends on the specified locale, try to match the names you get from the map with the ones you put in the script arguments.

Your time issues are weird, no idea about that.

**Comment by DerScreever** [comment]
you tried the master or develop branch?

**Comment by mellor21** [comment]
Develop, did I put this in the wrong spot?

**Comment by wcastello** [comment]
I was looking into this now, there is a (00m00s) hardcoded on map.js, also two disappear_time arguments for pokemonLabel()

**Comment by POPSuL** [comment]
I have similar issue. 
When I try to port countdown for that label I noticed about dissaper_time have an timestamp like UTC-(my current TZ offset).
E.g. I've the Asia/Sakhalin TZ (GMT+11) and on JS I see like that:
```js
new Date();
// displays my current local time, e.g. Wed Jul 20 2016 21:35:08 GMT+1100 (SAKT)
new Date(disappear_time); 
//displays my local time - 11 hours + (1..10 minutes), e.g. Wed Jul 20 2016 08:40:01 GMT+1100 (SAKT)
```
