### ISSUE TITLE
No pokemon on map and http://localhost:5000/raw_data does not show any pokemon

### ISSUE THREAD

**Issue by abberger1** [AHAAAAAAA/PokemonGo-Map#505]
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discordapp.com/invite/qbpVH6b).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:
Windows 7

Installed version of Python:
Python 2.7 .12 MSC v.1500 64bit Anaconda (running in virtual-env)

### Steps to reproduce
1. cloned repo and installed requirements successfully
2. ran "python example.py -u "username" -l "CITY, STATE" -st 100" and went to 127.0.0.1:5000
3. found map, but empty without pokemon

### What have you tried?
1. went to http://localhost:5000/raw_data to find empty dict 
2. also tried varying length of -st (went from 10 to 1000)
3. 

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by abberger1** [comment]
@IMNoob1  No - how do I do that?

**Comment by MikeDX** [comment]
You should use a much lower value than 100

**Comment by IMNoob1** [comment]
go to https://www.google.com/maps
1 tap the location you want to start the search from.
In the bottom you'll get the direction with lang & alt copy them
(example: 36.773569, 29.265488) -- Remove the space after the "," (turnout: 36.773569,29.265488)
Replace "CITY, STATE" to 36.773569,29.265488

Set ST to lower than 25 (you wont even able to reach them with airplane!)

update us

**Comment by MikeDX** [comment]
Try removing the comma from the location name in -l

**Comment by abberger1** [comment]
1. I have replaced the "CITY, STATE" with long, lat coordinates and the results are the same.
2. Now trying -st with less than 25. usually 2-5
3. Tried removing comma from location name

still no results :(

**Comment by IMNoob1** [comment]
i'd suggest fresh install of python and get pip all over again, just to be sure.

**Comment by DerScreever** [comment]
Im sorry, but we dropped the support for the master branch (example.py). 
This branch is deprecated.  
The new branch contains a much cleaner structure so pls report only issues related to the develop branch. 

Your development team
