### ISSUE TITLE
Pokemon with a negative TimeTillHiddenMs

### ISSUE THREAD

**Issue by matthewmelvin** [AHAAAAAAA/PokemonGo-Map#509]
The...

```
                for wild in cell.WildPokemon:
```
... loop is finding some pokemon's with a negative TimeTillHiddenMs value.   If I add a test at the top of the loop like...
```
                    if (wild.TimeTillHiddenMs < 0):
                        print wild
```
... I see values like... 

```
LastModifiedMs: 1469000855679
Latitude: -29.8598570915
Longitude: 31.0188614631
SpawnPointId: "1ef7a9c7741"
pokemon {
  PokemonId: 19
}
TimeTillHiddenMs: -122040448
```
Obviously, with a disappear_timestamp more than 33 hours in the past these never appear on the map. They're pre-expired as it were.   But I've been out with my phone to check the locations, and the pokemon really is there.

So, I don't know where this negative value is coming from (proto parser error?) but the end result is not all pokemon are being displayed on the map.

**Comment by sykhro** [comment]
Probably a proto parser error.
