### ISSUE TITLE
Missing features develop branch - Overview

### ISSUE THREAD

**Issue by DerScreever** [AHAAAAAAA/PokemonGo-Map#510]
# Features to be re-implemented
Just a little overview for the missing features on develop branch. 
Feel free to report missing features here.
If you want to reimplement some feature, post here please so everyone see that this is already in progress.

## List
- [x] Re-implementing a credentials/config.json | _Done_ | by @medghaim 
- [x] Re-implementing the 'ignore' and 'only' parameters  | _In progress_ | by @hhu94 
- [x] Auto-refresh | _in progress_ | by @Lunat1q
- [x] Display pokéstops | _in progress_ | by @invisiblek 	
- [x] Display gyms | _in progress_ | by @invisiblek 		
- [x] Locale for Pokemon names | _In progress_ | by @Scildrei
- [x] Coordinates transformer for China	
- [x] Debug mode	
- [x] Display only lured Pokestops
- [x] Route /next_loc (/next lat/lon variables)
- [x] Route /raw_data (output in this format: { "gyms": {}, "pokemons": {}, "pokestops": {} }) 
- [ ] Filter in webapp (toggle pokemon, pokestops and gyms display)

**Comment by hhu94** [comment]
I'll do the ignore and only parameters.

**Comment by PhyberApex** [comment]
raw_data location is also a feature I would really appreciate if brought back. Having this allows for a lot of flexibility with third party programms!

**Comment by Scildrei** [comment]
I added the locale for Poke names. I'll create a pull request asap.

**Comment by alexpantyukhin** [comment]
I could try `Display gyms` if it's not urgent task

**Comment by Rohmin** [comment]
- heroku compatiable
- next_loc /next lat/lon variables

**Comment by DerScreever** [comment]
@Rohmin 
i think heroku was never merged on master.

**Comment by Lunat1q** [comment]
i'll try to do auto-refresh.

**Comment by Rohmin** [comment]
@DerScreever There was a pull request for it, if it could be done in dev branch would be awesome. 
Link to it : https://github.com/AHAAAAAAA/PokemonGo-Map/pull/449

Also for  request /location?loc=

https://github.com/AHAAAAAAA/PokemonGo-Map/pull/384

**Comment by DerScreever** [comment]
@Rohmin 
like you told there was a pull request. but we never merged it. 
so first steps is to get 100% of the master functions then we can do something like this.

#384 need to be done again because of the new structure.

**Comment by invisiblek** [comment]
@alexpantyukhin I've got a good chunk of gyms done here, will probably keep going and get the pokestops done too if nobody else has jumped on it.

**Comment by DerScreever** [comment]
@invisiblek have fun ^^ waiting for the pull request

**Comment by NudeCaveMan** [comment]
We need a flag or function to interrupt the cycle to create a GUI. Otherwise there will be no way to set the new coordinates, without closing the window with the GUI. It is very uncomfortable.

**Comment by invisiblek** [comment]
That at least gets as much info as we had on master, more can be added later.

**Comment by alexpantyukhin** [comment]
@invisiblek there is already separated task https://github.com/AHAAAAAAA/PokemonGo-Map/issues/532 .

**Comment by alexpantyukhin** [comment]
I would like to take 'Filter in webapp' if there are no other guys who already do it

**Comment by invisiblek** [comment]
Time zones seem messed up too, everything is GMT it looks like? And countdown timers are busted

**Comment by invisiblek** [comment]
Times and countdown timers also fixed in https://github.com/AHAAAAAAA/PokemonGo-Map/pull/576

Freshly rebased =)

**Comment by alexpantyukhin** [comment]
@DerScreever 
There are already flags --display-pokestops --display-lured --display-gyms. It possible to leave it as it. But this way user needs to add it always for displaying. Is it ok?

**Comment by mikeporterdev** [comment]
Is 'Route /next_loc' the next location to be scanned?

**Comment by vanchagreen** [comment]
I took: Route /raw_data (output in this format: { "gyms": {}, "pokemons": {}, "pokestops": {} })

Pull Request here: https://github.com/AHAAAAAAA/PokemonGo-Map/pull/600

**Comment by SilverC** [comment]
I added a PR for next_loc. I believed I replicated the functionality from before but let me know if we would rather implement it differently. 

PR: #651

**Comment by Rohmin** [comment]
@SilverC It would be better for next_loc to take text location, and a function next_coord to take lat/kon

**Comment by SilverC** [comment]
@Rohmin I could go either way. It really depends on whether we want the server to be responsible for a location look up via google map api or the client to be responsible. Personally I think it makes more sense to make the client responsible for this feature since google api already supports this lookup from the client and it would offload some processing to the client as well. There are multiple pulls that will utilize the next_loc coming it seems, both autolocating and text based searches from the front end.
