### ISSUE TITLE
No pokemon on map or in JSON code

### ISSUE THREAD

**Issue by iTayGNR** [AHAAAAAAA/PokemonGo-Map#511]
I can't see any pokemons on the map.

http://localhost:5000/raw_data shows an empty JSON array:

`{
  "gyms": {}, 
  "pokemons": {}, 
  "pokestops": {}
}`

What should I do?
logged in with google.

**Comment by DerScreever** [comment]
develop branch or master branch?

**Comment by qwitriy** [comment]
Same issue. Master branch

**Comment by iTayGNR** [comment]
how do I know if develop branch or master branch?
I used this tutorial: https://github.com/vintagesucks/PokemonGo-Map-Install-Guides/blob/master/WINDOWS.md

**Comment by DerScreever** [comment]
Im sorry, but we dropped the support for the master branch (example.py). 
This branch is deprecated.  
The new branch contains a much cleaner structure so pls report only issues related to the develop branch. 

Your development team

**Comment by anuragdadheech** [comment]
Same issue, master branch.

> python example.py -a PTC -u ****** -p ****** -l "Central Park, New York, NY" -st 5
> [-] register_background_thread called
> [-] register_background_thread: not running inside Flask so not starting thread
>  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
>  * Restarting with stat
> [-] register_background_thread called
> [-] register_background_thread: initial registration
> [+] Locale is en
>  * Debugger is active!
> [+] Getting initial location
>  * Debugger pin code: 107-958-489
> [!] Your given location: Central Park, New York, NY, USA
> [!] lat/long/alt: 40.7711329 -73.9741874 0.0
> [!] PTC login for: *****
> [+] RPC Session Token: ******* ...
> 
> 127.0.0.1 - - [20/Jul/2016 16:58:12] "GET / HTTP/1.1" 200 -

Nothing after this. Nothing on map, nothing in raw_data.

**Comment by iTayGNR** [comment]
@DerScreever how can I use the new branch?
