### ISSUE TITLE
Failed to establish a new connection issue

### ISSUE THREAD

**Issue by san4a** [AHAAAAAAA/PokemonGo-Map#515]
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discordapp.com/invite/qbpVH6b).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:
Windows 8.1 Pro

Installed version of Python:
2.7

### Steps to reproduce
1. Install
2. Run:
example.py -a ptc -u login -p password -l "50.000000 37.000000" -st 10

### Logs or other output that would be helpful
Please see attachment:
![untitled2](https://cloud.githubusercontent.com/assets/13852024/16984438/a5cdf2fe-4e82-11e6-95d0-88bc59e6cb87.png)

And this exception is just eternal, so I can see no pokemons on the map...

**Comment by DerScreever** [comment]
Im sorry, but we dropped the support for the master branch. 
This branch is deprecated.  
The new branch contains a much cleaner structure so pls report only issues related to the develop branch. 

Your development team
