### ISSUE TITLE
Replace ECMAscript with plain JS

### ISSUE THREAD

**Issue by frdmn** [AHAAAAAAA/PokemonGo-Map#526]
As discussed with @CarlTaylor1989 

### Environment info
Operating System: any

Installed version of Python: not related to Pyhton

### Steps to reproduce
1. Clone `develop` branch
2. Open using browser without ES6-support (iOS/OS X Safari for example) 
3. Check console.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

![bildschirmfoto 2016-07-20 um 14 08 23](https://cloud.githubusercontent.com/assets/944459/16985890/c93d2b0a-4e83-11e6-8a3e-1d3640bfcc10.png)

**Comment by frdmn** [comment]
So we probably just need to turn the arrow function into an plain-jane one as well as the template string using the backticks (`)

**Comment by g3r4n** [comment]
this wil solve #496
