### ISSUE TITLE
No pokemon on map or in JSON code

### ISSUE THREAD

**Issue by iTayGNR** [AHAAAAAAA/PokemonGo-Map#527]
I can't see any pokemons on the map.

http://localhost:5000/raw_data shows an empty JSON array:

{ "gyms": {}, "pokemons": {}, "pokestops": {} }

What should I do?
Logged in with google.
Using the develop branch.

**Comment by PhyberApex** [comment]
raw_data does not work in current develop branch. You sure you are not using master?

**Comment by iTayGNR** [comment]
I just switched to the develop branch (I had the same problem with the master branch) So i'm sure it's the develop.

My Input:
`python runserver.py -a google -u **********@gmail.com -p ********** -l "32.7979775,44.9759091" -st 5 -ar 10;`

**Comment by iTayGNR** [comment]
Just noticed the console is repeating with its rescannings:

2016-07-20 15:32:41,845 [     search] [   INFO] Rescanning
2016-07-20 15:32:41,845 [     search] [   INFO] Scanning step 1 of 4.
2016-07-20 15:32:42,276 [     models] [   INFO] Upserting 3 gyms
2016-07-20 15:32:42,328 [     search] [   INFO] Completed 25.00% of scan.
2016-07-20 15:32:43,328 [     search] [   INFO] Scanning step 2 of 4.
2016-07-20 15:32:43,733 [     models] [   INFO] Upserting 3 gyms
2016-07-20 15:32:43,795 [     search] [   INFO] Completed 50.00% of scan.
2016-07-20 15:32:44,796 [     search] [   INFO] Scanning step 3 of 4.
2016-07-20 15:32:45,216 [     models] [   INFO] Upserting 5 gyms
2016-07-20 15:32:45,269 [     search] [   INFO] Completed 75.00% of scan.
2016-07-20 15:32:46,270 [     search] [   INFO] Scanning step 4 of 4.
2016-07-20 15:32:46,687 [     models] [   INFO] Upserting 2 pokemon
2016-07-20 15:32:46,736 [     models] [   INFO] Upserting 2 gyms
2016-07-20 15:32:46,793 [     search] [   INFO] Completed 100.00% of scan.

keeps repeating but nothing on map.

**Comment by iTayGNR** [comment]
@PhyberApex any ideas?

**Comment by PhyberApex** [comment]
As mentioned earlier develop branch returns "Not Found" for /raw_data so please check which branch you are running again. Also try to increase the step size maybe there are just no pokemon in your vicinity.

**Comment by iTayGNR** [comment]
@PhyberApex how can it be anything but develop branch?
I mean, I run `runserver.py` of develop and not `example.py` of master.

**Comment by iTayGNR** [comment]
@PhyberApex I deleted the master folder away from my computer and I get this error:
![2016-07-20_15-50-39](https://cloud.githubusercontent.com/assets/6430313/16986886/bee6fe0c-4e91-11e6-8548-41c23527e055.png)
So I guess it was using the master branch. how can I change it?

**Comment by PhyberApex** [comment]
I'm just telling you what I can see in my instance. I run the develop branch and I get a 404 from /raw_data. Pokestops and Gyms are not working in develop branch. Pokemons should work. So I can't help you here, Sorry!

**Comment by PhyberApex** [comment]
You are running on windows...I can't help you there sorry. I'm using it on a linux machine. But I would try to delete everything and do a new git clone :)

**Comment by iTayGNR** [comment]
@PhyberApex I'll try that.
When I try to delete the PokemonGo-Map-master folder I get a message that says that the folder is open in another program but it's not. probably the server on localhost:5000 is still running for some reason.. what can I do about it?

**Comment by DerScreever** [comment]
pokemon now on the map.
/raw_data still not implemented

**Comment by PhyberApex** [comment]
@iTayGNR open your task manager and check for python instances running and kill em all. Maybe try rebooting if that does not help.

**Comment by iTayGNR** [comment]
@PhyberApex @DerScreever okay it's the develop branch for sure - 404 on the /raw_data,
but I see only the GoMap header and I can't see any map..

**Comment by PhyberApex** [comment]
Try reloading the browser and clearing the cache. On Windows that is strg+f5. Also you are now on the develop branch...bugs are to be expected.

**Comment by iTayGNR** [comment]
@PhyberApex did it, no results. still can't see the map, waited about an hour
