### ISSUE TITLE
Loading map

### ISSUE THREAD

**Issue by craigbaines** [AHAAAAAAA/PokemonGo-Map#528]
Excuse the stupidity, iv'e never used python before. 

Iv'e installed everything, an im running the example.py in the cmd. Its searching on a loop.... How do i then load the template example to actually show me the map? 

Thanks!

**Comment by DerScreever** [comment]
when you run the server normaly you should go into your browser and open 127.0.0.1:5000

**Comment by craigbaines** [comment]
perfect thank you!
