### ISSUE TITLE
Dev build not showing anything aside from the GoMap bar?

### ISSUE THREAD

**Issue by kevvv** [AHAAAAAAA/PokemonGo-Map#529]
Welp I feel like an idiot, not sure what's wrong but 127.0.0.1:5000 is just showing a blank white page...  Is this something I screwed up?

**Comment by DerScreever** [comment]
yeah. had the same. @sykhro just told he fixed it. so lets try

**Comment by kevvv** [comment]
Thank you :)

**Comment by relomy** [comment]
This also appears in #496.

**Comment by kevvv** [comment]
Most recent commit only fixes it for the first load.

**Comment by DerScreever** [comment]
@sykhro will commit in some minutes.

**Comment by cyberflow** [comment]
after #533 see map on firefox, but still blank page on safari (mac OS & iOS)

**Comment by timdine** [comment]
Confirm, working in Firefox.  Does not work in IE
