### ISSUE TITLE
Script crashes after a while running

### ISSUE THREAD

**Issue by wohfab** [AHAAAAAAA/PokemonGo-Map#537]
So I run the script on my server to have access, while I am outside. But after a while, the script crashes. No new Pokémon appear and all the timers for the old ones run down until they disappear. Then, even CTRL+c out of the process would not work anymore. 

### Environment info
Operating System: Linux Server - Ubuntu 14.04
Installed version of Python: 2.7.6

### Steps to reproduce
1. run tmux session
2. run python script (example.py)
3. detach from tmux session

### What have you tried?
1. killing tmux window
2. creating new tmux window
3. re-run the script

**Comment by DerScreever** [comment]
start command please

thx

**Comment by wohfab** [comment]
you mean this? 

`python example.py -a PTC -u USERNAME -p PASSWORD -l "52.035401, 8.496388" -ar 1 -st 5 -H 0.0.0.0 -P 5000 -dg -dp -ol -L "de"`

**Comment by GForceWeb** [comment]
I've got a similar issue. Running the script pokemon seem to load for about an hour before no more are added to the map. The script still appears to be processing though and I can cancel/restart it without a problem

**Comment by DerScreever** [comment]
Im sorry, but we dropped the support for the master branch (example.py). 
This branch is deprecated.

The new branch contains a much cleaner structure so pls report only issues related to the develop branch.

Your development team
