### ISSUE TITLE
No Pokemon after second/third loop

### ISSUE THREAD

**Issue by Dutzen** [AHAAAAAAA/PokemonGo-Map#541]
Hi, 
I use the current master branch. I am using a MacBookPro
This is my command: python example.py -a ptc -u ********* -p ********** -l "48.877615, 12.5709" -st 15 -i Taubsi,Rattfratz -L de -H 0.0.0.0

It is just working fine. Everything is displayed correctly, Pidgeys and Rattatas are ignored as pleased.
But after the second or third loop of 250 steps. No pokemon are showing up.
The map stays empty (after expired are deleted)

I hope you can help me

**Comment by michi0987** [comment]
From what i've heard master branch is no longer supported. Ya shall use https://github.com/AHAAAAAAA/PokemonGo-Map/tree/develop instead :)
