### ISSUE TITLE
Script was running fine but now flask is missing

### ISSUE THREAD

**Issue by M4CC** [AHAAAAAAA/PokemonGo-Map#543]
Hi guys,

I got the script running just fine but when I stopped it and tried running it again with different settings I started getting this error that flask is missing.

How can I get it working again?

Thanks!

**Comment by M4CC** [comment]
Forced reinstall with "sudo pip install -I -r requirements.txt" and now it's complaining that I'm missing the flask_googlemaps module instead.

**Comment by sykhro** [comment]
pip install --upgrade -r requirements.txt

**Comment by M4CC** [comment]
It just prompted that all requirements are already up to date.

**Comment by auth100488** [comment]
hm i'd try a "pip uninstall flask" and then a "pip install flask".
If you get a "Wheel" error .. try downgrading this "pip install setuptools==21.2.1" then reinstall flask.

**Comment by M4CC** [comment]
Just tried it but I got the same problem, he simply doesn't recognize the module as being installed.

**Comment by M4CC** [comment]
Any help?
