### ISSUE TITLE
Error running script example.py

### ISSUE THREAD

**Issue by GowthamRayar** [AHAAAAAAA/PokemonGo-Map#545]
I tried running---> python example.py -u "username" -p "password" -l "location"-st 10

i got following error

  File "example.py", line 103
    print '[-] {}'.format(message)
                 ^
SyntaxError: invalid syntax

**Comment by Alexandre-Nourissier** [comment]
A space is missing before -st

**Comment by reyqn** [comment]
Looks like you are running python 3. Use 2.7

**Comment by auth100488** [comment]
Do not forget to flush the PIP cache when reinstalling to 2.7.x
c:\users\%username%\appdata\local\pip

**Comment by GowthamRayar** [comment]
thank u fellas I'll try with 2.7 ill let u know result

**Comment by GowthamRayar** [comment]
No module named flask error came up

**Comment by reyqn** [comment]
Did you run "pip install --upgrade -r requirements.txt"?
