### ISSUE TITLE
[Develop] Missing some pokemons

### ISSUE THREAD

**Issue by g3r4n** [AHAAAAAAA/PokemonGo-Map#547]
on the master there more pokemon than in develop :
master :
![master](https://cloud.githubusercontent.com/assets/10941033/16989151/58ac2002-4e93-11e6-9043-bd208b1a5afe.PNG)

develop :
![dev](https://cloud.githubusercontent.com/assets/10941033/16989159/621676e2-4e93-11e6-9c2c-1e7989c3b691.PNG)

**Comment by Scildrei** [comment]
Duplicate of this #538.

**Comment by g3r4n** [comment]
closed because of duplicate
