### ISSUE TITLE
No module named request

### ISSUE THREAD

**Issue by JefVH** [AHAAAAAAA/PokemonGo-Map#548]
Can somebody help me with this please? I use the updated develop branch

> Traceback (most recent call last):
  File "runserver.py", line 10, in <module>
    from pogom.app import Pogom
  File "/Users/jefsocialseeder/teams/experimenting/PokemonGo-Map/pogom/app.py", line 5, in <module>
    from flask import Flask, jsonify, render_template
  File "/Library/Python/2.7/site-packages/flask/__init__.py", line 17, in <module>
    from werkzeug.exceptions import abort
  File "/usr/local/lib/python2.7/site-packages/werkzeug/__init__.py", line 152, in <module>
    __import__('werkzeug.exceptions')
  File "/usr/local/lib/python2.7/site-packages/werkzeug/exceptions.py", line 71, in <module>
    from werkzeug.wrappers import Response
  File "/usr/local/lib/python2.7/site-packages/werkzeug/wrappers.py", line 26, in <module>
    from werkzeug.http import HTTP_STATUS_CODES, \
  File "/usr/local/lib/python2.7/site-packages/werkzeug/http.py", line 28, in <module>
    from urllib.request import parse_http_list as _parse_list_header
ImportError: No module named request

### Environment info
Operating System:
Mac OS X Yosemite 10.10.5
Installed version of Python:
2.7

### Steps to reproduce
1. Installed everything through the requirements.txt
2. Try to run runserver.py
3. Got this error

**Comment by devinvisible** [comment]
I have a similar issue on Windows 7 / python 2.7.12

`H:\PokemonGo-Map>pip install --upgrade -r requirements.txt
Collecting Flask==0.11.1 (from -r requirements.txt (line 1))
  Using cached Flask-0.11.1-py2.py3-none-any.whl
Collecting Jinja2==2.8 (from -r requirements.txt (line 2))
  Using cached Jinja2-2.8-py2.py3-none-any.whl
Collecting MarkupSafe==0.23 (from -r requirements.txt (line 3))
  Using cached MarkupSafe-0.23.tar.gz
Requirement already up-to-date: Werkzeug==0.11.10 in c:\python27\lib\site-packages (from -r requirements.txt (line 4))
Collecting argparse==1.2.1 (from -r requirements.txt (line 5))
  Downloading argparse-1.2.1.tar.gz (69kB)
    100% |################################| 71kB 347kB/s
Requirement already up-to-date: click==6.6 in c:\python27\lib\site-packages (from -r requirements.txt (line 6))
Requirement already up-to-date: itsdangerous==0.24 in c:\python27\lib\site-packages (from -r requirements.txt (line 7))
Collecting peewee==2.8.1 (from -r requirements.txt (line 8))
  Downloading peewee-2.8.1.tar.gz (474kB)
    100% |################################| 481kB 636kB/s
Collecting wsgiref==0.1.2 (from -r requirements.txt (line 9))
  Downloading wsgiref-0.1.2.zip
Requirement already up-to-date: geopy==1.11.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 10))
Requirement already up-to-date: protobuf==2.6.1 in c:\python27\lib\site-packages (from -r requirements.txt (line 11))
Requirement already up-to-date: requests==2.10.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 12))
Collecting s2sphere==0.2.4 (from -r requirements.txt (line 13))
  Using cached s2sphere-0.2.4-py2.py3-none-any.whl
Collecting gpsoauth==0.3.0 (from -r requirements.txt (line 14))
  Using cached gpsoauth-0.3.0.tar.gz
Collecting protobuf-to-dict==0.1.0 (from -r requirements.txt (line 15))
  Downloading protobuf-to-dict-0.1.0.tar.gz
Requirement already up-to-date: setuptools in c:\python27\lib\site-packages (from protobuf==2.6.1->-r requirements.txt (line 11))
Collecting future (from s2sphere==0.2.4->-r requirements.txt (line 13))
  Using cached future-0.15.2.tar.gz
Collecting pycryptodomex>=3.0 (from gpsoauth==0.3.0->-r requirements.txt (line 14))
  Using cached pycryptodomex-3.4.2-cp27-cp27m-win32.whl
Installing collected packages: MarkupSafe, Jinja2, Flask, argparse, peewee, wsgiref, future, s2sphere, pycryptodomex, gpsoauth, protobuf-to-dict
  Running setup.py install for MarkupSafe ... error
    Complete output from command c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\username\\appdata\\local\\temp\\pip-build-jezjuq\\Mar
kupSafe\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\username\appdat
a\local\temp\pip-ymllhg-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-2.7
    creating build\lib.win32-2.7\markupsafe
    copying markupsafe\tests.py -> build\lib.win32-2.7\markupsafe
    copying markupsafe\_compat.py -> build\lib.win32-2.7\markupsafe
    copying markupsafe\_constants.py -> build\lib.win32-2.7\markupsafe
    copying markupsafe\_native.py -> build\lib.win32-2.7\markupsafe
    copying markupsafe\__init__.py -> build\lib.win32-2.7\markupsafe
    running egg_info
    writing MarkupSafe.egg-info\PKG-INFO
    writing top-level names to MarkupSafe.egg-info\top_level.txt
    writing dependency_links to MarkupSafe.egg-info\dependency_links.txt
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'MarkupSafe.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'MarkupSafe.egg-info\SOURCES.txt'
    copying markupsafe\_speedups.c -> build\lib.win32-2.7\markupsafe
    running build_ext
    building 'markupsafe._speedups' extension
    error: [Error 2] The system cannot find the file specified

    ----------------------------------------
Command "c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\username\\appdata\\local\\temp\\pip-build-jezjuq\\MarkupSafe\\setup.py';exec(
compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\username\appdata\local\temp\pip-ymllhg-
record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\username\appdata\local\temp\pip-build-jezjuq\MarkupSafe
\

H:\PokemonGo-Map>python runserver.py -u asdf -p asdf -l "Boston, MA" -st 5 -dp -dg
Traceback (most recent call last):
  File "runserver.py", line 10, in <module>
    from pogom.app import Pogom
  File "H:\PokemonGo-Map\pogom\app.py", line 5, in <module>
    from flask import Flask, jsonify, render_template
ImportError: No module named flask

H:\PokemonGo-Map>python --version
Python 2.7.12
`

**Comment by DerScreever** [comment]
Please if you would read the first page there is a big fat: **For instructions, please refer to the wiki**
There you find https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Installation-and-requirements 
and there is a caption called: Install project dependencies

**Comment by JefVH** [comment]
@DerScreever it did all just that and it's not working

**Comment by devinvisible** [comment]
@DerScreever Look at the output of what I posted above. The first command is installing project dependencies. This is not a closed issue.

**Comment by mkody** [comment]
@devinvisible As far I can see in your log, this isn't an issue from this project but from one of the dependencies. This seems related: [falied to install flask under virutalenv on windows](http://stackoverflow.com/questions/38243633/falied-to-install-flask-under-virutalenv-on-windows-error-2-the-system-cann)

@JefVH Could you post the logs from `pip install --upgrade -r requirements.txt`? For some reason, this doesn't work at a 100% rate for everyone on OS X (while it worked fine for me). For information, I'm running `pip 8.1.2` with `Pyton 2.7.11`

**Comment by devinvisible** [comment]
@mkody You're correct. I needed to specify version 21.2.1 of setuptools prior to installing flask. Afterwards, it's still necessary to install the other dependencies that might not have completed:

> pip install setuptools==21.2.1
> pip install flask
> pip install --upgrade -r requirements.txt

**Comment by mkody** [comment]
@devinvisible Thanks for confirming. This should be put somewhere in the wiki, probably the FAQ.

**Comment by wuron** [comment]
@JefVH `pip install request` fixed the issue for me.
