### ISSUE TITLE
No poke's on map after scaning

### ISSUE THREAD

**Issue by ELusiveLPFAN** [AHAAAAAAA/PokemonGo-Map#549]
When I run app, it's successfully add pokemon's on map, but after complete scan, it continue scanning but don't add poke's to map. 15 minutes later map totally clean, cause "old" poke's expires, application continue scanning but nothing happens.
What wrong with it?

**Comment by DerScreever** [comment]
no add of pokemon on auto refresh.

**Comment by sykhro** [comment]
This is not a bug, you didn't feed it the -ar parameter

**Comment by ELusiveLPFAN** [comment]
What count of -ar actually use?

**Comment by ELusiveLPFAN** [comment]
Set -ar parameter to 10, testing now.

**Comment by Galtwise** [comment]
I have this issue while still having the -ar flag

**Comment by 20015jjw** [comment]
Setting `-ar` now, testing.

**Comment by ELusiveLPFAN** [comment]
> EDIT: Still not working with -ar 60. After around 30-40 min, pokemons stop to show up on the map. No errors are produced on the map, and restarting the server immediately resolves this.

Same issue. #

**Comment by mkody** [comment]
@20015jjw Can you confirm that you're using the `develop` branch?
For `-ar` not working, it's a known issue.

**Comment by 20015jjw** [comment]
@mkody I'm on master. I'll use develop to test now.

**Comment by 20015jjw** [comment]
@mkody `develop` still doesn't work. Pokemon stop appearing after 1 hour. I'm also using `-ar 10`.
