### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by auth100488** [AHAAAAAAA/PokemonGo-Map#550]
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discord.gg/Kzp4yky).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System: Widows 8/8.1

Installed version of Python: 2.7.11

### Steps to reproduce
1.Fresh Install
2.Launch

### What have you tried?
1.Uninstalling Geo + Reinstalling (did no help).
2.Multiple Fresh reinstall.
3.Different versions of Python

### Logs or other output that would be helpful
C:\Users\%USERNAME%\Desktop\pokego\PokemonGo-Map-develop>python c:\python27\get-pip
.py
Collecting pip
  Downloading pip-8.1.2-py2.py3-none-any.whl (1.2MB)
    100% |################################| 1.2MB 469kB/s
Collecting wheel
  Downloading wheel-0.29.0-py2.py3-none-any.whl (66kB)
    100% |################################| 71kB 2.3MB/s
Installing collected packages: pip, wheel
  Found existing installation: pip 7.1.2
    Uninstalling pip-7.1.2:
      Successfully uninstalled pip-7.1.2
Successfully installed pip-8.1.2 wheel-0.29.0

C:\Users\%USERNAME%\Desktop\pokego\PokemonGo-Map-develop>pip install setuptools==21
.2.1
Collecting setuptools==21.2.1
  Downloading setuptools-21.2.1-py2.py3-none-any.whl (509kB)
    100% |################################| 512kB 131kB/s
Installing collected packages: setuptools
  Found existing installation: setuptools 18.2
    Uninstalling setuptools-18.2:
      Successfully uninstalled setuptools-18.2
Successfully installed setuptools-21.2.1

C:\Users\%USERNAME%\Desktop\pokego\PokemonGo-Map-develop>pip install -r requirement
s.txt
Collecting Flask==0.11.1 (from -r requirements.txt (line 1))
  Downloading Flask-0.11.1-py2.py3-none-any.whl (80kB)
    100% |################################| 81kB 1.1MB/s
Collecting Jinja2==2.8 (from -r requirements.txt (line 2))
  Downloading Jinja2-2.8-py2.py3-none-any.whl (263kB)
    100% |################################| 266kB 87kB/s
Collecting MarkupSafe==0.23 (from -r requirements.txt (line 3))
  Downloading MarkupSafe-0.23.tar.gz
Collecting Werkzeug==0.11.10 (from -r requirements.txt (line 4))
  Downloading Werkzeug-0.11.10-py2.py3-none-any.whl (306kB)
    100% |################################| 307kB 1.3MB/s
Collecting argparse==1.2.1 (from -r requirements.txt (line 5))
  Downloading argparse-1.2.1.tar.gz (69kB)
    100% |################################| 71kB 1.5MB/s
Collecting click==6.6 (from -r requirements.txt (line 6))
  Downloading click-6.6.tar.gz (283kB)
    100% |################################| 286kB 1.1MB/s
Collecting itsdangerous==0.24 (from -r requirements.txt (line 7))
  Downloading itsdangerous-0.24.tar.gz (46kB)
    100% |################################| 51kB 3.2MB/s
Collecting peewee==2.8.1 (from -r requirements.txt (line 8))
  Downloading peewee-2.8.1.tar.gz (474kB)
    100% |################################| 481kB 930kB/s
Collecting wsgiref==0.1.2 (from -r requirements.txt (line 9))
  Downloading wsgiref-0.1.2.zip
Collecting geopy==1.11.0 (from -r requirements.txt (line 10))
  Downloading geopy-1.11.0-py2.py3-none-any.whl (66kB)
    100% |################################| 71kB 2.2MB/s
Collecting protobuf==2.6.1 (from -r requirements.txt (line 11))
  Downloading protobuf-2.6.1.tar.gz (188kB)
    100% |################################| 194kB 1.7MB/s
Collecting requests==2.10.0 (from -r requirements.txt (line 12))
  Downloading requests-2.10.0-py2.py3-none-any.whl (506kB)
    100% |################################| 512kB 939kB/s
Collecting s2sphere==0.2.4 (from -r requirements.txt (line 13))
  Downloading s2sphere-0.2.4-py2.py3-none-any.whl
Collecting gpsoauth==0.3.0 (from -r requirements.txt (line 14))
  Downloading gpsoauth-0.3.0.tar.gz
Collecting protobuf-to-dict==0.1.0 (from -r requirements.txt (line 15))
  Downloading protobuf-to-dict-0.1.0.tar.gz
Requirement already satisfied (use --upgrade to upgrade): setuptools in c:\pytho
n27\lib\site-packages (from protobuf==2.6.1->-r requirements.txt (line 11))
Collecting future (from s2sphere==0.2.4->-r requirements.txt (line 13))
  Downloading future-0.15.2.tar.gz (1.6MB)
    100% |################################| 1.6MB 389kB/s
Collecting pycryptodomex>=3.0 (from gpsoauth==0.3.0->-r requirements.txt (line 1
4))
  Downloading pycryptodomex-3.4.2-cp27-cp27m-win32.whl (7.4MB)
    100% |################################| 7.5MB 87kB/s
Building wheels for collected packages: MarkupSafe, argparse, click, itsdangerou
s, peewee, wsgiref, protobuf, gpsoauth, protobuf-to-dict, future
  Running setup.py bdist_wheel for MarkupSafe ... done
  Stored in directory: C:\Users\%USERNAME%\AppData\Local\pip\Cache\wheels\a3\fa\dc\
0198eed9ad95489b8a4f45d14dd5d2aee3f8984e46862c5748
  Running setup.py bdist_wheel for argparse ... done
  Stored in directory: C:\Users\%USERNAME%\AppData\Local\pip\Cache\wheels\0c\98\89\
7494d5db3af34dc96bba5bff3bf8a8f38eeeab5291ec174cc3
  Running setup.py bdist_wheel for click ... done
  Stored in directory: C:\Users\%USERNAME%\AppData\Local\pip\Cache\wheels\b0\6d\8c\
cf5ca1146e48bc7914748bfb1dbf3a40a440b8b4f4f0d952dd
  Running setup.py bdist_wheel for itsdangerous ... done
  Stored in directory: C:\Users\%USERNAME%\AppData\Local\pip\Cache\wheels\fc\a8\66\
24d655233c757e178d45dea2de22a04c6d92766abfb741129a
  Running setup.py bdist_wheel for peewee ... done
  Stored in directory: C:\Users\%USERNAME%\AppData\Local\pip\Cache\wheels\d1\1d\e3\
e94c8f786670159909883ab2dcd1d85f5ad62e6025e548e3c1
  Running setup.py bdist_wheel for wsgiref ... done
  Stored in directory: C:\Users\%USERNAME%\AppData\Local\pip\Cache\wheels\ba\22\0d\
47ab56272be3b73883925ae6bf7534afadc9836ef40c7cebd9
  Running setup.py bdist_wheel for protobuf ... done
  Stored in directory: C:\Users\%USERNAME%\AppData\Local\pip\Cache\wheels\c9\97\49\
1bf6b7b58d0adec650bcb625b6656877437d1f7d18c32e88ee
  Running setup.py bdist_wheel for gpsoauth ... done
  Stored in directory: C:\Users\%USERNAME%\AppData\Local\pip\Cache\wheels\06\d2\82\
d0710aa6bd4d119090452ab371dac9c725fd4a288456c3b929
  Running setup.py bdist_wheel for protobuf-to-dict ... done
  Stored in directory: C:\Users\%USERNAME%\AppData\Local\pip\Cache\wheels\b3\5f\67\
4af581810bdf4fd47eff115354343c227ec1a504010abc9e07
  Running setup.py bdist_wheel for future ... done
  Stored in directory: C:\Users\%USERNAME%\AppData\Local\pip\Cache\wheels\11\c5\d2\
ad287de27d0f0d646f119dcffb921f4e63df128f28ab0a1bda
Successfully built MarkupSafe argparse click itsdangerous peewee wsgiref protobu
f gpsoauth protobuf-to-dict future
Installing collected packages: click, Werkzeug, MarkupSafe, Jinja2, itsdangerous
, Flask, argparse, peewee, wsgiref, geopy, protobuf, requests, future, s2sphere,
 pycryptodomex, gpsoauth, protobuf-to-dict
Successfully installed Flask-0.11.1 Jinja2-2.8 MarkupSafe-0.23 Werkzeug-0.11.10
argparse-1.2.1 click-6.6 future-0.15.2 geopy-1.11.0 gpsoauth-0.3.0 itsdangerous-
0.24 peewee-2.8.1 protobuf-2.6.1 protobuf-to-dict-0.1.0 pycryptodomex-3.4.2 requ
ests-2.10.0 s2sphere-0.2.4 wsgiref-0.1.2

**C:\Users\%USERNAME%\Desktop\pokego\PokemonGo-Map-develop>python runserver.py -a PTC
 -u USRNAME -p PASSWORD -l "quebec, quebec" -st 5
Traceback (most recent call last):
  File "runserver.py", line 37, in <module>
    position = get_pos_by_name(args.location)
  File "C:\Users\%USERNAME%\Desktop\pokego\PokemonGo-Map-develop\pogom\pgoapi\utili
ties.py", line 59, in get_pos_by_name
    loc = geolocator.geocode(location_name)
  File "c:\Python27\lib\site-packages\geopy\geocoders\googlev3.py", line 217, in
 geocode
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "c:\Python27\lib\site-packages\geopy\geocoders\base.py", line 171, in _ca
ll_geocoder
    raise GeocoderServiceError(message)
geopy.exc.GeocoderServiceError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED]
certificate verify failed (_ssl.c:590)>**

C:\Users\%USERNAMER%\Desktop\pokego\PokemonGo-Map-develop>

**Comment by sykhro** [comment]
Please, re-run it with the -d flag and post the log

**Comment by cyberflow** [comment]
try to add follow to the script and check:
```
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
```

**Comment by auth100488** [comment]
@sykhro 

Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Users\%username%>cd C:\Users\%username%\Desktop\pokego\PokemonGo-Map-develop

C:\Users\%username%\Desktop\pokego\PokemonGo-Map-develop>set path=%PATH%;C:\python2
7;c:\python27\scripts

C:\Users\%username%\Desktop\pokego\PokemonGo-Map-develop>python runserver.py -u user -p pass -l "quebec, quebec" -st 5 -d
Traceback (most recent call last):
  File "runserver.py", line 37, in <module>
    position = get_pos_by_name(args.location)
  File "C:\Users\%username%\Desktop\pokego\PokemonGo-Map-develop\pogom\pgoapi\utili
ties.py", line 59, in get_pos_by_name
    loc = geolocator.geocode(location_name)
  File "C:\python27\lib\site-packages\geopy\geocoders\googlev3.py", line 217, in
 geocode
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "C:\python27\lib\site-packages\geopy\geocoders\base.py", line 171, in _ca
ll_geocoder
    raise GeocoderServiceError(message)
geopy.exc.GeocoderServiceError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED]
certificate verify failed (_ssl.c:590)>

C:\Users\%username%\Desktop\pokego\PokemonGo-Map-develop>


@cyberflow 
I'm not sure what you mean by adding it to the script ?
You mean adding these two lines to the actual runserver.py ?

Thanks for your help guys!

**Comment by auth100488** [comment]
@cyberflow 
You sir are a fucking genius!
haha it worked!
Here is the runserver.py with the working changes
[runserver - Copy.txt](https://github.com/AHAAAAAAA/PokemonGo-Map/files/374011/runserver.-.Copy.txt)
