### ISSUE TITLE
Radius steps

### ISSUE THREAD

**Issue by EuRusik** [AHAAAAAAA/PokemonGo-Map#552]
Is it possible to make the range more, and that there was no empty space pokemons around the marker location?
Now if I do the steps (-st) over 25+ Pokemon near invisible, just on the verge of radius :(

http://imgur.com/a/az1J0

**Comment by n1tr0g3n4ik** [comment]
Братюнь, объясни как ты карту сделал, а то невкуриваю

**Comment by EuRusik** [comment]
По инструции в описании

**Comment by n1tr0g3n4ik** [comment]
Объясни ты, я запустить не могу только, pip установил и тд

**Comment by MonkeyLeeT** [comment]
There's a radius limit in the code and that's why your center gets cleaned. Ideally you'd like to use less than 20 and a good center for Pokemon searches.
