### ISSUE TITLE
view on iPhone 

### ISSUE THREAD

**Issue by gotrock20** [AHAAAAAAA/PokemonGo-Map#556]
how do I setup port forwarding? I want to be able to view localhost:5000 on my iPhone. 

thank you

**Comment by bddwin7** [comment]
@gotrock20 you can use https://ngrok.com/

**Comment by mcspencehouse** [comment]
You need to run with the option "-H 0.0.0.0" to view from external browser

**Comment by theblackmarmoset** [comment]
Could you explain to me how I would run with the option "-H 0.0.0.0"?  I'm pretty much a mega noob when it comes to this stuff.  @mcspencehouse

**Comment by gotrock20** [comment]
how do I type it in from my iPhone browser? 192.168.1.xx:5000?

**Comment by bddwin7** [comment]
@theblackmarmoset python example.py -a google -u MyLogin -p MyPass -l MyLocation -st 5 -H 0.0.0.0

**Comment by bddwin7** [comment]
@gotrock20 if you just add "-H 0.0.0.0" - yes

**Comment by mcspencehouse** [comment]
Sure!
Just start the server by running: 
`python runserver.py -H 0.0.0.0 -a ptc -u <username> -p <password> -l <long lat> -st <steps>`

**Comment by RyanMBlue** [comment]
To view the map if you are in your internal network, use 192.168.1.xx:5000
To view the map if you are OUTSIDE your network, use your external IP address (whatismyip.com), so ###.###.###.###:5000

**Comment by theblackmarmoset** [comment]
What does the -st mean?  Also, while I'm here, I want to ask how to make the icons bigger.  I've tried moving the icons from the bigger icons folder to the icons folder but no change.  Also my map has no filtering stuff.  I want to know how to get the options to hide pokemon as well.  I'm really new to this so all help would be appreciated <3

**Comment by gotrock20** [comment]
do I need to setup some kind of port thing in my att verse routes ? it not working with I try 192.168.1.73:5000

**Comment by gotrock20** [comment]
nvm got it. my window firewall block it

**Comment by theblackmarmoset** [comment]
I still don't know how to view it on the iphone.  I put in my ip that I got from looking up my ip into the safari browser on my phone and it just comes up with an error.  Someone pls help

**Comment by talentedmrripley** [comment]
@theblackmarmoset You will most likely need to forward a port on your router.  This allows you to go to the public IP that you get from whatismyip.com and have that request sent to the computer running the software.  See if you can find your router here, http://portforward.com/ and then follow the directions.
