### ISSUE TITLE
Can't see the map, only the GoMap header

### ISSUE THREAD

**Issue by iTayGNR** [AHAAAAAAA/PokemonGo-Map#557]
![default](https://cloud.githubusercontent.com/assets/6430313/16990948/91bdc3a0-4ea2-11e6-9129-9aaff144bd87.png)
I see only the header but not the map. what can I do?

**Comment by Sciguymjm** [comment]
Do you have a Google Maps API key? 

https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Google-Maps-API:-a-brief-guide-to-your-own-key

**Comment by DerScreever** [comment]
get the latest changes. then it should work.

**Comment by iTayGNR** [comment]
@Sciguymjm yes. i updated it.
@DerScreever what changes? of the project?

**Comment by timdine** [comment]
#529 is the same.

**Comment by iTayGNR** [comment]
@DerScreever map loaded. but I can't see any pokemons!

**Comment by iTayGNR** [comment]
a refresh solved it. thanks!

**Comment by theblackmarmoset** [comment]
What is gomap?  Are there filters in the map you use like to filter out common pokemon?

**Comment by mkody** [comment]
@theblackmarmoset The "GoMap" you see in the screenshot is this project! Filters are not on the map (for now), but can be specified with an argument when starting the python script.

**Comment by janitory** [comment]
This also happens trying to manually refresh the page using latest Opera beta version.

If you visit the site using for instance "http://localhost:port" it works fine, however upon loading the site for the first time, an / is added to the end. Manually refreshing the page (STRG+R / F5) now tries to open "http://localhost:port**/**" resulting in the situation of the image above.

Removing the "/" at the end and visiting the site, shows the map again.
