### ISSUE TITLE
Team Instict yellow gym icons are hard to see

### ISSUE THREAD

**Issue by pasky** [AHAAAAAAA/PokemonGo-Map#558]
Do you agree that team instinct yellow gym icons are much harder to see on the map than the blue and red gyms?

Maybe adding a black or brown outline to the team instinct artwork would fix this.

**Comment by theblackmarmoset** [comment]
I may agree with that if I knew how to see the icons on the map.  All I see are pokemon atm.  Could someone tell me how to see the other stuff?

**Comment by MikeDX** [comment]
from the WIKI 

-dp = display pokestops
-dg = display gyms

**Comment by talentedmrripley** [comment]
@pasky I have meant to post this same thing.  The other gyms, red and blue, are easily visible but the yellow is very hard to make out.

**Comment by haagiboy88** [comment]
We are aware of this. But this is a low priority task and not development related. You can even do it yourself by chaning out the relevant icon for one with borders :)
