### ISSUE TITLE
Page is completely white and displays only "<h1>Flask Google Maps Full Map Example</h1>".

### ISSUE THREAD

**Issue by hughpearse** [AHAAAAAAA/PokemonGo-Map#559]
Description
Page is completely white and displays only "<h1>Flask Google Maps Full Map Example</h1>".

Operating System:
Fedora 21

Installed version of Python:
2.7.8

### Steps to reproduce
1. sudo pip install geopy protobuf requests flask-googlemaps s2sphere flask gpsoauth coveralls werkzeug
2. python example.py -a google -u *.*.*.*.@gmail.com -p *.*.*.*. -l "53.*.*.*.*., -6.*.*.*.*." -st 2
3. wait for steps to load
4. http://127.0.0.1:5000/

![screenshot from 2016-07-20 16 09 58](https://cloud.githubusercontent.com/assets/681555/16991977/6fc4fc30-4e95-11e6-80b0-2391d08b39d1.png)

**Comment by Joncy** [comment]
Also happening on OS X 10.11.5 with python 2.7.10

**Comment by rezz3x** [comment]
"Support for master branch dropped."

Use the develop branch.

**Comment by DerScreever** [comment]
@rezz3x 
like he said, the support for master branch dropped.

**Comment by n1tr0g3n4ik** [comment]
![screenshot_18](https://cloud.githubusercontent.com/assets/20505470/16994020/579eac6e-4eae-11e6-9a73-6d49e62ea126.png)
All work, but only 1 pokemon in map.
