### ISSUE TITLE
How to set up on CentOs 7

### ISSUE THREAD

**Issue by ddiesenreither** [AHAAAAAAA/PokemonGo-Map#560]
Hey Guys,

can somebody tell me how to set this up on my CentOS 7 Server. I have already successfully installed it and can run the example.py but i dont know how to access. I have it on an external server and i set "-H" to my IP Address and the Port is 5000. But when i load http://IP-ADDRESS:5000 nothing is happening.

Please help me i love this project.

Cheers

**Comment by equatebrand** [comment]
Not sure about CentOS 7, but this is what I did for CentOS6, substituting *** with my info:
`yum groupinstall "Development tools"
yum install zlib-devel
yum install bzip2-devel
yum install openssl-devel
yum install ncurses-devel
yum install sqlite-devel
cd /usr/src
wget https://www.python.org/ftp/python/2.7.12/Python-2.7.12.tar.xz
wget ***/PokemonGo-Map-master.zip
tar xf Python-2.7.12.tar.xz
unzip PokemonGo-Map-master.zip
cd Python-2.7.12
./configure --prefix=/usr/local
make && make altinstall
cd ..
curl -O https://bootstrap.pypa.io/get-pip.py
python2.7 get-pip.py
cd PokemonGo-Map-master
pip2.7 install -r requirements.txt
yum install screen
screen -S ***`
Then in screen:
`python2.7 example.py -a ptc -u *** -p *** -l "***" -st 10 -H 0.0.0.0 -P 5000`
and finally CTRL+A then D to detach.

**Comment by ddiesenreither** [comment]
Thanks for your reply, a few questions:

1. what does the *** mean on "screen -S ***"
2. how do i access the map in the browser when the script is running? ( i know little bit nooby 💃  )

**Comment by 0z4ck** [comment]
Hi.
If your server is a kind of VPS, you may need to open your port from your control panel of the account.

First, try curling from locale, another words execute "curl localhhost:5000" in your server with another process. 

If you can get the response , add the parameter "-H 0.0.0.0" in executing example.py and do "curl yourGlobalipOrDomainName:5000".

if you can't get the response , as I told you above you have to configure .

**Comment by equatebrand** [comment]
> Thanks for your reply, a few questions:

>what does the *** mean on "screen -S ***"
>how do i access the map in the browser when the script is running? ( i know little bit nooby :dancer: )

The *** is any name you choose. Maybe
`screen -S pokemon`
or just
`screen`

To access the map in a browser, just go to
http://your.ip.address:5000
assuming there's no firewall issues preventing you from getting to it. You might have to
`systemctl disable firewalld`

`systemctl stop firewalld`
though that will open up your system to, ya know, stuff.

**Comment by ddiesenreither** [comment]
Thank you guys, the issue was the firewall of my VPS i just opened up the 5000 Port.

2 beer for you guys 🍻  thanks
