### ISSUE TITLE
Pokemon go deployment on windows

### ISSUE THREAD

**Issue by Wickrman** [AHAAAAAAA/PokemonGo-Map#561]
Pokemon Go map on windows

Hi 

I'm fairly new to Github and my mate tried this worked instatly on linux, i'm trying on windows. 
What i've done so far : 

Made an app on heroku, got heroku toolbelt, got git, got python 2.7

working on: windows 10 - 64bit

The wiki shows very little information for windows users so i'm totally without a clue on how to continue. 

What I did so far : 

1) Cloned the repository to a local git repository 
2) got a unique google API key and adjusted this in credentials.json
3) when i Try to run the app it says there is no proc file. 

Wiki says make a blank procfile and heroku does the rest but this does not work, neither am i Sure wether the empty procfile has even been pushed to the master. 

--> So i need clarification on this 

Also I noticed a step to start a web process so the app can run. 

I receive error : scaling dynos ...

Couldn't find that information

So probably this has something to do with my proc file i'm guessing? 

So how do I continue from here on ? i find this hugely interesting but there as a complete noob this is already quite complex ^^ 

Any help would be hugely appreciated!

**Comment by Wickrman** [comment]
Also  this is my logging : 

2016-07-20T15:22:38.969272+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/" host=pokefinder3.herokuapp.com request_id=2f6fa2


Which brings me back to the heroku ps:scale web=1 then it gives me errors : 

couldn't find that information

**Comment by bestdark** [comment]
windows 10 - 64bit works perfect
make sure that you have installed all depencies
https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Installation-and-requirements
