### ISSUE TITLE
Don't know how to view on iphone still.

### ISSUE THREAD

**Issue by theblackmarmoset** [AHAAAAAAA/PokemonGo-Map#564]
Could someone please give me a tutorial on how to view this from my iphone?  I looked at the other guy's post and I added the "-H 0.0.0.0" and then looked up my ip with the :5000 at the end but nothing showed up.  I'd also like to ask how to filter out different pokemon because I don't have that option either.  I'm using google flask if that helps.

**Comment by IQNeoXen** [comment]
Are you using windows or linux? Try turning off the firewall and comment again

**Comment by theblackmarmoset** [comment]
Okay so I tried turning off my firewall and I still get nothing when putting my ip + :5000.  I'm using windows btw.  What could it be?

**Comment by IQNeoXen** [comment]
What exactly shows up when entering the IP into your phone?

**Comment by theblackmarmoset** [comment]
"Safari could not open the page because the server stopped responding"

**Comment by IQNeoXen** [comment]
Ok try typing "ipconfig" in your CMD and use your local ipv4 adress for the "-H x.x.x.x" parameter... that's how i got it working

**Comment by Nulifyer** [comment]
from what ive seen it has to do with safari itself i dont think it supports some formats that flask and python are using try getting the google chrome app on iphone and see if that works

**Comment by theblackmarmoset** [comment]
Wait, I thought the 0s in "-H 0.0.0.0" was supposed to be all 0s.  I'm not sure what you mean by "use your local ipv4 address for the "-H x.x.x.x" parameter".  Sorry I'm so new to this,  I just want it to work for my phone.  @IQNeoXen

**Comment by IQNeoXen** [comment]
No it doesn't have to be 0.0.0.0... just look up your local IP Adress (cmon you srsly don't know how to do this? :D ) and use it in the host option

**Comment by theblackmarmoset** [comment]
Wow I feel so stupid.  You honestly probably think I'm just trolling at this point. lol  I'm going to try to put my ipv4 in for the 0.0.0.0

**Comment by theblackmarmoset** [comment]
Okay once I have that running with the cmd prompt what do I put into my web browser?

**Comment by theblackmarmoset** [comment]
Btw getting the chrome app didn't help.  I feel so helpless right now. :(

**Comment by Nulifyer** [comment]
you want to put the local ip:port of the computer running the program as long as the web browser is on the same wifi

**Comment by theblackmarmoset** [comment]
I'm trying to be able to use this while I'm out of the house on my phone.  Is there any way to do that?  @Nulifyer

**Comment by Nulifyer** [comment]
if the chrome app didnt work then there is a problem with using this on apple, or you configured this wrong. as far as using this outside your house i just got that working about 30 min ago so yea it works but i have a android phone. also you need to portforward the port you using in you router so that people or just you can connect outside of our wifi.

**Comment by 0z4ck** [comment]
Hey guys .
 First , I recommend you to try to ping one to another device to verify if the packet can go through the LAN.

If you don't have the response, it means your router filters your packets.

Then , you have to configure them.

**Comment by Nulifyer** [comment]
C:\Python27\python.exe "C:\Users\kylee\Desktop\PokemonGo-Map-master\example.py" -a PTC -u ******* -p ***** -l "lattitude, longitude" -st 12 -dg -dp -ar 15 -H 0.0.0.0 -P 5000

^^ my command

**Comment by IQNeoXen** [comment]
Yep, got it working for me too with port forwarding. Pro-Tip: Use a Bubble-Browser so you don't have to switch between the map and pokemon go :D pretty awesome

**Comment by theblackmarmoset** [comment]
Thank you so much for all the help guys!  But I have a few questions.  What's a bubble browser?  How do I ping them?  And how do I port forward?

**Comment by IQNeoXen** [comment]
My Command:
`sudo python example.py -a google -u *********@gmail.com -p ************** -l "*********** Street 16" -st 5 -L de -dg -dp -H 192.168.178.27`

Where `192.168.178.27` is my local IP.

**Comment by Nulifyer** [comment]
port forwarding is router specific , depends on what you have and what your router is ( can help http://portforward.com/ ) . also dont put your local ip put 0.0.0.0

**Comment by Nulifyer** [comment]
http://poketeamstats.com/

**Comment by 0z4ck** [comment]
Look, if you are in the same segment, you don't need to "port forward" .

if your 3 first block of your IP adress is the same , you are in the same segment.

**Comment by Nulifyer** [comment]
@0z4ck he wants to use it outside the house

**Comment by theblackmarmoset** [comment]
Okay, so what do I put into the URL bar when I want to use the map outside my house?  I got the -H 0.0.0.0 thing set up now.

**Comment by 0z4ck** [comment]
@Nulifyer oh, sorry :D

**Comment by IQNeoXen** [comment]
You have to use a Dynamic DNS... Dude, no offense, but it seems like you're a total noob to this. Why don't you use https://pokevision.com/ or similar services? Works just as fine....

**Comment by theblackmarmoset** [comment]
None taken man.  I know how bad I am at this but I really want to learn how to use all this stuff.  I have to go now but maybe when I get back someone could help me or something.  Idk, sorry for wasting your guys' time. :(

**Comment by Nulifyer** [comment]
make sure that you type in http://[ip]:[port]

this api does not support https which has ssl and other stuff

**Comment by Hardstylah** [comment]
To piggyback off of him, I get an error on phone after 5 seconds of use. Oops something went wrong check your JS console. On google chrome and mozilla firefox Galaxy S7 Edge. No idea what could be the problem.

**Comment by IQNeoXen** [comment]
@Hardstylah I know exactly what is going on :P had this error myself... you need to get your own Google Maps JS API Key and put it in the credentials.json works fine for me now.

**Comment by Hardstylah** [comment]
Thanks! Will get one.

**Comment by Hardstylah** [comment]
This fixed it, Thanks alot!!!

**Comment by Nulifyer** [comment]
that issue bugged me so much for like two hours a day ago haha

**Comment by Hardstylah** [comment]
Although that is an option this one is way simler imo. just had to ask a Google api key which didnt even take 3 mins.

**Comment by rohangro** [comment]
Does the above way work if you're on LTE/far from home, not connected to the same wifi?

**Comment by Hardstylah** [comment]
Yes it does.

**Comment by Nulifyer** [comment]
yes you shouldnt need to be on your wifi if you have:
1. run the command with -H 0.0.0.0 -P 5000 
2. portforwared your router so connections to port 5000 go to the pc running the script
3. gotten a new api key from google maps
4. there are no unexpsected errors

note: if you are on the same wifi you will not know if it work until you are not. turning off wifi on your phone and trying to connect via : 
          "make sure that you type in http://[ip of router]:5000 in the url bar
           get router ip here http://www.ipchicken.com/
           this api does not support https which has ssl and other stuff"
should tell you if it works.

**Comment by theblackmarmoset** [comment]
Alright guys!  Thank you so much for the help.  One quick question, how do I port forward so the port 5000 goes to my pc?   Here is a screenshot of what my port forwarding page looks like.  http://prntscr.com/bvctbx

**Comment by Nulifyer** [comment]
The source port should be any and the destination should be 5000. There
should be a tutorial on portforward.com ( think I mentioned it before )

**Comment by Nulifyer** [comment]
If that doesn't help I'll go I to detail later when I'm home

**Comment by theblackmarmoset** [comment]
Alright.  This is what it looks like now: http://prntscr.com/bvcx23  

This is what I'm putting into cmd:

python example.py -a ptc -u ******** -p ******* -l "Adress" -st 10 -H 0.0.0.0 -P 5000

And I am typing this into chrome app on my iPhone: "http://[IP I got from searching "IP" in google]:5000"

When I put that into the chrome app on my phone it comes up with "This site can't be reached"

I hope I gave you enough info to diagnose the problem when you have the time.  Thanks for helping me with this btw. <3

**Comment by Nulifyer** [comment]
Is there a any option for inbound port , mine is set up for any port -> 5000

**Comment by theblackmarmoset** [comment]
It says inbound port here http://prntscr.com/bvd2eb but there is no option for "any port"  i have to type one in.

**Comment by Nulifyer** [comment]
What model is your router

**Comment by theblackmarmoset** [comment]
F9K1113v2 (01)  Thats what it says under the "model" section for my router.

**Comment by theblackmarmoset** [comment]
Is everything else I did correct?

**Comment by Nulifyer** [comment]
Seems so , as long as you see the step [x] of [y] in the console

**Comment by theblackmarmoset** [comment]
Then I'm not sure why I can't look at it on my phone.  Do you have any clue?

**Comment by theblackmarmoset** [comment]
Also I do see the step x of y thing

**Comment by Nulifyer** [comment]
Well , port forwarding is only for outside your home if you put the same URL but replace the IP with the computer's local IP does it come up?

**Comment by theblackmarmoset** [comment]
Would typing localhost:5000 be the same if I'm at home on my phone as putting the local ip in?

**Comment by Nulifyer** [comment]
If that's what you see it means the script started and got a handshake with Pokemon go servers , if you want we can talk more detail outside this thread maybe a skype call or something because it seems you might need more guidance in setting up and connection although it's possible it's just a apple problem try connecting from a different computer in the house in the same manner

**Comment by Nulifyer** [comment]
Local host would work but it might not yield the same results as using 0.0.0.0

**Comment by Nulifyer** [comment]
Oh wait you mean local host The URL no you need to get the actual local IP of the pc

**Comment by theblackmarmoset** [comment]
Oh alright.  Yeah I typed in the local ip with the :5000 on my phone but still no results.  I think we should talk over skype.  It would be easier

**Comment by Nulifyer** [comment]
I will contact you later when I get the chance maybe a hour or two idk then
we can Skype

**Comment by theblackmarmoset** [comment]
How do I message you on here?

**Comment by theblackmarmoset** [comment]
whatever. just add my skype: theblackmarmoset

**Comment by theblackmarmoset** [comment]
Also I have use Ethernet not wireless so could that interfere with this?

**Comment by Nulifyer** [comment]
No Ethernet would not , also let make a discord instead that way people can join seems a few people need help not just one

**Comment by Hardstylah** [comment]
what did it for me was chaning -H 0.0.0.0 into my actual ipv4 hah i overlooked it.

**Comment by MonkeyGoneWIld** [comment]
Could someone tell me how to get my own Google Maps JS API Key and how do i put it into credentials.json?

**Comment by Hardstylah** [comment]
https://developers.google.com/maps/documentation/javascript/get-api-key 
Create project and edit .json the last one should be gmaps key "xxxx" Just change that and you are good to go.

**Comment by theblackmarmoset** [comment]
alright sure.  a discord would work perfectly.  im busy right now but ill probably be free in about 3 hours

**Comment by Nulifyer** [comment]
Same

**Comment by theblackmarmoset** [comment]
I'm free for a discord right now.  You down to start one?

**Comment by Nulifyer** [comment]
I'm going to be busy Untill late sorry

**Comment by theblackmarmoset** [comment]
Alright man, no worries.   How can I contact you other than on here?

**Comment by Nulifyer** [comment]
Skype: kyle.edward.leddy@gmail.com ( username is nulifyer but that's is the
account )
