### ISSUE TITLE
How to make the icons bigger/smaller?

### ISSUE THREAD

**Issue by theblackmarmoset** [AHAAAAAAA/PokemonGo-Map#565]
Since I tried replacing the small icons with the large ones only a few got replaced and the rest are still little icons on the map.  Is there any way to replace all the icons on the map with larger icons?

**Comment by Sejadis** [comment]
clear your browser cache and you will see the icons you replaced

**Comment by theblackmarmoset** [comment]
Thank you so much man!  Helps a lot!

**Comment by theblackmarmoset** [comment]
Do you also know how to get the map to be able to hide certain pokemon?

**Comment by DerScreever** [comment]
@theblackmarmoset you could use the -i flag to ignore them
just pass them like -i xyz, xyz, xyz
