### ISSUE TITLE
How do i install the dependencies??

### ISSUE THREAD

**Issue by bmisheel** [AHAAAAAAA/PokemonGo-Map#569]
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discord.gg/Kzp4yky).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System: OS X El Capitan 

Installed version of Python:
Python 2.7.12 shell

### Steps to reproduce
1. i cant seem to download the dependencies. 
2. "Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt' when i run "pip install --upgrade -r requirements.txt" on terminal 
3. or i get SyntaxError on both Python 3.5.1 and 2.7.12

### What have you tried?
this is what i get on my python
"""Collecting pip
  Using cached pip-8.1.2-py2.py3-none-any.whl
Collecting wheel
  Using cached wheel-0.29.0-py2.py3-none-any.whl
Installing collected packages: pip, wheel
  Found existing installation: pip 8.1.1
    Uninstalling pip-8.1.1:
      Successfully uninstalled pip-8.1.1
Successfully installed pip-8.1.2 wheel-0.29.0
>>> pip install --upgrade -r requirements.txt
SyntaxError: invalid syntax
"""
How do i get past the SyntaxError? 

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by Wes974** [comment]
Try this :  sudo pip install --upgrade -r requirements.txt

**Comment by bmisheel** [comment]
i get "IndentationError: unexpected indent"

**Comment by murych** [comment]
Try `sudo pip install -r requirements.txt` without `--upgrade`. Worked for me.

**Comment by bmisheel** [comment]
Im kinda new to programming but when i try that, it still gives me a syntaxerror on python, highlighing "pip"

**Comment by GTB3NW** [comment]
I was having issues because as it turns out, pip2 isn't installed but pip3 is. Despite running it in a python2 virtualenv, it was running pip with pip3.

**Comment by bmisheel** [comment]
"""We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

Password:
Sorry, try again.
Password:
"""
what does this mean?

**Comment by Wes974** [comment]
"We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

#1) Respect the privacy of others.
#2) Think before you type.
#3) With great power comes great responsibility."

This part is just the warning when you use `sudo`the first time.

"Password:
Sorry, try again.
Password:"

And this part just mean that you typed your password wrong.

**Comment by bmisheel** [comment]
"student is not in the sudoers file.  This incident will be reported." ? so in the end it still doesnt work?

**Comment by mkody** [comment]
@bmisheel Well, it means you havent granted the user `student` the right to get  _"admin privileges"_.
If this is your machine and you have access to the `root` user, login with the `root` user and add you user to the sudoers [(see here how to do it)](http://askubuntu.com/a/7484).

Also, about this: 
> "Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt' when i run "pip install --upgrade -r requirements.txt" on terminal

It just means you were not in the root folder of this project, where the `requirements.txt` file is.

**Comment by GTB3NW** [comment]
add the user student to the group wheel & sudo

**Comment by Zach1993** [comment]
I had the same issue, so what you need to do is go to the root folder, and then try pip install --upgrade -r requirements.txt --user python this way it is using python user and you dont need to use sudo.

**Comment by bmisheel** [comment]
after all that, I am still unable to fully run the text and i keep getting this error, help?
"""Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/m6/998ksr450z541tt8bvnpgrz40000gp/T/pip-build-V1HRbd/protobuf/
""

**Comment by bmisheel** [comment]
No matter what i do, i keep getting error which says "Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-9ZRDsq/protobuf/"

**Comment by mkody** [comment]
It would be great if you'd share the full log there. 
I didn't see you were using OSX, so I can guess you need to have the build tools there. Do you have XCode and XCode's command line tools installed on your Mac?

**Comment by bmisheel** [comment]
bMisheel:PokemonGo-Map-master student$ sudo pip install -r requirements.txt
The directory '/Users/student/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/student/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting geopy==1.11.0 (from -r requirements.txt (line 1))
  Downloading geopy-1.11.0-py2.py3-none-any.whl (66kB)
    100% |████████████████████████████████| 71kB 3.6MB/s 
Collecting protobuf==2.6.1 (from -r requirements.txt (line 2))
  Downloading protobuf-2.6.1.tar.gz (188kB)
    100% |████████████████████████████████| 194kB 3.2MB/s 
    Complete output from command python setup.py egg_info:
    Download error on https://pypi.python.org/simple/google-apputils/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590) -- Some packages may not be found!
    Couldn't find index page for 'google-apputils' (maybe misspelled?)
    Download error on https://pypi.python.org/simple/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590) -- Some packages may not be found!
    No local packages or download links found for google-apputils
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-9ZRDsq/protobuf/setup.py", line 200, in <module>
        "Protocol Buffers are Google's data interchange format.",
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/dist.py", line 269, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/dist.py", line 313, in fetch_build_eggs
        replace_conflicting=True,
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 826, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1092, in best_match
        return self.obtain(req, installer)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1104, in obtain
        return installer(requirement)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/dist.py", line 380, in fetch_build_egg
        return cmd.easy_install(req)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 634, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('google-apputils')
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-9ZRDsq/protobuf/
bMisheel:PokemonGo-Map-master student$

**Comment by bmisheel** [comment]
i do have xcode installed

**Comment by mxwllco** [comment]
Ah i'm a designer trying to get this going but I hit a `Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'`
after `sudo pip install --upgrade -r requirements.txt`

**Comment by mkody** [comment]
@bmisheel So yeah, I see now where's the problem. `[SSL: CERTIFICATE_VERIFY_FAILED]` 
I don't remember how to fix this properly on OS X, give me a minute.

@mxwilco Make sure your in the root folder of the project before launching this.

**Comment by Zach1993** [comment]
@bmisheel did you try? >> 
pip install --upgrade -r requirements.txt --user python

**Comment by bmisheel** [comment]
@Zach1993  yeap, i tried that as well. all of it didnt work

**Comment by mkody** [comment]
OK, I remember that setuptools may need to be updated on old version of pip and OpenSSL. Could you try running this on your terminal?
`curl https://bootstrap.pypa.io/ez_setup.py -o - | python` -  This will download a recent version of setuptools and install it. [See official repo here.](https://github.com/pypa/setuptools/tree/master#unix-including-mac-os-x-curl)

**Comment by bmisheel** [comment]
Neither """curl https://bootstrap.pypa.io/ez_setup.py -o - | python""" OR """curl https://bootstrap.pypa.io/ez_setup.py -o - | sudo python"""  works. This is what I get. 
"""
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Pa100 12402  100 12402    0     0  13261      0 --:--:-- --:--:-- --:--:-- 13264

Traceback (most recent call last):
  File "<stdin>", line 426, in <module>
  File "<stdin>", line 422, in main
  File "<stdin>", line 337, in download_setuptools
  File "<stdin>", line 358, in _resolve_version
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>
"""

**Comment by breandr** [comment]
Also getting this egg_info error...

**Comment by GTB3NW** [comment]
Certificate errors sometimes are due to massive difference in computer clocks. Make sure you're time-synced with a timeserver.

Can you navigate to pypi in a browser?
