### ISSUE TITLE
Python Exception in thread search_thread

### ISSUE THREAD

**Issue by higyigma** [AHAAAAAAA/PokemonGo-Map#571]
### Environment info
Operating System: Debian 8
Windows 7

Installed version of Python: 2.7

### Steps to reproduce
1. Run example.py or runserver.py
2. ????
3. Death

### What have you tried?
1. Different computers
2. Different login authentication (Google, which results in request error 104, connection reset by peer loop)
3. Installing Dev Branch

### Logs or other output that would be helpful
C:\Users\rvoyles\Downloads\PokemonGo-Map-master>python example.py -a ptc -u LoginName -l "Blank Blank SD" -st 5
[-] register_background_thread called
[-] register_background_thread: not running inside Flask so not starting thread
 * Restarting with stat
[-] register_background_thread called
[-] register_background_thread: initial registration
 * Debugger is active!
[+] Locale is en
[+] Getting initial location
 * Debugger pin code: 109-366-621
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[!] Your given location: Blank Blank, SD, USA
[!] lat/long/alt: *********
Password:
[!] PTC login for: LoginName
Exception in thread search_thread:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "example.py", line 581, in main
    api_endpoint, access_token, profile_response = login(args)
  File "example.py", line 92, in memoizer
    cache[key] = obj(*args, **kwargs)
  File "example.py", line 514, in login
    access_token = get_token(args.auth_service, args.username, global_password)
  File "example.py", line 429, in get_token
    global_token = login_ptc(username, password)
  File "example.py", line 331, in login_ptc
    r = SESSION.get(LOGIN_URL, headers=head)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 487, in get
    return self.request('GET', url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 475, in reques
t
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 453, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(10054, 'An existing connection wa
s forcibly closed by the remote host'))

**Comment by DerScreever** [comment]
Im sorry, but we dropped the support for the master branch (example.py). 
This branch is deprecated.

The new branch contains a much cleaner structure so pls report only issues related to the develop branch.

Your development team

**Comment by higyigma** [comment]
Still happens on the dev branch, as I said in the report :P

**Comment by JohnDoeSec** [comment]
I'm also having this same issue.

**Comment by danielmarquespt** [comment]
Same issue on the Dev branch

**Comment by loki980** [comment]
Same issue on node 6ddb0b919c35b9f03ac04d607661554493bf5670 (latest develop as of right now).

Using windows 7.  The server starts up, the map is displayed with the specified location at localhost:5000.  No pokemon/pokestops/gyms are displayed.  I have my own gmaps api key that's validating as working.  If I change the API key it throws a gmaps API key error, so I have a working API key.

I'm running the server with:
`python.exe runserver.py -a ptc -u username -p password -l "times square" -st 10`

I also replaced "times square" with my current location
`python.exe runserver.py -a ptc -u username -p password -l "xx.xxxx,xx.xxxx" -st 10`

The background GETs are returning:
`{"gyms":[],"pokemons":[],"pokestops":[]}`

If I change my login/password to an invalid one, the same behavior is exhibited, so it appears there's an issue with authentication.  I also tried the following with the same error:
`python.exe runserver.py -a ptc -uusername -ppassword -l "xx.xxxx,xx.xxxx" -st 10`
`python.exe runserver.py -a ptc -u "username" -p "password" -l "xx.xxxx,xx.xxxx" -st 10`
`python.exe runserver.py -a ptc -u 'username' -p 'password' -l "xx.xxxx,xx.xxxx" -st 10`

I was going to try a google account, but I can't seem to figure out how to sign up using one...

**Comment by loki980** [comment]
Looking at `search.py`, line 54, `log.info('Login to Pokemon Go successful.')` means you should see:
> [     search] [   INFO] Login to Pokemon Go successful.

I do not see that.  There's something wrong with logging in.

**Comment by loki980** [comment]
Figured it out.  Try accessing the following URL from localhost:
> https://sso.pokemon.com/sso/login

For me, it was blocked by my firewall.

**Comment by higyigma** [comment]
Loki solved.
