### ISSUE TITLE
Object has no attribute 'latitude'

### ISSUE THREAD

**Issue by 23o9** [AHAAAAAAA/PokemonGo-Map#577]
### Environment info
Operating System: Ubuntu 14.04.4 LTS

Installed version of Python:
Python 2.7.6

### Steps to reproduce
Yeah, so this worked flawlessly for quite some time. I thought it may be due to an API key rejection from Google, but I guess not. I have updated my API key anyway.

I run the following command: _python example.py -a Google -u USERNAME -p PASSWORD -st 5 -l "Big Ben, London"_

**Error is at the end of the post.**

### What have you tried?
1. Changed GMaps API key
2. Tried another Google account
3. Tried running it on a different operating system (OS X)

None of this held any success.

### Logs or other output that would be helpful
After I get a debugger pin code, the following occurs:

> Exception in thread search_thread:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
>     self.run()
>   File "/usr/lib/python2.7/threading.py", line 763, in run
>     self.__target(*self.__args, **self.__kwargs)
>   File "example.py", line 571, in main
>     retrying_set_location(args.location)
>   File "example.py", line 157, in retrying_set_location
>     set_location(location_name)
>   File "example.py", line 177, in set_location
>     origin_lat, origin_lon = local_lat, local_lng = loc.latitude, loc.longitude
> AttributeError: 'NoneType' object has no attribute 'latitude'

**Comment by Sejadis** [comment]
i guess the missing -u was accidently deleted when removing your login data?

**Comment by 23o9** [comment]
@Sejadis yes, thanks! I put it back in.
