### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by talentedmrripley** [AHAAAAAAA/PokemonGo-Map#581]
I see several new command line switch options but am not able to ascertain their function.  Can this info be added to the readme or included in the wiki?

Examples:
-dl
-c
-d
-m

**Comment by DerScreever** [comment]
https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Usage/f485f5ddab14d5fbab24fab3afea5cc00f7165d7

we will update later

**Comment by npeep** [comment]
I would also appreciate it being updated!   I've added the table as it stands now below.

Flag | Description 
------------ | -------------
-u | Username
-p | Password
-l | Any location Google Maps can understand
-st | Steps to take
-i, --ignore | Comma-separated list of Pokémon to ignore
-o, --only | Comma-separated list of Pokemon to search for exclusively
-dp, --display-pokestop | Display pokestop
-dg, --display-gym | Display gym
-dl | ????
-h | ????
-H | Host?
-P | Port?
-L | ???Locale???
-ar | Auto Refresh?
-c | ????
-d | ????
-m | ????
-k | ????

**Comment by DerScreever** [comment]
this was the old: https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Usage/f485f5ddab14d5fbab24fab3afea5cc00f7165d7

```
    parser.add_argument('-c', '--china', help='Coordinates transformer for China', action='store_true')
    parser.add_argument('-d', '--debug', help='Debug Mode', action='store_true')
    parser.add_argument('-m', '--mock', help='Mock mode. Starts the web server but not the background thread.', action='store_true', default=False)
    parser.add_argument('-k', '--google-maps-key', help='Google Maps Javascript API Key', default=None, dest='gmaps_key')

```
this has already some help. we will later add the rest.

**Comment by Orrielel** [comment]
The list was previously removed from README.md, to move it to the WIKI, but it was never added;

| Flag                       | Description                                            | Required |
|----------------------------|--------------------------------------------------------|----------|
| `-a` `--auth-service`      | Auth service (PTC or google)                           |          |
| `-u` `--username`          | Username                                               | ✓        |
| `-p` `--password`          | Password                                               | ✓        |
| `-l` `--location`          | Any location Google Maps can understand                | ✓        |
| `-st` `--step-limit`       | Steps to take                                          | ✓        |
| `-i` `--ignore`            | Comma-separated list of Pokémon names or IDs to ignore |          |
| `-o` `--only`              | Comma-separated list of Pokémon names or IDs to search |          |
| `-ar` `--auto-refresh`     | Number of seconds on which to autorefresh              |          |
| `-dp` `--display-pokestop` | Display pokéstops                                      |          |
| `-dg` `--display-gym`      | Display gyms                                           |          |
| `-H` `--host`              | Set web server listening host                          |          |
| `-P` `--port`              | Set web server listening port                          |          |
| `-L` `--locale`            | Locale for Pokemon names: default en, check locale folder for more options |          |
| `-c` `--china`             | Coordinates transformer for China                      |          |
| `-d` `--debug`             | Debug mode                                             |          |
| `-ol` `--onlylure`         | Display only lured pokéstop                            |          |

**Comment by evrardjp** [comment]
👍 

Could someone update the wiki or should we recreate a PR with USAGE.md?

**Comment by dorian-marchal** [comment]
What means "step to take" for the `---step-limit` option ?

**Comment by mkody** [comment]
@dorian-marchal It's the radius to scan from the location you set with `--location`. 
As I remember, it makes this kind of math: **x * n²** (x being Niantic's normal radius when you're playing (in meters), n being the value you give to `--step-limit`)
