### ISSUE TITLE
How would I put this on an Ubuntu server?

### ISSUE THREAD

**Issue by Csgonetwork** [AHAAAAAAA/PokemonGo-Map#582]
Operating System:
Ubuntu 14.04 

How would I put this on an Ubuntu server?
I would need to know where to start off with, im not completely sure since I never use Python for anything else.

If someone can just point me in a direction I hope I am able to figure it out!

( P.S. , DO I need stuff like Apache2 installed? )

**Comment by 23o9** [comment]
Simply git clone, then use -H SERVERIP -P LISTENINGPORT when you execute runserver.py

**Comment by 23o9** [comment]
Oh, you'll also need to "sudo apt-get install git, python, python-dev, python-pip and gcc", before you clone anything

**Comment by algoni** [comment]
I'm using nginx as a reverse proxy for the python app. Nginx can also add HTTP Basic auth to password-protect the instance.

Example site config:

```
server {
server_name example.com; 
listen [::]:80; 
listen 80;

location / { 
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;  
proxy_set_header Host $http_host;
proxy_set_header X-NginX-Proxy true;
proxy_pass http://127.0.0.1:5000/;   
proxy_redirect off;  
auth_basic "Restricted content.";
 auth_basic_user_file /path/to/authfile;
}
}
```

**Comment by Csgonetwork** [comment]
Hmm still dont really understand. WIlling to pay 5$ BTC who can set it up quickly over Teamviewer if possible!

**Comment by IDSninja** [comment]
```
#!/bin/bash
sudo apt-get install gcc git
sudo easy_install pip
git clone https://github.com/AHAAAAAAA/PokemonGo-Map
cd PokemonGo-Map
pip install -r requirements.txt
```
Then you just need to run the script including -H <ip address> and -P <port number>

You don't have to include the port number, but it will bind to 5000 by default.

**Comment by Csgonetwork** [comment]
Thanks! I will immediately try this out!

**Comment by Csgonetwork** [comment]
Then you just need to run the script including -H and -P

You don't have to include the port number, but it will bind to 5000 by default.

Not fully sure how I should run this since I use a .bat file for this to run on windows. Do I just use 

example.py -a PTC -u .. -p .. -l "52.51679, .... " -st 20  -H 0.0.0.0 -P 5000 -ar 5  and tytpe it in putty?

**Comment by IDSninja** [comment]
It would be easier for you to probably run:
```
python example.py -a PTC -u .. -p .. -l "52.51679, .... " -st 20 -H 0.0.0.0 -P 5000 -ar 5
```
Then open your browser to http://your-server-ip-here:5000

**Comment by Csgonetwork** [comment]
Thanks a lot for your help! But seems that there appears an error when I type it in puTTY

 -l "52.51679, 5.47177" -st 20 -H 0.0.0.0 -P 5000 -ar 5
Traceback (most recent call last):
  File "example.py", line 28, in <module>
    from requests.packages.urllib3.exceptions import InsecureRequestWarning
ImportError: No module named packages.urllib3.exceptions
root@localhost:~/PokemonGo-Map# --help
--help: command not found
root@localhost:~/PokemonGo-Map# start --help
Usage: start [OPTION]... JOB [KEY=VALUE]...
Start job.

**Comment by IDSninja** [comment]
run this command to install requests:
```
sudo pip install requests
```

**Comment by Csgonetwork** [comment]
Seems like same error appears...

**Comment by IDSninja** [comment]
The error means you dont have the python requests module and pip is how you install it
