### ISSUE TITLE
Branch Develop Traceback (most recent call last)

### ISSUE THREAD

**Issue by tzull** [AHAAAAAAA/PokemonGo-Map#584]
Hi, i'm running Branch Develop now. Lastime i'm run master branch as well. But after information at wiki said for using develop branch i got some error.
### Environment info
Operating System: Windows 7

Installed version of Python: 2.7

### Steps to reproduce
1. Run runserver.py -a PTC -u xxxxxx -p xxxxxx -l Jakarta -st 50 -ar -k xxxxxxxx_xxxxxxxx

### Logs
Traceback (most recent call last):
  File "C:\Python\GoPokemon\runserver.py", line 10, in <module>
    from pogom.app import Pogom
  File "C:\Python\GoPokemon\pogom\app.py", line 10, in <module>
    from .models import Pokemon, Gym, Pokestop
  File "C:\Python\GoPokemon\pogom\models.py", line 5, in <module>
    from peewee import Model, SqliteDatabase, InsertQuery, IntegerField,\
ImportError: No module named peewee

**Comment by DerScreever** [comment]
pip install peewee

**Comment by tzull** [comment]
Hi Thanks for your information, i think i'm doing mistake did not running requirement.txt. Because i'm from master branch, so i skip requirement.txt and i'm wrong. Hahahahaa

thanks dude.
