### ISSUE TITLE
How to add own google maps api key

### ISSUE THREAD

**Issue by resper** [AHAAAAAAA/PokemonGo-Map#585]
Hello,

i want to add in the credentials.json file my own api key. I have a developer account at google.

What kind of api key I have to request? 
- Browser
- Server
- Android

What I have to add to the fields:
- ptc_client_secret
- android_id
- service
- client_sig-
- gmaps_key

When I request an api key I have only a key name and a key

**Comment by Wickrman** [comment]
gmaps key is your google Api key: the other ones should be filled in already

**Comment by Wickrman** [comment]
{
	"ptc_client_secret"	: "w8ScCUXJQc6kXKw8FiOhd8Fixzht18Dq3PEVkUCP5ZPxtgyWsbTvWHFLm2wNY0JR",
	"android_id"		: "9774d56d682e549c",
	"service"			: "audience:server:client_id:848232511240-7so421jotr2609rmqakceuu1luuq0ptb.apps.googleusercontent.com",
	"client_sig"		: "321187995bc7cdc2b5fc91b11a96e2baa8602c62",
	"gmaps_key"			: "your key" 
}

This is the file i've downloaded from the repository

**Comment by Wickrman** [comment]
Ps : it's not working with me either yet , still trying so don't take my word, listen to other advise too ^^

**Comment by DerScreever** [comment]
https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Google-Maps-API:-a-brief-guide-to-your-own-key


generate a browser key.
