### ISSUE TITLE
How to enter latitude and longitude for location?

### ISSUE THREAD

**Issue by FarisAzka** [AHAAAAAAA/PokemonGo-Map#587]
When using my street name plus city the map is showing the wrong area with the same street name. Since the pin can't be moved, is it possible to enter exact coordinate location?

**Comment by rezz3x** [comment]
just put them in instead of the street name

**Comment by tzull** [comment]
just -l < Street Name or State or City or Country > no need lat and long

**Comment by FarisAzka** [comment]
@rezz3x Silly me. It works. But only if there's a space between the two
-l "-1.23456, 7.8901234" works but -l "-1.23456,7.8901234" (no space) didn't work.

Anybody knows where's the manual that explain each parameter of runserver.py? I need to read that before asking another silly question

**Comment by rezz3x** [comment]
https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Usage

**Comment by FarisAzka** [comment]
No, that page doesn't explain each parameter, the formatting, etc. For example the -ar AUTO_REFRESH. Is it in seconds, miliseconds, or what? What does -dp, -dl, -dg do?

**Comment by FarisAzka** [comment]
Of course, runserver.py --help is the answer. I really need to get some sleep before I ask another stupid question here.
