### ISSUE TITLE
How to change the timezone?

### ISSUE THREAD

**Issue by DanielVolz** [AHAAAAAAA/PokemonGo-Map#589]
I have a +2h on pokemon spawns. Is it possible to change the current timezone?

**Comment by adunna** [comment]
Currently it takes server time. Are you running it on a remote server or local system?

**Comment by DanielVolz** [comment]
I'm running the develop branch locally and have the +2h issue. With the old master branch I had no problems regarding time.

**Comment by daruda87** [comment]
I also have the +2h timezone issue.
Living in GMT+1, running on own pc.

All hours +2

**Comment by daruda87** [comment]
for example, current time 20:01.

Pokémon says:


Jigglypuff - #39
Disappears at 22:11:03 (00m00s)
Get Directions

**Comment by mkorsak** [comment]
I have a time zone issue as well, it's reporting 4 hours behind (so I'm assuming it's going off of UTC time when I'm EDT). Running it on a Ubuntu server, and just checked, my timezone is appropriately set to EDT and my time there is correct.

**Comment by mcmaxl** [comment]
same here, running on ubuntu server with timezone set properly, but pokemon showing +2 hours

**Comment by invisiblek** [comment]
https://github.com/AHAAAAAAA/PokemonGo-Map/pull/576
