### ISSUE TITLE
Disappearing of Poremons

### ISSUE THREAD

**Issue by 0x111** [AHAAAAAAA/PokemonGo-Map#595]
### Environment info
Operating System:
Linux Mint 17.2 Rafaela/Windows 7

Installed version of Python:
2.7.11/2.7.9

### Steps to reproduce
1.Start it like "python example.py -a google -u nick@gmail.com -p Pass -l "55.807645, 37.797870" -st 5 -H 0.0.0.0 -P 5000 -ar 10"
2. Wait for ~30 minutes
3.There is 0 pokemons

### What have you tried?
1.Firstly i used it without -ar, it was the same.

**Comment by janitory** [comment]
Use the dev branch. Master is not supported anymore.
