### ISSUE TITLE
Development branch finding many less pokemon than Master branch

### ISSUE THREAD

**Issue by talentedmrripley** [AHAAAAAAA/PokemonGo-Map#596]
I'm running both the master and dev branch with the same parameters on the same machine.  The master branch is showing about double the amount of Pokemon in my area as the dev branch.

**Comment by docrockulus** [comment]
I have the same issue, I am also unable to see pokestops/gyms on the map in the dev branch.

**Comment by noaqzz** [comment]
http://imgur.com/60HT2SG

python runserver.py -a PTC -u XXX -p YYY -l "ZZZ" -st 6 -H 0.0.0.0 -P 12345 -k AAAAAA

python example.py -a PTC -u XXX -p YYY -l "ZZZ" -st 6 -H 0.0.0.0 -P 12345

**Comment by docrockulus** [comment]
python runserver.py -a google -u xxx -p xxx -l "42.315035 -83.037306" -st 5 -H 0.0.0.0 -P 5000 -ar 30 -i 96

I also have two more running on 5001 and 5002, I see all the pokemon data they have each collected on the 5000 map, but the number of mons is signifigantly less than that of the master branch.

**Comment by daruda87** [comment]
Same issue here...

**Comment by talentedmrripley** [comment]
python example.py -u ***** -p ***** -st 10 -i "Pidgey,Rattata,Paras,Pidgeotto,Geodude,Mankey,Abra,Ponyta,Spearow,Drowzee,Venonat,Zubat" -l "*****,******" -H 0.0.0.0 -P 5002 -dg -ar 3

python runserver.py -u ***** -p ***** -st 10 -i "Pidgey,Rattata,Paras,Pidgeotto,Geodude,Mankey,Abra,Ponyta,Spearow,Drowzee,Venonat,Zubat" -l "*****,*****" -H 0.0.0.0 -dg -ar 3

**Comment by nletourneau** [comment]
This is probably because of the fixing of the spiral logic. The old traversal was doing a lot of duplicate path finding across the map and it has been made a ton better... but the distances between scans is now greater as a side effect of this cleanup. 

Old style (master branch)
![image](https://cloud.githubusercontent.com/assets/225737/16997026/8590aa32-4e68-11e6-88b7-d61f28bf8391.png)

new style (develop branch)
![image](https://cloud.githubusercontent.com/assets/225737/16997034/8fce745c-4e68-11e6-947d-ffdf59d2beeb.png)

Likely need to just lower the 0.0025 in search.py to something like 0.0005 and increase the steps.

**Comment by docrockulus** [comment]
@nletourneau Confirmed this improved pokemon finding. Is it possible to display those paths or did you draw them manually?

**Comment by noaqzz** [comment]
> Likely need to just lower the 0.0025 in search.py to something like 0.0005 and increase the steps.

0.0005 seems to be overkill. it takes many more steps to get an equal map. 0.0012 seems better

**Comment by nletourneau** [comment]
If you want to generate google maps links of the traversal path you can use this:

```python
loc = [lat,lng]
steps = generate_location_steps(loc, 5)
polyline = ''.join(map(lambda l: '{:f},{:f}|'.format(l[0], l[1]), steps))[:-1]
print 'http://maps.googleapis.com/maps/api/staticmap?size=400x400&path='+polyline
```

**Comment by tekulvw** [comment]
What about something more like this? (search path from #645)

![image](https://cloud.githubusercontent.com/assets/3731082/17002617/22a563f4-4e9a-11e6-88ac-7afb4a982001.png)

**Comment by docrockulus** [comment]
Most people are probably concerned with the pokes close to their location first, with the more distant ones being less of a priority. Starting from the center out is probably more useful.

**Comment by falko100** [comment]
Will it take more time to do if you have more steps ? Is there some sort of cooldown before being able to "scan" again ?

**Comment by tekulvw** [comment]
Fair point @docrockulus I didn't have that sort originally because I wanted to conserve memory by not holding the entire list of coordinate pairs in memory in order to sort them but I guess the need to start close trumps that. Here's the new planned pathing:

![image](https://cloud.githubusercontent.com/assets/3731082/17003031/25b251ea-4e9c-11e6-99cf-3e2181979eb3.png)

**Comment by docrockulus** [comment]
@tekulvw Are those first steps Center, S, NW, E, E, NW?

**Comment by tekulvw** [comment]
They are, full list is below.

```
[(0.0, 0.0, 0), (-0.0025, 0.0, 0), (0.0, -0.0025, 0), (0.0, 0.0025, 0), (0.0025, 0.0, 0),
(-0.0025, -0.0025, 0), (-0.0025, 0.0025, 0), (0.0025, -0.0025, 0), (0.0025, 0.0025, 0),
(-0.005, 0.0, 0), (0.0, -0.005, 0), (0.0, 0.005, 0), (0.005, 0.0, 0), (-0.005, -0.0025, 0),
(-0.005, 0.0025, 0), (-0.0025, -0.005, 0), (-0.0025, 0.005, 0), (0.0025, -0.005, 0),
(0.0025, 0.005, 0), (0.005, -0.0025, 0), (0.005, 0.0025, 0), (-0.005, -0.005, 0),
(-0.005, 0.005, 0), (0.005, -0.005, 0), (0.005, 0.005, 0)]
```

**Comment by gui710** [comment]
Could any of you guys ( @tekulvw  or @docrockulus ) help me understand this better?
I'm kind of lost in this subject and wouldn't something like this be better (I don't know how to do those things)?

![untitled](https://cloud.githubusercontent.com/assets/10745669/17009265/d1b2c3f4-4ef0-11e6-9d4c-9ccb4df4e87c.png)
I'm very sorry for my broken English, my drawing skills (that are over 9000) and also my knowledge for not knowing how to do those things.

**Comment by nletourneau** [comment]
Did some investigation on when things show up, radius of 100m seems to be the key. For max efficiency it should be some sort of circle packing with overlap, probably hexoganal. I might throw up a PR for comments and to see if people are interested.

**Comment by gui710** [comment]
@nletourneau Just asking how do you generate something like @tekulvw and @docrockulus did and change it on your server?

**Comment by Hexadigital** [comment]
I can confirm that the dev branch shows much less Pokemon than the master branch. Dev showed 6 Pokemon in my sub, while the master showed over 30.

**Comment by AHAAAAAAA** [comment]
step size too large. lowering it to match the master.
