### ISSUE TITLE
Unable to load the pokemon icons / refresh

### ISSUE THREAD

**Issue by mrgeneral** [AHAAAAAAA/PokemonGo-Map#597]
### Environment info
Operating System:
Debian 8
Installed version of Python:

2.7.9
### Steps to reproduce
Setup nginx proxy

Config here:

server {
    listen 80 default_server;
    listen [::]:80 default_server ipv6only=on;

    index index.html index.htm;

    server_name intmaps.net;

location / {
root /var/www;
}

location /lisboa/ {
    rewrite ^/lisboa(/.*)$ $1 break;
    proxy_pass http://127.0.0.1:2000/;
    include /etc/nginx/proxy_params;
    proxy_redirect    off;
}

location /leiria/ {
    rewrite ^/leiria(/.*)$ $1 break;
    proxy_pass http://127.0.0.1:2001/;
    include /etc/nginx/proxy_params;
    proxy_redirect    off;
}

location /marinhagrande {
    rewrite ^/marinhagrande(/.*)$ $1 break;
    proxy_pass http://127.0.0.1:2002/;
    include /etc/nginx/proxy_params;
    proxy_redirect    off;
}

}

---

Folks, trying to setup an nginx proxy. It worked using the master branch, it won't load the pokemon icons nor refresh using the develop version.

Any idea?

**Comment by mariuskvarner** [comment]
Same problem. 

On master branch it works both locally and behind areverse proxy. 
On developement it works locally, but not behind a reverse proxy.

**Comment by mrgeneral** [comment]
Correct, @mariuskvarner, it runs just great on the master branch, but won't display it accordingly in development.

**Comment by mrgeneral** [comment]
This has been fixed with the fix #602
