### ISSUE TITLE
Error on line 133

### ISSUE THREAD

**Issue by MeesMaas** [AHAAAAAAA/PokemonGo-Map#6]
I get the following error message. no Idea what happened

```
  File "example.py", line 133
    except Exception, e:
                    ^
SyntaxError: invalid syntax
```

**Comment by Idhanta** [comment]
See FAQ here: https://m.reddit.com/r/pokemongodev/comments/4t80df/wip_pokemon_go_map_visualization_google_maps_view/d5feu2f

**Comment by sykhro** [comment]
You need Python 2.7
