### ISSUE TITLE
Display lured pokestops

### ISSUE THREAD

**Issue by AHAAAAAAA** [AHAAAAAAA/PokemonGo-Map#60]
It would interesting if we can display which Pokestops are currently lured.

**Comment by Djimusic** [comment]
I have been looking into the code for this. I believe it should be possible.
Still unable to get the names though :(

**Comment by Djimusic** [comment]
Do you have a list of all of the Fort Variables?
 message PokemonFortProto {
    string FortId = 1;
    int64 LastModifiedMs = 2;
    double Latitude = 3;
    double Longitude = 4;
    int32 Team = 5;
    int32 GuardPokemonId = 6;
    int32 GuardPokemonLevel = 7;
    bool Enabled = 8;
    // ENUM.Holoholo.Rpc.FortType FortType = 9;
    int64 GymPoints = 10;
    bool IsInBattle = 11;
    //unknown ActiveFortModifier = 12;
    Holoholo.Rpc.MapPokemonProto ActivePokemon = 13;
    int64 CooldownCompleteMs = 14;
    // ENUM.Holoholo.Rpc.Sponsor.Types.FortSponsor.Sponsor Sponsor = 15;
    // ENUM.Holoholo.Rpc.RenderingType.Types.FortRenderingType.RenderingType RenderingType = 16;
 }

I found that, but it does not have anything like names?
Could ActiveFortModifier be Lures?

**Comment by DerScreever** [comment]
message FortData {
  string id = 1;
  int64 last_modified_timestamp_ms = 2;
  double latitude = 3;
  double longitude = 4;
  bool enabled = 8;
  POGOProtos.Map.Fort.FortType type = 9;

  //// Fields related to gyms only

  // Team that owns the gym
  POGOProtos.Enums.TeamColor owned_by_team = 5;

  // Highest CP Pokemon at the gym
  POGOProtos.Enums.PokemonType guard_pokemon_type = 6;
  int32 guard_pokemon_level = 7;

  // Prestigate / experience of the gym
  int64 gym_points = 10;

  // Whether someone is battling at the gym currently
  bool is_in_battle = 11;

  //// Fields related to pokestops only

  // Timestamp when the pokestop can be activated again to get items / xp
  int64 cooldown_complete_timestamp_ms = 14;

  POGOProtos.Map.Fort.FortSponsor sponsor = 15;
  POGOProtos.Map.Fort.FortRenderingType rendering_type = 16;

  // Might represent the type of item applied to the pokestop, right now only lures can be applied
  bytes active_fort_modifier = 12;
  POGOProtos.Map.Fort.FortLureInfo lure_info = 13;
}

and 

message FortLureInfo {
  string fort_id = 1;
  double unknown2 = 2;
  POGOProtos.Enums.PokemonType active_pokemon_type = 3;
  int64 lure_expires_timestamp_ms = 4;
}

**Comment by alvinycheung** [comment]
This is great and it's the reason why I stumbled upon this repo. I'm not a python dev (I specialize in js) but will try to do this until this issue is closed.

**Comment by JZ6** [comment]
complete
