### ISSUE TITLE
This page didn't load Google Maps correctly. See the JavaScript console for technical details.

### ISSUE THREAD

**Issue by Arderos** [AHAAAAAAA/PokemonGo-Map#604]
On the latest master branch the following error appears a couple of seconds after opening the url:

This page didn't load Google Maps correctly. See the JavaScript console for technical details.

### Environment info
Operating System:
Debian 8 amd64
Installed version of Python:
2.7.9

### Steps to reproduce
1. Follow the installation process described in wiki
2. Launch the program: sudo python example.py -a google -u <username> -p <password> -l "Kitay-Gorod" --st 8 -H 0.0.0.0 -P 80 -ar 10 -dp -ol -i 19,16,13
3. Open the url

**Comment by DanielVolz** [comment]
>1. Follow the installation process described in wiki
Are you being honest here?! ;)

https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Google-Maps-API:-a-brief-guide-to-your-own-key

use "-k GMAPIKEY"

**Comment by Arderos** [comment]
Sorry, my bad.
Maybe a link in the installation guide (https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Installation-and-requirements) would be a good idea?
