### ISSUE TITLE
I am having trouble logging in. 

### ISSUE THREAD

**Issue by jagalbraith** [AHAAAAAAA/PokemonGo-Map#605]
me@mycomputer:~/coding/python/pkmgo/PokemonGo-Map$ **./example.py -u my_google_accout@gmail.com  -l City -st 10000000**
_```
[-] register_background_thread called
[-] register_background_thread: not running inside Flask so not starting thread
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
[-] register_background_thread called
[-] register_background_thread: initial registration
[+] Locale is en
 * Debugger is active!
[+] Getting initial location
 * Debugger pin code: 298-358-377
[!] Your given location: City, State
[!] lat/long/alt: 0000 -0000
Password: 
[!] PTC login for: my_google)account@gmail.com
As a security measure, your account has been disabled for 15 minutes because you have failed to log in correctly too many times. Please come back and try again in 15 minutes.
Exception in thread search_thread:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./example.py", line 581, in main
    api_endpoint, access_token, profile_response = login(args)
  File "./example.py", line 92, in memoizer
    cache[key] = obj(*args, **kwargs)
  File "./example.py", line 516, in login
    raise Exception('[-] Wrong username/password')
Exception: [-] Wrong username/password_
```


**What am I supposed to be using for the PTC login?**

**Comment by docrockulus** [comment]
First off, that's WAY too many steps. 

Your ptc login is your Pokemon Traiding Club account, or switch to "-a google" to use google auth.

**Comment by MonkeyLeeT** [comment]
PTC account and password.
"-u username -p password"

To use google you need to specify so via "-a google'.

And yes, too many steps, make it less than 15 for reasonable scanning.

**Comment by jagalbraith** [comment]
Awesome, Thank you!!

-- 
John Galbraith
Information Security Analyst
Cell: 727-[[[RECIPIENT NOT IN ADDRESS BOOK]]]
Blog: https://tech55i.com
