### ISSUE TITLE
Exception: [-] Wrong username/password 

### ISSUE THREAD

**Issue by MattChristiansen** [AHAAAAAAA/PokemonGo-Map#607]
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discord.gg/Kzp4yky).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System: OS X 10.11.6

Installed version of Python: 

### Steps to reproduce
1. python example.py -a google -u your@gmail.here -p passwordhere -l "777 Yamato Road, Boca Raton, FL" -st 5 -dp -ar 2 
2. python example.py -a google -u username -p passwordhere -l "777 Yamato Road, Boca Raton, FL" -st 5 -dp -ar 2
3.

### What have you tried?
1. See above 

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

[-] register_background_thread called
[-] register_background_thread: not running inside Flask so not starting thread
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
[-] register_background_thread called
[-] register_background_thread: initial registration
[+] Locale is en
 * Debugger is active!
[+] Getting initial location
 * Debugger pin code: 249-441-589
[!] Your given location: 777 Yamato Rd, Boca Raton, FL 33431, USA
[!] lat/long/alt: 26.3949117 -80.1004768 0.0
[!] Google login for: imthedeadhomie@g
Exception in thread search_thread:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "example.py", line 581, in main
    api_endpoint, access_token, profile_response = login(args)
  File "example.py", line 92, in memoizer
    cache[key] = obj(*args, **kwargs)
  File "example.py", line 516, in login
    raise Exception('[-] Wrong username/password')
Exception: [-] Wrong username/password

I am using my personal gmail credentials that I use to log into the game. Any idea what I may be doing wrong?

**Comment by imthe666st** [comment]
Do you have 2 factor authentication activated?  
Got the same error until I disabled that.

**Comment by MattChristiansen** [comment]
I will double check. I don't believe so. I am using my personal account and I do not think I set up 2FA. I will let you know the outcome. Thank you.

**Comment by ryan-shaw** [comment]
Don't disable 2 step. Use app passwords

**Comment by MattChristiansen** [comment]
2 Step is off and my account isn't eligible for app passwords?

**Comment by MattChristiansen** [comment]
I am running it in virtualenv. Did it with someone else who has it working this way and theres works fine. So I am very puzzled. Yes, I tested my creds as well. Logged into my email account and logged into the app.

**Comment by FrostTheFox** [comment]
I wouldn't be using your actual account to login here. I'm not too familiar with Google login method, so sorry I can't more helpful here.

**Comment by MattChristiansen** [comment]
Maybe I shouldn't run in a virtualenv? Can someone point me in the right direction? Otherwise I have no IDEA what could be wrong.

**Comment by DerScreever** [comment]
master branch support dropped.
