### ISSUE TITLE
Viewing on iPhone for a noob

### ISSUE THREAD

**Issue by heron94** [AHAAAAAAA/PokemonGo-Map#608]
Can anyone give me a step by step guide on how to get this working on my iPhone for when I'm out and about please?

**Comment by rohangro** [comment]
@Nulifyer posted this handy guide on a similar earlier thread:

> 1. run the command with -H 0.0.0.0 -P 5000 
> 2. portforwared your router so connections to port 5000 go to the pc running the script
> 3. gotten a new api key from google maps
> 4. there are no unexpsected errors
> 
> note: if you are on the same wifi you will not know if it work until you are not. turning off wifi on your phone and trying to connect via : 
> "make sure that you type in http://[ip of router]:5000 in the url bar
> get router ip here http://www.ipchicken.com/
> this api does not support https which has ssl and other stuff"
> should tell you if it works.

I personally prefer to use [ngrok](ngrok.com) or [Pagekite](pagekite.net), both of which are easy to install and get running, but if you don't want to download any new software the above method is pretty simple too.

**Comment by heron94** [comment]
@rohangro Cheers for that.. But like I say I'm a total noob to all of this. How do I get ngrok running and what does it do?

**Comment by heron94** [comment]
@rohangro Also, where do I place the -H 0.0.0.0. etc?

**Comment by mkody** [comment]
You need to use your own computer or a server to host this software. The `-H 0.0.0.0` is added to the command to launch the python script.

**Comment by rohangro** [comment]
To get ngrok running, download the appropriate version from [https://ngrok.com/download](https://ngrok.com/download), then unzip it. In terminal/command prompt go to the folder you downloaded it to (probably downloads) and type `./ngrok http 5000` then navigate to the ngrok.io link it spits out. 

Like mkody said, if you're using the 4-step method above, just add the `-H 0.0.0.0` to the end of the command you used to launch the map.
