### ISSUE TITLE
Countdown timers in infobox indicating when pokemon will disappear

### ISSUE THREAD

**Issue by AHAAAAAAA** [AHAAAAAAA/PokemonGo-Map#61]
Currently we show despawn time statically based on when we load it, would be cool if we could have a countdown timer instead. Additionally, it would be great if we removed the marker when they do despawn

**Comment by Djimusic** [comment]
I will take this on via javascript if that seems like the best idea!

**Comment by sykhro** [comment]
Frontend team will take care of this

**Comment by DerScreever** [comment]
Same as #31

**Comment by sykhro** [comment]
Will close #31 just to not bother pinging assignees again. It wasn't a bug anyway, just not implemented

**Comment by nborrmann** [comment]
Instead of updating the countdown timer, i changed the message to display the exact time at which the pokemon will despawn in PR #88. Imo this is much easier but just as good.

**Comment by haagiboy88** [comment]
At the moment I agree nborrmann. But when we are able to properly despawn the icons at the correct time we should go back to "despawns in x time".

**Comment by DerScreever** [comment]
Nah wont go back to this. take the soulution from @nborrmann for the UI the user see.
But internal use the "despawns in x time" and then update the map.
But i think it is easiert to read that the pokemon despawn at "14:30:02".

**Comment by ortschun** [comment]
Countdown timer was there, but some recent commit seems to have that removed?

**Comment by JZ6** [comment]
complete
