### ISSUE TITLE
Unable see any pokemon.. 

### ISSUE THREAD

**Issue by abhishek246** [AHAAAAAAA/PokemonGo-Map#610]
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discord.gg/Kzp4yky).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:

Installed version of Python:

### Steps to reproduce
1.
2.
3.

### What have you tried?
1.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by FrostTheFox** [comment]
It would be nice to actually provide some information.  We don't even know what OS you're running!

**Comment by mcmaxl** [comment]
same here. running server on ubuntu, browser shows blank page with menu to the left and no map. browser is safari on mac os x

**Comment by FrostTheFox** [comment]
@mcmaxl What command are you starting with?

**Comment by Wickrman** [comment]
The most important of all , is in your command line the program example.py actively searching pokemon ? 

If so, refresh your page!

**Comment by mcmaxl** [comment]
`root@BlackBox:/# python /opt/pokemongo-dev/runserver.py -u ***** -p ***** -l "*****" -st 10 -H 0.0.0.0 -P 5010 -L de -ar 5
`

**Comment by FrostTheFox** [comment]
@mcmaxl Alrighty, you said yours came up after 3 minutes? Your command looks fine to me. @abhishek246 What command are you running?

**Comment by mcmaxl** [comment]
yeah strange. Auto refresh doesn't seem to be working anyway

**Comment by FrostTheFox** [comment]
@mcmaxl There's a lot going on in the background, so the public code isn't the best at the moment. It's being worked on.

**Comment by mcmaxl** [comment]
figured :). Amazing work!

**Comment by chuparCh0pper** [comment]
So does it work now? Can the issue be closed? What did you do to fix the problem?
