### ISSUE TITLE
Running the script remotely or on external server

### ISSUE THREAD

**Issue by mtrang** [AHAAAAAAA/PokemonGo-Map#614]
Any suggestions on how to run this on an external server? My biggest concern is Niantic banning IP addresses. I use a different account to run the script and use a public wifi network. But ideally, I rather just have the script running on an external server/seedbox.

Thank you for all the hard work!!

**Comment by frdmn** [comment]
Setup an VPS on DigitalOcean or AWS :)

**Comment by wohfab** [comment]
DigitalOcean ist really awesome. Also you get 10USD codes from Linux Action Show like every time (`heresthething` for new users only - but this would fit your needs)

**Comment by frdmn** [comment]
And Amazon is offering 1 year of a small free tier for a lot of AWS products for any new customers. Also worth a look, I run mine on the tiny EC2 instance and it works great!

**Comment by IDSninja** [comment]
Running on a debian box in the digital ocean right now!
```
#!/bin/bash
sudo apt-get install gcc git
sudo easy_install pip
git clone https://github.com/AHAAAAAAA/PokemonGo-Map
cd PokemonGo-Map
sudo pip install -r requirements.txt
```

**Comment by mtrang** [comment]
IDNinja, you the man. I wasted an hour trying it on my own, but doing it your way I got it up and running in 5 mins on DigitalOcean. Thanks!

**Comment by IDSninja** [comment]
No problem! Happy to help
