### ISSUE TITLE
Runs locally, not in Heroku app

### ISSUE THREAD

**Issue by Wickrman** [AHAAAAAAA/PokemonGo-Map#615]
Hi guys

i've managed to run it locally and can view on 127.0.0.1:5000 and it's amazing how good it works. 
yet we're not there yet. 

I need to be able to access this map on my phone , live. 

I made a friend try : http://routerip:5000. he gets an error. 

neither can i get my app working in heroku. Although my proc file has the same parameters as i use in the command line : 

web: python example.py -a ptc -u w*****n -p F************1 -l "9830, Sint-martens-latem, lauwstraat 80 " -st 20 -p 5000 -host 0.0.0.0

yet when i try to load it shows application error. 

Logs show me this : 

2016-07-20T18:26:03.886965+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=pokefinder3.herokuapp.com request_id=34882a7c-2a5c-487c-be22-f2f20d21c413 fwd="80.200.86.***" dyno= connect= service= status=503 bytes=

What could be the problem here? Locally it works, throwing it into a heroku app does not work. 

i'm guessing it's something with the forwarding ? My mate can't get through my router's firewall or something?

**Comment by docrockulus** [comment]
You need to forward a port to port 5000 on your machine where you are running the map, then connect to externalip:forwarded port.

**Comment by lparkermg** [comment]
So for when you run it locally, you'll probably need port forwarding etc, on your router. Not to sure about the heroku one though.

**Comment by frdmn** [comment]
@lparkermg @docrockulus that's not his problem right now. The app is crashing and cant even be available with properly set port forwards.

@Wickrman Can you check if you have `python` in `$PATH`? Any other method to see more stdout logs from Heroku?

**Comment by Wickrman** [comment]
Have to go right now, i'll get back on this post later on , i'll check these things soon

**Comment by frdmn** [comment]
@Wickrman Also check this project, apparently it has working example `Procfiles` for a Flask application: https://github.com/mjhea0/flask-boilerplate

**Comment by OstrichProjects** [comment]
Read through [Miguel Grinberg's Heroku write up in his flask tutorial](http://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-xviii-deployment-on-the-heroku-cloud).  It should give you more insight into how to set it up.

On top of that, it would probably be good to add a "Deploy to Heroku" button in the readme so people can set up servers without having to install Heroku on their machines.  [Slack-Pokemon](https://github.com/rvinluan/slack-pokemon) is a good example of this.  All of the input parameters can be saved as environment variables.
