### ISSUE TITLE
Specific to develop branch

### ISSUE THREAD

**Issue by Galtwise** [AHAAAAAAA/PokemonGo-Map#616]
My timezone is set to UTC -6, all pokemon that spawn on the develop branch map show as already expired 6 hours ago. Changing my timezone to UTC did not fix this

Any ideas?

**Comment by lparkermg** [comment]
I'm getting a somewhat similar issue with old expired pokemon not expiring. My guess is the expired ones are not getting removed from the database used.

**Comment by wcastello** [comment]
#578

**Comment by craigbaines** [comment]
also have expired pokemon stuck, any fix?

**Comment by SeeingBlue** [comment]
I am having the exact same issue on dev build.

**Comment by invisiblek** [comment]
https://github.com/AHAAAAAAA/PokemonGo-Map/pull/576
