### ISSUE TITLE
Question about mapping

### ISSUE THREAD

**Issue by Zach1993** [AHAAAAAAA/PokemonGo-Map#618]
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discord.gg/Kzp4yky).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:
OSX 10.11
Installed version of Python:
2.7.10

### Steps to reproduce
1. zacharys-MacBook-Pro:PokemonGo-Map-master ZachLee$ python example.py -a google -u z***@gmail.com -p ******* -l "******, Gilbert, AZ" -st 5 
2.
3.

### What have you tried?
1. running on terminal, however I dont know how to open it up on a map, it just loops in terminal.
I am running the example.py version, not the dev version. Can someone explain to me how to open it in a server so I can see the items on a map? I have limited experience with this sort of thing. Thankyou so much!

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by FrostTheFox** [comment]
The master branch is no longer supported. Download from develop branch instead.

**Comment by k0mat** [comment]
go to localhost:5000 in your browser

**Comment by Zach1993** [comment]
@FrostTheFox @k0mat I am encountering a problem with the develop branch where It is giving me an error where it will say "Unexpected HTTP server response - needs 200 got 502" or "Map download fail" And it doesn't seem to be auto updating the map I have open...

**Comment by FrostTheFox** [comment]
@Zach1993 That's because the servers are having issues right now.

**Comment by Zach1993** [comment]
@FrostTheFox Thanks, just wanted to make sure it wasn't something I was doing wrong.
