### ISSUE TITLE
How to run on Windows?

### ISSUE THREAD

**Issue by varunrramani** [AHAAAAAAA/PokemonGo-Map#619]
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discord.gg/Kzp4yky).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System: Windows

Installed version of Python: 2.7.12

### Steps to reproduce
1.
2.
3.

### What have you tried?
1. C:\PokemonGo-Map>runserver.py -h -a google -u ********* -p ********* -l  MyLocation -st 5
AND
 C:\PokemonGo-Map>python runserver.py -h -a google -u ********* -p ********* -l  MyLocation -st 5

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

It only shows the following in the cmd
usage: runserver.py [-h] [-a AUTH_SERVICE] -u USERNAME [-p PASSWORD] -l
                    LOCATION -st STEP_LIMIT [-i IGNORE | -o ONLY]
                    [-ar AUTO_REFRESH] [-dp] [-dl] [-dg] [-H HOST] [-P PORT]
                    [-L LOCALE] [-c] [-d] [-m] [-k GMAPS_KEY]

optional arguments:
  -h, --help            show this help message and exit
  -a AUTH_SERVICE, --auth-service AUTH_SERVICE
                        Auth Service
  -u USERNAME, --username USERNAME
                        Username
  -p PASSWORD, --password PASSWORD
                        Password
  -l LOCATION, --location LOCATION
                        Location, can be an address or coordinates
  -st STEP_LIMIT, --step-limit STEP_LIMIT
                        Steps
  -i IGNORE, --ignore IGNORE
                        Comma-separated list of Pok├⌐mon names or IDs to
                        ignore
  -o ONLY, --only ONLY  Comma-separated list of Pok├⌐mon names or IDs to
                        search
  -ar AUTO_REFRESH, --auto-refresh AUTO_REFRESH
                        Enables an autorefresh that behaves the same as a page
                        reload. Needs an integer value for the amount of
                        seconds
  -dp, --display-pokestops
                        Display pok├⌐stops
  -dl, --display-lured  Display only lured pok├⌐stop
  -dg, --display-gyms   Display gyms
  -H HOST, --host HOST  Set web server listening host
  -P PORT, --port PORT  Set web server listening port
  -L LOCALE, --locale LOCALE
                        Locale for Pokemon names: default en, checklocale
                        folder for more options
  -c, --china           Coordinates transformer for China
  -d, --debug           Debug Mode
  -m, --mock            Mock mode. Starts the web server but not the
                        background thread.
  -k GMAPS_KEY, --google-maps-key GMAPS_KEY
                        Google Maps Javascript API Key

Also I am on development branch

**Comment by DanielVolz** [comment]
Maybe try it without -h ?

**Comment by k0mat** [comment]
that because you are using the -h switch. remove it and try again

**Comment by ZeldoKavira** [comment]
It's not because you are using the switch, but because you are using it without an argument. You can either remove -h or complete it (to listen on all addresses you would do -h 0.0.0.0)

**Comment by k0mat** [comment]
@ZeldoKavira -h switch shows help and then exits, -H switch changes the ip of host

**Comment by ZeldoKavira** [comment]
Ah yes, sorry my bad. A note that there are two -h in your command as well, they will both need to be removed.
