### ISSUE TITLE
Asynchronous requests during scan. 

### ISSUE THREAD

**Issue by AHAAAAAAA** [AHAAAAAAA/PokemonGo-Map#62]
Having separate threads ping the servers for a certain location simultaneously could drastically improve our load times. Might require quite a rewrite of some function.

**Comment by KonstantinKuklin** [comment]
We need to study the behavior of the ordinary game client, if he does not send asynchronous requests - this may be a problem and become a reason for the ban.

**Comment by AHAAAAAAA** [comment]
Agree, we should investigate!

**Comment by Hextar** [comment]
What about using two or n accounts? Wouldn't that reduce the load time, and reduce the call from a single account?

The only strange thing would be 3 or more account pinging from the same IP, but hey could be thetering

**Comment by Nulifyer** [comment]
using multiple accounts could work and you guys could run two through a proxy or something to make them from seperate ip's

**Comment by JZ6** [comment]
complete
