### ISSUE TITLE
Error in importing packages.urllib3.exception

### ISSUE THREAD

**Issue by samdunsavy** [AHAAAAAAA/PokemonGo-Map#623]
Operating System: Ubuntu 14.04.4 LTS

I am trying to run example.py but it seems that it's unable to import 

File "/home/rock/PokemonGo-Map/example.py", line 28, in <module>
    from requests.packages.urllib3.exceptions import InsecureRequestWarning
ImportError: No module named packages.urllib3.exceptions

**Comment by mkody** [comment]
As stated in the README
> Support for master branch dropped.

Also, can you check that the dependencies are up to date and that you're using `pip2`?

**Comment by samdunsavy** [comment]
I cloned the develop branch and now I am getting the same problem in runserver.py earlier I was using pip but this time I used pip2  as `sudo pip2 install -r /home/rock/PokemonGo-Map/requirements.txt`
And got this `sudo pip2 install -r /home/rock/PokemonGo-Map/requirements.txt`

**Comment by IDSninja** [comment]
did you try 
```
sudo pip install requests
```

**Comment by mkody** [comment]
Can't you try without `sudo`?
I don't know why you're all using this sudo with this.

**Comment by IDSninja** [comment]
You don't need sudo if you are running as root, but you do need be root for da pip in standard systems

**Comment by samdunsavy** [comment]
Perfect.. easy_install worked.. Thanks a lot!
