### ISSUE TITLE
[Read!!] Lets be smart

### ISSUE THREAD

**Issue by lucasfeliciano** [AHAAAAAAA/PokemonGo-Map#624]
First of all, cheers to all of the contributors!!

At some point Niantic will patch their servers and make this unavailable.

The most important thing that we can get from this project is DATA.

I'm starting to log everything data that I get around my city, so I can analyse this data 

If we analyse this data we can figure the patterns of the respawns,  where the pokemons usually appears and how often they appear and so on.

We can discover a lot with it. We can make some data visualisation on top of that.

In a couple of days i'll create a repo with a program that gather this information, if we can populate one unique database it will be awesome.

**Comment by blaskovic** [comment]
If you run this app, you can then just do something like:

```
curl 'localhost:port' | grep 'pokemon-pattern' && script_to_log_to_db
```

So it should not be something hard to do. If you have something ready, post it here. Otherwise I can do something similar.
