### ISSUE TITLE
Map stops updating after some time

### ISSUE THREAD

**Issue by brownsnake** [AHAAAAAAA/PokemonGo-Map#625]
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discord.gg/Kzp4yky).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System: Ubuntu 14.04 LTS

Installed version of Python: 2.7.9

### Steps to reproduce
1. Leave the app running for over 1 hour

### What have you tried?
1.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

No logs to attach. If I let the app run for about 1.5 hours, all of the pokemon disappear, none of the new spawns appear. I have to kill the process and restart to get the new spawns on map.

**Comment by rezz3x** [comment]
It doesn't load new Pokemons for me too, got it running for like a Hour.
I got the develop Branch setup.

**Comment by ElGovanni** [comment]
I had this same bug.

**Comment by SeeingBlue** [comment]
Dev build is having issues loading pokemon for a lot of people.
Master build gave me this issue too. It's like auto updating stops working after awhile.

**Comment by frdmn** [comment]
Can you guys check your web console when that error occurs?

**Comment by ElGovanni** [comment]
@frmdn I got nothing in console, It just stop :/

**Comment by dorian-marchal** [comment]
Nothing in the console neither.
And I feel like it doesn't update anymore, even after restarting the server.

**Comment by HanYangZhao** [comment]
same, nothing special show on console . wasn't #465 suppose to fix this?

**Comment by ElGovanni** [comment]
@dorian-marchal @HanYangZhao Hey guys wich of extra parametrs do you use?
I'm using `-ar 30 -dp -ol`

**Comment by noaqzz** [comment]
servers are down - new update

**Comment by dorian-marchal** [comment]
@ElGovanni 
```
python runserver.py -a google -u XXX -p XXX -l XXX -st 5 -ar 10
```

**Comment by ElGovanni** [comment]
@dorian-marchal maybe -ar is a problem?

**Comment by rezz3x** [comment]
I didn't had -ar on, and i didn't worked as well.

**Comment by Sejadis** [comment]
cant find it anymore but i think on another issue the problem was identified as the token expiring after some time 
 so about every 30 mins a new token has to be requested from the server

**Comment by crckdns** [comment]
same problem as in master branch :)

**Comment by Heavywavez** [comment]
if this still bug? this happening to me since yesterday.

**Comment by IMNoob1** [comment]
Yes it skill a known bug, in my pov its probably related to the google api requests.

**Comment by Nulifyer** [comment]
If running with batch file couldn't we stop the program after 30 min and restart Untill devs fix this re authentication

**Comment by brownsnake** [comment]
Actually, this is exactly what I did. In a while loop, I did timeout -s 9 1800 before the Python.
On Jul 20, 2016 6:16 PM, Nulifyer <notifications@github.com> wrote:If running with batch file couldn't we stop the program after 30 min and restart Untill devs fix this re authentication

**Comment by Josephvb10** [comment]
@brownsnake Can you share the full script?

**Comment by brownsnake** [comment]
Will do once I get back to my computer. Be warned, it only works for sure on Ubuntu. Probably debian, as well, definitely not Windows
On Jul 20, 2016 6:23 PM, Josephvb10 <notifications@github.com> wrote:@brownsnake Can you share the full script?

**Comment by Nulifyer** [comment]
So it's in bash ? That's not difficult to change alot of it is the same

**Comment by brownsnake** [comment]
It's bash, but it uses the timeout utility in the Ubuntu coreutils package.
On Jul 20, 2016 6:33 PM, Nulifyer <notifications@github.com> wrote:So it's in bash ? That's not difficult to change alot of it is the same

**Comment by Nulifyer** [comment]
Probably some batch equivalent way to do that

**Comment by ddiesenreither** [comment]
@brownsnake how can i timeout it and restart again on Linux? i startet it with the & at the end to create a process but it stops after token expires.

**Comment by vDrag0n** [comment]
Ok, so Grabbing a new token before the script restarts its step, has kept the map updated.

On the depreciated master branch, you can do so by removing @memoize for the login and calling the login process again at the end of main.

**Comment by brownsnake** [comment]
For those interested, here is the script I use to kill/restart the server after half an hour:

`while :; do timeout -s 9 1800 python example.py -a google -u USER -p PASS -l "123 Fake Street, New York, New York" -st 10 -H 0.0.0.0 -P 8080 -dp -dg; done`

As I said in my email before, this is only tested with Ubuntu Linux. I'm not sure of other distributions' support of the `timeout` command.

**Comment by ddiesenreither** [comment]
thanks, i just cloned the new master repo where the fix is in included.

**Comment by Josephvb10** [comment]
But this still shouldn't be closed lol 
The bug is still present

**Comment by MikeDX** [comment]
This should be closed as master is now deprecated whilst the develop branch is being built. The new builds in develop do not have this issue!

**Comment by Josephvb10** [comment]
According to #733 the issue is still present.

**Comment by MikeDX** [comment]
Interesting

my server has been running for over an hour, I'll see if i can reproduce this bug and fix it if possible

**Comment by Mikeboyslim** [comment]
@vDrag0n Removing @memorize in example.py worked perfectly. I have been running the script for 1 hour now with no issues. Thanks mate.

**Comment by Josephvb10** [comment]
@Mikeboyslim Yup, for me too.  Did you also called login at the end? Because I did that, but could be unnecessary.

**Comment by actondong** [comment]
@Josephvb10 I also feel like call login again at end of main doesn't make much sense. 
When I first see this issue, I feel like it is due to game taken expiration. So remove memorize does make sense in this case. Let me test it today and see (BTW I am working on deprecated master branch
