### ISSUE TITLE
DevBranch: gyms dont show, no expiration cd on pokemon, no flushing cache from db, expiration in wrong tz

### ISSUE THREAD

**Issue by IronChroni** [AHAAAAAAA/PokemonGo-Map#626]
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discord.gg/Kzp4yky).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:
CE6.8
Installed version of Python:
2.7.9

### Steps to reproduce
1. Launch runserver.py with -dg full develop clone
2. Hover over any pokemon no expiration count down
3. Wait a significant time and see them never drop off the map.
4. Be anywhere other than west coast

### What have you tried?
1. Nuking pogom.db does allow for new data to be collected, but I can only assume it will be stale shortly.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).
Logs for gyms show proper:
2016-07-20 15:01:02,471 [     models] [   INFO] Upserting 4 gyms
2016-07-20 15:01:02,511 [     search] [   INFO] Completed 89.00% of scan.
2016-07-20 15:01:03,512 [     search] [   INFO] Scanning step 90 of 100.

So this appears to be a display issue.

**Comment by rezz3x** [comment]
Gym's aren't implemented yet, however a PR is out with the Features, #576

**Comment by IronChroni** [comment]
Support for master branch dropped.

**Comment by rezz3x** [comment]
He is using the develop Branch like, the master doesn't have the pogom.db
