### ISSUE TITLE
Pokemon go cordinates error

### ISSUE THREAD

**Issue by Trojqn** [AHAAAAAAA/PokemonGo-Map#629]
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discord.gg/Kzp4yky).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System: Windows 8.1 

Installed version of Python:
2.7.12

### Steps to reproduce
1.
2.
3.

### What have you tried?
1.Tried messing with the coordinates works with cities that are far away from me, not on my own city

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).
gives me a error : example.py: error: unrecognized arguments: then my attitude is listed

**Comment by rezz3x** [comment]
how did you start the process? give us the args

**Comment by Trojqn** [comment]
C:\Python27\python example.py -a ptc -u (my username) -p (password) -l (coordinates with quotes and no comma just a space) -st 10

**Comment by rezz3x** [comment]
Don't use the master Branch, use the develop one.

**Comment by Trojqn** [comment]
The master branch? Can you explain, I don't understand what you are saying and could you give me a link to the develop one?

**Comment by rezz3x** [comment]
https://github.com/AHAAAAAAA/PokemonGo-Map/tree/develop
