### ISSUE TITLE
ImportError: No Module Named Flask

### ISSUE THREAD

**Issue by WillRust303** [AHAAAAAAA/PokemonGo-Map#630]
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discord.gg/Kzp4yky).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System: Windows 7

Installed version of Python:
Python 3

### Steps to reproduce
1. runserver.py -h -a google -u ******* -p ****** -st 5
2.
3.

### What have you tried?
1.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by sanderploegsma** [comment]
Have you tried running it as `python runserver.py ...`?

**Comment by WillRust303** [comment]
gets a little further that time: No module named 'peewee'

**Comment by jabelone** [comment]
So install peewee... ("pip install peewee")

**Comment by sanderploegsma** [comment]
I guess that comes down to the fact that the requirements in the master and develop branch are not the same. So if you installed the requirements on the master branch, you need to run `pip install -r requirements.txt` from the develop branch again.

**Comment by DerScreever** [comment]
also install python 2.7
