### ISSUE TITLE
When opened browser after about 5 sec, error occured.

### ISSUE THREAD

**Issue by alawing** [AHAAAAAAA/PokemonGo-Map#632]
Oops! Something went wrong.
This page didn't load Google Maps correctly. See the JavaScript console for technical details.

**Comment by k0mat** [comment]
You probably haven't provided the correct google maps api key. go here for instructions how to do it https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Google-Maps-API:-a-brief-guide-to-your-own-key

**Comment by mkody** [comment]
Also, your probably using the `master` branch, which is unsupported for now. (If the key was missing, you couldn't actually start the server)
