### ISSUE TITLE
My webconsole says after finding pokemon, map disappears "SyntaxError: missing } after property list http://localhost:5000/ Line 51"

### ISSUE THREAD

**Issue by sasha00123** [AHAAAAAAA/PokemonGo-Map#639]
### Environment info
Operating System:
KALI linux 2.0
Installed version of Python:
2.7

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).
web:
SyntaxError: missing } after property list
http://localhost:5000/
Line 51
in terminal:(earlier it wasn't)
[-] retrying_api_req: request error (Unexpected end-group tag.), retrying

**Comment by Chiggins** [comment]
The `[-] retrying_api_req: request error (Unexpected end-group tag.), retrying` message means that the servers are currently down. Give it a go later.

**Comment by sasha00123** [comment]
but earlier this message didn't exist and in web concole was SyntaxError: missing } after property list
http://localhost:5000/
Line 51 
after terminal said it found a pokemon
