### ISSUE TITLE
Generate test data for server requests

### ISSUE THREAD

**Issue by AHAAAAAAA** [AHAAAAAAA/PokemonGo-Map#64]
Niantic's servers go down often, and it would be useful if we had a way to test this locally without pinging their servers. Perhaps setting up a dummy server or just a test mode.

**Comment by kutyel** [comment]
What about [this](https://github.com/sotojuan/is-pokemon-go-up-cli)?

**Comment by DerScreever** [comment]
does not help.

**Comment by DerScreever** [comment]
Im sorry, but we dropped the support for the master branch (example.py). 
This branch is deprecated.  
The new branch contains a much cleaner structure so pls report only issues related to the develop branch. 

Your development team
