### ISSUE TITLE
can't open file 'example.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by Smilhjan** [AHAAAAAAA/PokemonGo-Map#641]
Operating System: OSX 10.11.6 Beta (15G26a)

Installed version of Python: 2.7.11

### Steps to reproduce
1.  mac:PokemonGo-Map-develop Kai$ python example.py -a ptc -u *** -p *** -l "***" -st 5 -L de -i 13,16,19,21 -ar 30

### What have you tried?
1.  nothing. with current master branch its working, but not with developer branch

### Logs or other output that would be helpful
/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'example.py': [Errno 2] No such file or directory

**Comment by FrostTheFox** [comment]
Because developer doesn't use example.py. It uses runserver.py.

**Comment by Smilhjan** [comment]
that explains a lot!   it's too late for me, should go to bed, cab't even read filenames in folders.
thx
