### ISSUE TITLE
i dont know what to do

### ISSUE THREAD

**Issue by thebtrainerblue** [AHAAAAAAA/PokemonGo-Map#643]
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discord.gg/Kzp4yky).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System: what do i do. i downloaded the zip file but i dont know hwat to do next.

Installed version of Python:

### Steps to reproduce
1.
2.
3.

### What have you tried?
1.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by jabelone** [comment]
Read the second line of your "issue"... You will get more help there.
