### ISSUE TITLE
AttributeError: 'module' object has no attribute 'total_ordering'

### ISSUE THREAD

**Issue by mark-rodgers** [AHAAAAAAA/PokemonGo-Map#646]
### Environment info
Operating System: CentOS release 6.7 (Final)
Installed version of Python: 2.7.10
pip version: 8.1.2

### Steps to reproduce
1. python example.py -u CENSORED -p CENSORED -l "CENSORED" -st 10

### What have you tried?
1. reinstall python from source
2. reinstalling pip

### Logs or other output that would be helpful
`Traceback (most recent call last):
  File "example.py", line 23, in <module>
    from s2sphere import *
  File "/usr/lib/python2.6/site-packages/s2sphere/__init__.py", line 5, in <module>
    from .sphere import *
  File "/usr/lib/python2.6/site-packages/s2sphere/sphere.py", line 12, in <module>
    @functools.total_ordering
AttributeError: 'module' object has no attribute 'total_ordering'`

### Other notes
CentOS 6 comes with Python 2.6 installed, so I installed Python 2.7 from source. This is a digital ocean server.

**Comment by jabelone** [comment]
You are running it using python 2.6, try running it with python 2.7 instead.

**Comment by mark-rodgers** [comment]
cannot believe I overlooked that. Strange though I cannot seem to get it to run in Python2.7 although I KNOW 2.7 is installed.

`which python
alias python='/usr/local/bin/python2.7'`

`python --version
Python 2.7.9`

I've also modified the first line of the example.py to the following:
`#!/usr/local/bin python2.7`

Still no luck, the script is refusing to run in 2.7 for some reason.

**Comment by mark-rodgers** [comment]
Fixed, i was running a bash script to start up example.py with all the flags i wanted, for some reason "python" inside a bashscript calls python2.6 but outside of the script it calls 2.7. I updated the script to call python2.7 bin directly.
