### ISSUE TITLE
"Map Download failed. Trying again." on develop branch 

### ISSUE THREAD

**Issue by FaizSayyid** [AHAAAAAAA/PokemonGo-Map#649]
Running the new develop branch, i get these a lot of the time:

[    rpc_api] [WARNING] Unexpected HTTP server response - needs 200 got 502
[     search] [   INFO] Map Download failed. Trying again.

Is this a bug or a server side issue?

**Comment by jonathan-dejong** [comment]
Same here :) Posting to follow!

**Comment by Rebosar** [comment]
Also getting the same error. I believe it is a server issue.

**Comment by mkody** [comment]
Servers are down. [Duplicate of many other issues.](https://github.com/AHAAAAAAA/PokemonGo-Map/labels/Not%20an%20issue%3A%20servers%20are%20down)

**Comment by MonkeyLeeT** [comment]
Server down.
