### ISSUE TITLE
Incorrect email password

### ISSUE THREAD

**Issue by samdunsavy** [AHAAAAAAA/PokemonGo-Map#655]
I am trying to use this command
`sudo python /home/rock/PokemonGo-Map/runserver.py -a google -u starr******@gmail.com -p ******** -l 28.7990445,76.13351120000004 -st  30`
But all it says is login failed even when my email and password is correct

**Comment by craigbaines** [comment]
surround your email / username in " "'s maybe? aka"-u "MYUSERNAME" -p "MYPASSWORD"

**Comment by haagiboy88** [comment]
Not a development issue
