### ISSUE TITLE
retrying_api_req: request error (Unexpected end-group tag.), retrying

### ISSUE THREAD

**Issue by mark-rodgers** [AHAAAAAAA/PokemonGo-Map#656]
### Environment info
Operating System: CentOS release 6.7 (Final)
Installed version of Python: 2.7.9

### Steps to reproduce
1. run example.py

### What have you tried?
1. nada

### Logs or other output that would be helpful
[-] register_background_thread called
[-] register_background_thread: not running inside Flask so not starting thread
  Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
  Restarting with stat
[-] register_background_thread called
[-] register_background_thread: initial registration
  Debugger is active!
[+] Locale is en
[+] Getting initial location
  Debugger pin code: 261-645-244
[!] Your given location: CENSORED
[!] lat/long/alt: CENSORED CENSORED 0.0
[!] PTC login for: CENSORED
[+] RPC Session Token: TGT-1345600-qZ2XdVvhe59gX ...
[-] retrying_api_req: request error (Unexpected end-group tag.), retrying
[+] Received API endpoint: https://pgorelease.nianticlabs.com/plfe/147/rpc
[-] retrying_api_req: request error (Unexpected end-group tag.), retrying
[-] retrying_api_req: request error (Unexpected end-group tag.), retrying
[-] retrying_api_req: request error (Unexpected end-group tag.), retrying
[-] retrying_api_req: request error (Unexpected end-group tag.), retrying
[-] retrying_api_req: request error (Unexpected end-group tag.), retrying

### Other info
`[-] retrying_api_req: request error (Unexpected end-group tag.), retrying`
is repeating indefinitely. I just want to confirm this means the server is down? Unsure if it is coincidental but I'm also having troubles logging into Pokemon GO from the actual game app on Android, just sitting at the loading bar with a picture of Gyarados...

**Comment by tstokes8040** [comment]
I got that same issue as well. I think it is because the servers are down, but not sure.

**Comment by Skullmonkey** [comment]
Yes, servers are wonky.
