### ISSUE TITLE
Data erros when start in my VPS

### ISSUE THREAD

**Issue by SkyBadPT** [AHAAAAAAA/PokemonGo-Map#659]
Im getting smome erros when one user try to see the website can someone help me?

Operating System: Ubuntu 15

Installed version of Python:
Python 2.7.12

What i have tryed:
Im starting with this command: (I have hidded the ID and PASSWORD)

`python example.py -a ptc -u USER -p PASS -l "38.767948, -9.094914" -st 20 -H 00.00.00.00 -P 5000 -ar 5`

Logs:

[-] retrying_api_req: request error (Unexpected end-group tag.), retrying
[-] retrying_api_req: request error (Unexpected end-group tag.), retrying
xx.xx.xx.xx - - [20/Jul/2016 23:04:47] "GET /data HTTP/1.1" 200 -
xx.xx.xx.xx  - - [20/Jul/2016 23:04:50] "GET /data HTTP/1.1" 200 -
[-] retrying_api_req: request error (Unexpected end-group tag.), retrying
xx.xx.xx.xx  - - [20/Jul/2016 23:04:52] "GET /data HTTP/1.1" 200 -
xx.xx.xx.xx - - [20/Jul/2016 23:02:34] "GET /data HTTP/1.1" 200 -
[-] retrying_api_req: request error (Unexpected end-group tag.), retrying
xx.xx.xx.xx - - [20/Jul/2016 23:02:34] "GET /config HTTP/1.1" 200 -

(xx.xx.xx.xx ) is the IP os the user.

**Comment by mkody** [comment]
1) You're using the `master` branch. Please checkout the develop branch: `git checkout develop`
2) Servers are unstable at the moment

**Comment by DerScreever** [comment]
we dropped the support for the master branch.
