### ISSUE TITLE
NEW FEATURE (I'm not trolling)

### ISSUE THREAD

**Issue by cmorbaab** [AHAAAAAAA/PokemonGo-Map#661]
In the future, I would recommend adding a filter when searching for pokemon since most of the pokemon in my area are shit so I want to look for good pokemon.

**Comment by npeep** [comment]
This is already a feature.  The -i switch will ignore a list that you specify.

**Comment by tomcat90** [comment]
This already exists

**Comment by eruliaf** [comment]
Perhaps implementing this in the UI will aid users such as @cmorbaab who do not realize this functionality is present

**Comment by docrockulus** [comment]
You can already do this. Use the -i <poke#>,<poke#> to ignore certain pokemon. Use -o to only show certain pokemon.

**Comment by theblackmarmoset** [comment]
How do you use the -i switch?  Is it like -i Zubat, Rapidash, Sandslash and so on?  Or is it some other format?

**Comment by npeep** [comment]
@theblackmarmoset This other issue has an updated copy of the Usage parameters..should explain it.  But yes, you can use names (with no spaces, just commas) or ID#'s.

https://github.com/AHAAAAAAA/PokemonGo-Map/issues/581

**Comment by theblackmarmoset** [comment]
@npeep Thank you so much!  Helps a lot man.  This will make it so much easier on me.  <3

**Comment by medghaim** [comment]
Eventually this functionality will be available through the UI, I'd imagine.

**Comment by shadow7412** [comment]
Yeah I can see the value of doing it through the UI - being able to temporarily hide certain pokemon, but still retaining the ability to view them when you want to would be very useful.
