### ISSUE TITLE
runserver.py file not found

### ISSUE THREAD

**Issue by uday1201** [AHAAAAAAA/PokemonGo-Map#664]
problem with executing the server. Installed the requirements . I'm running on ubuntu 15.10

**Comment by Skullmonkey** [comment]
I am guessing you are still on the master branch. Switch to develop: https://github.com/AHAAAAAAA/PokemonGo-Map/tree/develop

**Comment by dhirnitish** [comment]
I think you have downloaded the master branch. Try downloading the develop branch or make sure you are in the right folder.

**Comment by uday1201** [comment]
Thanks

**Comment by jangrewe** [comment]
`git checkout develop`

**Comment by shadow7412** [comment]
@uday1201 if this solved your problem, can you please close this issue?
