### ISSUE TITLE
Unexpected end-group tag

### ISSUE THREAD

**Issue by plokiii** [AHAAAAAAA/PokemonGo-Map#667]
### Environment info
Operating System:

Windows 7 

Installed version of Python:

2.7.12

### Steps to reproduce
1. Install Python, launch pip
2. C:\Python27\Scripts\pip.exe install -r requirements.txt
3. C:\Python27\python example.py -a ptc -u ****** -p ******  -l "PLACE" -st 10

### What have you tried?
1. Download again the folder
2. reinstall pip and python

### Logs or other output that would be helpful
When i execute the 3d step here what i got : 

[http://puu.sh/q8zIZ/b50158ec53.png](url)

**Comment by plokiii** [comment]
What do you mean server are down ?

I dont have my iPhone with me, we cant play right now thats the pb ?

**Comment by plokiii** [comment]
Ok so i found my iphone and i am connected, just got that pb "GPS signal not found"

**Comment by talentedmrripley** [comment]
It means that Niantic is having server issues and therefore neither the game nor the map will work.
