### ISSUE TITLE
Feature Ideas

### ISSUE THREAD

**Issue by alexanderrock** [AHAAAAAAA/PokemonGo-Map#669]
- [ ] Notifier (like https://github.com/jxmorris12/PokemonGo-Finder/blob/master/notifier.py)
- [ ] Run to pokestops
- [ ] Farm specific area for pokestops
- [ ] Human walking logic
- [ ] Catch Pokemon automatically
- [ ] Drop items when bag is full
- [ ] Scan your inventar for XYZ CP pokemon and release them
- [ ] Pokemon catch filter
- [ ] Hatch eggs
- [ ] Incubate eggs
- [ ] Evolve pokemons
- [ ] Use candy
- [ ] Fully automate this script

**Comment by Sejadis** [comment]
this is not supposed to be a bot playing for you so i highly doubt any of that will be implemented

**Comment by marioacarvalho** [comment]
Please, this shouldn't be bot! Only thing that I agree is the *Notifier* e.g. Select a pokemon that I want and get a browser notification when it's within my range.

**Comment by talentedmrripley** [comment]
I don't think the intention of this was ever to be a bot to play for you.  I don't want to see features like that added.
