### ISSUE TITLE
Track repeating visits to same location

### ISSUE THREAD

**Issue by billbo99** [AHAAAAAAA/PokemonGo-Map#672]
Not sure how easy this would be to implement,  but when the servers were running I saw a 'Ponyta' keep appearing near the same location every 15 minutes, and then disappear after 5 mins.

If possible keep the old records after the pokemon expires in the DB, but only show the live locations on the map.

Then when the pokemon next appears kick off a stored procedure is to check for the same pokemon in a 20-50m range.  You could also show that history when clicking on the pokemon the frequency of re-occurrence in the general area.

**Comment by crckdns** [comment]
you could just create a heat-map with all the data from database per pokemon, so you know/see the spawnpoints :)
