### ISSUE TITLE
Start server with pm2??

### ISSUE THREAD

**Issue by SkyBadPT** [AHAAAAAAA/PokemonGo-Map#673]
Can someone help me how can i start the server with pm2 or screen in linux ubuntu for the server don't stop when i close the SSH Console?

**Comment by Stex** [comment]
1. Start a new screen with `screen`
2. Once inside, run the server as usual.
3. Detach the screen with `CTRL + a` `CTRL + d`

You can get back to your screen session later with `screen -x` (assuming you only have one screen session open)

**Comment by crckdns** [comment]
you open a new screen or tmux session ..and start the scanner inside~ like with everything run inside of a terminal multiplexer.

**Comment by benjdlambert** [comment]
```bash
pm2 start ./example.py -- -u user -p password #etc
```
