### ISSUE TITLE
Error: [INFO] Map Download failed. Trying again.

### ISSUE THREAD

**Issue by tr1p0z** [AHAAAAAAA/PokemonGo-Map#676]
Pokerstops are not showing for me and im getting this error and not too much pokemos in a good place, seems like something is wrong, maybe  are server problems

**Comment by docrockulus** [comment]
Servers are having trouble, give it some time. 

http://cmmcd.com/PokemonGo/

**Comment by medghaim** [comment]
Closing as it's not an issue.
