### ISSUE TITLE
Not able to view on iPhone?

### ISSUE THREAD

**Issue by theblackmarmoset** [AHAAAAAAA/PokemonGo-Map#678]
Okay.  So here is the rundown.  I've been trying to get this working on iPhone for the past few hours with no avail.  I've has some great people help me out with it and I am still having problems.  

Alright. This is what my port forwarding page looks like: http://prntscr.com/bvcx23

This is what I'm putting into cmd:

python example.py -a ptc -u ******** -p ******* -l "Adress" -st 10 -H 0.0.0.0 -P 5000

And I am typing this into safari on my iPhone: "http://[IP I got from searching "IP" in google]:5000"

When I put that into the safari on my phone it comes up with "Safari cannot open the page because it could not connect to the server"

I hope I gave you enough info to diagnose the problem. <3

**Comment by Bakies** [comment]
Your inbound port is set to 25565, so you should got to http://[your ip]:25565 or change that to 5000

**Comment by theblackmarmoset** [comment]
It still comes up with the same error.

**Comment by IQNeoXen** [comment]
Why did you choose Port 25565 for your inbound Port?? Set it to 5000 aswell

**Comment by theblackmarmoset** [comment]
Just set it to 5000 and tried again and it still does not work.

**Comment by Bakies** [comment]
does it work locally on the computer you are running it from?
browser to http://localhost:5000 on the host machine

**Comment by theblackmarmoset** [comment]
Yeah, it works on my computer but not my phone.

**Comment by theblackmarmoset** [comment]
http://prntscr.com/bvfsu5  This is what comes up when I type that in my computer.

**Comment by IQNeoXen** [comment]
Looks like you're German so maybe it's easier this way...

Versuch mal "-H" und dann nicht 0.0.0.0 sondern deine lokale IP. 

Geht es denn nur auf dem iPhone nicht oder auch nicht von deinem PC aus?

**Comment by theblackmarmoset** [comment]
LOL I'm not german! Why did you think that though?  I don't speak a nip of german.

**Comment by theblackmarmoset** [comment]
I'm american

**Comment by IQNeoXen** [comment]
Try the exact same thing you typed on your iPhone into your PC and see if it works there

**Comment by IQNeoXen** [comment]
Hahaha lol because in your portforwarding Screenshot, it says "Language: German" xD

**Comment by theblackmarmoset** [comment]
Oh wtf? thats weird.  Anyways, I tried typing in the local ip and my ipv4 into my computer and neither worked.  But when I type localhost:5000 into the computer it works.

**Comment by IQNeoXen** [comment]
The fuck.. sorry wrong Screen. Omg i'm drunk excuse me.. lol


Try it from another Computer in your network and see if that works

**Comment by IQNeoXen** [comment]
Ohh Okay. That looks like a Firewall issue.. is it still turned off?

**Comment by theblackmarmoset** [comment]
No I turned it back on.  I'll try turning it off and seeing if it works.

**Comment by IQNeoXen** [comment]
If not, add an exclusion to it in the Firewall Settings

**Comment by Bakies** [comment]
double check the internal IP for the host machine

**Comment by theblackmarmoset** [comment]
yup, still doesn't work and I do have an exclusion to it in firewall settings.  Just to be sure you're talking about windows firewall right?

**Comment by theblackmarmoset** [comment]
How do I find my internal IP?

**Comment by theblackmarmoset** [comment]
do i use the ipconfig thing?

**Comment by theblackmarmoset** [comment]
OH! I just got it to work with my wifi.  brb going outside to see if it works with my LTE data.

**Comment by theblackmarmoset** [comment]
Okay, so it doesn't work with my local ip if I'm not connected to my home wifi

**Comment by IQNeoXen** [comment]
That makes sense because it's your LOCAL ip lol... Since you portforwarded it, try connecting trough your public ip... (Like xxx.xxx.xxx.xxx:5000)

**Comment by theblackmarmoset** [comment]
I deleted all those comments since it was pretty spammy.  Anyways, it doesn't work with my public ip.  So  I still don't know what the issue is.

**Comment by IQNeoXen** [comment]
If it works with your local ip but not your public one, the issue has something to do with your portforwarding. Are you sure you forwarded the right Port to the right Computer?

**Comment by theblackmarmoset** [comment]
No I'm not.  How can I be sure I did though?  I'm really new to all this stuff.

**Comment by IQNeoXen** [comment]
Ok so in your portforwarding Settings, be sure it forwards Port 5000 to Port 5000 to your local computer (his IP adress)

And doublecheck the ipadress with ipconfig ;)

**Comment by theblackmarmoset** [comment]
Does this look right to you?  http://prntscr.com/bvg289

**Comment by jgr3go** [comment]
Does it not need to be turned on?

**Comment by IQNeoXen** [comment]
If your PC has the ipadress 192.168.2.9 then it should work.

Be sure that you've typed in the right public ipadress! Go to http://www.myip.is/ if you're not sure..

**Comment by IQNeoXen** [comment]
Btw, don't worry if the map doesn't show any Pokémon now... Servers seem to be down again

**Comment by theblackmarmoset** [comment]
Okay so I turned it on and it still seems to not be working on my iPhone in the safari app.   My PC does have the ip address 192.168.2.9  and it still doesn't work on my phone.  :(

**Comment by IQNeoXen** [comment]
Your phone is connected to the same network (WiFi)? I thought you got that working previously?

**Comment by MrHexagon** [comment]
192.168.2.9 is your local network ip, you need your router ip. Get it here http://ipaddress.com

**Comment by theblackmarmoset** [comment]
This is what I typed into the safari URL in my phone. [Router IP address]:5000

Is that right?

**Comment by IQNeoXen** [comment]
@MrHexagon haha i already tried to tell him this ;) look up soms posts...

**Comment by IQNeoXen** [comment]
Yeah should be alright. Type the same thing into your PCs Browser and look if that works..

**Comment by theblackmarmoset** [comment]
It doesn't work in my PC's browser either.

**Comment by theblackmarmoset** [comment]
My firewall is off.

**Comment by IQNeoXen** [comment]
Then there's still a Problem with the portforwarding..

**Comment by IQNeoXen** [comment]
Is there a specific error or just "Timeout" or something? When trying to connect from your pcs browser

**Comment by theblackmarmoset** [comment]
What's wrong with the port forwarding then?   Because I thought [this](http://prntscr.com/bvgbmk) was right.

**Comment by theblackmarmoset** [comment]
It says "Safari could not open the page because the server stopped responding".  So that's a timeout thing right?

**Comment by IQNeoXen** [comment]
Yeah it should be right... Can you try using another Browser on your PC?

**Comment by theblackmarmoset** [comment]
Sure

**Comment by theblackmarmoset** [comment]
Downloading firefox now.

**Comment by theblackmarmoset** [comment]
Doesn't work with firefox either.

**Comment by MrHexagon** [comment]
@IQNeoXen whoops, shoulda read higher

@theblackmarmoset 
Open port 5000 on your router and point it to 192.168.2.9 port 5000

if you're accessing from within your local network you need to use 192.168.2.9:5000
if you're accessing from outside your local network use [routerip]:5000

**Comment by IQNeoXen** [comment]
Ok... I'm really sorry but it's fckin late here in Europe and I have to sleep now. Try Posting all your error messages and I'll have a look tomorrow, ok? Maybe someone solves your problem while i'm asleep ;) cya!

**Comment by theblackmarmoset** [comment]
Okay thanks for the help @IQNeoXen  @MrHexagon how do I open port 5000 on my router and point it to my local ip with port 5000?

**Comment by theblackmarmoset** [comment]
So are you saying this isn't right?  http://prntscr.com/bvgf7t

**Comment by theblackmarmoset** [comment]
Error I get: http://prntscr.com/bvggb4

**Comment by MrHexagon** [comment]
Do you see map if you go to 192.168.2.9:5000 ?

**Comment by theblackmarmoset** [comment]
Yes

**Comment by MrHexagon** [comment]
Ok now turn wifi off on your phone so that you're not using your local network and try and connect to [routerip]:5000 on your phone.

**Comment by jgr3go** [comment]
@theblackmarmoset your screenshot looks correct, my guess is there's another setting in your router that's blocking external traffic (even your port forwarding is set up correctly, you may have to enable outside traffic in the first place), or you're in a subnetwork (like at a school or something) and don't have access to the intermediary routers.  

If not the second, look around at other settings in your router to see if there's anything that might have disabled external traffic.

**Comment by theblackmarmoset** [comment]
Would any of these tabs have disabled external traffic? http://prntscr.com/bvgjeo  I am at a home computer, not a school/work one.  Also I tried turning off my wifi on my phone and wasn't able to connect that way either. :/

**Comment by jgr3go** [comment]
possibly the firewall tab, yeah. What router are you using?

**Comment by theblackmarmoset** [comment]
I have a belkin router and it says the firewall is turned off in the firewall tab. http://prntscr.com/bvgko4

**Comment by theblackmarmoset** [comment]
http://prntscr.com/bvgljx  This is what the dashboard looks like.

**Comment by theblackmarmoset** [comment]
Advanced settings in the dashboard. http://prntscr.com/bvglp3

**Comment by jgr3go** [comment]
Hm, I'm mostly out of ideas.  I assume when you go here: http://www.yougetsignal.com/tools/open-ports/   and change the port to 5000, is says it's closed, right?

**Comment by theblackmarmoset** [comment]
Well when I have the pokemon locator running it says its open but then when I don't have it running it says its closed.

**Comment by jgr3go** [comment]
oh! that means your port forwarding is working then --- that's the ip address you're trying to open on your phone when the server is running?

**Comment by theblackmarmoset** [comment]
yes

**Comment by theblackmarmoset** [comment]
http://prntscr.com/bvgo11 server running

**Comment by theblackmarmoset** [comment]
Oops, i sent a link with my ip in it.  Pls don't hack meh. :P  Anyways,  it still does not work when I try on my PC or phone while the server is running

**Comment by world177** [comment]
From reddit

https://www.reddit.com/r/pokemongodev/comments/4t80df/wip_pokemon_go_map_visualization_google_maps_view/d5gcu71

> go to the last line in example.py and change it to
> `app.run(host='0.0.0.0', debug=True)`

**Comment by jgr3go** [comment]
eh, i'd delete that comment, just in case :/

As @world177 mentioned, it has some stuff tied to localhost it looks like.  Odd.

**Comment by theblackmarmoset** [comment]
Just to be clear, do I change everything in the last line to that?  So change "app.run(debug=True, threaded=True, host=args.host, port=args.port)"  to "app.run(host='0.0.0.0', debug=True)"?

**Comment by world177** [comment]
Yes. Remove the last line completely and change it to that. It worked for me at least.

**Comment by jgr3go** [comment]
just change the host, port/threaded you'll want to keep   (or run the server with  `-H 0.0.0.0`)

**Comment by jgr3go** [comment]
Without trying it you should also just be able to boot the server with `--host 192.168.2.9` added to whatever the rest of the arguments are.

**Comment by theblackmarmoset** [comment]
@world177 That didn't work for me.  @jgr3go I'm using this to run the server [python example.py -a ptc -u ****** -p ****** -l "Location" -st 10 -H 0.0.0.0 -P 5000 -ar 5]

**Comment by jgr3go** [comment]
Sorry deleted my post since I don't know for sure -- try your internal IP instead of 0.0.0.0

**Comment by world177** [comment]
Did you receive any errors or anything? Or can you just not access it through the internet still? I'll scroll up and see what you have for port forwarding.

**Comment by theblackmarmoset** [comment]
@jgr3go  Okay I'll try that.

**Comment by theblackmarmoset** [comment]
@world177  I didn't receive any errors.

**Comment by theblackmarmoset** [comment]
@jgr3go  Still getting the same error. http://prntscr.com/bvgslq

**Comment by world177** [comment]
Did you verify that the private ip is the correct one on your network? I didn't see a post up above about it.

**Comment by theblackmarmoset** [comment]
Yeah I did.  It's the right one because I used it to look at the map in my browser while connected to my home wifi.

**Comment by theblackmarmoset** [comment]
What?  Why was this closed?

**Comment by world177** [comment]
Probably because this isn't an issue with their code.

**Comment by theblackmarmoset** [comment]
Oh, can you still help me with this though?  I've been trying to get it working for the past 5 hours.

**Comment by jgr3go** [comment]
i can in a little bit, this conversation is more appropriate for a gitter / chat though, i agree with the closing of the issue anyway. :)

**Comment by world177** [comment]
Okay.. umm..

Make sure this is still changed.

> go to the last line in example.py and change it to
> `app.run(host='0.0.0.0', debug=True)`

Then verify your port forwarding settings are still like so:
http://prnt.sc/bvcx23

Make sure your private ip is 192.168.2.9 (which can be done from cmd by typing "ipconfig")

After this, I would try turning off your firewall again, and accessing it from outside your network.

**Comment by theblackmarmoset** [comment]
Did all this with no success.   I'm so sad that I can't figure out with the issue is and neither can anyone else.  :/

**Comment by jgr3go** [comment]
What got it working for me was:
`python example.py -a google -u ***** -p ***** -l "New York" -st 10 -ar 5 -P 5000 -H '0.0.0.0'`

and the original code 
`app.run(debug=True, threaded=True, host=args.host, port=args.port)`

You should see a line of output at the beginning looking like:
`   * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)`

The last output is the most important, it needs to be opened on 0.0.0.0 and port 5000

**Comment by theblackmarmoset** [comment]
I see all that and have all those settings.  THIS IS FRUSTRATING ME!  Sorry, I have just been trying to solve this problem and I feel like I've gotten nowhere in the past 6 hours...  http://prntscr.com/bvh4c6

**Comment by jgr3go** [comment]
Are you sure?  I'm able to hit your endpoint....

**Comment by theblackmarmoset** [comment]
@jgr3go  what do you mean you're able to hit my endpoint?

**Comment by jgr3go** [comment]
http://prnt.sc/bvh7wu

Based on your public IP address in the screenshot you posted above (which you should probably delete :)  )

**Comment by theblackmarmoset** [comment]
Awesome! You know where I live!  You should come over and get on my computer to fix the issue if you're around my location man.  If you'd like to delete that comment btw that would be great so no creepers come to my house. :P

**Comment by theblackmarmoset** [comment]
Thanks man

**Comment by jgr3go** [comment]
Yep, tried to delete the upload too but I don't know why it's not letting me do that.

**Comment by theblackmarmoset** [comment]
all good man, you think you could actually come over and I could tell you whats been going on?  I trust you. :)

**Comment by theblackmarmoset** [comment]
or we could skype.  that would be pretty simple too.

**Comment by theblackmarmoset** [comment]
if you're down to skype just add me.  I really need help right now.  skype: theblackmarmoset

**Comment by world177** [comment]
I mean, it looks like it's working fine if he's able to connect to it.

**Comment by theblackmarmoset** [comment]
I can connect to it just fine with my computer.  It's using my computer's IP address and doing it on mobile that I'm having trouble with.

**Comment by theblackmarmoset** [comment]
@jgr3go do you think you'll be able to skype me?

**Comment by world177** [comment]
On your phone, use the address you get from here:

http://ipaddress.com/

And enter into your phone browser 

'http://yourip:5000'

**Comment by theblackmarmoset** [comment]
@world177  It still doesn't work.

**Comment by jgr3go** [comment]
I thought i just did, skype chat anyway

**Comment by theblackmarmoset** [comment]
I don't think you did man.  I didn't get your request.  What's your skype?

**Comment by Abbondanzo** [comment]
Dropping this tip for anyone else who reads. If the host is set to localhost or 127.0.0.1, you can only access the map via the local server (i.e. why it works on the computer it's hosted on and not a phone). When you set the host to 0.0.0.0, it allows external applications to communicate with your server/hosted program.
