### ISSUE TITLE
Error running pip upgrade command

### ISSUE THREAD

**Issue by nickproz** [AHAAAAAAA/PokemonGo-Map#679]
I've run:
pip install --upgrade -r requirements.txt 
and
sudo pip install --upgrade -r requirements.txt 
and keep getting this error, any ideas?:

Installing collected packages: setuptools
  Found existing installation: setuptools 1.1.6
    Uninstalling setuptools-1.1.6:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip/req/req_set.py", line 736, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 742, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 299, in move
    copytree(src, real_dst, symlinks=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 208, in copytree
    raise Error, errors
Error: [('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.py', '/var/folders/ms/7dwzt15n7711kyqhyx3bydbml4xqlz/T/pip-1m8O0j-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.py', "[Errno 1] Operation not permitted: '/var/folders/ms/7dwzt15n7711kyqhyx3bydbml4xqlz/T/pip-1m8O0j-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.py'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.pyc', '/var/folders/ms/7dwzt15n7711kyqhyx3bydbml4xqlz/T/pip-1m8O0j-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.pyc', "[Errno 1] Operation not permitted: '/var/folders/ms/7dwzt15n7711kyqhyx3bydbml4xqlz/T/pip-1m8O0j-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.pyc'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.py', '/var/folders/ms/7dwzt15n7711kyqhyx3bydbml4xqlz/T/pip-1m8O0j-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.py', "[Errno 1] Operation not permitted: '/var/folders/ms/7dwzt15n7711kyqhyx3bydbml4xqlz/T/pip-1m8O0j-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.py'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.pyc', '/var/folders/ms/7dwzt15n7711kyqhyx3bydbml4xqlz/T/pip-1m8O0j-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.pyc', "[Errno 1] Operation not permitted: '/var/folders/ms/7dwzt15n7711kyqhyx3bydbml4xqlz/T/pip-1m8O0j-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.pyc'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib', '/var/folders/ms/7dwzt15n7711kyqhyx3bydbml4xqlz/T/pip-1m8O0j-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib', "[Errno 1] Operation not permitted: '/var/folders/ms/7dwzt15n7711kyqhyx3bydbml4xqlz/T/pip-1m8O0j-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib'")]

**Comment by Bakies** [comment]
run as root/run with sudo

**Comment by rlex** [comment]
>Operation not permitted
Run with sudo or use tools like https://github.com/yyuu/pyenv

**Comment by isnifer** [comment]
Or install with `--user python` in the end
```bash
pip install --upgrade -r requirements.txt --user python
```
