### ISSUE TITLE
Can't execute script, 'Cryptodome.Cipher._raw_ecb' error

### ISSUE THREAD

**Issue by joaop7marinho** [AHAAAAAAA/PokemonGo-Map#681]
After installing Python, pip, etc. I tried to execute the script and it seems that it cannot load 'Cryptodome.Cipher._raw_ecb' or sth...
http://pastebin.com/YU3DaV59
Any idea?

**Comment by IQNeoXen** [comment]
Any errors while pip-installing the dependencies?

**Comment by joaop7marinho** [comment]
I think it perfectly installed pip, and I even tried to reinstall by double-clicking again on the installer.
Maybe it has sth to be with the change I made from Phyton 3 to Phyton 2?

**Comment by IQNeoXen** [comment]
Yeah you installed pip but are you sure it installed the others requirements right?

That could be an issue, yep.. try forcing it to use Python 2.7

**Comment by joaop7marinho** [comment]
If I try to use 'pip install --upgrade -r requirements.txt' on the PokemonGo-Map folder, it just says that all the requirements are up to date.
I unistalled the one I had (3.5.2) and installed 2.7.12 as I said before, what do you mean by "force it"?

**Comment by IQNeoXen** [comment]
Oh Okay so your system is clean :D try installing the requirements by using sudo..

And just doublecheck your Python Version by typing "python" into a new Shell so it will show the Version it's using by default

**Comment by joaop7marinho** [comment]
Oh damn I need to take a look at it tomorrow, and I'm a little newby to this kinda thing so maybe I'll have to do a researsh :s and thanks for ur help man!

**Comment by IQNeoXen** [comment]
Np ;) let me know if you need any help!

**Comment by virus32** [comment]
im having the exact same error. im on windows 10.

**Comment by virus32** [comment]
Update: I downgraded python from 2.7.12 to 2.7.10 .

and i had to use setup tools version 23.2.1 to install flask-googlemaps  + markup.

pip install setuptools==23.2.1

and now it works beautifully!!!
@joaop7marinho I hope this helps u.

**Comment by joaop7marinho** [comment]
@virus32 , Sorry to bother, but even when I used setup tools version 23.2.1 to install the requirements, (it says that I can upgrade it, as the requirements do) and I get the exact same error... what in the world can I do?

**Comment by virus32** [comment]
@joaop7marinho u have to downgrade Python itself from 2.7.12 to 2.7.10, so u have uninstall the latest version. its the latest version of python thats causing this "cannot native module"

the setuptools 23.2.1  is just to install Flask-googlemaps and the markup.

one last thing make sure u download 2.7.10 32 bit edition and not the 64.

sorry about the late answer

**Comment by joaop7marinho** [comment]
@virus32 oh no problem, actually i just nerd to thank you for replying. I thought you would no longer answer because this was closed. I had already done all those steps and still nothing, but you last mention of the 32 bits that didn't even passed by my mind. I'll check it tomorrow since it is pretty late in my country (4:34 a.m.) and see if it works. Thanks again!

**Comment by virus32** [comment]
@joaop7marinho 64 bit vs 32 Bit makes a huge difference in python, so let me know how it went!

**Comment by joaop7marinho** [comment]
Yah i just uninstalled 64bit version and installed 32 one, and I did the same as I did before and still nothing. I guess I'll just start all over like the wiki says, the installation way seems updated and different somehow.

**Comment by virus32** [comment]
@joaop7marinho alright bro! good luck! and if for some reason it still doesnt work. try deploying it straight to heroku. so can access it on the web. heroku is a much easier option.
