### ISSUE TITLE
BUG: Times incorrect when run on server in different timezone to client

### ISSUE THREAD

**Issue by MikeDX** [AHAAAAAAA/PokemonGo-Map#683]
The Human readable version of the timestamps (for pokemon TTL and I'm going to guess pokestop time but I cannot tell on the current develop branch build) are incorrect. 

My VPS timezone is in EDT - and my local browser is GMT+1 (BST), so all times shown on the map are currently 4 hours off:

e.g. 
localtime: 23:42
pokemon time from map: 

Gastly - #92
Disappears at 19:48:19 (00m00s)

I shall investigate this and submit a pull request with a fix - unless somebody else is working on it.

**Comment by Stex** [comment]
There is #578 which seems to go into the same direction

**Comment by Bakies** [comment]
I think this is a more general issue, my server and I are in the same time zone and the times are wrong.

**Comment by talentedmrripley** [comment]
I believe all the times are UTC.  Last time I looked mine were off by exactly the offset to my timezone.

**Comment by MikeDX** [comment]
UTC is the same as GMT isn't it? Pull request seems to address that but I'm unsure as to why the times aren't saved as a unix timestamp - but as a datetime field, just seems to add unnecessary conversion for no real reason. Maybe someone can shed light on this..

**Comment by MikeDX** [comment]
This seems to be fixed in the latest commit(s), so I am closing this bug for now.
