### ISSUE TITLE
Script has stopped working for me

### ISSUE THREAD

**Issue by iPenguin67** [AHAAAAAAA/PokemonGo-Map#686]
### Environment info
Operating System: Mac OS 10.9.4

Installed version of Python: 2.7.12

I installed the Master version earlier today and it was working as long as the servers were working. Then I closed one instance and tried to re-run it, and got nothing. Checked the site, download the develop version, tried again, still nothing. When I say nothing, I mean once I enter the command, the next line just says:
> 

### Steps to reproduce
1. *Note this is after Python and pip are installed -- previously the app was working for me.
2. Enter python runserver.py -a ptc -u [my username] -p [mypassword] -l "43xxxxxx, -8x.xxxxxxx” -st 100
3. Get a line below that just reads "> " with a little box cursor.

### What have you tried?
1. Reinstalling, installing the develop branch, updating requirements.txt, refreshing my localhost:5000 window. 

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by Stex** [comment]
@iPenguin67 Your command contains two kinds of quotation marks - most likely from copy+paste. This causes the shell to wait for the closing `"` which are not actually part of the command.

Simply replace both with normal quotation marks and you should be fine.
