### ISSUE TITLE
credentials.json missing

### ISSUE THREAD

**Issue by Valareos** [AHAAAAAAA/PokemonGo-Map#688]
Trying to run develop as is, says credentials.json missing.

I worked around it by copying my credentials.json from my previous install (from master)

Should I instead edit the credentials.example.json with my API key instead?

**Comment by macgngsta** [comment]
edit your credentials.json from before and remove all the other key pairs except for `gmaps_key`

**Comment by mohitbagde** [comment]
Or you could run the runserver.py with -k API_KEY by following this [page](https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Google-Maps-API:-a-brief-guide-to-your-own-key) on the wiki.

**Comment by Valareos** [comment]
Thanks, Ill use the -k API_KEY one then. My run file is set as a batchfile so I can have saved location sin @rem lines

**Comment by medghaim** [comment]
It'll be easier to just state your API in the file, then rename it to: "credentials.json" so you don't have to enter your key every time.

But yes, this is by design.

**Comment by JZ6** [comment]
closed
