### ISSUE TITLE
Server issues

### ISSUE THREAD

**Issue by daknet01001** [AHAAAAAAA/PokemonGo-Map#690]
Hello, 

I'm on linux, all my python requirement are ok, and i'm on the dev branch.
When i lunch the server with :
python runserver.py -a google -u XXX@gmail.com -p XXXX -l "Brussels" -st 6 -ar 100 -dl

Many time the auth will fail:
[auth_google] [   INFO] Google Login failed.

And when the auth will succeed i have:
 [    rpc_api] [WARNING] Unexpected HTTP server response - needs 200 got 502

i don't know if it's the Pokeservers ares done again or if i do something wrong because it's my first time to run this.

A other point is that my web page (http://127.0.0.1:5000/) load correctly the html but no CSS no JS and no favico.
my chrome js consol tell me 404 for everything except for favico who's 500

Thanks for your help

**Comment by Tzeentchful** [comment]
The servers are indeed down. Please check before opening an issue.
http://ispokemongodownornot.com/

**Comment by daknet01001** [comment]
oké... i have see #687 ... whe have write post on same time but if you have any answer for my other point   ;D

**Comment by JZ6** [comment]
server issues
