### ISSUE TITLE
Error message for down servers

### ISSUE THREAD

**Issue by talentedmrripley** [AHAAAAAAA/PokemonGo-Map#691]
Change or add to error messages like "Unexpected HTTP server response - needs 200 got 502" to indicate that this generally means the servers are down.

**Comment by DustinChaloupka** [comment]
Parsing the response content (or at least the status code) and giving a more informed message would be nice, if nothing else but to curtail the amount of issues that get created because the servers are down/unstable.

**Comment by medghaim** [comment]
Yep, this was suggested in the dev channel. We're discussing :) Closing this issue and adding it to our desired feature list!
