### ISSUE TITLE
Data saving into a csv

### ISSUE THREAD

**Issue by Katospiegel** [AHAAAAAAA/PokemonGo-Map#694]
Hi, 

I think that it could be interesting for research purposes to get a csv with the information downloaded that appear in the map. I'm thinking in visualize heatmaps of a certain pokemon of the city. 

Any idea to develop this in the near future?

**Comment by ththompson** [comment]
The development branch is writing everything to an SQLlite3 database. This can be used to build the heat maps / analysis.
