### ISSUE TITLE
Development Exception in thread search_thread: too many SQL var

### ISSUE THREAD

**Issue by NgJason** [AHAAAAAAA/PokemonGo-Map#699]
### Environment info
Operating System: w10

Installed version of Python:
2.7.12

### Steps to reproduce
python runserver.py -a google -u XXXXXXXXX@gmail.com -p XXXXXX -l "37.788573,-122.396042" -st 10

### Logs or other output that would be helpful

![screenshot 2016-07-20 17 37 05](https://cloud.githubusercontent.com/assets/6984333/17007861/df8f736e-4ea0-11e6-8088-04abf3c9f3c8.png)

**Comment by fhirner** [comment]
remove pogom.db

**Comment by NgJason** [comment]
@fhirner Removing pogom.db leads to a new exception:
![5ad2dc47dd](https://cloud.githubusercontent.com/assets/6984333/17007995/095e7acc-4ea2-11e6-8ec0-2ba0f9e7dbf2.png)

**Comment by jabelone** [comment]
Removing pogom.db fixes the issue for me.

**Comment by cleavenworth** [comment]
Also encountering this issue.

OS: macOS 10.12
Python: 2.7.12

Same steps to reproduce

**Comment by kingeddard** [comment]
I keep having this issue, is this supposed to be fixed?
