### ISSUE TITLE
what login credits hould i use + error on line 133 example.py exception syntax error

### ISSUE THREAD

**Issue by Theo1996** [AHAAAAAAA/PokemonGo-Map#7]
what login credits hould i use + error on line 133 example.py exception syntax error

**Comment by Idhanta** [comment]
Use your Pokemon trainer club login credentials.
See FAQ here: https://m.reddit.com/r/pokemongodev/comments/4t80df/wip_pokemon_go_map_visualization_google_maps_view/d5feu2f

**Comment by Theo1996** [comment]
OK THX
