### ISSUE TITLE
The only issue... No GUI. But hey, who needs it!

### ISSUE THREAD

**Issue by GlassToeStudio** [AHAAAAAAA/PokemonGo-Map#703]
### Steps to reproduce
1.
![image](https://cloud.githubusercontent.com/assets/11790533/17008000/d45de130-4eb2-11e6-8bb5-45d8f87e8abd.png)

**Comment by GlassToeStudio** [comment]
Was behind on the times. It looks as though a UI is in the works. And an Android app, and some other Electron app... Great Job Guys!

**Comment by blakebjorn** [comment]
threw this together real quick

https://github.com/blakebjorn/PokeMapGUI

**Comment by GlassToeStudio** [comment]
That screen shot above is what I threw together real quick, thought it would be nive to have the map embedeed.

**Comment by blakebjorn** [comment]
I don't think google maps works with QWebView on any of the python 2.7 bindings *shrug* too lazy to implement anything more than this

**Comment by GlassToeStudio** [comment]
I don't know, but it works fine in a windows web form.
