### ISSUE TITLE
Gyms and PokeStops display even without the parameters in command line. 

### ISSUE THREAD

**Issue by Skullmonkey** [AHAAAAAAA/PokemonGo-Map#704]
### Environment info
Operating System:
Win 10

Installed version of Python:
2.7.12

Commit:
10461D3

### Steps to reproduce
1. Running script with command 
`python runserver.py -a ptc -u *** -p *** -l "*** ***" -st 10 -H 0.0.0.0 -P 8800 -ar 3`

### What have you tried?
1. Adding just "-dp", "-dg", and "-dp -dg".
2. Reverted to command above.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by vincesmits** [comment]
Can confirm i also have this issue.

**Comment by Maxincredible52** [comment]
this issue is actually pretty annoying

**Comment by talentedmrripley** [comment]
I can also confirm.  I also deleted the DB and reran without the -dp flag and they still appear.

**Comment by boltron88** [comment]
-dl isn't functioning ether

**Comment by invisiblek** [comment]
https://github.com/AHAAAAAAA/PokemonGo-Map/pull/702

**Comment by Skullmonkey** [comment]
Issue fixed.
