### ISSUE TITLE
develop branch is not taking options as -dl -dg -dp into account and shows always everything

### ISSUE THREAD

**Issue by MoritzT** [AHAAAAAAA/PokemonGo-Map#705]
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discord.gg/Kzp4yky).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System: Ubuntu

Installed version of Python: 2.7

### Steps to reproduce
1. clone develop build and run it with -dl option
2. open map and look at all those pokespots
3. profit ;-)

### What have you tried?
1. Only showing the pokespots that have currently a lure in it based on the parameter -dl

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by Skullmonkey** [comment]
Same as #704.

**Comment by Maxincredible52** [comment]
this is actually pretty annoying
