### ISSUE TITLE
Map not displaying properly when Server is ran on Windows 7

### ISSUE THREAD

**Issue by Valareos** [AHAAAAAAA/PokemonGo-Map#707]
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discord.gg/Kzp4yky).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System: Windows 7

Installed version of Python: Python 2.7 (latest)

### Steps to reproduce
1. Run server on Windows 7 machine
2. Look at map from any other device
3. http://120.146.39.206:5000/  Link to my running server

### What have you tried?
1. 

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).
 If you can specify what logs you need, exactly, I will provide

**Comment by Valareos** [comment]
I do not know if the issue is based on the OS, or a recent commit has caused this. My windows 10 machine works fine but I downloaded those files an hour ago. I will attempt to re-dowload on my windows 10 machine and report if bug appears there now

**Comment by Valareos** [comment]
Issue does not exist when server is ran on a windows 10 machine  Everything on the map actually works fine on the windows 7, its just a display issue. A possible workaround is a flag that removes the displayed header info and shows just the map, for those with older OS servers?

**Comment by FrostTheFox** [comment]
What command are you running to start?

**Comment by Valareos** [comment]
copy of the batch file I use here
---Begin Batch File---
echo off
SET USERNAME= **WITHHELD**
SET PASSWORD=**WITHHELD**
SET API=**WITHHELD**

rem Flagstone, Queensland
rem SET LOC="-27.809181, 152.955869"

rem Jimboomba, Queensland
SET LOC="-27.830999, 153.024365"

rem Jimboomba Park, Queensland
rem SET LOC="-27.836428, 153.028749"

c:\\Python27\python runserver.py -a ptc -u %USERNAME% -p %PASSWORD% -l %LOC% -st 10 -H 0.0.0.0 -dp -dg -k %API%

---End Batch File--

**Comment by FrostTheFox** [comment]
This issue was caused by a recent commit, we don't know why it was made, but we have reverted it. Please redownload develop and let me know if it fixes this issue.

**Comment by Valareos** [comment]
Confirm issue has been fixed. Thank you
