### ISSUE TITLE
No Pokemon Being Shown?

### ISSUE THREAD

**Issue by HiImon1x** [AHAAAAAAA/PokemonGo-Map#709]
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discord.gg/Kzp4yky).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System: Windows 7

Installed version of Python: 2.7.12

### Steps to reproduce
I followed vintagesucks's guide on how to get this installed and running using Git (The guide can be found here: https://github.com/vintagesucks/PokemonGo-Map-Install-Guides/blob/master/WINDOWS.md), and upon running runserver.py no pokemon show up.  I don't get any error messages and the program seems to be running fine (scanning for pokemon and all that) but none show up on my map.
1. Git Bash in the PokemonGo-Map-develop folder
2. Run `python runserver.py -a google -u [USERNAME] -p [PASSWORD] -l "LOCATION" -st 5`
3. No errors, program logs in and starts scanning.
4. No pokemon appear on map.
In the logs it says that it is, "Upserting 6 pokemon" but they aren't being displayed on the map

### What have you tried?
1. I honestly wouldn't even know where to start.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by Skullmonkey** [comment]
Does refreshing the browser help?

**Comment by HiImon1x** [comment]
no, refreshing doesn't fix the issue :(

**Comment by ariefbayu** [comment]
can you share the "LOCATION"?

**Comment by HiImon1x** [comment]
San Jose, CA

**Comment by prajwalkman** [comment]
I had a kinda similar issue - opening the page on my mobile (android chrome) showed the map but no markers. I enabled "request desktop site" then the markers appeared. Then disabled "request desktop site" and it continued working normally.

**Comment by HiImon1x** [comment]
how do I open the page on my android phone?  I tried last night but I couldn't.

**Comment by ariefbayu** [comment]
I have no problem with "San Jose, CA" as location. A lot of pokemon there...

**Comment by HiImon1x** [comment]
idk man.  I don't get any error messages but on my map there isn't any pokemon

**Comment by HiImon1x** [comment]
what's the URL I'm supposed to be going to?

**Comment by slin1202** [comment]
I have the same issue, I can see console messages from the server saying Pokemon are being upserted but I don't see them on the frontend.

**Comment by slin1202** [comment]
I've boiled it down so far to that the Pokemon are being created in the database but the request doesn't return any.

**Comment by suspended** [comment]
Probably Unicode errors in the Python script causing JSON output to have a 'u' prepended to the /data endpoint

**Comment by HiImon1x** [comment]
@suspended How would I go about fixing that?

**Comment by HiImon1x** [comment]
[Fix]
I was having the same issue as #527, deleting the master folder that I still had downloaded fixed it.
