### ISSUE TITLE
CSS Broken on dev branch 

### ISSUE THREAD

**Issue by Bakies** [AHAAAAAAA/PokemonGo-Map#710]
http://i.imgur.com/T4W9cuy.png

**Comment by daknet01001** [comment]
I have something close to that see my post #695 
logs are the same?

**Comment by Bakies** [comment]
No, I am not having any errors in the log

**Comment by hgentry** [comment]
Can confirm, experiencing this too. Firefox on Mint, Midori on Raspbian both showing this issue

**Comment by Bakies** [comment]
Im using chrome on fedora 24

**Comment by daknet01001** [comment]
you are lucky at least your JS is working

**Comment by FrostTheFox** [comment]
Not quite sure where this issue is extending from, mine loads CSS fine on the latest version.

**Comment by Bakies** [comment]
@FrostTheFox I am on commit 73c151d1d56a342925b2be643b3e7f4fd8476dee
You want any info from me?

**Comment by MikeDX** [comment]
The latest commit that I can see removed the app.min.css - which I assume is being generated by grunt. 

templates/map.html
33:		<link rel="stylesheet" href="/static/dist/css/app.min.css" />

**Comment by Bakies** [comment]
[image](https://cloud.githubusercontent.com/assets/1388188/17008980/66e32c34-4ec4-11e6-9a54-ebc7c44209fb.png)

looks like the CSS is returning a 404

**Comment by FrostTheFox** [comment]
How did you guys download? ZIP file? Or via git?

**Comment by Bakies** [comment]
i used git, update with git pull

**Comment by MikeDX** [comment]
also via git, hence the git log in the comment :D

**Comment by FrostTheFox** [comment]
@MikeDX Hi, I didn't see your last comment. We are looking into why these files were removed in that commit.

**Comment by FrostTheFox** [comment]
We are reverting the commit that caused this issue. Everybody please redownload the develop branch. This should fix the issue.

**Comment by Bakies** [comment]
Thanks @FrostTheFox that push fixed it
