### ISSUE TITLE
Docker Support

### ISSUE THREAD

**Issue by cookandy** [AHAAAAAAA/PokemonGo-Map#712]
Hello,

I think it would be useful to add Docker support (to save people the headache of installing python dependencies).  

I've created a very simple Docker image which can be used the same way the app can.  For example:   

```
docker run -d --name pokemon-go-map -p 5000:5000 acook/pokemon-go-map -a google -u "<user@gmail.com>" -p "<password>" -k <googleAPIKey> -H 0.0.0.0 -l "<location>" -st 10 -ar 5 -i "Rattata,Zubat,Drowzee,Pidgey,Ekans,Paras"
```

The project [is here](https://github.com/cookandy/pokemon-go-map-docker) if you want to contribute.

As we start to persist data, enhancements might need to be made to map external volumes.  Feedback welcome.

**Comment by Bakies** [comment]
theres a pull request for this

**Comment by cookandy** [comment]
D'oh!  Searched issues, but not pull requests.  Thanks
