### ISSUE TITLE
Pokemon arent removed until page refresh

### ISSUE THREAD

**Issue by Bakies** [AHAAAAAAA/PokemonGo-Map#714]
on dev branch
They are marked Gone! when you hover over them but never get removed from the map
commit 73c151d1d56a342925b2be643b3e7f4fd8476dee

**Comment by Skullmonkey** [comment]
#704 and #705 duplicate.

**Comment by Bakies** [comment]
closed: goto dupes

**Comment by Bakies** [comment]
those dupes seem like they are different issues so I am re-opening this issue.

**Comment by Skullmonkey** [comment]
My bad, I meant to reference #700

**Comment by Bakies** [comment]
@DerScreever this is still an issue, should not be closed
