### ISSUE TITLE
Server hosted on AWS Ubuntu system refuses all outside connections (localhost works) 

### ISSUE THREAD

**Issue by Schwaitz** [AHAAAAAAA/PokemonGo-Map#715]
### Environment info
Operating System: Ubuntu 14.04.

Installed version of Python:
Both 3.5 and 2.7. Running with 2.7.

###Info

* localhost:5000 is working perfectly.
* Security Group on AWS allows all traffic to port 5000.
* I get an immediate "refused to connect" error instead of endless loading.
* netstat -l shows that it has a state of "LISTEN" on localhost:5000 with a foreign address of *:*.

Is the problem on my end, or is there some reason for it being unable to connect remotely?

**Comment by Bakies** [comment]
add -H 0.0.0.0

**Comment by FrostTheFox** [comment]
What command are you starting with?

**Comment by Schwaitz** [comment]
@Bakies @FrostTheFox 

Adding -H 0.0.0.0 fixed it. Thanks!

Adding that information somewhere in the wiki might help other people!

**Comment by Bakies** [comment]
Its in usage doc but none of the flags are actually explained :/

issue should be closed

**Comment by FrostTheFox** [comment]
@Schwaitz I can look into adding it. Thanks for the feedback, glad that solved your issue.
