### ISSUE TITLE
Dev build and Master build showing up different pokemons 

### ISSUE THREAD

**Issue by gui710** [AHAAAAAAA/PokemonGo-Map#716]
Hello,
I noticed that Master build shows different Pokemons of Dev build as you can see here:

Master: http://imgur.com/a/b7u25
Dev: http://imgur.com/a/EiuKz

Both screen shots were taken at same time.

Location: New York, NY, USA

Master Run Code: "C:\Python27\python.exe example.py -a ptc -u ********* -p ********* -l "New York, NY, USA" -st 10 -H ********* -P 5001 -dp -dg"

Dev Run Code: C:\Python27\python.exe runserver.py -a ptc -u *********  -p *********  -l "New York, NY, USA" -st 10 -H *********  -P 5000

### Environment info
Operating System: Windows 8.1

Installed version of Python: 2.7.12

### Steps to reproduce
1. Run both builds at the same time.

### What have you tried?
1. Latest Dev build and Master Build at the same time.

**Comment by FrostTheFox** [comment]
Duplicate: #596

**Comment by medghaim** [comment]
Closing. Please refer to #596
