### ISSUE TITLE
Oops! Something went wrong, even though it loads fine for a few seconds.

### ISSUE THREAD

**Issue by laernumoretz** [AHAAAAAAA/PokemonGo-Map#719]
Was working perfectly last night.
Now the webserver loads, all poke show and gyms etc, but after 10 seconds it forces me to leave the page saying "Oops! Something went wrong.    This page didnt load google maps correctly. see the javascript console for technical details"

If I refresh the map updates everything just fine though, but sometimes it happens in 2 seconds and can't get poke fast enough to see whats going on around me. 
This is happening on all computers and iOS devices, on local wifi or out and about, ports are setup etc.

Tried to sign up for a google API but it keeps saying server error too. Googles end or ours?

**Comment by jabelone** [comment]
Did you sign up for the API key and actually enter it into the credentials.json file?

**Comment by laernumoretz** [comment]
Haven't been to get an API, it keeps saying server error on googles website trying to get one.
So its the built in API that was working fine a few hours ago

**Comment by jabelone** [comment]
That's why you're getting the error,  The built in one is hitting the limit.  I can register a new API key right now.  Did you follow the guide? https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Google-Maps-API:-a-brief-guide-to-your-own-key

**Comment by laernumoretz** [comment]
Clicked past the google API server errors a bunch of times, gonna try adding it, will post back if not working :)

**Comment by jabelone** [comment]
Also post back if you do get it working so someone can close the issue :)

**Comment by FrostTheFox** [comment]
Yes, please reply if this fixes it, if it does I will close the issue.

**Comment by laernumoretz** [comment]
Yep that's what it was, new API is flawless, thanks all!

**Comment by jabelone** [comment]
No worries :)

**Comment by ChenxiSu** [comment]
I still get the same problem after generating a new google API following the wiki. I am using windows10, any idea how to fix it?
