### ISSUE TITLE
Coordinates

### ISSUE THREAD

**Issue by amartshah** [AHAAAAAAA/PokemonGo-Map#722]
python example.py -a google -u blank@gmail.com -p blank -l “40.7588951, -73.9873815” -st 1000

is resulting in the following error:
[-] register_background_thread called
[-] register_background_thread: not running inside Flask so not starting thread
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
[-] register_background_thread called
[-] register_background_thread: initial registration
[+] Locale is en
 * Debugger is active!
[+] Getting initial location
 * Debugger pin code: 142-455-223
Exception in thread search_thread:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "example.py", line 571, in main
    retrying_set_location(args.location)
  File "example.py", line 157, in retrying_set_location
    set_location(location_name)
  File "example.py", line 177, in set_location
    origin_lat, origin_lon = local_lat, local_lng = loc.latitude, loc.longitude
AttributeError: 'NoneType' object has no attribute 'latitude'

Can someone please post an example?

**Comment by Bakies** [comment]
you should provide a more detailed explanation of whats "not working" this is a place for bugs and issues you can get on the discord and ask for setup help there

**Comment by chijinbo** [comment]
no comma between longitude and latitude

**Comment by Skullmonkey** [comment]
Remove the "," so “40.7588951 -73.9873815”

**Comment by jabelone** [comment]
For reference the discord server [is here](https://discord.gg/Kzp4yky)

**Comment by amartshah** [comment]
23 -l “40.7588951 -73.9873815” -st 100
usage: example.py [-h] [-a AUTH_SERVICE] -u USERNAME [-p PASSWORD] -l LOCATION
                  -st STEP_LIMIT [-i IGNORE | -o ONLY] [-ar AUTO_REFRESH]
                  [-dp] [-dg] [-H HOST] [-P PORT] [-L LOCALE] [-ol] [-c] [-pm]
                  [-d]
example.py: error: unrecognized arguments: -73.9873815”

**Comment by FrostTheFox** [comment]
You're running the master branch. Use develop instead. master is no longer supported.
