### ISSUE TITLE
Current Map Display hides the zoom buttons

### ISSUE THREAD

**Issue by Valareos** [AHAAAAAAA/PokemonGo-Map#723]
If your not using a device that either 1: has a center mouse wheel for zooming 2: does not have the ability to zoom via touch screen, it is impossible to zoom in and out of the map

**Comment by Valareos** [comment]
Though I think its awesome that if you go into street view you can see exactly where the pokemon is at lol

**Comment by Valareos** [comment]
Current Work around, double clicking will zoom in, double right clicking zooms out

**Comment by Ayysir** [comment]
@Valareos  only on cpu, on device its moot

**Comment by MikeDX** [comment]
scroll wheel will zoom in / out on a "CPU" (I am guessing you mean desktop/laptop/something with a keyboard/mouse). On mobiles devices does pinch to zoom in work?

**Comment by IDSninja** [comment]
I have zoom buttons in chrome with iOS. Also pinching does work. This is Chrome on the master branch though.

**Comment by Valareos** [comment]
Issue was on a laptop without a touchpad mouse.

Closing out the issue as a recent commit has fixed the issue (whether intentionally or not I dont know, but  I wont argue :)
