### ISSUE TITLE
ImportError: No module named flask

### ISSUE THREAD

**Issue by crushedhat** [AHAAAAAAA/PokemonGo-Map#724]
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discord.gg/Kzp4yky).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System: MAC OS X El Capitain

Installed version of Python: 2.7.9

### Steps to reproduce
1.
2.
3.

### What have you tried?
1. Pulled from Github and website. Both versions produce the same results

### Logs or other output that would be helpful
Traceback (most recent call last):
  File "example.py", line 4, in <module>
    import flask
ImportError: No module named flask

**Comment by FrostTheFox** [comment]
Did you try rerunning the pip install -r requirements.txt command?

**Comment by tealtail** [comment]
Hopefully this helps.
When I saw the same "No module named flask" error it ended up being because of the way I was trying to run the app: `./runserver.py [OPTIONS]` 

after a while of scratching my head and looking over my env, simply running `python runserver.py [OPTIONS]` was what worked.

**Comment by crushedhat** [comment]
I did, I ended up installing all the modules myself. I do have another error now though. When I go to  http://localhost:5000 it just Flask Google Maps Full Map Example in bold text, it never changes.

**Comment by tealtail** [comment]
Any interesting console output? Did you provide your own GMaps Key?

**Comment by FrostTheFox** [comment]
Ah, you're not using the develop branch. Master branch is no longer supported.
