### ISSUE TITLE
Fatal error in launcher: Unable to create process using '"'

### ISSUE THREAD

**Issue by Pakalaka60** [AHAAAAAAA/PokemonGo-Map#726]
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discord.gg/Kzp4yky).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System: 
Windows 10
Installed version of Python:
Python 2.7.12

### Steps to reproduce
1. 
2.
3.

### What have you tried?
1. Redid whole instruction page

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by jabelone** [comment]
Please include some more info like the whole error message etc.

**Comment by Pakalaka60** [comment]
Whoops my bad. I put in this command (pip install -r requirements.txt) into the command center. It came up with Fatal error in launcher: Unable to create process using '"'.

**Comment by FrostTheFox** [comment]
This isn't a map issue, but try this command instead: python -m pip install -r requirements.txt

**Comment by Pakalaka60** [comment]
Thank you so so much! 1 last thing, when I entered in my location and my user details, I got this message: python: can't open file 'example.py': [Errno 2] No such file or directory

**Comment by FrostTheFox** [comment]
@Pakalaka60 You're running the develop branch? It would be runserver.py then.

**Comment by Pakalaka60** [comment]
Tried that, got the same thing. can't open file 'runserver.py': [Errno 2] No such file or directory, I will post what command I'm using blurring out the account details. python runserver.py -a google -u *****@gmail.com -p ***** -l "Coords" -st 10. Also, for the username I'm using the email I used for Pokemon Go, should I use my Pokemon Go username?

**Comment by FrostTheFox** [comment]
Hmm, very weird! If you signed in with Google, you use insertemail@gmail.com

Is runserver.py in your current directory? That's a python error telling you that file doesn't exist.

**Comment by Pakalaka60** [comment]
How would you check that?

**Comment by FrostTheFox** [comment]
I'm assuming since you're on windows that you're running this from CMD? Just type dir and it should list all files/folders in the current directory.

**Comment by Pakalaka60** [comment]
Doesn't look like it

**Comment by FrostTheFox** [comment]
What folder does it say you're in?

**Comment by Pakalaka60** [comment]
C:\Users\Parker

**Comment by FrostTheFox** [comment]
I doubt that's the folder where everything is, did you download the zip file and extract it somewhere? if so, that's where you need to be in cmd.

**Comment by Pakalaka60** [comment]
C:\Users\Parker>dir
 Volume in drive C has no label.
 Volume Serial Number is ****-*****
This is what im getting btw. I extracted it to the C: folder so it should be in there

**Comment by FrostTheFox** [comment]
Straight to C:? You might want to make a folder like C:\Users\Parker\Pokemap and extract all the files there, just so we can make sure everything is there.

**Comment by Pakalaka60** [comment]
Forgot to put this in. I have a folder where everything related to this is in. I opened the command window in there and typed in dir, but it doesn't look like runserver.py is in that list

**Comment by FrostTheFox** [comment]
What about requirements.txt?

**Comment by Pakalaka60** [comment]
Its in there

**Comment by FrostTheFox** [comment]
Example.py?

**Comment by Pakalaka60** [comment]
Not in there. However, this is a main.py and a pokemon_pb2.py

**Comment by FrostTheFox** [comment]
Alright, its probably best to redownload from: https://github.com/AHAAAAAAA/PokemonGo-Map/archive/develop.zip This way you get the newest version (I know you're not on develop because there's no pokemon_pb2.py in the develop branch), from there try running your command again.

**Comment by Pakalaka60** [comment]
Should I extract it in the same folder?

**Comment by FrostTheFox** [comment]
Probably best to remove all the old stuff, or put it in a new folder. Actually, now that I look at it I think you got something different but related to the project. (a more, private version per se)

**Comment by FrostTheFox** [comment]
You're going to need to create credentials.json, using this template:

{
	"gmaps_key" : ""
}

And follow these instructions:
https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Google-Maps-API:-a-brief-guide-to-your-own-key

**Comment by FrostTheFox** [comment]
Once you've done that, make sure it's in the folder with everything else, and it should run okay.

**Comment by Pakalaka60** [comment]
UPDATE: I took the previously made credentials.example.json, renamed it, put in my API code, and ran the code you gave to me in the beginning of this thread. It came up with No module named pip.

**Comment by FrostTheFox** [comment]
https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Installation-and-requirements Use this link to reinstall pip. If you're still getting it afterwards, try running C:\Python27\Scripts\pip install -r requirements.txt

**Comment by Pakalaka60** [comment]
So I saved pip (Saved as a link) to my desktop. I opened up the command window and ran python get-pip.py. It came up with can't open file 'get-pip.py': [Errno 2] No such file or directory. I know I definitely messed up installing pip

**Comment by FrostTheFox** [comment]
Did you cd C:\Users\Parker\Desktop then run the python get-pip.py?

**Comment by Pakalaka60** [comment]
I went ran cd C:\Users\Parker\Desktop into cmd and put in the command but it came up with this 'python' is not recognized as an internal or external command,
operable program or batch file.

**Comment by FrostTheFox** [comment]
Do C:\Python27\python get-pip.py

**Comment by Pakalaka60** [comment]
It successfully installed Pip.

**Comment by FrostTheFox** [comment]
Now go back to where all your files are, and try C:\Python27\Scripts\pip install -r requirements.txt

**Comment by Pakalaka60** [comment]
Done, it worked!

**Comment by FrostTheFox** [comment]
Okay! Can you do C:\Python27\python runserver.py 

Add all your arguments to the end and tell me if it works.

**Comment by Pakalaka60** [comment]
Sorry, as you can probably tell, I don't know much about this. What arguments do you mean for me to add?

**Comment by FrostTheFox** [comment]
It's alright, these things: -a google -u **@gmail.com -p ** -l "Coords" -st 10

Whatever you were putting after the .py file earlier.

**Comment by Pakalaka60** [comment]
So I ran C:\Python27\python runserver.py -a google -u ********@gmail.com -p **** -l "*******" -st 10 into my Pokemon Go folder. I got this

Traceback (most recent call last):
  File "runserver.py", line 10, in <module>
    from pogom.app import Pogom
  File "C:\Pokemon Go\pogom\app.py", line 5, in <module>
    from flask import Flask, jsonify, render_template, request
ImportError: No module named flask

**Comment by FrostTheFox** [comment]
Run in the same folder C:\Python27\Scripts\pip install flask

Sorry this is taking so many steps, this is kinda prone to break at the moment.

**Comment by Pakalaka60** [comment]
No problem! Thank you for being so patient! I ran the command and it seems to work but at the end I just wanted to note that it said this:Command "c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\parker\\appdata\\local\\temp\\pip-build-kmmhi_\\MarkupSafe\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\parker\appdata\local\temp\pip-wiz3uo-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\parker\appdata\local\temp\pip-build-kmmhi_\MarkupSafe\      in red text. I ran the command and it popped up with the same message

**Comment by FrostTheFox** [comment]
Try running runserver.py and see if it works regardless.

**Comment by Pakalaka60** [comment]
I put that in and it came up with this Traceback (most recent call last):
  File "C:\Pokemon Go\runserver.py", line 10, in <module>
    from pogom.app import Pogom
  File "C:\Pokemon Go\pogom\app.py", line 5, in <module>
    from flask import Flask, jsonify, render_template, request
ImportError: No module named flask

**Comment by FrostTheFox** [comment]
Let's try to reinstall flask, C:\Python27\Scripts\pip uninstall flask

Then C:\Python27\Scripts\pip uninstall flask

I might have to go soon, but I'll give some of the other people here the link and see if they can help more.

**Comment by Pakalaka60** [comment]
You gave me the same code twice :).

**Comment by Pakalaka60** [comment]
It says that I cant uninstall if it was never installed btw

**Comment by FrostTheFox** [comment]
Huh, someone else was having this issue aswell, It's getting late where I'm at, as I said I'll throw the link in our Discord, hopefully someone else can help you!

Sorry I couldn't solve the issue.

**Comment by Pakalaka60** [comment]
Thank you very much!
