### ISSUE TITLE
issue with finding lickitung on the map

### ISSUE THREAD

**Issue by yarden32** [AHAAAAAAA/PokemonGo-Map#727]
### Environment info
windows 
Installed version of Python:
2.7.12

appearantly lickitung couldn't be seen on the map. after it spawned. i tried to see where it is but with not success. at the end i just went out and wished for luck to find it with the 3 steps bug XD (found it :D)

that should be checked though

**Comment by JawnZ** [comment]
did you have an incense on? if you're using a dummy account for the map (which you should be) then sometimes your actual account will see things that the dummy account can't (such as with incense)

**Comment by medghaim** [comment]
`master` or `develop` branch?

**Comment by yarden32** [comment]
No incense.. just woke up and saw him

בתאריך 21 ביולי 2016 06:29,‏ "JawnZ" <notifications@github.com> כתב:

**Comment by yarden32** [comment]
Not sure what you mean. Im kinda new to all of this

בתאריך 21 ביולי 2016 06:40,‏ "Mohammad Edghaim" <notifications@github.com>
כתב:
