### ISSUE TITLE
Blurry Icons

### ISSUE THREAD

**Issue by rahatarmanahmed** [AHAAAAAAA/PokemonGo-Map#728]
![pokemap 2016-07-20 22-13-02](https://cloud.githubusercontent.com/assets/3174006/17010207/711beed6-4ec7-11e6-954a-f265080efb84.png)

I've only tested this in chrome, but the icons show up very blurry. This screenshot isn't the best quality but I promise they show up as blurry on my screen.

Running on commit bfa70a8388b5280ade3a849fdad9dd1262cc8771

**Comment by FrostTheFox** [comment]
The icons just kinda generally are blurry.

**Comment by rahatarmanahmed** [comment]
I don't know how the ones in `static/large-icons` are being used, but you could totally just nearest neighbor shrink (no antialiasing) those by 50% and only use those icons. If you still need the icons at a larger size, use CSS to display them larger w/ no antialiasing.

**Comment by JZ6** [comment]
the icons were shrunk because it was too big before, we ll have to look into this again
