### ISSUE TITLE
tried to install on vps and can't get acces into it 

### ISSUE THREAD

**Issue by ahmadihamid** [AHAAAAAAA/PokemonGo-Map#73]
GitHub issues are for bug reporting.  
For general support, and feature request, join [our discord server](https://discord.gg/kwAcr7e).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System: ubuntu 14.04 lts 64 bit

Installed version of Python: Python 2.7.6

### Steps to reproduce
1.follow readme
2. acces via internet [vps ip]:5000
3.

### What have you tried?
1.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by ryantheleach** [comment]
Flask by default isn't listening to external ports. In the example.py edit app.run to app.run(host="0.0.0.0", port=5000, debug=True, threaded=True)

Feel free to edit the port to 80 if you don't want to specify the port when connecting.

**Comment by DerScreever** [comment]
First i had the same problem then you. 
But as @ryantheleach told you need to edit the app.run.
This will be later done with a parameter at start.

**Comment by ahmadihamid** [comment]
thanks for fast respond, it works!
