### ISSUE TITLE
cant view map on iphone

### ISSUE THREAD

**Issue by coreyrules12** [AHAAAAAAA/PokemonGo-Map#730]
### Environment info
Operating System:windows 10

Installed version of Python:2.7

### Steps to reproduce
1.just try to go on the map it loads for a few seconds than theres an error
2.
3.

### What have you tried?
1.diffrent browser same result 

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by FrostTheFox** [comment]
What is the error? Is it only on iPhone? Have you tried it on another PC? What command are you running?

**Comment by coreyrules12** [comment]
the exact error is "oops something went wrong the page didnt load google maps correctly" no tried it on a android too same error dont have antother pc to try it on running this oneC:\Python27\python.exe example.py -u username-p password -l "my state" -st 700 -H 0.0.0.0

**Comment by Rhynocerous** [comment]
You likely need your own Google Maps API key.

**Comment by coreyrules12** [comment]
whats that

**Comment by FrostTheFox** [comment]
@coreyrules12 https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Google-Maps-API:-a-brief-guide-to-your-own-key

**Comment by coreyrules12** [comment]
thank you

**Comment by FrostTheFox** [comment]
Let me know when this issue is fixed so I can close it.

**Comment by coreyrules12** [comment]
its fixed

**Comment by FrostTheFox** [comment]
Great, glad we could solve your issue.
