### ISSUE TITLE
Scanner eventually stops looking for pokemon

### ISSUE THREAD

**Issue by Bakies** [AHAAAAAAA/PokemonGo-Map#733]
it just sits there running the flask server, no errors it said Getting all pokemon or something then just sat there, the only other log was the http hits.

on dev branch
running Ubuntu 14.04.4
commit 148f1a7a564e86d3bcd1ac1d078524aef29af721

**Comment by dhirnitish** [comment]
Yeah i agree to it. It starts around the lat and lng specified and starts to go away and stop looking gradually around that point.

**Comment by Bakies** [comment]
log looks like this:
https://gist.github.com/Bakies/99cb5a923384c42f650b21472f0f0e6c

**Comment by dhirnitish** [comment]
I am running a cron to solve this problem. You don't need to clear the database as well. Simply stop the command and rerun again and its good. 

Fine solution for right now!

**Comment by Bakies** [comment]
Im going to close this, I think it was fixed at some point
