### ISSUE TITLE
Wrong username/password

### ISSUE THREAD

**Issue by tedlasai** [AHAAAAAAA/PokemonGo-Map#734]
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discord.gg/Kzp4yky).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info MAC OSX 10.115
Operating System:

Installed version of Python: 2.7

### Steps to reproduce
1.  I ran this : python example.py -a ptc - u ****** -p ****** -l "Times Square" - st 50
2. I know the username and password are correct

### What have you tried?
1.different browser
2. Google account and ptc account

### Logs or other output that would be helpful

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "example.py", line 581, in main
    api_endpoint, access_token, profile_response = login(args)
  File "example.py", line 92, in memoizer
    cache[key] = obj(*args, **kwargs)
  File "example.py", line 516, in login
    raise Exception('[-] Wrong username/password')
Exception: [-] Wrong username/password

**Comment by rdamron** [comment]
This is likely an issue with the API and nothing to do with the app. Also you are using the outdated master branch.

**Comment by tedlasai** [comment]
How do I fix this issue with the API? I just switched to a newer version. DerScreevers branch. Please recommend which branch to use.

**Comment by Bakies** [comment]
you should be using the develop branch, double check your username and passwords, username is not your email if you are using that

**Comment by tedlasai** [comment]
where is the develop branch link?

**Comment by tedlasai** [comment]
Can someone give me the exact link from where to download it?

**Comment by Bakies** [comment]
green button on this page: https://github.com/AHAAAAAAA/PokemonGo-Map/tree/develop

**Comment by sahilshekhawat** [comment]
Here you go: https://github.com/AHAAAAAAA/PokemonGo-Map/tree/develop
its the develop branch. you can download via "Download zip" on the right hand side.

**Comment by medghaim** [comment]
Please use the `develop` branch, as others have stated. Closing issue. Please feel free to open a new one if you have difficulties running everything in the new branch.
