### ISSUE TITLE
Accepting credentials and other parameters from web page

### ISSUE THREAD

**Issue by ikhere** [AHAAAAAAA/PokemonGo-Map#737]
We should have means of accepting credentials and other configuration related parameters through a web page.

**Comment by Bakies** [comment]
this looks like it is in the works on the dev branch

**Comment by ikhere** [comment]
Didn't find any enhancement for that. So thought of adding.

**Comment by ikhere** [comment]
:thought_balloon:  Not sure why this was marked as closed though.

**Comment by FrostTheFox** [comment]
It's something we might be doing in the future.

**Comment by MonkeyLeeT** [comment]
Feel free to suggest this again the future. Cleaning issues for now.
