### ISSUE TITLE
pokemon not display anymore after the server running for  a long while 

### ISSUE THREAD

**Issue by actondong** [AHAAAAAAA/PokemonGo-Map#742]
This issue is very certain. I have met with it three times.

I deployed the app on heroku. Everything works well at beginning. Even though the server go idle, when new request come, it wake up and work well.

The problem is, after a while I didn't use the server, it could not display any pokemon.  Can only show the map. I can see the debugging info of looping through steps, and even search for pokemon in certain location. BUT, no pokemon is displayed. 

I am not even sure whether this is a backend issue or front-end issue.
This could only be solved by restart the server.
Anybody have idea about why this happening?

**Comment by Ayysir** [comment]
im having same issue, had to set a crontab on my server to push a empty commit for auto deploy to proc..... terrible circumvent though

**Comment by Bakies** [comment]
Dupe? #733 
I think you are talking about this issue.
