### ISSUE TITLE
Still can't start on Windows

### ISSUE THREAD

**Issue by NickRimmer** [AHAAAAAAA/PokemonGo-Map#743]
Last issue in master branch still actual in develop branch (#311)

### Environment info
Operating System:
Windows 10

Installed version of Python:
Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)] on win32

### Steps to reproduce
1. git clone -b develop https://github.com/AHAAAAAAA/PokemonGo-Map.git
2. pip install --upgrade -r requirements.txt
3. python runserver.py -a ptc -u *** -p *** -l "NY" -st 5

### What have you tried?
1. Start with admin rights (https://github.com/AHAAAAAAA/PokemonGo-Map/issues/311#issuecomment-233596525)
2. "pip uninstall -r requirements.txt" and "pip install -r requirements.txt"
3.  Copying "c:\Python27\Lib\site-packages\Cryptodome\Math\mpir.dll" to "c:\Python27\" folder. (https://github.com/AHAAAAAAA/PokemonGo-Map/issues/311#issuecomment-233755212)

### Logs or other output that would be helpful
>C:\Users\xan\Documents\pok\PokemonGo-Map>python runserver.py -a ptc -u *** -p *** -l "NY" -st 5
Traceback (most recent call last):
  File "runserver.py", line 12, in <module>
    from pogom.search import search_loop
  File "C:\Users\xan\Documents\pok\PokemonGo-Map\pogom\search.py", line 7, in <module>
    from pgoapi import PGoApi
  File "C:\Users\xan\Documents\pok\PokemonGo-Map\pogom\pgoapi\__init__.py", line 1, in <module>
    from pgoapi      import *
  File "C:\Users\xan\Documents\pok\PokemonGo-Map\pogom\pgoapi\pgoapi.py", line 34, in <module>
    from auth_google import AuthGoogle
  File "C:\Users\xan\Documents\pok\PokemonGo-Map\pogom\pgoapi\auth_google.py", line 29, in <module>
    from gpsoauth import perform_master_login, perform_oauth
  File "C:\Python27\lib\site-packages\gpsoauth\__init__.py", line 4, in <module>
    from . import google
  File "C:\Python27\lib\site-packages\gpsoauth\google.py", line 4, in <module>
    from Cryptodome.PublicKey import RSA
  File "C:\Python27\lib\site-packages\Cryptodome\PublicKey\RSA.py", line 83, in <module>
    from Cryptodome.Math.Numbers import Integer
  File "C:\Python27\lib\site-packages\Cryptodome\Math\Numbers.py", line 42, in <module>
    from Cryptodome.Math._Numbers_gmp import Integer
  File "C:\Python27\lib\site-packages\Cryptodome\Math\_Numbers_gmp.py", line 155, in <module>
    _gmp.mpz_init = lib.__gmpz_init
  File "C:\Python27\lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "C:\Python27\lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function '__gmpz_init' not found

"pip list" command result (https://github.com/AHAAAAAAA/PokemonGo-Map/issues/311#issuecomment-233592661)
>click (6.6)
coverage (4.1)
coveralls (1.1)
docopt (0.6.2)
Flask (0.11.1)
Flask-GoogleMaps (0.2.0)
future (0.15.2)
geopy (1.11.0)
gpsoauth (0.3.0)
itsdangerous (0.24)
Jinja2 (2.8)
MarkupSafe (0.23)
peewee (2.8.1)
pip (8.1.2)
protobuf (2.6.1)
protobuf-to-dict (0.1.0)
pycryptodomex (3.4.2)
requests (2.10.0)
s2sphere (0.2.4)
setuptools (24.2.0)
Werkzeug (0.11.10)
wheel (0.29.0)

**Comment by Bakies** [comment]
password visible, you should edit that

**Comment by NickRimmer** [comment]
Already (=

**Comment by arpsmack** [comment]
Hey, I discovered on my Windows 10 machine that python was finding a lib named "gmp" instead of the MPIR library.  `C:\Python27\Lib\site-packages\Cryptodome\Math\_Numbers_gmp.py` tries to load "gmp" first, and only loads MPIR if that fails.

If you go into that file and modify it so it loads MPIR instead (I just added a "raise OSError" on line 99, right at the start of the try block), it works.

**Comment by Fly33** [comment]
In addition on win32 you should add the following lines below:
    if bits.startswith("64") and linkage.startswith("Win"):
        # MPIR uses unsigned long long where GMP uses unsigned long
        # (LLP64 vs LP64)
        gmp_defs = "typedef unsigned long long UNIX_ULONG;" + gmp_defs_common
        c_ulong = c_ulonglong
+    else:
+        gmp_defs = gmp_defs_common
