### ISSUE TITLE
No Pokemon or Map Visible after Scipt Completes

### ISSUE THREAD

**Issue by rishabhbanga** [AHAAAAAAA/PokemonGo-Map#748]
Although I do not get any error while running the script, but once the script completes the search, the localhost site after refreshing (to display the search results) first showed :

XML Parsing Error: unexpected parser state 
Location: jar:file:///C:/xyz/browser/omni.ja!/chrome/browser/content/browser/aboutNetError.xhtml Line Number 537, Column 68:
        <div id="ed_connectionFailure">&connectionFailure.longDesc;</div>
-------------------------------------------------------------------^

and after refreshing again :

Shows Unable to connect

Operating System: Windows 7

Installed version of Python: Python 2.7.12

### Steps to reproduce
This is the Script I'm running C:\Python27\python example.py -a ptc -u XXXX -p XXXX -l "28.63028 77.36779" -st 10

**Comment by rishabhbanga** [comment]
Note: According to the solution given in #568 and a couple of other issues I read through, issue might be with me using the Master Branch instead of the Developer branch. 

Will try to use that and update if issue still persists.

**Comment by medghaim** [comment]
Please use the `developer` branch and report back with results.

**Comment by rishabhbanga** [comment]
@medghaim Didn't need to use the `developer` branch. It was an issue with Firewall settings.
