### ISSUE TITLE
Pokemon not being removed

### ISSUE THREAD

**Issue by Justinian6** [AHAAAAAAA/PokemonGo-Map#752]
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discord.gg/Kzp4yky).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System: Win10

Installed version of Python: 2.7.9

### Steps to reproduce
1. Run server
2. Wait for a pokemon to expire

### What have you tried?
1. Messing with the ar setting

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

No errors.... But once a Pokemon hits gone the browser never refreshes to remove it, I have to do it myself

**Comment by Xaldeon** [comment]
Pokemon remaining time shows as "(Expired)". You need to manually refresh the site to get rid of them.

**Comment by Bakies** [comment]
Dupe #714

**Comment by SeeingBlue** [comment]
#714 was closed by @DerScreever but this is still an issue.

**Comment by Bakies** [comment]
Not sure why #714 was closed, #700 may be related as well

**Comment by Justinian6** [comment]
@sykhro This wasn't solved so not sure why it was marked closed

**Comment by Bakies** [comment]
this is solved on the dev branch from what im aware

**Comment by Justinian6** [comment]
Oh ok great... Sorry bout that

**Comment by Bakies** [comment]
Just pulled and made sure, it is fixed
