### ISSUE TITLE
Hello, who made a map, and can help me find a Pokemon, I would say the coordinates of where to find them, thank you very much.

### ISSUE THREAD

**Issue by FlyVik** [AHAAAAAAA/PokemonGo-Map#753]
Hello, who made a map, and can help me find a Pokemon, I would say the coordinates of where to find them, thank you very much.

**Comment by hhu94** [comment]
Why are issue posts like this not closed / deleted right away?

**Comment by FlyVik** [comment]
https://www.google.com.ua/maps/@49.0284344,24.3702885,15z?hl=ru

**Comment by MRokas** [comment]
@FlyVik - there's no need for that, this setup automatically finds any pokemon spawns!

**Comment by FlyVik** [comment]
I put on windows and it is not included

**Comment by IDSninja** [comment]
click on the pokemon, then click on"get directions" 

youll see coordinates in the url

**Comment by FlyVik** [comment]
I do not poluchayetsya that in order to make Python 2.7, the Where pop, I'm not understand
