### ISSUE TITLE
Not able to load map in either develop or master branch

### ISSUE THREAD

**Issue by quoder** [AHAAAAAAA/PokemonGo-Map#759]
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discord.gg/Kzp4yky).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:
Ubuntu 16.04
Installed version of Python:
2.7.12

### Steps to reproduce
1. python runserver.py -a ptc -u ***** -p **** -l "***** *****" -st 10  (develop branch)
2. python example.py -a ptc -u ***** -p **** -l "***** *****" -st 10  (master branch)

### What have you tried?
1. Retried bunch of times

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).
In Develop branch:

2016-07-21 11:36:37,165 [  runserver] [   INFO] Parsed location is: ****/****/**** (lat/lng/alt)
2016-07-21 11:36:37,165 [     search] [   INFO] Attempting login to Pokemon Go.
2016-07-21 11:36:37,167 [   auth_ptc] [   INFO] PTC login for: *****
Traceback (most recent call last):
  File "runserver.py", line 76, in <module>
    config['GMAPS_KEY'] = load_credentials(os.path.dirname(os.path.realpath(__file__)))['gmaps_key']
  File "/home/*****/Downloads/PokemonGo-Map-develop/pogom/utils.py", line 88, in load_credentials
    with open(filepath+os.path.sep+'credentials.json') as file:
IOError: [Errno 2] No such file or directory: '/home/*****/Downloads/PokemonGo-Map-develop/credentials.json'

In Master branch:
All I get is 'Flask Pokemon Go Full Map Example' with a white background and the terminal keep on looping from 0 to 100%. After 100%, it still won't load and again keeps on looping

**Comment by Ayysir** [comment]
https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Google-Maps-API:-a-brief-guide-to-your-own-key

**Comment by quoder** [comment]
Thanks, now at least the map is loading.
