### ISSUE TITLE
--ignore not working with multiple arguments

### ISSUE THREAD

**Issue by stanleykylee** [AHAAAAAAA/PokemonGo-Map#76]
The documentation isn't available yet, but looking at the code, it should be ignoring zubats if i just use "-i zubat". However, they still show up?

**Comment by sykhro** [comment]
weird, just tested it and it seemed to work. be sure to clean your cache.

**Comment by sykhro** [comment]
Can confirm this works, not a bug. Will keep open to give support

**Comment by marauder37** [comment]
Yes wfm

**Comment by stanleykylee** [comment]
Pulled latest and still not working. Running following command:

python example.py -u user -p pass -l "location" -st 4 -i Zubat,Drowsee,Pidgey

**Comment by sykhro** [comment]
Multiple arguments don't seem to work

**Comment by marauder37** [comment]
So I just tested with `-i Zubat,owsee,Pidgey,Doduo,Poliwag,Poliwhirl` and each time I added a name it vanished from the map

**Comment by sykhro** [comment]
I fell into the caching issue myself. It works as it should, apologies

**Comment by stanleykylee** [comment]
OK, how do I clear cache? I'm running on mac and terminated the terminal and now flask is complaining that the port is in use. Going to restart for now, but is there another way to clear cache?

**Comment by sykhro** [comment]
You have to clear the cache in your browser. Refer to docs or do it from the options of your browser

**Comment by stanleykylee** [comment]
Cleared cache and still no luck. Python 2.7.11 is no good?

**Comment by sykhro** [comment]
Are you using the latest master?

**Comment by stanleykylee** [comment]
Yes, I just pulled again - 4ece37e

**Comment by stanleykylee** [comment]
ok, never mind, someone kill me now. the latest one is working. not sure what changed but one thing i had wrong for sure was spelling of drowzee.
