### ISSUE TITLE
Auto Refresh seems to remove every Pokemon on each refresh cycle

### ISSUE THREAD

**Issue by UzEE** [AHAAAAAAA/PokemonGo-Map#762]
The current JavaScript implementation of Auto Refresh seems to clear out every previous pokemon on the map instead of just the expired ones. Basically, the following expressions always evaluates to true:

```js
$.each(markers, function(i, item){
  if (item.disapear <= lastStamp - (dObj.getTimezoneOffset() * 60000))        
    item.m.setMap(null);        
  });
```

My guess is that it is because of the timezone offsets (I'm in GMT+0500). I'd submit a pull request myself but I'm still not familiar with the system well enough. If it doesn't get addressed by tonight, maybe I'll do it and submit a PR.

### Environment info
Operating System:
**Ubuntu 14.04.3 LTS**

Installed version of Python:
**Python 2.7.6**

### Steps to reproduce
1. Run the server.
2. Open the web browser.
3. The previous Pokemon would always disappear when getting new Pokemon regardless of their expiry time.

### What have you tried?
1. Changing the `-ar` interval has no affect.

**Comment by codeplexnl** [comment]
I also have encountered this problem.

When looking at the requests made to get the pokemon is see the frist request is to "/pokemons/0" and all requests after have what is assume the timestamp. However they return an empty array maybe this is the problem?

I don't have time to look at it right now. but i hope this helps.

**Comment by joker8656** [comment]
I can confirm the same issue.

**Comment by UzEE** [comment]
@codeplexnl The JSON output for subsequent requests does often have Pokemon in them. The problem is that every other Pokemon previously on the map gets removed and only the current ones returned in the request are plotted.

**Comment by hhu94** [comment]
This part of the code is being reworked. See #732

**Comment by UzEE** [comment]
Yes. #751 also seems to be a possible fix.

**Comment by hhu94** [comment]
I don't like #751. I think we should wait till @invisiblek finishes his fix https://github.com/invisiblek/PokemonGo-Map/commit/9ef49cf327967ca7793be93242570a33ad2da14d

**Comment by codeplexnl** [comment]
@UzEE  Ah is see now :D. ill take a longer look next time :)

**Comment by joker8656** [comment]
#732 works.

**Comment by leTokki** [comment]
Changing
`if (item.disapear <= lastStamp - (dObj.getTimezoneOffset() * 60000))`
to
`if (item.disapear <= lastStamp + (dObj.getTimezoneOffset() * 60000))`

fixed it for me

**Comment by flexusjan** [comment]
@leTokki Yes this fix the problem of auto refresh removing all pokemons. But now, the auto refresh doesn't remove expired pokemons. (manual refresh still work.)

**Comment by MonjoNL** [comment]
getTimezoneOffset() returns the offset in minutes in JavaScript not milliseconds.

So the correct fix is to change the line to if (item.disapear <= lastStamp - (dObj.getTimezoneOffset() * 60))

I will try to change it.

**Comment by Frozen-byte** [comment]
For me it's only working, when I remove the multiplication completely.

**Comment by Silvikk** [comment]
@MonjoNL  
Where should I make this changes? Can't find map.js

**Comment by MonjoNL** [comment]
@Silvikk I already submitted it but it has to be approved.
But if you want to fix your copy already, the file is in the static folder.

**Comment by Silvikk** [comment]
@MonjoNL Yeah, I'm in this folder and there are nothing like map.js, just jquery.js

**Comment by MonjoNL** [comment]
@Silvikk In that case you are using the master branch and not the develop branch

**Comment by hughpearse** [comment]
./static/map.js
if (item.disapear <= lastStamp){
            item.m.setMap(null);
