### ISSUE TITLE
Is it possible to set location to current position of device?

### ISSUE THREAD

**Issue by ddiesenreither** [AHAAAAAAA/PokemonGo-Map#764]
Hi guys,

is there a way to give the script the current lat, lng from browser/device?

Greetings

**Comment by Ayysir** [comment]
https://github.com/AHAAAAAAA/PokemonGo-Map/pull/725

**Comment by ddiesenreither** [comment]
so if i run the develop branch there is the feature with the current location?

**Comment by MonkeyLeeT** [comment]
No, not yet. But ETA in next 24 hours.
