### ISSUE TITLE
Intallation on Windows 10 64 bit didnt work

### ISSUE THREAD

**Issue by rewop777** [AHAAAAAAA/PokemonGo-Map#766]
### Environment info
Operating System: Windows 10

Installed version of Python: 2.7.12

### Steps to reproduce
1. Intalled Python
2.Ran Pip
3. Tried to run the cmd promts pip install -r requirements.txt
4. Get reply in window that 'pip' is not a recognized as an internal or external command, operable program or batch file

### What have you tried?
1. I know this is probably childs play for someone but i dont know what to do

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by lnmtriet93** [comment]
Instead of run "pip install -r requirements.txt" command, you can also try "C:\Python27\Scripts\pip install -r requirements.txt"

**Comment by emhollowed** [comment]
I had the same problem and was able to get the install to run by copying the requirements.txt (inside the PokemonGo-Map-master zip) into "C:\Python27\Scripts" and then navigating to that folder from the command line and running "pip install -r requirements.txt".

**Comment by abberger1** [comment]
you can do "python -m pip install -r requirements.txt" if python is in your default path

**Comment by klinxe** [comment]
Add the paths to .exe for both pip and python in your system properties (Windows is a dick). It works for me.

**Comment by j0hnsa** [comment]
Lookup for setting environment variables
