### ISSUE TITLE
Pokemon go location issue. please help! Thank you.

### ISSUE THREAD

**Issue by samerj29** [AHAAAAAAA/PokemonGo-Map#773]
Hello i am getting a location error when i run the script. I have tried a lot of different combinations and nothing seems to work. Please Help. 

### Environment info
Operating System:
 win 7

Installed version of Python: 
2.7.12

### Steps to reproduce
1 .follow the installation description
2. python example.py -a ptc -u ******* -p ******* -1 "Toronto, Ontario" -st 10
3.

### What have you tried?
1. I have tried "Toronto Ontario" , "Toronto Canada" , "Toronto" and coordinates.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

example.py: error: argument -1/--location is required

**Comment by MikeDX** [comment]
You need to use -l not -1

Of course you could also use --location instead of -l, like the error says

**Comment by samerj29** [comment]
Thank you very much. As you can tell i am a complete noob in this sort of stuff. It works. IF you ever need construction advice, im your guy. Thanks again
