### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by Tydelike** [AHAAAAAAA/PokemonGo-Map#775]
Hi there I'm sure I'm just being an idiot but I'm on Windows 7 64bit and followed the steps:

1 .follow the installation description
2. python example.py -a ptc -u ***** -p **** -l "33.7749 20.1224" -st 100

The error I get is:
File "example.py", line 103
print '[-] {}'.format(message)

I have tried using just a city/town name but always get the same result :)

Any advice will be greatly appreciated!

**Comment by Sejadis** [comment]
you are using the old master branch which is not supported anymore 
you should switch to the develop branch

**Comment by Tydelike** [comment]
Do I then run it using the runserver.py instead?

**Comment by Sejadis** [comment]
yes commands should be the same although im not sure that all prevoius existing flags are implements yet

**Comment by DerScreever** [comment]
most of the previous should work again.

**Comment by DeadK** [comment]
Sorry  i cant find runserver.py did i miss anything ?

**Comment by Sejadis** [comment]
> you are using the old master branch which is not supported anymore 
you should switch to the develop branch

**Comment by DeadK** [comment]
where do i find that sorry i just joined community

**Comment by DeadK** [comment]
nvm found it..
 lets hope it works.
