### ISSUE TITLE
Reddit description and maybe new default?

### ISSUE THREAD

**Issue by Sejadis** [AHAAAAAAA/PokemonGo-Map#778]
Many people that need help still use the master branch
so maybe it would be good to make the develop branch the new default?
also the reddit page should be edited as it still tells people to download the master branch

**Comment by Galtwise** [comment]
Develop branch will be merged once it's decided it's stable enough

**Comment by DerScreever** [comment]
like the poster before me told.

**Comment by Sejadis** [comment]
ok so no setting the develop as default

but at least change the reddit post to tell people to download the develop branch?
i mean the questions pop up continuously and the answer is always "switch to develop branch"
