### ISSUE TITLE
Encounters exception on finding Nidoran (Male & Female)

### ISSUE THREAD

**Issue by pranavperfect** [AHAAAAAAA/PokemonGo-Map#779]
### Environment info
Operating System: Windows 10

Installed version of Python: 2.7.10

### Steps to reproduce
1. If Nidoran male of female is found, an exception occurs as their name has a symbol in their name. I modified the script to print name on command prompt.

### What have you tried?
1. Original script does not cause any issues.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by benemorius** [comment]
Please state which commit you're running and post the full traceback.

**Comment by pranavperfect** [comment]
I believe i'm using the master commit.
The error is as mentioned above about unicode male and female symbols in the name of Nidoran.
I modified the example.py script to only display name of pokemon captured on command prompt. Which led to this exception. The original script does not have this issue.
