### ISSUE TITLE
Google account login

### ISSUE THREAD

**Issue by Trozz** [AHAAAAAAA/PokemonGo-Map#78]
ability to login with Google account rather than Pokemon account.

e.g. https://github.com/tejado/pokemongo-api-demo

**Comment by DerScreever** [comment]
already posted as pull request
https://github.com/AHAAAAAAA/PokemonGo-Map/pull/43/files

**Comment by Trozz** [comment]
Didn't see it before I opened issue, it appears that this is having the same issue as the test that I was performing, closing this issue.
