### ISSUE TITLE
Technically, would it be possible to change the location by URL parameter?

### ISSUE THREAD

**Issue by friiks** [AHAAAAAAA/PokemonGo-Map#781]
I've installed the map and although it works it would be nice to know if it's possible to modify the code so it would accept URL parameter or a point on the map as a location for which to show the pokemon so multiple users could view different locations?
Or is the PTC username/pass required to emulate a single user just "walking" around making multiple locations impossible?

**Comment by SOLiNARY** [comment]
If you are using master branch, then add this code:
`
@app.route('/set_loc')
def set_loc():
    name = flask.request.args.get('name', '')
    if name == "":
        print('[-] Invalid location: %s' % name)
    else:
        print('[+] Jumped to location: %s' % name)
        retrying_set_location(name)
        return 'ok'
`
to the end of example.py.

Then use
**site.com/set_loc?name=baku**
or
**site.com/set_loc?name=45.123,56.789**

P.S. Spaces in name do not work.
