### ISSUE TITLE
pokemonGo-Map for Android

### ISSUE THREAD

**Issue by GozhevDenis** [AHAAAAAAA/PokemonGo-Map#786]
Can I install pokemonGo on my phone(android).

**Comment by ditchfieldcaleb** [comment]
It works decently well if you just add the site to your home screen.

**Comment by medghaim** [comment]
@omkarmoghe is working on porting the project with a few contributors over at https://github.com/omkarmoghe/Pokemap

**Comment by DerScreever** [comment]
or use QPython.
