### ISSUE TITLE
Are the timestamps/labels still problematic? 

### ISSUE THREAD

**Issue by wcastello** [AHAAAAAAA/PokemonGo-Map#788]
Can anyone confirm the timestamps/labels are still wrong? I thought someone else had fixed this in another merge while I was sleeping with a similar changes and dumped mine but now I'm seeing the countdowns still zeroed and the times are still off by a bunch of hours.

**Comment by frdmn** [comment]
Works fine for me: 
![bildschirmfoto 2016-07-21 um 10 56 44](https://cloud.githubusercontent.com/assets/944459/17016987/d567d796-4f31-11e6-96f2-098a272192b5.png)

**Comment by DerScreever** [comment]
they work.

**Comment by wcastello** [comment]
That's weird. 

<img width="1119" alt="screen shot 2016-07-21 at 1 57 37 am" src="https://cloud.githubusercontent.com/assets/3504711/17017044/91a4497c-4ee6-11e6-9e72-0b7b8f65b4b1.png">

and it's 1:58am here.

**Comment by wcastello** [comment]
Oh, forget it, now they're showing, no idea why they weren't though.

**Comment by MikeDX** [comment]
Probably a cached map.js
