### ISSUE TITLE
Installation went fine. But example.py broke.

### ISSUE THREAD

**Issue by feralfenrir** [AHAAAAAAA/PokemonGo-Map#789]
### Environment info
Operating System:
Windows 10 x64

Installed version of Python:
2.7.12

### Steps to reproduce
1. Installed Python and intsalled pip with get-pip.py
2. Run the "pip install -r requirements.txt" command. It installed the requirements. The output if I run this again now is below.
3. python example.py -a ptc -u *** -p *** -l "12.975354 77.617149" -st 10

### What have you tried?
1. I've tried feeding locations like New York, etc.

### Logs or other output that would be helpful
>pip install -r requirements.txt
Requirement already satisfied (use --upgrade to upgrade): geopy==1.11.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): protobuf==2.6.1 in c:\python27\lib\site-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): requests==2.10.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): flask-googlemaps==0.2.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): s2sphere==0.2.4 in c:\python27\lib\site-packages (from -r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): flask==0.11.1 in c:\python27\lib\site-packages (from -r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): gpsoauth==0.3.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): coveralls==1.1 in c:\python27\lib\site-packages (from -r requirements.txt (line 8))
Requirement already satisfied (use --upgrade to upgrade): werkzeug==0.11.10 in c:\python27\lib\site-packages (from -r requirements.txt (line 9))
Requirement already satisfied (use --upgrade to upgrade): setuptools in c:\python27\lib\site-packages (from protobuf==2.6.1->-r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): future in c:\python27\lib\site-packages (from s2sphere==0.2.4->-r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): itsdangerous>=0.21 in c:\python27\lib\site-packages (from flask==0.11.1->-r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): click>=2.0 in c:\python27\lib\site-packages (from flask==0.11.1->-r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): Jinja2>=2.4 in c:\python27\lib\site-packages (from flask==0.11.1->-r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): pycryptodomex>=3.0 in c:\python27\lib\site-packages (from gpsoauth==0.3.0->-r requirements.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): coverage>=3.6 in c:\python27\lib\site-packages (from coveralls==1.1->-r requirements.txt (line 8))
Requirement already satisfied (use --upgrade to upgrade): docopt>=0.6.1 in c:\python27\lib\site-packages (from coveralls==1.1->-r requirements.txt (line 8))
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe in c:\python27\lib\site-packages (from Jinja2>=2.4->flask==0.11.1->-r requirements.txt (line 6))

Output from example.py:

Traceback (most recent call last):
  File "example.py", line 26, in <module>
    from gpsoauth import perform_master_login, perform_oauth
  File "C:\Python27\lib\site-packages\gpsoauth\__init__.py", line 4, in <module>
    from . import google
  File "C:\Python27\lib\site-packages\gpsoauth\google.py", line 4, in <module>
    from Cryptodome.PublicKey import RSA
  File "C:\Python27\lib\site-packages\Cryptodome\PublicKey\RSA.py", line 83, in <module>
    from Cryptodome.Math.Numbers import Integer
  File "C:\Python27\lib\site-packages\Cryptodome\Math\Numbers.py", line 42, in <module>
    from Cryptodome.Math._Numbers_gmp import Integer
  File "C:\Python27\lib\site-packages\Cryptodome\Math\_Numbers_gmp.py", line 155, in <module>
    _gmp.mpz_init = lib.__gmpz_init
  File "C:\Python27\lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "C:\Python27\lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function '__gmpz_init' not found

**Comment by frdmn** [comment]
Use `develop` branch instead of `master` please.

**Comment by DerScreever** [comment]
we dropped support for the master branch. use develop branch, until we merge it to the master branch.

**Comment by feralfenrir** [comment]
I was able to get it work by commenting out the import gpsoauth line, bt thanks!
