### ISSUE TITLE
Discussion

### ISSUE THREAD

**Issue by ronakjain90** [AHAAAAAAA/PokemonGo-Map#791]
Hello.

I'm Ronak, a Ruby Developer, working on PokemonGo-Map since I found it very interesting. This project got me started with Python in just a day. I might differ on my opinion, but I find that the scope of this project is very limited to developers/programmers, who are familiar with command line prompt and tedious installation process.

I want to take this to the next level by creating a complete Cloud Based Application. I have following feature in my mind. Some are completed, some are yet to be done. I invite collaboration.

- [ ]  User Enters his Login Details, we will use that to generate Access-Token. Store the `access_token`  in DB/Key Value Store ( High Availability). Care needs to be taken since the user will be supplying his real data, and there needs to be no impressions in server logs.
- [x] Fetching all the available Pokemon's in Parallel, right now it's sequentially done which is very slow. I have implemented multithreading. Now responses just takes 2-3 seconds.
- [x] Caching the Pokemon's available, so that if we have too many users at a given location we can just fetch them from our cache. Caching can be implemented using any framework, that would auto purge the expired Pokemon's. I have implemented caching using MongoDB with TTL feature.
- [ ] Serving the cached Pokemon's first using Geospatial Query. Simultaneously triggering a background thread for every request, to update the Pokemon's.
- [ ] I find that Flask is extremely slow for production use case. It would be better to switch to something else. A Framework that can handle extremely huge load. Pythonist can guide?
- [ ] Maybe a Mobile App to consume the JSON data.

If you find this Idea/Concept Interesting, I'm inviting collaborators to reach the milestone.

https://github.com/ronakjain90/PokemonGo-Map

PS: I'm just 1 day into Python, apologies for wrong coding style/ standard.

**Comment by DerScreever** [comment]
" I might differ on my opinion, but I find that the scope of this project is very limited to developers/programmers, who are familiar with command line prompt and tedious installation process." 

we change this already. later you can use the complete functions of our projekt with the ui. no need of commands in the feature.

**Comment by haagiboy88** [comment]
I like your idea with paralell, multithreading and caching of Pokemon! Are you in our discord chat?

**Comment by rushingfitness** [comment]
Rails dev here, first time with Python as well. I was actually thinking about porting this to Rails for a ruby version for those who don't code in Py and just keeping up to date with PR's on this repo. 

I would also be pretty interested in having a global cache so you could not only see pokes near you, but anywhere in the map view.

**Comment by ronakjain90** [comment]
@haagiboy88 Well you can just clone my repository, I've implemented Parallel threads to find pokemons. and it's really fast, just takes up 3 seconds. I'm not on your discord chat. Please add me?

@rushingfitness I feel that there has been a lot of work done in Python, and porting will take ages. Hence i started learning python, ( Its not that bad I would say) I have finished to write good amount of code in a day. Caching is necessary if you plan to develop a web application, else we will literally choke our servers.

**Comment by rushingfitness** [comment]
@ronakjain90 I've already begun porting it over since there aren't too many files and it isn't fairly complex. If anything it'll be a good challenge ;)
It's similar to Ruby, but it's just not my thing and can code 10x faster in Ruby.

**Comment by ronakjain90** [comment]
@rushingfitness I agree. I took it as an opportunity to learn Python. Whats the link to the ruby port ?

**Comment by rushingfitness** [comment]
Not on github yet. Still porting on my dev. Actually going to sleep in a few (526am here) so won't be up for a while. Just thought I would mention it here while I remembered. Looking forward to seeing your work man, great progress so far!

**Comment by ronakjain90** [comment]
@DerScreever Will look forward to having a discussion with the project owner. @AHAAAAAAA
