### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in C:\Users\DeadK\AppData\Local\Temp\pip-build-r_q31ulv\wsgiref\

### ISSUE THREAD

**Issue by DeadK** [AHAAAAAAA/PokemonGo-Map#794]
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discord.gg/Kzp4yky).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System: Windows 10

Installed version of Python:
Python 3.5

### Steps to reproduce
1.pip install -r requirements.txt

### Logs or other output that would be helpful
Requirement already satisfied (use --upgrade to upgrade): Flask==0.11.1 in c:\users\deadk\appdata\local\programs\python\python35\lib\site-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): Jinja2==2.8 in c:\users\deadk\appdata\local\programs\python\python35\lib\site-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe==0.23 in c:\users\deadk\appdata\local\programs\python\python35\lib\site-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): Werkzeug==0.11.10 in c:\users\deadk\appdata\local\programs\python\python35\lib\site-packages (from -r requirements.txt (line 4))
Collecting argparse==1.2.1 (from -r requirements.txt (line 5))
  Using cached argparse-1.2.1.tar.gz
Requirement already satisfied (use --upgrade to upgrade): click==6.6 in c:\users\deadk\appdata\local\programs\python\python35\lib\site-packages (from -r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): itsdangerous==0.24 in c:\users\deadk\appdata\local\programs\python\python35\lib\site-packages (from -r requirements.txt (line 7))
Collecting peewee==2.8.1 (from -r requirements.txt (line 8))
  Using cached peewee-2.8.1.tar.gz
Collecting wsgiref==0.1.2 (from -r requirements.txt (line 9))
  Using cached wsgiref-0.1.2.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\DeadK\AppData\Local\Temp\pip-build-r_q31ulv\wsgiref\setup.py", line 5, in <module>
        import ez_setup
      File "c:\users\deadk\appdata\local\temp\pip-build-r_q31ulv\wsgiref\ez_setup\__init__.py", line 170
        print "Setuptools version",version,"or greater has been installed."
                                 ^
    SyntaxError: Missing parentheses in call to 'print'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\DeadK\AppData\Local\Temp\pip-build-r_q31ulv\wsgiref\

**Comment by haagiboy88** [comment]
Try python 2.7.x, but I think it should run fine on 3.5 as well now. Closing as this is not development related.

**Comment by DeadK** [comment]
so if it should work with 3.5 aswell then why wont it update ?

**Comment by DeadK** [comment]
Well turns out it works with Python 2.7.12 on windows 7 Thanks haagiboy88
