### ISSUE TITLE
Map marker.disapear and lastStamp are in Unix Epoch. No timezone calculation is necessary.

### ISSUE THREAD

**Issue by clbuttic** [AHAAAAAAA/PokemonGo-Map#795]
By doing a timezone calulation (subtracting Date.getTimezoneOffset() * 60000), lastStamp is adjusted to something way off, and the comparison is invalid. Any /pokemons updates to the map to someone in a TZ east of UTC will result in all pokemon markers being removed immediately, and west of UTC removed after a long time.

```
diff --git a/static/map.js b/static/map.js
index 22e3f52..104abb2 100644
--- a/static/map.js
+++ b/static/map.js
@@ -230,7 +230,7 @@ GetNewPokemons = function(stamp) {
     lastStamp = dObj.getTime();
 
     $.each(markers, function(i, item){
-        if (item.disapear <= lastStamp - (dObj.getTimezoneOffset() * 60000))
+        if (item.disapear <= lastStamp)
             item.m.setMap(null);
     });
 };
```

**Comment by DerScreever** [comment]
@clbuttic we are already working on a fix for this problem. just wait a bit.
