### ISSUE TITLE
Commands to run runserver.py

### ISSUE THREAD

**Issue by SPGxSimplicity** [AHAAAAAAA/PokemonGo-Map#796]
What commands do I use to run it from the developer version? it gives me error example.py was not found

**Comment by Sejadis** [comment]
well because there is none
you run the runserver.py

**Comment by SPGxSimplicity** [comment]
Yeah, I figured that out. still not loading up properly. 

File "runserver.py", line 82, in <module>
    config['GMAPS_KEY'] = load_credentials(os.path.dirname(os.path.realpath(__file__)))['gmaps_key']
  File "/Users/SimplyxTarek/Downloads/PokemonGo-Map-develop-2/pogom/utils.py", line 114, in load_credentials
    with open(filepath+os.path.sep+'credentials.json') as file:
IOError: [Errno 2] No such file or directory: '/Users/SimplyxTarek/Downloads/PokemonGo-Map-develop-2/credentials.json'

**Comment by medghaim** [comment]
Rename `credentials.example.json` to `credentials.json`, and input your google maps API key in there.
