### ISSUE TITLE
Map on Android not seen

### ISSUE THREAD

**Issue by crouch766** [AHAAAAAAA/PokemonGo-Map#798]
### Environment info
Operating System: Android
Installed version of Python: 2.7

### Steps to reproduce
1. Install the Develop Branch on my webserver
2. Open the webpage from android phone (tested with Chrome and Cyanogenmod Browser)
3. I can see only the Menu Bar and the Test Button, the "Map" is Blank
4. From my pc works fine

Below the screenshot of my browser phone
![15da2138-0756-418b-91dd-b14af651013f](https://cloud.githubusercontent.com/assets/6096879/17017423/9b680be0-4f33-11e6-8a4f-c2ddbc920042.jpg)

Thanks a lot for your work!

**Comment by rushingfitness** [comment]
@crouch766 if you can connect your phone to computer via USB, you should be able to do a JS console through Chrome and check to see if there are any JS errors. My money is there's something funky with the api + android

**Comment by crouch766** [comment]
Ok, i can do that in a two hours. Thanks for the support.

**Comment by dhirnitish** [comment]
Try this on your phone - http://developerscodex.com:5000/

**Comment by rushingfitness** [comment]
@dhirnitish yeah that works for me (Not OP). P.S. man you have a lot of pokes near you that are super rare where I live or have never seen!

**Comment by rushingfitness** [comment]
@dhirnitish well it did work. Now getting some js errors.

**Comment by dhirnitish** [comment]
@rushingfitness haha i am bored of seeing the same pokemons again and again. You can paste the js errors here.

**Comment by rushingfitness** [comment]
Doesn't seem to be there anymore. But it said that the maps api was not configured to work with your URL. But again, now it works fine, not sure what happened.

**Comment by crouch766** [comment]
Sorry, was my vpn that not works fine. I disconnect that and now work my site and and your @dhirnitish 

Thanks and sorry for my mistake
