### ISSUE TITLE
Unable to pass in a proxy address for the requests

### ISSUE THREAD

**Issue by PhantomBadger** [AHAAAAAAA/PokemonGo-Map#80]
Unable to run the example from behind a proxy, adding in support for this and a --proxy flag from the cmd line would be sufficient to provide support

**Comment by DerScreever** [comment]
normaly this should work. 
i run my server behind an proxy and all things work great.

**Comment by PhantomBadger** [comment]
I've gotten it working by editing the code to include a hardcoded proxy dictionary and passing it into the request and GoogleV3 calls, if there's a need for it I can clean it up and throw it up as a pull request with the aforementioned flag

**Comment by DerScreever** [comment]
yes please create a pull request with aditional proxy flag. 
then we can see if the owner wants to merge it or not.
