### ISSUE TITLE
Error starting server: Credentials.json file issue

### ISSUE THREAD

**Issue by pet90210** [AHAAAAAAA/PokemonGo-Map#800]
**Environment info**

**Operating System:**
Mac OSX 10.11.5

**Installed version of Python:**
Python 2.7.12

**Steps to reproduce**

i did everything as said above and it worked out great. Had some Xcode Issue first - but they are solved.
Now I'm trying to start the Server .

Logs

 python /Users/IrmischPhotography/Documents/Pokemon/example.py -a google -u *******@gmail.com -p ********* -l 37.315391 -8.795521  -st 10

Traceback (most recent call last):
  File "/Users/IrmischPhotography/Documents/Pokemon/example.py", line 41, in <module>
    with open('credentials.json') as file:
IOError: [Errno 2] No such file or directory: 'credentials.json'

The File 'credentials.json' is in the same location as the "example.py" file

Someone can help?

Thank you very much :)
Patrick

**Comment by DerScreever** [comment]
switch to develop branch pls....

**Comment by Zegorax** [comment]
You need to use the develop branch. The master branch is not working at the moment.

**Comment by pet90210** [comment]
Just downloaded it - Do I need to do the whole procedure another time?

Thanks!

**Comment by medghaim** [comment]
Please take support questions to https://discord.gg/nN44Z
