### ISSUE TITLE
    'No Google Maps Javascript API key entered. Please take a look at the wiki f or instructions on how to generate this key.')

### ISSUE THREAD

**Issue by DeadK** [AHAAAAAAA/PokemonGo-Map#802]
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discord.gg/Kzp4yky).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:
Windows 7
Installed version of Python:
2.7

### Steps to reproduce
1. C:\Users\DeadK\Desktop\PokemonGo-Map-develop>python runserver.py -a ptc -u ****** -p******* -l "19.11478,72.869805" -st 10

### What have you tried?
1. so it first said no such file as credential.json checked directory and remaned credential.examples.json
2. now it gives error as follows any advice? 
Content of credentail.json `{
	"gmaps_key" : ""
}`

### Logs or other output that would be helpful

2016-07-21 15:05:02,092 [  runserver] [   INFO] Parsed location is: 19.1148/72.8
698/0.0000 (lat/lng/alt)
2016-07-21 15:05:02,098 [     search] [   INFO] Attempting login to Pokemon Go.
2016-07-21 15:05:02,111 [   auth_ptc] [   INFO] PTC login for: ***********
Traceback (most recent call last):
  File "runserver.py", line 82, in <module>
    config['GMAPS_KEY'] = load_credentials(os.path.dirname(os.path.realpath(__fi
le__)))['gmaps_key']
  File "C:\Users\DeadK\Desktop\PokemonGo-Map-develop\pogom\utils.py", line 118,
in load_credentials
    'No Google Maps Javascript API key entered. Please take a look at the wiki f
or instructions on how to generate this key.')
pogom.exceptions.APIKeyException: No Google Maps Javascript API key entered. Ple
ase take a look at the wiki for instructions on how to generate this key.

**Comment by betrisey** [comment]
You have to get an API key
explained here: https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Google-Maps-API:-a-brief-guide-to-your-own-key
and put into in the credential.json file { "gmaps_key" : "XXXXXXXXXX" }

**Comment by medghaim** [comment]
The answer is in your title :(

The wiki is linked above. Do the above and you're set.
