### ISSUE TITLE
I can't do pip install -r requirements.txt

### ISSUE THREAD

**Issue by ProRobins** [AHAAAAAAA/PokemonGo-Map#803]
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

**Comment by DeadK** [comment]
did you change directory to the correct path?

**Comment by ProRobins** [comment]
I think

**Comment by ProRobins** [comment]
no becasue it won't let me

**Comment by ProRobins** [comment]
how do i do that?

**Comment by DeadK** [comment]
do something go to the folder  press shift plus right click and then chose open command prompt here

**Comment by ProRobins** [comment]
yeah im there

**Comment by ProRobins** [comment]
but how do i cd

**Comment by mherceg** [comment]
Can you execute command "dir" and let us know what it outputs?

**Comment by ProRobins** [comment]
?

**Comment by mherceg** [comment]
Just type in 
dir
In your command prompt and paste the output here

**Comment by ProRobins** [comment]
07/21/2016  12:41 AM    <DIR>          .
07/21/2016  12:41 AM    <DIR>          ..
07/21/2016  12:41 AM    <DIR>          .github
07/21/2016  12:41 AM                11 .gitignore
07/21/2016  12:41 AM               151 .travis.yml
07/21/2016  12:41 AM               368 credentials.json
07/21/2016  12:41 AM    <DIR>          Easy Setup
07/21/2016  12:41 AM            29,233 example.py
07/21/2016  12:41 AM             1,081 LICENSE
07/21/2016  12:41 AM    <DIR>          locales
07/21/2016  12:41 AM             5,905 pokemon.proto
07/21/2016  12:41 AM            78,759 pokemon_pb2.py
07/21/2016  12:41 AM             1,526 README.md
07/21/2016  12:41 AM               149 requirements.txt
07/21/2016  12:41 AM    <DIR>          static
07/21/2016  12:41 AM    <DIR>          templates
07/21/2016  12:41 AM             2,086 transform.py
              10 File(s)        119,269 bytes
               7 Dir(s)  106,843,643,904 bytes free

**Comment by ProRobins** [comment]
that?

**Comment by yashmangal9506** [comment]
![image](https://cloud.githubusercontent.com/assets/20562083/17018830/41956472-4f57-11e6-9552-4cc6ee980d45.png)

**Comment by mherceg** [comment]
Excellent. Try executing
pip install -r requirements.txt

**Comment by ProRobins** [comment]
C:\Users\Favor\Desktop\PokemonGo-Map-master\PokemonGo-Map-master>dir
 Volume in drive C is SSD
 Volume Serial Number is 5E9B-2B97

 Directory of C:\Users\Favor\Desktop\PokemonGo-Map-master\PokemonGo-Map-master

07/21/2016  12:41 AM    <DIR>          .
07/21/2016  12:41 AM    <DIR>          ..
07/21/2016  12:41 AM    <DIR>          .github
07/21/2016  12:41 AM                11 .gitignore
07/21/2016  12:41 AM               151 .travis.yml
07/21/2016  12:41 AM               368 credentials.json
07/21/2016  12:41 AM    <DIR>          Easy Setup
07/21/2016  12:41 AM            29,233 example.py
07/21/2016  12:41 AM             1,081 LICENSE
07/21/2016  12:41 AM    <DIR>          locales
07/21/2016  12:41 AM             5,905 pokemon.proto
07/21/2016  12:41 AM            78,759 pokemon_pb2.py
07/21/2016  12:41 AM             1,526 README.md
07/21/2016  12:41 AM               149 requirements.txt
07/21/2016  12:41 AM    <DIR>          static
07/21/2016  12:41 AM    <DIR>          templates
07/21/2016  12:41 AM             2,086 transform.py
              10 File(s)        119,269 bytes
               7 Dir(s)  106,843,643,904 bytes free

C:\Users\Favor\Desktop\PokemonGo-Map-master\PokemonGo-Map-master>

**Comment by yashmangal9506** [comment]
how to do that

**Comment by ProRobins** [comment]
?

**Comment by yashmangal9506** [comment]
@mherceg pls comment

**Comment by mherceg** [comment]
As you typed 
dir
Now just type in your command prompt 
pip install -r requirements.txt

Fellas if you don't know how to use command prompt please don't open issues for that.

**Comment by ProRobins** [comment]
pip is not recognized

**Comment by medghaim** [comment]
This is _not_ issue worthy. Google can help with CMD, and for actual one on one support please go to: https://discord.gg/nN44Z

**Comment by ProRobins** [comment]
still need help

**Comment by ryantheleach** [comment]
Read the wiki. https://github.com/AHAAAAAAA/PokemonGo-Map/wiki

**Comment by ProRobins** [comment]
wiki dont do shit i fixed it

**Comment by MikeDX** [comment]
Great, if you've fixed it maybe you can submit a pull request

**Comment by yashmangal9506** [comment]
pls someone explain the whole process step by step pls i beg you
