### ISSUE TITLE
can't open file 'example.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by vlrprbttst** [AHAAAAAAA/PokemonGo-Map#809]
### Environment info
Operating System: Mac OSX

Installed version of Python:
2.7

### Steps to reproduce
1. downloaded branch develop and signed up an account
2. `cd` to the root of the folder and ran `pip install -r requirements.txt` (success)
3. ran `pip install --upgrade -r requirements.txt` (success)
4. ran `python example.py -a ptc -u [USERNAME] -p [PASSWORD] -l "[LOCATION]" -st 10` and i get

`/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'example.py': [Errno 2] No such file or directory`

### What have you tried?
both the master and develop branch, on master branch i get another error

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by medghaim** [comment]
Please take support questions to: https://discord.gg/nN44Z

There's no more example.py. It's runserver.py in the develop branch.

**Comment by vlrprbttst** [comment]
@medghaim docs are outdated then.

**Comment by medghaim** [comment]
https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Usage

**Comment by vlrprbttst** [comment]
@medghaim any more elaborate version of this? like what is needed, what is not, what is the real syntax to launch a basic launch, do I need a maps key etc.? I "guess" everything surrounded by `[ ]` is an option
