### ISSUE TITLE
attribute Error:lat and lng required

### ISSUE THREAD

**Issue by lakhhan** [AHAAAAAAA/PokemonGo-Map#814]
i hve tryed using lat & lng   21.2119969  -72.8252129 and also adding complet addres but still showing the same error.. could any one hepl me to figured it out,,??

**Comment by alexhutchings** [comment]
Put quotation marks around the location

**Comment by lakhhan** [comment]
yeh i had did that bt showing the error.. :-(

**Comment by fettlaus** [comment]
Please provide the complete command you entered.

**Comment by lakhhan** [comment]
![untitled](https://cloud.githubusercontent.com/assets/20564866/17019811/dc0588c6-4f5b-11e6-9ae1-7e4258757db1.png)
![pkm](https://cloud.githubusercontent.com/assets/20564866/17019812/dc068ece-4f5b-11e6-90ad-3e26b6c34c1c.png)

tryed many times bt still the same error!!

**Comment by lnmtriet93** [comment]
try inserting comma between lat and lng, it will work

**Comment by alexpantyukhin** [comment]
Do you try the `master` branch? Actually I would advise to use develop branch. It seems that `master` is not supported .

**Comment by lakhhan** [comment]
how to change the branch from master to develop..??

**Comment by lnmtriet93** [comment]
Change the branch to develop: git checkout develop

**Comment by lakhhan** [comment]
it shows "please commit your changes or stash them before you can switch branches."

**Comment by alexpantyukhin** [comment]
It means that you made some changes in files.
git checkout .
git checkout develop

But it's not related for the current question already.

**Comment by lakhhan** [comment]
so i hve to do to change the branch to develop??

**Comment by lakhhan** [comment]
anybody here to help me out??

**Comment by docrockulus** [comment]
Yes change to develop. Also, is that a double space between lat and long?

**Comment by xDanielle** [comment]
I have the same problem
