### ISSUE TITLE
example.py: error: argument -l/--location: expected one argument

### ISSUE THREAD

**Issue by adambowles** [AHAAAAAAA/PokemonGo-Map#816]
Ubuntu 14.04.2 LTS, Python 2.7.6

`$ python example.py -a ptc -u [redacted] -p [redacted] -l "Birmingham, UK" -st 10 -ar 30 -dl -dg -H 0.0.0.0`

`usage: example.py [-h] [-a AUTH_SERVICE] -u USERNAME [-p PASSWORD] -l LOCATION
                  -st STEP_LIMIT [-i IGNORE | -o ONLY] [-ar AUTO_REFRESH]
                  [-dp] [-dg] [-H HOST] [-P PORT] [-L LOCALE] [-ol] [-c] [-pm]
                  [-d]`

![pokemon](https://cloud.githubusercontent.com/assets/10128574/17019690/7af091fa-4f35-11e6-837b-49bf76d7eb68.png)

**Comment by medghaim** [comment]
Support for `master` has been dropped. Please checkout the develop branch.
