### ISSUE TITLE
what should i  do? can anyone answer?

### ISSUE THREAD

**Issue by sasha00123** [AHAAAAAAA/PokemonGo-Map#817]
### Environment info
Operating System:
Kali 2.0
Installed version of Python:
2.7.12

What is  the map dissapers after some steps! in browser console 
SyntaxError: missing } after property list
http://localhost:5000/
Line 51
![2016-07-21 15-32-45](https://cloud.githubusercontent.com/assets/17847512/17019929/bc724670-4f60-11e6-9f84-1778c72d5718.png)

**Comment by docrockulus** [comment]
Are you on master or develop branch?

**Comment by sasha00123** [comment]
I was on master) now on develop, thanks
