### ISSUE TITLE
Pokemon disapearing after ~20 seconds of scanning.

### ISSUE THREAD

**Issue by Hardstylah** [AHAAAAAAA/PokemonGo-Map#818]
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discord.gg/Kzp4yky).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System: Win 8

Installed version of Python: 2.7.12

### Steps to reproduce
1.  open command prompt in folder
2. Paste " python runserver.py -u xx -p xx -l "location,street" -st 10 --ignore weedle,caterpie,rattata,pidgey,spearow,poliwag,magikarp,paras,zubat  -H xxx.xxx.xxx.xxx
3. starts up can see pokemon
4. after 15 seconds "29:09] "GET /pokestops HTTP/1.1" 200 -
[2016-07-21 12:29:09,089] ERROR in app: Exception on /gyms [GET]
Traceback (most recent call last):" 
5. already scanned pokemon disapear.
6. no more pokemon show up.

### What have you tried?
1. asked in discord if anyone else had problem
2. Tried downloading a fresh folder.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

29:09] "GET /pokestops HTTP/1.1" 200 -
[2016-07-21 12:29:09,089] ERROR in app: Exception on /gyms [GET]
Traceback (most recent call last):

AttributeError: 'module' object has no attribute '_strptime'

**Comment by AlphaJuliettOmega** [comment]
wow this ticket, 10/10

**Comment by medghaim** [comment]
This is known. A commit was pushed that broke /pokestops, and is being worked on right now by @sykhro. Should be along shortly.
