### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by Foxy1990** [AHAAAAAAA/PokemonGo-Map#821]
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discord.gg/Kzp4yky).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:
Windows Server 2012 R2

Installed version of Python:
Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (
AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

> c:\PoGoDev>runserver.py -u USERNAME -l LOCATION -st 10
Password:
Traceback (most recent call last):
  File "C:\PoGoDev\runserver.py", line 44, in <module>
    position = get_pos_by_name(args.location)
  File "C:\PoGoDev\pogom\pgoapi\utilities.py", line 59, in get_pos_by_name
    loc = geolocator.geocode(location_name)
  File "C:\Python27\lib\site-packages\geopy\geocoders\googlev3.py", line 217, in
 geocode
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "C:\Python27\lib\site-packages\geopy\geocoders\base.py", line 171, in _ca
ll_geocoder
    raise GeocoderServiceError(message)
geopy.exc.GeocoderServiceError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED]
certificate verify failed (_ssl.c:590)>

> c:\PoGoDev>

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by Foxy1990** [comment]
Okay i fixed the problem for me here is my solution i added this code to PoGoDev\pogom\pgoapi\utility.py after import re

> import ssl

try:
    _create_unverified_https_context = ssl._create_unverified_context
except AttributeError:
    # Legacy Python that doesn't verify HTTPS certificates by default
    pass
else:
    # Handle target environment that doesn't support HTTPS verification
    ssl._create_default_https_context = _create_unverified_https_context

**Comment by Xerocry** [comment]
Same error. Try to add code and it didn't help, still `SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590
)`

**Comment by Foxy1990** [comment]
hm for me it worked u sure u edited the right file? :dancer:

**Comment by Xerocry** [comment]
It seems I have another issue, without GeocoderServiceError

**Comment by bjodasso** [comment]
I have the same issue as Xerocry. It seems a certificate is invalid. BUt I don't know where to look to add.renew a certificate for the error it is giving.
