### ISSUE TITLE
Not working code with a little change

### ISSUE THREAD

**Issue by zeoril** [AHAAAAAAA/PokemonGo-Map#822]
Actually the question in the title , at the slightest change file example.py file does not start , add a line such as the `print "1" `, in `clear_stale_pokemons`, after which it is printed

**Comment by Sejadis** [comment]
well if it doesnt start after you change it you obviously did something wrong
but non the less master branch not supported anymore - you should switch to develop branch

**Comment by MRokas** [comment]
Could we see your edited code example?

**Comment by zeoril** [comment]
```
def clear_stale_pokemons():
    current_time = time.time()

    for pokemon_key in pokemons.keys():
        pokemon = pokemons[pokemon_key]
        if current_time > pokemon['disappear_time']:
            print "[+] removing stale pokemon %s at %f, %f from list" % (
                pokemon['name'].encode('utf-8'), pokemon['lat'], pokemon['lng'])
			print "1"
            del pokemons[pokemon_key]
```
