### ISSUE TITLE
Map not being updated after ~30 minutes

### ISSUE THREAD

**Issue by vaurdan** [AHAAAAAAA/PokemonGo-Map#823]
Apparently, after some testing, the map is not being updated after 30 minutes despite there is no error in the console. No new pokemon is appearing, and the lured pokestops doesn't disappear.

Only restarting the script solves this, so I'm thinking it might be something related with the ticket validity, that is only renewed when you login and it's only valid for 30 minutes.

### Environment info
Operating System: CentOS 7

Installed version of Python: 2.7.6

### Steps to reproduce
1. Run the script and wait ~30 minutes
2. Watch all the pokemon on the map disappear (after the timer is done)
3. No new pokemon is appearing on the map
4. ?
5. profit

**Comment by jangrewe** [comment]
Are you using the master branch instead of develop? If so, there's your problem... RTFM! ;-)

**Comment by vaurdan** [comment]
Ha! I haven't found anything mentioning that I should use the develop branch. Thanks for letting me know :) I'm going to see if I can replicate this on the dev branch.

**Comment by fipso** [comment]
Same here

**Comment by AlphaJuliettOmega** [comment]
USE THE SEARCH BEFORE YOU OPEN A TICKET BRUV
https://github.com/AHAAAAAAA/PokemonGo-Map/issues/812

**Comment by MikeDX** [comment]
nobody should be using the master branch at the moment, I'm sure it says so on the front page

**Comment by jangrewe** [comment]
i'm still using it because it's the only branch showing all (or at least the most) markers, but i also know how to work around its quirks ;-)

(got the dev branch running, too, of course - but only to compare with master)
