### ISSUE TITLE
Google Maps could not be loaded correctly (Map visible for a split second, then Error)

### ISSUE THREAD

**Issue by TsuyoshiPSER** [AHAAAAAAA/PokemonGo-Map#824]
I tried with different browsers and master and development version. I think the server runs fine, in the short time the map is visible i can see Pokemon and PokeStops wich are in my area, but like i said after a split second, not even one full second, i get the error that Google Maps could not be loaded correctly/properly (i don't know what the correct translation would be, i get the error in german)

**Comment by jabelone** [comment]
Read the wiki... https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Google-Maps-API:-a-brief-guide-to-your-own-key

**Comment by TsuyoshiPSER** [comment]
I already did that.

**Comment by DerScreever** [comment]
@TsuyoshiPSER you could post the german error.
Im from germany ^^

**Comment by actondong** [comment]
I guess this is due to API key issue. Get your own googlemap api key and replace the one in credentials

**Comment by kevdotcom** [comment]
I had this problem with the master branch aswell... dev-branch should work.

**Comment by tamoler** [comment]
When you create key - select server type.

**Comment by Feldunoob** [comment]
That's indeed API key: tested.
