### ISSUE TITLE
Bug: Unable to disable Gyms in develop

### ISSUE THREAD

**Issue by darcycartwright** [AHAAAAAAA/PokemonGo-Map#827]
**Disclaimer:** 
I didn't want to put this as a bug because I wasn't sure if it was just me doing it wrong or not.

I was wondering if anyone knew how to disable gyms from showing up on the developer version?

They seem to be on by default now and the instructions Wiki didn't help.

**Comment by AlphaJuliettOmega** [comment]
but why?

**Comment by darcycartwright** [comment]
Because I don't want to view 1000000 gyms over the top of the Pokémon I'm looking for.

**Comment by darcycartwright** [comment]
<img width="778" alt="screen shot 2016-07-21 at 9 29 52 pm" src="https://cloud.githubusercontent.com/assets/20495914/17021283/6ae31d32-4f8a-11e6-99e3-2082b792624a.png">

**Comment by AlphaJuliettOmega** [comment]
epic, there's way more pokemon than gyms in my area : like 500:1
good luck xD

**Comment by DerScreever** [comment]
just dont pass the -dg flag to your start command

**Comment by darcycartwright** [comment]
I haven't.

**Comment by docrockulus** [comment]
What is your launch command?

**Comment by darcycartwright** [comment]
python runserver.py -a PTC -u username -p password -l "Address" -st 5 -H 0.0.0.0 -P 5000

**Comment by docrockulus** [comment]
Actually, I can confirm that gyms are displayed without passing the -dg flag. 1c26e54

**Comment by darcycartwright** [comment]
So this is a bug then?

**Comment by docrockulus** [comment]
Would seem like it. Someone should tag it as such.

**Comment by benemorius** [comment]
This appears fixed on the latest commit (51f651228c00a96b86f5c38d1a2d53b32e5d9862)

The command line switch is obsoleted and gym display can now be toggled as a map layer in the browser.
