### ISSUE TITLE
for develop branch

### ISSUE THREAD

**Issue by lakhhan** [AHAAAAAAA/PokemonGo-Map#832]
it shows can't open file 'example.py' : [errno 2] no such file or directory

**Comment by MRokas** [comment]
You've to use runserver.py

**Comment by lakhhan** [comment]
![untitled](https://cloud.githubusercontent.com/assets/20564866/17021856/4d337d6c-4f68-11e6-80cf-6b2a6ad69f8b.png)

it showing like this.. ;(

**Comment by RyanMBlue** [comment]
You need to copy the credentials.json.example file to credentials.json and edit it to put your google API key in there

**Comment by lakhhan** [comment]
Thanx i hve did it😉

**Comment by immorro** [comment]
Ohhh fuck..I dnt knw anything bt i want the map for pokemon go..any could me out.!??
