### ISSUE TITLE
Error: Unicode equal comparison failed to convert both arguments to Unicode

### ISSUE THREAD

**Issue by caracol007** [AHAAAAAAA/PokemonGo-Map#839]
### Environment info
Operating System:
Windows 10 N 
Installed version of Python:
2.7.12

### Steps to reproduce
1. run pip install -r requirements.txt

### What have you tried?
1. Nothing, as I'm totally new to all of this.. 

### Logs or other output that would be helpful
C:\PokemonMap\Develop\PokemonGo-Map-develop>pip install -r requirements.txt
[...]
Collecting geopy==1.11.0 (from -r requirements.txt (line 10))
  Using cached geopy-1.11.0-py2.py3-none-any.whl
Collecting protobuf==2.6.1 (from -r requirements.txt (line 11))
c:\python27\lib\urllib.py:1299: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  return ''.join(map(quoter, s))
Exception:
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\python27\lib\site-packages\pip\commands\install.py", line 310, in run
    wb.build(autobuilding=True)
  File "c:\python27\lib\site-packages\pip\wheel.py", line 750, in build
    self.requirement_set.prepare_files(self.finder)
  File "c:\python27\lib\site-packages\pip\req\req_set.py", line 370, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "c:\python27\lib\site-packages\pip\req\req_set.py", line 522, in _prepare_file
    finder, self.upgrade, require_hashes)
  File "c:\python27\lib\site-packages\pip\req\req_install.py", line 271, in populate_link
    self.link = self._wheel_cache.cached_wheel(self.link, self.name)
  File "c:\python27\lib\site-packages\pip\wheel.py", line 68, in cached_wheel
    self._cache_dir, link, self._format_control, package_name)
  File "c:\python27\lib\site-packages\pip\wheel.py", line 148, in cached_wheel
    return pip.index.Link(path_to_url(path))
  File "c:\python27\lib\site-packages\pip\download.py", line 457, in path_to_url
    url = urllib_parse.urljoin('file:', urllib_request.pathname2url(path))
  File "c:\python27\lib\nturl2path.py", line 67, in pathname2url
    path = path + '/' + urllib.quote(comp)
  File "c:\python27\lib\urllib.py", line 1299, in quote
    return ''.join(map(quoter, s))
KeyError: u'\xfc'

**Comment by Kret1** [comment]
Similar error here:


**Environment info**

Operating System:
Windows 10 Home
Installed version of Python:
2.7.12
**Steps to reproduce**

    run pip install -r requirements.txt

**What have you tried?**

  I've tried using pip included on this PY verson and an external one, I also have linked paths on system variables like so: [http://i.imgur.com/cmmjZ82.png](url)

**Logs or other output that would be helpful**

C:\Users\R********o\Documents\PokemonGo-Map-master>pip install -r requirements.txt
Collecting geopy==1.11.0 (from -r requirements.txt (line 1))
  Using cached geopy-1.11.0-py2.py3-none-any.whl
Collecting protobuf==2.6.1 (from -r requirements.txt (line 2))
c:\python27\lib\urllib.py:1299: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  return ''.join(map(quoter, s))
Exception:
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\python27\lib\site-packages\pip\commands\install.py", line 310, in run
    wb.build(autobuilding=True)
  File "c:\python27\lib\site-packages\pip\wheel.py", line 750, in build
    self.requirement_set.prepare_files(self.finder)
  File "c:\python27\lib\site-packages\pip\req\req_set.py", line 370, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "c:\python27\lib\site-packages\pip\req\req_set.py", line 522, in _prepare_file
    finder, self.upgrade, require_hashes)
  File "c:\python27\lib\site-packages\pip\req\req_install.py", line 271, in populate_link
    self.link = self._wheel_cache.cached_wheel(self.link, self.name)
  File "c:\python27\lib\site-packages\pip\wheel.py", line 68, in cached_wheel
    self._cache_dir, link, self._format_control, package_name)
  File "c:\python27\lib\site-packages\pip\wheel.py", line 148, in cached_wheel
    return pip.index.Link(path_to_url(path))
  File "c:\python27\lib\site-packages\pip\download.py", line 457, in path_to_url
    url = urllib_parse.urljoin('file:', urllib_request.pathname2url(path))
  File "c:\python27\lib\nturl2path.py", line 67, in pathname2url
    path = path + '/' + urllib.quote(comp)
  File "c:\python27\lib\urllib.py", line 1299, in quote
    return ''.join(map(quoter, s))
KeyError: u'\xe9'

**Comment by fmmarinho** [comment]
Same problem here

**Comment by Kret1** [comment]
Tried on different computer with WIN 10 PRO

Python version 2.7.12

Logs:

C:\Python27\PokemonGo-Map-master>pip install -r requirements.txt
Collecting geopy==1.11.0 (from -r requirements.txt (line 1))
  Downloading geopy-1.11.0-py2.py3-none-any.whl (66kB)
    100% |################################| 71kB 695kB/s
Collecting protobuf==2.6.1 (from -r requirements.txt (line 2))
  Downloading protobuf-2.6.1.tar.gz (188kB)
    100% |################################| 194kB 1.3MB/s
Collecting requests==2.10.0 (from -r requirements.txt (line 3))
  Downloading requests-2.10.0-py2.py3-none-any.whl (506kB)
    100% |################################| 512kB 1.0MB/s
Collecting flask-googlemaps==0.2.0 (from -r requirements.txt (line 4))
  Downloading Flask-GoogleMaps-0.2.0.tar.gz
Collecting s2sphere==0.2.4 (from -r requirements.txt (line 5))
  Downloading s2sphere-0.2.4-py2.py3-none-any.whl
Collecting flask==0.11.1 (from -r requirements.txt (line 6))
  Downloading Flask-0.11.1-py2.py3-none-any.whl (80kB)
    100% |################################| 81kB 952kB/s
Collecting gpsoauth==0.3.0 (from -r requirements.txt (line 7))
  Downloading gpsoauth-0.3.0.tar.gz
Collecting coveralls==1.1 (from -r requirements.txt (line 8))
  Downloading coveralls-1.1-py2.py3-none-any.whl
Collecting werkzeug==0.11.10 (from -r requirements.txt (line 9))
  Downloading Werkzeug-0.11.10-py2.py3-none-any.whl (306kB)
    100% |################################| 307kB 1.2MB/s
Requirement already satisfied (use --upgrade to upgrade): setuptools in c:\python27\lib\site-packages (from protobuf==2.6.1->-r requirements.txt (line 2))
Collecting future (from s2sphere==0.2.4->-r requirements.txt (line 5))
  Downloading future-0.15.2.tar.gz (1.6MB)
    100% |################################| 1.6MB 620kB/s
Collecting itsdangerous>=0.21 (from flask==0.11.1->-r requirements.txt (line 6))
  Downloading itsdangerous-0.24.tar.gz (46kB)
    100% |################################| 51kB 731kB/s
Collecting click>=2.0 (from flask==0.11.1->-r requirements.txt (line 6))
  Downloading click-6.6.tar.gz (283kB)
    100% |################################| 286kB 1.4MB/s
Collecting Jinja2>=2.4 (from flask==0.11.1->-r requirements.txt (line 6))
  Downloading Jinja2-2.8-py2.py3-none-any.whl (263kB)
    100% |################################| 266kB 1.1MB/s
Collecting pycryptodomex>=3.0 (from gpsoauth==0.3.0->-r requirements.txt (line 7))
  Downloading pycryptodomex-3.4.2-cp27-cp27m-win_amd64.whl (7.5MB)
    100% |################################| 7.5MB 205kB/s
Collecting coverage>=3.6 (from coveralls==1.1->-r requirements.txt (line 8))
  Downloading coverage-4.1-cp27-cp27m-win_amd64.whl (164kB)
    100% |################################| 174kB 1.0MB/s
Collecting docopt>=0.6.1 (from coveralls==1.1->-r requirements.txt (line 8))
  Downloading docopt-0.6.2.tar.gz
Collecting MarkupSafe (from Jinja2>=2.4->flask==0.11.1->-r requirements.txt (line 6))
  Downloading MarkupSafe-0.23.tar.gz
Building wheels for collected packages: protobuf, flask-googlemaps, gpsoauth, future, itsdangerous, click, docopt, MarkupSafe
  Running setup.py bdist_wheel for protobuf ... done
  Stored in directory: C:\Users\Rub'n\AppData\Local\pip\Cache\wheels\c9\97\49\1bf6b7b58d0adec650bcb625b6656877437d1f7d18c32e88ee
c:\python27\lib\urllib.py:1299: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  return ''.join(map(quoter, s))
Exception:
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\python27\lib\site-packages\pip\commands\install.py", line 310, in run
    wb.build(autobuilding=True)
  File "c:\python27\lib\site-packages\pip\wheel.py", line 836, in build
    path_to_url(wheel_file))
  File "c:\python27\lib\site-packages\pip\download.py", line 457, in path_to_url
    url = urllib_parse.urljoin('file:', urllib_request.pathname2url(path))
  File "c:\python27\lib\nturl2path.py", line 67, in pathname2url
    path = path + '/' + urllib.quote(comp)
  File "c:\python27\lib\urllib.py", line 1299, in quote
    return ''.join(map(quoter, s))
KeyError: u'\xe9'

**Comment by fmmarinho** [comment]
i have Windows XP

**Comment by paprika01** [comment]
Hello Everyone! I have the same problem. I followed this step by step installation guide: https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Installation-and-requirements

If somebody is reding this who solved this problem, please help!

Thank you!
