### ISSUE TITLE
-i argument is invalid

### ISSUE THREAD

**Issue by docrockulus** [AHAAAAAAA/PokemonGo-Map#842]
After the most recent commit, the -i argument is invalid

python runserver.py -a google -u xxx -p xxx -l "x y" -st 10 -H 0.0.0.0 -P 5001 -ar 30 -i 96

`runserver.py: error: unrecognized arguments: 30 -i 96`

**Comment by lnmtriet93** [comment]
they removed the argument -i/--ignore and -o/--only I thinked. There's an update in usage

**Comment by docrockulus** [comment]
Great, now there will be drowzees everywhere! :P

**Comment by docrockulus** [comment]
The -ar argument appears to also be invalid now!

**Comment by lnmtriet93** [comment]
I found out the new usage being:
usage: runserver.py [-h] [-a AUTH_SERVICE] -u USERNAME [-p PASSWORD] -l
                    LOCATION -st STEP_LIMIT [-H HOST] [-P PORT] [-L LOCALE]
                    [-c] [-d] [-m] [-k GMAPS_KEY]

**Comment by docrockulus** [comment]
I like the new filtering of gyms/pokestops with the on-map menu, but not being able to filter out these 5,000,000 drowzees is painful.

http://i.imgur.com/2L4zepn.jpg?1

**Comment by DerScreever** [comment]
@docrockulus we are working on an ui filter :-)

**Comment by OXVIL** [comment]
Use names of pokemon as:
-i Pidgey,Drowzee,Zubat,Rattata

**Comment by DerScreever** [comment]
@OXVIL removed on last develop
