### ISSUE TITLE
No map in the latest dev build

### ISSUE THREAD

**Issue by bonan999** [AHAAAAAAA/PokemonGo-Map#844]
No map showing up in the latest dev build

### Environment info
Operating System: Mac OSX 10.11.5

Installed version of Python:
2.7

### Steps to reproduce
1. Start Server
2. Go to [ip]:5000

### What have you tried?
1.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by chaze117** [comment]
If you not hosted to a specific IP with -H parameter you shuld try 127.0.0.1:5000 or localhost:5000

**Comment by MRokas** [comment]
Could you open up dev console and copy-paste what it says? perhaps there's an error.

**Comment by lparkermg** [comment]
I think it might be something to do with #843

**Comment by Duckylord** [comment]
does your localhost:5000 say: http://imgur.com/a/TBDJw?

**Comment by lparkermg** [comment]
Na just tried it on mine, mine comes up with the page, but the map itself doesn't display. Though I do get this in the console.
<img width="1020" alt="screen shot 2016-07-21 at 13 33 48" src="https://cloud.githubusercontent.com/assets/6538466/17022771/d01642a8-4f47-11e6-8324-8f9fea7f777a.png">

**Comment by bonan999** [comment]
I can't even start and connect to the server now.
 ```
 File "/Users/hugohammarstrom/Desktop/Development/PokemonGo/PokemonGo-Map/runserver.py", line 63, in <module>
    app.run(threaded=True, debug=args.debug, host=args.host, port=args.port)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 843, in run
    run_simple(host, port, self, **options)
  File "/Library/Python/2.7/site-packages/werkzeug/serving.py", line 694, in run_simple
    inner()
  File "/Library/Python/2.7/site-packages/werkzeug/serving.py", line 656, in inner
    fd=fd)
  File "/Library/Python/2.7/site-packages/werkzeug/serving.py", line 544, in make_server
    passthrough_errors, ssl_context, fd=fd)
  File "/Library/Python/2.7/site-packages/werkzeug/serving.py", line 464, in __init__
    HTTPServer.__init__(self, (host, int(port)), handler)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 420, in __init__
    self.server_bind()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 434, in server_bind
    self.socket.bind(self.server_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
```

**Comment by medghaim** [comment]
Try deleting pogom.db

**Comment by lnmtriet93** [comment]
Related to IntegrityError, removing pogom.db will fix it.

**Comment by bonan999** [comment]
I've tried that before, but deleted pogom.db again and still nothing

**Comment by bonan999** [comment]
Okey, so it appeared to be a problem with the -H parameter. Removed that and now the server is starting, but the problem with the map not showing is still there. 
<img width="1247" alt="skarmavbild 2016-07-21 kl 14 47 41" src="https://cloud.githubusercontent.com/assets/7461128/17023162/49dadd06-4f52-11e6-8274-b63fe4b82bad.png">

`[Error] Viewport argument key "minimal-ui" not recognized and ignored. (127.0.0.1, line 6)

[Error] Failed to load resource: the server responded with a status of 404 (NOT FOUND) (cross.png, line 0)

[Error] SyntaxError: Unexpected identifier 'pad'
	(anonym funktion) (map.js:137)

[Error] InvalidValueError: initMap is not a function
	Yg (js:96:425)
	(anonym funktion) (js:131)
	Load (js:21)
	(anonym funktion) (js:130:600)
	global code (js:131)`

**Comment by cyberflow** [comment]
Same problem on Safari (mac OS and iOS). All working fine on firefox.

**Comment by flexusjan** [comment]
Same problem here. - Google Chrome works - Mozilla Firefox don't.

Firefox Webconsole:
SyntaxError: missing ; before statement map.js:137:8
InvalidValueError: initMap is not a function


Maybe Firefox can't handle the "let"-keyword in line 137.

**Comment by vincesmits** [comment]
I also get a blank map with safari, few commits ago it worked. it does work in other browsers so no real problem just a confirmation.

**Comment by MRokas** [comment]
Someone screwed up with one of .js files

@flexusjan  - if your firefox cant handle _let_ keyword, it's time to update your browser. _let_ is supported in firefox since long time ago.

**Comment by bonan999** [comment]
**Error fixed in latest dev build**
This issue can be closed now!
