### ISSUE TITLE
credentials.json

### ISSUE THREAD

**Issue by Kevinclon** [AHAAAAAAA/PokemonGo-Map#845]
It runs into a problem finding credentials.json
There is a credentials.example.json but I don't know what I would do to make that work appropratly

**Comment by cschmatzler** [comment]
Rename the existing file or create a new one

**Comment by dominicE** [comment]
rename it do credentials.json and put in your api key

**Comment by MRokas** [comment]
rename **credentials.examples.json** to **credentials.json**

**Comment by lnmtriet93** [comment]
You can clone this file then rename the copied file to credentials.json
Remember to add your gmaps_key

**Comment by pix** [comment]
@Kevinclon : https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Google-Maps-API:-a-brief-guide-to-your-own-key

**Comment by medghaim** [comment]
pls

**Comment by medghaim** [comment]
pls

**Comment by Kevinclon** [comment]
Wow thanks for the instant help, you guys are lovley and i am silly
