### ISSUE TITLE
Error in file

### ISSUE THREAD

**Issue by sandy0201** [AHAAAAAAA/PokemonGo-Map#846]
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discord.gg/Kzp4yky).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System: **Windows 10**

Installed version of Python:
**Python 3.5.2**

### Steps to reproduce
1. In command prompt enter: **python example.py -a ptc -u ****** -p ****** -l "Sandton, South Africa" -st 10**
2. Error returned: 
![image](https://cloud.githubusercontent.com/assets/2969051/17022737/f8c7b36e-4f4f-11e6-981e-ee069b7c1d6b.png)

### What have you tried?
1. Don't know what to do, new to python.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by dominicE** [comment]
Did you read Wiki? You need Python 2.7
