### ISSUE TITLE
After replacing GMAPKEY it says KeyError

### ISSUE THREAD

**Issue by Kevinclon** [AHAAAAAAA/PokemonGo-Map#850]
https://gyazo.com/394caa044eb68aaa6ac43e3d93f8e047

I replaced the Gmapkey with the key generated and now it gives a "KeyError: 'gmaps_key'"

To confirm the cred file should look like this right?

{
	"Mycode" : ""
}

**Comment by lnmtriet93** [comment]
The right format in your credentials.json sould be:
{
	"gmaps_key" : "Your_Key"
}
