### ISSUE TITLE
cant send to channel or specified device in pushbullet(error)

### ISSUE THREAD

**Issue by malosaa** [AHAAAAAAA/PokemonGo-Map#852]
### Environment info
Operating System: x32 win7

Installed version of Python:
2.7.x

### Steps to reproduce
tested everything 

### What have you tried?
1.

**Comment by shadow7412** [comment]
If you want this to go anywhere - please provide some details.
I currently have no idea what you're talking about.

**Comment by malosaa** [comment]
now you only can send push note to youself , but i know with pushbullet you can send to a created channel and my other devices .. thats what i want ..

**Comment by malosaa** [comment]
anyone can add it ?

**Comment by malosaa** [comment]
?
