### ISSUE TITLE
Node.js spawn example.py

### ISSUE THREAD

**Issue by externuz** [AHAAAAAAA/PokemonGo-Map#856]
Hi! We tried to start your server dynamically from node.js via
```
  let cmd = spawn('/usr/bin/python', [
    './locator/example.py',
    '-u',
    'login',
    '-p',
    'password',
    '-l',
    'Moscow',
    '-st',
    '100'
  ]);
```
but there is some problems:
1. `IOError: [Errno 2] No such file or directory: 'credentials.json'` - can be fixed by adding path to credentials.json or copy credentials.json to our start folder.
2. This log after start example.py from node.js:
```
* Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
* Restarting with stat
* Debugger is active!
* Debugger pin code: 139-284-560
```
Server really starts on 5000 port, but nothing happens when we open page localhost:5000.
If we start example.py from shell, all is okay, working perfect. How can we fix this issue? Help, pls.

What are we trying? We tried to use `python-shell` module, tried to use 'exec' instead 'spawn'. Nothing helps, one result for each variant.

**Comment by DerScreever** [comment]
we droppen support for master branch. we are working on develop on our rework.

**Comment by RyanMBlue** [comment]
example.py is from the master branch. They are no longer supporting that branch, use the develop branch instead
