### ISSUE TITLE
runserver.py: error: argument -p/--password: expected one argument

### ISSUE THREAD

**Issue by adambowles** [AHAAAAAAA/PokemonGo-Map#859]
Ubuntu: 14.04.2  
Python: 2.7.6  
branch: development

Command: `user@host:~/PokemonGo-Map$ python runserver.py -a ptc -u [redacted] -p [redacted] -l "[redacted]" -st 12 -dp -dg -H 0.0.0.0 -P 5001`

Shows the same error message when I remove the -p argument entirely

![pokemon](https://cloud.githubusercontent.com/assets/10128574/17023916/b3880bac-4f4d-11e6-9e1e-114f43215693.png)

**Comment by Fiofant** [comment]
remove -dp -dg

**Comment by adambowles** [comment]
Works, but why?
