### ISSUE TITLE
No module naped flask

### ISSUE THREAD

**Issue by a1kaed** [AHAAAAAAA/PokemonGo-Map#860]
i have a problem
![screenshot from 2016-07-21 16 15 45](https://cloud.githubusercontent.com/assets/20579460/17023925/8263da2c-4f5e-11e6-9ba6-bf91dfa2f5cd.png)

sorry. my English is very bad.
i use reinstal flask with _pip unininstal flask_ and _easy-install flask_

**Comment by DerScreever** [comment]
pip install --upgrade -r requirements.txt

**Comment by Megamatic** [comment]
same here. Also, in the wiki you refer to using the example.py from the develop branch. However, that branch does not have a file called example.py.

**Comment by DerScreever** [comment]
@megamatic fixed.

**Comment by wcyyo** [comment]
Same here.Solved this problem now?@Megamatic
