### ISSUE TITLE
Suggestion: Highlight Filter ? 

### ISSUE THREAD

**Issue by craigbaines** [AHAAAAAAA/PokemonGo-Map#863]
I was wondering if theirs anyone else who would see the need for my idea. 

Instead of simply filtering certain Pokemon out, or showing only a select few. Would it be possible to have a third filter for Pokemon you wanted highlighted, so i can go about my business farming all the garbage and be notified when my more desired Pokemon show up. 

I saw there are a few people working on browser notifications, sound notifications, they would all be awesome ways to do this, along with either or both of them id say perhaps an increased icon size for your highlighted Pokemon, so they stand out on the map more? 

Im no python coder but id be willing to play around a bit an try if the idea is welcomed, id of course let someone else who actually knows python take charge if anyone fancies it!

Just an idea i think would be handy and hopefully not too difficult to add in if you lot agree! 

Thanks

**Comment by craigbaines** [comment]
@richipargo 
@NgJason

**Comment by NgJason** [comment]
@craigbaines The devs are working on a new filter system at this time.
