### ISSUE TITLE
Good way to run on mobile.

### ISSUE THREAD

**Issue by caranicas** [AHAAAAAAA/PokemonGo-Map#865]
Just wanted to throw this out there. I just started using [ngrok](https://ngrok.com/) so I can use the map while I'm out. 

Ngrok creates a tunnel to a port on your computer, and generates a URL. You can hit the url on your mobile browser and see the map while you are out. its pretty amazing.

**Comment by Hardstylah** [comment]
Already available with the command -H 0.0.0.0

**Comment by matthiasdrymalla** [comment]
@Hardstylah but as expected, there are limitations concerning your network infrastructure, maybe ngrok can help with that!

**Comment by jfarese23** [comment]
@caranicas I've also been using ngrok. It's awesome but my map always stops updating after about half an hour. Is there a way to fix this?

**Comment by Znuff** [comment]
Update to latest version.

**Comment by ChristianLuxem** [comment]
I think someone should write a Step on Step Dokumentation in the Wiki. 
Something like:
1. Install from here: LINK
2. Run your Command line with the following params: ...
3. etc...
It looks to be a very nice feature!

**Comment by matthiasdrymalla** [comment]
@ChristianLuxem There was at least a section in the Wiki, which explained how to use -H and -P flag. It was removed yesterday. But since the wiki is a git-projekt either feel free to look for these changes. :P

**Comment by caranicas** [comment]
@jfarese23 I think that might be your computer going to sleep? i just tried to force mine awake, but it still returned to the login screen, and i lost my connection.

**Comment by Lenny188** [comment]
Well can someone give me a hint how to forward that map so I can actually open it up on my iPhone while i am outside? I seriously have no Idea how to do so...where do I have to put the command -H 0.0.0.0? Help needed here :) thx a lot!

**Comment by revoqed** [comment]
Hey! Im trying to use ngrok and set up http to the port im using for the live pokemon radar, but when i try to connect through my phone all I get is a blank page that says maps at the top. I get an error saying get/static/img/cross.png 404 not found. Any help would be appreciated! Thanks.

**Comment by revoqed** [comment]
@caranicas @jfarese23 
if you guys could help me please, i get this message and blank screen from my phone when trying to connect to the url

GET /static/img/cross.png                 404 NOT FOUND
GET /static/map.js                        200 OK
GET /static/dist/css/app.min.css          200 OK
GET /static/js/vendor/modernizr.custom.js 200 OK
GET /static/js/vendor/classie.js          200 OK
GET /static/dist/js/app.min.js            200 OK
GET /static/js/vendor/svg-overlay.js      200 OK
GET /static/css/style8.css                200 OK
GET /                                     200 OK
