### ISSUE TITLE
Map Stops Updating

### ISSUE THREAD

**Issue by jfarese23** [AHAAAAAAA/PokemonGo-Map#869]
Hi I'm loving the program and it seems to work great for a while, but after about 30-45 minutes of running, the Pokemon on the map stop being updated. Right now, I have an autorefresh interval of 60 seconds. Is there some way to combat this issue? I've been using ngrok to use the program on mobile, but it isn't very useful if it stops updating. Thanks for any help you can provide.

**Comment by Znuff** [comment]
Update.

**Comment by DerScreever** [comment]
we know this already, its a bug we fix that.

**Comment by jfarese23** [comment]
@Znuff @DerScreever I updated about an hour ago. It's still not working

**Comment by leovarmak** [comment]
@DerScreever I want to find the pokemon around a particular location. So the location wont change. Now I want to keep it running all the time. I took up a Digital Ocean Droplet and I want to keep the server running all the time. Now what happens is that after like 30-40 minutes usage the already existing pokemons are show but others slowly disappear. This things continues and atlast all pokemon disappear an wont update
