### ISSUE TITLE
Looping through multiple refresh iterations causes slow down in flask

### ISSUE THREAD

**Issue by Lazarix** [AHAAAAAAA/PokemonGo-Map#87]
### Environment info
Operating System: Centos 6.3

Installed version of Python: 2.7

### Steps to reproduce
1. Run code
2. Let it get to 100%
3. Wait for further loops to complete
4. After 3rd or 4th loop, map gets slower to refresh
5. After 6th iteration, map is unusable
6. Closing app and starting the refresh again brings back responsiveness.

CPU / Memory usage are negligible, so unknown cause.

**Comment by D3nn3** [comment]
Yes that is the case. I did further testing and chrome dev tools tells me that the page size is getting bigger and bigger over time reaching more than 50mb after sime time. Maybe this info helps.

**Comment by marauder37** [comment]
ok I'm going to have a look at whether clearing the pokemon lists on each iteration fixes it

**Comment by favll** [comment]
#79 fixes this, however, there is still a small bug in that PR originating from false indentation.

**Comment by favll** [comment]
Merge #101 instead.
