### ISSUE TITLE
Regression: Ignore / Only options gone. Can't display only lured pokestops

### ISSUE THREAD

**Issue by Znuff** [AHAAAAAAA/PokemonGo-Map#870]
Arguably, the most useful feature of the map was to display Only some specific pokemons or ignore the most common ones, in the hopes of finding that Pikachu or whatever you were looking for.

Latest version has those options removed from the backend command line, but there are no actual options offered in the frontend to compensate for the removal of those options.

I personally find this to be a regression of this project.

**Comment by npeep** [comment]
That is my experience as well - tested the latest development branch changes this morning and without -i the output is overwhelming.

**Comment by DerScreever** [comment]
@Znuff we are already working on the frontend ui to ignore etc :-) just give us some time ^^ you will find your pikachu :-)

**Comment by craigbaines** [comment]
Expired pokemon are not being removed still too, im using the latest version of dev. I see the fix i had been using from the pull requests got closed (broken?) too.

**Comment by sykhro** [comment]
Yeah, call it regression, I'm saying this again for the 10th time: develop is not release, stuff is being changed, features can me dropped for a little.
I tested everything personally for hours, the pokemons are being removed once expired and as soon as updatemap is passed, so maximum 5 seconds after expiry

**Comment by craigbaines** [comment]
Im not saying its regression, sorry, probably typed this in the wrong place lol, i appreciate all the work from everyone, it's an awesome little app :) I was more asking if there was any other  solution atm to that one i had previously been using, which is now closed?

**Comment by sykhro** [comment]
that's quite strange, what browser are you using?

**Comment by craigbaines** [comment]
Chrome and firefox.

**Comment by DanielVolz** [comment]
Mine neither:
<img width="257" alt="screenshot 2016-07-21 16 16 35" src="https://cloud.githubusercontent.com/assets/3275994/17025977/a6c46c1a-4f5e-11e6-89ff-56611dad79c9.png">

6+ minutes after the despwan.

**Comment by npeep** [comment]
Same on win10 with Chrome Version 51.0.2704.106 m (64-bit).
![2016-07-21 09_32_56-pokemap](https://cloud.githubusercontent.com/assets/6043230/17026636/58c6764e-4f26-11e6-9ed8-1dc48223f74a.png)

**Comment by sykhro** [comment]
@npeep @DanielVolz latest commit should have fixed the issue

**Comment by npeep** [comment]
@sykhro Thanks!  Side note:  Now the pokestop toggle is not working for me.  Just FYI, in case it wasn't intentional.

**Comment by craigbaines** [comment]
Yep, there working again for me now (Thanks) The only issue i see atm, is that pokestops on/off toggle only seems to turn off the last ones that got added, rather than them all, if that makes sense. Im not sure if the gyms work the same but when i totggle them, they all go on or off (may be because no new ones are being added)

**Comment by npeep** [comment]
@sykhro pokestops work after your latest commit.  Thanks man!

**Comment by craigbaines** [comment]
Was about to say the same, thanks!
