### ISSUE TITLE
Error Starting the server

### ISSUE THREAD

**Issue by SkyBadPT** [AHAAAAAAA/PokemonGo-Map#872]
Im using this command to start: (I have hidded the location, user and pass)

`python runserver.py -a ptc -u USER -p PASS -l "LOCATION" -st 10 -H 00.00.00.00 -P 5000 -ar 5`

and im getting this error:

```
usage: runserver.py [-h] [-a AUTH_SERVICE] -u USERNAME [-p PASSWORD] -l
                    LOCATION -st STEP_LIMIT [-H HOST] [-P PORT] [-L LOCALE]
                    [-c] [-d] [-m] [-k GMAPS_KEY]
runserver.py: error: unrecognized arguments: 5
```
also im using the last Dev i have just downloaded it like 5 minutes ago.

Also can someone tell me what is the `-ar 5` because i used it in the other versions

**Comment by sykhro** [comment]
The auto-refresh is integrated in the UI, you don't have to pass that argument

**Comment by hedqvist** [comment]
Autorefresh is now in the ui, no need to use it in arguments. remove -ar 5 and you are good to go!

**Comment by SkyBadPT** [comment]
Sure it is working now but the map is black and the gyms are appearing how can i change the map color and how can i hide the gyms?

**Comment by SkyBadPT** [comment]
Neverming i found it but the pokestops are bugged btw

**Comment by SkyBadPT** [comment]
nut i can't change the map color

**Comment by cesarbecerra** [comment]
to change the map color just find the file map.js and delete styles array in the function initMap

**Comment by SkyBadPT** [comment]
@cesarbecerra Thanks
