### ISSUE TITLE
map starts to have hole

### ISSUE THREAD

**Issue by coreyrules12** [AHAAAAAAA/PokemonGo-Map#875]
when the map is at like step 400 it starts getting a gigantic hole where i put the starting location with no pokemon around me

**Comment by MRokas** [comment]
They just despawn, and nearby locations doesn't get checked. This would require different approach to looping.

**Comment by coreyrules12** [comment]
so theres no way of stoping it from happening

**Comment by MRokas** [comment]
Reduce steps. 400 is way too big anyway.

**Comment by sykhro** [comment]
400 steps means you are searching in in a 400*400 area, that's way too big

**Comment by coreyrules12** [comment]
ok thank you
