### ISSUE TITLE
Pokemons don't disappear

### ISSUE THREAD

**Issue by SkyBadPT** [AHAAAAAAA/PokemonGo-Map#878]
When the time ends the pokemon appear (expired) but don't disappear. this still one bug or it as been fixed?

**Comment by IQNeoXen** [comment]
Just refresh... they should be gone afterwards

**Comment by flexusjan** [comment]
It would be better, if the expired Pokemons disappears via auto-refresh.

Still waiting for this feature...

**Comment by SkyBadPT** [comment]
Yes me too it would be great!

**Comment by sykhro** [comment]
Latest commit should have fixed this, please test

**Comment by npeep** [comment]
@sykhro Still happening for me after syncing the latest commit.  Should I have to delete the DB?  (trying that now).

![image](https://cloud.githubusercontent.com/assets/6043230/17028679/fa8a8824-4f2d-11e6-8085-77488e910204.png)

**Comment by sykhro** [comment]
It doesn't disappear if the infobox is open

**Comment by npeep** [comment]
@sykhro I only opened those to show you for the screenshot - the entire screen was littered with expired 'mons.

**Comment by npeep** [comment]
OK- Yay!  Just had to delete the DB and it worked great.

**Comment by trippyhat** [comment]
I am still seeing this issue where the expired pokemons won't automatically disappear from the map.  I've deleted my db and restarted the application.

I'm using commit 6ddb0b919c35b9f03ac04d607661554493bf5670.

**Comment by trippyhat** [comment]
Hm, pulled again and it looks like 99a97f473e34ab7adc34ea4d6a5b5749c1206084 fixed this issue!
