### ISSUE TITLE
pokemon not appearing

### ISSUE THREAD

**Issue by shadow15151** [AHAAAAAAA/PokemonGo-Map#879]
when going to https:\localhost:5000 i get: secure connection failure An error occurred during a connection to localhost:5000. SSL received a record that exceeded the maximum permissible length. Error code: SSL_ERROR_RX_RECORD_TOO_LONG

http:\localhost:5000 actually does bring up a map, but there are no pokemon on said map

### Environment info
Operating System: win 7

Installed version of Python:
2.7.12

![capture](https://cloud.githubusercontent.com/assets/20580504/17026094/dbb0c19e-4f2c-11e6-9be4-0ab21b834adb.PNG)

**Comment by IQNeoXen** [comment]
why do you use https? Just try it with http://localhost:5000

**Comment by shadow15151** [comment]
if you would notice, i mentioned that i did use http://localhost:5000
no pokemon appeared

**Comment by sykhro** [comment]
the exception says it all. do you have 2-factor auth on your google account?

**Comment by IQNeoXen** [comment]
Sorry. Yeah, @sykhro is right - username or password is wrong. If you have 2 factor auth enabled, it won't work. Try it with a pokemon trainer account!

**Comment by shadow15151** [comment]
i do not have 2 factor auth on my account, but ill try with a pokemon trainer account and see if that works

**Comment by IQNeoXen** [comment]
Oh lol i just saw that you typed in `****@google.com... ` Try using `***@gmail.com`

**Comment by hedqvist** [comment]
you shouldnt enter @gmail.com at the end as username only the pre-@gmail.com

**Comment by IQNeoXen** [comment]
@hedqvist @gmail.com works fine for me...

**Comment by shadow15151** [comment]
the pokemon trainer account worked fine, thank you for your help i clearly just messed something up on my end
