### ISSUE TITLE
Installation Problems

### ISSUE THREAD

**Issue by Bellamy207** [AHAAAAAAA/PokemonGo-Map#881]
Operating System: Mac OS

Installed version of Python: 2.7.12

Hey i'm having some installation problems: 

After i input `pip install -r requirements.txt` it give me the error `Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/s_/s3zpbb_15d1b8ts5rzq2r9340000gn/T/pip-build-oxkkFg/protobuf-to-dict/`.

When i follow the next step `python runserver.py -a ptc -u B***** -p ****** -l "4x.xxxxx 9.xxxx" -st 10` it says
`File "runserver.py", line 10, in <module>
    from pogom.app import Pogom
  File "/Users/Blue/Downloads/PokemonGo-Map-develop/pogom/app.py", line 5, in <module>
    from flask import Flask, jsonify, render_template, request
ImportError: No module named flask`

Thanks in advance ;)

**Comment by Zsub** [comment]
Try running `pip` as root via `sudo`. Your complete install command becomes: `sudo -H pip install -r requirements.txt`. And then re-run the server.

**Comment by Bellamy207** [comment]
Hey, thanks for your fast response. unfortunately it didn't work. i got the same error. 

Here again my complete code 

`Collecting Flask==0.11.1 (from -r requirements.txt (line 1))
  Downloading Flask-0.11.1-py2.py3-none-any.whl (80kB)
    100% |████████████████████████████████| 81kB 2.2MB/s 
Collecting Jinja2==2.8 (from -r requirements.txt (line 2))
  Downloading Jinja2-2.8-py2.py3-none-any.whl (263kB)
    100% |████████████████████████████████| 266kB 2.5MB/s 
Collecting MarkupSafe==0.23 (from -r requirements.txt (line 3))
  Downloading MarkupSafe-0.23.tar.gz
Collecting Werkzeug==0.11.10 (from -r requirements.txt (line 4))
  Downloading Werkzeug-0.11.10-py2.py3-none-any.whl (306kB)
    100% |████████████████████████████████| 307kB 2.1MB/s 
Collecting argparse==1.2.1 (from -r requirements.txt (line 5))
  Downloading argparse-1.2.1.tar.gz (69kB)
    100% |████████████████████████████████| 71kB 6.5MB/s 
Collecting click==6.6 (from -r requirements.txt (line 6))
  Downloading click-6.6.tar.gz (283kB)
    100% |████████████████████████████████| 286kB 2.2MB/s 
Collecting itsdangerous==0.24 (from -r requirements.txt (line 7))
  Downloading itsdangerous-0.24.tar.gz (46kB)
    100% |████████████████████████████████| 51kB 4.9MB/s 
Collecting peewee==2.8.1 (from -r requirements.txt (line 8))
  Downloading peewee-2.8.1.tar.gz (474kB)
    100% |████████████████████████████████| 481kB 1.8MB/s 
Requirement already satisfied (use --upgrade to upgrade): wsgiref==0.1.2 in /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7 (from -r requirements.txt (line 9))
Collecting geopy==1.11.0 (from -r requirements.txt (line 10))
  Downloading geopy-1.11.0-py2.py3-none-any.whl (66kB)
    100% |████████████████████████████████| 71kB 6.1MB/s 
Collecting protobuf==2.6.1 (from -r requirements.txt (line 11))
  Downloading protobuf-2.6.1.tar.gz (188kB)
    100% |████████████████████████████████| 194kB 2.8MB/s 
Collecting requests==2.10.0 (from -r requirements.txt (line 12))
  Downloading requests-2.10.0-py2.py3-none-any.whl (506kB)
    100% |████████████████████████████████| 512kB 1.6MB/s 
Collecting s2sphere==0.2.4 (from -r requirements.txt (line 13))
  Downloading s2sphere-0.2.4-py2.py3-none-any.whl
Collecting gpsoauth==0.3.0 (from -r requirements.txt (line 14))
  Downloading gpsoauth-0.3.0.tar.gz
Collecting protobuf-to-dict==0.1.0 (from -r requirements.txt (line 15))
  Downloading protobuf-to-dict-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    
    Installed /private/tmp/pip-build-jqz3Or/protobuf-to-dict/nosexcover-1.0.10-py2.7.egg
    Searching for coverage
    Reading https://pypi.python.org/simple/coverage/
    Best match: coverage 4.2b1
    Downloading https://pypi.python.org/packages/ca/76/75cb8a80084dc08d373ef39a04237a658e6dcf4adeaba3fe2a9753a904e3/coverage-4.2b1.tar.gz#md5=587019c5f1a0af28c08e9e9586d5a60a
    Processing coverage-4.2b1.tar.gz
    Writing /tmp/easy_install-_eTOV9/coverage-4.2b1/setup.cfg
    Running coverage-4.2b1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-_eTOV9/coverage-4.2b1/egg-dist-tmp-bDtE8v
    warning: no previously-included files found matching 'ci/appveyor.token'
    no previously-included directories found matching 'doc/_build'
    no previously-included directories found matching 'tests/eggsrc/build'
    no previously-included directories found matching 'tests/eggsrc/dist'
    no previously-included directories found matching 'tests/eggsrc/*.egg-info'
    warning: no previously-included files matching '*.py[co]' found anywhere in distribution
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    warning: no previously-included files found matching 'ci/appveyor.token'
    no previously-included directories found matching 'doc/_build'
    no previously-included directories found matching 'tests/eggsrc/build'
    no previously-included directories found matching 'tests/eggsrc/dist'
    no previously-included directories found matching 'tests/eggsrc/*.egg-info'
    warning: no previously-included files matching '*.py[co]' found anywhere in distribution
    **
    ** Couldn't install with extension module, trying without it...
    ** BuildFailed: command 'cc' failed with exit status 1
    **
    
    Installed /private/tmp/pip-build-jqz3Or/protobuf-to-dict/coverage-4.2b1-py2.7.egg
    Searching for nose>=1.0
    Reading https://pypi.python.org/simple/nose/
    Best match: nose 1.3.7
    Downloading https://pypi.python.org/packages/58/a5/0dc93c3ec33f4e281849523a5a913fa1eea9a3068acfa754d44d88107a44/nose-1.3.7.tar.gz#md5=4d3ad0ff07b61373d2cefc89c5d0b20b
    Processing nose-1.3.7.tar.gz
    Writing /tmp/easy_install-QpRNwL/nose-1.3.7/setup.cfg
    Running nose-1.3.7/setup.py -q bdist_egg --dist-dir /tmp/easy_install-QpRNwL/nose-1.3.7/egg-dist-tmp-2r8roJ
    no previously-included directories found matching 'doc/.build'
    
    Installed /private/tmp/pip-build-jqz3Or/protobuf-to-dict/nose-1.3.7-py2.7.egg
    Searching for protobuf>=2.3.0
    Reading https://pypi.python.org/simple/protobuf/
    Best match: protobuf 3.0.0b4
    Downloading https://pypi.python.org/packages/8b/fa/2a4f48c3579a5d88bfe4e8408227cb12731efcb30da4ba423cf115a1d320/protobuf-3.0.0b4-py2.7.egg#md5=e29a69cb89fff0bc39f099e705e4e93e
    Processing protobuf-3.0.0b4-py2.7.egg
    creating /private/tmp/pip-build-jqz3Or/protobuf-to-dict/protobuf-3.0.0b4-py2.7.egg
    Extracting protobuf-3.0.0b4-py2.7.egg to /private/tmp/pip-build-jqz3Or/protobuf-to-dict
    
    Installed /private/tmp/pip-build-jqz3Or/protobuf-to-dict/protobuf-3.0.0b4-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-jqz3Or/protobuf-to-dict/setup.py", line 25, in <module>
        'Topic :: Software Development :: Libraries :: Python Modules',
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/dist.py", line 239, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/dist.py", line 263, in fetch_build_eggs
        parse_requirements(requires), installer=self.fetch_build_egg
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 580, in resolve
        raise VersionConflict(dist,req) # XXX put more info here
    pkg_resources.VersionConflict: (six 1.4.1 (/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python), Requirement.parse('six>=1.9'))
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-jqz3Or/protobuf-to-dict/
`

**Comment by Zsub** [comment]
Hmm, you might want to throw that into Google, it's not something I recognise.

**Comment by dbergey** [comment]
I had to upgrade pip to get it to work: `pip install --upgrade pip`

I also sudo'd various attempts, so YMMV.

**Comment by Bellamy207** [comment]
thanks for your advice, but still getting the same error ... :/

**Comment by apolloclark** [comment]
The error message:
```shell
 pkg_resources.VersionConflict: (six 1.4.1 (/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python), Requirement.parse('six>=1.9'))
```


You can fix this by upgrading the six package:
```shell
sudo pip install --upgrade six
```

**Comment by yturyan** [comment]
From what directory "runserver.py" should be run ?

**Comment by Bellamy207** [comment]
ok, now im getting this, when trying to install requirements 

`Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-zju3aG/pycryptodomex/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Waq6Vv-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-zju3aG/pycryptodomex/`

**Comment by jowang0319** [comment]
same error: getting this while trying to install:



> Requirement already satisfied (use --upgrade to upgrade): Flask==0.11.1 in /usr/local/lib/python3.5/site-packages (from -r requirements.txt (line 1))
> Requirement already satisfied (use --upgrade to upgrade): Jinja2==2.8 in /usr/local/lib/python3.5/site-packages (from -r requirements.txt (line 2))
> Requirement already satisfied (use --upgrade to upgrade): MarkupSafe==0.23 in /usr/local/lib/python3.5/site-packages (from -r requirements.txt (line 3))
> Requirement already satisfied (use --upgrade to upgrade): Werkzeug==0.11.10 in /usr/local/lib/python3.5/site-packages (from -r requirements.txt (line 4))
> Collecting argparse==1.2.1 (from -r requirements.txt (line 5))
>   Using cached argparse-1.2.1.tar.gz
> Requirement already satisfied (use --upgrade to upgrade): click==6.6 in /usr/local/lib/python3.5/site-packages (from -r requirements.txt (line 6))
> Requirement already satisfied (use --upgrade to upgrade): itsdangerous==0.24 in /usr/local/lib/python3.5/site-packages (from -r requirements.txt (line 7))
> Requirement already satisfied (use --upgrade to upgrade): peewee==2.8.1 in /usr/local/lib/python3.5/site-packages (from -r requirements.txt (line 8))
> Collecting wsgiref==0.1.2 (from -r requirements.txt (line 9))
>   Using cached wsgiref-0.1.2.zip
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/private/tmp/pip-build-b3qt2rsi/wsgiref/setup.py", line 5, in <module>
>         import ez_setup
>       File "/private/tmp/pip-build-b3qt2rsi/wsgiref/ez_setup/__init__.py", line 170
>         print "Setuptools version",version,"or greater has been installed."
>                                  ^
>     SyntaxError: Missing parentheses in call to 'print'
>     
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-b3qt2rsi/wsgiref/

**Comment by m-i-k-e** [comment]
I am getting the same bug

Mac os 10.11.6
python 2.7.10

![error](https://cloud.githubusercontent.com/assets/965789/17028271/fc106002-4f5e-11e6-850f-2b42028df340.png)

I have did this:
`sudo -H pip install --ignore-installed six`

and this:
`pip install --upgrade pip`

and it still says flask is missing.

**Comment by apolloclark** [comment]
Mac OSX has an issue with how Python is installed by default, doesn't allow user modification. So, you'll need to install Python into a different folder. Here's details and a solution:

http://apple.stackexchange.com/a/209583

**Comment by m-i-k-e** [comment]
I've installed python with brew just before installing.

**Comment by m-i-k-e** [comment]
I see it's a bit more complicated. I'll try and uninstall the pre-provided Apple python

**Comment by apolloclark** [comment]
@m-i-k-e
Try this command:
```shell
sudo python -m pip install --upgrade six
```

What is the output of the following commands?

```shell
sw_vers -productVersion
python --version
which python
echo $PYTHONPATH;
pip show six
```

**Comment by jowang0319** [comment]
@apolloclark 
I tried the brew install and it worked! thx

**Comment by susanvs** [comment]
'sudo' is not recognized as an internal or external command,
operable program or batch file.

**Comment by apolloclark** [comment]
@jowang0319 glad to hear! :) Brew installs a secondary instance of python into a different folder that you are able to update.

**Comment by yturyan** [comment]
What about Linux ? System don't see the pyserver.py file...

**Comment by yturyan** [comment]
python: can't open file 'runserver.py': [Errno 2] No such file or directory

**Comment by susanvs** [comment]
I am also getting that error: python: can't open file 'runserver.py': [Errno 2] No such file or directory

**Comment by susanvs** [comment]
Great! lots of help here!

**Comment by mrDinckleman** [comment]
@susanvs 
Try to install dev-branch, copy credentials.json from master-branch to your project and start server
This helped for me

**Comment by susanvs** [comment]
@mrDinckleman Okay I shall give that a try. Thank you.

**Comment by Bellamy207** [comment]
@apolloclark: the brew worked for me as well. 

but still gettingt the "python: can't open file 'runserver.py': [Errno 2] No such file or directory" error, when trying to start the server. 

Also tried your advice @susanvs. The runserver.py was now be found, but now it says:
```
File "runserver.py", line 10, in <module>
    from pogom.app import Pogom
  File "/Users/Blue/Downloads/PokemonGo-Map-develop/pogom/app.py", line 10, in <module>
    from .models import Pokemon, Gym, Pokestop
  File "/Users/Blue/Downloads/PokemonGo-Map-develop/pogom/models.py", line 5, in <module>
    from peewee import Model, SqliteDatabase, InsertQuery, IntegerField,\
ImportError: No module named peewee


```

**Comment by susanvs** [comment]
@Bellamy207 I have also got that error message now. 
Traceback (most recent call last):
  File "runserver.py", line 10, in <module>
    from pogom.app import Pogom
  File "C:\PokemonGo-Map-develop\pogom\app.py", line 10, in <module>
    from .models import Pokemon, Gym, Pokestop
  File "C:\PokemonGo-Map-develop\pogom\models.py", line 5, in <module>
    from peewee import Model, SqliteDatabase, InsertQuery, IntegerField,\
ImportError: No module named peewee

**Comment by fuzha** [comment]
how if error like this? 

`    /usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DLTC_NO_ASM -Isrc/ -I/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c src/MD2.c -o build/temp.macosx-10.6-intel-2.7/src/MD2.o
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    error: command '/usr/bin/clang' failed with exit status 1`

**Comment by fuzha** [comment]
how if error like this?

>     /usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DLTC_NO_ASM -Isrc/ -I/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c src/MD2.c -o build/temp.macosx-10.6-intel-2.7/src/MD2.o
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    error: command '/usr/bin/clang' failed with exit status 1

**Comment by m-i-k-e** [comment]
@apolloclark 

> sudo python -m pip install --upgrade six
Password:
/usr/bin/python: No module named pip
$ sw_vers -productVersion
10.11.6
$ python --version
Python 2.7.10
$ which python
/usr/bin/python
$ echo $PYTHONPATH;
$ pip show six
---
Metadata-Version: 2.0
Name: six
Version: 1.10.0
Summary: Python 2 and 3 compatibility utilities
Home-page: http://pypi.python.org/pypi/six/
Author: Benjamin Peterson
Author-email: benjamin@python.org
Installer: pip
License: MIT
Location: /usr/local/lib/python2.7/site-packages
Requires: 
Classifiers:
  Programming Language :: Python :: 2
  Programming Language :: Python :: 3
  Intended Audience :: Developers
  License :: OSI Approved :: MIT License
  Topic :: Software Development :: Libraries
  Topic :: Utilities
$

**Comment by m-i-k-e** [comment]
@apolloclark doesn't look like i'm using the brew version. Do you know how to disable/remove the apple python?

**Comment by apolloclark** [comment]
@m-i-k-e don't remove the Apple python version, it's used by various system services.

Yeah, use the brew version of python, it's the better option on Mac versus installing it from scratch.

**Comment by TheBrain0110** [comment]
@m-i-k-e Uninstalling the system python is a terrible idea, and probably impossible anyway.

I just finished dealing with this bug myself. At least, the first bug posted in this thread, about packages not being found because the install failed to complete; many people have jumped on with unrelated issues, including windows users.

In my case it was `protobuf-to-dict` that wanted `six >=1.10.0`, and the system version was 1.4.1, and no amount of `--ignore-installed six --user --upgrade` would make it use another one.

It comes from a combination of OS X 10.11 El Capitan's System Integrity Protection, which prevents modifying /System even under root/sudo, and the system python coming with older versions of frameworks, and sys.path putting those default system packages first, even if you install another version in another location.

Using homebrew to install a separate python is a good option to get around that.

It's also possible to use a .pth file in /Library/Python/2.7/site-packages, as explained [here][http://apple.stackexchange.com/a/210021/216].
(Personally, I made it the contents of the .pth file `import sys; sys.path = ['/Users/<yourusername>/Library/Python/2.7/lib/python/site-packages','/Library/Python/2.7/site-packages'] + sys.path`, replacing <yourusername> appropriately. It should find user packages anyway, but just to be sure.)

That's what I did, and it worked fine. You then just have to run `pip install six --upgrade` either with sudo to install to /Library/Python, or with --user to install to your home dir.
Then run the PokemonGoMap installer as usual, probably with `--upgrade` and either `--user` or as sudo.

**Comment by fuzha** [comment]
ok, i fix my error with this :)

`xcode-select --install`

**Comment by Bellamy207** [comment]
Any idea how to get along with the peewee module import error when starting the server?

**Comment by m-i-k-e** [comment]
@apolloclark 
Still getting the flask error 

Does this look correct?

`$ python -m site
sys.path = [
    '/Users/mike/Library/Python/2.7/lib/python/site-packages',
    '/Library/Python/2.7/site-packages',
    '/Users/mike',
    '/Users/mike/Library/Python/2.7/lib/python/site-packages',
    '/Library/Python/2.7/site-packages',
    '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip',
    '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7',
    '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin',
    '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac',
    '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages',
    '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python',
    '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk',
    '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old',
    '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload',
    '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC',
]
USER_BASE: '/Users/mike/Library/Python/2.7' (exists)
USER_SITE: '/Users/mike/Library/Python/2.7/lib/python/site-packages' (exists)
ENABLE_USER_SITE: True`

**Comment by m-i-k-e** [comment]
@apolloclark I ran 
`which python`

and got

`/usr/bin/python`

So I looked here:

[https://stackoverflow.com/questions/5157678/python-homebrew-by-default](url)

and took their advice to move /usr/local/bin to the top.

It now runs :)

Is this a really bad thing to do?

**Comment by Seb-AS** [comment]
fixed same issue on mac using export PATH=/usr/local/bin:/usr/local/sbin:~/bin:$PATH

**Comment by mehdi-S** [comment]
fixed OP problem on Debian 8 with :

**apt-get install sudo**
**sudo -H pip install --ignore-installed six**
**sudo** pip install -r requirements.txt

in **bold** are the new step gather in this post

**Comment by pokedev** [comment]
i was able to fix this problem with :

```
brew install python
sudo -H pip install -r requirements.txt
```

**Comment by ClickerMonkey** [comment]
@m-i-k-e 

I got rid of the flask error by adding this to `~/.bash_profile`:

```bash
export PYTHONPATH=`brew --prefix`/lib/python2.7/site-packages:$PYTHONPATH
```

Once added, I made sure it was ran in the current session with `. ~/.bash_profile`

**Comment by mhelmetag** [comment]
For people on OSX and Linux, I really really recommend using virtualenv and virtualenvwrapper so that you can section off different Python projects and not totally hose your system installed Python.

**Comment by jeafke** [comment]
I can't help myself for saying this. But when you're at the point of writing something here because your not getting it to work instantly... You might try to Google first and read about the utter basic stuff... If you don't want to put some time and effort into it, just drop the idea and keep walking. This distracts the developers from doing their goal. This is just absolutely not the right place for asking how to get a python interpreter running IMHO

**Comment by sheikhsabayyal** [comment]
Everything is working fine except the location. The script is reading only first word of location. 

E.g if I write Manhattan, New York 
it gives error  like "runserver.py: error: unrecognized arguments: New York 

Only works with a single word. Any solution to this?

**Comment by Dotard** [comment]
"Manhattan, New York"
