### ISSUE TITLE
Not showing all pokemons

### ISSUE THREAD

**Issue by tr1p0z** [AHAAAAAAA/PokemonGo-Map#883]
Last time this tool dont show Arcanine with level 1900 :/

**Comment by tr1p0z** [comment]
And now -i is deleted in the last version

**Comment by DerScreever** [comment]
@tr1p0z -i will be back soon

**Comment by tr1p0z** [comment]
Sometimes is not showing all pokemons, im sure about that

**Comment by aviel600** [comment]
had same issue, https://github.com/AHAAAAAAA/PokemonGo-Map/issues/819
still couldnt solve it.
my map miss a lot of pokemons, for example it show me 3 pokemons in some step although there are 5

**Comment by tr1p0z** [comment]
A test:
https://gyazo.com/6531632f40d70c4a2c15d7c0f3711aaa
https://gyazo.com/b77e06c27e3878276c95588c74bbf3da

**Comment by trippyhat** [comment]
This might be an issue with the search being too wide. See https://github.com/AHAAAAAAA/PokemonGo-Map/issues/910
