### ISSUE TITLE
File runserver.py line 62, doesn't start

### ISSUE THREAD

**Issue by marazmatik** [AHAAAAAAA/PokemonGo-Map#885]
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discord.gg/Kzp4yky).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:
Ubuntu 16.04
4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Installed version of Python:
Python 2.7.12

### Steps to reproduce
1. clean install
2. python runserver.py -a google -u username -p password -l "Russia, Korolev" -st 4

### What have you tried?
1.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

Traceback (most recent call last):
  File "runserver.py", line 62, in <module>
    config['GMAPS_KEY'] = load_credentials(os.path.dirname(os.path.realpath(__file__)))['gmaps_key']
  File "/home/nick/pkgo/dev/PokemonGo-Map/pogom/utils.py", line 104, in load_credentials
    with open(filepath+os.path.sep+'credentials.json') as file:
IOError: [Errno 2] No such file or directory: '/home/nick/pkgo/dev/PokemonGo-Map/credentials.json'

**Comment by ChristianLuxem** [comment]
You need to rename the credentials.example.json to credentials.json. 
After that you will get the next Step. Create a Javascript Google Maps API Key and paste it into.
