### ISSUE TITLE
Error when run server

### ISSUE THREAD

**Issue by hellb0y8577** [AHAAAAAAA/PokemonGo-Map#886]
At the first time i run the command python runserver.py -a ptc -u [USERNAME] -p [PASSWORD] -l "[LOCATION]" -st 10, it worked fine. But the second time I try to re-run the command and command promt said: python: can't open file 'runserver.py': [Errno 2] No such file or directory.

Can anybody help me please, thank you.

**Comment by DerScreever** [comment]
maybe you are not on develop?

**Comment by Owneryt** [comment]
help me 
![default](https://cloud.githubusercontent.com/assets/20580518/17026314/5880a744-4f68-11e6-9250-0f4e3728d8f6.png)

**Comment by yturyan** [comment]
The same for me...
python: can't open file 'runserver.py': [Errno 2] No such file or directory

**Comment by Yoora87** [comment]
I had the same problem, change runserver.py into example.py and it should work

**Comment by mkody** [comment]
If you can't find the runserver.py, it's because you're not using the `devlop` branch.

**Comment by hellb0y8577** [comment]
Argg, thank you guys. How silly I am.
