### ISSUE TITLE
Could not retrieve token

### ISSUE THREAD

**Issue by lulzz1337** [AHAAAAAAA/PokemonGo-Map#888]
Hi guys

So I've wanted to try this map out, but running in a authentication problem, please see below.
Maybe this dosent work in my country?

### Environment info
Operating System: Win 10

Installed version of Python:
3.27

### Steps to reproduce
Run server

### What have you tried?
1. created the pokemon trainer, can login successfully from the app.

### Logs or other output that would be helpful
See attached, error:
2016-07-21 16:38:15,032 [   auth_ptc] [  ERROR] Could not retrieve token: Your username or password is incorrect. You have 2 attempts left before you will be locked out of your account for 15 minutes.

I can successfully login the app with used username and password.

**Comment by fust** [comment]
Are you trying to sign in to a PTC account or a Google one? Make sure you're using the correct auth mechanism

**Comment by MRokas** [comment]
Could we see what arguments you're using?

**Comment by lulzz1337** [comment]
I'm using a newly created PTC account, where I can login to both the site (https://club.pokemon.com) and the app. 
Argument im calling is in attached, but im using: python runserver.py -a ptc -u [lulzz1337] -p [xxxxxx] -l "[maarslet, Denmark]" -st 10
 Im using PokemonGo-Map-develop
