### ISSUE TITLE
GMAPS_KEY issue... In develop

### ISSUE THREAD

**Issue by Siyfion** [AHAAAAAAA/PokemonGo-Map#889]
Without specifying my own Google Maps API Key I get the following:

```
Traceback (most recent call last):
  File "runserver.py", line 62, in <module>
    config['GMAPS_KEY'] = load_credentials(os.path.dirname(os.path.realpath(__file__)))['gmaps_key']
  File "/Users/siyfion/Git/PokemonGo-Map/pogom/utils.py", line 104, in load_credentials
    with open(filepath+os.path.sep+'credentials.json') as file:
IOError: [Errno 2] No such file or directory: '/Users/siyfion/Git/PokemonGo-Map/credentials.json'
```

When I attempted to use my own key, I just seems to get a "Something went wrong" screen, though I'm not 100% certain I set the key up correctly.

**Comment by LucasAdam** [comment]
Are you sure you renamed credentials.example.json into credentials.json

**Comment by PokeDon** [comment]
Also inside the file : Key should look like this ...

{
	"gmaps_key" : "AIzaSyCtIs3sjAFdziTiGpBokDXfXxqqCZZZZ"
}

and make sure the file is called

**Comment by Siyfion** [comment]
@LucasAdam Nope! But I didn't see that I had too... my bad! :/

**Comment by Siyfion** [comment]
@LucasAdam Now I'm just getting this... What sort of API key is required? Browser or Server?

![screen shot 2016-07-21 at 15 56 26](https://cloud.githubusercontent.com/assets/338488/17027413/b5534024-4f5b-11e6-91f2-bd5b18826260.png)

**Comment by Siyfion** [comment]
Ignore me... I missed the section in the Wiki on API keys!
