### ISSUE TITLE
The scanner stop working after about 10 minutes

### ISSUE THREAD

**Issue by IAmYeled** [AHAAAAAAA/PokemonGo-Map#893]
When I am at home, it doesn't bother me that much becuse I stop the command and restarting it.
But when im using this via my phone I can't do it.
Is there any way to reload the command automatically or something like this?

**Comment by Sejadis** [comment]
in dev branch this seems to be fixed so i guess you use the master branch?
if so it would probably best to switch to dev branch

**Comment by IAmYeled** [comment]
@Sejadis How do I swich do dev branch?

**Comment by Sejadis** [comment]
https://github.com/AHAAAAAAA/PokemonGo-Map/tree/develop

**Comment by IAmYeled** [comment]
@Sejadis Im not a fan of the Dev tool, the black map and I can't ignore pokemons... Is'nt there other way to do this?
