### ISSUE TITLE
OperationalError: table gym has no column named gym_points

### ISSUE THREAD

**Issue by djderan** [AHAAAAAAA/PokemonGo-Map#894]
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discord.gg/Kzp4yky).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:

Installed version of Python:
2.7

### Steps to reproduce
1. Just logging in with standard parameters
2. Dev branch
3.

### What have you tried?
1.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by Sejadis** [comment]
delete the  pogom.db

**Comment by CarlTaylor1989** [comment]
Yep delete pogom.db, closing this.

**Comment by djderan** [comment]
I did not have that file in the project and I am getting the same issue with pokestops
