### ISSUE TITLE
After server running for 3 hrs, get [-] retrying_get_profile: get_profile returned no-len payload, retrying

### ISSUE THREAD

**Issue by actondong** [AHAAAAAAA/PokemonGo-Map#895]
The is bug initially is, after running around 1 hr, no pokemon show out any more.

The fix I applied is, remove @momorize above login() method 

This fix works, now the server perform sound longer,

after 3 hrs, new issue pop out
keeping getting below error in logs
[-] retrying_get_profile: get_profile returned no-len payload, retrying

Also, solved by restart server of course

**Comment by actondong** [comment]
personally I want to draw more attention to this issue. This is also mentioned in a closed issue but never solved.  This is closely related to #625 which is closed

**Comment by der-eismann** [comment]
Can cornfirm. Removing [@memoize](https://github.com/AHAAAAAAA/PokemonGo-Map/blob/master/example.py#L505) helps letting the map run longer than 30-60 minutes. But after a longer period I get the same error as described above.
