### ISSUE TITLE
Is there some extra code to write if I have to search for pokestops and gyms .

### ISSUE THREAD

**Issue by ashish2612** [AHAAAAAAA/PokemonGo-Map#897]
Please do not respond by saying that there may be no gyms around you because I am pretty sure there are.. please also provide code if it is required.thnks

**Comment by JKapitein** [comment]
There are now sliders in the menu that will toggle Gyms and Pokestops

**Comment by ashish2612** [comment]
Do i need to download new code from here @JKapitein . Because there is no menu showing in my map

**Comment by DerScreever** [comment]
@ashish2612 just download the latest version of our develop branch

**Comment by ashish2612** [comment]
can u give me the link from where i can download latest version

**Comment by JKapitein** [comment]
https://github.com/AHAAAAAAA/PokemonGo-Map/tree/develop


Press the clone or download button on the right, and then select Download ZIP
