### ISSUE TITLE
Error in line 3

### ISSUE THREAD

**Issue by dosenhosenjoe** [AHAAAAAAA/PokemonGo-Map#9]
Hello 
when i try to python example-py i get this error:
Traceback (most recent call last):
  File "example.py", line 3, in <module>
    from flask import Flask, render_template
ImportError: No module named flask
Help ? :D

**Comment by theryangeary** [comment]
Did you remember to run "pip install -r requirements.txt"?

**Comment by dosenhosenjoe** [comment]
I almost got it to work but when i go to localhost i get this error: https://i.imgur.com/6U8ssyc.png

**Comment by mattmmeloan** [comment]
That happens when pokemon club is down. Just wait a little while for servers to come back up and try again.

**Comment by marauder37** [comment]
Code was just merged to fix this, give it a try

**Comment by sykhro** [comment]
You need to use Python 2.7
