### ISSUE TITLE
Unrecognized Call Error 

### ISSUE THREAD

**Issue by Slimshady124** [AHAAAAAAA/PokemonGo-Map#900]
example.py: error: unrecognized arguments: calls

I get this error every time I start the search. I'm a noob to python so if there's something really simple I'm missing, please don't roast me. 

### Environment info
Operating System: Windows 10 

Installed version of Python: Python 2.7

### Steps to reproduce
1.Start the search

### What have you tried? - 

And I'm from India so we don't officially have the game yet. I thought that could be the reason but i'm not too sure.

**Comment by DerScreever** [comment]
try it with the develop branch pls. we droppen the support for master branch
