### ISSUE TITLE
too many sql variables(not duplicate)

### ISSUE THREAD

**Issue by Vitaliy66** [AHAAAAAAA/PokemonGo-Map#901]
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discord.gg/Kzp4yky).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:windows 10

Installed version of Python:2.7.3

### Steps to reproduce
1.
2.
3.

### What have you tried?
1.Delete pogom file

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).
![1](http://clip2net.com/clip/m406990/3e056-clip-23kb.png?nocache=1)

**Comment by sykhro** [comment]
Delete pogom.db, pull latest and retry

**Comment by Vitaliy66** [comment]
@sykhro I said that it doesn't work for me

**Comment by Vitaliy66** [comment]
Help someone please

**Comment by hexus** [comment]
@sykhro's advice fixed some database errors I was getting. Might be worth putting this in the FAQ because I would have otherwise had no idea to delete that file.
