### ISSUE TITLE
No module named flask ??

### ISSUE THREAD

**Issue by TheDarkMonster62** [AHAAAAAAA/PokemonGo-Map#905]
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discord.gg/Kzp4yky).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System: Windows 8.1

Installed version of Python: 2.7.12

### Steps to reproduce
1. Can't run the server
2.
3.

### What have you tried?
1. python runserver.py -a ptc -u ******** -p ********* -l "********* ********" -st 10 
--------------------------------------
OUTPUT OF THE COMMAND : 
 (Traceback (most recent call last):
  File "runserver.py", line 10, in <module>
    from pogom.app import Pogom
  File "C:\Users\ThÚo\Desktop\PokemonGo-Map-develop\pogom\app.py", line 5, in <m
odule>
    from flask import Flask, jsonify, render_template, request
ImportError: No module named flask)
----------------------------------------
### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

To install the requirements i ran this command : 
@echo off
C:\Python27\python get-pip.py
cd ..
C:\Python27\Scripts\pip install -r requirements.txt
C:\Python27\Scripts\pip install -r requirements.txt --upgrade
rename credentials.json credentials.json
set /p API= Enter your Google API key here:

    (
    echo {
    echo "gmaps_key" : "%API%"
    echo }
    ) > credentials.json
The output is : http://pastebin.com/H1wDWJvu
When i enter my google API key the cmd closes ...

I don't know what to do now . 
Any help is appreciated .

**Comment by fettlaus** [comment]
I suspect, that Python has problems with your user name. Try to move your PokemonGo-Map folder to C:\

There were even errors thrown while installing the requirements so you may need to do this step again.

**Comment by TheDarkMonster62** [comment]
I moved the folder to C:\PokemonGo-Map-develop
I tried to delete pip in scripts and i deleted lib/site-packages but it is still giving me the error http://pastebin.com/aYy5snt8

**Comment by TheDarkMonster62** [comment]
Why did you close this ??!

**Comment by fettlaus** [comment]
\xe9 ist the code for é. Are you sure that this letter isn't used somewhere?

**Comment by TheDarkMonster62** [comment]
I will check again tomorrow but i think not ...
