### ISSUE TITLE
Change of location by moving around the map

### ISSUE THREAD

**Issue by clinton2111** [AHAAAAAAA/PokemonGo-Map#906]
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discord.gg/Kzp4yky).
To make bug reports easy to find and organised, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System: Windows 10

Installed version of Python:
2.7

### Steps to reproduce
1.
2.
3.

### What have you tried?
1.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).
it would be awesome if there was a way to change your location by just moving around the map instead of starting and adding the new locations in the terminal every time.

**Comment by DerScreever** [comment]
we are working on this.

**Comment by clinton2111** [comment]
Ty so much for making this :+1:
