### ISSUE TITLE
Develop branch -> search parameters needs a correction

### ISSUE THREAD

**Issue by noaqzz** [AHAAAAAAA/PokemonGo-Map#910]
>  yield (x * 0.0025 + initial_location[0], y * 0.0025 + initial_location[1], 0)

The standard search parameter in the develop branch is 0.0025 and is not that accurate.
Less pokemons are showing up.

I did a test with .0005, .0010, .0015, .0020 and .0025. 
Using .0015 seems to be the best choice. I almost missed a Lapras when using .0025 ><

**Comment by fettlaus** [comment]
See my issue regarding this  #903
