### ISSUE TITLE
Pokemons don't dissappear after changing the location

### ISSUE THREAD

**Issue by lnmtriet93** [AHAAAAAAA/PokemonGo-Map#911]
Like title, pokemons don't dissappear after changing the location. That meand everytime I stopped the command prompt and re-enter new command with new location argument,

**Comment by docrockulus** [comment]
You can delete the pogom.db in the same folder as runserver.py to remove all previously collected entries.

**Comment by HinoReo** [comment]
I think it is a feature to cover more map. I launch 3 processes simultaneously and since I am able to forward only one of it to ngrok, it is quite handy to have the pokemons there. Also, they will go away when expired, or yes, you can delete pogom.db

**Comment by lnmtriet93** [comment]
Thank @docrockulus and @HinoReo 
I knowed that we could delete pogom.db but it's a little of annoyed. Too much pokemons may cause a lag to my computer :(
