### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 'C:\\Users\\RADIOHEAD\\Desktop\\PokemonGo-Map-develop\\credentials.json'

### ISSUE THREAD

**Issue by Jshak** [AHAAAAAAA/PokemonGo-Map#912]
Traceback (most recent call last):
  File "runserver.py", line 62, in <module>
    config['GMAPS_KEY'] = load_credentials(os.path.dirname(os.path.realpath(__file__)))['gmaps_key']
  File "C:\Users\RADIOHEAD\Desktop\PokemonGo-Map-develop\pogom\utils.py", line 104, in load_credentials
    with open(filepath+os.path.sep+'credentials.json') as file:
IOError: [Errno 2] No such file or directory: 'C:\\Users\\RADIOHEAD\\Desktop\\PokemonGo-Map-develop\\credentials.json'

**Comment by Sejadis** [comment]
tell is how you run the script - there is a typo somewhere

**Comment by Jshak** [comment]
@Sejadis i found the mistake in this one but am stuck in

IOError: [Errno 2] No such file or directory: 'C:\\Users\\RADIOHEAD\\Desktop\\PokemonGo-Map-develop\\credentials.json'

this one

**Comment by Sejadis** [comment]
rename the credentials.example.json and put your api key in
guide to that is on the wiki page

**Comment by wildpoopling** [comment]
I got the same error as Jshak - do you have an example of syntax for renaming?

**Comment by Rohmin** [comment]
just rename credentials.example.son to credentials.json and put your google API key in there

**Comment by rezz3x** [comment]
Or just use the Argument -k to define you Google API Key.

**Comment by Jshak** [comment]
lolz guys now stuck in 
"No Google Maps Javascript API key entered in credentials.json file!"
pogom.exceptions.APIKeyException: No Google Maps Javascript API key entered in credentials.json file! Please take a look at the wiki for instructions on how to generate this key, then add that key to the file!
how do we add api,... please help

**Comment by Jshak** [comment]
@Sejadis @Rohmin @rezz3x :bread:

**Comment by andrewda** [comment]
https://github.com/AHAAAAAAA/PokemonGo-Map/blob/develop/credentials.example.json

There's literally only one spot to put the key... You put it there.

**Comment by wildpoopling** [comment]
yup got it

**Comment by Jshak** [comment]
@wildpoopling so what did you put there haha??

**Comment by Sejadis** [comment]
the error EXACTLY tells you what to do

**Comment by Jshak** [comment]
@sejadis lol never did this before so..
how do you get the api??

what do you put in there??
{
	"gmaps_key" : ""
}

**Comment by Sejadis** [comment]
@wildpoopling  create an browser key

**Comment by Jshak** [comment]
hey i got it BTW googling helped

**Comment by wildpoopling** [comment]
@Sejadis I thought that was the issue - made a browser key - still seems to be a login issue 

<img width="563" alt="screen shot 2016-07-21 at 12 46 44 pm" src="https://cloud.githubusercontent.com/assets/20582430/17031292/485e2ae8-4f41-11e6-9a5d-68edbeebe43a.png">
<img width="557" alt="screen shot 2016-07-21 at 12 47 59 pm" src="https://cloud.githubusercontent.com/assets/20582430/17031307/5fbbc222-4f41-11e6-8d9d-6017ec1cc27b.png">

**Comment by wildpoopling** [comment]
@Jshak 

so you made a browser key from API and copied pasted between the "" in the credentials then ran the command 

python runserver.py -a ptc -u [USERNAME] -p [PASSWORD] -l "[LOCATION]" -st 10

with pokemon website login, yes?

**Comment by Sejadis** [comment]
ok that message was ptc related not api key
i guess you just mistyped your login info

**Comment by wildpoopling** [comment]
well thats weird - i'll take a look. reset login on pokemon website and typed exactly that...

**Comment by Zitgard** [comment]
@wildpoopling Maybe you put your nickname in brackets? Like : [Yourname] instead of Yourname? (worked for me)
