### ISSUE TITLE
Error : unrecognized arguments

### ISSUE THREAD

**Issue by jeckoz** [AHAAAAAAA/PokemonGo-Map#913]
guys, please help, when i set location -L with minus(-) latitude or longitude it says : Error : unrecognized arguments.

how to set location with minus latitude or longitude

**Comment by fettlaus** [comment]
Location is set with a lowercase L

**Comment by Nicknack1234** [comment]
You just put the lat and long in side quotes, My arguments with negative latitude works
`runserver.py -a google -u **** -p **** -st 1 -l "-31.79041999999999, 115.7481"`

**Comment by jeckoz** [comment]
thanks nicknack1234, i love u

**Comment by jeckoz** [comment]
ohh wait, location work, but no pokemon showed UP. whats wrong?

**Comment by Sejadis** [comment]
tell us what you write to run the script
