### ISSUE TITLE
Google Account instead of Pokemon Trainer Club possible?

### ISSUE THREAD

**Issue by Lenny188** [AHAAAAAAA/PokemonGo-Map#918]
Is there any Chance that this Code is not using the Trainer Club but my google Account since I  created a new Account to try this out but all I see are really weak pokemons and I think the map will look a lot different with my 22 EP Account ;) 

Greets!

**Comment by Nicknack1234** [comment]
Yes, Its in the docco, `-a google -u username -p password`

**Comment by sykhro** [comment]
It's already there, and documented.

p.s: I'm not marking this as "big book of learn how to read" because you have been one of least annoying with this type of issue so far :p

**Comment by Sejadis** [comment]
and no the map will look the same no matter what account you use
