### ISSUE TITLE
error: argument -st/--step-limit is required

### ISSUE THREAD

**Issue by neobithia** [AHAAAAAAA/PokemonGo-Map#919]
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discord.gg/Kzp4yky).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System: Windows 10 Pro, Version 1511, Build 10586.494

Installed version of Python: 2.7.12

### Steps to reproduce
1. Run the command "like normal"
`python example.py -a ptc -u ****** -p ****** -l **.******,**.******" -st 10`
2. try different values in st argument: 5, 10, 15, 20
3. none of them work?

### What have you tried?
1. Running the command "bare" with only the minimum required arguments.
2. I'm using my own Google API Key.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).
`example.py: error: argument -st/--step-limit is required`

**Comment by sykhro** [comment]
example.py is no longer supported, please use the develop branch

**Comment by neobithia** [comment]
Thanks sykhro!

I'm using the develop branch but now I get this error?

`ImportError: No module named peewee`

**Comment by neobithia** [comment]
Thanks I closed this.  But, the wiki says the Master branch is for stable builds, so wouldn't it still be supported?

https://github.com/AHAAAAAAA/PokemonGo-Map/wiki

Just curious, that's all.  I'll move to the dev branch.
