### ISSUE TITLE
Pokemon Icons too small in windows on HiDPi

### ISSUE THREAD

**Issue by abderrahmane-tj** [AHAAAAAAA/PokemonGo-Map#92]
![pogo](https://cloud.githubusercontent.com/assets/302837/16915485/a4cc91c4-4cef-11e6-9946-a380c61735f6.png)

**Comment by haagiboy88** [comment]
We have already resized them by Rainz in the discord. Just waiting for him to upload them and do a pull request.

**Comment by abderrahmane-tj** [comment]
@haagiboy88 thanks for the quick reply, very cool project btw ^^

**Comment by CarlTaylor1989** [comment]
Closing.
