### ISSUE TITLE
can i upload to hosting and use domain?

### ISSUE THREAD

**Issue by jeckoz** [AHAAAAAAA/PokemonGo-Map#925]
How to make this script online on hosting and domain?
can some one tell me?
pls

**Comment by chnateag** [comment]
Hi,

just run the script with -H public_ip

**Comment by FrostTheFox** [comment]
If -H public_ip doesn't work for you, just do -H 0.0.0.0

**Comment by Lenny188** [comment]
I ran the Script with -H 0.0.0.0 but how can I hope it on my iPhone??

**Comment by talentedmrripley** [comment]
@Lenny188 on your iPhone go to http://domainorIPofyourserver:5000  Assuming that you have no firewall blocking ports that should take you to the map.
