### ISSUE TITLE
Unrecognized arguments when trying to lookup specific Pokemon

### ISSUE THREAD

**Issue by clinton2111** [AHAAAAAAA/PokemonGo-Map#928]
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discord.gg/Kzp4yky).
To make bug reports easy to find and organised, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System: Windows 10 Home Single Language

Installed version of Python:
2.7

### Steps to reproduce
1.
2.
3.

### What have you tried?
1. python runserver.py -a google -u c******@gmail.com -p ********* -l "15.497875 73.807478" -st 5000 -o "Electabuzz,Gengar,Dragonite" -ar AUTO_REFRESH -k *My Gmpas Key*

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).
I get this when I run the above command in cmd to search for specific Pokemon. I have tried removing the separating comma in between the Pokemon names but same issue

usage: runserver.py [-h] [-a AUTH_SERVICE] -u USERNAME [-p PASSWORD] -l
                    LOCATION -st STEP_LIMIT [-H HOST] [-P PORT] [-L LOCALE]
                    [-c] [-d] [-m] [-k GMAPS_KEY]
runserver.py: error: unrecognized arguments: -o Electabuzz,Gengar,Dragonite

**Comment by Sejadis** [comment]
the -i and -o flags arent implemented right now
