### ISSUE TITLE
Could not get profile

### ISSUE THREAD

**Issue by TheLuBu** [AHAAAAAAA/PokemonGo-Map#93]
[!] login for: xxxxxxx
[+] RPC Session Token: TGT-7074092-YLxzoNm5GppyA ...
[-] get_api_endpoint: calling get_profile
[+] Received API endpoint: https://pgorelease.nianticlabs.com/plfe/139/rpc
[-] Ooops...
Exception in thread search_thread:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\PoGo\example.py", line 372, in main
    raise Exception("Could not get profile")
Exception: Could not get profile

### Environment info
Windows 10

Installed version of Python:
2.7

### Steps to reproduce
1.
2.
3.

### What have you tried?
1. Starting and restarting the script

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by lorddusk** [comment]
Servers are being hammered, so keep trying, eventually you will get through.

**Comment by DerScreever** [comment]
i can get my profile. so must be a server problem

**Comment by CarlTaylor1989** [comment]
Closing for now
