### ISSUE TITLE
Tiny Pokemon Icons 

### ISSUE THREAD

**Issue by npeep** [AHAAAAAAA/PokemonGo-Map#930]
After the latest commit or so (6ddb0b9 ?) all of the pokemon icons are noticeably smaller, and do stay small after zooming in.  I don't think its always been this way..

Zoomed in on little pokemon:
![image](https://cloud.githubusercontent.com/assets/6043230/17030802/de254256-4f36-11e6-916a-f7d37ae1cc25.png)

Zoomed out on same pokemon:
![image](https://cloud.githubusercontent.com/assets/6043230/17030819/edcec8bc-4f36-11e6-9be0-d297f919ea08.png)

### Environment info
Operating System: Win 10, Chrome Version 52.0.2743.82 m (64-bit)

Installed version of Python: 2.7

### Steps to reproduce
1. Look at the 'mons.
2. Zoom on the 'mons.

### What have you tried?
1.  Deleting DB, re-cloning latest commit.  Closing/relaunching chrome, force refreshes..

**Comment by sykhro** [comment]
It has always been like this, gmap markers don't get bigger with zoom...

**Comment by npeep** [comment]
Okilee dokilee.  Did the markers get reduced in size during one of the commits?  They just seem less legible to me.  Can't hardly tell a dodrio from a doduo.

**Comment by Heavywavez** [comment]
Think thats more personal issue, i have no problems to see what pokemon is.

**Comment by QuadTog** [comment]
Try replacing your icon directory with this:
[icons.zip](https://github.com/AHAAAAAAA/PokemonGo-Map/files/376624/icons.zip)

**Comment by npeep** [comment]
Now we're cooking with fire.  Thanks @QuadTog !

**Comment by atomoton** [comment]
Very helpful thanks!

**Comment by neobithia** [comment]
QuadTog:  You just won the internet!
