### ISSUE TITLE
Install Problem

### ISSUE THREAD

**Issue by Owneryt** [AHAAAAAAA/PokemonGo-Map#932]
![default](https://cloud.githubusercontent.com/assets/20580518/17026314/5880a744-4f68-11e6-9250-0f4e3728d8f6.png)
P.s Im rename user data

**Comment by hhu94** [comment]
@medghaim Please close this.

**Comment by medghaim** [comment]
Closing this issue as it is outdated. If this issue still persists on the `develop` branch, please reopen a new issue and update the information therein to reflect the new changes.

Also, please be aware of the incredibly helpful and supportive community at: 
https://discordapp.com/invite/Kzp4yky
