### ISSUE TITLE
Pokemon not loading close to center

### ISSUE THREAD

**Issue by mkorsak** [AHAAAAAAA/PokemonGo-Map#933]
When I first start the program, it works fine. However as I keep it running over time, eventually the map won't load Pokemon near the point I'm searching. The Pokemon on the map almost start to form a circle rather than a full circular area covered. As time goes on, the circle gets thinner, and eventually nothing will be left on the map.

**Comment by Sejadis** [comment]
any error messages?
what stepcount do you use?

**Comment by michi0987** [comment]
+1 saw the same tendency

**Comment by fettlaus** [comment]
Sounds like your step count is too high. Try reducing it to something sensible like 4 or 5

**Comment by mkorsak** [comment]
No error messages. Have tried variable step counts as low as 10. It's happened to every version I've tried over the last 2 days.

**Comment by garcialopezco** [comment]
I'm having a similar issue, after a successful search when the new one is done, no pokemons are showed at all and eventually the map is empty.

command:

python example.py -a google -u "email" -p "pass" -l "my location" -st 12 -i Geodude,Mankey,Paras,Pidgey,Zubat,Raticate,Rattata,Ekans -ar 15 -dp -ol -dg -H 0.0.0.0 -P 8080

System:

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04 LTS"

Python 2.7.6

**Comment by fettlaus** [comment]
Does the problem look like the ones described in #874 and #733?

**Comment by Sejadis** [comment]
@garcialopezco first step for you would be to switch to dev branch

**Comment by garcialopezco** [comment]
oh crap! my mistake, switching branches  ...

**Comment by peda** [comment]
Close to center I do so many pokemons in the master branch but they are missing in the dev branch see the attached screenshots (thew one with more pokemons in the center is taken from the master branch the other one from the latest dev branch)

![bildschirmfoto von 2016-07-22 00-27-44](https://cloud.githubusercontent.com/assets/559490/17041006/49136b94-4fa3-11e6-95d1-57883b6bb4c6.png)
![bildschirmfoto von 2016-07-22 00-27-32](https://cloud.githubusercontent.com/assets/559490/17041007/491732c4-4fa3-11e6-88cc-ce34d72a4c80.png)

**Comment by Slivo-fr** [comment]
Same issue about missing pokemons on dev branch, while showed on master

**Comment by hhu94** [comment]
@medghaim Please close this.

**Comment by medghaim** [comment]
Closing this issue as it is outdated. If this issue still persists on the `develop` branch, please reopen a new issue and update the information therein to reflect the new changes.

Also, please be aware of the incredibly helpful and supportive community at: 
https://discordapp.com/invite/Kzp4yky
