### ISSUE TITLE
Toggle Map styles

### ISSUE THREAD

**Issue by trippyhat** [AHAAAAAAA/PokemonGo-Map#934]
The map is currently using a dark theme. It was originally the standard style you see at official google maps website. 

Can you make an option to toggle the different styles? But for now, how can I change it back to the original style instead of the dark theme?

**Comment by michi0987** [comment]
Yes please, my eyes hurt :(

**Comment by carmenchui** [comment]
Same here! Very hard to see with the dark theme!

**Comment by Orrielel** [comment]
Impossible to distinguish the roads from the natural terrain if using it on a cellphone outside in the middle of the day.
It might be good at nights, but it should be user selective.

**Comment by oboshto** [comment]
You might need to create custom map. Try this one http://googlemaps.github.io/js-samples/styledmaps/wizard/index.html then change /static/map.js

**Comment by DerScreever** [comment]
the toggle will be added.

**Comment by DanielSiepmann** [comment]
Currently the default style is back in develop branch.

When will the toggl be added, as I prefer the dark style ;)
