### ISSUE TITLE
Gym Info Box

### ISSUE THREAD

**Issue by craigbaines** [AHAAAAAAA/PokemonGo-Map#939]
Is it intentional that when i hover over a gym, the info box is opened, and if held there for 3/4 seconds, when i move the mouse away it stays open. 

Its rather annoying IMO, pokemon and pokestops both work in the way id assume this should, on mouseout they close, even if iv'e been hovering over it for 10 mins.

**Comment by sykhro** [comment]
This shouldn't be happening, gyms use the same function that adds listeners to pokemons and stops. purge your cache

**Comment by craigbaines** [comment]
Am i the only one?

Im using incognito, also tried deleting my cache, also tryed it from both chrome an firefox with the same result.

**Comment by 123456abcdef** [comment]
Same for me. Only for gyms. I'm using firefox.

**Comment by MRokas** [comment]
Same here, on Firefox 49.0a2 on Ubuntu.

This is weird af though. :/

**Comment by craigbaines** [comment]
Why is this closed, very much so still an issue.

**Comment by craigbaines** [comment]
![c2044f7f93674586e8b1710c70101443](https://cloud.githubusercontent.com/assets/9383958/17055651/16ec137e-5006-11e6-9e90-de9476820e59.gif)
