### ISSUE TITLE
Mobile devices won't refresh

### ISSUE THREAD

**Issue by Justinian6** [AHAAAAAAA/PokemonGo-Map#941]
iOS web browsers not clearing expired Pokemon on refresh... Desktop works fine

**Comment by DeastinY** [comment]
Same here on android, but a little different. At some point no new pokemons were added from mobile. Refreshing on Desktop and it worked again

**Comment by medghaim** [comment]
Closing this issue as it is outdated. If this issue still persists on the `develop` branch, please reopen a new issue and update the information therein to reflect the new changes.

Also, please be aware of the incredibly helpful and supportive community at: 
https://discordapp.com/invite/Kzp4yky
