### ISSUE TITLE
Pokéstops Toggle not working

### ISSUE THREAD

**Issue by EdenGottlieb** [AHAAAAAAA/PokemonGo-Map#943]
Pokéstops toggle is working two times: one to hide them, one to show them. After that they stay visible no matter how many times you press it.

### Environment info
Operating System: Mac OS X

Browser: Safari and Chrome

Installed version of Python:
Pyton 2.7.10

### Steps to reproduce
1. Run runserver.py with your parameters (run the program
2.
3.

### What have you tried?
1. Trying to fix it myself in map.js didn't work

**Comment by sykhro** [comment]
This issue was fixed with the latest commit

**Comment by EdenGottlieb** [comment]
Problem persists on Mac OS X, both Safari and Chrome!

**Comment by EdenGottlieb** [comment]
Problem persists on Mac OS X, both Chrome and Safari...
