### ISSUE TITLE
OOps something went wrong....the page doesnt even open?

### ISSUE THREAD

**Issue by Jshak** [AHAAAAAAA/PokemonGo-Map#944]
![image](https://cloud.githubusercontent.com/assets/13570862/17032595/d7ed0d20-4f99-11e6-8d6f-2cbca03d47b8.png)

**Comment by sykhro** [comment]
Details needed.

**Comment by EasyAsABC123** [comment]
try a different web browser

**Comment by MRokas** [comment]
Most likely you've used wrong or expired GMap Api Key. Can we get details from dev tools console?

**Comment by Jshak** [comment]
@sykhro @EasyAsABC123 @MRokas ???????????????

**Comment by MRokas** [comment]
@Jshak- https://console.developers.google.com/apis/library - activate google maps api here

**Comment by Jshak** [comment]
@MRokas Thanks dude!!!!
