### ISSUE TITLE
This Error --> example.py: argument -1/-- location is required

### ISSUE THREAD

**Issue by bhavic** [AHAAAAAAA/PokemonGo-Map#947]
### Environment info
Operating System: Windows 7

Installed version of Python:  2.7.12

I am getting this error -
usage: example.py [-h] [-a AUTH_SERVICE] -u USERNAME [-p PASSWORD] -1 LOCATION
-st STEP_LIMIT [-i IGNORE : -o ONLY] [-ar AUTO_REFRESH]
[-dp] [-dg] [-H HOST] [-P PORT] [-L LOCALE] [-ol] [-c] [-pm]
[-d]
example.py: error: argument -1/-- location is required

### This is what I tried -
1.C:\Pyhton27\python.exe example.py -a ptc -u ****** -p ****** -l "28.704042 77.129288" -st 10
Also tried , 
2. C:\Pyhton27\python.exe example.py -a ptc -u ****** -p ****** -l "rohini , delhi" -st 5

Getting this error again and again.
Please help :)

**Comment by Zach1993** [comment]
Only the develop branch is supported. Go use that one.
