### ISSUE TITLE
Next_loc returning 405 Method Not Allowed

### ISSUE THREAD

**Issue by RollTideDG** [AHAAAAAAA/PokemonGo-Map#949]
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discord.gg/Kzp4yky).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:
Windows 7
Installed version of Python:
2.7

### Steps to reproduce
1. Make a call to the next_loc with Lat and Lon arguments and page returns 405 Method Not Allowed

### What have you tried?
1.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by FrostTheFox** [comment]
We're looking into this issue.

**Comment by SilverC** [comment]
@RollTideDG @FrostTheFox It requires a post. Are you trying to make the call from a browser? Because that'll be a GET and result in an in a 405

**Comment by macgngsta** [comment]
the problem is that in the flask app - the endpoint is a POST but is looking at query parameters. Either send the parameters in the query `next_loc?lat=123&lon=234` or modify the endpoint to accept both:

`````
#part of query string
        if request.args:
            lat = request.args.get('lat', type=float)
            lon = request.args.get('lon', type=float)
#from post requests
        if request.form:
            lat = request.form.get('lat', type=float)
            lon = request.form.get('lon', type=float)
`````

**Comment by macgngsta** [comment]
why was this bug closed?

**Comment by SilverC** [comment]
Because it's not a bug. A put is actually more appropriate here since we're modifying data on the server and yes it probably makes more sense to include the data in the body rather than as query params but that doesn't constitute a bug. Merely a slightly odd implementation
