### ISSUE TITLE
Location is required Error (example.py: error: argument -1/-- location is required)

### ISSUE THREAD

**Issue by bhavic** [AHAAAAAAA/PokemonGo-Map#950]
### Environment info
Operating System: windows 7

Installed version of Python: 2.7.12

### I am getting this error -
usage: example.py [-h] [-a AUTH_SERVICE] -u USERNAME [-p PASSWORD] -1 LOCATION
-st STEP_LIMIT [-i IGNORE : -o ONLY] [-ar AUTO_REFRESH]
[-dp] [-dg] [-H HOST] [-P PORT] [-L LOCALE] [-ol] [-c] [-pm]
[-d]
example.py: error: argument -1/-- location is required

### This is what I have tried -
1.C:\Pyhton27\python.exe example.py -a ptc -u ****** -p ****** -l "28.704042 77.129288" -st 10
Also tried , 
2. C:\Pyhton27\python.exe example.py -a ptc -u ****** -p ****** -l "rohini , delhi" -st 5

Getting this error again and again.
Please help :)

**Comment by ChristianLuxem** [comment]
you are running in the wrong directory. You need to run this script in the folder, that you extract of the zip-file. There should also be an example.py into. Otherwise use the Development branch with runserver.py

**Comment by bhavic** [comment]
Thanks for the response.
This is the full path -
C:\Users\Bhavic\Downloads\Pokemongomaster\PokemonGo-Map-Master>.C:\Pyhton27\python.exe example.py -a ptc -u ****** -p ****** -l "28.704042 77.129288" -st 10

**Comment by FrostTheFox** [comment]
The master branch is currently unsupported. You need to download and use the develop branch.

**Comment by FrostTheFox** [comment]
@ChristianLuxem It looks like he is in the right directory, just python not properly in his path.
