### ISSUE TITLE
Pokemon Icons are low res

### ISSUE THREAD

**Issue by benwaffle** [AHAAAAAAA/PokemonGo-Map#951]
Please add higher resolution pokemon icons

**Comment by Pakalaka60** [comment]
If it works, you should be happy. They are trying to make it more user friendly so that isn't going to be a top priority

**Comment by neobithia** [comment]
Agree, this is not a high priority.  Filtering Pokemons is higher.  But, it's a nice to have.  It's kind of hard to tell what kind of Pokemon it is.  In the meantime, let's just mouse hover. :)

**Comment by QuadTog** [comment]
#930
