### ISSUE TITLE
ImportError: No module named peewee

### ISSUE THREAD

**Issue by mrfacu87** [AHAAAAAAA/PokemonGo-Map#952]
Receiving the following error message when running 'python runserver.py -u XXXXX -p XXXXX --location "LOCATION" -st 25 -ar 10 -H "0.0.0.0" -P "5000"':

Traceback (most recent call last):
  File "runserver.py", line 10, in <module>
    from pogom.app import Pogom
  File "C:\PokemonGo-Map-develop\pogom\app.py", line 10, in <module>
    from .models import Pokemon, Gym, Pokestop
  File "C:\PokemonGo-Map-develop\pogom\models.py", line 5, in <module>
    from peewee import Model, SqliteDatabase, InsertQuery, IntegerField,\
ImportError: No module named peewee

### Environment info
Operating System:
Windows 10

Installed version of Python:
2.7

### Steps to reproduce
1.Run: python runserver.py -u XXXXX -p XXXXX --location "LOCATION" -st 25 -ar 10 -H "0.0.0.0" -P "5000"

**Comment by Justinian6** [comment]
Run the Easy Setup batch file....

**Comment by neobithia** [comment]
run the requirements.txt again

**Comment by mrfacu87** [comment]
Thanks, the batch file did the trick.

**Comment by FrostTheFox** [comment]
Problem solved?

**Comment by FrostTheFox** [comment]
I'm assuming this issue is resolved. If you have any further issues, open a new issue.
