### ISSUE TITLE
No module named gpsauth

### ISSUE THREAD

**Issue by rwroni** [AHAAAAAAA/PokemonGo-Map#954]
Traceback (most recent call last):
  File "example.py", line 26, in <module>
    from gpsoauth import perform_master_login, perform_oauth
ImportError: No module named gpsoauth

**Comment by EdenGottlieb** [comment]
It means that your computer doesn't have the required module.
You need to run "pip install -r requirements.txt" with su (Mac and Linux) or administrator rights (Windows) otherwise you'll encounter permission problems

**Comment by rwroni** [comment]
so I had to use an administrator to run this application ? Can I use another user ?

**Comment by EdenGottlieb** [comment]
Mac requires administrator rights, I'm not sure if windows does too... Try and run "pip install -r requirements.txt" (without parenthesis again) and look for any ACCESS DENIED errors

**Comment by rwroni** [comment]
i did not find any issues, the end of process when i run the requirement.txt are like this
Command "C:\Python27\python.exe -c "import setuptools, tokenize;__file__='c:\\users\\247\\appdata\\local\\temp\\pip-build-a9xish\\pycryptodomex\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\247\appdata\local\temp\pip-ru7ktm-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\247\appdata\local\temp\pip-build-a9xish\pycryptodomex

**Comment by rwroni** [comment]
is that ok?

**Comment by TheRealGitCub** [comment]
I was getting this issue on Ubuntu 14.04. [Solved it](https://github.com/AHAAAAAAA/PokemonGo-Map/issues/407#issuecomment-233734636) by running the following:

`sudo apt-get install python2.7-dev`

You could also try:

`sudo apt-get install build-essentials`

**Comment by istoutjesdijk** [comment]
sudo yum install python-devel on CentOS.
