### ISSUE TITLE
How do I open the map on my iPhone?

### ISSUE THREAD

**Issue by Lenny188** [AHAAAAAAA/PokemonGo-Map#956]
I ran the Script with -H 0.0.0.0 but how can I open it on my iPhone?? Which steps are needed that I can use this map on my iPhone?

#question

**Comment by FrostTheFox** [comment]
Where are you running it? You may have to port forward if you're running it at home.

**Comment by McKean** [comment]
use this: https://localtunnel.me/

**Comment by Roastmaster** [comment]
im running it on ngrok

**Comment by Lenny188** [comment]
How can I run it on ngrok since I can't install Localtunnel :/

**Comment by Lenny188** [comment]
case closed, got localtunnel working! thx @McKean !!!! This was helpful even though I had to check out how to install it properly
