### ISSUE TITLE
Gym argument (-dg) not working in dev branch?

### ISSUE THREAD

**Issue by neobithia** [AHAAAAAAA/PokemonGo-Map#958]
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discord.gg/Kzp4yky).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:  Windows 10 Pro, Version 1511, Build 10586.494

Installed version of Python:  2.7.12

### Steps to reproduce
1.  Run basic command with -dg argument
`python runserver.py -dg -a ptc -u [USERNAME] -p [PASSWORD] -l "[LOCATION]" -st 10`

### What have you tried?
1. Expected result:
`'-dg' '--display-gym'`

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

> usage: runserver.py [-h] [-a AUTH_SERVICE] -u USERNAME [-p PASSWORD] -l
>                     LOCATION -st STEP_LIMIT [-H HOST] [-P PORT] [-L LOCALE]
>                     [-c] [-d] [-m] [-k GMAPS_KEY]
> runserver.py: error: argument -d/--debug: ignored explicit argument 'g'

**Comment by narayanjr** [comment]
The option was removed from the command line. You can do it from the UI now. Click Menu in the top left then toggle gyms.

**Comment by neobithia** [comment]
Thank you!
