### ISSUE TITLE
Pokestops stopped showing up on the map

### ISSUE THREAD

**Issue by iambibhas** [AHAAAAAAA/PokemonGo-Map#96]
The pokestops stopped showing up on the map since I pulled 4-5 hours ago. Did something change?

### Environment info
Operating System: Linux Mint/Ubuntu 14.04

Installed version of Python: 2.7

### Steps to reproduce
1. run script
2. refresh browser
3. no pokestops!

### What have you tried?
1. creating an issue on github

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by lorddusk** [comment]
If you really want them back, change the name of changePstop.png in the /static/forts/ folder. They were removed or changed rather in https://github.com/AHAAAAAAA/PokemonGo-Map/commit/4faf0363cc7a17a34ea7d44225b30552bdae0649

**Comment by CarlTaylor1989** [comment]
This has temporarily been hidden - as @lorddusk says, change the file name from changePstop.png to Pstop.png.

**Comment by iambibhas** [comment]
Is it hidden because something better is coming up?
