### ISSUE TITLE
AttributeError: 'module' object has no attribute 'is_running_from_reloader'

### ISSUE THREAD

**Issue by wouterverduin** [AHAAAAAAA/PokemonGo-Map#960]
Hi There,

After installing all dependencies and running it; i get the following error: 

Traceback (most recent call last):
  File "example.py", line 908, in <module>
    register_background_thread(initial_registration=True)
  File "example.py", line 733, in register_background_thread
    if not werkzeug.serving.is_running_from_reloader():
AttributeError: 'module' object has no attribute 'is_running_from_reloader'

Tried googling it, but couldnt get any clues. Anyone who can point it out for me? :)

**Comment by FrostTheFox** [comment]
You're using the master branch. You need to use the develop branch.
