### ISSUE TITLE
Exception while install the requirements

### ISSUE THREAD

**Issue by cbedoy** [AHAAAAAAA/PokemonGo-Map#961]
I got an exception while install the requirements, Don't you know?

I'm using Mac OS

➜  PokemonGo-Map-master pip install -r requirements.txt           

        
Collecting geopy==1.11.0 (from -r requirements.txt (line 1))
  Using cached geopy-1.11.0-py2.py3-none-any.whl
Collecting protobuf==2.6.1 (from -r requirements.txt (line 2))
  Using cached protobuf-2.6.1.tar.gz
Collecting requests==2.10.0 (from -r requirements.txt (line 3))
  Using cached requests-2.10.0-py2.py3-none-any.whl
Collecting flask-googlemaps==0.2.0 (from -r requirements.txt (line 4))
  Using cached Flask-GoogleMaps-0.2.0.tar.gz
Collecting s2sphere==0.2.4 (from -r requirements.txt (line 5))
  Using cached s2sphere-0.2.4-py2.py3-none-any.whl
Collecting flask==0.11.1 (from -r requirements.txt (line 6))
  Using cached Flask-0.11.1-py2.py3-none-any.whl
Collecting gpsoauth==0.3.0 (from -r requirements.txt (line 7))
  Using cached gpsoauth-0.3.0.tar.gz
Collecting coveralls==1.1 (from -r requirements.txt (line 8))
  Using cached coveralls-1.1-py2.py3-none-any.whl
Collecting werkzeug==0.11.10 (from -r requirements.txt (line 9))
  Using cached Werkzeug-0.11.10-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): setuptools in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from protobuf==2.6.1->-r requirements.txt (line 2))
Collecting future (from s2sphere==0.2.4->-r requirements.txt (line 5))
  Using cached future-0.15.2.tar.gz
Collecting itsdangerous>=0.21 (from flask==0.11.1->-r requirements.txt (line 6))
  Using cached itsdangerous-0.24.tar.gz
Collecting click>=2.0 (from flask==0.11.1->-r requirements.txt (line 6))
  Using cached click-6.6.tar.gz
Collecting Jinja2>=2.4 (from flask==0.11.1->-r requirements.txt (line 6))
  Using cached Jinja2-2.8-py2.py3-none-any.whl
Collecting pycryptodomex>=3.0 (from gpsoauth==0.3.0->-r requirements.txt (line 7))
  Using cached pycryptodomex-3.4.2.tar.gz
Collecting coverage>=3.6 (from coveralls==1.1->-r requirements.txt (line 8))
  Using cached coverage-4.1-cp27-cp27m-macosx_10_10_x86_64.whl
Collecting docopt>=0.6.1 (from coveralls==1.1->-r requirements.txt (line 8))
  Using cached docopt-0.6.2.tar.gz
Collecting MarkupSafe (from Jinja2>=2.4->flask==0.11.1->-r requirements.txt (line 6))
  Using cached MarkupSafe-0.23.tar.gz
Installing collected packages: geopy, protobuf, requests, itsdangerous, click, werkzeug, MarkupSafe, Jinja2, flask, flask-googlemaps, future, s2sphere, pycryptodomex, gpsoauth, coverage, docopt, coveralls
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/req/req_set.py", line 742, in install
    **kwargs
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/req/req_install.py", line 831, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/req/req_install.py", line 1032, in move_wheel_files
    isolated=self.isolated,
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/wheel.py", line 346, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/wheel.py", line 317, in clobber
    ensure_dir(destdir)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/geopy'

**Comment by FrostTheFox** [comment]
Try running with sudo.

**Comment by cbedoy** [comment]
I used sudo, and I got the same problem
