### ISSUE TITLE
Syntax meaning?

### ISSUE THREAD

**Issue by denniskai1234** [AHAAAAAAA/PokemonGo-Map#962]
Can someone explain me what those options do?

[-c] [-d] [-m]

**Comment by sykhro** [comment]
-m : mock data. it feeds the script some dummy data, useful for debugging without pulling data form the servers
-d : debug messages
-c : coordinates fix for china

the automatic refresh is no longer needed, frontend removes expired pokemons automatically

**Comment by narayanjr** [comment]
'-c', '--china', help='Coordinates transformer for China'
'-d', '--debug', help='Debug Mode'
'-m', '--mock', help='Mock mode. Starts the web server but not the background thread.'

Yes the ar flag is gone but also not needed now.

**Comment by npeep** [comment]
Take a look here:  https://github.com/AHAAAAAAA/PokemonGo-Map/issues/581

**Comment by neobithia** [comment]
Please use SEARCH, this has been asked.
