### ISSUE TITLE
Flask not installing properly

### ISSUE THREAD

**Issue by Pakalaka60** [AHAAAAAAA/PokemonGo-Map#963]
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discord.gg/Kzp4yky).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System: Windows 10

Installed version of Python: 2.7.12

### Steps to reproduce
1.
2.
3.

### What have you tried?
1. Uninstalling flask (Said flask wasn't there) and re-installing

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).
Tried running the last command but it came up with this

Traceback (most recent call last):
File "runserver.py", line 10, in 
from pogom.app import Pogom
File "C:\Pokemon Go\pogom\app.py", line 5, in 
from flask import Flask, jsonify, render_template, request
ImportError: No module named flask I tried uninstalling flask but it said it wasnt there

**Comment by Roastmaster** [comment]
Are you running the developer or master branch?  Also are you using the correct python instance? (2 or 3)

What is the output of `pip list`?

**Comment by Pakalaka60** [comment]
I'm pretty sure I am running the developer branch. How can I make sure? (I'm using Python 2.7.12)
I forgot the line of code to access pip. For now it's saying that 'pip' is not recognized as an internal or external command,
operable program or batch file.

**Comment by DerScreever** [comment]
read the wiki pls

**Comment by Pakalaka60** [comment]
What wiki
