### ISSUE TITLE
-i [ignore] argument animals/creatures/pokemon not working in dev branch?

### ISSUE THREAD

**Issue by neobithia** [AHAAAAAAA/PokemonGo-Map#967]
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discord.gg/Kzp4yky).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:  Windows 10 Pro, Version 1511, Build 10586.494

Installed version of Python: 2.7.12

### Steps to reproduce
1. Run basic command with -i argument
`python runserver.py -dg -a ptc -u [USERNAME] -p [PASSWORD] -l "[LOCATION]" -st 10 -i pikachu`
### What have you tried?
1.  Expected result:
`'-i'  '--ignore', help='Comma-separated list of Pokémon names or IDs to ignore')`

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

> usage: runserver.py [-h] [-a AUTH_SERVICE] -u USERNAME [-p PASSWORD] -l
>                     LOCATION -st STEP_LIMIT [-H HOST] [-P PORT] [-L LOCALE]
>                     [-c] [-d] [-m] [-k GMAPS_KEY]
> runserver.py: error: unrecognized arguments: -i pikachu

**Comment by narayanjr** [comment]
It was removed, they are working on a UI version

**Comment by DerScreever** [comment]
@narayanjr  has the good informations ;-)

**Comment by neobithia** [comment]
How does it work in the UI?

**Comment by narayanjr** [comment]
It is not currently part of the UI yet.  It is still in the process of being written so I do not know how they plan to handle storing user preferences.  Hopefully they are persisted across sessions.
