### ISSUE TITLE
No pokemon on map

### ISSUE THREAD

**Issue by buddytohelpu** [AHAAAAAAA/PokemonGo-Map#969]
No pokemon are showing on map after I updated to newest revision#495

**Comment by DerScreever** [comment]
for me it work, try latest develop

**Comment by efiku** [comment]
You should put screenshot from your browser console. :)  
F12 -> Console. (In Chrome)

**Comment by buddytohelpu** [comment]
I just got in chrome console.
Failed to load resource: the server responded with a status of 404 (NOT FOUND)

**Comment by henningphan** [comment]
I had a similar problem which happened because of chrome caching the files so It used the old code to retrieve pokemons which was deprecated. The solution was to refresh the website with shift+F5

**Comment by buddytohelpu** [comment]
I tried with no luck =( tried a different computer too with the same issue. It was working on an earlier revision

**Comment by henningphan** [comment]
What is the path of 404?

**Comment by rdamron** [comment]
Failed to load resource: the server responded with a status of 404 (NOT FOUND)
2http://172.24.3.126:5000/static/dist/js/app.min.js Failed to load resource: the server responded with a status of 404 (NOT FOUND)
http://172.24.3.126:5000/static/img/cross.png Failed to load resource: the server responded with a status of 404 (NOT FOUND)
http://172.24.3.126:5000/static/dist/css/app.min.css Failed to load resource: the server responded with a status of 404 (NOT FOUND)

**Comment by buddytohelpu** [comment]
Just took a screenshot. Re-installed python, fresh download of dev build.
"<blockquote class="imgur-embed-pub" lang="en" data-id="a/HBaZ8"><a href="//imgur.com/HBaZ8"></a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>``
