### ISSUE TITLE
"no module named peewee" when starting server

### ISSUE THREAD

**Issue by Bellamy207** [AHAAAAAAA/PokemonGo-Map#970]
Hey,

when i'm trying to start the server i get the error `no module named peewee`

I tried to install it, but it was already installed by the former requirement.txt installation. So it's no wonder that i got this: `Requirement already satisfied (use --upgrade to upgrade): peewee in /usr/local/lib/python2.7/site-packages`. And it's upgraded as well. What can i do about it?

Using the develop branch.

**Comment by neobithia** [comment]
When that happened to me, I just uninstalled EVERYTHING and re-installed it again.  It's not a fix, but a workaround.
