### ISSUE TITLE
How to render the contents on a web domain?

### ISSUE THREAD

**Issue by Quebroph** [AHAAAAAAA/PokemonGo-Map#971]
I run the script on a debian server with froxlor panel. 

How to render the contents with the domain i redirected in the ftp folder?
In which file should i change which setting?

- https://domain.tld:5000 does not work

**Comment by Tigershark2005** [comment]
Flask is not running https from how it's configured by default. It's also configured for localhost only by default. The easiest and quickest way is to add

> -H 0.0.0.0

to your execution command line. This binds it to an available external address instead of loopback only.

**Comment by Quebroph** [comment]
Thanks for the fast reply. The server runs without ssl.
I startet the job with -H 0.0.0.0.
I´m still not getting the map it via domain.tld:5000

**Comment by Quebroph** [comment]
It works! But Javascript crashes after 1-2 seconds. 

How can we fix this?

<img width="947" alt="Pokemap Javascript Error" src="https://cloud.githubusercontent.com/assets/2054568/17034016/104ea8c2-4f81-11e6-92f8-9f1bf22697fd.png">

**Comment by Zsub** [comment]
> Will a google develeperts API key solve this?

Yes.

**Comment by Quebroph** [comment]
Got it - sorry for my questions. I´ve no experience with this stuff.
Where should i put the api key in the script?

**Comment by Tigershark2005** [comment]
In the credentials.json file. It's the gmaps_key variable. Also check this page out: https://github.com/AHAAAAAAA/PokemonGo-Map/wiki 

That's where you'll get a little more in-depth guide. Don't worry about questions, that's exactly what these issues lists and forums are for. Projects like this aren't meant to be exclusively for expert users, so we need to keep that in mind, and at times adjust documentation or programming to account for users that aren't as familiar with it. Thank you for your input!

**Comment by Quebroph** [comment]
Thanks! It works :-)

**Comment by jtmantis** [comment]
Hey guys, would you mind sharing how have you managed to make it work on external server? What files do you upload to your ftp folder? I'd like to add a map to my website with all pokestops and gyms displayed in my local area.

**Comment by Quebroph** [comment]
You need more than a "normal" webspace because you have to be able to access the server commands directly to start/stop the server. You must upload all file to the ftp. The server should support python 2.7 and other software (see requirements.txt). If this is ready you can add -H IP.IP.IP.IP of your server (replace IP.IP... with your server's ip addresse). Access the pokemap with domain.tld:5000
