### ISSUE TITLE
Missing Ignore function?

### ISSUE THREAD

**Issue by welshboy** [AHAAAAAAA/PokemonGo-Map#972]
Not sure if this is an issue, or a deliberate removed of the ignore param? It was good because it stopped the map getting cluttered. Is this going to be re-added or should I implement it myself?

**Comment by npeep** [comment]
They are re-implementing this through the UI - there is not pull request for it yet, but I think @sykhro is involved (or he at least knows better than me).

**Comment by welshboy** [comment]
@npeep Awesome! Thanks. I want to get involved and contribute but I've not used python for a few years. I'm going to scan over the source now and see if theres anything I can improve/add

**Comment by neobithia** [comment]
Please use SEARCH.  This was already asked.

**Comment by welshboy** [comment]
@neobithia Apologies. Will close this.

**Comment by Tigershark2005** [comment]
@welshboy I see this is closed but -i is included already, not under development. In your execution command use -i with the number of the pokemon, comma separated. I'm using -i 13,16,19,21,133 because I don't want Pidgeys, Rattatas, Eevee, Spearow, or Weedle.
