### ISSUE TITLE
Alert when new pokemon appears, or some pokemon rarity chart.

### ISSUE THREAD

**Issue by dragonkoko** [AHAAAAAAA/PokemonGo-Map#973]
Alert when a new pokemon appears or customizable using creditionals.json to input which pokemons i want to be alerted for when they appear.

**Comment by npeep** [comment]
@dragonkoko Check the pull requests.  People have coded these functionalities, its only a matter of time and some more effort from these awesome folks until they are implemented.

**Comment by neobithia** [comment]
Please label your issue:  Enhancements

**Comment by craigbaines** [comment]
hell yes we do.

**Comment by jnovack** [comment]
Technically, the app is bringing a feature BACK that was in the Beta.

In the Beta, it showed you how far away you were in meters, not "1, 2 or [3 which could mean 6] paw prints".  But alerts would probably be for rares so they don't have to check the app every x minutes.

If I'm doing rand(activity), and Mew pops up for 15 mins, I want to find out at 14:59 left, not when I check my phone/browser when it could be 34 seconds left.

**Comment by neobithia** [comment]
fair enough :)
