### ISSUE TITLE
[Feature Request] Set Location

### ISSUE THREAD

**Issue by IQNeoXen** [AHAAAAAAA/PokemonGo-Map#975]
Hi there,
idk where to put feature requests so i'll just post it here.
Is it possible to include a "Set Location" feature into the web-interface? So that you don't have to restart the server everytime you want to scan another location.

Would be very nice!
I'm learning python now so i'll try my best to implement it myself, but i'm clearly not the best programmer you have ever seen ;)

Nice project, keep up the good work devs!

**Comment by npeep** [comment]
Check the pull requests :)  This has already been coded, but not committed yet.  They are working on it.

https://github.com/AHAAAAAAA/PokemonGo-Map/pull/660

**Comment by neobithia** [comment]
Please label your issue:  Enhancements

Agree, this is a great idea!

**Comment by FrostTheFox** [comment]
Closing due to pending pull requests.
