### ISSUE TITLE
Running PokeMaps in sub-directory. How to set global URL path prefix?

### ISSUE THREAD

**Issue by rcoenen** [AHAAAAAAA/PokemonGo-Map#978]
Feature request: I'd like to set a prefix so that he app can run in /a-sub-directory/like/this/ rather than always on the root /

**Comment by Cliffield** [comment]
On a webserver you could use [nginx as reverse proxy](https://www.nginx.com/resources/admin-guide/reverse-proxy/) to run the app in /foo/bar/ for example.

server:80/foo/bar1/ --> app:5000
server:80/foo/bar2/ --> app:5001

**Comment by rcoenen** [comment]
mmm that's overkill

I tried to patch the code to support this as config option (not much of a Python nor Flask framework guru here) but its eems a common thing to do

http://stackoverflow.com/questions/18967441/add-a-prefix-to-all-flask-routes

However

specifying `app.config['APPLICATION_ROOT'] = '/abc/123'` did not work for me.
It should be straightforward to get this into the app itself without the need for reverse proxy servers?
