### ISSUE TITLE
Map doesn't detect Pikachu

### ISSUE THREAD

**Issue by EasyAsABC123** [AHAAAAAAA/PokemonGo-Map#980]
### Environment info
Operating System: Windows 10

Installed version of Python: 2.7.*

### Steps to reproduce
1. Run runserver.py
2. Open localhost:5000
3. Find a Pikachu in game, look on map, it won't be there

### What have you tried?
1. Changing radius and waiting for refresh

**Comment by lnmtriet93** [comment]
That meand maybe there no pikachu around your location?

**Comment by neobithia** [comment]
Pikachu has special powers.  No way around this.

:P 

jk, it could be expired and not updating?

**Comment by MRokas** [comment]
From what I've seen some pokemons spawns for everyone, and others spawn exclusively to player.

**Comment by fankaisong** [comment]
@neobithia   Your profile pic just so hot.

**Comment by MRokas** [comment]
@fankaisong Your comment just so much cringeworthy.
