### ISSUE TITLE
Searching Locations Stop Working?

### ISSUE THREAD

**Issue by SSminowjohnson** [AHAAAAAAA/PokemonGo-Map#981]
I have been searching cities using the following syntax: "Los Angeles, CA", "New York City, New York", etc. That has been working fine. But today when I tried I received errors, for example:

example.py: error: unrecognized arguments: Angeles, Californiaö

If I just try "California" that works fine. I downloaded the entire zip again and still the same error. Anyone know why this would be?

**Comment by FrostTheFox** [comment]
Full command?

**Comment by efiku** [comment]
example.py -l "Text with spaces" 

surround with " " your text.

(Linux) :)

**Comment by SSminowjohnson** [comment]
python example.py -u ***** -p ********* -l “Los Angeles, California” -st 999 -sw

**Comment by SSminowjohnson** [comment]
I have been using quotes. Worked just fine for a couple days.

**Comment by FrostTheFox** [comment]
You need to use the develop branch. Master branch support is dropped at the moment.
