### ISSUE TITLE
Error runserver.py username

### ISSUE THREAD

**Issue by CryZerR** [AHAAAAAAA/PokemonGo-Map#982]
when I open runserver.py i have error argument username ?

**Comment by welshboy** [comment]
you need to do python runserver.py -a google/ptc -u username -p password

**Comment by narayanjr** [comment]
-i, -o, -ar, -dp, -ol, -dg are no longer supported.

-i is being implemented with the UI
-ar is not longer needed

-dp, -dg can be controlled in the UI currently

**Comment by CryZerR** [comment]
i'm develop and when I open runserver.py I not username or password

`#!/usr/bin/python
# -*- coding: utf-8 -*-

import os
import logging

from threading import Thread

from pogom import config
from pogom.app import Pogom
from pogom.utils import get_args, insert_mock_data, load_credentials
from pogom.search import search_loop
from pogom.models import create_tables, Pokemon, Pokestop, Gym

from pogom.pgoapi.utilities import get_pos_by_name

log = logging.getLogger(__name__)


def start_locator_thread(args):
    search_thread = Thread(target=search_loop, args=(args,))
    search_thread.daemon = True
    search_thread.name = 'search_thread'
    search_thread.start()


if __name__ == '__main__':
    logging.basicConfig(level=logging.INFO, format='%(asctime)s [%(module)11s] [%(levelname)7s] %(message)s')

    logging.getLogger("peewee").setLevel(logging.INFO)
    logging.getLogger("requests").setLevel(logging.WARNING)
    logging.getLogger("pogom.pgoapi.pgoapi").setLevel(logging.WARNING)
    logging.getLogger("pogom.pgoapi.rpc_api").setLevel(logging.INFO)

    args = get_args()

    if args.debug:
        logging.getLogger("requests").setLevel(logging.DEBUG)
        logging.getLogger("pgoapi").setLevel(logging.DEBUG)
        logging.getLogger("rpc_api").setLevel(logging.DEBUG)

    create_tables()

    position = get_pos_by_name(args.location)
    log.info('Parsed location is: {:.4f}/{:.4f}/{:.4f} (lat/lng/alt)'.
             format(*position))

    config['ORIGINAL_LATITUDE'] = position[0]
    config['ORIGINAL_LONGITUDE'] = position[1]
    config['LOCALE'] = args.locale

    if not args.mock:
        start_locator_thread(args)
    else:
        insert_mock_data()

    app = Pogom(__name__)
    config['ROOT_PATH'] = app.root_path
    if args.gmaps_key is not None:
        config['GMAPS_KEY'] = args.gmaps_key
    else:
        config['GMAPS_KEY'] = load_credentials(os.path.dirname(os.path.realpath(__file__)))['gmaps_key']
    app.run(threaded=True, debug=args.debug, host=args.host, port=args.port)

`

**Comment by narayanjr** [comment]
Are you trying to open it to make edits? or are you trying to run the file?

**Comment by CryZerR** [comment]
run the file

**Comment by narayanjr** [comment]
To run the file you need to do a command like this,

Assuming you are using a Pokemon Trainer Acccount
python runserver.py -a ptc -u yourUserName -p yourPassword -l "New York City, New York" -st 10

If you are using a google account
python runserver.py -a google -u yourUserName -p yourPassword -l "New York City, New York" -st 10

You can also change "New York City, New York" to what ever location you want, just make sure you keep the quotes around it.

**Comment by CryZerR** [comment]
I write it Where (cmd...) ?

**Comment by narayanjr** [comment]
yes

**Comment by CryZerR** [comment]
error "python" is not recognized :/

**Comment by narayanjr** [comment]
Either you dont have python installed or it isnt on your PATH.  I suggest you google it.

**Comment by Tigershark2005** [comment]
I had to restart my computer even though python and pip were in my path variables. If you're using Windows, click start and type environment, you'll know which to click. You're looking for the PATH environment variable for the system. It should have python and a pip folder in it.

**Comment by CryZerR** [comment]
no
