### ISSUE TITLE
Pokemon expiration date stuck  at 01:00:00

### ISSUE THREAD

**Issue by bocaci** [AHAAAAAAA/PokemonGo-Map#983]
All the pokemons show a wrong countdown:
 Disappears at 01:00:00 (expired)
Was working fine before latest commits, any ideas?

**Comment by Jared87** [comment]
Same here, servertime is CEST.

**Comment by peda** [comment]
same here (also CEST)

**Comment by Fank** [comment]
same

**Comment by KingsDevelopment** [comment]
+1

**Comment by FrostTheFox** [comment]
Try redownloading develop. Pushed new commit.

**Comment by Jared87** [comment]
Working, also the Pokemon-ID Link isn't the timestamp anymore.
