### ISSUE TITLE
Develop version shopws not all pokemons

### ISSUE THREAD

**Issue by tatarrr95** [AHAAAAAAA/PokemonGo-Map#984]
I'm launch master version and it shows all pokemons. But develop version doesn't show all pokemons. Example, it doesn't show "paras", "ekans", "caterpie" and others

**Comment by KeenIIDX** [comment]
Unable to reproduce here.  Mine is showing Paras and Caterpies nearby me.

**Comment by MonjoNL** [comment]
In one of the first versions of example.py I noticed that some pokemon do not have a normal disappear time. They were active for longer than the normal 15 minutes and were labeled with 23:59:59 (Expired).
But in fact these pokemon are actually there in the game, perhaps this is a bug in the game itself, but  I have a feeling that these pokemons are the ones that are not visible anymore in the more recent versions of this project.

**Comment by fankaisong** [comment]
I have all maps working but no pokemons showing.  Just like a map....nothing else
