### ISSUE TITLE
Output Plugin Architecture

### ISSUE THREAD

**Issue by jnovack** [AHAAAAAAA/PokemonGo-Map#988]
I would like the ability to write an output plugin (thus not complicating the main application) for tracking stats over time.  The app could load everything in the `/plugins` directory and let users write their own. (Perhaps one for example?)

Up for discussion is calling the plugin:
* after each loop (visible pokemon have been sorted, deduplicated, etc) - could lead to delays
* after each visible pokemon - could lead to duplicates

Perhaps both, with a different entry point for each?

Example Uses:

* Upload to Elasticsearch <3
* Output to CSV
* SYSLOG?   `[EMERG] MewTwo sighted at 27.9878484, 86.9075165,14`
* Running multiple scripts and then dumping to a centralized database for true crowd-sourcing. :)

**Comment by FrostTheFox** [comment]
We might introduce this in the future. To keep down on issues, I'm closing this for now.

**Comment by jnovack** [comment]
:(

I understand.
