### ISSUE TITLE
Location Arg no longer being accepted

### ISSUE THREAD

**Issue by rkowalk** [AHAAAAAAA/PokemonGo-Map#989]
As of 3 AM MST my dev server is no longer able to accept a location under either -l or --location.

The following is the launch command - 
python ~/Documents/Git/PokemonGo-Map/runserver.py -a ptc -u $$$ -p $$$ --location "937 S 1635 W Orem UT" -st 10 -l "Rattata,Pidgey,Paras,Drowzee,Venonat,Ponyta,Abra,Rhyhorn,Diglett,Geodude,Mankey,Meowth,Pidgeotto,Eevee,Zubat,Caterpie,Weedle,Growlithe,29,Spearow,32" -dl -H 0.0.0.0 -P 80

This returns a missing arg statement
![screen shot 2016-07-21 at 12 30 54 pm](https://cloud.githubusercontent.com/assets/6676013/17034268/2ceb0c42-4f3f-11e6-98ae-cbeb03427798.png)

**Comment by rkowalk** [comment]
The above is still replicated when the deppricated commands are removed(-dl)

**Comment by Zsub** [comment]
I think it's because you use the `-dl` parameter, which has been removed.

**Comment by FrostTheFox** [comment]
Use coordinates like: 45.6818439 -71.239834

**Comment by neobithia** [comment]
And try removing all deprecated args.

**Comment by Sejadis** [comment]
you're using -l instead of -i 
and iirc ignore isnt implemented right now?

**Comment by RyanMBlue** [comment]
Try running this command instead:
runserver.py -a ptc -u $$$ -p $$$ --location "937 S 1635 W Orem UT" -st 10 -H 0.0.0.0 -P 80

**Comment by rkowalk** [comment]
Thanks for the help everyone.  Didnt realize I hadn't removed -i
