### ISSUE TITLE
Bring back Satellite view.

### ISSUE THREAD

**Issue by mastamoon** [AHAAAAAAA/PokemonGo-Map#991]
koolkthnkzbye

**Comment by Tigershark2005** [comment]
The satellite view is available in the master (main) branch. It should be selectable from the top left. Use Chrome if you aren't seeing it.

**Comment by MRokas** [comment]
It is available in latest develop version. It was always there, just "hidden" behind navbar.

**Comment by mastamoon** [comment]
Sorry, im using the Dev branch... Is there a way to have the nav bar hide, or move the satellite toggle down?

**Comment by MRokas** [comment]
Just use latest version.
