### ISSUE TITLE
Password parameter: Expected one argument?

### ISSUE THREAD

**Issue by zale90** [AHAAAAAAA/PokemonGo-Map#992]
Somehow when I start runserver.py of the develop branch it throws me this error: 

usage: runserver.py [-h] [-a AUTH_SERVICE] -u USERNAME [-p PASSWORD] -l
                    LOCATION -st STEP_LIMIT [-H HOST] [-P PORT] [-L LOCALE]
                    [-c] [-d] [-m] [-k GMAPS_KEY]
**runserver.py: error: argument -p/--password: expected one argument**

I'm starting runserver.py with these parameters however:
/var/python/pokemongomap$ python _runserver.py -a PTC -u "someuser" -p somepw -l "somelocation" -st 10 -H 0.0.0.0 -P 5000 -L de --display-gym -dp -ol -ar 30_

Using quotes around the password doesn't help either.

**Comment by RyanMBlue** [comment]
you are using depreciated arguments. Your "-dp" is throwing it off, since it sees a p.

Only use args listed in the usage statment

**Comment by Zsub** [comment]
You're using deprecated parameters, `-dg -dp -dl` at least are deprecated.
