### ISSUE TITLE
Website dosent work on Phones

### ISSUE THREAD

**Issue by denniskai1234** [AHAAAAAAA/PokemonGo-Map#993]
The current master version works very well on mobile phones but the current one not, the map background dosent load which looks very weird.

**Comment by sykhro** [comment]
Are you running the latest commit?

**Comment by dbanka** [comment]
I am running the latest commit and the map is not loading in computer also

**Comment by denniskai1234** [comment]
If you reload the map it does showup fine, not sure why.

**Comment by tatarrr95** [comment]
I installed develop version on my server. Launch with command python runserver.py -H [ip of server] -P 5000 -a ptc -u [login] -p [pass] -l "[coordinates]" -st 2 -k [google key]. All work on my computer and iphone

**Comment by denniskai1234** [comment]
It does work yeah, but with the current version you have to load the map twice on any device until the background shows up and the menu with the options is also hidden on the first view.

**Comment by dbanka** [comment]
Failed to load resource: the server responded with a status of 404 (NOT FOUND)
http://localhost:5000/pokemons Failed to load resource: the server responded with a status of 404 (NOT FOUND)

I am getting these errors

**Comment by thewreckingcrew6** [comment]
I used the above info to make the web server work through my firewall. But I have one issue. If I connect to the web server using a local ip such as 192.168.1.xxx, it works fine and flawlessly, however if I connect to it using my remote ip xxx.xxx.xxx.xxx, it loads up fine and works for about 2 seconds, and then this happens. https://www.dropbox.com/s/t2mik54dhq4ey8f/PokemapError.png?dl=0

**Comment by dbanka** [comment]
![pic](https://cloud.githubusercontent.com/assets/6622487/17034999/c81df3ba-4fa2-11e6-94a2-f9ca97cef8bf.png)

**Comment by tatarrr95** [comment]
thewreckingcrew6 , if you in Chrome, touch f12 and see console. I think you have limit on google map watching. Use last develop version and use own api key
