### ISSUE TITLE
pip install -r requirements.txt

### ISSUE THREAD

**Issue by fragler** [AHAAAAAAA/PokemonGo-Map#994]
### Environment info
Operating System: Win10 64bit

Installed version of Python: Latest 2.7

### Steps to reproduce
1. Followed steps to install python
2. Followed steps to install pip
3. Shift + Right clicking in the pokemongo-map-master folder to open command in directory
4. pip install -r requirements.txt into win cmd and get "'pip' in not recognized as an internal or external command, operable program or batch file."

### What have you tried?
1. I have tried opening the python cmd and os.chdir to the pokemongo-map-master folder and try pip install -r requirements.txt again, but get a syntax error with the ^ under 'install'

it seems like maybe i do not have pip installed? but i ran the get-pip.py provided in the zip file here.

**Comment by sykhro** [comment]
Refer to the wiki on how to install pip

**Comment by fragler** [comment]
ok i did. it seems to bbe the same file but i went ahead and ran it anyway. it flashes something i don't know what it says. is there a way to make thee cmd pause or add a press any key to close? just to confirm what the cmd is printing.

**Comment by tatarrr95** [comment]
Use .bat file in folder Easy Setup and feel fine

**Comment by fragler** [comment]
ok, i just did that also. the cmd flashes and i am unable to read anything done. but i still get the 'pip is not recognized message.
also i appreciate the fast responses. thank you!

**Comment by Tigershark2005** [comment]
When you install Python it asks about adding pip to your path environment variable. You want to enable that. This allows you to type pip at any command prompt and be able to run the program. I actually had this issue until I restarted my computer. Path variables occassionally need to be reread which happens on startup. Let me know if that works.

**Comment by fragler** [comment]
i have restarted my pc sinnce i thought that itt may have been needed. i do not recall seeing anyting asking about pip during python install, but i will reinstall python to verify that.

**Comment by RyanMBlue** [comment]
if you cant command-line pip, you can always do this instead:
>python -m pip install -r requirements.txt

**Comment by amckenna** [comment]
You need to make sure python is in your path. This may help you: https://www.reddit.com/r/pokemongodev/comments/4t80df/wip_pokemon_go_map_visualization_google_maps_view/d5feu2f

**Comment by neobithia** [comment]
Also, environment variables are not recursive by design, so please make sure you add an explicit path to your pip folder location.

**Comment by Tigershark2005** [comment]
@DerScreever The user is still having the issue?

**Comment by fragler** [comment]
i just read through how to add the path. i added those via setx path for python and pip and now it is working! thank you guys!
