### ISSUE TITLE
Wrong timezone on Heroku app on develop branch

### ISSUE THREAD

**Issue by smcyr** [AHAAAAAAA/PokemonGo-Map#995]
## Expected Behavior
I expect that the map show that the pokemons expire in the right time

## Current Behavior
All the pokemons show that they expired at 19:00.

## Possible Solution
I tried to set the config variable "TZ" in Heroku Config Vars, but it doesn't change anything. Perhaps take into consideration this variable in the code.

## Steps to Reproduce (for bugs)
1. Deploy the app to Heroku
2. Try the url of the app

## Context
I wanted to use Heroku to simplify deployment.

## Your Environment
* Version used: latest develop branch
* Environment name and version (e.g. Python 2.7): Heroku
* Operating System and version (desktop or mobile): Windows - Desktop

Thank you very much!

**Comment by RyanMBlue** [comment]
![capture](https://cloud.githubusercontent.com/assets/11836411/17034869/898e43fc-4f52-11e6-9b81-ff73f4ca7df5.JPG)

I am having the same issue, but in a command line run with my browser.

**Comment by smcyr** [comment]
I still have the problem even after restarting the dyno, clearing the browser cache and refreshing the url.

**Comment by smcyr** [comment]
It seems to be fixed now, thanks.
