### ISSUE TITLE
Touch map gestures not  working on Windows touchscreens

### ISSUE THREAD

**Issue by neobithia** [AHAAAAAAA/PokemonGo-Map#997]
## Expected Behavior
Touch map gestures like:

- Touch & drag
- Pinch to zoom

These touch gestures work on a touchscreen with http://maps.google.com in Chrome Version 51.0.2704.103 m (64-bit)

However, the same touch gestures don't work with GoMap.

## Current Behavior
Touch gestures not working

## Possible Solution
Some kind of overlay blocking touch events?

## Steps to Reproduce (for bugs)
1.  Run GoMap on a Windows Touchscreen
2. Touch and Drag
3. Pinch to zoom
4. It doesn't work
5. But, open another tab and try it with Google Maps and it works.

## Context
Navigating maps is easier with your fingers than a cursor.  Better UI.

## Your Environment
* Operating System: Windows 10 Pro, Version 1511, Build 10586.494
* Installed version of Python: 2.7.12
* Chrome Version 51.0.2704.103 m (64-bit)
* Inspiron 11 3000 Series 2-in-1

**Comment by JZ6** [comment]
theres an overlay in place
