### ISSUE TITLE
[Enhancement] Exact Location for Dev Branch

### ISSUE THREAD

**Issue by ImQuinton** [AHAAAAAAA/PokemonGo-Map#999]
On the stable branch you could add a line that says: <div>{lat} {lng}</div> in the example.py and that would display the cords for the given pokemon

So the for example the exmaple.py would like something like:

LABEL_TMPL = u'''
<div><b>{name}</b><span> - </span><small><a href='http://www.pokemon.com/us/pokedex/{id}' target='_blank' title='View in Pokedex'>#{id}</a></small></div>
<div>Disappears at - {disappear_time_formatted} <span class='label-countdown' disappears-at='{disappear_time}'></span></div>
<div><a href='https://www.google.com/maps/dir/Current+Location/{lat},{lng}' target='_blank' title='View in Maps'>Get Directions</a></div>
<div>{lat} {lng}</div>
'''

So when I moved to Dev. Branch I noticed you couldn't do that. I think adding the cords under the pokemon info box would be a great addition for the Dev. Branch.

**Comment by medghaim** [comment]
Closing this issue as it is outdated. If this issue still persists on the `develop` branch, please reopen a new issue and update the information therein to reflect the new changes.

Also, please be aware of the incredibly helpful and supportive community at: 
https://discordapp.com/invite/Kzp4yky
